### ISSUE TITLE
AppInsights drops first log

### ISSUE THREAD

**Issue by vw52** [microsoft/ApplicationInsights-dotnet#1016]
## Repro Steps
Deploy or restart Azure Web App with App Insights and some test log events or exceptions. We have this in our Global.asax App_Start

            TelemetryConfiguration.Active.TelemetryInitializers.Add(new InsightsInitializer(AppInsightsSettings.Instance)); // loads custom initialization parameters

            // The InstrumentationKey is set and TelemetryClient is created the first time the static Logger is called
            Logger.LogEvent("AppInisghts initialized"); // This logevent doesn't show up in logs
            
            TokenSettings.Initialize(appSettings); // other initialization step
            Logger.LogEvent("Token settings initialized"); // This one does
        }

##  Actual Behavior
The first logged event or exception never shows up in the ms.portal.azure.com, but we see the ones after that. Also putting a thread.wait() for 1 minute gets the first event to show up in the logs.

## Expected Behavior
All events/exceptions should be logged once the InstrumentationKey and TelementryClient are created.

## Version Info 
SDK Version : 2.8.1
.NET Version :	4.6.1					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Windows
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApps

**Comment by lmolkova** [comment]
@vw52 thanks for reporting this!

1. How AppInsights provider for logging is initialized? I.e how TelemetryClient is created and how/when instrumentation key is set?

2. Can you repro the same behavior with TelemetryClient?

3. Can you run the app in debug mode and check what appears in the debug output - AppInsigbhts dumps all telemetry items there. Can you find first message in the log? Does ikey appears at the beginning of the message or it's displayed as `unconfigured` there?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
