### ISSUE TITLE
Modules are ignored by TelemetryConfiguration.CreateFromConfiguration

### ISSUE THREAD

**Issue by mediawolf** [microsoft/ApplicationInsights-dotnet#1018]
I have multi-executable application where each executable may require a different configuration (specific modules, own performance counters). Thus I don't have ApplicationInsights.config in the application directory. Instead, I use TelemetryConfiguration.CreateFromConfiguration but it ignores modules defined in a provided configuration ([relevant change](https://github.com/Microsoft/ApplicationInsights-dotnet/pull/105)).

## Version Info 
SDK Version : 2.8.1
.NET Version : 4.7.1					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : VS
Hosting Info (IIS/Azure WebApps/ etc) :

**Comment by lmolkova** [comment]
Thanks for reporting this!
Do you pass configuration as a string to the `CreateFromConfiguration`?

It actually requires config file to be passed like:

`TelemetryConfiguration configuration = TelemetryConfiguration.CreateFromConfiguration(File.ReadAllText("C:\\ApplicationInsights.config"));`

**Comment by mediawolf** [comment]
Yes, that's exactly what I do.
The implementation of TelemetryConfiguration.CreateFromConfiguration calls:
`  TelemetryConfigurationFactory.Instance.Initialize(configuration, null, config);`
where second parameter is instance of TelemetryModules. As the result, the loading logic of a module list inside TelemetryConfigurationFactory.LoadProperties(…) is not triggered.
The only place, I found, which passes non-null value is getter of TelemetryConfiguration.Active property.

**Comment by mediawolf** [comment]
Probably API can be extended with public overrides that take client instance of TelemetryModules. API unit- and integration tests will benefit from that too.

**Comment by stanislav-poliakov** [comment]
It will be great to extend `TelemetryConfiguration.CreateFromConfiguration` with following signature:
```
public static TelemetryConfiguration CreateFromConfiguration(string config, bool setAsActive = false)
```
or make possibility to set any configuration to active. so `new TelemertyClient()` could use custom configuration

**Comment by stanislav-poliakov** [comment]
@lmolkova Could be have possibility to change `ApplicationInsights.config` to smth else and `new TelemetryClient()` should load new one
