### ISSUE TITLE
PathTooLongException attempting to restore Nuget reference microsoft.applicationinsights.azurewebsites.

### ISSUE THREAD

**Issue by MattGal** [microsoft/ApplicationInsights-dotnet#1019]
## Repro Steps
1.  From a desktop app and a user with a 7-character name (say, MattGal) reference the 2.6.5 version of the nupkg with default settings
2.  Try to restore this solution

##  Actual Behavior

Dies due to a PathTooLongException while trying to write to C:\Users\xxxxxxx \.nuget\packages\microsoft.applicationinsights.azurewebsites\2.6.5\content\2.6.5\core\store\x64\netcoreapp2.0\microsoft.extensions.configuration.environmentvariables\2.0.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.EnvironmentVariables.dll
(shrewd observers will note that this is 265 characters, 5 morethan 260
## Expected Behavior

NuPkg is capable of actually being restored

## Version Info 
SDK Version : 2.6.5 (it's hilarious because this is how long of a path it's trying to make!)
.NET Version : 4.7.2	 						
How Application was onboarded with SDK(**VisualStudio**/StatusMonitor/Azure Extension) :
OS : Windows 10 Client RS4
Hosting Info (IIS/Azure WebApps/ etc) : N/A

**Comment by pharring** [comment]
That Nuget package is a site extension for Azure App Services. It isn't meant to be referenced from code.
What are you trying to do?
Are you perhaps looking for a different nuget package? Microsoft.ApplicationInsights.WindowsServer?

**Comment by MattGal** [comment]
Interesting, although I don't get why that makes Max path not happen.  I was trying to follow some examples that used AzureRoleEnvironmentTelemetryInitializer and I absolutely couldn't find the type.  Feel free to close, I gave up on that path anyways, I just thought this was a bad practice for nupkg formatting.
