### ISSUE TITLE
Do not allow to send a NaN and +- infinity as a value of measurments

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#102]
DC wouldn't accept measurements when it is set to NaN.

...On second though maybe we need to make DC accept it as it's unclear how to tell that the metric is bad... It's better to send it than to throw exception or send zero instead.

**Comment by SergeyKanzhelev** [comment]
Converted to the bug as Breeze do not allow NaN and Infinity any longer. Need to send zeroes instead. @abaranch can we take it for stable 2.0?

**Comment by abaranch** [comment]
Sure
