### ISSUE TITLE
Synchronous wrapping of asynchronous code

### ISSUE THREAD

**Issue by dennisbappert** [microsoft/ApplicationInsights-dotnet#1026]
The AI codebase uses several synchronous wrappers for async code and exposes those APIs.
All flavors of Task.Wait, Task.WaitAll, GetAwaiter().GetResult(), .Result, etc.

## Repro Steps
1. Take a ASP.NET Core web application (no SynchronizationContext)
2. Use Application Insights
3. Put very high load on the application

##  Actual Behavior
Massive ThreadPool starvation until the application stops responding at all.

## Expected Behavior
No ThreadPool starvation.

## Version Info 
SDK Version : any
.NET Version : ASP.NET Core	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : any
Hosting Info (IIS/Azure WebApps/ etc) : any

**Comment by macrogreg** [comment]
@dennisbappert : Does this repro without using the Nito.AsyncEx library?

**Comment by dennisbappert** [comment]
Yes it does.

**Comment by pharring** [comment]
Do we have a self-contained repro? One where the app runs successfully until Application Insights is added?
If so, could we get a dump of the process at the point of "massive ThreadPool starvation"? From that we should be able to see where the tasks are blocked.
