### ISSUE TITLE
Internal Bug: EventSourceException: LogVerbose and NullRefEx

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1029]
This seems to have been introduced in the 2.8 milestone.

`AI (Internal): [Microsoft-ApplicationInsights-Core] EventSourceException while processing event "LogVerbose": System.NullReferenceException:Object reference not set to an instance of an object.`

Ideally can get this fixed in the 2.9 milestone.

**Comment by Dzoukr** [comment]
Any update on this?

**Comment by TimothyMothra** [comment]
Hi @Dzoukr, I wasn't aware this was still an issue.
Do you by any chance have a stack trace?

**Comment by Dzoukr** [comment]
Oh, sorry, I mixed errors, my fault. I got

```  
AI (Internal): [Microsoft-ApplicationInsights-Data] ERROR: Exception in Command Processing for EventSource Microsoft-ApplicationInsights-Data: 
An instance of EventSource with Guid XXX already exists.
```

But this is obviously different one. Sorry again. :(

**Comment by TimothyMothra** [comment]
No worries, it looks like we should have closed this issue a year ago. :)

Regarding the new error you quoted, I've seen that when customers try to have two versions of the SDK in the same process. 
Can you tell me a little bit more about how you set up Application Insights in your application? 
Or feel free to create a new issue, we have a questionnaire that helps us get started investigating.

**Comment by Dzoukr** [comment]
Yes, I can tell you more. I am trying to create own `TelemetryClient` on Startup of functions host. It is mainly because of this issue: https://github.com/Azure/azure-functions-host/issues/5353

**Comment by TimothyMothra** [comment]
Okay that makes more sense. 
Because Azure Functions comes with the SDK already configured, creating your own TelemetryClient can cause the duplicate SDK issue. ("an instance already exists").

Can you please try the code sample here and let me know if this works:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-and-later-2
This uses dependency injection to grab the same configuration in use by Functions to create your own TelemetryClient.
I would expect this to work without issue.

**Comment by Dzoukr** [comment]
But that's the issue. I am on v3 and dependecy injection of TelemetryConfiguration into constructor does not work. That's what I tried to work around and endup here. :)

**Comment by TimothyMothra** [comment]
@Dzoukr gotcha. can you please tell me the version number of the SDK referenced by your application? 

Sometimes version mismatches between customer applications & Functions can cause "weirdness". 
Looking at their NuGet, looking at their dependencies on our SDK...
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/
It appears that they are on AspNetCore v2.8/ Base v2.11. (We unified our version numbers starting with v2.12).

I would recommend using the same versions as they are.
- https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.8.0

@lmolkova can you confirm that my recommendation is correct? Is there someone on the Functions team that could help investigate this?

**Comment by Dzoukr** [comment]
@TimothyMothra thanks for helping me, really appreciate it!

Here are the versions of packages:

```
Microsoft.NET.Sdk.Functions (3.0.3)
Microsoft.Azure.WebJobs.Logging.ApplicationInsights (3.0.14)
```

and from local tools:

```
Azure Functions Core Tools (3.0.2106 Commit hash: 5431fca4f603bf9446d7dd2d5f96a43b5f69b5cb)
Function Runtime Version: 3.0.13107
```

**Comment by TimothyMothra** [comment]
@Dzoukr does your application have any direct dependencies on Microsoft.ApplicationInsights ?

**Comment by TimothyMothra** [comment]
Oh, apparently this might be related to an ongoing issue with Functions v3.
https://github.com/Azure/azure-functions-host/pull/5551
You actually linked to this earlier but I missed the connection.

Reading through their comments, they have several fixes and they've already started their release process but I don't know their ETA.


Are you able to wait for their update?
If you can't wait, is downgrading to Functions v2 an option for you?

**Comment by Dzoukr** [comment]
@TimothyMothra I can wait, no problem with that.

Thanks again for helping me even I got here with different error. :smile:
