### ISSUE TITLE
Supportability: Introduce a diagnostics api

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1030]
**Proposal**

Add a new api to TelemetryClient: `public void PrintDiagnostics(string fileName)`.

Customers would be able to call this method at suspected points of failure within their application.
Api would serialize key runtime objects to a text file to send to us for support cases. (ex: TelemetryClient, TelemetryConfiguration, TelemetryChannel, ...)

Not all customers use a static TelemetryClient, so adding this to the TelemetryClient class ensures we get the exact pipeline affecting customers.

**Advantages**:
- We wouldn't need to rely on a user to tell us how they've configured Application Insights. We could dump all the internals to file and inspect ourselves. This would eliminate guesswork and frustration.
- For customers not utilizing an `applicationInsights.config` we could see the full runtime configuration.

**Risks:**
- may contain private user data. should we encrypt this file?
- because this needs access to internal classes, we MUST add this to BaseSDK. Wouldn't be able to support older versions.

**Comment by MS-TimothyMothra** [comment]
@Dmitry-Matveev @SergeyKanzhelev @cijothomas @lmolkova 
is this too crazy to work? :)

**Comment by MS-TimothyMothra** [comment]
@cijothomas I like this as an extension of our existing EventSource logging. And it would simplify the troubleshooting scenario of users required to install a new executable (PerfView) which first has to be precisely configured before it can capture useful logs.

I'm trying to solve a different scenario where the user has an incorrect configuration. If our troubleshooting is configuration dependent then we are effectively blocked. I think this is a scenario that we need to invest in: how to troubleshoot an invalid configuration at runtime.

We can request users send us their config file, but often customers have made different configurations in code, or entirely in code. 

- First, asking customers to share this code is rarely helpful. 
- Second, even if they've configured a static TelemetryClient correctly, if they use a new TelemetryClient object that may use a different configuration which is difficult today to diagnose. 
- Third, a configuration may not be fully loaded at AppStart time. So being able to dump all internals at a specific point in time on a specific TelemetryClient object may be useful. Alternatively we could investigate working with the Snapshot debugger to capture objects in memory. However if this is also configuration dependent we'll have the same problem.

**Comment by dhaval24** [comment]
@cijothomas I agree that there should be a good file writer for diagnostic logs.  However, to detect configuration issues effectively, you would probably need to effectively use a logger which is configured outside AI. Commonly in Java world people use [SLF4J (this is a facade for logging)](https://www.slf4j.org) and the user provides the actual implementation. In this case when the configuration parsing happens, we still get the logs when parsing fails due to some illegal config file.  Is there something similar to SLF4J in .NET which you can rely on?
