### ISSUE TITLE
Logging SQL queries

### ISSUE THREAD

**Issue by Leon99** [microsoft/ApplicationInsights-dotnet#1034]
I need to collect SQL queries for an ASP.NET app hosted as an Azure App Service. I managed to learn (it wasn't particularly easy/pleasant experience BTW) that I need to install the site extension, which now doesn't appear along all other extensions but can be installed by a dedicated button (BTW how about fixing the terminology - if it's a site extension, put it in the list with others, otherwise - don't call it an extension).

However, I don't want to do it manually for multiple app services, I want to adjust my Terraform specs accordingly instead. I couldn't find a proper way to do it programmatically.

What I noticed, however, is if I just add application settings that the **Turn on site extension** adds, the SQL gets logged. Now the question is - if adding certain application settings is all it takes, why not just do it by default or allow it via code, without the need to add all those settings that only seem to hold version information (why are they needed at all)?

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
