### ISSUE TITLE
Log messages in application insights in .net framework 4.6.1

### ISSUE THREAD

**Issue by ashwineev** [Microsoft/ApplicationInsights-dotnet#1053]
I have created a console application targeting .net framework 4.6.1
In program.cs I have written below code:-

```
       TelemetryConfiguration.Active.InstrumentationKey = CloudConfigurationManager.GetSetting("InstrumentationKey");
            log4net.Config.XmlConfigurator.Configure();
            var logger = LogManager.GetLogger(nameof(GraphDeltaJobFw2));
log.Error("webjob started");
```
In the app.config
```
  <configSections>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net"/>
  </configSections>
  <log4net>
    <root>
      <level value="ALL"/>
      <appender-ref ref="aiAppender"/>
      <appender-ref ref="ConsoleAppender"/>
    </root>
    
    <appender name="ConsoleAppender" type="log4net.Appender.ConsoleAppender">
      <param name="Threshold" value="INFO"/>
      <layout type="log4net.Layout.PatternLayout">
        <param name="ConversionPattern" value="%d [%t] %-5p %c [%x] - %m%n"/>
      </layout>
    </appender>
    <appender name="aiAppender" type="Microsoft.ApplicationInsights.Log4NetAppender.ApplicationInsightsAppender, Microsoft.ApplicationInsights.Log4NetAppender">
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%message%newline"/>
      </layout>
    </appender>
  </log4net>
```
I have added nuget reference Microsoft.ApplicationInsights.Log4NetAppender
In assembly info addded [assembly: log4net.Config.XmlConfigurator(Watch = true)]
when I run the web job I can see the console message "webjob started".But I do not see the message in application insight.

Is any step missing this?

**Comment by joseclament** [comment]
You need to specify the Application Insight key value in ur log4net config file. 
`  
<appender name="aiAppender" type="Microsoft.ApplicationInsights.Log4NetAppender.ApplicationInsightsAppender, Microsoft.ApplicationInsights.Log4NetAppender">
  <InstrumentationKey name="AppInsightsKey" value="xxxxxx-xxx-x--x-x" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%message%newline"/>
      </layout>
    </appender> 
`
