### ISSUE TITLE
Expose setting that allows to disable sending AI internal SDK error

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1056]
Sometimes we send too many 'AI Internal' errors (like in case of https://github.com/Microsoft/ApplicationInsights-dotnet/issues/973). This usually indicates an issue within SDK and provides a piece of useful information for AI developers.

However, customers should be able to disable it to avoid extra noise and costs associated with it.

**Comment by SergeyKanzhelev** [comment]
Do you have a suggestion on how this API may look like?

**Comment by MS-TimothyMothra** [comment]
I think a root level setting on `TelemetryConfiguration` would work. 
```
public bool OptOutInternalErrors { get; set }
```
This would default to false, but allow users to set to true.

I belive this would be the only class affected:
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/d2601a387323d82e6ac2956be1e36c4cbed0615f/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/PortalDiagnosticsSender.cs#L8-L11

**Comment by cijothomas** [comment]
Allow severity of "Disabled" on this to Disable SDK's DiagnosticsTelemetryModule.
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/d2601a387323d82e6ac2956be1e36c4cbed0615f/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs#L113
