### ISSUE TITLE
Move FileDiagnosticsTelemetryModule to Base SDK

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1059]
Proposing to move the FileDiagnosticModule to base sdk rather than in hosting startup.
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/HostingStartup/HostingStartup/FileDiagnosticsTelemetryModule.cs

This will make it easy for customers to collect full SDK traces as needed for detailed investigation purposes.

**TODO**
- Move FileDiagnosticsTelemetryModule to Base sdk (blocked on #1160)
- Introduce Environment Variable "ApplicationInsights_DiagnosticMode". This allows customers to enable without re-deploying their application.
- Introduce TelemetryConfiguration Boolean Variable "DiagnosticMode". This allows customers who may have multiple apps deployed per machine, or if they do not have access to EnVar.
- TelemetryConfigurationFactory should evaluate both config and environment variables.
- TelemetryConfigurationFactory should emit an ETW trace to confirm that this has been enabled.

**Comment by cijothomas** [comment]
Also proposing to control the logging purely via ENV variables.

**Comment by Dmitry-Matveev** [comment]
It would make sense to move it out of hosting startup Nuget package to ease the diagnostics experience for our customers and support engineers.
Environment variables can be good in non-shared environments, is there an environment (e.g. functions/jobs/service fabric/multi-pool IIS) where setting environment variable may affect many apps at the same time? Do you propose to have a different instruction set per environment then to handle the differences?

**Comment by cijothomas** [comment]
Thanks for sharing comments. I intend to do first part only now.
ENV variable based control needs further investigation, esp. in shared environments. (but we already have this issue with ikey)

**Comment by SergeyKanzhelev** [comment]
Sounds good. Try to make it as generic as possible so people can configure things like rotation of log files and such. Also allow log file path be configured from env vars.

**Comment by SergeyKanzhelev** [comment]
AI.config -based enablement would work as starting point just fine.

**Comment by TimothyMothra** [comment]
This task is dependent on #1160
