### ISSUE TITLE
Improve channel performance by serializing telemetry directly to stream to be used in Transmission

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1063]
The JsonSerializer used to serialize Telemetry currently uses a MemoryStream to write serialized data to. This is then converted to a byte[], and stored inside Transmission.
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/Extensibility/Implementation/JsonSerializer.cs#L64

This byte[] is then converted again to a new MemoryStream, for writing to network.
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L165

Proposing to avoid this conversions back and forth - modify JsonSerializer to write to just a MemoryStream and modify Transmission to use the same stream to write to network. This should avoid unwanted memory allocations/GC  etc and boost performance.

**Comment by johnib** [comment]
@cijothomas , based on the milestones mentioned above, can we assume that v2.14 already fixes that? Thanks

**Comment by cijothomas** [comment]
The milestone for this is "Future", means this is not done.

**Comment by msvinth** [comment]
This also leads to GC pressure when used in server applications. We are currently going through a process of optimising memory allocations to reduces numbers of GCs and are now at the point that all our own memory allocations are dwarfed by Application Insights allocations. Some screen shots from JetBrains dotMemory. This is after just writing like 100 events.

System.Byte[] allocations:
![image](https://user-images.githubusercontent.com/22496844/141627778-da8d01ee-c61b-4c3e-9e5b-b657324bafc6.png)
![image](https://user-images.githubusercontent.com/22496844/141628456-83a9ead0-5e7c-4cf6-8be4-11b119524c9b.png)
![image](https://user-images.githubusercontent.com/22496844/141631768-0627c33b-e7da-46ec-a9d5-e1ce9915864d.png)


System.Char[] allocations:
![image](https://user-images.githubusercontent.com/22496844/141629661-55ac39e5-e09a-4e83-9783-8ea52dfb3196.png)

**Comment by TrayanZapryanov** [comment]
Looks like links are broken, but the usage of MemoryStream is still there.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/19a3ecf77bebd7bbcffb6ca553b920016a412ed4/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/JsonSerializer.cs#L53

https://github.com/microsoft/ApplicationInsights-dotnet/blob/19a3ecf77bebd7bbcffb6ca553b920016a412ed4/BASE/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L175

Should I try to fix this ?
