### ISSUE TITLE
Exception serialization does not handler Empty exception message.

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1066]
Oringally reported:https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/823
Application Insights Rejecting Exceptions with empty Message

Repro:
 TelemetryClient tc = new TelemetryClient();
            tc.Context.InstrumentationKey = "validikey";
            tc.TrackException(new Exception(""));
            tc.Flush();

Response from backend:
 Field 'message' on type 'ExceptionDetails' is required but missing or empty. Expected: string, Actual: undefined

// The following gets mesage automatically populated, but passing "" or string.empty breaks it.
var ex = new Exception();
tc.TrackException(ex); 

Fix would be to modify Exception sanitization to handle this properly.

**Comment by kristofferjalen** [comment]
This bug is still there.

**Comment by NeilMountford** [comment]
This is still an issue, I've created a PR with a unit test: #2857 that will hopefully solve it.
