### ISSUE TITLE
WPF application not terminating when using v2.9.0-beta3 or newer

### ISSUE THREAD

**Issue by IGx89** [Microsoft/ApplicationInsights-dotnet#1080]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Open Visual Studio and create a new WPF application
2. Add the "Microsoft.ApplicationInsights.WindowsServer" NuGet package, v2.9.0-beta3 or v2.9.0 (final)
3. Add the following line into MainWindow's constructor: `TelemetryConfiguration.Active.InstrumentationKey = "";` (per instructions on https://docs.microsoft.com/en-us/azure/azure-monitor/app/windows-services#4-send-telemetry)
4. Press F5 to start the application, then exit it by clicking the "X" on the application window

##  Actual Behavior
Window closes but application doesn't terminate.

## Expected Behavior
Application fully terminates.

## Version Info 
SDK Version : 2.9.0 beta 3 or newer (beta 2 or older, like v2.8.1, don't have this issue)
.NET Version : 4.7.2
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10 1803
Hosting Info (IIS/Azure WebApps/ etc) : N/A

**Comment by IGx89** [comment]
Best guess is that this was caused by #1028, which creates a new non-background thread. Since the thread isn't set as Background and apparently isn't being terminated by the code, the application can't fully terminate.

CC @macrogreg

**Comment by IGx89** [comment]
I also attempted adding `TelemetryConfiguration.Active.Dispose();` to Application_Exit, with no luck either.

**Comment by Dmitry-Matveev** [comment]
@IGx89 , thanks a lot for catching this. PR #1081 is to address this issue.

**Comment by Dmitry-Matveev** [comment]
@IGx89 , we shipped 2.9.1 stable with the fix. Thanks again for reporting!

**Comment by IGx89** [comment]
Thanks a lot!
