### ISSUE TITLE
Provide a timeout for TelemetryClient.Flush

### ISSUE THREAD

**Issue by yufeih** [microsoft/ApplicationInsights-dotnet#1088]
#264 adds timeout for `InMemoryChannel`, it would be very handy to also provide a timeout for `TelemetryClient.Flush`

**Comment by paulomorgado** [comment]
Or add a `CancellationToken`.

**Comment by MS-TimothyMothra** [comment]
I'm doing this in my project using `InMemoryChannel`:

```
private static void FlushAndWait(this TelemetryClient telemetryClient)
     => Task.Run(() => telemetryClient.Flush()).Wait(TimeSpan.FromSeconds(5));
```

**Comment by paulomorgado** [comment]
@MS-TimothyMothra, that only times out the `Wait`. not the `Run`-
