### ISSUE TITLE
InMemoryChannel causes lock contention

### ISSUE THREAD

**Issue by ionsphere** [microsoft/ApplicationInsights-dotnet#1090]
## Repro Steps
1. In a Unit test, create a TelemetryClient
2. Launch 400 threads
3. In each thread call TelemetryClient.Track 250 times
4. Profile the behavior

It will total with 100,000 calls and a possible runtime of 8-10 seconds. Just increase 250 to 2500 if you want a better profiling picture.

A comparable library which internally uses ETW to pipe the events is running 10 times faster with no locking. Even when having a "BatchBlock-ActionBlock pipe from TPL DataFlow writing on local disk with SemaphoreSlim-lock only in ActionBlock" runs 60 times faster (of course, locking each thread to write to disk runs slower).

##  Actual Behavior
65% is spent in Lock contention. 27% is due to GC Wait lock. All the rest 38% is actual locking.

Only 7% of time is spent in OnBufferFull handler - the test is not blasting too heavy with events.

Such heavy locking gets strongest impacts on the ThreadPool as all our code is asynchronous with Tasks, but if a Task locks, then it cannot release a thread and causes either thread starvation or thread pool growth which is already a CPU starvation. Eventually machine peaks at 100% CPU and unable to respond to actual HTTP calls.

## Expected Behavior
No locking on threads sourcing the events.

## Version Info
Library Version: Microsoft.ApplicationInsights 2.9.1
.NET Version: 4.7.2

## Details
With high load applications the implementation of TelemetryBuffer becomes the bottleneck, that slows down all requests and causes high latency.

The reason behind having that many calls is because property dictionaries in those cases are different and cannot be just aggregated into a single Metric. All those properties are used as custom dimensions for search. There are 20 properties, each can have somewhere between 5 to 100 different values.

Possible options:

1. Allow custom implementation of TelemetryBuffer. Testing shows that using TPL Dataflow to post events and then process them in a single Task (ActionBlock with parallelism 1) improves performance. Of course, standard implementation should not rely on yet another heavy library, but having the possibility to override just one class for our narrow use case can be beneficial. Current implementation does not allow such extensibility as InMemoryTransmitter requires exactly TelemetryBuffer class and not an interface and anyway all those classes are internal except InMemoryChannel's default constructor, which hints a requirement to reimplement the whole ITelemetryChannel.

2. Provide interface with batching support of an IEnumerable with, say, ITelemetry. There is a similar support with TrackEvent where for the same properties it is possible to send multiple metrics. Having similar interface but for different property sets could allow having a lock just once instead of N-times. Aggregation into a batch will be done in caller's code, not in library.

3. Provide ETW-version of TelemetryClient to send events into asynchronous pipe. Sadly, right now TelemetryClient implements no interfaces and is sealed, meaning a lot of work to cut it out for another implementation.

4. Provide asynchronous version of TelemetryClient or just add Track***Async which must use at most Task-friendly SemaphoreSlim to maintain a lock.

**Comment by ionsphere** [comment]
May relate to issues in #1026

**Comment by ionsphere** [comment]
May relate to issues in #895

**Comment by ionsphere** [comment]
![Performance Profiler scoped to Microsoft.ApplicationInsights.TelemetryClient.Track](https://user-images.githubusercontent.com/2500945/53295223-a6ddcd80-37ab-11e9-9aba-6157411a8f9b.png)

**Comment by cijothomas** [comment]
Thanks for the detailed post. Could you share the repro app you are using? I typically use something similar to the one here: https://github.com/Microsoft/ApplicationInsights-dotnet/tree/cithomas/perfapp/Test/PerfTest

Would be great if you can share the repro app and we'll see what perf improvements can be done here.

**Comment by cijothomas** [comment]
Main reason to get repro code is to make sure that no obvious error in the way SDK is used.!

**Comment by ionsphere** [comment]
I've created a gist of my unit tests: https://gist.github.com/ionsphere/bf2af2bba9047e0dde04a981b5a58c1c

There are two tests:
- AppInsightsMetricTrackValueIsolatedTest - testing calls to GetMetric(...).TrackValue(...)
- AppInsightsMetricTrackTraceIsolatedTest - testing calls to TrackTrace(...)

The performance difference of the two tests fluctuates. For GetMetric it is stable and always shows 200+ events per millisecond. But for TrackTrace it was up to 100 events per millisecond but also down to 15 events per millisecond. That means TrackTrace usage should be minimized, or the implementation changed.

Notice: running those tests took 2.5 minutes on my box.

Profile shows that for TrackTrace timeline 22% is spent in System code, 43% in Lock contention, 10% in GC wait, 13% in CPU wait.
Quite noticeable time was spent in CopyDictionary (16%).
But still main time was contributed by TelemetryBuffer.Enqueue (72%).

To compare TrackValue has 22% spent in System code, 21% in GC wait, 42% in CPU wait.
While 18% of time was spent in TryGetDataSeries, main time was in BuildPointMoniker (63%).
