### ISSUE TITLE
Unexpected behavior in .net core console application vs .net framework console application

### ISSUE THREAD

**Issue by woutervs** [Microsoft/ApplicationInsights-dotnet#1092]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create 3 projects, A .net core console application B .net framework console application C TelemetryExtensions project

2. Create a telemetry processor in C eg.:

```
    public class AugmentTelemetryWithApplicationIdentifier : ITelemetryProcessor
    {
        private readonly ITelemetryProcessor next;

        public AugmentTelemetryWithApplicationIdentifier(ITelemetryProcessor next)
        {
            this.next = next;
        }

        public void Process(ITelemetry item)
        {
            item.Context.GlobalProperties["ApplicationIdentifier"] = Assembly.GetEntryAssembly().FullName;
            next.Process(item);
        }
    }
```

Create in both A & B a ApplicationInsights.config file contents:

```
<?xml version="1.0" encoding="utf-8" ?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
  <TelemetryProcessors>
    <Add Type="Xynaps.TelemetryExtensions.AugmentTelemetryWithExceptionPropertiesProcessor, Xynaps.TelemetryExtensions"></Add>
    <Add Type="Xynaps.TelemetryExtensions.AugmentTelemetryWithApplicationIdentifier, Xynaps.TelemetryExtensions"></Add>
  </TelemetryProcessors>
</ApplicationInsights>
```

3. Set the following code in the static void Main in both A & B

```
            var client = new TelemetryClient();
            client.TrackTrace("Hello World.");
            Console.ReadLine();
```

##  Actual Behavior
In A a log is written without the augmented property from the processor
In B a log is written with the augmented property from the processor

## Expected Behavior
In A a log should have been written with the augmented property from the processor

## Notable remarks
* In a .net core console app when no ApplicationInsights.config is available not a single log is written.
When a ApplicationInsights.config is available and it's empty but the processors are added likeso:

            TelemetryConfiguration.Active.TelemetryProcessorChainBuilder.Use(next => new AugmentTelemetryWithApplicationIdentifier(next))
                .Build();
Behavior is as expected.
Though when no ApplicationInsights.config is available and the above code to add a processor is used not a single log is written.

* With log I mean telemetryClient.TrackTrace("Something") for example.

## Version Info 
SDK Version : 2.9.1
.NET Version :	.NET Core 2.2 vs .NET Framework 4.7.2 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Local development

**Comment by cijothomas** [comment]
@woutervs .net core apps don't read from applicationinsights.config. So only way to modify settings is to do it programatically.https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started-for-a-.NET-Core-console-application

**Comment by woutervs** [comment]
Fair enough, though that doesn't explain why the "ApplicationInsights.config" file has to be present otherwise nothing gets logged.

**Comment by cijothomas** [comment]
Sorry I don't get it.  what do you mean by "ApplicationInsights.config" **has** to be present?

**Comment by woutervs** [comment]
Nvm I tried that scenario a couple of times with and without the 'ApplicationInsights.config' file present and it seems to work in a .NET core solution regardless.

Though in a .NETFramework the file has to be available for logs to occur.

**Comment by cijothomas** [comment]
'ApplicationInsights.config' is optional even in .NET Framework. Everything can be configured in code.

**Comment by woutervs** [comment]
```
    public class Program
    {
        private static void Main(string[] args)
        {
            var client = new TelemetryClient();
            client.TrackTrace("Hello world. 564");
            Console.ReadLine();
        }
    }
```

Works in .NET Core
Doesn't work in .NETFramework 4.7.2
Both projects only have Microsoft.ApplicationInsights 2.9.1 as package.

**Comment by lmolkova** [comment]
`TelemetryClient()` instantiates TelemetryConfiguration.Active, that by default on .NET Framework reads ApplicationInsights.config. It does not happen on .NET Core - config is not supported there. This is by design.

**Comment by woutervs** [comment]
> `TelemetryClient()` instantiates `TelemetryConfiguration.Active`, that, by default on .NET Framework reads ApplicationInsights.config. It does not happen on .NET Core - config is not supported there. This is by design.
> 
> Please follow https://docs.microsoft.com/bs-latn-ba/azure/azure-monitor/app/console.
> On .NET Core we do NOT recommend using `TelemetryConfiguration.Active` singleton and suggest that you create configuration instance.

Okay we already established that .NET Core doesn't need the .config file, even if it's there it's ignored.
What I'd like to know now is why that behavior is different for .NET Framework all good that .NET Framework can read the .config file. But apparently it doesn't work at all if the config file isn't there.

If that's by design that's a very strange design choice in my humble opinion.
At least let it work without the .config file as well then.

**Comment by cijothomas** [comment]
Re-iterating this:
'ApplicationInsights.config' is **optional** even in .NET Framework. Everything can be configured in code.

**Comment by lmolkova** [comment]
.NET core  promotes using DI pattern for configuration and xml files are certainly not a .NET core way for configuration.

what does not work well without config on .NET Core? I assume you miss the ikey - you can put it in the APPINSIGHTS_INSTRUMENTATIONKEY env var or set it explicitly in the code (on  the TelemetryConfiguration instace you created).

**Comment by woutervs** [comment]
Then why doesn't my code example work without the applicationinsights.config file present in .NET Framework?

**Comment by woutervs** [comment]
> .NET core promotes using DI pattern for configuration and xml files are certainly not a .NET core way for configuration.
> 
> what does not work well without config on .NET Core? I assume you miss the ikey - you can put it in the APPINSIGHTS_INSTRUMENTATIONKEY env var or set it explicitly in the code (on the TelemetryConfiguration instace you created).

Like I said before, everything works fine in .NET Core I changed my code accordingly, the problem is in .NET Framework

**Comment by lmolkova** [comment]
So could you describe what is the problem you observe on .NET Fx with and without config?

**Comment by woutervs** [comment]
With the  .config file when telemetryClient.TrackTrace("Hello World"); is called you can find the log back whilst debugging in visual studio. Without the .config file present there is nog log whilst debugging.

**Comment by woutervs** [comment]
In a dotnet core 2.2 application with application insights package 2.11.0
Without an empty ApplicationInsights.config there is no logging whilst debugging in visual studio 2019 preview (latest version)
Logging is visible when the applicationinsights.config file is available.

DI setup:

```
            builder.RegisterType<TelemetryClient>().AsSelf();
            builder.Register(context =>
            {
                var configuration = context.Resolve<IConfiguration>();
                var telemetryConfiguration = new TelemetryConfiguration();
                var instrumentationKey = configuration["APPINSIGHTS_INSTRUMENTATIONKEY"];
                if (!string.IsNullOrWhiteSpace(instrumentationKey))
                {
                    telemetryConfiguration.InstrumentationKey = instrumentationKey;
                }
                telemetryConfiguration.TelemetryProcessorChainBuilder
                    .Use(next => new AugmentTelemetryWithApplicationIdentifier(next))
                    .Use(next => new AugmentTelemetryWithExceptionPropertiesProcessor(next))
                    .Build();

                //Could add processors/sinks here...
                return telemetryConfiguration;
            }).SingleInstance();
```

Then resolve using

var client = container.Resolve<TelemetryClient>();

Am I doing my DI registration wrong somehow that I still need the applicationinsights.config file to see traces whilst debugging?
