### ISSUE TITLE
what's the usage of method TrackAvailability()?

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-dotnet#1096]
I want to know in which case I should use TrackAvailability().

As per my understanding, this method is used to check the web availability, right?
and if so, I can add some properties in the method, then check in the azure portal to see if I can receive the properties, then determine if the web is available.

If I'm correct, then I think we can also use other methods like TrackEvent() etc. which can also send some custom info, then we can check it in azure portal.

**Comment by MS-TimothyMothra** [comment]
It's meant to work with this feature in the portal: https://docs.microsoft.com/azure/azure-monitor/app/monitor-web-app-availability

**Comment by dalibormesaric** [comment]
Is it possible that TrackAvailability() creates new Availability Test that would go under Overall? Related to the screenshots from the url you provided @TimothyMothra

**Comment by PeterOrneholm** [comment]
+1 one the question from @dalibormesaric. I'm using `TrackAvailability()` from my package https://github.com/PeterOrneholm/Orneholm.ApplicationInsights . It works as expected, but it dows not show up as a test in the list in the portal. Do I need to set some special property for it to show up there?
