### ISSUE TITLE
Deactivate adaptive sampling for Exceptions

### ISSUE THREAD

**Issue by drauch** [microsoft/ApplicationInsights-dotnet#1097]
We have the following ApplicationInsights.config:

```
<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
	<MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
	<ExcludedTypes>Event;Exception</ExcludedTypes>
</Add>
<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
	<MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
	<IncludedTypes>Event</IncludedTypes>
</Add>
```

According to https://github.com/Microsoft/ApplicationInsights-dotnet/issues/743 this means:

* Sample everything except Event/Exception, using 5 items/sec as the upper limit
* Sample Events, also using 5 items/sec as the upper limit (has its own rule, so the 5 items/sec applies to events only)

But for Exceptions it looks like it uses some kind of default value now instead of "no sampling at all". How to configure "no sampling for Exceptions"?

**Comment by Dmitry-Matveev** [comment]
This sounds like a bug, the configuration you have is supposed to ingore exceptions in the sampling.

To workaround, you can use [Telemetry Initializer](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#add-properties-itelemetryinitializer) that sets Sampling Rate to 100 on Exception Telemetry items:
```
    public class MyTi : ITelemetryInitializer
    {
        public string MyProp { get; set; }
        public void Initialize(ITelemetry telemetry)
        {
            if (telemetry is ExceptionTelemetry && telemetry is ISupportSampling supportSampling)
            {
                supportSampling.SamplingPercentage = 100;
            }
        }
    }
```
You'd need to register this initializer in ApplicationInsights.config file or via code:
`<Add Type="Namespace.MyTi, AssemblyName">`

**Comment by drauch** [comment]
Thank you for your reply! I need to check back whether it's really a bug or whether I made a mistake on my part. Sorry for any inconveniences.
