### ISSUE TITLE
Need a consistent way to specify proxy server

### ISSUE THREAD

**Issue by reyang** [microsoft/ApplicationInsights-dotnet#1105]
Today the Application Insights SDKs rely on the underlying platform/system proxy settings, which varies by the system and runtime you are running on, and the programming language you use.

This is a feature ask to provide a consistent way to specify proxy server while sending telemetry data. It could be environment variable, configuration file or coded approach as long as there is a consistency.

**Comment by MS-TimothyMothra** [comment]
Sharing for context.
We have some minor documentation here:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/troubleshoot-faq#can-i-monitor-an-intranet-web-server
