### ISSUE TITLE
Metric dimension not shown in Azure Application Insights (portal)?

### ISSUE THREAD

**Issue by jdvor** [Microsoft/ApplicationInsights-dotnet#1117]
tag: Question

Where the metric dimension should be visible in Azure Application Insights (portal)?

Test:
```
.GetMetric("tc_counter_two", "apples").TrackValue(rnd.Next(1, 4));
.GetMetric("tc_counter_two", "pears").TrackValue(1);
```

Every minute (default aggregation interval) the portal shows two records for metric **tc_counter_two** with stats (sum, min, max, stddev) correctly corresponding to what's being tracked in code above. However the dimension - **apples / pears** in this case - is nowhere to be seen in the records.
The result is you can't really tell them apart.

Maybe it is a bug (it seems to me it is) or at best enhancement. If so, should I report it here?

**Comment by cijothomas** [comment]
@jdvor I guess this must be a UI issue, Let me confirm internally and get back to you.

**Comment by cijothomas** [comment]
@Dmitry-Matveev you recently responded to a ticket about namespaces - is this related? (105488966 icm # for internal reference.)

**Comment by Dmitry-Matveev** [comment]
@cijothomas , the issue you referenced was specific to metric namespaces being omitted and it has been fixed, so, most likely, it's a different one.

My guess would be that dimensions have not landed in Metrics backend and are only available in Analytics backend at his time. Analytics query may help with splitting those and charting separately.

**Comment by jdvor** [comment]
> @cijothomas 
> My guess would be that dimensions have not landed in Metrics backend and are only available in Analytics backend at this time. Analytics query may help with splitting those and charting separately.

By analytics backend do you mean (on portal) Application Insights resource / Analytics where you would use queries like this:
```
customMetrics 
| where name == "tc_counter_two" 
| order by timestamp desc nulls last 
```
or is it something else?

Because if you mean the above - neither dimension **nor** metricNamespace is shown.

**Comment by jdvor** [comment]
Because of this [implementation](https://github.com/jdvor/appmetrics-applicationinsights) I have some very recent experience with `TelemetryClient.Track(ITelemetry telemetry)` method - that's an API for cases where application code is doing pre-aggregation. It's where you can pass metricNamespace and it certainly does not add any new properties, custom dimensions or filtering capabilities to analytics (if by analytics you mean things in comment above).
But it is possible that `GetMetric().TrackValue()` API behaves differently when MetricIdentifier with namespace is provided.

**Comment by jdvor** [comment]
@cijothomas or @Dmitry-Matveev : so is there a way how to access / work with reported dimensions and namespaces?

**Comment by cijothomas** [comment]
@jdvor 
I tried the examples from here, and dimenstions show up.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#getmetric

Modified your example as below, based on doc:
tc.GetMetric("tc_counter_two", "fruit").TrackValue(new Random().Next(1, 4),"Apples");
tc.GetMetric("tc_counter_two", "fruit").TrackValue(1, "Oranges");

**Comment by cijothomas** [comment]
![image](https://user-images.githubusercontent.com/5232798/57108377-650b5f00-6ce7-11e9-9e84-a3a9763ca62f.png)

**Comment by edaena** [comment]
@cijothomas Where did you get that table view for the metrics? I'm seeing this issue, but I can't find that table view you showed.
