### ISSUE TITLE
Open Build Visibility

### ISSUE THREAD

**Issue by stimms** [microsoft/ApplicationInsights-dotnet#1124]
When submitting PRs it is difficult to check on the build because the Azure DevOps pipelines are not publicly visible. It would also be helpful to have the `azure-pipelines.yml` checked into the repository.

**Comment by cijothomas** [comment]
@stimms Thanks for the feedback. Only Linux builds currently use the yml which is here: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.vsts/linux-build.yml

I'll check internally on what can be done to expose CI build/test logs public.

**Comment by cijothomas** [comment]
Until this is public, please refer to this doc https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md to know how to build/test locally.

**Comment by MS-TimothyMothra** [comment]
Azure DevOps has introduced pipelines that can be publicly visible. We need to migrate to those for PRs.

**Comment by TimothyMothra** [comment]
this is done
