### ISSUE TITLE
Direct Json support in customDimenions

### ISSUE THREAD

**Issue by mattmccleary** [microsoft/ApplicationInsights-dotnet#1127]
## Repro Steps
Given the following data submitted in a custom dimension:
 
```
{
               "EventId": "123",
               "EventName": "XXX",
               "TenantId": "200",
               "CreatedAt": "2019-04-27 00:31:20",
               "Content": {
                              "paymentReceived": {
                                            "businesspartnerAccount": {
                                                           "accountExternal": "12345"
                                            }
                              }
               }
}
```

##  Actual Behavior
currently we have to do the following to access JSON-data
`| extend accountExternal = parse_json(customDimensions.Content).paymentReceived.businesspartnerAccount.accountExternal`

## Expected Behavior
We would prefer
`| extend accountExternal = customDimensions.Content.paymentReceived.businesspartnerAccount.accountExternal`

## Version Info 
SDK Version : All
.NET Version : All						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : N/A
Hosting Info (IIS/Azure WebApps/ etc) : N/A

**Comment by cijothomas** [comment]
removed P1. Lets reserve it for any critical bugs.
