### ISSUE TITLE
Experimental Features Flag

### ISSUE THREAD

**Issue by MS-TimothyMothra** [microsoft/ApplicationInsights-dotnet#1131]
## Proposal
I'm proposing a new property on the `TelemetryConfiguration`:  Experimental Features.

- Experimental Features is a comma separated string of feature names.
- This string should be very quick to evaluate. Therefore there will be no data structure or values to parse. A feature is either **on** or **off** which is determined by the name existing in the string.

1. **Configuration Property**
```
/// <summary>
/// Gets or sets a string indicating if an experimental feature should be enabled.
/// This string contains comma separated feature names.
/// Ex: "featurename1, featurename2, featurename3"
/// </summary>
/// <remarks>
/// This property allows the dev team to ship and evaluate features before adding these to the public API.
/// We are not committing to support any features enabled through this property.
/// Use this at your own risk.
/// </remarks>
[EditorBrowsable(EditorBrowsableState.Never)]
public string[] ExperimentalFeatures { get; set; }
```

2. **This would be paired with a new public class (name TBD).**
This makes the value of the configuration available to Base, Web, Logging, and Core SDKs.

```
namespace Microsoft.ApplicationInsights.Extensibility.Implementation
{
    using System;
    using System.ComponentModel;

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static class ExperimentalFeaturesUtility
    {
        public static bool Evaluate(TelemetryConfiguration telemetryConfiguration, string featureName, ref bool? featureValue)
        {
            if (!featureValue.HasValue)
            {
                featureValue = Exists(telemetryConfiguration.ExperimentalFeatures, featureName);
            }

            return featureValue.Value;
        }

        private static bool Exists(string[] features, string featureName)
        {
            bool value = false;

            if (features != null || features.Length > 0)
            {
                value = Array.Exists(features, x => x.Equals(featureName, StringComparison.OrdinalIgnoreCase));
            }

            return value;
        }
    }
}
```

3. **Each SDK would have a private internal class to access values of Experimental Features** 
This keeps features private which allows us to enable or disable features as needed.
Retiring a feature won't break the SDK. Old feature names in the config string can be safely ignored.

```
namespace Microsoft.ApplicationInsights.Extensibility.Implementation
{
    using System;

    internal class ExperimentalFeatures
    {
        private static readonly Lazy<ExperimentalFeatures> InstanceLazy = new Lazy<ExperimentalFeatures>();

        public static ExperimentalFeatures Instance => InstanceLazy.Value;

        private static bool? deferedRequesttelemetry;

        public static bool DeferedRequestTelemetry => ExperimentalFeaturesUtility.Evaluate(nameof(DeferedRequestTelemetry), ref deferedRequesttelemetry);
    }
}
```

## Why
We've been having several discussions lately about implementing and testing dramatic changes to the SDK. This will allow us to add features but hide them from the public api until they're fully finished.

This will enable us to experiment with performance enhancements needed for the On By Default scenarios.

**Comment by MS-TimothyMothra** [comment]
@SergeyKanzhelev @Dmitry-Matveev @cijothomas @lmolkova for comment.

**Comment by SergeyKanzhelev** [comment]
I want to learn more about what kind of features you are thinking about which will not require it's own API surface. And if there is an API surface - why not just have Enable flag there? An easy alternative is to define and register a telemetry module, for which the only job is to enable some feature in `Initialize` method. And this telemetry module can be even defined as an internal class.

**Comment by MS-TimothyMothra** [comment]
Our attach extensions require performance enhancements to be On-By-Default in these environments.
We're making perf enhancements which defer execution until after sampling.

We don't want customers to find these features because if not configured exactly it may break the SDK.

These are not expected to be permanent enhancements. Significant changes are coming to help solve sampling (NET CORE 3.0 and SDK 3.0). But we can't wait for these changes. 

Keeping these out of the public API gives us some flexibility to remove or change classes without breaking customers. We shouldn't delete private classes after being referenced in a config.

**Comment by MS-TimothyMothra** [comment]
#1174 is a good example.

This currently requires a property set on the `RequestTrackingTelemetryModule `and to add a the `PostSamplingTelemetryProcessor `after sampling. 
It would be ideal to have a single setting control both halves of this, but without adding a new Enable boolean to the config for every one-off feature.

I proposed the ExperimentalFeatures string as a compromise.

**Comment by lmolkova** [comment]
A couple of thoughts on the design: 
- it has to work nicely with any instance of TelemetryConfiguration - not just Active, otherwise, it won't be useful in ASP.NET Core SDK

- please consider the possibility of having an array in the config for features instead of comma separated string. Not critical, but simplifies parsing 

```xml
<ExperimentalFeatures>
   <feature>"foo"</feature>
   <feature>"bar"</feature>
</ExperimentalFeatures>
```

**Comment by lmolkova** [comment]
@SergeyKanzhelev we do not always want to expose flags to customers especially as a public API. Some features we want to control ourselves and remove once we want.

Some of these feature flags are very confusing and spread further than one telemtery module. 

As @MS-TimothyMothra mentioned #1174 is a perfect example of such a feature. We also know for sure we are going to change it and won't need feature flag anymore.

**Comment by SergeyKanzhelev** [comment]
definitely go with array, not a concatenated string. 

However I'm still thinking you are solving a wrong problem. Experiments will required installing an initializer of telemetry modules. So you will need to still configure two things and coordinate this configuration.

The problem you are trying to solve (I think) is a problem we already have - coordination between data producers (telemetry modules) and pipeline. Similar to what we have in quick pulse where telemetry module on initialization tries to synchronize itself with the telemetry processor. And may loose this synchronization.

Imagine this problem is solved - do you still need feature flags setting on telemetry configuration class?

**Comment by lmolkova** [comment]
In case of https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/1174 we are talking about feature flag on RequestTrackingTelemtetryModule. processors/initializers and feature flags are orchestrated by the config and remain internal (yes, it works) or can be declared in other places (extensions) .

In particular, I want to avoid this:
```csharp
        /// <summary>
        /// Gets or sets a value indicating whether requestTelemetry.Url and requestTelemetry.Source are disabled.
        /// Customers would need to use the <see cref="PostSamplingTelemetryProcessor" /> to defer setting these properties.
        /// </summary>
        /// <remarks>
        /// This feature is still being evaluated and not recommended for end users.
        /// This setting is not browsable at this time.
        /// </remarks>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool DisableTrackingProperties { get; set; } = false;
```

In case of e.g. W3C  we needed orchestration between Request and Dependency modules and ended up with two options. Single feature flag could be a better option here.

**Comment by SergeyKanzhelev** [comment]
One alternative is to call it `ConfigurationOptions` and allow to register strongly typed objects in `TelemetryConfiguration` object. Sort of DI. Perhaps built-in object will be one with a name and a single `bool` value inside.

In example with W3C headers you may need to express various preferences - convert to W3C, keep incoming header format, or convert to Request-Id. For this setting you need more than just a single `bool`. Also objects are easier to use if you want this setting to be changeable from the runtime.

**Comment by lmolkova** [comment]
ConfigurationOptions sounds good to orchestrate initializers/modules/processors together, but it does not seem to help with avoiding `DisableTrackingProperties ` and other experimental feature flags. 

Feature flags can work together with such callback (e.g. for feature 'foo' I will automatically set up inittializer and module), but something still needs to set up the feature flag

**Comment by SergeyKanzhelev** [comment]
callback are not the key in proposal. It's nice addition. I'm suggesting to have more than simple `bool` for experimental feature. And in general instead of calling them experimental flags call them configuration options. So this feature can be used to coordinate config for non-experimental features as well.

**Comment by MS-TimothyMothra** [comment]
How would you want this to look exactly?

It sounds like you're proposing a `dictionary<string, object>`. In general, I don't have a problem with this but I want to better understand the use case.



My reasoning for a collection of strings was to keep this as simple as possible and not introduce a lot of parsing and overhead. One compromise might be to retain the string array `string[]` and when evaluating the feature, inject the desired object.

**Comment by lmolkova** [comment]
I missed something about `dictionary<string, object>`. I guess `ConfigurationOptions`  is an additional callback that could be called when TelemetryConfiguration is created/built and modules/SDKs can subscribe to it to add processors and initializers a lot like ASP.NET Core DI container.  
From my understanding, it does not change design for an experimental feature config/evaluation and it needs more design. 

I'm not sure if we need to design it now, I believe `ExperimentalFeaturesUtility` (might be with a different name) is enough to close on microsoft/ApplicationInsights-dotnet-server#1174.
 
@SergeyKanzhelev what are your thoughts on this? Can we proceed with experimental features array and think about `ConfigurationOptions` callback when we have a scenario that needs it?

**Comment by SergeyKanzhelev** [comment]
I was thinking of array that @MS-TimothyMothra suggested. So modules and processors can exchange config information in a form of an object, not a single string or a single bool. And this object can be mutates in runtime. Use case as above - some features may require extra configuration, not just "enable" flag or be controlled in runtime.

Callback idea is neat. Maybe it can be additional feature.

**Comment by lmolkova** [comment]
I guess we need a whiteboarding session to understand each other :)

I personally do not think we should overengineer it. Again in ASP.NET Core we have DI and orchestration problem does not exists, in classic, we have xml config that works as DI. Experimental features enablement is needed in addition to that.

**Comment by MS-TimothyMothra** [comment]
Saving this here.
This is how I recommend interacting with the API:

```
namespace Microsoft.ApplicationInsights.Extensibility.Implementation.Experimental
{
    /// <summary>
    /// This class provides a means to interact with the <see cref="TelemetryConfiguration.ExperimentalFeatures" />.
    /// This performs a simple boolean evaluation; does a feature name exist in the string array?
    /// Evaluation results are cached.
    /// </summary>
    internal static class ExperimentalFeatures
    {
        internal static bool IsExampleFeatureEnabled(TelemetryConfiguration telemetryConfiguration) => telemetryConfiguration.EvaluateExperimentalFeature("exampleFeature");
    }
}
```
