### ISSUE TITLE
AppInsights NuGet packages work with Package References "style"

### ISSUE THREAD

**Issue by joaopgrassi** [microsoft/ApplicationInsights-dotnet#1137]
I'm upgrading a .NET Framework 4.7.2 project to use the new SDK `csproj` style. 

Before doing the change, I usually [migrate](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference) the project first to use [PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) then I edit the `.csproj` file to match with the new format.

When migrating a project that uses the Application Insights NuGet packages, I get some warnings:

![Image of Yaktocat](https://i.imgur.com/1wkcCjp.png)

This is because the `content` folder is not compatible with the new package reference format. 

Also, the `ApplicationInsights.config` is completely cleaned up. The content of file after applying the migration to `PackageReferences` is:

```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
</ApplicationInsights>
```

My question: Is there anything I can expect **not to work** when upgrading to the new format? I upgraded the packages to the latest version `2.9.1`, and the issue still happens.

In case something will not work due to the `content` folder not being used, is there any plans to change the package to "play nicely" with the new format?

Thanks!

**Comment by cijothomas** [comment]
@MS-TimothyMothra can you take a look? seems related to another issue about applicationinsights.config file.

**Comment by joaopgrassi** [comment]
Hi guys, any news on this?

**Comment by MS-TimothyMothra** [comment]
Hi @joaopgrassi.
I'm scheduled to look into resolving this in July. 

For a workaround,
You can set your config file to Copy to Output directory. That's what this target file is doing.
https://github.com/microsoft/ApplicationInsights-dotnet-server/blob/1beaa2aa25db6a90f814b372e65d15ab78f8d314/Src/DependencyCollector/DependencyCollector/Microsoft.ApplicationInsights.DependencyCollector.targets

**Comment by joaopgrassi** [comment]
Hi @MS-TimothyMothra

Thanks for the reply. So, I should keep `ApplicationInsights.config` with its original content, and make sure it's copied to the output directory? Also, I'm curious about why it got its content all removed, as part of the migration. Is the SDK supposed to be configured differently in SDK projects? 

What I did so far was: I kept the original file and deployed the app to Azure and it seems so far that everything is the same. I can see the dependencies being collected (HTTP, SQL Server), errors, performance counters and so on.

**Comment by MS-TimothyMothra** [comment]
There is no configuration difference for SDK projects.

When you upgrade our SDK, we have some xml transforms that apply to the config. These are meant to enable new features or config changes. 

**As a workaround**, you can install the same version of the SDK in an empty project and compare the differences to your project. I know this is less than ideal and I'm sorry for the inconvenience. Please add to this thread if you have any additional problems.

**Comment by joaopgrassi** [comment]
I had a chance to try the workaround in a new project as suggested, to see the differences. The steps I did are:

- Created a new WebApi (Not ASP.NET Core) project targeting .NET Framework 4.7.2
- Followed [this](https://github.com/NuGet/docs.microsoft.com-nuget/issues/860) to upgrade the project to use `PackageReference` instead of `packages.config`, as it's not supported "by default" for web projects on vs2017
- Reloaded the project, made sure everything is working
- Right-click on project > Add Application Insights> Just Add the SDK to try locally

Outcome: 

- `ApplicationInsights.config` file is **not created**
- As I can see, only `Microsoft.ApplicationInsights.TraceListener` and `Microsoft.ApplicationInsights.Web` NuGet packages are installed

If I don't convert the project to use `PackageReference`, then adding Application Insights creates the `.config` file and all works. So, I guess it boils down to adding the SDK via Visual Studio on projects which uses `PackageReference` does not work well.
