### ISSUE TITLE
Custom metric splitting doesn't seem to work

### ISSUE THREAD

**Issue by scabana** [microsoft/ApplicationInsights-dotnet#1144]
## Repro Steps
1. Create an Application Insights instance in azure portal
2. Run this code: 
```csharp
    internal class Program
    {
        private static void Main(string[] args)
        {
            var client = new TelemetryClient(new TelemetryConfiguration("{Some key}"));
            
            Metric metric = client.GetMetric(new MetricIdentifier("SomeNamespace", "test", "dimesion1"));

            while (true)
            {
                metric.TrackValue(1, "value1");
                metric.TrackValue(2, "value2");

                Thread.Sleep(5000);
            }
        }
    }
```
3. Go to AppInsights on Azure portal, Metrics, select the metric, add splitting on "dimension1", see a single line like this: 
![image](https://user-images.githubusercontent.com/8278735/58107813-9fff0500-7bb8-11e9-97c4-0c2b7bbf6351.png)

##  Actual Behavior

A single line/metric shows up.

## Expected Behavior

Two lines(or more if there were more dimension1 values) should show up, one per dimension on which it is split.

## Version Info 
SDK Version : 2.9.1
.NET Version :	.net core 2.2.101 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Create app insights + use key in console app
OS : win 10 1709
Hosting Info (IIS/Azure WebApps/ etc) :Console App

**Comment by Dmitry-Matveev** [comment]
@scabana ,

Can you please check if you have those metrics in Analytics (Overview page -> Analytics) as well and whether they have the different `dimension1` values in there?

P.S. Also, please make sure to run this sample for at least a minute each time (the default aggregation period is 1 minute, so `trackValue()` won't be aggregated/sent unless 1 whole minute has passed).

**Comment by cijothomas** [comment]
@vgorbenko

**Comment by scabana** [comment]
@Dmitry-Matveev , 

They are there and they have a property called ```customDimensions``` with different values. 

Are custom metrics still in preview? On a new app insights instance, I was able to get the ```Add filter``` and ```Add splitting``` buttons to light up, but splitting didn't split on the dimension selected, filter worked. On a much older instance of App Insights (in a custom metrics supported region), the buttons just won't light up.

**Comment by Dmitry-Matveev** [comment]
@scabana , unfortunately, I can only answer the collection portion of the question and it looks like the data has been collected but was not either presented or processed correctly.

@vgorbenko would need to take that question further.

**Comment by vgorbenko** [comment]
@scabana, please open your Application Insights resource, click on the **Usage and estimated costs** tab, and open **Custom metrics (preview)** panel. Make sure that you have **Enable alerting on custom metric dimensions** checkbox checked so that Azure collects dimensions of your custom metric.

**Comment by scabana** [comment]
Thanks, the custom metrics (preview) enabled all that was needed. Would have been super nice to have some UI indication that it was what was needed.

**Comment by dmunch** [comment]
Almost 5 years later, and thi sis still in preview, and still a pretty well-hidden feature 😅
