### ISSUE TITLE
Sanitization of strings

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#1145]
@cijothomas, I re-read your comment here: https://github.com/Microsoft/ApplicationInsights-Home/issues/292#issuecomment-437165571 and have a problem with the statement:

>SDK does not do anything other than trimming - if the value was some json/xml it may be broken.

SDK should sanitize strings before serialization. It is one of the important design principles to allow any string to be sent to the backend - there should be no unhandled errors in that logic. Issues with invalid JSON are practically impossible to troubleshoot.

Also, I see this test case. So perhaps we have the logic, just a comment is wrong.

https://github.com/microsoft/ApplicationInsights-dotnet/blob/80025b5d79cc52485510d422cfa5a0a8159dac83/Test/Microsoft.ApplicationInsights.Test/Shared/TelemetryClientTest.cs#L1169

**Comment by cijothomas** [comment]
@SergeyKanzhelev I am not sure I understand the issue./bug here?

SDK trims off strings to keep it within limit. That's all SDK is doing at sanitize step.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/80025b5d79cc52485510d422cfa5a0a8159dac83/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Property.cs#L228

The value itself is put by user, and could have been interpreted as json or anything by user - but for SDK its a string and it will just trim off anything exceeding the MAX size. This won't affect the JSON schema for AI backend. I am not aware of any unhandled errors in this space.
