### ISSUE TITLE
Remove dependency on System.Net.Requests from everywhere 

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1146]
Burn 
https://github.com/microsoft/ApplicationInsights-dotnet/blob/ca4b1eb3660e69024384b3623ccc177824568d79/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L358

**Comment by cijothomas** [comment]
Its already marked obsolete, and anything marked Obsolete can/should be removed in 3.0
