### ISSUE TITLE
404 (not-retryable) will not save to file on ServerTelemetryChannel configuration

### ISSUE THREAD

**Issue by erwinkramer** [microsoft/ApplicationInsights-dotnet#1151]
So the issue with checking for 404's (including 200's?) and completely ignoring the logging is pretty annoying. In my case, a proxy is configured to block some endpoints. If it blocks an endpoint, it will return a HTTP 404 or 200 response with a proxy blockpage. 

In this case, i would really like it to:
- **AT LEAST** Respond with feedback when `DeveloperMode` is enabled. Currently no error and no warning is showing up. 
- Create a file in the `StorageFolder` location with the logs i was trying to send. 

These 2 issues make it very hard to get into AI in the first place. 

Also pretty weird, when Microsoft itself returns a 404 (yes i know it is rare, but you want reliability when you use the `WindowsServer` package right?!) you should also get the feedback and the file in the `StorageFolder` location.

Using Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel version 2.10.

**Comment by cijothomas** [comment]
There is Warning level trace sent for any status codes not whitelisted for retry.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/src/ServerTelemetryChannel/Implementation/TelemetryChannelEventSource.cs#L514

Retries are done only for known backend issues or network errors. Only items meant for retry are stored to local storage folder.
