### ISSUE TITLE
Expose Initialization via ConfigString [Feature request for App Svc Extension]

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1159]
# Proposal to support codeless attach configuration

## Today
Our Codeless Attach projects use embedded configuration
At runtime, they will use reflection to access `TelemetryConfigurationFactory` which will serialize this string. Then reflection is used again to set `TelemetryConfiguration.Active`

https://github.com/microsoft/ApplicationInsights-dotnet/blob/0ea76e8ec77e74181a085f6f4ef2856773dc6489/src/Microsoft.ApplicationInsights/Extensibility/Implementation/TelemetryConfigurationFactory.cs#L52

https://github.com/microsoft/ApplicationInsights-dotnet/blob/653214810e3e853908f69f94337a996561fe76b6/src/Microsoft.ApplicationInsights/Extensibility/TelemetryConfiguration.cs#L84

## Proposal
We already have a public API that can do most of this work:

https://github.com/microsoft/ApplicationInsights-dotnet/blob/653214810e3e853908f69f94337a996561fe76b6/src/Microsoft.ApplicationInsights/Extensibility/TelemetryConfiguration.cs#L301-L316

## Option 1 (Simple fix)
- Replace the `modules: null` with `modules: TelemetryModules.Instance`.
- Codeless Attach would continue to use reflection to set `TelemetryConfiguration.Active`

## Option 2 
- Replace the `modules: null` with `modules: TelemetryModules.Instance`.
- Internally set `TelemetryConfiguration.Active`

This is my preferred option.
I know that there is a plan to obsolete the TelemetryConfiguration singleton so I think it would be ideal to do all the configuration within the SDK.

## Option 3
- Introduce a new API for Codeless Attach to perform the full end-to-end configuration.

## Outstanding questions
- Who or What uses `TelemetryConfiguration.CreateFromConfiguration` today?
- Would changing the behavior break anyone?

**Comment by MS-TimothyMothra** [comment]
@SergeyKanzhelev @Dmitry-Matveev @cijothomas @lmolkova @Mikhail-Pranovich 
please review
