### ISSUE TITLE
End support for NETSTANDARD 1.6

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1160]
.NET Core 1.1 will end support on June 27 2019.
https://devblogs.microsoft.com/dotnet/net-core-1-0-and-1-1-will-reach-end-of-life-on-june-27-2019/

This repo (and other repos), have lot of conditional compilations for NETSTANDARD1_6,. Proposing to remove all NETSTANDARD 1_6 or lower support. 

Once .net core 3.0 is GAed, we'll need to add 3.0 tests as well, so removing 1.1 could be clubbed together.

**Comment by MS-TimothyMothra** [comment]
It looks like `NETStandard.Library` v1.6.1 might be bringing in `System.Net.Http` v4.3.0 which is out of compliance.

**Comment by TimothyMothra** [comment]
i'm closing this parent issue as we're tracking this effort in smaller issues.
