### ISSUE TITLE
End support for NET 4.5 (in favor of NET 4.5.2)

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1161]
> starting January 12, 2016 Microsoft will no longer provide security updates, technical support or hotfixes for .NET 4, 4.5, and 4.5.1 frameworks.
https://devblogs.microsoft.com/dotnet/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

We should have a serious discussion about migrating our projects off of .NET 4.5 and onto .NET 4.5.2 instead. 

https://github.com/microsoft/ApplicationInsights-dotnet/blob/9405f131a9689a4290af37e7e53151a1f4d789fd/src/Microsoft.ApplicationInsights/Microsoft.ApplicationInsights.csproj#L6

I expect that dropping support for NET 4.5 would be controversial.
As a compromise, I think we could target both 4.5 and 4.5.2 until we're ready to retire 4.5 completely.

## TODO:
1. Add Net452 to all projects targeting net45x
2. Remove Net45 and Net451
3. Audit Builds and confirm that tests are being discovered.

**Comment by eddynaka** [comment]
@TimothyMothra , i can start adding .net452 where we have .net45, so, when we decide to drop .net45 people that uses at least net452 won't be affected. what do you think?

**Comment by TimothyMothra** [comment]
2.15 already has some big changes, i don't want to take another big one like this right now
