### ISSUE TITLE
'TelemetryContext.Properties' is obsolete

### ISSUE THREAD

**Issue by itorian** [microsoft/ApplicationInsights-dotnet#1171]
I updated ApplicationInsight packages and started noticing obsolete warning on below code. We have similar code all around the places in application, how do i fix this.

```
var request = new RequestTelemetry();

request.Name = "AccountActivity";
request.Context.Properties["TenantId"] = "value_here";
request.Context.Properties["TenantName"] = "value_here";
request.Context.Properties["LoginProvider"] = "value_here";
request.Context.Properties["Timestamp"] = "value_here";

var ai = new TelemetryClient();
ai.TrackRequest(request);
```

**Comment by cijothomas** [comment]
request.Properties would work.
Alternately, request.Context.GlobalProperties can be used for low cardinality properties. Both are serialized and sent to back-end in the same way today.
