### ISSUE TITLE
Bug: Both TelemetryChannels do not correctly handle AggregateException

### ISSUE THREAD

**Issue by MS-TimothyMothra** [microsoft/ApplicationInsights-dotnet#1173]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
**still investigating, don't have a repro yet**

Breeze fixed their issues. Can test using this: https://badssl.com/

##  Actual Behavior

We aren't handling the `AggregateException`.
Instead, we log this message: 
> "Failed to send: One or more errors occurred.."

https://github.com/microsoft/ApplicationInsights-dotnet/blob/f181abbcdf6a6a2a4aea821ce1d72e98b0c68fbe/src/Microsoft.ApplicationInsights/Channel/InMemoryTransmitter.cs#L136-L144

Send method returns a Task
https://github.com/microsoft/ApplicationInsights-dotnet/blob/f181abbcdf6a6a2a4aea821ce1d72e98b0c68fbe/src/Microsoft.ApplicationInsights/Channel/InMemoryTransmitter.cs#L151

## Expected Behavior

We need to correctly handle the `AggregateException`.

## Version Info 
SDK Version : all
.NET Version :	all						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : nuget
Hosting Info (IIS/Azure WebApps/ etc) : onprem

**Comment by MS-TimothyMothra** [comment]
`ServerTelemetryChannel` might have the same bug. Investigating...

**Comment by cijothomas** [comment]
@MS-TimothyMothra Great catch! We really want to log most accurate error message if things are not working well, and fixing this further improves supportability.
Can you confirm that this issue is not affecting reliability (we are still doing retries as expected), but only our logging, and hence suportability is affected?

**Comment by pharring** [comment]
@MS-TimothyMothra I don't think ServerTelemetryChannel has the bug because it does an `await` which unpacks the Exception.

**Comment by MS-TimothyMothra** [comment]
@cijothomas No behavior is affected, we're only logging incorrect or incomplete exceptions
