### ISSUE TITLE
System.ArgumentException in Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChainBuilder.Build

### ISSUE THREAD

**Issue by vinod1054** [microsoft/ApplicationInsights-dotnet#1177]
If you are reporting bug/issue, please provide detailed Repro instructions.

Exception while configuring application insights for service fabric services

message -- Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
Exception -- System.ArgumentException

```
at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.<ReverseIterator>d__75`1.MoveNext()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryProcessorChainBuilder.Build()
```

Following is the piece of code used to configure AI
```csharp
telemetryConfiguration.InstrumentationKey = this.ConfigurationManager.GetSettingAsString(ServiceConstants.GenevaInstrumentationKey);
telemetryConfiguration.TelemetryProcessorChainBuilder.Use(next => new GenevaMetricsProcessor(next)
{
    MetricAccountName = this.ConfigurationManager.GetSettingAsString(ServiceConstants.MetricAccountName),
    MetricNamespace = this.ConfigurationManager.GetSettingAsString(ServiceConstants.MetricNamespace),
    DefaultDimensions = { ServiceFabricPropertyNames.ServiceTypeName, ServiceFabricPropertyNames.NodeName }
});
telemetryConfiguration.TelemetryProcessorChainBuilder.Build();
```

## Repro Steps
1. 
2. 

## Version Info 
SDK Version : dotnet:2.9.1-26108
.NET Version :	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS :
Hosting Info (IIS/Azure WebApps/ etc) : Service fabric cluster in azure

**Comment by TimothyMothra** [comment]
Not an SDK issue.
This is a problem with the GenevaMetricsProcessor.

Replied offline.

**Comment by GeorgiMateev** [comment]
Hello,
I'm hitting the same exception.
I also build the chain processor and I have a custom TelemetryProcessor.
What was the issue with the one in the question?

**Comment by Invictuschen** [comment]
Hi dudes, our code is also facing this issue now. We also use Geneva to do some custom metric recording. I just wonder if you have some solutions/conclusions to this thing? It would be rather great if you could bring some information. @GeorgiMateev @vinod1054 @lmolkova

**Comment by MatthiasVnh** [comment]
@TimothyMothra We are also hitting this issue with a custom processor. Would you mind explaining what the issue was and how it can be resolved?
