### ISSUE TITLE
Internal exceptions when targeting .NET Core 2.1

### ISSUE THREAD

**Issue by freebird8x** [microsoft/ApplicationInsights-dotnet#1178]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create a .NET Core console app and target .NET Core 2.1
2. Write a simple telemetry client like below and run the code:
```
var configuration = new TelemetryConfiguration
{
    InstrumentationKey = "<guid>",
    TelemetryChannel = new Microsoft.ApplicationInsights.Channel.InMemoryChannel()
};

var telemetryClient = new TelemetryClient(configuration);
telemetryClient.Context.Operation.Id = Guid.NewGuid().ToString();
telemetryClient.Context.Operation.Name = "Testing";

telemetryClient.GetMetric("Testing Metric").TrackValue(100);
telemetryClient.TrackEvent("Testing Event", new Dictionary<string, string> { { "Testing", "Test" } });
telemetryClient.TrackTrace("Testing Trace");

telemetryClient.Flush();
```

##  Actual Behavior
The code failed to push data to Application Insights and there are these exceptions in the output log:
```
Exception thrown: 'System.Net.Sockets.SocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Net.Http.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll
Exception thrown: 'System.AggregateException' in System.Private.CoreLib.dll
```
## Expected Behavior
When targeting .NET Core 2.1, there should not be exceptions and the metrics can be pushed to Application Insights. 
This seems to have something to do with System.Net.Http 4.3.4 not compatiable with .NET Core 2.1.
Note that when targeting .NET Core 2.0, it works fine.

## Version Info 
SDK Version : 2.10
.NET Version :	Core 2.1 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VS 2017
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : running locally as desktop app.

**Comment by cijothomas** [comment]
I am not reproeing this in 2.1 or 2.2.
Did you run in 2.2? Also, did you explicitly specify System.Net.Http version? Would be great to attach a repro project.

**Comment by freebird8x** [comment]
Sure here's the sample project. I didn't specify the `System.Net.Http` version. Just simply add nuget reference to` Microsoft.ApplicationInsights` 2.10.
Note that the exception is swallowed by` Microsoft.ApplicationInsights` dlls so you won't be able to catch it. But if you look into the Output window, you would see it. In the attached zip file, I included `DebugOutputLog.txt `which shows the exceptions I see over here (scroll to the end of the log).

[CSharptTestCore.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/3428906/CSharptTestCore.zip)

**Comment by cijothomas** [comment]
I didnt get a repro with this. Also, the title is probably misleading - these is no crash, and application insights is successfully sending data to backend.

Please run perfview and get us SDK logs as well:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data#PerfView

make sure to start perfview before you run the app.

**Comment by freebird8x** [comment]
ok, I have revised the title to internal exception. However, the data is not sent to backend when there are internal exceptions. It happens when telemetryClient.Flush() executes.

attached is the perfview log.

[PerfViewData.etl.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/3433187/PerfViewData.etl.zip)

**Comment by cijothomas** [comment]
The attached trace does not contain all the traces. Make sure to include all the providers.

PerfView.exe collect -MaxCollectSec:300 -NoGui /onlyProviders=*Microsoft-ApplicationInsights-Core,*Microsoft-ApplicationInsights-Data,*Microsoft-ApplicationInsights-WindowsServer-TelemetryChannel,*Microsoft-ApplicationInsights-Extensibility-AppMapCorrelation-Dependency,*Microsoft-ApplicationInsights-Extensibility-AppMapCorrelation-Web,*Microsoft-ApplicationInsights-Extensibility-DependencyCollector,*Microsoft-ApplicationInsights-Extensibility-HostingStartup,*Microsoft-ApplicationInsights-Extensibility-PerformanceCollector,*Microsoft-ApplicationInsights-Extensibility-PerformanceCollector-QuickPulse,*Microsoft-ApplicationInsights-Extensibility-Web,*Microsoft-ApplicationInsights-Extensibility-WindowsServer,*Microsoft-ApplicationInsights-WindowsServer-Core,*Microsoft-ApplicationInsights-Extensibility-EventSourceListener,*Microsoft-ApplicationInsights-AspNetCore

**Comment by cijothomas** [comment]
Closing. Please reopen once you get the logs and this continues to repro for you.
