### ISSUE TITLE
Telemetry bypassing corporate proxy, how to inject proxy settings?

### ISSUE THREAD

**Issue by KrothuTheCoder** [microsoft/ApplicationInsights-dotnet#1188]
We are trying to run docker containers on an IaaS VM in Azure, where all web traffic is going through a corporate blue coat proxy then through a checkpoint firewall. When running the application code locally that has implemented simple AI SDK options (i.e. import nuget package and give it instrument key) the telemetry flows as expected. 

However, when we dockerise the application and push to our IaaS VM the telemetry ignores all proxy settings in the container and tries to bypass the proxy hitting the firewall directly. This is the automatically blocked. 

Where to me it looks like your setting a private static HttpClient, is there a way of overriding that to give it the proxy settings? 

## Version Info 
SDK Version : 2.7.1
.NET Version :	netcoreapp2.2					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Using Microsoft.ApplicationInsights.AspNetCore Version="2.7.1"
OS : Windows 10 and Windows server 2016
Hosting Info (IIS/Azure WebApps/ etc) : Docker and Kestrel

**Comment by KrothuTheCoder** [comment]
Also thinking if instead of creating your HttpClient directly could using a HttpClientFactory with a named client allow for it to be overridden for specific client needs in the startup?

**Comment by pharring** [comment]
Have you tried setting [`System.Net.WebProxy.DefaultWebProxy`](https://docs.microsoft.com/dotnet/api/system.net.webrequest.defaultwebproxy) in your startup code?

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/441#issuecomment-516253821

**Comment by KrothuTheCoder** [comment]
Thanks for your responses, unfortunately setting the proxy by reflection did not work. Right now we are looking to make sure that we can curl the endpoint from within the running container

**Background Info:** we are using/stuck with using **dotnet/core/aspnet:2.2.3-nanoserver-1803** as the base image [this is another problem I am trying to fix].

Using the below as an example of our dockerfile to set the proxy details, we are 

```
FROM dotnet/core/aspnet:2.2.3-nanoserver-1803
USER ContainerAdministrator 
WORKDIR /app

ENV ASPNETCORE_URLS http://+
ENV http_proxy http://proxy.example.com:8080 
ENV https_proxy http://proxy.example.com:8080 

EXPOSE 80 443
COPY ./src/example/dist .
ENTRYPOINT ["dotnet", "exampleCode.dll"]
```

**Comment by KrothuTheCoder** [comment]
Ok, the current update is that I have so some telemetry getting through, using the docker configured and using program.cs HttpHandler/Proxy reflection hack. We are still testing but calling the Telemetry client in the startup.cs I have seen the different types of telemetry come through.

However, although we have manged to get traffic to **dc.services.visualstudio.com** for the telemetry which is a good step forward. Any live telemetry to **rt.services.visualstudio.com** is still going directly to the firewall and getting blocked. Any thoughts?

Halfway there with some code that is not desirable, if there was a way we could override the HttpHandler for Application Insights it would be a cleaner implementation.

**Comment by KrothuTheCoder** [comment]
Can someone tell me what the class responsible for sending the live telemetry is called? I am trying to see if I can get the reflection method to work for that class too.
