### ISSUE TITLE
Improve Config Parsing Exceptions

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1194]
Can we please change TelemetryConfigurationFactory to include the property name when it fails to parse a value from the configuration file.

**Actual Exception:**
System.FormatException: 'Input string was not in a correct format.'

**Expected Exception:**
Exception: Failed to parse 'MaxTransmissionBufferCapacity' Reason: 'Input string was not in a correct format'
Inner Exception: System.FormatException: 'Input string was not in a correct format.'

**Comment by cijothomas** [comment]
Where will user see this Exception?

**Comment by TimothyMothra** [comment]
it currently throws the FormatException in the user code when the config file is first parsed.

A sample app (see code sample) will throw on line 3 when it initializes a TelemetryClient.

```
        static void Main(string[] args)
        {
            var tc = new TelemetryClient();
            tc.TrackTrace("this is a test");
        }
```

**Comment by cijothomas** [comment]
i see. I never knew SDK would actually throw an exception but instead log to EventSource.
So now the proposed change throws a better exception, right/

**Comment by TimothyMothra** [comment]
Exactly. I'm just replacing an exception that is already thrown with more meaningful details.

**Comment by cijothomas** [comment]
Thanks for clarifying!
