### ISSUE TITLE
Make TelemetryConfiguration.EnableW3CCorrelation static

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1198]
https://github.com/microsoft/ApplicationInsights-dotnet/blob/521a84dd529599305b74bdcd4027af2d7666a4e6/src/Microsoft.ApplicationInsights/Extensibility/TelemetryConfiguration.cs#L185-L201

The setter deals with static properties on Activity and having two different instances of configuration with different settings is not possible. 

So logically it should be static.

**Comment by lmolkova** [comment]
@cijothomas what do you think?

**Comment by cijothomas** [comment]
@lmolkova I guess we don't have any other neat option. I need to check how static properties behave when configured from AI.Config file.

Another option.
Completely remove this from TelemetryConfig, and have EnableW3C field on both RequestCollector and DependencyCollector. Similar to the current W3C enablement?

**Comment by cijothomas** [comment]
we ended with the following:

Removed the public setting from TelemetryConfiguration.
Make TelemetryConfiguration define a static ctor(), inside which it'll set format to W3C, if format is NOT enforced already.

For users deciding to turn it off, simply use Activity static methods.
Activity.Default = Hierrachical,
Activity.Enforce = true.
