### ISSUE TITLE
Review entire code base for possible unhandled exceptions and fix.

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1204]
Similar to whats discussed here, we should review the codebase entirely to make sure all paths are covered in try..catch..

https://github.com/microsoft/ApplicationInsights-dotnet/issues/1184

**Comment by cijothomas** [comment]
This must be done for other repos as well. We have seen an increasing number of cases recently where SDK is not handling all possible exceptions.

**Comment by cijothomas** [comment]
@TimothyMothra would you have time to review this before we ship stable?

**Comment by TimothyMothra** [comment]
I don't think it's feasible to do this task in a day. I propose moving this to 2.13
