### ISSUE TITLE
Azure Function 2.0 Does not deliver exceptions to App Insights

### ISSUE THREAD

**Issue by cdesewell** [microsoft/ApplicationInsights-dotnet#1212]
Azure Function 2.0 Does not deliver exceptions to App Insights, following this [guide ](https://blogs.msdn.microsoft.com/hmahrt/2017/02/17/richer-exception-details-in-application-insights-custom-exceptions/) and several others.

I've written the following method to report exceptions to app insights:

## Repro Steps

```
public void PublishOperationResult(Exception ex, string CustomMessage, Guid invocationId)
{
     var _client = new TelemetryClient
     {
         InstrumentationKey = "my-key"
     };

     _client.Context.Operation.Id = invocationId.ToString();
     _client.Context.Operation.Name = "SnapshottingViewsException";

     var exception = new ExceptionTelemetry(ex);

     var properties = new Dictionary<string, string>
     {
         {"CustomMessage", CustomMessage}
     };

     foreach (var property in properties)
     {
         exception.Properties.Add(property);
     }

     _client.TrackException(exception);
}
```

When calling the method I can see the exception being logged in the Visual Studio debug output but nothing appears in App Insights, both locally and on an azure consumption plan.

`Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.653f95d8909341b5a971eaa88c40606b.Exception","time": ...
`

##  Actual Behavior
Exceptions are not logged to app insights

## Expected Behavior
Exceptions with properties are logged to app insights

## Version Info 
SDK Version : 1.0.29
.NET Version : .Net Core  2.1.0
Microsoft.ApplicationInsights.AspNetCore Version: 2.7.1						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Windows 10 
Hosting Info :  Azure Functions Consumption Plan

**Comment by cdesewell** [comment]
Solved, sort of.

The exception in question that I was testing with came from an SQL client. When thrown up this is seen as an exception by AppInsights but when reported by the TelemetryClient its seen as a Dependency Error with a different message/title. And thus a little more difficult to spot.

**Comment by cijothomas** [comment]
Use the sample from here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-3. In your snippet, you are creating a new TelemetryClient - this is going to use different configuration and channel, etc, than the one used by Functions host. It is recommended to get TelemetryConfig from the DI, and re-use it in your telemetry client.

**Comment by TimothyMothra** [comment]
I'm closing this as resolved, but feel free to reopen if you have additional questions.
