### ISSUE TITLE
Version 2.11.0 introduced dependency on System.Memory

### ISSUE THREAD

**Issue by avivanoff** [microsoft/ApplicationInsights-dotnet#1219]
## Repro Steps
1. Create a project that target full .NET Framework.
2. Add a reference to Microsoft.ApplicationInsights 2.11.0.

##  Actual Behavior
Microsoft.ApplicationInsights.dll full framework assembly references System.Memory.dll  .NET Standard assembly.

## Expected Behavior
Microsoft.ApplicationInsights.dll full framework assembly should only reference full framework assemblies.

## Version Info 
SDK Version : 2.11.0
.NET Version : .NET Framewokr 4.8					
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Desktop application

**Comment by lmolkova** [comment]
https://www.nuget.org/packages/System.memory has .NET 45 target. And this dependency is by design.
Is there a particular problem with that?

**Comment by avivanoff** [comment]
> https://www.nuget.org/packages/System.memory has .NET 45 target. And this dependency is introduced by design.

There is no System.Memory assembly that targets full framework. The one that says it targets full framework, is still a .NET Standard assembly.


> Is there a particular problem with that?

The problem is that now we have to add more binaries to our desktop application installer. Not a big deal, but still.

**Comment by volthezz** [comment]
@lmolkova, shouldn't this dependency be added to .nuspec?
