### ISSUE TITLE
Tracking Additional Information

### ISSUE THREAD

**Issue by TonyValenti** [microsoft/ApplicationInsights-dotnet#1225]
Right now I use the following code to track metrics:
````
            var Config = new TelemetryConfiguration();
            Config.InstrumentationKey = ProductDefinitionExtension.Assembly_ApplicationInsights;
            Config.TelemetryChannel = new Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel();
            Config.TelemetryChannel.DeveloperMode = System.Diagnostics.Debugger.IsAttached;
            
            var Client = new TelemetryClient(Config);
            Client.InstrumentationKey = ProductDefinitionExtension.Assembly_ApplicationInsights;
            Client.Context.Component.Version = ProductDefinitionExtension.Assembly_Version;
            Client.Context.Session.Id = Guid.NewGuid().ToString();
            Client.Context.Device.OperatingSystem = Environment.OSVersion.ToString();

....
            Client.TrackMetric(new MetricTelemetry(e.Name, e.Value));

````

I have a few questions about this:
1.  When capturing the telemetry, I also want to record some additional information (for example, hard drive model).  How do I attach this arbitrary information?

2.  When submitting information, it seems like Application Insights submits a request every time I call "TrackMetric".  Is there a way to have it batch those together for better performance or is it sending a request per "TrackMetric" because I'm in developer mode?

**Comment by eduardomb08** [comment]
Tony, this does not answer your questions, but I noticed you're calling TelemetryConfiguration(). It's probably best to call TelemetryConfiguration.CreateDefault().

Best Regards,

Eduardo Monteiro de Barros

________________________________

**Comment by cijothomas** [comment]
1. You can add telemetry initializers to add any additional properties to telemetry. (https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#add-properties-itelemetryinitializer)

2.  Use https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#getmetric  - This aggregates telemetry. This is the recommended mechanism.

Btw, overall, you should use this approach: https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#net-corenet-framework-console-application  - Its sets up default configuration for you with out having to manually stitch together pieces.

**Comment by cijothomas** [comment]
> Tony, this does not answer your questions, but I noticed you're calling TelemetryConfiguration(). It's probably best to call TelemetryConfiguration.CreateDefault(). Best Regards, Eduardo Monteiro de Barros
> […](#)
> ________________________________ From: Tony Valenti <notifications@github.com> Sent: Thursday, September 26, 2019 19:05 To: microsoft/ApplicationInsights-dotnet <ApplicationInsights-dotnet@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [microsoft/ApplicationInsights-dotnet] Tracking Additional Information (#1225) Right now I use the following code to track metrics: var Config = new TelemetryConfiguration(); Config.InstrumentationKey = ProductDefinitionExtension.Assembly_ApplicationInsights; Config.TelemetryChannel = new Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel(); Config.TelemetryChannel.DeveloperMode = System.Diagnostics.Debugger.IsAttached; var Client = new TelemetryClient(Config); Client.InstrumentationKey = ProductDefinitionExtension.Assembly_ApplicationInsights; Client.Context.Component.Version = ProductDefinitionExtension.Assembly_Version; Client.Context.Session.Id = Guid.NewGuid().ToString(); Client.Context.Device.OperatingSystem = Environment.OSVersion.ToString(); .... Client.TrackMetric(new MetricTelemetry(e.Name, e.Value)); I have a few questions about this: 1. When capturing the telemetry, I also want to record some additional information (for example, hard drive model). How do I attach this arbitrary information? 2. When submitting information, it seems like Application Insights submits a request every time I call "TrackMetric". Is there a way to have it batch those together for better performance or is it sending a request per "TrackMetric" because I'm in developer mode? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FApplicationInsights-dotnet%2Fissues%2F1225%3Femail_source%3Dnotifications%26email_token%3DACZTD526B2K5ALYRW4ENSP3QLU53DA5CNFSM4I27663KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HOAQC7A&data=02%7C01%7C%7Caaa78bc30bf24dcf541d08d742d6021a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637051359230869828&sdata=8c0cDbHwNRzhSe0iLsywK2jDdz0FYy4M3HNqXHKclnI%3D&reserved=0>, or mute the thread<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZTD537FTQJY7SFJEK22L3QLU53DANCNFSM4I27663A&data=02%7C01%7C%7Caaa78bc30bf24dcf541d08d742d6021a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637051359230879840&sdata=DBnuGdKdTUXx6HFjYiRphDTNgbJ0Dq03n8RAfMbgjfk%3D&reserved=0>.

Infact, the recommendation is to NOT do that as well. Just get a telemetry client from DI as per this doc:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#how-can-i-track-telemetry-thats-not-automatically-collected

**Comment by eduardomb08** [comment]
Good to know. Thanks, Cijo.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
