### ISSUE TITLE
No debug telemetry in visual studio 2019 16.4.0 preview 1.0

### ISSUE THREAD

**Issue by woutervs** [microsoft/ApplicationInsights-dotnet#1229]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
Setup a new .NET Core 3.0 project in VS2019 16.4.0 P1.0
(.NET Core 2.1/2.2 shows the same behavior)
Add nuget package ApplicationInsights 2.11.4 (tried all version down until 2.6.4).
Use the following code:

```
        public static void Main()
        {
            Console.WriteLine("Hello World!");

            var telemetry = new TelemetryClient(new TelemetryConfiguration());

            telemetry.TrackTrace("Hello World");

            Console.ReadLine();
        }
```

##  Actual Behavior
No debug telemetry.

## Expected Behavior
Seeing debug telemetry inside visual studio

## Version Info 
SDK Version : 2.11.4 (Down to 2.6.4)
.NET Version :	3.0 (Down to 2.1) 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Win 10
Hosting Info (IIS/Azure WebApps/ etc) : Debug mode

## Aditional notes
Logging in debug mode actually works when an empty ApplicationInsights.config file is available in the project.

**Comment by cijothomas** [comment]
Visual Studio looks for applicationinsights output only for certain type of projects- Asp.Net, Asp.Net Core projects. Not for console apps.

**Comment by woutervs** [comment]
Okay so if this is intended behavior, why does it then work if I add an empty 'ApplicationInsights.config' file?

**Comment by cijothomas** [comment]
@woutervs Probably that's how VS integration works. Either way, this is not an SDK bug or issue. Closing this.

@woutervs I will send this issue to VS owners for their attention. (I dont know if they have any place for raising issues).

**Comment by vijayrkn** [comment]
This is the best way to report a problem for Visual Studio - https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019#report-a-problem
