### ISSUE TITLE
NWebSec, Content Security Policy & AI

### ISSUE THREAD

**Issue by naeemsarfraz** [Microsoft/ApplicationInsights-dotnet#123]
Is the client side script tracking code compatible with CSP's?

I'm struggling to configure it with the NWebSec nuget package.

    Refused to connect to 'http://dc.services.visualstudio.com/v2/track' because it violates the following Content Security Policy directive: "connect-src 'self'".

**Comment by SergeyKanzhelev** [comment]
Can you please give more details? Looking at documentation for NWebSec it seems to be possible to configure dc.services.visualstudio.com as an additional ```connect-src``` [source](https://docs.nwebsec.com/en/4.2/nwebsec/Configuring-csp.html#directives-in-web-config). Have you tried it?

**Comment by SergeyKanzhelev** [comment]
+ @MaxShehovtsov FYI

**Comment by naeemsarfraz** [comment]
Thank you, yes it is supported I was focused on script src and missed the fact that I needed to configure the connect-src.
