### ISSUE TITLE
Unhandled exception : Access violation reading location

### ISSUE THREAD

**Issue by NehaliSahu** [microsoft/ApplicationInsights-dotnet#1231]
Hi , we have encountering an app crash due to ApplicationInsights

**Error** : Unhandled exception at 0x00007FFA27E8F09F (clr.dll) in 09db8779-c257-4d7e-a7d6-61ef51e6723a__1295929914.hdmp: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

**Call Stack** :

mscorlib.dll!System.RuntimeTypeHandle.GetTypeByName(string name, bool throwOnError, bool ignoreCase, bool reflectionOnly, ref System.Threading.StackCrawlMark stackMark, System.IntPtr pPrivHostBinder, bool loadTypeFromPartialName) Line 620
at f:\dd\ndp\clr\src\BCL\system\runtimehandles.cs(620)
mscorlib.dll!System.Type.GetType(string typeName) Line 105
at f:\dd\ndp\clr\src\BCL\system\type.cs(105)
Microsoft.ApplicationInsights.dll!**Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.GetManagedType**(string typeName) Line 442
at E:\A\_work\743\s\src\Microsoft.ApplicationInsights\Extensibility\Implementation\TelemetryConfigurationFactory.cs(442)
Microsoft.ApplicationInsights.dll!**Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.LoadInstances**<Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer>(System.Xml.Linq.XElement definition, System.Collections.Generic.ICollection<Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer> instances, Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryModules modules) Line 271
at E:\A\_work\743\s\src\Microsoft.ApplicationInsights\Extensibility\Implementation\TelemetryConfigurationFactory.cs(271)
[Native to Managed Transition]
[Managed to Native Transition]
mscorlib.dll!System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(object obj, object[] parameters, object[] arguments) Line 761
at f:\dd\ndp\clr\src\BCL\system\reflection\methodinfo.cs(761)
mscorlib.dll!System.Reflection.RuntimeMethodInfo.Invoke(object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, object[] parameters, System.Globalization.CultureInfo culture) Line 735
at f:\dd\ndp\clr\src\BCL\system\reflection\methodinfo.cs(735)
Microsoft.ApplicationInsights.dll!Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.LoadInstance(System.Xml.Linq.XElement definition, System.Type expectedType, object instance, object[] constructorArgs, Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryModules modules) Line 194
at E:\A\_work\743\s\src\Microsoft.ApplicationInsights\Extensibility\Implementation\TelemetryConfigurationFactory.cs(194)
Microsoft.ApplicationInsights.dll!Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.LoadProperties(System.Xml.Linq.XElement instanceDefinition, object instance, Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryModules modules) Line 324
at E:\A\_work\743\s\src\Microsoft.ApplicationInsights\Extensibility\Implementation\TelemetryConfigurationFactory.cs(324)
Microsoft.ApplicationInsights.dll!Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.LoadInstance(System.Xml.Linq.XElement definition, System.Type expectedType, object instance, object[] constructorArgs, Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryModules modules) Line 184
at E:\A\_work\743\s\src\Microsoft.ApplicationInsights\Extensibility\Implementation\TelemetryConfigurationFactory.cs(184)
Microsoft.ApplicationInsights.dll!Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.LoadFromXml(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration configuration, Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryModules modules, System.Xml.Linq.XDocument xml) Line 151
at E:\A\_work\743\s\src\Microsoft.ApplicationInsights\Extensibility\Implementation\TelemetryConfigurationFactory.cs(151)
Microsoft.ApplicationInsights.dll!Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration configuration, Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryModules modules, string serializedConfiguration) Line 72
at E:\A\_work\743\s\src\Microsoft.ApplicationInsights\Extensibility\Implementation\TelemetryConfigurationFactory.cs(72)
Microsoft.ApplicationInsights.dll!Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active.get() Line 91
at E:\A\_work\743\s\src\Microsoft.ApplicationInsights\Extensibility\TelemetryConfiguration.cs(91)
Microsoft.AI.Web.dll!Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule.ApplicationInsightsHttpModule() Line 42
at E:\A\_work\147\s\Src\Web\Web.Shared.Net\ApplicationInsightsHttpModule.cs(42)

**Comment by cijothomas** [comment]
Please share sdk versions, where the app is hosted etc.

**Comment by lmolkova** [comment]
and could you please also provide your AppInsights config? Do you have any custom initializers set up there?
