### ISSUE TITLE
When 'ILogger' writes to AppIns, the LogLevel enum values for Debug and Trace are merged into Severity value Verbose.  I would like to filter out in my ITelemetryProcessor for level Trace

### ISSUE THREAD

**Issue by pb-qs** [microsoft/ApplicationInsights-dotnet#1232]
## Repro Steps

When an 'ILogger' writes to Application Insights, the LogLevel enum values for Debug and Trace are merged into the Severity value Verbose.  

I would like to filter out in my ITelemetryProcessor for level Trace.

Is there a way to add the LogLevel as an additional property to all ITelemetry ?

## Version Info 
SDK Version : 2.11.0.0
.NET Version :	ASP.NET Core 2.2.x 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Win 10
Hosting Info (IIS/Azure WebApps/ etc) :  local & Azure Web App

**Comment by cijothomas** [comment]
ApplicationInsights data model does not have Debug and Trace level, hence they are mapped in to Verbose level. (https://github.com/microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/ILogger/ApplicationInsightsLogger.cs#L128)

If you are looking to filter Ilogger logs, TelemetryProcessor is NOT the right way for Ilogger logs. Filtering is built-in in the logging framework, and can filter by Debug or Trace. The following doc has samples:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#control-logging-level

**Comment by pb-qs** [comment]
I wanted to protect against Trace type logs going to App Ins, by accidental change in appSettings.  Ie- sensitive data might exist on a trace level record.   

For now it appears I will have to block Debug too (if using the TelemetryProcessor).

**Comment by cijothomas** [comment]
Yes. If you are in telemetry processor, you are in AI realm and its data model apply. Its efficient to filter it out at logging infra level, without ever reaching application insights.

**Comment by pb-qs** [comment]
Sure, by default it'll be setup not to send Trace to App Ins (this is the belt and braces code for when someone changes config).

I guess I need to see if there's a way of filtering on the end of the logging process, before the AI code.  Thanks
