### ISSUE TITLE
AppInsights depends on Microsoft.AspNetCore.Hosting.IHostingEnvironment

### ISSUE THREAD

**Issue by ianjirka** [microsoft/ApplicationInsights-dotnet#1235]
I'd like a clarification of support based on this doc: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core

It implies that the only supported environment for AppInsights in dotnetcore is using the ASPNetCore WebHost.  I have some batch jobs that use ASPNet for configuration and DI and they didn't require a WebHost until now (and thus didn't have a startup, etc., which seems to be the recommended route now). I had been running with preview 8 and AI 2.9.1 previously.

Is it expected that AI depends on the presence of the WebHost now?

Thanks much?

## Repro Steps
public static IHostBuilder ConfigureTelemetry( this IHostBuilder builder)
        {
           return builder.ConfigureServices((context, services) => {
                        services.AddApplicationInsightsTelemetry(instrumentationKey);
                    });
        }

##  Actual Behavior
Works fine IFF 
hostBuilder.ConfigureWebHostDefaults((webHostBuilder) => {
                        // no-opt; simply required by App Insights.
                    });

is present, otherwise fails with
 System.InvalidOperationException : Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' while attempting to activate 'Microsoft.AspNetCore.Hosting.DefaultApplicationInsightsServiceConfigureOptions'.

## Expected Behavior
Should work without setting up a WebHost

## Version Info 
SDK Version : 3.0.100
.NET Version : DotNetCore 3.0 (final)
	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Manual
OS : Windows/Linux
Hosting Info (IIS/Azure WebApps/ etc) : Kubernetes

**Comment by cijothomas** [comment]
I think you should try and use the new Microsoft.ApplicationInsights.WorkerService package instead following the doc here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service
The aspnetcore package is tied too much into asp.net core and webhost, httpcontext etc. and fails if any are not present (as is the case for background jobs etc.)

**Comment by ianjirka** [comment]
Looks promising - thanks for the pointer!

**Comment by danpdc** [comment]
What about Blazor WebAssembly? The approach to use Microsoft.ApplicationInsights.WorkerService doesn't really help.

**Comment by rwb196884** [comment]
This is still broken; it is not possible to add application insights to a console application.

**Comment by pharring** [comment]
@rwb196884 here's the documentation for that: https://learn.microsoft.com/azure/azure-monitor/app/console
Did you try it? If so, what part is not working for you?

**Comment by JohannSig** [comment]
The WorkerService package (and the above instructions link for it) works, but you have to make sure none of your console program's dependencies are making the "normal" AddApplicationInsightsTelemetry() call on the side.
