### ISSUE TITLE
RichPayloadEventSourceEtwPayloadSerializationTest investigate failure

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1236]
failed with OutOfMemoryException once in the past 30 days.

After this OOM, test run continued! and other tests passed. 
[logs_10559249.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/3705015/logs_10559249.zip)

So it's either this test that might lead to OOM or there is some infra problem. Needs further investigation

```
Test method Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.RichPayloadEventSourceEtwPayloadSerializationTest threw exception:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

Stack trace
    at Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.RichPayloadEventSourceEtwPayloadSerializationTest()
```

**Comment by TimothyMothra** [comment]
I'm skeptical that's the real bug.
I've seen a lot of OOM exceptions suddenly this month.
