### ISSUE TITLE
Add SubStatusCode to RequestTelemetry

### ISSUE THREAD

**Issue by StormRider01** [microsoft/ApplicationInsights-dotnet#1246]
IIS Request Filtering will set SubStatusCodes for various operations: https://docs.microsoft.com/en-us/iis/manage/configuring-security/configure-request-filtering-in-iis

Of particular interest is 404.7- Request Filtering: File name extension denied
I'd like to filter these out of telemetry (I really don't need to instrument thousands of failed PHP requests) while still sending standard 404 responses.

**Comment by cijothomas** [comment]
closing as duplicated https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/382
