### ISSUE TITLE
Can't track custom telemetry

### ISSUE THREAD

**Issue by GenaVyb** [microsoft/ApplicationInsights-dotnet#1252]
Hey, 

I'm in the middle of the deployment of application insights.

I went step by step with the documentation: 
1) Added SDK to my project
2) Created App Insight resource.
3) Added instrumental key to my config.

plus I've added **custom** Exception and Metric tracking.

 TelemetryConfiguration.Active.InstrumentationKey = _instrumentationKey;
 var telemetryClient = new TelemetryClient(TelemetryConfiguration.Active);

I'm using in some places of my code :

telemetryClient .TrackMetric(metricTelemetry);
telemetryClient .GetMetric("MetricName").TrackValue(50);
telemetryClient .TrackException(exceptionTelemetry);
telemetryClient .TrackTrace(traceTelemetry);
telemetryClient .TrackEvent(eventTelemetry);

**when** I run my Website on my local machine, custom telemetry reported as expected.

**when** i deploy it t to Azure Cloud Services web role, i only see the telemetry from SDK and not my custom event/exception/metric tracking. 
On Live Metrics Stream i see all the regular graph are working well.

what am i missing? why can't i see my custom telemetry on my production environment?

AI version 2.11.0.0
.Net Framework 4.7
Azure Cloud Services Web Role

Thanks
Gena

**Comment by GenaVyb** [comment]
Any ideas?

**Comment by cijothomas** [comment]
PLease get the logs from non-working machine
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data#troubleshooting-logs

If cloud services, you can RDP to vm and run perfview as well to collect logs instead.


some quick thoughts:
How are you confirming that telemetry is not working? Have you confirmed that the code paths resulting in custom telemetry is being hit in your Prod environment?

**Comment by GenaVyb** [comment]
Hey, 
Thank you for your response

I've collected some logs by added logs section in my ApplicationInsights.config.
I confirm that custom telemetry is not working by looking at Live Metrics Monitor,
I run my app and i cannot see any custom telemetry that I'm send and I'm sending a lot.
When i run the app on-premise or in azure emulator, all the metrics, traces and exception are delivered and and i see it on the  Live Metrics Monitor.

Can you please give an instructions how should I use  **perfview** on Web Role instance with RDP.
 
also attached ApplicationInsights.config that i use

[log.txt](https://github.com/microsoft/ApplicationInsights-dotnet/files/3752742/log.txt)
[ApplicationInsights.config.txt](https://github.com/microsoft/ApplicationInsights-dotnet/files/3752744/ApplicationInsights.config.txt)

Thank you
Gena

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data#PerfView Perfview instructions. Please start perfview before you app starts (you can kill the process, start perfview, start the app again), and collect for 1 minute or so or perfviw.

Can you check if the missing data is available in search/analytics? This will isolate if this is just a LiveMetrics issue.

**Comment by GenaVyb** [comment]
Yeah, it's also missing in search and logs analytics.
I see only the out of the box data that comes from SDK, like requests and handled exceptions.
I'm going to deploy one instance on Cloud Service and start the prefview.
Do i need export file some file with the results or something?

**Comment by GenaVyb** [comment]
I've run the PerfView and I have the PerfViewData.etl zip file, but it's too big (31 Mb), how can I get this to you?
For 1 minute I've run only one operation that suppose to produce Exception (telemetryClent.TrackExceptoin)

**Comment by Dmitry-Matveev** [comment]
Unlike ASP.NET Core AI SDK, ASP.NET AI SDK should work fine with `TelemetryConfiguration.Active` and the issue appears to be environmental. (You also may skip `TelemetryConfiguration.Active` in the constructor of `TelemetryClient`, .NET version of `TelemetryClient` uses TC.Active by default)

Any chance of the different configuration settings jumping in? When deployed, another InstrumentationKey may jump in from ApplicationInsights.config file or from envrionment variable APPINSIGHTS_INSTRUMENTATIONKEY or from web.config (if you read it from web.config in `TelemetryConfiguration.Active.InstrumentationKey = _instrumentationKey;`).

Also, on the deployed web site you may have sampling kicked in and some of the custom telemetry as well as auto-collected telemetry can be sampled out if it's a part of the sampled out transaction (however, I'd still expect to see every instance of Metric Telemetry - metrics are not sampled).

Another possible issue is batching / flushing (typically does not affect web roles but worker roles, though..). If the process is existing before batch of 500 items is populated and before 30 seconds have passed, the telemetry is lost if not flushed forcefully. In debug mode locally, telemetry is emitted as soon as it's tracked (so-called `DeveloperMode`), so that's another thing to look at.

**Comment by GenaVyb** [comment]
@Dmitry-Matveev, Thank you for your reply.

1) I've just put this syntax to explain what I'm doing. I'm using the standard  syntax 
TelemetryClient telemetryClient = new TelemetryClient(); the configuration details are taken by the SDK from configs. (best practice in documentation).
2) I've double checked and i saw that I'm using the same key everywhere.
3) I've removed sampling from the ApplicationInsights.config. And you right metrics are not sampled and I also can't see my custom metrics.
4) For now I need to deploy it to Web Role only. As I understand I don't need to flush by myself, the SDK does it for me. I'm not using DeveloperMode in my web site. (I've used it when i was testing locally in some Console App).

* I would like to point that for current configurations(same AppInsights config and same Instrumental key), my web site is working **on-premise** and from azure **emulator** as expected. The issue is only when I deploy it to Cloud Service.

**Comment by GenaVyb** [comment]
@cijothomas , @Dmitry-Matveev 

I've just run the PerfView with details from 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data#PerfView
for 1 minute on web role. I've navigated to page called **SimulationForm.aspx**.
On **Page_Load(object sender, EventArgs e)** of that page I've added the next syntax : 

           
         **var _TelemetryClient = new TelemetryClient();
         var exceptionTelemetry = new ExceptionTelemetry();

            exceptionTelemetry.Exception = new Exception(iMessage);
            exceptionTelemetry.Message = iMessage;
            exceptionTelemetry.SeverityLevel = severityLevel;
            exceptionTelemetry.Properties.Add("UserId", iUserId?.ToString());
            exceptionTelemetry.Properties.Add("CategoryName", iAITrackObjectBase.CategoryName);

            _TelemetryClient.TrackException(exceptionTelemetry);**

Maybe you could see something that I'm missing there. 

[PerfViewData.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/3754188/PerfViewData.zip)

**Comment by GenaVyb** [comment]
Thank you for your help. 

Finally I've found the solution for this issue. 
It was logical in my code.

Thanks
Gena
