### ISSUE TITLE
Issue in corefx can cause an app to fail to close when using Application Insights

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#1255]
Applicaiton Insights is effected by https://github.com/dotnet/corefx/issues/41740. Until it picks up a version of CoreFx with the fix, users of AppInsights on OSX will not be able to close their applications with Ctrl-C, because a non-background thread was created when `NetworkAddressChanged` was set. This might sound a bit esoteric but it's a scenario that affects users.

1. If not OSX – no special logic
2. If not netstandard (FW 4.6) – no special logic
3. Check if the current runtime’s version is fewer than 3.1. If 3.1+ - no special logic
4. Otherwise:
    1. After subscribing to NetworkAddressChanged, reflect over System.Net.NetworkInformation.NetworkChange to get the thread out of the static field s_runLoopThread and set IsBackground=true
    2. If above failed for any reason - Unsubscribe to NetworkAddressChanged

**Comment by SergeyKanzhelev** [comment]
Code with the validators to narrow down the fix to affected platforms:

```
bool isMacOs = System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.OSX);
bool isNetCore = System.AppContext.TargetFrameworkName.StartsWith(“.NETCoreApp” , StringComparison.OrdinalIgnoreCase);
if (isMacOs && isNetCore && Environment.Version < new Version(3, 1, 0))
{
     // workaround https://github.com/dotnet/corefx/issues/41740 in .NET Core 3.0 and earlier
}
```

**Comment by SergeyKanzhelev** [comment]
Alternatively to using reflection - it was suggested that event handler may be removed at `AssemblyLoadContext.Unloading`.

**Comment by cijothomas** [comment]
Moving to next milestone as we have no bandwidth to address this in 2.12
