### ISSUE TITLE
Exception is not logged in Application Insights, targeting net472

### ISSUE THREAD

**Issue by carl-berg** [microsoft/ApplicationInsights-dotnet#1258]
I'm currently having some issues where logged exceptions are not showing up in application insights. The application is a windows service using NServiceBus targeting `net472` but using new project format, appsettings.json as configuration and Microsoft DI. Setup of AI and logging is done like this:
```csharp
serviceCollection.Configure<TelemetryConfiguration>(config =>
{
    // using Microsoft.Applicationinsights.WindowsServer.TelemetryChannel 2.10.0
    var channel = new ServerTelemetryChannel();
    config.TelemetryChannel = channel;
    config.TelemetryInitializers.Add(new MyCustomInitializer());
    channel.Initialize(config);
});

serviceCollection.AddLogging(builder => 
{
    builder.AddConfiguration(configuration.GetSection("Logging"));
    builder.AddConsole(o => o.IncludeScopes = true);
    builder.AddApplicationInsights(configuration["ApplicationInsights:InstrumentationKey"]);
});
```
And NServiceBus is configured like this
```csharp
// This gets logged to AI
logger.LogCritical(new Exception("Test exception"), "Testing exception logging");

// ... but these never show up in AIs (but are visible in Visual Studio output)
endpointConfiguration.Notifications.Errors.MessageHasBeenSentToDelayedRetries += (s, e) => 
  logger.LogCritical(e.Exception, "MessageHasBeenSentToDelayedRetries");
endpointConfiguration.Notifications.Errors.MessageHasFailedAnImmediateRetryAttempt += (s, e) => 
  logger.LogCritical(e.Exception, "MessageHasFailedAnImmediateRetryAttempt");
endpointConfiguration.Notifications.Errors.MessageSentToErrorQueue += (s, e) => 
  logger.LogCritical(e.Exception, "MessageSentToErrorQueue");

// If i remove the exception in the event handlers above and just log text it will also show up in AI, but not with the exception.
```
My hunch is that ApplicationInsights somehow treat these exceptions as handled and never sends them. I have read about setting `EnableAllExceptions` to true, but i'm not sure where i can configure this programatically as i don't have a `ApplicationInsights.config` -file.

**Comment by cijothomas** [comment]
ApplicationInsightsLoggerProvider is whats collector ilogger logs/exceptions. AI SDK doesn't have any notion on treating exceptions as unhandled. 

I don't know what you mean by "visible in Visual Studio output" - can you elaborate with screenshots? Are they AI output? If you see if it in Visual Studio, but not in portal, then its ikey issue or sampling elimination.

**Comment by carl-berg** [comment]
Upgrading to NServiceBus 7.2.0 seems to solve this issue. No idea why though...

**Comment by cijothomas** [comment]
I don't think there is any question about application insights here anymore, closing. Please re-open if there are pending questions from application insgiths.
