### ISSUE TITLE
Improve supportability regarding Invalid Instrumentation Keys

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1260]
**Problem**
Customers are affected when the SDK does not report invalid instrumentation keys.

**Out of Scope**
- Note that the SDK cannot validate an ikey. The SDK is able to send to multiple ingestion services so it must be the responsibility of those ingestion services to validate keys. Http response codes are emitted in ETW logs.

**Changes**
- The TelemetryConfiguration factory will now report if an Ikey was not found in either the config file or environment variables. **DONE** https://github.com/microsoft/ApplicationInsights-dotnet/pull/1187 (This was shipped in 2.12-Beta1)
https://github.com/microsoft/ApplicationInsights-dotnet/blob/7633ae849edc826a8547745b6bf9f3174715d4bd/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/TelemetryConfigurationFactory.cs#L470-L489

- The `TelemetryConfiguration.InstrumentationKey` currently throws an exception when set to null. 
This will be changed to include empty strings and illegal characters. 
https://github.com/microsoft/ApplicationInsights-dotnet/blob/7633ae849edc826a8547745b6bf9f3174715d4bd/BASE/src/Microsoft.ApplicationInsights/Extensibility/TelemetryConfiguration.cs#L145-L150

**Comment by phatcher** [comment]
@TimothyMothra Regarding making empty string invalid, how does this affect the use case of running locally with no key so Visual Studio enables telemetry but doesn't forward it to an AI instance?

**Comment by TimothyMothra** [comment]
Hi @phatcher, thanks for the reminder. I'll test this scenario.

My change here only throws an exception if a user tries to explicitly set an empty string. if you're leaving the key property empty by default, nothing should change. :)

**Comment by SergeyKanzhelev** [comment]
@TimothyMothra the question remains - what would be the customer experience look like? One may want to disable telemetry when running locally and do it programmatically.

**Comment by SergeyKanzhelev** [comment]
Also, if ikey is set from config file and config file is broken - is it OK to just crash startup of an app?

**Comment by TimothyMothra** [comment]
for 2.12, I'm expanding ETW logs to report when an Instrumentation Key is missing or misconfigured.

for 2.13, I'm considering an Environment Variable driven "diagnostic mode" that would auto-inject our FileWritter that saves ETW events to text file. 
This would be opt-in as needed and allow users to collect ETW traces that otherwise wouldn't be accessible.

**Comment by cijothomas** [comment]
Can we close this? as we now add ETW log?

**Comment by cijothomas** [comment]
We have this item tagged for next milestone to further improve the scenario: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1059
