### ISSUE TITLE
Transmission.cs: use IHttpClientFactory and a named client

### ISSUE THREAD

**Issue by espenrl** [microsoft/ApplicationInsights-dotnet#1273]
`Transmission.cs` uses a single static HttpClient. That makes it hard to configure the HttpClient for proxying requests.

As per Microsoft best practice a named HttpClient should be used together with `IHttpClientFactory`.

https://github.com/microsoft/ApplicationInsights-dotnet/blob/70e438848915ec163fd7794221b27be34260d3b4/BASE/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L22

Configuration would then be like

``` CSharp
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddHttpClient(Transmission.HttpClientName)
        .AddHttpMessageHandler<CustomProxyRequestHandler>();
}
```

where `CustomProxyRequestHandler` is custom code to configure proxying.

See [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.0). The code should apply to .NET Core, not just ASP.NET Core.

**Comment by cijothomas** [comment]
This is planned to be addressed and is feature ask.
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/441

**Comment by KrothuTheCoder** [comment]
Hello, is there any update on when this might be addressed?

**Comment by TimothyMothra** [comment]
Sorry, I don't have an update to share at this time.
Reworking the channels is the very highest item on our backlog but our team hasn't had the bandwidth to address it.
Please continue upvoting these issues, this helps us prioritize tasks.
