### ISSUE TITLE
AspNetCore package doesn't enable ILogger logging for .NetFramework v4.6

### ISSUE THREAD

**Issue by jorupp** [microsoft/ApplicationInsights-dotnet#1277]
Tested with 2.8.2, but the dependencies for 2.12.0-beta1 look similar.

The `.NETStandard, Version=v2.0` build for `Microsoft.ApplicationInsights.AspNetCore` includes `Microsoft.Extensions.Logging.ApplicationInsights` as a dependency, but `.NETFramework, Version=v4.6` doesn't.  Manually adding `Microsoft.Extensions.Logging.ApplicationInsights@2.11.0` (which is a `.NETStandard, Version=v2.0` library) and calling the registration manually works fine. 
 ie.
```
services.AddLogging(loggingBuilder =>
    {
        loggingBuilder.AddApplicationInsights();
    });
```

https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#aspnet-core-applications doesn't make any mention of this 2.7.0-beta3 and newer behavior not being supported for .NETFramework apps.

And yes, my app is ASP.Net Core 2.2 on Framework 4.6, which is why I noticed.  There's a workaround, but if this is intended, I can open a bug on the docs instead to reflect that.

**Comment by cijothomas** [comment]
Note

The new provider is available for applications that target NETSTANDARD2.0 or later. If your application targets older .NET Core versions, such as .NET Core 1.1, or if it targets the .NET Framework, continue to use the old provider.


There is this note. I hoped it'd have hinted you about this.

**Comment by jorupp** [comment]
Thanks for pointing that out @cijothomas - I didn't notice it because I wasn't migrating from an old version of the provider, and that's the section where the note is.  I'll open an issue on the docs then - thanks for the quick followup.
