### ISSUE TITLE
Add cloud location to telemetry context

### ISSUE THREAD

**Issue by DavidParks8** [microsoft/ApplicationInsights-dotnet#1279]
AzureInstanceComputeMetadata has a location field which my team is very interested in sending as a dimension in every metric and trace. Are there any objections to adding a field with that value somewhere in the TelemetryContext?

**Comment by cijothomas** [comment]
You can store it in custom properties now itself, without requiring any change in application insights sdk.

**Comment by DavidParks8** [comment]
Yes, but the class which retrieves it is internal. I would rather not have to reimplement it.
