### ISSUE TITLE
Log request body in Azure Functions

### ISSUE THREAD

**Issue by nhart12** [microsoft/ApplicationInsights-dotnet#1280]
Same as this issue 
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/940

The recommended workaround was to use a custom middleware as a workaround as the ITelemetryInitializer was now only being called once at the end of the request when the requestbody stream was already disposed.
I am however using an Azure function, is there a way to accomplish the same but in an azure function where I cannot inject middleware?

My initial thought is to modify the Microsoft.ApplicationInsights.AspNetCore.DiagnosticListeners.HostingDiagnosticListener class to store the requestbody in a memory stream from the OnHttpRequestInStart event handler. I believe it's possible to call StoreRawObject on the TelemetryContext and later retrieve that stream in a telemetry initializer?

**Comment by cijothomas** [comment]
Any chance you can log the request body using ilogger and have applicationinsights capture the log?

**Comment by nhart12** [comment]
Yeah that's what the workaround is currently, would be nice to log requests also when the azure function bindings fail, 401's, etc

**Comment by cijothomas** [comment]
We are tracking a work item for likely 2020 execution - https://feedback.azure.com/forums/357324-azure-monitor-application-insights/suggestions/13949925-add-support-for-viewing-raw-body-requests
Until then Ilogger workaround is the only option :(

**Comment by cijothomas** [comment]
Closing as we have a duplicate item for Application Insights already: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1880

This is not planned for this year 2020.

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0 .New middleware from asp.net core 6.0 makes this easy to do.
