### ISSUE TITLE
Exception messages are traced in a wrong locale

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-dotnet#129]
Internal telemetry collected by SDK must be InvariantCulture.
Examples:

TelemetryInitializer_Microsoft.ApplicationInsights.Web.AccountIdTelemetryInitializer_filed_to_initialize_telemetry_item_System.IndexOutOfRangeException:_Индекс_находился_вне_границ_массива

[msg=Log_Error];[msg=System.AggregateException:_One_or_more_errors_occurred._--->_System.Exception:_要求されたオブジェクトが存在しません。_(HRESULT_からの例外:0x80010114)_____at_Windows.Storage.StorageFile.GetBasicPr

[msg=DependencyOperationTelemetryInitializerFailed];[msg=System.NullReferenceException:_La_référence_d'objet_n'est_pas_définie_à_une_instance_d'un_objet._____à_PSellerProfil_Web.UserIDTelemtry

**Comment by SergeyKanzhelev** [comment]
Caveat here is that at times we didn't want to use [ToInvariantString](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/ed10e183ffb27eeaa7b54cca2197a3032d71ca9a/src/Core/Managed/Shared/Extensibility/Implementation/Tracing/Extensions.cs#L18) for desktop, phone and store applications as were not sure implications of setting (even temporarily) thread culture to invariant culture. So we were using this method only from server SDK. We might keep doing this only for 4.0 & 4.5 versions of SDK or doublecheck with somebody from CLR on possible implications.

**Comment by abaranch** [comment]
With cutting devices support we should be fine without ifdefs

**Comment by abaranch** [comment]
Fixed #142
