### ISSUE TITLE
ExceptionTelemetry Unexpected Behavior

### ISSUE THREAD

**Issue by spresnal** [microsoft/ApplicationInsights-dotnet#1294]
Code that produces the error:

            ExceptionTelemetry telemetry = new ExceptionTelemetry();
            telemetry.Context.Operation.Id = inspectionId;
            telemetry.Context.Operation.Name = operationName;
            telemetry.SeverityLevel = level;
            telemetry.Message = message;
            telemetry.Exception = exception;
            _client.TrackException(telemetry);

When setting the telemetry.Message field using the above code, all of the Context properties get **wiped out**  (nulled). This is not expected behavior when setting the message property.

To make the code work I had to rearrange the lines so that setting message came earlier in the operation like so:

            ExceptionTelemetry telemetry = new ExceptionTelemetry();
            telemetry.SeverityLevel = level;
            telemetry.Exception = exception;
            telemetry.Message = message;
            telemetry.Context.Operation.Id = inspectionId;
            telemetry.Context.Operation.Name = operationName;
            _client.TrackException(telemetry);

**Comment by cijothomas** [comment]
Thanks for reporting!
Its not Message. Its Exception which clears context. 
@SergeyKanzhelev Do you know if this is expected behavior?

**Comment by cijothomas** [comment]
I'll tag this as a bug, as I cannot think of reason why setting Exception would intentionally clear context.
