### ISSUE TITLE
Custom ConfigurationProviders are not respected

### ISSUE THREAD

**Issue by GeeWee** [microsoft/ApplicationInsights-dotnet#1297]
I would like to keep my InstrumentationKey in a configuration file that's not `Appsettings.json` or `Appsettings.Development.json`, but rather something else. This is currently not possible out-of the box. An example:

```csharp
//Program.cs
//Inside CreateHostBuilder
	config.AddJsonFile("myfile.json", false, true);
}

//Startup.cs inside configureServices
services.AddApplicationInsightsTelemetry();

// Later in an injected service
// This is injected in
IOptionsMonitor<TelemetryConfiguration> _telemetryConfiguration;

// This returns an empty string
var instrumentationKey = _telemetryConfiguration.CurrentValue.InstrumentationKey;
```

I think the mistake is in `DefaultApplicationInsightsServiceConfigureOptions.cs`
on line 38, where no matter what, the configuration passed further only reads from `Appsettings` files, and environment variables.

This happens even though i explicitly provide my configuration in `Startup.cs` 
```csharp
// Like this, where Configuration is the "correct configuration from Startup.cs
services.AddApplicationInsightsTelemetry(Configuration);
```

However if I explicitly provide the instrumentation key from the configuration it works
```csharp          

services.AddApplicationInsightsTelemetry(Configuration["ApplicationInsights:InstrumentationKey"]);

```

This is an ASP.Net core 3.0 project

**Comment by cijothomas** [comment]
The default behaviour when using .AddApplicationInsightsTelemetry() is to read settings from appsettings.json only.

If you have your settings in a different place, then AddApplicationInsightsTelemetry(IConfiguration config), should be used. The instrumentation key should be in the order ApplicationInsights:Instrumentationkey inside the configuration.

Its not clear to me what do you meant by "explicitly provide the insturmentation key from the configuration it works".

Duplicate:
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/867

**Comment by GeeWee** [comment]
Fair enough - I don't think that's very clear from the documentation.

You're right that it's a duplicate. Previously when passing the Configuration explicitly, I still wasn't able to register the InstrumentationKey, or so I thought - but I must have been mistaken, as it works when testing today.
Thanks for the help.

**Comment by cijothomas** [comment]
Agree. The doc does not mention AddApplicationInsightsTelemetry(IConfiguration). The 1st phase was to have some doc at least, then improve it.
Will be improving docs with advanced options.

Thanks for your time.
