### ISSUE TITLE
Question: Is it possible to set 'Browser version'

### ISSUE THREAD

**Issue by NenoLoje** [microsoft/ApplicationInsights-dotnet#1304]
From a **.NET Core CLI** app, it's easy to set context properties and, for example, set the operating system:

``` csharp
tc.Context.Device.OperatingSystem = Environment.OSVersion.ToString();
```

That data can be seen on the portal:

![ai-how-to-set-browser-version](https://user-images.githubusercontent.com/13981145/68855284-35013780-06de-11ea-8302-5e5e11a32006.png)

Is it also possible to set the "**Browser version**"?

Thanks!
--Neno

**Comment by cijothomas** [comment]
Dont think its possible in serverside sdk. It'd be a js/client sdk concept.
