### ISSUE TITLE
Application Insights provides misleading picture by introducing fake "Execute request handler" requests

### ISSUE THREAD

**Issue by zakimaksyutov** [microsoft/ApplicationInsights-dotnet#1309]
My web site was completely down for some period of time but Application Insights made us think that some requests were succeeding (leading us to wrong theory, and delaying mitigation):

![image](https://user-images.githubusercontent.com/15914532/68966338-b1ede900-0792-11ea-8b6c-fc0068b89572.png)

After we opened web app view then it became clear that there were no successful requests during this time:

![image](https://user-images.githubusercontent.com/15914532/68966388-d053e480-0792-11ea-8c9e-400bfa9c7642.png)

Looks like that Application Insights always creates a fake "Execute request handler". These requests are always marked as succeeded:

![image](https://user-images.githubusercontent.com/15914532/68966617-6720a100-0793-11ea-91cc-d7ed1559ab40.png)

This also explained why Application Insights showed twice as much traffic than it really was.

We use the following version:

`  <package id="Microsoft.ApplicationInsights" version="2.10.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.4.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.10.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.10.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.10.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.10.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.10.0" targetFramework="net461" />
`

**Comment by lmolkova** [comment]
We have removed 'Execute request handler' requests in AppInsights 2.11.0. They initially intend to workaround the correlation issue for POST requests https://github.com/microsoft/ApplicationInsights-dotnet-server/pull/898 and they have their own limitations. The latest version solves the issue without introducing intermediate requests.

I'm closing this issue and there is no further action item. Feel free to reopen as needed.

**Comment by zakimaksyutov** [comment]
Upgraded to 2.11 and everything works as expected now! Thank you! =)

**Comment by agelenava** [comment]
Hi! 
I just faced the same issue. I see 'Execute request handler' for each request in AI 

![image](https://user-images.githubusercontent.com/7485440/104100743-43c98700-52ae-11eb-89ca-7cafc21e9c05.png)

We use AI version 2.13.1
![image](https://user-images.githubusercontent.com/7485440/104100969-55ab2a00-52ae-11eb-890f-b5a0868b3624.png)

Is there a way to turn off this 'fake' event?
Thank you in advance.

**Comment by sachetpatil1** [comment]
@agelenava Did u got any solution to eliminate this 'Execute request handler' events? We are using 2.16 version.

**Comment by sachetpatil1** [comment]
> Upgraded to 2.11 and everything works as expected now! Thank you! =)

@zakimaksyutov Is this only works on 2.11 version? We are using ApplicationInsights 2.16 version. But still 'Execute request handler' showing up for each request.
