### ISSUE TITLE
Provide AddApplicationInsightsTelemetry(bool AddLoggingProvider) 

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1310]
Propose to add a overload to AddApplicationInsightsTelemetry() method which takes a bool - AddLoggingProvider, based on which ApplicationInsightsLoggingProvider should be added or not. This is different from adding ApplicationInsightsLoggingProvider and then filtering so it wont get any logs.

See the original issue:
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/854#issuecomment-541266478

**Comment by zvolkov** [comment]
Workaround:

```
    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Logging.ApplicationInsights;

...
            services.AddApplicationInsightsTelemetry();

            // Remove AI logger provider that causes a circular dependency error.
            var serviceDescriptor = services.SingleOrDefault(
                s => s.ServiceType == typeof(ILoggerProvider) && s.ImplementationType == typeof(ApplicationInsightsLoggerProvider));
            if (serviceDescriptor != null)
            {
                services.Remove(serviceDescriptor);
            }
```
