### ISSUE TITLE
Enable ILogger provider for apps targetting .NET Framework

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1312]
This (https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/853) enables ilogger by default for NETSTANDARD20. The project also targets NET46, and we need to ensure that apps targeting .net framework also should be able to use this change.

**Comment by SergeyKanzhelev** [comment]
Change here: https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/LOGGING/src/ILogger/ILogger.csproj#L3 and make sure everything builds

**Comment by cijothomas** [comment]
SInce msft.extension.logging is only targetting netstandard2.0, we need to target net461 (or net472) in ilogger to consume it. This means aspnetcore project (which targets net45, net46) should additionally target net461 (or net472) - and enable auto ilogger integration for netstandard20 and net461(or net472).
This makes ilogger integration work well with .net core app targeting netet461 (or net472). We wont support older targets like net45 or net46.

**Comment by cijothomas** [comment]
2.14.0-beta5 should have this. 
Thanks @eddynaka and @rajkumar-rangaraj
