### ISSUE TITLE
`ILogger.LogError(Exception, string)` results in incorrect exception message in AppInsights

### ISSUE THREAD

**Issue by richardszalay** [microsoft/ApplicationInsights-dotnet#1325]
```xml
<PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.9.1" />
```

Steps to reproduce:
1. Setup a basic ASP.NET Core application
2. Configure AI using `services.AddLogging(c => c.AddApplicationInsights())`
3. Throw an Exception with the message "Actual exception message"
4. Catch the exception and log it to an injected `ILogger` using `logger.LogError(ex, "Contextual message")`
5. Review the exception in AI

Expected:

Both "Contextual message" and "Actual exception message" are presented in the `exception` object in AI

Actual:

Only "Context message" is included. The actual exception message is lost.

**Comment by cijothomas** [comment]
@richardszalay Can you use the latest (2.11.0) of the package and see if this is an issue?

**Comment by cijothomas** [comment]
There was this change: https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/282

**Comment by btastic** [comment]
Is this related to this: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1807?

I am currently investigating why we don't see any exceptions when Logging with `LogInformation(ex, "message")` either.

AI Version: `<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.14.0" />`
This is our code:

```
public async Task<bool> IsAvailableAsync()
{
	try
	{
		var response = await externalService.GetSomething();

		if (!string.IsNullOrEmpty(response.id))
		{
			return true;
		}
	}
	catch (TimeoutException)
	{
		_logger.LogInformation("Timeout exception when checking for ServiceAvailability.");
		return false;
	}
	catch (Exception ex)
	{
        // this happens, but AI is not logging exceptions
		_logger.LogWarning(ex, "Exception when checking for ServiceAvailability");
		return false;
	}

	return false;
}
```

Here is the details page of the "exception" log:
![image](https://user-images.githubusercontent.com/6894999/88863610-89fcc380-d203-11ea-9d33-7154e0156d95.png)

Is there anything we can do to solve this?

**Comment by joaopgrassi** [comment]
Just FYI, I hit this a while ago where Information logs were not being found on App Insights and it's due to this: https://github.com/MicrosoftDocs/azure-docs/issues/52657. Basically the ApplicationInsights log provider does not inherit from the "Default" log levels/categories.

**Comment by cijothomas** [comment]
@btastic Trying to understand the issue you are reporting more:
The following is your code:
```
// this happens, but AI is not logging exceptions
_logger.LogWarning(ex, "Exception when checking for ServiceAvailability");
```

ApplicationInsights is capturing the above as a TraceTelemetry and not as ExcepionTelemetry - is this what you are experiencing?

**Comment by chigivigi** [comment]
@cijothomas that is happening in my azure function. I am sending a LogError message, but it is written as a Trace in ApplicationInsights. 

Azure Function v3, netcore 3.1

**Comment by cijothomas** [comment]
> @cijothomas that is happening in my azure function. I am sending a LogError message, but it is written as a Trace in ApplicationInsights.
> 
> Azure Function v3, netcore 3.1

For functions - please post it in Functions repo, as Functions use a different integration with applicationinsights.

**Comment by abisleem** [comment]
> > @cijothomas that is happening in my azure function. I am sending a LogError message, but it is written as a Trace in ApplicationInsights.
> > Azure Function v3, netcore 3.1
> 
> For functions - please post it in Functions repo, as Functions use a different integration with applicationinsights.

This is actually happening to me on .AspDotNetCore on .NetCore 3.1

![image](https://user-images.githubusercontent.com/69599457/164566959-5c66b485-13f1-4856-9758-5e5cdc34eddd.png)


![image](https://user-images.githubusercontent.com/69599457/164566983-12d6bd43-0331-4ea5-b8ba-197f2fc2aea8.png)

**Comment by cijothomas** [comment]
> > > @cijothomas that is happening in my azure function. I am sending a LogError message, but it is written as a Trace in ApplicationInsights.
> > > Azure Function v3, netcore 3.1
> > 
> > 
> > For functions - please post it in Functions repo, as Functions use a different integration with applicationinsights.
> 
> This is actually happening to me on .AspDotNetCore on .NetCore 3.1
> 
> ![image](https://user-images.githubusercontent.com/69599457/164566959-5c66b485-13f1-4856-9758-5e5cdc34eddd.png)
> 
> ![image](https://user-images.githubusercontent.com/69599457/164566983-12d6bd43-0331-4ea5-b8ba-197f2fc2aea8.png)

Please open a new issue in this repo, with the exact description of the expected behavior vs actual.

**Comment by abisleem** [comment]
I see that this unexpected behavior is brought up here as well #2471. I won't open a new issue to avert from creating duplicates.
