### ISSUE TITLE
Can't read request telemetry in unit test

### ISSUE THREAD

**Issue by lindgrend** [microsoft/ApplicationInsights-dotnet#1330]
Hello,

We are adding tests for a middle-ware that will output request and response bodies when requests fails. Our approach was to fake the TelemetryChannel which we found working examples of. Now this logs the TraceTelemetry just fine but not the RequestTelemetry (Well technically it does but after the test has passed the assertion). We tried flushing the TelemetryClient but that didn't seem to solve anything. 

A minimal repro can be found @ https://github.com/lindgrend/ApplicationInsightsTestingIssue to highlight our problem, any help would be appreciated.

**Comment by cijothomas** [comment]
While a repro is great, I am not sure what is the issue you are facing. Please describe the issue you are facing in terms of whats expected vs whats actual behavior.

**Comment by lindgrend** [comment]
Expected: When the test is run and the assertion is executed, there should be a RequestTelemetry in the SentRequestTelemetries collection.

Actual: The TelemetryChannel.Send() with the expected RequestTelemetry is called after the test has executed the assertion hence the test fails.

Hope that this clears up what I meant.
