### ISSUE TITLE
ApplicationInsight log traces creating memory dump 

### ISSUE THREAD

**Issue by SABARISHV06** [microsoft/ApplicationInsights-dotnet#1332]
We are using telemetry client & configuration in common class library and accessing across the application. Below is my code snippet

```
private static TelemetryConfiguration configuration;
private static TelemetryClient telemetryClient;

        public Constructor(string appInsightKey, string trackingId = "")
        {
            configuration = TelemetryConfiguration.CreateDefault();
            configuration.InstrumentationKey = appInsightKey;
            TrackingId = trackingId;
            if (telemetryClient == null)
            {
                telemetryClient = new TelemetryClient(configuration);
            }
        }
        public void Info(string message)
        {
            try
            {
                telemetryClient.Context.Operation.Id = TrackingId;
                telemetryClient.TrackTrace(message, SeverityLevel.Information);
            }
            catch (Exception ex)
            {
                telemetryClient.TrackTrace(ex.Message, SeverityLevel.Error);
            }
        }
```
this is working fine & logging into app-insights. But on debugging the performance, we ran the memory dump in Azure app service and we could find lot of telemetry thread issues: 

Below are the repeated error in memory dump analyzer: 
> Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.Runner()+
> Microsoft.ApplicationInsights.Metrics.DefaultAggregationPeriodCycle.Run()+
> Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.StateThreadWorker
> Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.QuickPulse.Helpers.QuickPulseThreadModuleScheduler+State.Worker()
 
Was this a buggee in the DLL or 
Am I doing wrong way of implementation? kindly suggest me to get rid of the telemetry issue

Microsoft.ApplicationInsights version: 2.11.0.0
.Net framework: 4.6.1

**Comment by SABARISHV06** [comment]
@cijothomas any help on this issue?

**Comment by cijothomas** [comment]
@SABARISHV06 What is the **issue** here? Is application insights crashing your app? or leaking memory? or something else? 
I can see application insights threads - that's part of SDK.

**Comment by SABARISHV06** [comment]
@cijothomas we are not facing any crash, but we are seeing memory leak in the memory dump analysis. 
Error we got is thread is waiting in a WaitMultiple
ntdll!ZwWaitForMultipleObjects+c 
KERNELBASE!WaitForMultipleObjectsEx+f0 
clr!WaitForMultipleObjectsEx_SO_TOLERANT+3c 
clr!Thread::DoAppropriateWaitWorker+237 
clr!Thread::DoAppropriateWait+64 
clr!WaitHandleNative::CorWaitOneNative+163 
mscorlib_ni!System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean)+21 
mscorlib_ni!System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean)+21 
mscorlib_ni!System.Threading.WaitHandle.WaitOne(System.TimeSpan, Boolean)+60 
mscorlib_ni!System.Threading.WaitHandle.WaitOne(System.TimeSpan, Boolean)+60 
mscorlib_ni!System.Threading.WaitHandle.WaitOne(System.TimeSpan)+17 
mscorlib_ni!System.Threading.WaitHandle.WaitOne(System.TimeSpan)+17 
**Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.Runner()**+7b 
mscorlib_ni!System.Threading.Tasks.Task.InnerInvoke()+28 
mscorlib_ni!System.Threading.Tasks.Task.Execute()+30 

was our understanding is wrong?

**Comment by cijothomas** [comment]
This thread is part of normal operation. Transmitter sends telemetry once every 30 secs or once 500 items are buffered. Why do you think there is memory leak?

**Comment by SABARISHV06** [comment]
@cijothomas thanks for the clarification, but still i am not clear why the below threads are been created, 

Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.StateThreadWorker(System.Threading.CancellationToken)+50a
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.QuickPulse.Helpers.QuickPulseThreadModuleScheduler+State.Worker(System.Object)+45

And I could see **two** Channel.Inmemory thread, 
Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.Runner()+
Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.Runner()+ it is mean that if we have more number(500+) of traces in buffer will it create a new thread? orelse we are not closing the channel properly? 
 
Please clarify, we are predicting it was the cause of the High CPU utilization & slowness of the application.

**Comment by cijothomas** [comment]
Like in mentioned earlier, those threads you see are part of normal SDK operation. I don't see any "leak" here. (If the # of threads like this is increasing over time to 10 or 100s - then I can understand its a leak)

Channel does not create threads per 500 items. Just once.
(I can't tell for sure why are you seeing 2 Runners - most likely one channel was created and not disposed)

**Comment by SABARISHV06** [comment]
@cijothomas Do you know how to dispose the channel? any references would be highly helpful

**Comment by cijothomas** [comment]
channel implements `IDisposable` so you can just call `Dispose`. 
However, I don't think that extra channel lying around is causing the perf issues.

**Comment by SABARISHV06** [comment]
@cijothomas we are also getting below .NET Exceptions Report on the memory dump. Do you let us know what we are missing? 

System.Net.WebException | 19 | The operation has timed out | System.Net.HttpWebRequest.GetResponse()    Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.QuickPulse.QuickPulseServiceClient.SendRequest(System.String, Boolean, System.String, System.String, Microsoft.ApplicationInsights.Extensibility.Filtering.CollectionConfigurationInfo ByRef, System.Action`1<System.IO.Stream>)
-- | -- | -- | --
System.ObjectDisposedException | 60 | Cannot access a disposed object. | System.Net.HttpWebRequest.GetResponse()    Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.QuickPulse.QuickPulseServiceClient.SendRequest(System.String, Boolean, System.String, System.String, Microsoft.ApplicationInsights.Extensibility.Filtering.CollectionConfigurationInfo ByRef, System.Action`1<System.IO.Stream>)
fyr, 
![image](https://user-images.githubusercontent.com/16812919/71586294-b6eada00-2b3f-11ea-9702-880522ca10e8.png)

**Comment by TimothyMothra** [comment]
For context, this is the method in the call stack:

https://github.com/microsoft/ApplicationInsights-dotnet/blob/35e4bb2624bcbe2af9fb5d1e724b28ffd49c460c/WEB/Src/PerformanceCollector/Perf.Shared.NetFull/Implementation/QuickPulse/QuickPulseServiceClient.cs#L123-L162

**Comment by rajkumar-rangaraj** [comment]
Closing the ticket as out of date. If you're still having issues, please reopen.

**Comment by bensmind** [comment]
We ran into the same issue, the confusion was around the fact that it's not the `TelemetryClient` causing the issue rather, it was instances of `TelemetryConfiguration` that were not wrapped with a `using`. Once this was added our memory leak went away
