### ISSUE TITLE
Add ability to turn off SQL query logging for Azure Functions

### ISSUE THREAD

**Issue by pzbyszynski** [microsoft/ApplicationInsights-dotnet#1334]
Just wanted to make sure this issue will not get lost during repo migration: https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/980 

Inability to turn off SQL logging generates privacy & cost issues

**Comment by andrewleader** [comment]
Yeah I need to turn off logging (I'd like to turn off dependency tracking in general) for my Azure Functions. It's costing me a boat load and I never look at that info. How do I do it?

**Comment by lmolkova** [comment]
@andrewleader for functions you could disable all dependency tracking in host.json with something like:

```json
{
  "logging": {
    "applicationInsights": {
      "enableDependencyTracking": false
    }
  }
}
```

This is **not** applicable to ApplicationInsights ASP.NET Core SDK in general and there is no way to disable SQL collection only

**Comment by andrewleader** [comment]
Thanks @lmolkova, but that doesn't seem to be working. I've made that change and deployed it, 20 minutes later here's the telemetry event

![image](https://user-images.githubusercontent.com/13246069/72631784-bb6a0d80-3909-11ea-810d-233b585fc229.png)

I'm using Azure Functions v2, here's my host.json

```json
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "default": "Warning"
    },
    "applicationInsights": {
      "enableDependencyTracking": false
    }
  }
}
```

**Comment by andrewleader** [comment]
Using the sampling along with `samplingExcludedTypes` also doesn't do anything...

**Comment by lmolkova** [comment]
@andrewleader 

if Functions configuration does not work for you according to https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#applicationinsights, please create an issue in https://github.com/Azure/azure-functions-host or https://github.com/Azure/azure-webjobs-sdk, If you apply any custom configuration (in host.json or code), please provide details there.

**Comment by pzbyszynski** [comment]
@lmolkova I do not want to turn off all dependencies, just SQL query text logging. It was possible for non-core applications.

SQL query logging consumes huge amounts of data volume. With the amount of data we generate, application insights are useless for us. We have to set a cap limit that is being hit very fast. And without a cap, AI costs us the same amount that all other services we use combined!!!

**Comment by andrewleader** [comment]
@pzbyszynski I managed to find a solution that worked, and documented it a bit better here: https://medium.com/@andrewleader/disable-tracking-dependencies-in-azure-function-application-insights-629e5d192464

**Comment by pzbyszynski** [comment]
@andrewleader I followed your example. As I only need to exclude SQL query text from my dependencies I set `dependency.Data = null;` inside telemetry processor. It works great in core web API, unfortunately, it does not work for me in functions. SQL query text is still being logged :/

cc: @lmolkova

**Comment by andrewleader** [comment]
Unfortunately the solution I had for using the FunctionStartup doesn't seem to be working for my newly deployed v3 function... Super frustrating. Why is it so complicated to disable this!

**Comment by andrewleader** [comment]
@pzbyszynski so I got something working for my new v3 function (and I updated my article).

I got it working purely using `host.json`. The problem is their docs for `samplingExcludedTypes` are incorrect, so that property wasn't working at all, hence why I could previously never get host.json to work.

**host.json**: https://gist.github.com/andrewleader/28b6b4903b3db6043378e818d3b3a8b3

**Article with explanations**: https://medium.com/@andrewleader/disable-tracking-dependencies-in-azure-function-application-insights-629e5d192464

**Comment by pzbyszynski** [comment]
@andrewleader Thx for taking time to describe your solution, unfortunately, it will not solve my problem because I need to log SQL dependencies, just not SQL command text

@lmolkova Any news on that? Also, why following code works on .net core web API hosted on App Service and does not work on Azure Functions (SQL command text is still logged)

```
    public class SqlQueryTextTelemetryProcessor : ITelemetryProcessor
    {
        private readonly ITelemetryProcessor _next;
        private readonly IConfiguration _configuration;

        public SqlQueryTextTelemetryProcessor(ITelemetryProcessor next, IConfiguration configuration)
        {
            _next = next;
            _configuration = configuration;
        }

        public void Process(ITelemetry item)
        {
            if (_configuration.GetValue<bool>("SqlQueryLoggingIsEnabled") == false)
            {
                var dependency = item as DependencyTelemetry;
                if (dependency?.Type == "SQL")
                {
                    dependency.Data = null;
                }
            }
            
            _next.Process(item);
        }
    }

```

**Comment by cijothomas** [comment]
@pzbyszynski Can you share how you added SqlQueryTextTelemetryProcessor to the configuration in Azure Functions? I suspect the issue is Azure Functions not picking up your added processor.

**Comment by pzbyszynski** [comment]
@cijothomas 

In `Startup.cs` I add it like so:

```
builder.Services.AddApplicationInsightsTelemetryProcessor<SqlQueryTextTelemetryProcessor>();
```

Also, I am using functions V3

**Comment by cijothomas** [comment]
@pzbyszynski I just learned from Azure functions that, Functions do not support adding custom telemetry processors. So the above will not work. 
We are working with Azure functions to add this support, no ETA yet.

**Comment by pzbyszynski** [comment]
@cijothomas Can you share the issue link so I can subscribe for notifications?

**Comment by pzbyszynski** [comment]
@cijothomas Could not find an issue you were referring to in web-jobs repo. Do you have any updates on that?

**Comment by cijothomas** [comment]
I can't find the issue in Functions webjobs, but here's the closest I've found.
https://github.com/Azure/azure-functions-host/issues/3741

There are no updates on this.  @brettsam Can you confirm if telemetryprocessors are still not supported/supported in Functions?

**Comment by pzbyszynski** [comment]
@cijothomas Thx, that is an excellent thread, it describes all the problems I have encountered with Functions & AI

**Comment by pzbyszynski** [comment]
@cijothomas Sorry for bothering but I have constant problems with AI unfortunately. 
Some time ago I turned off dependency tracking altogether using `"enableDependencyTracking": false` in `host.json` (due to the fact that SQL dependency tracking was generating huge costs for us).

Now I wanted to turn it back on, but it seems like SQL dependency is not tracked at all now. I mean not only SQL text, but no SQL dependencies are being tracked (all other dependencies are tracked correctly). Any idea why it might be so?

Here are my `csproj` references

```
  <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.1" />
  <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
  <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.14.0" />
  <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
  <PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.14.0" />
  <PackageReference Include="System.Runtime" Version="4.3.1" />
```

**Comment by cijothomas** [comment]
@pzbyszynski I wish I could help more - but I don't own the Functions integration, and it must be followed up in WebJobs/Functions host repo.

Functions have integrated ApplicationInsights SDK, and support/question for that must be routed directly to Functions repo.
For Application insights usage outside Azure Functions, feel free to post here, and I can help.

I know its frustrating to go back and forth, but I dont have better answer than redirecting folks to Functions repo.

**Comment by pzbyszynski** [comment]
Thx @cijothomas, appreciate your help
