### ISSUE TITLE
Integration with .NET Activity is not documented

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1336]
AppInsights heavily relies upon .NET System.Diagnostics.Activity for in-proc context propagation (correlaiton) and dependency tracking.

Integration and limitations (when to use Activity vs AppInsights APIs) need to be documented.

**Comment by lmolkova** [comment]
related: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1222

**Comment by GeeWee** [comment]
Just chiming in to say that I've also spent hours trying to figure out the interactions here.

**Comment by TimothyMothra** [comment]
related: #1586 

We met with @mrbullwinkle yesterday and he will reach out to @SergeyKanzhelev to discuss how to better document this.
