### ISSUE TITLE
Improve EventCounter name

### ISSUE THREAD

**Issue by Expecho** [microsoft/ApplicationInsights-dotnet#1341]
How about (optionally) using the MetricNamespace property of a MetricTelemetry to store the eventsource name? As I understand the namespace property is there to group metrics together. ([source](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview#namespace)). I don't really like the pipe character to make a distinction between the eventsource name and the eventcounter name.

Related to microsoft/ApplicationInsights-dotnet-server#1226

**Comment by cijothomas** [comment]
Yes. This should have been the right way instead of esname|counter.
Unfortunately we may not be able to fix this as some cx may have taken a dependency on this name.

Or as you suggested, this must be an opt-in flag.

**Comment by Expecho** [comment]
> Yes. This should have been the right way instead of esname|counter.
> Unfortunately we may not be able to fix this as some cx may have taken a dependency on this name.
> 
> Or as you suggested, this must be an opt-in flag.

Shall I give it a go in a PR, by using an opt-in flag?

**Comment by cijothomas** [comment]
@Expecho Yes we are happy to get a contribution!

**Comment by Expecho** [comment]
I've started the work. As a reminder: after and if changes are merged we should update the docs: https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters
