### ISSUE TITLE
Requests from Azure FrontDoor cannot be marked as synthetic due to empty UserAgent string

### ISSUE THREAD

**Issue by delradie** [microsoft/ApplicationInsights-dotnet#1343]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create an App Service website and configure insights as standard
2. Configure an Azure FrontDoor with the app service in an active backend pool

##  Actual Behavior

Telemetry shows high traffic to the configured health probe URL. Examination of service logs shows that the user agent is blank

## Expected Behavior

There should be a way of filtering health probe requests as synthetic

## Version Info 
SDK Version :  2.11.2
.NET Version :	4.7.2 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Windows
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApps

**Comment by nicklasjepsen** [comment]
I agree, we need a way to filter the requests, it would be nice it they were marked as bot or Front Door. Our logs are polluted, our cost to AppInsights goes up.

**Comment by cijothomas** [comment]
We do not have any update on this. The actual fix would be to engage Frontdoor team and make sure they sent a predictable useragent, so SDK can do something about it.
