### ISSUE TITLE
SQL dependencies do not work with Microsoft.Data.SqlClient in 2.11 with ASP.NET MVC 5 app

### ISSUE THREAD

**Issue by stebet** [microsoft/ApplicationInsights-dotnet#1347]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create a new ASP.NET MVC 5 application running on .NET Framework 4.7.2
2. Add Application Insights using Visual Studio
3. Add a NuGet reference to Microsoft.Data.SqlClient
4. Add a NuGet reference to Dapper (optional, just used here for simplicity)
5. Trigger the following code to run, for example in the Index action on the HomeController (add your appropriate SQL connection values).
```csharp
public ActionResult Index()
{
    using(SqlConnection conn = new SqlConnection("Server=localhost;Database=master;Trusted_Connection=True;"))
    {
        string[] names = conn.Query<string>("SELECT name FROM sys.tables").ToArray();
        return View();
    }
}
```

##  Actual Behavior
An error can be seen in the Debug output window, with the following information:
`ERROR: Exception in Command Processing for EventSource Microsoft-AdoNet-SystemData: Event BeginExecute is givien event ID 2 but 1 was passed to WriteEvent.`

## Expected Behavior
SQL dependency is properly picked up and reported, without errors.

## Version Info 
SDK Version : 2.11
.NET Version : .NET Framework 4.7.2
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : VisualStudio
Hosting Info (IIS/Azure WebApps/ etc) : IIS

**Comment by michaelpaulus** [comment]
Is there any update on this?  I just got done upgrading all of our projects to EF Core.  I didn't realize this was an issue until now.

**Comment by stebet** [comment]
If you are using Microsoft.Data.SqlClient, you should be fine if you upgrade to the [latest release](https://www.nuget.org/packages/Microsoft.Data.SqlClient/) (1.1.0 as of this comment).

**Comment by stebet** [comment]
This issue was fixed with this PR: https://github.com/dotnet/SqlClient/pull/241
