### ISSUE TITLE
DependencyTelemetry.TryGetOperationDetail isn't as helpful as it could be

### ISSUE THREAD

**Issue by IanKemp** [microsoft/ApplicationInsights-dotnet#1350]
See microsoft/ApplicationInsights-dotnet-server#897.

1. There is no indication as to what values can be passed as the key.
2. There is no type-safety in the values returned.

tl;dr there's no way for anyone to know that they can call

```csharp
if (myDependencyTelemetryInstance.TryGetOperationDetail("HttpRequest", out var rawMsg)
    && rawMsg is HttpRequestMessage message)
{
    // do something with message
}
```

The only reason I know to do the above is because I trawled through issues and PRs in this repo. Most people probably won't be as patient, and they shouldn't need to be.

#### Suggestion

1. Publicly expose relevant [`RemoteDependencyConstants`](https://github.com/microsoft/ApplicationInsights-dotnet-server/blob/master/Src/DependencyCollector/Shared/Implementation/RemoteDependencyConstants.cs#L21) keys.
2. Add specific overloads on `DependencyTelemetry` that reflect what `HttpCoreDiagnosticSourceListener` and `HttpProcessing` are storing:

```csharp
  bool TryGetHttpRequestOperationDetail(out HttpRequestMessage message);
  bool TryGetHttpResponseOperationDetail(out HttpResponseMessage message);
  bool TryGetHttpResponseHeadersOperationDetail(out WebHeaderCollection headers);
```
3. Actually publicise the existence of these predefined keys and values in the [official docs for `DependencyTelemetry.TryGetOperationDetail`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.dependencytelemetry.trygetoperationdetail?view=azure-dotnet).

**Comment by H0110WED** [comment]
Any update on this? Just having the list of keys and values would be great in the meantime.

**Comment by IanKemp** [comment]
Not stale.

**Comment by OskarKlintrot** [comment]
I think I can give this a shot when #2524 gets merged. Shouldn't be too hard hopefully, it looks like it will be pretty straight forward.
________________________________
> Need to evaluate if similar concept can be extended to Requesttelemetry as well. We have quite large number of customers asking for mechanism to read request/response body. While it can't be done by SDK by default (privacy etc.), if we populate the request/response objects in this way, users can access it in initializer and add to telemetry as desired.
> @cijothomas

That would be very helpful! I guess that could be a separat issue? We are adding the body today in middleware's, would be very neat to be able to use initializers like we can with `DependencyTelemetry`.

**Comment by IanKemp** [comment]
Not stale, reopen!

**Comment by OskarKlintrot** [comment]
@IanKemp did #2566 solve it for you or do you need something else?
