### ISSUE TITLE
DependencyCollector references a bad and old version of System.Data.SqlClient

### ISSUE THREAD

**Issue by ErikEJ** [microsoft/ApplicationInsights-dotnet#1351]
You should update the reference to System.Data.SqlClient to a newer version, you are currently using version 4.3.1 and current version is 4.6.1 - the 4.3.1 version causes issues with newer dependencies - see issue here: https://github.com/dotnet/SqlClient/issues/144

**Comment by ErikEJ** [comment]
Ping??

**Comment by cijothomas** [comment]
dependency on System.Data.SqlClient was removed in the current beta. We can close this issue.
