### ISSUE TITLE
Use WAS-DEFAULT-HOSTNAME HttpHeader to get slot name

### ISSUE THREAD

**Issue by debugthings** [microsoft/ApplicationInsights-dotnet#1368]
## Issue
Currently we use the [WEBSITE_HOSTNAME](https://github.com/microsoft/ApplicationInsights-dotnet-server/blob/c47719cdc1d204ed99b19bb033ef9dc18118103d/Src/WindowsServer/WindowsServer.Shared/AzureWebAppRoleEnvironmentTelemetryInitializer.cs#L18) to determine the App Service slot the code is deployed to.

This environment variable is passed in upon process creation by the App Service sandbox and is not updated. This requires a reboot of the App Service to get the correct value.

## Result
The result of this is telemetry will have an incorrect `cloud_RoleName` until this happens which can skew customer metrics.

## Proposal
The proposed fix is to read the `WAS-DEFAULT-HOSTNAME` http header instead which is sent by the App Service front end (ARR) servers and will always have the correct app service host name.

**Comment by Expecho** [comment]
> Update:
> We got confirmation from AppService team that was-default-hostname is correct way to get the role name we want, and its guaranteed to be correct.
> 
> There is no update yet on how to get this on webjobs or background jobs, so they'll continue to rely on the env variable.

I stumbled upon this issue in our web apps as well. What is the status of this issue? At least we can get it right for the web apps, and create a seperate issue for the webjobs?

**Comment by cijothomas** [comment]
> > Update:
> > We got confirmation from AppService team that was-default-hostname is correct way to get the role name we want, and its guaranteed to be correct.
> > There is no update yet on how to get this on webjobs or background jobs, so they'll continue to rely on the env variable.
> 
> I stumbled upon this issue in our web apps as well. What is the status of this issue? At least we can get it right for the web apps, and create a seperate issue for the webjobs?

We have this fixed already for web apps, as they can rely on hostname header. For webjobs, there is no request or header, so not sure how to fix it there. So its unfixed for WebJobs and there are no clear guidance on how to fix it as well. (We can close this and open a new issue just to track this for webjobs)

**Comment by Expecho** [comment]
> 
> ... So its unfixed for WebJobs and there are no clear guidance on how to fix it as well. (We can close this and open a new issue just to track this for webjobs)

Maybe using the [newly announced Event Grid events](https://docs.microsoft.com/en-us/azure/event-grid/event-schema-app-service) an environment variable can be updated, it might solve the issue as defined in this Issue:

> Currently we use the WEBSITE_HOSTNAME to determine the App Service slot the code is deployed to.

> This environment variable is passed in upon process creation by the App Service sandbox and is not updated. This requires a reboot of the App Service to get the correct value.

**Comment by cijothomas** [comment]
> > ... So its unfixed for WebJobs and there are no clear guidance on how to fix it as well. (We can close this and open a new issue just to track this for webjobs)
> 
> Maybe using the [newly announced Event Grid events](https://docs.microsoft.com/en-us/azure/event-grid/event-schema-app-service) the environment variable can be updated, it might solve the issue as defined in this Issue:
> 
> > Currently we use the WEBSITE_HOSTNAME to determine the App Service slot the code is deployed to.
> 
> > This environment variable is passed in upon process creation by the App Service sandbox and is not updated. This requires a reboot of the App Service to get the correct value.

Looks promising.

One of the thing we are trying to avoid is SDKs having deep knowledge about all the Azure platforms - and instead have all Azure environments expose the information is a standardized way, so SDKs don't have to have specialized solution for each compute platform. (There was not enough bandwidth to pursue this, so I expect this issue to be unresolved for short-term)

**Comment by cijothomas** [comment]
@Expecho If you use the EventGrid approach to solve you issue, please post back the approach/sample code, so other customers can leverage it, until SDK itself gets this capability (which will take some time)

**Comment by Expecho** [comment]
> @Expecho If you use the EventGrid approach to solve you issue, please post back the approach/sample code, so other customers can leverage it, until SDK itself gets this capability (which will take some time)

To be honest, we do not use webjobs so that part is not affecting us. So I won't probably use the EventGrid approach myself but it could be interesting for future readers of this issue. If we do have the need we will post a sample.

**Comment by IgnacioAlvarezArenas** [comment]
Hi all. I was wondering if this issue was actually resolved for App Services. Let me explain my situation:

I have two slots, the production and another called csharp in my App Service called ignacio app. I have Agent Based App Insights so it is running these versions:

![image](https://user-images.githubusercontent.com/61497756/89988119-fb625a80-dc76-11ea-9e4e-ec3212d28518.png)

When I run this query the following happens:
requests
| where timestamp  >= datetime(2020-08-05 08:00:00) and timestamp <=  datetime(2020-08-05 09:20:00)
| where url !contains "csharp"
| project timestamp,cloud_RoleName,url
| order by timestamp

![image](https://user-images.githubusercontent.com/61497756/89988672-c99dc380-dc77-11ea-97e2-73a68c03aa7f.png)

but then I do the swap:
![image](https://user-images.githubusercontent.com/61497756/89988735-df12ed80-dc77-11ea-8b9c-1b7eebd53ca5.png)

So as you can see, the URL remains the same (www2.ignacioapps.com) but the Cloud role name changed. I restarted the App Service (which is also implicitly done by the swap). 

Can you guys confirm this is the expected behaviour?

**Comment by cijothomas** [comment]
Its fixed in 2.12 version of the SDK.
Are you using Asp.Net or Asp.Net Core in agent based enablement?

**Comment by IgnacioAlvarezArenas** [comment]
Hi Cijo,

I am actually using Asp.NET in Agent Based. It seems that I am using 2.8.6.

Regards,
Ignacio Alvarez Arenas
AZURE CLOUD ENGINEER
Azure CXP
+353 (1) 2797590
igalvare@microsoft.com<mailto:igalvare@microsoft.com>
[Microsoft]

**Comment by cijothomas** [comment]
@IgnacioAlvarezArenas Asp.Net agent is on an old version of SDK. You need to use SDK based approach to benefit from this.

**Comment by IgnacioAlvarezArenas** [comment]
Thanks for the clarification Cijo. What about if I was using .NET Core agent based? Would I run into the same situation?

Thanks in advance!

Ignacio Alvarez Arenas
AZURE CLOUD ENGINEER
Azure CXP
+353 (1) 2797590
igalvare@microsoft.com<mailto:igalvare@microsoft.com>
[Microsoft]

**Comment by cijothomas** [comment]
Asp.Net Core agent is somewhat new. I don't know exact version, but I think its newer than 2.12 so you will be fine in Asp.Net core.
(You can verify sdk version from any telemetry field to confirm which version is used by the agent)

**Comment by IgnacioAlvarezArenas** [comment]
Thanks for the clarification Cijo, really helpful!
