### ISSUE TITLE
Dependency tracking function tests fail with "All Apps are not unhealthy".

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1369]
Dependency functional tests sometimes fail while starting containers with test apps.
Check this two runs out:

[dlab14_DDMBLDW183_2019-05-22_15_58_57.zip](https://github.com/microsoft/ApplicationInsights-dotnet-server/files/3209682/dlab14_DDMBLDW183_2019-05-22_15_58_57.zip)
[dlab14_DDMBLDW182_2019-05-22_14_42_20.zip](https://github.com/microsoft/ApplicationInsights-dotnet-server/files/3209683/dlab14_DDMBLDW182_2019-05-22_14_42_20.zip)

**Comment by TimothyMothra** [comment]
Cijo and I made some progress on this in November.
I'm closing this issue, with a promise that we will continue to monitor the builds.
