### ISSUE TITLE
MSB3030 with linked config files

### ISSUE THREAD

**Issue by drauch** [microsoft/ApplicationInsights-dotnet#1381]
We've just upgraded from 2.6.x to 2.9.1 and now our build fails with the following error message:

```
(CopyApplicationInsightsConfigToOutputDirectory target) -> 
C:\Users\BuildAgent-SP\.nuget\packages\microsoft.applicationinsights.windowsserver\2.9.1\build\Microsoft.ApplicationInsights.WindowsServer.targets(9,5): error MSB3030: Could not copy the file "ApplicationInsights.config" because it was not found.
```

Our ApplicationInsights.config file is part of the project, however, it is a linked item:

```
  <ItemGroup>
    <None Include="..\ApplicationInsights-WebApps.config" Link="ApplicationInsights.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

Is this a bug? It worked in 2.6.x.

**Comment by TimothyMothra** [comment]
Duplicate issue: #1085

This is no longer reproducible.
I'm closing this as fixed, but if you're still encountering issues with our latest SDK please comment.
