### ISSUE TITLE
Dependency conflict with Eventhubs and DiagnosticSource on Cloud Service

### ISSUE THREAD

**Issue by binkiesjoris** [microsoft/ApplicationInsights-dotnet#1382]
This week I deployed a new Azure Cloud Service using the [azure eventhubs](https://github.com/Azure/azure-event-hubs-dotnet) package. That package has a dependency on System.Diagnostics.DiagnosticSource >= 4.5.0. After deploying I get the following error:

`Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.` 

The fusion log doesn't show anything useful, other than that it find 2 different versions of the dll (hence the error). I remoted into the VM and found that a bunch of Application Insights packages are deployed next to my application (which does NOT include Application Insights), and also System.Diagnostics.DiagnosticSource version 4.4.0.

My assumption so far is that Insights is being automatically deployed by azure to wrap my application and provide telemetry (even though I have turned that off) and is therefor messing with my application. The error is not fixable with assembly redirects (it either cant find the dll, or you get the manifest error), is there any else I could try or might this be caused by an issue with the dependency guidance of the Application Insights packages?

I also posted this [issue](https://github.com/Azure/azure-event-hubs-dotnet/issues/382) on the eventhubs page.

**Comment by togglebrain** [comment]
Facing the same issue, need appinsights on an application that is using Microsoft.Azure.EventHubs, which in turn depends on System.Diagnostics.DiagnosticSource. Assembly binding does not help. Is there a fix available?

**Comment by TimothyMothra** [comment]
@Dmitry-Matveev please review

**Comment by Dmitry-Matveev** [comment]
@Mikhail-msft , I thought we have shipped the version that automatically backs-off in case of conflicting assemblies, have we had some regression or the issue @togglebrain experiences is something new?

**Comment by Mikhail-msft** [comment]
@togglebrain could you confirm what is the exact issue you see (is it "no data" or the app is crashing?) and in what environment (App Service/Azure VM/Cloud Service/status monitor v2?) it happens?
@heyams FYI for issue reported by @DaleyKD .

**Comment by togglebrain** [comment]
> @togglebrain could you confirm what is the exact issue you see (is it "no data" or the app is crashing?) and in what environment (App Service/Azure VM/Cloud Service/status monitor v2?) it happens?
> @heyams FYI for issue reported by @DaleyKD .

We are observing "no data" issue with multiple app services. Checked with azure support team also and they suggested removing the System.Diagnostics.DiagnosticSource dll but that crashes the app since its a dependency for the event hubs library in use in our APIs.

**Comment by DaleCam** [comment]
Im having the issue because I am using Azure.Storage which depends on Azure.core which depends on System.Diagnostics.DiagnosticSource which seems to break App Insights (no data being collected)

**Comment by Deepa-Puranik** [comment]
Is this issue still exist with runtime version of application insight we can't use package which got dependency with System.Diagnostics.DiagnosticSource.dll along with application insight configured run time.
We are currently facing this issue and we can't delete System.Diagnostics.DiagnosticSource.dll from our code application folder.
Any help related to this?

**Comment by adekle** [comment]
For anyone else running into this issue, the workaround that resolved it in our case was to add App Insights to the application manually following the instructions here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net#add-application-insights-manually.
