### ISSUE TITLE
SQL dependencies >= 100 seconds are not tracked

### ISSUE THREAD

**Issue by taddison** [microsoft/ApplicationInsights-dotnet#1385]
We noticed a few long-running SQL calls were not being tracked by app insights, and after investigating found the cutoff to be 100 seconds.

The below app will log dependency calls for 98,99 seconds and nothing for 100,101.  We repeated this several times to try and isolate any timing issues and got very consistent results.

Setup:
- netcoreapp2.2
- Microsoft.ApplicationInsights 2.8.1
- MIcrosoft.ApplicationInsights.DependencyCollector 2.8.1

(on GitHub [here](https://github.com/taddison/csharp-coffre/tree/7ece318face449639b36ed82ee3ffa180c5a4fc0/appinsights-sql-test), needs an instrumentation key and SQL database to work).

```csharp
using System;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.Extensibility;
using System.Threading;
using System.Data.SqlClient;
using Microsoft.ApplicationInsights.DependencyCollector;

namespace appinsights_sql_test
{
    class Program
    {
        static void Main(string[] args)
        {
            var config = TelemetryConfiguration.Active;
            config.InstrumentationKey = "###";
            var module = new DependencyTrackingTelemetryModule();
            module.Initialize(config);

            var telemetryClient = new TelemetryClient();
            telemetryClient.TrackTrace("Start Benchmark");

            using(var conn = new SqlConnection("server=localhost;initial catalog=master;integrated security=SSPI"))
            {
                conn.Open();
                for(var i = 98; i <= 102; i++)
                {
                    var ts = new TimeSpan(0, 0, i);
                    using (var cmd = new SqlCommand($"waitfor delay '00:{ts.Minutes:00}:{ts.Seconds:00}'",conn))
                    {
                        client.TrackTrace($"Running SQL query for {ts.TotalSeconds} seconds");
                        cmd.ExecuteNonQuery();
                    }
                }
            }

            Console.WriteLine("Done.");
            telemetryClient.Flush();
            // https://github.com/Microsoft/ApplicationInsights-dotnet/issues/407
            Thread.Sleep(10000);
        }
    }
}
```

Here is an example of the captured telemetry from earlier tests - you can see we no longer get dependency data from 100 seconds.

```kql
union traces, dependencies
| where timestamp > todatetime("20181220 21:02:00") and timestamp < todatetime("20181220 21:16:00")
| project timestamp, message, duration
| order by timestamp desc
```

![image](https://user-images.githubusercontent.com/2743558/50353499-7614ba00-0516-11e9-80e3-614507c4c810.png)

**Comment by Alexander-Bartosh** [comment]
Guys maybe you can `complete` the items that are removed from cache with a duration of X seconds (100 seconds) ? 
The specific value of X can be decided in the meantime. 
Would be nice to treat X as `TimedOut` in the portal as well.

**Comment by jawn** [comment]
Is any action planned on this issue? While I am a fan of Application Insights, this bug makes it hard to recommend it for proactive production monitoring and analysis.

**Comment by cijothomas** [comment]
No work item is planned for fixing this. Agree its a bad bug, but it is still a relatively lower priority issue, as this should affect only .NET framework apps using System.Data.SqlClient. .NET Core works in a different way, and should not be affected by this issue.

While we cannot commit to a timeline for the fix, there is a good chance that the fix would come through OpenTelemetry. (OpenTelemetry Sql instrumentation does not have this issue).

**Comment by jawn** [comment]
Thanks for your feedback, does that mean Microsoft.Data.SqlClient does not have this issue?

**Comment by cijothomas** [comment]
> @cijothomas Thanks for your feedback, does that mean Microsoft.Data.SqlClient does not have this issue?

Sorry I actually its an issue only in .NET Framework, and not in .NET core.
System.Data.SqlClient/Microsoft.DataSqlClient - both would face this issue. (only in .Net framework)

**Comment by jawn** [comment]
@cijothomas assuming no action has been taken on this one, and nothing planned for .NET Framework?

Has anything come through via OpenTelemetry?

**Comment by cijothomas** [comment]
Nothing planned in this repo to improve/fix this.
OpenTelemetry instrumentation does not have this problem. (There is no production recommended OpenTelemetry + ApplicationInsightsExporter available today.)
