### ISSUE TITLE
QuickPulseServiceClientSubmitsCollectionConfigurationETagToService flaky test

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1392]
Test method Microsoft.ApplicationInsights.Tests.QuickPulseServiceClientTests.QuickPulseServiceClientSubmitsCollectionConfigurationETagToService threw exception: 
System.InvalidOperationException: Sequence contains no elements

https://dev.azure.com/mseng/AppInsights/_build/results?buildId=7600941&view=ms.vss-test-web.test-result-details

**Comment by TimothyMothra** [comment]
I'm no longer seeing this test fail, so i'm closing this task.
