### ISSUE TITLE
ASP.NET MVC application with windows authentication NTLM 401 challenge do not log the 200 response.

### ISSUE THREAD

**Issue by udi12** [microsoft/ApplicationInsights-dotnet#1394]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1.  ASP.NET  MVC website hosted on windows server 2012 standard
2. Browsing to pages introducing the 401 challenge 

##  Actual Behavior
AI only logs the 401 responses

## Expected Behavior

AI should Log the 401 + 200 responses

## Version Info 
SDK Version :
.NET Version : 4.5	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : windows server 2012 standard
Hosting Info (IIS/Azure WebApps/ etc) :
IIS over private virtual servers, 
AI / Analytics over Azure

**Comment by scoarem** [comment]
I have the same problem with soap services.
When using the application insight version 2.5.1 the dependency is logged as successful = true.
After upgrading to the latest version 2.14.0 the dependency is logged as successful = false.
All the webservices are working fine and the logging of the earlier version is more correctly.

**Comment by bdlane** [comment]
I'm having the same problem - when making HTTP requests to a resource secured with Windows authentication, the first (unauthenticated) request is tracked by AI with the 401 response code and marked as 'failed' - as expected. But the second (authenticated) request is not tracked at all by AI. So when you look in the AI logs, all you see are 401s!

I would expect to see both the first failed request, and the second successful request.

I've attached an example based on the console app example [here](https://docs.microsoft.com/en-gb/azure/azure-monitor/app/console#full-example). It shows a request to an unsecured resource works fine and is tracked as a successful dependency with a 200 response, whereas a request to a Windows Auth secured resource is only tracked as a failed dependency with a 401 response, even though the second authenticated request happens and is successful.

This is using the `Microsoft.ApplicationInsights` and `Microsoft.ApplicationInsights.DependencyCollector` packages v 2.14.0
[AppInsightsHttpTests.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/4975531/AppInsightsHttpTests.zip)
