### ISSUE TITLE
Perf suggestion: Cache version info in GetSdkVersion

### ISSUE THREAD

**Issue by vincec-msft** [microsoft/ApplicationInsights-dotnet#1398]
SdkVersionUtils.GetSdkVersion is called often and does a lot of work to get the version info from the assembly housing SdkVersionUtils.

That information doesn't change so can it be cached the first time it's called? Both version and postfix are caching candidates, then the function would just have to do some string concatenation and no expensive reflection.

https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/eb884b81c568b1054f9b7168ea4b0ec61f9e3506/Src/Common/SdkVersionUtils.cs#L13

**Comment by eddynaka** [comment]
Hi @lmolkova , is this still up-for-grabs? if yes, how do you think is the most appropriate way to implement that?
Thanks
