### ISSUE TITLE
Recently added configuration options for Diagnostic Source providers are missing from official documentation

### ISSUE THREAD

**Issue by Dmitry-Matveev** [microsoft/ApplicationInsights-dotnet#1405]
[Copied from ApplicationInsights-Home repo](https://github.com/Microsoft/ApplicationInsights-Home/issues/235):

ApplicationInsights is great but the `applicationinsights.config` file has a lot of settings which aren't comprehensively documented. Since this is telemetry we're talking about, disclosure is critical for integrity and privacy (especially for the installation defaults).

The closest reference is [here](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-configuration-with-applicationinsights-config) but doesn't seem like it's maintained in-sync with code. As an example, the following block (added by default on nuget installation) is not documented anywhere that's easy to find. Google searches mostly reveal all the stackoverflow and blog articles discussing other/related appinsight issues - not useful.

```
<IncludeDiagnosticSourceActivities>
  <Add>Microsoft.Azure.EventHubs</Add>
  <Add>Microsoft.Azure.ServiceBus</Add>
</IncludeDiagnosticSourceActivities>
```

**Comment by alexandery** [comment]
This has been reported 2 years ago. Any progress? There are quite a few grey areas in the functionality with no documentation. Not good at all.
