### ISSUE TITLE
WCF Service dependency tracking only auth requests resulting into 401 response

### ISSUE THREAD

**Issue by gabarach** [microsoft/ApplicationInsights-dotnet#1408]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create an ASP.NET (target framework 4.6.1) Web API application using Visual Studio 2017 (by default, it refers to Application Insights 2.2 SDK)
**Packages.config**:
```
<package id="Microsoft.ApplicationInsights" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.0.6" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.2.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.2.0" targetFramework="net461" />
```

2. Update the Application Insights nuget packages to either 2.4 or 2.6.1
**Packages.config**:
```
<package id="Microsoft.ApplicationInsights" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.4.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.6.1" targetFramework="net461" />
```
  
3. Specify the Application Insights instrumentation key in the ApplicationInsights.config file. 
4. Add a service reference to a WCF service that uses basicHttpBinding and has been configured for Transport Security using Windows Authentication.
5. Write code to invoke WCF operation from the Web API controller (e.g. ValuesController)
6. Either deploy/host the Web API in Azure App Services or host in IIS or simply run using Visual Studio/IIS Express
7. Invoke Web API method (e.g. values/get)
8. Visit Application Insights Log Analytics and query both **requests** and **dependencies** tables.

##  Actual Behavior
Query to dependencies for the corresponding operation_Id of the request will show only records with type=WCF Service, resultCode=401, Success=FALSE though the service call was successful. It’s only tracking the authentication request resulting into 401 response code. The subsequent HTTP POST request with user credentials and response code 200, isn’t tracked. Ideally, it should combine both and show as a single dependency as done in AI 2.2 SDK.

## Expected Behavior
Dependencies should combine the duration for both auth handshake related HTTP request and actual operation and list it as a single record with resultCode=200.

## Version Info 
SDK Version : 2.4 or 2.6.1
.NET Version :	4.6.1 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio
OS : Windows 10 (Version 1607)
Hosting Info (IIS/Azure WebApps/ etc) : Both IIS and Azure App Services - API App

**Comment by quails4Eva** [comment]
This issue significantly reduces the usefulness of app insights in apps that have Windows authenticated web api dependencies.

Is this something that would need fixing in ApplicationInsights? Or is it something in the behaviour of the HttpClient? I would assume it's ApplicationInsights interpreting the HttpClient responses.

See similar/same issues https://github.com/microsoft/ApplicationInsights-dotnet/issues/1394
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1627
