### ISSUE TITLE
Azure instance metadata heartbeat provider should not assume the IHeartbeatPropertyManager is available upon .Initialize

### ISSUE THREAD

**Issue by d3r3kk** [microsoft/ApplicationInsights-dotnet#1413]
We need to ensure that the `IHeartbeatPropertyManager` is instantiated before we attempt to add heartbeat properties to it.

Currently, we are relying on the implementation details of the baseSDK rather than handling the scenario that the `IHeartbeatPropertyManager` becomes available more dynamically.

The issue arose from this comment specifically:
@pharring
Now I look closer at what you're doing within the constructor (enumerating all previous telemetry modules), perhaps that wouldn't be appropriate because you can't ensure you're the last module to be loaded (or at least after all the other `IHeartbeatPropertyManager` instances). Indeed, even as an `ITelemetryInitializer` you're relying on an implementation detail that they are constructed after all modules are created.

**Comment by cijothomas** [comment]
@TimothyMothra to confirm fix and close.
