### ISSUE TITLE
WebTestTelemetryInitializer should cache the result per request

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1420]
To avoid re-running the computations if there are multiple telemetry items in the context of the same request, the result should be cached.
Similar to 
https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/580

**Comment by eddynaka** [comment]
@TimothyMothra , can I take this issue?

**Comment by TimothyMothra** [comment]
@eddynaka I don't have any context on these issues, they were both opened and addressed by Cijo.
