### ISSUE TITLE
Add ability to turn off SQL query logging for Azure Functions

### ISSUE THREAD

**Issue by pzbyszynski** [microsoft/ApplicationInsights-dotnet#1425]
As stated in microsoft/ApplicationInsights-aspnetcore#968, it is impossible to turn off SQL query logging for Azure Functions (consumption plan). SQL Query logging adds significantly to AI costs, there should be a possibility to turn it off the same way as in application service

## Repro Steps
1. Go to Azure Function -> Platform features -> All settings -> Application Insights and turn `SQL Commands` off

##  Actual Behavior
SQL Queries are still logged

## Expected Behavior
SQL Query should not be logged

**Comment by andrewleader** [comment]
I need this. It's costing me a ton in AI because of dependencies (like SQL) being tracked in my functions! How is there not a way to turn this off?

**Comment by cijothomas** [comment]
Closed via https://github.com/microsoft/ApplicationInsights-dotnet/pull/1514
`EnableSqlCommandTextInstrumentation` on `DependencyTrackingTelemetryModule` can be used to enable/disable full SQL Text collection.

**Comment by pzbyszynski** [comment]
@cijothomas Any docs on how to do that (preferably via `appsettings.json`?

**Comment by cijothomas** [comment]
Follow the regular doc for customizing any module:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#configuring-or-removing-default-telemetrymodules

```
services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((module, o) =>
            {
                module.EnableSqlCommandTextInstrumentation = true;
            });
```

the sdk doesn't read anything other than ikey from appsettings.json. But users can read any config from appsettings.json (or other sources), and apply.

Also - this feature is not in Azure functions yet.

**Comment by pzbyszynski** [comment]
@cijothomas Any news on that? I am on `2.14.0` and still have no access to `module.EnableSqlCommandTextInstrumentation` property

**Comment by cijothomas** [comment]
@pzbyszynski This was already shipped in 2.14 and doc is updated as well.

**Comment by pzbyszynski** [comment]
@cijothomas Unfortunately I can't get this to work. On Wab App it works as expected. On Azure Functions, no-meter the `module.EnableSqlCommandTextInstrumentation` flag value, I get no SQL tracking. Not only no SQL text, but no SQL dependencies at all

**Comment by cijothomas** [comment]
For Functions - Please follow up in Functions repo: https://github.com/Azure/azure-webjobs-sdk
