### ISSUE TITLE
EventGrid End-to-End logging - EventGridDiagnosticsEventHandler on roadmap?

### ISSUE THREAD

**Issue by daniel-pfaeffli** [microsoft/ApplicationInsights-dotnet#1427]
Hi all,
We are heavily building solutions around eventgrid. End to end logging is awkard due missing Correlation Support from Event Grid.

## Repro Steps
1. Add an Event to an eventgrid Topic with EventGridClient or bare http post request. Application Insights will automatically inject the correlation heaeders for this dependency.
2. Topic consumer which gets notified by webhook endpoint will not receive the correlation headers.

##  Actual Behavior
EventGrid does not offer an opportunity to define if correlation information should be delivered to consumers.

## Expected Behavior
EventGrid should pickup corellation headers on Event creation, persists them with the event and delivers them to the consuming endpoint as well. (as servicebus is allready doing)

## Version Info 
SDK Version: Microsoft.ApplicationInsights.AspNetCore 2.7.1
Microsoft.Azure.WebJobs.Extensions.EventGrid 2.0.0
Microsoft.Azure.EventGrid 3.2.0

**Comment by emilkje** [comment]
Any updates on this issue? Correlation and activity support is essential if AEG intends to be a general purpose event router both internal and external to the Azure platform.

**Comment by mmulhearn** [comment]
Any update on this?  Looking to get full tracing through an Event Grid as well.

**Comment by cijothomas** [comment]
Unfortunately, no updates, and no work planned in ApplicationInsights for this in next 6 months. 
The actual work would be in the EventGrid client libraries, and not necessarily in the application insights SDK. 

Please raise a feedback here: https://feedback.azure.com/forums/357324-azure-monitor-application-insights

**Comment by Expecho** [comment]
> Unfortunately, no updates, and no work planned in ApplicationInsights for this in next 6 months.
> The actual work would be in the EventGrid client libraries, and not necessarily in the application insights SDK.
> 
> Please raise a feedback here: https://feedback.azure.com/forums/357324-azure-monitor-application-insights

Would this be something that the App Insights team need to build into the Event Grid team, or would it be something they need to do? If there is any guidance on how to build this I would not mind trying to give it a go. It is just that I do not know where/how to start.

**Comment by cijothomas** [comment]
> > Unfortunately, no updates, and no work planned in ApplicationInsights for this in next 6 months.
> > The actual work would be in the EventGrid client libraries, and not necessarily in the application insights SDK.
> > Please raise a feedback here: https://feedback.azure.com/forums/357324-azure-monitor-application-insights
> 
> Would this be something that the App Insights team need to build into the Event Grid lib, or would it be something they need to do? If there is any guidance on how to build this I would not mind trying to give it a go. It is just that I do not know where/how to start.

The instrumentation must be done in the EventGrid library itself. Need to instrument it using the new ActivitySource mechanism. @pakrym Can you let us know if this is something EventGrid is planned to do?

(EventGrid instrumentation alone is not sufficient. One needs to write ApplicationInsights adapter for the same - This is not planned in 2020, and is likely to come through OpenTelemetry Intergration. The specifics for this are being discussed only).

**Comment by pakrym** [comment]
The new EventGrid library that is currently being worked on would be instrumented with the activity source that app insights already knows how to collect as part of AzureSDK collectors.

**Comment by cijothomas** [comment]
> The new EventGrid library that is currently being worked on would be instrumented with the activity source that app insights already knows how to collect as part of AzureSDK collectors.

Application Insights does not have ActivitySource based subscription mechanism. It has Diagnosticsource based mechanism only . Is EventGrid instrumented with ActivitySource or DiagnosticSource or mix of both?

**Comment by pakrym** [comment]
Even Track 2 Azure libraries are not using ActivitySource based publishing yet, it's `DiagnosticSource` for now.

**Comment by cijothomas** [comment]
Ok, if using DiagnosticSource, then application insights should already be capable of collecting them.

Track2 libraries - Are they planned to use ActivitySource?

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/DependencyCollector/DependencyTrackingTelemetryModule.cs#L86 @Expecho This should already allow collecting "generic" DiagnosticSource activities. Haven't tried this myself to see what the experience would look like - but is this something which you can try out ?

**Comment by pakrym** [comment]
> Track2 libraries - Are they planned to use ActivitySource?

We haven't planned the migration yet, we would need the support from AppInsights and OT first not to break our customers.

**Comment by cijothomas** [comment]
Okay got it. Yes, we can work together to get this.

I will see if @Expecho can use the existing application insights capabilities to monitor EventGrid basic collection.

**Comment by cijothomas** [comment]
@lmolkova FYI;

**Comment by mariomeyrelles** [comment]
Any news on that?

**Comment by cijothomas** [comment]
@mburumaxwell Nice!
(what you wrote is a preview of future (3.0) of this SDK, once it starts to move to new Activity model, (similar to OpenTelemetry.)

**Comment by mburumaxwell** [comment]
@cijothomas Great! When do you expect to have preview available?

**Comment by shubhambits** [comment]
event grid has added support - [Custom delivery properties](https://docs.microsoft.com/en-us/azure/event-grid/delivery-properties)
