### ISSUE TITLE
Question: What is the correct way to add request-specific properties to telemetry context?

### ISSUE THREAD

**Issue by joostvz** [microsoft/ApplicationInsights-dotnet#1428]
I want to add request-specific data to the telemetry context, so that it will be included in the default AI _Trace_ and _Request_ log messages. This data is retrieved from the request body in my Azure Function (v2). Ideally, I want to be able to add this data to the context inside my Function, and not in a TelemetryInitializer (as that would force me to parse the request body in both the Function and the initializer).

I looked at the `TelemetryClient` to do this, but this one doesn't seem to have an applicable property for it:
- `TelemetryClient.Context.GlobalProperties` is meant for global properties, and not for request-scoped properties;
- `TelemetryClient.Context.Properties` is obsolete, and I don't see how I can use the recommended replacement `ISupportProperties.Properties` there.

Note: I've also opened a [question on StackOverflow](https://stackoverflow.com/questions/56851912/add-custom-telemetry-properties-inside-azure-function) for this.

**Comment by scottmcm** [comment]
For anyone who ends up here in the future, if you're in AspNetCore one answer is to do this:
```csharp
var requestTelemetry = context.HttpContext.Features.Get<RequestTelemetry>();
requestTelemetry.Properties["Foo"] = "Bar";
```

**Comment by safakgur** [comment]
@lmolkova:
> You can update request telemetry properties by adding tags on `Activity.Current` like
> ```cs
> Activity.Current?.AddTag("my-prop", ExtractPropFromRequest());
> ```

Hi - is this still the case with Azure Functions on .NET 5 (isolated process)? `Activity.Current` seems to always be null:

```c#
[Function("Foo")]
public HttpResponseData Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = RoutePrefix + "foo")]
    HttpRequestData req)
{
    // `Current` is null, `AddTag` doesn't get executed.
    Activity.Current?.AddTag("Bar", "Baz");

    return req.CreateResponse();
}
```

Do I need to start an activity manually using `TraceParent` and `TraceState` from `req.FunctionContext.TraceContext`?

**Comment by Zenuka** [comment]
> @lmolkova:
> 
> > You can update request telemetry properties by adding tags on `Activity.Current` like
> > ```cs
> > Activity.Current?.AddTag("my-prop", ExtractPropFromRequest());
> > ```
> 
> Hi - is this still the case with Azure Functions on .NET 5 (isolated process)? `Activity.Current` seems to always be null:
> 
> ```cs
> [Function("Foo")]
> public HttpResponseData Run(
>     [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "foo")]
>     HttpRequestData req)
> {
>     // `Current` is null, `AddTag` doesn't get executed.
>     Activity.Current?.AddTag("Bar", "Baz");
> 
>     return req.CreateResponse();
> }
> ```
> 
> Do I need to start an activity manually using `TraceParent` and `TraceState` from `req.FunctionContext.TraceContext`?

I just started a new 3.1 function app with `Microsoft.NET.Sdk.Functions (3.0.13)` and `Microsoft.ApplicationInsights.AspNetCore (2.18.0)` and `Activity.Current` seems to be null as well.

I also tried to use the "HttpContext"-way but I can't seem to get an HttpContext from the `IHttpContextAccessor`, it's always null.

**Comment by jrichardsz** [comment]
> For anyone who ends up here in the future, if you're in AspNetCore one answer is to do this:
> 
> var requestTelemetry = context.HttpContext.Features.Get<RequestTelemetry>();
> requestTelemetry.Properties["Foo"] = "Bar";

You are my hero!!!

![Image](https://github.com/user-attachments/assets/c4ea0391-c42c-424d-849c-c0a8fd57071c)
