### ISSUE TITLE
Application insights increases application memory usage

### ISSUE THREAD

**Issue by alexiordan** [microsoft/ApplicationInsights-dotnet#1429]
With Application Insights enabled my application uses up to 1.2 GB of RAM. With Application Insights disabled, the application uses around 200 MB. Please see the picture below.

Why?

It wouldn't be a problem, but I am get warnings about the used memory raising above the 80% threshold and that I may encounter errors because of that.
I have also other applications running in the same App Service Plan  (S2): 3.5 GB RAM.

The application is a .Net Core Asp.Net AppService using SignalRService. It is configured with 
`<ServerGarbageCollection>false</ServerGarbageCollection>`  (see: 
https://github.com/aspnet/AspNetCore/issues/1976#issuecomment-416942540  )

The difference between the right and the left part of the red bar in the image are only the following 2 lines of code.
```
services.AddApplicationInsightsTelemetry();
services.AddApplicationInsightsTelemetryProcessor<NoSignalRRequestFilter>();
```
where `NoSignalRRequestFilter` class is as follows:
```
 public class NoSignalRRequestFilter : ITelemetryProcessor
    {
        private ITelemetryProcessor Next { get; set; }

        public NoSignalRRequestFilter(ITelemetryProcessor next)
        {
            this.Next = next;
        }

        public void Process(ITelemetry item)
        {
            var request = item as RequestTelemetry;

            if (request != null && request.Name != null)
                if (request.Name.Contains("hubName1") 
                    || request.Name.Contains("hubName2")
                    || request.Name.Contains("hubName3"))
                    return;

            // Send everything else:
            this.Next.Process(item);
        }
    }
```

![image](https://user-images.githubusercontent.com/15249495/60428382-6088f700-9c01-11e9-9e10-69c0089ba808.png)

Would someone, please, help me figure this out?

**Comment by Marusyk** [comment]
Have the same issue https://github.com/microsoft/ApplicationInsights-dotnet/issues/2140
Does anyone know how to use AI in production without a memory leaks?
