### ISSUE TITLE
Custom configuration example "Add request-level properties for all telemetry items" does not work?

### ISSUE THREAD

**Issue by lexdenotter** [microsoft/ApplicationInsights-dotnet#1433]
The example in the wiki does not work, 
`Microsoft.AspNetCore.Http.IHttpContextAccessor.HttpContext.get returned null.` 
is raised on startup. 

this is the link to the wiki:
[https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration#add-request-level-properties-for-all-telemetry-items](wiki) 
this is my code: 

` public class PropertyTelemetryInitializer : ITelemetryInitializer
    {
        IHttpContextAccessor httpContextAccessor;

        public PropertyTelemetryInitializer(IHttpContextAccessor httpContextAccessor)
        {
            this.httpContextAccessor = httpContextAccessor;
        }

        public void Initialize(ITelemetry telemetry)
        {
            telemetry.Context.GlobalProperties["statusCode"] = httpContextAccessor.HttpContext.Response.StatusCode.ToString();
        }
    }
`
on startup in `ConfigureServices`:
`
 services.AddSingleton<ITelemetryInitializer, PropertyTelemetryInitializer>();
 services.AddApplicationInsightsTelemetry();
`

**Comment by Seabizkit** [comment]
yeah i ma see werid behavor 

```c#
       services
.AddMvc(	options =>{options.Filters.Add<ExceptionFilter>();})
.SetCompatibilityVersion(CompatibilityVersion.Version_3_0)
.ConfigureApiBehaviorOptions(options =>
{
	options.InvalidModelStateResponseFactory = actionContext =>
	{
		var modelState = actionContext.ModelState
						   .Select(p => new
						   {
							   key = p.Key,
							   errors = p.Value.Errors.Select(e => e.ErrorMessage)
						   })
						   .ToDictionary(kv => kv.key, kv => kv.errors);
		var baseResponse = new BaseResponse();
		foreach (var item in modelState)
		{
			baseResponse.AddReason(item.Key, string.Join(",", item.Value));
		}

		//need to investigate why this is null on prod
		var requestTelemetry = actionContext.HttpContext.Features.Get<RequestTelemetry>();
		if (requestTelemetry != null)
		{
			//add the reasons to Telemetry data
			var errors = new SerializableError(actionContext.ModelState);
			requestTelemetry.Properties.Add("ModelState", JsonConvert.SerializeObject(errors));
		}

		return new BadRequestObjectResult(baseResponse);// OkObjectResult(errors);
	};
})
.AddNewtonsoftJson()
.AddXmlSerializerFormatters();

```
Dev and QA this work deployed and local
 `var requestTelemetry = actionContext.HttpContext.Features.Get<RequestTelemetry>();`

but returns null in prod????

**Comment by itfwf** [comment]
@Seabizkit did you find a fix for production null ? I've encountered the same issue.

**Comment by Seabizkit** [comment]
nope still same issue and updated all the nuget packages involved thought it might be that @itfwf , if you find the answer please tell me too... very filtrating, make no sense, same code works on dev and qa environments...

**Comment by itfwf** [comment]
@Seabizkit we "solve" that issue by deleting all settings related to app inshights from appService -> Configuration
