### ISSUE TITLE
Content Security Policy with script-src 'self' prevents Application Insights javascript running

### ISSUE THREAD

**Issue by Spencerooni** [microsoft/ApplicationInsights-dotnet#1443]
In Shared/_Layout I have added the following line within the `<head>` section of my application:

`@Html.Raw(JavaScriptSnippet.FullScript)`

Which correctly outputs the Application Insights javascript, inline. However, my application has the following header in the response for security reasons...

`Content-Security-Policy:script-src 'self';`

... which prevents inline javascript. Therefore, I receive the following error in the browser console (chrome):

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-od4GZDd/FJpzTaUjnBJEZbKvWwfP3SPsG+UsfNdoDpc='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by stemixreal** [comment]
I'm new to CSP and had the same problem. Adding the sha to scrpit-src solved it quickly and easily. You'd have to change the sha if the script was changed but that isn't often afaik. I'm not up to speed on dynamic script in csp 3 yet, if it allows only nonces the sha won't work. 

Like I said I'm new to this side of things so could very easily be wrong. Checking my headers with various tools seems to confirm what I think you can do. Please feel free to correct me if I'm talking out of my hat, I'm keen to learn where I'm mistaken.

**Comment by qJake** [comment]
Any update on this? Does ASP.NET Core handle script nonces out of the box, or how is CSP being handled going forward with regards to the App Insights injected script tag?

**Comment by TimothyMothra** [comment]
For reference, the snipped comes from here: 
https://github.com/microsoft/ApplicationInsights-dotnet/blob/d032dbfdab3059f894aaa0de139a01231ccb997c/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/JavaScriptSnippet.cs#L62-L64


I'm reading up on CSP and I'm not aware of any mechanism in AspNetCore to provide a nonce for us.
- https://vcsjones.dev/2014/12/17/content-security-policy-nonces-in-asp-net-and-owin/
- https://www.tpeczek.com/2015/06/content-security-policy-in-aspnet-mvc.html
- https://joonasw.net/view/csp-in-aspnet-core


So the immediate question I have is if you implement your own nonce, where would you store it that we could read it and apply it to the script tag?

**Comment by qJake** [comment]
@TimothyMothra I have a home-grown `nonce` solution in my ASP.NET Core projects. Basically, the way it works is, I generate a `nonce` value early on in the request pipeline (pseudo-randomly), write it as part of the CSP header, and set it in the `HttpContext.Items` collection. Then, I wrote a tag helper called `auto-nonce="true"` that, if set, will read the same key out of `HttpContext.Items` and apply the correct nonce value scoped to that particular request onto the specified HTML tag. (It's valid on `<script>` and `<style>` tags and possibly some others I'm not thinking of.)

It works very well, except when stuff wants to write `<script>` tags onto the page without my control. 😉 

----

One possible solution would be, if we had the capability to do something like this:

```razor
<script auto-nonce="true">
    @Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet.WriteSnippet(false);
</script>
```

With the signature of that method being something like: `string WriteSnippet(bool includeScriptTags = true)`

----

Another solution would simply be to read a specific config value from the ASP.NET Core config provider ([we already have `ApplicationInsights:InstrumentationKey`](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-application-insights-server-side-telemetry-no-visual-studio), after all) - something like `ApplicationInsights:SuppressScriptTag` (`true`/`false`) for example.

**Comment by TimothyMothra** [comment]
@qJake thanks for your detailed reply!
This all sounds very reasonable to me. I need to review this one of our architects before we proceed.
I wanted to reply and set the expectation that there won't be a quick turn around on our end but we are taking this seriously.

**Comment by dancundy** [comment]
> @TimothyMothra I have a home-grown `nonce` solution in my ASP.NET Core projects. Basically, the way it works is, I generate a `nonce` value early on in the request pipeline (pseudo-randomly), write it as part of the CSP header, and set it in the `HttpContext.Items` collection. Then, I wrote a tag helper called `auto-nonce="true"` that, if set, will read the same key out of `HttpContext.Items` and apply the correct nonce value scoped to that particular request onto the specified HTML tag. (It's valid on `<script>` and `<style>` tags and possibly some others I'm not thinking of.)
> 
> It works very well, except when stuff wants to write `<script>` tags onto the page without my control. 😉
> 
> One possible solution would be, if we had the capability to do something like this:
> 
> ```
> <script auto-nonce="true">
>     @Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet.WriteSnippet(false);
> </script>
> ```
> 
> With the signature of that method being something like: `string WriteSnippet(bool includeScriptTags = true)`
> 
> This method, if called, would also somehow need to detect that it exists or was invoked on a Razor page, and not write the automatic snippet in that case. (Not sure it's possible to detect if this method exists in the Razor compilation context ahead of time or not.)
> 
> Another solution would simply be to read a specific config value from the ASP.NET Core config provider ([we already have `ApplicationInsights:InstrumentationKey`](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-application-insights-server-side-telemetry-no-visual-studio), after all) - something like `ApplicationInsights:SuppressScriptTag` (`true`/`false`) for example.
> 
> This may work well in conjunction with the manual snippet writing above.

This solution would be great. I use a also helper lib to manage my nonces.

**Comment by TimothyMothra** [comment]
So the plan is to add a new public property:
- `JavaScriptSnippet.FullScript` (existing)
    Provides the <script> tag and the script body
- `JavaScriptSnippet.ScriptBody` (new)
    Will provide only the script body

I'm going to try to get a PR for this today or tomorrow.

**Comment by qJake** [comment]
@TimothyMothra This is awesome. And just to come full circle so I understand how this is going to work... if we look at the [client-side snippet documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-client-side-telemetry-for-web-applications), it says to add this line:

```razor
@Html.Raw(JavaScriptSnippet.FullScript)
```

Which, for this PR, we can optionally change to:

```razor
<script auto-nonce="true"> @* Or whatever your nonce strategy is... *@
    @Html.Raw(JavaScriptSnippet.ScriptBody)
</script>
```

Correct? 😁

**Comment by TimothyMothra** [comment]
Correct! 
The idea is to give you full control over that script tag.
I have a PR for this now, but I was waiting to get some feedback.

**Comment by qJake** [comment]
I love it! I can't think of any scenarios where this wouldn't be flexible.

And I suppose that if someone decided to define the script tag as, say, `<script async defer>` and that caused telemetry issues... that's on them (and/or that's a documentation issue that should be noted as such).

**Comment by TimothyMothra** [comment]
merged. Expect this change to be available in 2.14-beta3. Should be released this or next week.

**Comment by chinwobble** [comment]
Hi I'm having trouble getting this working with these packages.
```xml
<PackageReference Include="NWebsec.AspNetCore.Middleware" Version="3.0.0" />
<PackageReference Include="NWebsec.AspNetCore.Mvc.TagHelpers" Version="3.0.0" />
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.17.0" />
```

In my startup code I have these csp headers configured:
```csharp
app.UseCsp(options =>
            {
                options.ScriptSources(s =>
                {
                    s.StrictDynamic()
                    .CustomSources("https:", "http:")
                    .Self()
                    .UnsafeInline();
                    //s.UnsafeInline().CustomSources("https://az416426.vo.msecnd.net");
                });
            });
```


After that I updated my cshtml to this:
```cshtml
<script nws-csp-add-nonce="true">
  @Html.Raw(JavaScriptSnippet.ScriptBody)
</script>
```

After I load the page  the following snippet is added.
```html
<script src="https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js"></script>
```

However it has no nonce so csp refuses to load it.
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js (“script-src”).
```

Am I missing something?

**Comment by stemixreal** [comment]
Add "https://az416426.vo.msecnd.net" to script-src
