### ISSUE TITLE
Which settings are available wihin appsettings.json?

### ISSUE THREAD

**Issue by xperiandri** [microsoft/ApplicationInsights-dotnet#1448]
Is there any documentation which settings are available to be set in `appsettings.json`?
As I looked into microsoft/ApplicationInsights-aspnetcore#276 I see `TelemetryChannel:DeveloperMode`. What is that?

Could you provide a list of settings with descriptions?

**Comment by xperiandri** [comment]
What about the link to documentation?

**Comment by cijothomas** [comment]
> What about the link to documentation?
We just released this https://github.com/microsoft/ApplicationInsights-dotnet/issues/1882.
Docs are being worked on to be released before the above becomes stable.
