### ISSUE TITLE
Using AI in NLog breaks file / console loggers

### ISSUE THREAD

**Issue by mrtristan** [microsoft/ApplicationInsights-dotnet#1449]
i found two other issues where this is reported, but both people that opened them closed them without much info:
https://github.com/microsoft/ApplicationInsights-dotnet-logging/issues/137
https://github.com/microsoft/ApplicationInsights-dotnet-logging/issues/266

it seems that if the AI target is enabled, NLog console / file loggers cease working. If you simply comment out the AI target and rule, they start working again.

sample config:

```
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <extensions>
    <add assembly="Microsoft.ApplicationInsights.NLogTarget" />
  </extensions>
  
  <targets async="true">
    <target xsi:type="File" name="logfile" fileName="D:\logs\${shortdate}.log" layout="${longdate} [${threadid}] ${uppercase:${level}} ${message}" />
    <target xsi:type="File" name="errorlogfile" fileName="D:\logs\error_${shortdate}.log" layout="${longdate} [${threadid}] ${uppercase:${level}} ${message}" />
    <target type="ApplicationInsightsTarget" name="aiTarget" />
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="logfile" />
    <logger name="*" minlevel="Error" writeTo="errorlogfile" />
    <logger name="*" minlevel="Info" writeTo="aiTarget" />
  </rules>
</nlog>
```

**Comment by zak-nye** [comment]
@mrtristan Did you ever get any further with this? I have the same issue when working on a legacy piece of code. I have made sure to remove any duplicate config added by the nuget install process, but the very presence of the ApplicationInsightsTarget seems to prevent the file and console targets working.
