### ISSUE TITLE
Telemetry Processors Design Update

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-dotnet#145]
As we announced [here](https://azure.microsoft.com/en-us/blog/request-filtering-in-application-insights-with-telemetry-processor/) we've recently added a new concept: TelemetryProcessors. It can be used for filtering telemetry collected by ApplicationInsights SDK.

We collected a feedback and there are several modification that we would like to do.
Let me describe all the scenarios that we have and explain what we have now, what we would like to change and why.

## All TelemetryProcessors in Configuration

Currently [Web SDK](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/2.0.0-beta3) by default adds 1 telemetry processor (AdaptiveSampling). You can add more custom telemetry processors to the ApplicationInsights configuration file. They will be automatically loaded as soon as you create `TelemetryConfiguration`.

Scenario is working as expected and there are no changes here.

## All TelemetryProcessors in Code

You can remove AdaptiveSampling from configuration file and configure it in code. You can also add custom telemetry processors as described [here](https://azure.microsoft.com/en-us/documentation/articles/app-insights-sampling/).

Scenario is working as expected and there are no changes here.

### Add Sampling and Custom processors after default processors from configuration file

In the next Web SDK version we would like to add several Telemetry Processors in the configuration file (e.g. filter requests out by UserAgent). At the same time if you want to provide AdaptiveSampling callback method you need to configure it in code. Right now when you configure sampling in code configuration file is ignored. That means that if you want to add AdaptiveSampling or some custom telemetry processor you also need to move all other telemetry processors that we already have in the configuration file to code.

Let's look at the example:

	var builder = TelemetryConfiguration.Active.GetTelemetryProcessorChainBuilder();
	builder.Use((next) => new AnotherProcessor(next));
	builder.UseAdaptiveSampling();
	builder.Build();

Right now in the code above

- `TelemetryConfiguration.Active` has list of processors defined in the configuration file
- `GetTelemetryProcessorChainBuilder` creates a new empty list of processors
- `Use` (and `UseAdaptiveSampling`) adds new processors to this empty list 
- `Build` overrides processors defined in `TelemetryConfiguration.Active` with the list created by `GetTelemetryProcessorChainBuilder`

Proposal: `GetTelemetryProcessorChainBuilder` creates a new list from the processors defined in the configuration file. `Use` (as before) adds to this list. 

Note: We will have default filters from the config executed first, than custom processors defined in code and sampling (if it is defined in code).

### Add Custom processors before default processors from configuration file

Currently the scenario is not supported at all because as described above when you define telemetry processor in code configuration file is ignored. With implementation update described above custom telemetry processors are added after the ones that are defined in the configuration file.

If you want to add custom telemetry processors before default ones you would have 2 options
- Define all telemetry processors in code
- Define all telemetry processors in configuration file

Mixed mode will not be supported. 

## Update TelemetryProcessor properties in code

This scenario is added to address this [issue](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/87).

The proposal is to expose readonly TelemetryProcessors collection.

	public sealed class TelemetryProcessorChain: IDisposable
	{
		public IReadOnlyCollection<ITelemetryProcessor> TelemetryProcessors { get; }
	
		public void Process(ITelemetry item);
	}

**Comment by AlexBulankou** [comment]
Nice! To clarify a few things:

> proposal: `GetTelemetryProcessorChainBuilder` creates a new list from the processors defined in the configuration file. `Use` (as before) adds to this list.

Does this mean that if I have code today that calls `GetTelemetryProcessorChainBuilder` and then adds telemetry processors manually, because previously I didn't expect this method to add them from config; I may end up with them adding twice after update? Do we have checks in place to not allow adding telemetry processors more than once?

> Update TelemetryProcessor properties in code

Would be great to understand the scenario - what telemetry processor would you like to update in code and what scenario is it addressing. Linked issue #87 didn't provide details on what properties we would like to update. Are updates applied immediately to any subsequent uses of this telemetry processor?

Also, and this may be not immediately related, it would be great to have a generic filtering processor that would allow filter out telemetry (by specifying either property/value (perhaps with a regex?) in the config file, and add a few of them, e.g. for [Browser Link](http://www.asp.net/visual-studio/overview/2013/using-browser-link) . This would teach customers that configuring filters is super easy.

**Comment by abaranch** [comment]
@AlexBulankou, Thank you for your comment.

Regarding 1
You got it right. But since right now we do not have default telemetry processors I do not think that customers would define one custom processor in code and one in the configuration file especially knowing that right now config would be ignored. So we are safe here. I also do not think that we should prohibit adding same telemetry processor several times because you may have configurable processors and you want to add them several times.

Regarding 2
Let's say you defined all processors in configuration file because you wanted one custom processor to go before default ApplicationInsights filters (that we will add in the future), but some parameters of this processor need to be updated in the runtime depending on the environment. 

Regarding 3
Yes. I agree. I think that would be out next step.

**Comment by SergeyKanzhelev** [comment]
I wonder why have you decided that ```GetTelemetryProcessorChainBuilder``` will return pre-initialized chain builder and not ```Build``` will insert modules from configuration right after all customer-defined modules? I think typical scenario is when you want to filter something before it will be sent to the standard filters and sampling processors, right?

Nice change!

**Comment by abaranch** [comment]
We optimized it for a different scenario:
- We have default filters in the config which customer does not want to define in code.
- Usually customer redefines only sampling in code that goes after our default filters
- Advanced customer also defines filters in code. In that case he removes only sampling from config and defines his filters in code and adds sampling after that.
