### ISSUE TITLE
Make class TplActivities internal or change namespace

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1452]
It's not clear that this class was ever intended to be public.
If there is no objection, we should make it internal.

If this remains public, the namespace **MUST** be changed. "Shared" is a reserved keyword.
See [CA1716: Identifiers should not match keywords](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1716-identifiers-should-not-match-keywords?view=vs-2015)

https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/93ad4a8a46965d95654fe1f962df74c3bb792a79/src/EventSource.Shared/EventSource.Shared/Utilities/TplActivities.cs#L7-L26

**Comment by eddynaka** [comment]
Hi @TimothyMothra , can I help in this?

Would be better to change to internal or change the namespace? If the namespace is the choice, what name should we give?

Thanks

**Comment by cijothomas** [comment]
@eddynaka This would be a breaking change and hence this will only be done in next major version bump to 3.0, which is not planned in immediate term.
