### ISSUE TITLE
In NLog, if use log.Info() with many parameters, can these parameters will be stored as properties in appInsights?

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-dotnet#1459]
I have installed Nlog and Microsoft.ApplicationInsights.NLogTarget with latest nuget package version.

If I use this method log.Info() in NLog, with many parameters, like below:

log.Info("a test", "param1", "param2", "param3", "param4");

then how can I send these paramters like "param1" / "param2" as custom properties in azure application insights(it means that in azure portal-> application insights-> this message "a test" should have these custom proerties)?

**Comment by snakefoot** [comment]
You can do this in NLog 4.5 (and later):
```c#
log.Info("a test {param1} {param2} {param3} {param4}", "param1", "param2", "param3", "param4");
```
See also: https://github.com/NLog/NLog/wiki/How-to-use-structured-logging
