### ISSUE TITLE
[BUG] NLogTarget does not work well with NLog Structured Logging

### ISSUE THREAD

**Issue by ionmincu** [microsoft/ApplicationInsights-dotnet#1460]
When using NLog with structured logging, parameters sent with `@` will not be logged as serialized. 

For example:
```
var position = new Pos { Latitude = 25, Longitude = 134 };
var elapsedMs = 34;

logger.Trace("Processed {@Position} in {Elapsed:000} ms.", position, elapsedMs);
```
The `Position` property of the log will be filled with `MyApp.Pos` instead of a serialized version of posisition.

**Comment by ionmincu** [comment]
Isssue is still present with `Microsoft.ApplicationInsights.NLogTarget` version 2.12.0.
Example:
```csharp
_logger.LogError("Got an IS4 error with id {errorId}, details: {@error}", errorId, message);
```
In customDimessnion it's logged as:
![image](https://user-images.githubusercontent.com/44569445/71161837-c79f7400-2252-11ea-8409-5162e4c01fcd.png)

**Comment by snakefoot** [comment]
@ionmincu Would Json-string be acceptable as property-value when having specified `@` ?

NLog has a Json-serializer that could be activated for non-primitive-types.

**Comment by snakefoot** [comment]
@ionmincu What happens if you do this:

```xml
<nlog>
  <extensions>
    <add assembly="Microsoft.ApplicationInsights.NLogTarget" />
  </extensions>

  <targets async="true">
    <target type="ApplicationInsightsTarget" name="aiTarget">
        <contextProperty name="properties">
              <layout type="JsonLayout" includeAllProperties="true" maxRecursionLimit="1" />
        </contextProperty>
    </target>
  </targets>

   <logger name="*" minlevel="Info" writeTo="aiTarget" />
</nlog>
```

**Comment by TimothyMothra** [comment]
two workarounds have been provided. I'm marking this as resolved. 
Feel free to reopen if you have additional questions.
