### ISSUE TITLE
How to use console logging with TelemetryClient?

### ISSUE THREAD

**Issue by PankajRawat333** [microsoft/ApplicationInsights-dotnet#1461]
I have written my own Logger class using "TelemetryClient" to sink data in ApplicationInsight.. which is working fine but my logs are not getting display in Azure function console log window.

this is my custom logger [Code](https://stackoverflow.com/questions/53210589/application-insight-telemetryclient-doesnt-display-logs-in-azure-function-conso)

I can understand "TelemetryClient" responsibility only sent data in ApplicationInsight regardless type of application. Is there any solution or workaround to display same logs in Azure Function console log section??

**Comment by cijothomas** [comment]
Closing old issue. There doesn't seem to be any action item for this repo.
