### ISSUE TITLE
Duplicate exceptions with log4netappender

### ISSUE THREAD

**Issue by Mystere** [microsoft/ApplicationInsights-dotnet#1463]
I spent some time trying to figure this one out.  It seems that the log4netappender translate logged exceptions to App Insights exceptions (rather than traces).  This seems like a good idea on the surface, but AI is already logging the exception as it occurs (I assume that Microsoft.ApplicationInsights.AspNet/AspNetCore do this, not to mention the Uncaught ai exception handler for MVC apps), resulting in a duplicate exception being generated.  In addition, the trace message you expect does not show up and this can lead to a lot of wasted time trying to figure out why all the traces you expect are not being logged.

Is there some preferred method to deal with this?  How do I disable this unwanted "helpful" functionality?

**Comment by CarpeTeknus** [comment]
We had to change the loglevel to "None" for certain components (middleware and lambdaexception)
