### ISSUE TITLE
ASP.Net Core 2.2 ILogger

### ISSUE THREAD

**Issue by emilssonn** [microsoft/ApplicationInsights-dotnet#1465]
After adding the Microsoft.Extensions.Logging.ApplicationInsights nuget and setting it up by following https://github.com/Microsoft/ApplicationInsights-dotnet-logging/tree/develop/src/ILogger#aspnet-core-application all logs now appears twice in application insights.

The issue is reproducible by creating an Asp.net core 2.2 api app and:

- Adding the Microsoft.ApplicationInsights.AspNetCore nuget
- Add UseApplicationInsights to Program.cs
- Add Microsoft.Extensions.Logging.ApplicationInsights and configure it according to the docs.

What is the correct way of logging to application insights in asp.net core 2.2? Should I remove some other ILogger provider? Or do I lose some other logging if I do that (for example azure diagnostic logging, Microsoft.Extensions.Logging.AzureAppServices)?

**Comment by cijothomas** [comment]
Closing as no further action is needed for this repo.
