### ISSUE TITLE
NLogTarget does not set a correlation ID

### ISSUE THREAD

**Issue by dorfire** [microsoft/ApplicationInsights-dotnet#1471]
When initializing the `TelemetryClient`, I expect the target to also set `client.Context.Operation.Id` to something, preferable a random GUID.

**Comment by amgadalaa** [comment]
Hey,
Any updates on this one?
Any way to add operation id to traces when using Nlog extension?
Thanks.

**Comment by cijothomas** [comment]
No update - have you tried the workaround suggested by @lmolkova https://github.com/microsoft/ApplicationInsights-dotnet/issues/1471#issuecomment-464177158

**Comment by amgadalaa** [comment]
@cijothomas No didn't try yet.
Someone needs to be the first to confirm it :)

**Comment by cijothomas** [comment]
@amgadalaa Please describe exactly what you are trying to achieve, and we can try to help. This issue is describing several problems and not sure which one you care about. You may open a new issue, with exact problem description also.
