### ISSUE TITLE
Package update replaces log configuration in app.config

### ISSUE THREAD

**Issue by Muhomorik** [microsoft/ApplicationInsights-dotnet#1474]
Hello,

This is an old issue that happens every time one update Microsoft.ApplicationInsights.NLogTarget.
app.config rules are replaced with default ones.

I've just updated from 2.6.4 to 2.8.2 and got this change.

![appinsights](https://user-images.githubusercontent.com/11274409/47000646-fb4fad00-d128-11e8-88e7-05c84b13f813.png)

**Comment by snakefoot** [comment]
Another poor soul bitten by this "feature":

https://usefulscripts.wordpress.com/2020/05/10/use-application-insights-logging-adapters-with-nlog-c-console-application/

**Comment by snakefoot** [comment]
Stil think this "feature" should be removed. The idea was it should help with initial setup, but actually it is causing a lot of pain during deployment with unexpected surprises. Don't like unexpected surprises.

**Comment by snakefoot** [comment]
Still bad behavior to modify config-files on nuget-package install.
