### ISSUE TITLE
Add constructor to initialize TraceListener with a TelemetryConfiguration object.

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1476]
This is a continuation of PR microsoft/ApplicationInsights-dotnet-logging#76.

We need to add a constructor to `TraceListener` to initialize it with a `TelemetryConfiguration`.
Similar to: [DependencyTrackingTelemetryModule.Initialize()](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/DependencyTrackingTelemetryModule.cs#L123)

[This must be CLS compliant](https://github.com/Microsoft/ApplicationInsights-dotnet/pull/674)

Unit Test:
Need to be able to configure Context objects (SessionId for example) and verify that they are set in TelemetryClient. See details in original PR.

**Comment by eddynaka** [comment]
Hi,

I started to take this issue and i have some questions:

Below the code that i wrote based on TelemetryClient:

```csharp
/// <summary>
/// Initializes a newinstance of the ApplicationInsightsTraceListener class.
/// </summary>
/// <param name="configuration"></param>
public ApplicationInsightsTraceListener(TelemetryConfiguration configuration)
{
    configuration = configuration ?? TelemetryConfiguration.Active;

    this.TelemetryClient = new TelemetryClient(configuration);
    
    this.TelemetryClient.Context.GetInternalContext().SdkVersion = SdkVersionUtils.GetSdkVersion("sd:");
}
```

1. TelemetryConfiguration is complaining about CLSCompliant, it is located in the Microsoft.ApplicationInsights. Should I add the tag in the class or in the AssemblyInfo.cs?
2. Based on the validation that we already have in TelemetryClient, that would be enough?

Thanks

**Comment by lmolkova** [comment]
ApplicationInsights is not CLS compliant because it depends on System.Diagnostics.DiagnosticSource which is not CLS compliant. This cannot be easily changed.

Also, the typical way to initialize TraceListener is through [config file](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/how-to-create-and-initialize-trace-listeners#to-create-and-use-a-trace-listener-by-using-a-configuration-file) where proving custom configuration is not possible.

**Comment by eddynaka** [comment]
Hi @lmolkova , I assumed it was applicationinsightsTraceListener based on the link in the original PR. Was that right?

For question one that I made, how should I proceed in make CLSCompliant?

Thanks.

**Comment by lmolkova** [comment]
Right, I also mean `ApplicationInsightsTraceListener`. 

One of the popular ways to configure such listeners is through the config file. I **guess** it means that it has to have a parameterless constructor. As a part of this work, we need to understand how this scenario works and make sure still works. 

Regarding CLS compliance: we need to find out how it should work assuming there are other APIs and dependencies in the project which are NOT CLS compliant: whether is it even possible to make Microsoft.ApplicationInsights CLS compliant.

So, there are two investigations that need to happen to proceed with this task further.

**Comment by eddynaka** [comment]
Hi @lmolkova ,

today we already have two constructors:

```csharp
public ApplicationInsightsTraceListener() : this(string.Empty){}

public ApplicationInsightsTraceListener(string instrumentationKey)
{
  // some code
}
```

So, i was adding a constructor with `TelemetryConfiguration` parameter.

About the investigation, can I help with that?


Thanks.

**Comment by lmolkova** [comment]
ok, so if we have multiple constructors already, adding another one is fine.

Regarding CLS investigation - sure, please do it.

**Comment by TimothyMothra** [comment]
I'm closing this as it is no longer necessary and a workaround is available.
