### ISSUE TITLE
ILogger - populate exception.Data into exceptionTelemetry

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1479]
Previous ILogger used to populate Exception.Data into properites.
https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/de1af6235a4cc365d64cbc78db9bdd2d579a37ee/src/Microsoft.ApplicationInsights.AspNetCore/Logging/Implementation/ApplicationInsightsLogger.cs#L72

The new implementation does not:
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/ILogger/ApplicationInsightsLogger.cs#L99

Also, the old implementation has a potential Cast exception as reported here:
https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/831

**Comment by laszlozold** [comment]
It seems like it got fixed in Version 2.5.0-beta2: https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/a135f1f7d9da7beb11f9bcf20a30f7e779b739f2/NETCORE/CHANGELOG.md

**Comment by ishepherd** [comment]
TelemetryClient.TrackException doesn't do this either.
