### ISSUE TITLE
Dependency Tracking for Always Encrypted Connection in ASP.NET Core 2.2

### ISSUE THREAD

**Issue by lsuarez5280** [microsoft/ApplicationInsights-dotnet#1482]
Hello. I wish I had more specifics around the limitations here, but I've had to transition to the [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient/) package in order to support Always Encrypted with my ASP.NET Core 2.2 application. This has the unfortunate effect of eliminating automatic wireup of SQL dependency tracking. I admit I don't fully know what events Application Insights hooks in order to facilitate SQL dependency tracking in Core, so I'm at a loss as to how to restore this to my impacted applications that have had to replace their SqlConnection factory and ISqlConnection implementation for Entity Framework Core 2. Could someone potentially point me to any place they might know of that I can reattach dependency tracking to this SqlClient, or at least how this is done in the current codebase so I can try to replicate functionality?

Currently using the Microsoft.ApplicationInsights.AspNetCore 2.8.2 package.

**Comment by lmolkova** [comment]
Please start with https://github.com/dotnet/SqlClient. They should be able to share any behavior in  DiagnosticSource hooks that are affected by Always Encrypted mode.

This is the code AppInsights is hooked to: https://github.com/dotnet/SqlClient/blob/654933a0811ab30b843a20aff051b8d585238505/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlClientDiagnosticListenerExtensions.cs

**Comment by lsuarez5280** [comment]
Thanks @lmolkova. I appreciate the pointers and will post back if I have further inquiries, along with a solution if I have one.

**Comment by lsuarez5280** [comment]
Leaving a trackback to https://github.com/dotnet/SqlClient/issues/93 since it's related to this question.

**Comment by lsuarez5280** [comment]
There are a few problems that I can identify pretty readily:
[ProfilerSqlConnectionProcessing.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/Shared/Implementation/ProfilerSqlConnectionProcessing.cs) and [ProfilerSqlCommandProcessing.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/Shared/Implementation/ProfilerSqlCommandProcessing.cs) are pretty tightly coupled in terms of generating telemetry properties from the System.Data assembly's implementation of SqlConnection and SqlCommand. In addition, [ProfilerRuntimeInstrumentation.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/Shared/Implementation/ProfilerRuntimeInstrumentation.cs) is tied to diagnostic instrumentation from the System.Data assembly, so at least I understand the why.

DependencyTrackingTelemetryModule is not very extensible in terms of replacing these elements using dependency injection, so I suppose my next question is what's the best way to proceed? I assume I should wire up function decorators similar to the ProfilerRuntimeInstrumentation that generates dependency telemetry when it detects SQL events from the Microsoft.Data assembly events outlined in the link provided [in the above comment](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1482#issuecomment-562318996), but I don't think it's going to be anywhere near as exhaustive as the standard behavior provided by this library. Did I miss an easier way to go about shimming this or am I generally out of luck here?

**Comment by lsuarez5280** [comment]
@lmolkova Actually after reviewing [SqlClientDiagnosticSourceListener.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/89d3d6398301435361f7749222ef987c443c12d8/WEB/Src/DependencyCollector/Shared/Implementation/SqlClientDiagnostics/SqlClientDiagnosticSourceListener.cs) on the latest beta release, this library appears to be supported, so please disregard this issue. I'll close for now and reopen if it's not what I anticipated.
