### ISSUE TITLE
Move Github templates to root folder.

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1486]
Move all files like "\BASE\.github\ISSUE_TEMPLATE.md" to root -> ".github\ISSUE_TEMPLATE.md"". Only ones in root are recognized by Github.

**Comment by cijothomas** [comment]
@TimothyMothra Can you do this as merging of repos broke the Github templates.

**Comment by TimothyMothra** [comment]
Sure, I can do this today
