### ISSUE TITLE
Ability to turn off Request collection for static files

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1500]
Create a new Asp.net core Web Application and make a request to any page.
Several RequestTelemetry items are auto-collected, with one corresponding to the main Request, and others for static contents like .css/.js files. (See screenshot below)
![image](https://user-images.githubusercontent.com/5232798/70683173-1b5bfd00-1c56-11ea-9a89-18d3b342756b.png)

Proposal:
1. Add a new option to RequestTrackingTelemetryModule, "DoNotTrackStaticContent", which will automatically ignore all requests to static files. 

2. An alternate proposal is to mark requests as 'IsStaticContent` and provide easy options in UI to ignore "IsStaticContent". (This require schema modification and backend/UI work as well)

3. Do nothing, let users write TelemetryProcessors to filter those Requests.

**Comment by Bouke** [comment]
I have the same question, how to configure AI to ignore static files?
