### ISSUE TITLE
v2.12.0 breaks TelemetryInitializer support in Azure Function (V2)?

### ISSUE THREAD

**Issue by Expecho** [microsoft/ApplicationInsights-dotnet#1507]
## Repro Steps
I have an azure function v2 that uses a TelemetryInitializer as outline in #1428. When I test my function using v2.11.0 I can see the TelemetryInitializer doing its work. When I update to v2.12.0 it does not work anymore. Breakpoints inside the TelemetryInitializer are not hit. Downgrading vajc to v2.11.0 makes it work again.

I have created a repo to demonstrate the issue. It can be found [here](https://github.com/Ibis-Software/AppInsightsDemo/tree/issues-ai-v2-12-0/src/FunctionApp). The master branch is set to use v2.11.0 and in that branch it works. The linked branch does not work.

##  Actual Behavior
After updating to v2.12.0 from v2.11.0 the TelemetryInitializer are not called anymore.

## Expected Behavior
I expect the TelemetryInitializer  being called.

## Version Info 
SDK Version : v2.12.0
.NET Version :	.Net Core 2.1						
Hosting Info (IIS/Azure WebApps/ etc) : Azure Function v2

**Comment by cijothomas** [comment]
Going ahead of the SDK version used by Functions is always a problem. Please take a dependency on WebJobs SDK (and not directly on ApplicationInsights). When functions update to 2.12, you'll also get 2.12. @brett from Functions team suggested this some time back.

**Comment by Expecho** [comment]
> Going ahead of the SDK version used by Functions is always a problem. Please take a dependency on WebJobs SDK (and not directly on ApplicationInsights). When functions update to 2.12, you'll also get 2.12. @brett from Functions team suggested this some time back.

That's some sound advice, thanks! Added the Microsoft.Azure.WebJobs.Logging.ApplicationInsights package.

**Comment by TimothyMothra** [comment]
@cijothomas Would you recommend that all Functions users take a dependency on the WebJobs package instead of Application Insights directly?
I feel like I see bugs like this every other month and I'm wondering how we can better document/communicate this to our customers.

**Comment by brett** [comment]
@Expecho : wrong @brett

**Comment by TimothyMothra** [comment]
Sorry, tagging @brettsam for reference

**Comment by cijothomas** [comment]
> @cijothomas Would you recommend that all Functions users take a dependency on the WebJobs package instead of Application Insights directly?
> I feel like I see bugs like this every other month and I'm wondering how we can better document/communicate this to our customers.

Yes. No direct AI sdk. Get it through web jobs only.

**Comment by Expecho** [comment]
> > @cijothomas Would you recommend that all Functions users take a dependency on the WebJobs package instead of Application Insights directly?
> > I feel like I see bugs like this every other month and I'm wondering how we can better document/communicate this to our customers.
> 
> Yes. No direct AI sdk. Get it through web jobs only.

I think the docs need some modifications as well then, since it guides developers to using the AI nuget package. See https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#log-custom-telemetry-in-c-functions

**Comment by TimothyMothra** [comment]
Thank you for sharing.
I'm re-opening this so we can track a necessary documentation update.
