### ISSUE TITLE
App Insights causes our app to crash on Windows XP

### ISSUE THREAD

**Issue by dbohls** [Microsoft/ApplicationInsights-dotnet#151]
It seems that System.Threading.Tasks.dll assembly, contained in the Microsoft.Bcl.1.1.8 NuGet package that App Insights depends on, is version 2.6.8.0.

However, Micosoft.Threading.Tasks.dll, contained in the Microsoft.Bcl.Async.1.0.168 NuGet package that App Insights depends on, expects System.Threading.Tasks.dll to be version 1.5.11.0.

See the following assembly binder log.

*** Assembly Binder Log Entry  (1/4/2016 @ 8:03:14 PM) ***

The operation failed.
Bind result: hr = 0x80131040. No description available.

Assembly manager loaded from:  c:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\xtra\temp\vb\AppInsightsTest\debug\VirtualBench.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/xtra/temp/vb/AppInsightsTest/debug/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = VirtualBench.exe
Calling assembly : Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\xtra\temp\vb\AppInsightsTest\debug\VirtualBench.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from c:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Safe mode is set (publisher policy disallowed).
LOG: Post-policy reference: System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/xtra/temp/vb/AppInsightsTest/debug/System.Threading.Tasks.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\xtra\temp\vb\AppInsightsTest\debug\System.Threading.Tasks.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: The assembly reference did not match the assembly definition found.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by SergeyKanzhelev** [comment]
Look at https://github.com/Microsoft/ApplicationInsights-dotnet/issues/97 Do you have [kb 2468871](https://support.microsoft.com/en-us/kb/2468871) installed?

**Comment by dbohls** [comment]
kb 2468871 is installed.

We generate our our csproj files, but I have now noticed the NuGet for Microsoft.Bcl.Async does add an app.config with binding redirects for System.Threading.Tasks. I'll make sure that gets included when we generate our csproj.
