### ISSUE TITLE
Understanding type and hierarchy or tracked exceptions

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-dotnet#1512]
Hi folks,

I have a question about how we track and display exception. I think that we may be displaying an inner exception where the outer exception should be shown and I would like to validate whether my reasoning makes sense.

**Scenario**:

(Full repro code below.) Inside an Azure Function I am using an Http Client to call an invalid URL and then I use response.EnsureSuccessStatusCode() to get an exception thrown. Later I catch and track that exception.

If I inspect that exception in VS I see that this is a _nested_ exception. The outer exception is HttpRequestException and it is wrapping an SocketException. This makes sense.

![image](https://user-images.githubusercontent.com/20691812/71205282-f0c20380-2256-11ea-8b85-6a882f78167e.png)

![image](https://user-images.githubusercontent.com/20691812/71205293-f61f4e00-2256-11ea-9e80-63e914521def.png)

![image](https://user-images.githubusercontent.com/20691812/71205311-fb7c9880-2256-11ea-97a2-8086402633eb.png)

However, when I look at the E2E telemetry, see the following, which I find confusing.

a)	The exception is shown twice – in the context of the dependency and then in the context of my method.
b)	The overview shows the type of the inner exception, where as the mindset I have is in terms of the outer exception – after all the outer type is what I have specified when catching it by type.

![image](https://user-images.githubusercontent.com/20691812/71205346-0d5e3b80-2257-11ea-835d-0b22d938a903.png)

The way the information is presented is a property of the data, not the UI. You can see it in the telemetry details:

[ [Go to Log Analytics and Run Query](https://portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fad825170-845c-47db-8f00-11978947b089%2FresourceGroups%2FGregP-Tests%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2FGregP-Functions03/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA22QPU%252FDMBCGdyT%252BwylTglpqxwmQCphgYGPIxIIuzpGaNnZkXwWR%252BuNxytBU6nDDfTzve3d7a5yFG7i%252BWq0O8LMhT8Cmp8DYD%252FAM2LlUbbLYv9RtkWnK0yQXslrKfClVLeRaibUQH0kGaNsZ8HgJKI9A%252BQ%252BcbNxAHjku9%252FnWgnaW0dgASdsIVRI%252ByKLMlSoQm%252FuqoKopkASJO5lMCoN336T55LwAw9TX40CLM%252BF59o6eLE81E4O93r7%252BDruo8gTsAntju1TvA7v%252BJcraEJlwW3vUW2qnSaMN78Ys4vbLRSgiGjm12EfTBA6QLCCuE7Cj45nOt%252BShGWf%252FwaAhfvoP%252Fm1DeJQBAAA%253D) ]

![image](https://user-images.githubusercontent.com/20691812/71205393-2ebf2780-2257-11ea-94e5-1565eeae2573.png)

After adding the TrackedExplicitly flag I was able to understand why I see the exception twice – it was logged by the runtime and rethrown and then it was logged by me again. This is very confusing: it took adding the TrackedExplicitly flag to understand but now that I do, I do not know if and how we can make it better. Perhaps there is any context I am missing around this, I would love to know.

The other point - taking the “main” type from the inner rather than the outer type seems less understandable. My code explicitly works with an HttpRequestException but I see a different type in the logs. Is there a specific reason why it works this way?

Thank you!

**Full repro code:**

```
using System;
using System.Threading.Tasks;
using System.Net.Http;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.Extensibility;

namespace GregP_Functions05
{
    public class Func_03_04
    {
        public const string Version = "9";

        private readonly TelemetryClient _telemetryClient;

        public Func_03_04(TelemetryConfiguration telemetryConfig)
        {
            _telemetryClient = new TelemetryClient(telemetryConfig);
        }

        [FunctionName("Func-03-04")]
        public async Task<IActionResult> Run(
                            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequest req,
                            ExecutionContext context, ILogger log)
        {
            string funcName = $"{typeof(Func_03_04).FullName}.Version.{Func_03_04.Version}";

            log.LogInformation("C# HTTP trigger function processed a request.");
            log.LogInformation($"Exec type: \"{funcName}\".");

            string simulateFailureStr = req.Query["SimulateFailure"];
            simulateFailureStr = String.IsNullOrEmpty(simulateFailureStr) ? "false" : simulateFailureStr;
            bool simulateFailure = Boolean.Parse(simulateFailureStr);

            try
            {
                using (HttpClient client = new HttpClient())
                {

                    using (HttpResponseMessage response = await client.GetAsync(simulateFailure
                                                                            ? "https://www.bing.comX/search?q=My+Query+Term"
                                                                            : "https://www.bing.com/search?q=My+Query+Term"))
                    {
                        response.EnsureSuccessStatusCode();

                        const string expectedContent = "<title>My Query Term - Bing</title>";
                        string responseContent = await response.Content.ReadAsStringAsync();
                        bool? hasExpectedContent = responseContent?.Contains(expectedContent);

                        if (true != hasExpectedContent)
                        {
                            throw new Exception("Remote call succeeded, but response did not contain the expected content.");
                        }
                    }
                }
            }
            catch (HttpRequestException exception)
            {
                _telemetryClient.TrackException(
                                        exception,
                                        new Dictionary<string, string>() { ["TrackedExplicitly"] = true.ToString() });
            }

            return new OkObjectResult($"\"{funcName}\" completed. simulateFailure={simulateFailure}. Time is {DateTimeOffset.UtcNow}.");
        }
    }
}
```

**Comment by cijothomas** [comment]
1. 
The fact that exception is shown twice is due to this known issue, where DependencyTrackingModule reports an exception. (i.e it calls TrackException). This bug/issue exists only in .net core implementation, and not in .net framework. This must be fixed.
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1362

2.  The sdkVersion field in the Exception gives a hint to who/how this was tracked - rdddsc - indicates from DependencyTrackingModule. dotnetc  - indicates manual track.

3. The Exception telemetry correctly has outerType as HttpRequestException and innermostType as 
System.Net.Sockets.SocketException

![image](https://user-images.githubusercontent.com/5232798/71207173-16e9a280-225b-11ea-8067-6efccaa6c70a.png)

Maybe this UI is designed to show innermost exception than outermost one. I'll let UI team comment on this. @zakimaksyutov ?

**Comment by cijothomas** [comment]
Closing as no action on this for a long time.

**Comment by peterbozso** [comment]
Could this be reopened for discussion please? The situation with the Azure Portal's UI is still the same as reported earlier by @macrogreg. I strongly agree that the outermost exception should be displayed on the failures/end-to-end transaction details views, instead of the innermost. Then, when troubleshooting a particular case, the developer could still drill down in Log Analytics and see the inner exception. But for a quick check, it's extremely confusing to see that my code tracks one type of exception, but on the portal I see another one. What do you think about this @cijothomas @zakimaksyutov ?

**Comment by cijothomas** [comment]
I'll wait to see if @zakimaksyutov knows if this is intentional in UI.

**Comment by gallivantor** [comment]
Any news on this? I want to second @peterbozso  that this behaviour is very confusing as App Insights UI shows the inner exception type rather than the outer exception type

**Comment by cfauchere** [comment]
Why was this issue closed? It was never answered.
