### ISSUE TITLE
CreateRequestTelemetryPrivate: System.ArgumentOutOfRangeException: Length cannot be less than zero.

### ISSUE THREAD

**Issue by Dmitry-Matveev** [microsoft/ApplicationInsights-dotnet#1513]
## Repro Steps
SDK telemetry got the following exception trending:
```
AI (Internal): [Microsoft-ApplicationInsights-Extensibility-Web] Unknown error, message System.ArgumentOutOfRangeException: Length cannot be less than zero. Parameter name: length
    at System.String.Substring(Int32 startIndex, Int32 length)
    at Microsoft.ApplicationInsights.Web.Implementation.RequestTrackingExtensions.CreateRequestTelemetryPrivate(HttpContext platformContext)
    at Microsoft.ApplicationInsights.Web.Implementation.RequestTrackingExtensions.ReadOrCreateRequestTelemetryPrivate(HttpContext platformContext)
    at Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule.OnBeginRequest(HttpContext context)
    at Microsoft.ApplicationInsights.Web.AspNetDiagnosticTelemetryModule.AspNetEventObserver.OnNext(KeyValuePair`2 value)
```

## Version Info 
SDK Version : 2.12.0-21496

**Comment by TimothyMothra** [comment]
method is here:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/35e4bb2624bcbe2af9fb5d1e724b28ffd49c460c/WEB/Src/Web/Web.Shared.Net/Implementation/RequestTrackingExtensions.cs#L14

I don't see an explicit call to String.Substring

**Comment by jakenuts** [comment]
I'm also getting this constantly now and it's a bit of a hassle as it swamps the rest of my trace telemetry.

It emerged for me at the 2.11.0-21474 version as an IndexOutOfRangeException and then evolved into ArgumentOutOfRangeException in 2.12.0-21496.

Version: dotnet:2.10.0-31626
**No exceptions**

Version: dotnet:2.11.0-21474
**IndexOutOfRangeException** 
@ W3CUtilities.TryGetTraceId < CreateRequestTelemetryPrivate < ReadOrCreateRequestTelemetryPrivate

```
AI (Internal): [Microsoft-ApplicationInsights-Extensibility-Web] Unknown error, message System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.ApplicationInsights.W3C.Internal.W3CUtilities.TryGetTraceId(String legacyId, ReadOnlySpan`1& traceId)
   at Microsoft.ApplicationInsights.Web.Implementation.RequestTrackingExtensions.CreateRequestTelemetryPrivate(HttpContext platformContext)
   at Microsoft.ApplicationInsights.Web.Implementation.RequestTrackingExtensions.ReadOrCreateRequestTelemetryPrivate(HttpContext platformContext)
   at Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule.OnBeginRequest(HttpContext context)
   at Microsoft.ApplicationInsights.Web.AspNetDiagnosticTelemetryModule.AspNetEventObserver.OnNext(KeyValuePair`2 value)
```

Version: dotnet:2.12.0-21496
**ArgumentOutOfRangeException** 
@ String.Substring < CreateRequestTelemetryPrivate < ReadOrCreateRequestTelemetryPrivate

```
AI (Internal): [Microsoft-ApplicationInsights-Extensibility-Web] Unknown error, message System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.ApplicationInsights.Web.Implementation.RequestTrackingExtensions.CreateRequestTelemetryPrivate(HttpContext platformContext)
   at Microsoft.ApplicationInsights.Web.Implementation.RequestTrackingExtensions.ReadOrCreateRequestTelemetryPrivate(HttpContext platformContext)
   at Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule.OnBeginRequest(HttpContext context)
   at Microsoft.ApplicationInsights.Web.AspNetDiagnosticTelemetryModule.AspNetEventObserver.OnNext(KeyValuePair`2 value)
```

It's hard to find a consistent pattern between events just prior to the error especially as I'm always working with a sampled subset of the events data. Can't seem to reproduce outside of production which might be a clue (availability?).

![SNAG-0112](https://user-images.githubusercontent.com/344606/71265944-55dc2e80-2315-11ea-86dd-ec149ee1ae6c.png)

**Comment by TimothyMothra** [comment]
@jakenuts thank you for the extra call stacks, this was a big help!

I think the `ArgumentOutOfRangeException` is coming from `GetRootId`.
`IndexOf` can return a value of -1 which would then throw from the call to `Substring`
https://github.com/microsoft/ApplicationInsights-dotnet/blob/e9e9347967253ffe4baa2cfe018ce5dec72a756b/WEB/Src/Common/W3C/W3CUtilities.cs#L13-L25

The `IndexOutOfRangeException` was coming from `TryGetTraceId`.
I don't see this in our internal telemetry for 2.12 so I think @lmolkova fixed this one already.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/e9e9347967253ffe4baa2cfe018ce5dec72a756b/WEB/Src/Common/W3C/W3CUtilities.cs#L27

**Comment by ssa3512** [comment]
Is there any workaround for the issue until it is released? Our trace logs are filled with nothing but this error.

![image](https://user-images.githubusercontent.com/1991399/72934549-d8e80e80-3d31-11ea-9ebe-521269c6977b.png)

**Comment by TimothyMothra** [comment]
We had a fix for this in 2.13-beta1.
Telemetry shows that this exception is still occurring. 

The plan is to disable compiler in-line optimization for this method only in the 2.13-beta2.
Our hope is that we can capture a full stack trace to see where this is occurring.

**Comment by gplwhite** [comment]
FYI - 2.13-beta1 did seem to resolve this for us.

**Comment by TimothyMothra** [comment]
we're no longer seeing this error so i'm going to close this as resolved.
