### ISSUE TITLE
ILogger in ASP.NET Core 2.2 targeting net472 does not log

### ISSUE THREAD

**Issue by krispenner** [microsoft/ApplicationInsights-dotnet#1518]
I would like my ILogger logs to be written to AI after tweaking their messages.

This all works perfectly easy when targeting netcoreapp2.2 but I cannot get this to work for net472. Please tell me what I am missing. The Application Insights ILogger integration seems to have been re-written several times over the last few years and I can't find any clear documentation as to what is required for this to work. I keep reading this is obsolete and that is not to be used. They all seem to suggest the below should just work where `services.AddApplicationInsightsTelemetry()` is all I need.
 
## Repro Steps
1. Create new **ASP.NET Core** application targeting **net472**

2. Add package reference to `Microsoft.ApplicationInsights.AspNetCore 2.12.0`

3. Replace **Startup** class with:
```cs
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddApplicationInsightsTelemetry();
        services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        app.ApplicationServices.GetService<TelemetryConfiguration>().TelemetryInitializers.Add(new TraceMessageCleanser());
        app.UseMvc();
    }
}
```

4. Replace **ValuesController** class with:
```cs
[Route("api/[controller]")]
[ApiController]
public class ValuesController : ControllerBase
{
    private readonly ILogger _logger;

    public ValuesController(ILogger<ValuesController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public ActionResult<IEnumerable<string>> Get()
    {
        _logger.LogError("ERROR message.");
        return new string[] { "value1", "value2" };
    }
}
```

5. Add **TraceMessageCleanser** class:
```cs
public class TraceMessageCleanser : ITelemetryInitializer
{
    public void Initialize(ITelemetry item)
    {
        if (item is TraceTelemetry trace)
        {
            trace.Message = "MESSAGE_OVERRIDE";
        }
    }
}
```

6. Replace **appsetting.json** with
```json
{
    "ApplicationInsights": {
        "InstrumentationKey": "YOUR_KEY_HERE"
    },
    "Logging": {
        "ApplicationInsights": {
            "LogLevel": {
                "Default": "Debug"
            }
        },
        "LogLevel": {
            "Default": "Debug"
        }
    }
}
```

7. Run the app.

##  Actual Behavior
Nothing is logged to **AI**, does not hit **TraceMessageCleanser**

## Expected Behavior
Trace event of error severity is logged to **AI** with message "MESSAGE_OVERRIDE".

## Additional Test on netcoreapp2.2

8. Replace the csproj file with:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>netcoreapp2.2</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.12.0" />
        <PackageReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
```

9. Run the app.

10. Trace event of error severity **is** logged to **AI** with message "MESSAGE_OVERRIDE".

## Version Info 
SDK Version : 2.12.0
.NET Version : 4.7.2
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS :
Hosting Info (IIS/Azure WebApps/ etc) : local running in Kestrel

**Comment by krispenner** [comment]
If I call `loggingBuilder.AddApplicationInsights()` in `ConfigureLogging()` of my `Program.cs` file. Then I start to receive TraceTelemetry instances through my TelemetryProcessor and into AI. However, from what I read I should not have to do this. **And**, doing so has now caused all non-TraceTelemetry (such as RequestTelemetry) to **not** pass through my TelemetryProcessors. 

So it seems that `loggingBuilder.AddApplicationInsights()` and `services.AddApplicationInsightsTelemetry()` are to be used exclusively (one or the other but not both).

How can I have them both working? I'm sure it's possible but I don't know what the missing piece is.

**Comment by cijothomas** [comment]
For applications targeting full framework, the new ILogger provider is not enabled.
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1312 - This issue is tracking making ilogger work for apps targeting full framework.

There is a note in doc saying full framework is not supported for the new provider.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#migrate-from-the-old-applicationinsightsloggerprovider
So you need to do both loggingBuilder.AddApplicationInsights() and services.AddApplicationInsightsTelemetry(). Former to get ilogger logs, and later to enable telemetry collection.

**Comment by krispenner** [comment]
Thank you for clarifying. However, there is an issue with this approach as I last mentioned.
When configuring ITelemetryProcessors, they now only execute on TraceTelemetry and nothing else. 

I'm guessing the `loggingBuilder.AddApplicationInsights()` creates a second client or some sort of channel that replaces the first one registered with `services.AddApplicationInsightsTelemetry()` and so any configuration applied is not used by RequestTelemetry, MetricTelemetry, or DependencyTelemetry. If I remove the `loggingBuilder.AddApplicationInsights()` call then my ITelemetryProcessors are used by requests, metrics and dependencies but then I have no traces.

How can they all use my configuration below? I want all requests, metrics, dependencies **and** traces to pass through my ITelemetryProcessors.

```cs
app.ApplicationServices.GetService<TelemetryConfiguration>().TelemetryProcessorChainBuilder
    .Use(next => new MyProcessor(next))
    .Build();
```

**Comment by cijothomas** [comment]
Lets try this:
1. Enable 'old' LoggerProvider by using `loggerfactory.AddApplicationInsights` in `Configure` method.
```public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc();

            loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Warning);
        }
```

2.  Add custom initializer like to DI in `ConfigureServices`.
```
services.AddApplicationInsightsTelemetry();
            services.AddSingleton<ITelemetryInitializer, TraceMessageCleanser>();
```

This should cause both ilogger logs from old provider, any Request/other telemetry to use same telemetry configuration containing the TraceMessageCleanser.

I think the confusion is on how to enable old logging provider by using loggerFactory. Those are deprecated and now not documented :(.

**Comment by cijothomas** [comment]
My this statement was incorrect:

> So you need to do both loggingBuilder.AddApplicationInsights() and services.AddApplicationInsightsTelemetry(). Former to get ilogger logs, and later to enable telemetry collection.

It should be `loggerFactory.AddApplicationInsights(app.ApplicationServices, LogLevel.Warning);` and not `loggingBuilder.AddApplicationInsights()`

**Comment by cijothomas** [comment]
This is fixed and should be available in the coming beta5 onwards. https://github.com/microsoft/ApplicationInsights-dotnet/pull/1539
