### ISSUE TITLE
Upgrade Microsoft.ApplicationInsights.AspNetCore 2.7.1 to 2.12 makes custom event not written to app insight

### ISSUE THREAD

**Issue by pranavkm** [microsoft/ApplicationInsights-dotnet#1519]
_From @andrew-vdb on Monday, December 23, 2019 7:51:57 PM_

### Describe the bug
Custom event is not always written to app insight

### Further technical details
- ASP.NET Core version
3.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
vs 2019 enterprise

I can see that custom event is being called but when i query it, it does not show the track event

_Copied from original issue: aspnet/AspNetCore#18012_

**Comment by pranavkm** [comment]
_From @andrew-vdb on Monday, December 23, 2019 7:53:08 PM_

Not sure if this is the correct repo to report

**Comment by pranavkm** [comment]
_From @Pilchie on Monday, December 23, 2019 8:11:10 PM_

@davidfowl do you have an Application Insights contact?

**Comment by pranavkm** [comment]
_From @davidfowl on Monday, December 23, 2019 9:22:15 PM_

Yes this should be filed on https://github.com/microsoft/ApplicationInsights-dotnet

**Comment by andrew-vdb** [comment]
```
Startup.cs
services.AddTransient<TelemetryService>();

TelemetryService.cs
public TelemetryService(TelemetryClient telemetryClient)
        {
            this.telemetryClient = telemetryClient;
        }       
```

Putting the new constructor might fix the issue

There is case where injected TelemetryClient has null sdkVersion
![image](https://user-images.githubusercontent.com/12871379/71410172-8a692680-2644-11ea-99f1-11dd27f5f848.png)

then it correctly inject with sdkVersion
![image](https://user-images.githubusercontent.com/12871379/71410208-a8368b80-2644-11ea-891d-42742bdd53f4.png)

**Comment by cijothomas** [comment]
How are you tracking custom event? 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#how-can-i-track-telemetry-thats-not-automatically-collected

**Comment by andrew-vdb** [comment]
using TrackEvent, what else...
Not by using directly but using my own class wrapper
Changing the wrapper to TelemetryClient is not an option

Please wait for some times until my tester confirm that the CustomEvent already fixed by putting new constructor in class wrapper

**Comment by cijothomas** [comment]
Follow the doc for tracking custom event. Reopen if there are follow up qns.
