### ISSUE TITLE
Ambiguity in using AddApplicationInsightsTelemetryProcessor

### ISSUE THREAD

**Issue by ganesshkumar** [microsoft/ApplicationInsights-dotnet#1520]
We have a common library which does telemetry(and bunch of other horizontal features) for aspnetcore web services and netcore background services. This project depends on both `Microsoft.ApplicationInsights.AspNetCore`(2.12.0)  and `Microsoft.ApplicationInsights.WorkerService`(2.12.0) to support both type of services,

Now when I try to use `AddApplicationInsightsTelemetryProcessor` in our package, it throws ambiguity error. I guess the issue is both the assemblies are bringing the same file (https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/develop/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs). 

I am using extern/alias as mentioned in this issue, https://github.com/NuGet/Home/issues/4989, to solve the ambiguity. Is there any cleaner way to do this?

## Version Info 
SDK Version : 2.12.0
.NET Version :	2.2 						

How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS: Windows
Hosting Info (IIS/Azure WebApps/ etc) : Service Fabric

**Comment by cijothomas** [comment]
I cant suggest anything other than saying use Microsoft.ApplicationInsights.AspNetCore for web project, and Microsoft.ApplicationInsights.WorkerService for non-web project. Using them both in a library project is not one of the recommended paths.
You may still use a single library and make telemetry work - but in that case, you have to setup everything manually, and not rely on any extensions methods like AddApplicationInsights or AddApplicationInsightsWorker etc. They are methods defined to help common scenarios (web, console etc.). If yours is custom, then these wont work as expected.

**Comment by dstj** [comment]
@cijothomas I just had the same issue (happy to have found this closed issue). I also have a scenario where I have both s web host and background service in the same project.

Trying `services.AddApplicationInsightsTelemetryProcessor<WebSocketTelemetryFilter>();` causes:
```
[CS0121] The call is ambiguous between the following methods or properties:
'Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetryProcessor<T>(Microsoft.Extensions.DependencyInjection.IServiceCollection)'
and
'Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetryProcessor<T>(Microsoft.Extensions.DependencyInjection.IServiceCollection)'
```

I'll try your suggestion:
>you have to setup everything manually, and not rely on any extensions methods like AddApplicationInsights or AddApplicationInsightsWorker etc.

But might I suggest adding this example to the official documentation somewhere?

**Comment by cijothomas** [comment]
@dstj Does this help -> https://github.com/MicrosoftDocs/azure-docs/issues/53063

**Comment by dstj** [comment]
@cijothomas Thanks. Helps a bit. I think. "b." says:

> b. clarify that HostedServices inside Asp.net core application using AspNetCore package, can have telemetryclient injected to it. This will share config with rest of the web application.

I think that helps. I'm not sure how to do it, but I would then need to configure the `TelemetryClient` outside the `WebHost` and then find a way to pass it to both the web host and the background service (since my two services don't share the DI container).

**Comment by cijothomas** [comment]
If the web and background dont share the DI, then you'd need to add both nugets.

**Comment by dstj** [comment]
@cijothomas 
That's what I had done, but when I had to add a TelemetryProcessor to filter out web socket connections like so `services.AddApplicationInsightsTelemetryProcessor<WebSocketTelemetryFilter>();`, I got the `[CS0121] The call is ambiguous between the following methods or properties:` error... which got me here in the first place.

**Comment by cijothomas** [comment]
This:
```
services.AddSingleton<ApplicationInsights.AspNetCore.ITelemetryProcessorFactory>(builder => new ProcessorForAspNetCore());
services.AddSingleton<ApplicationInsights.WorkerService.ITelemetryProcessorFactory>(builder => new ProcessorForWorkder());
```

**Comment by dstj** [comment]
@cijothomas Thanks! I managed to patch the missing links. For those who may stumble on this issue, the final setup is: 

```csharp
services.AddSingleton<ITelemetryProcessorFactory>(builder => new WebSocketTelemetryFilterFactory());
services.AddApplicationInsightsTelemetry();
services.AddMvc(options => {
...

public class WebSocketTelemetryFilterFactory : ITelemetryProcessorFactory
{
	public ITelemetryProcessor Create(ITelemetryProcessor nextProcessor)
	{
		return new WebSocketTelemetryFilter(nextProcessor);
	}
}

public class WebSocketTelemetryFilter : ITelemetryProcessor
{
	private ITelemetryProcessor Next { get; set; }

	public WebSocketTelemetryFilter(ITelemetryProcessor next)
	{
		Next = next;
	}

	public void Process(ITelemetry item)
	{
		const string webSocketPath = "/ws";
		if (item is RequestTelemetry request && request.Url.AbsolutePath == webSocketPath) {
			return;
		}

		Next.Process(item);
	}
}
```

**Comment by DishanRajapaksha** [comment]
> 
> 
> @cijothomas Thanks! I managed to patch the missing links. For those who may stumble on this issue, the final setup is:
> 
> ```cs
> services.AddSingleton<ITelemetryProcessorFactory>(builder => new WebSocketTelemetryFilterFactory());
> services.AddApplicationInsightsTelemetry();
> services.AddMvc(options => {
> ...
> 
> public class WebSocketTelemetryFilterFactory : ITelemetryProcessorFactory
> {
> 	public ITelemetryProcessor Create(ITelemetryProcessor nextProcessor)
> 	{
> 		return new WebSocketTelemetryFilter(nextProcessor);
> 	}
> }
> 
> public class WebSocketTelemetryFilter : ITelemetryProcessor
> {
> 	private ITelemetryProcessor Next { get; set; }
> 
> 	public WebSocketTelemetryFilter(ITelemetryProcessor next)
> 	{
> 		Next = next;
> 	}
> 
> 	public void Process(ITelemetry item)
> 	{
> 		const string webSocketPath = "/ws";
> 		if (item is RequestTelemetry request && request.Url.AbsolutePath == webSocketPath) {
> 			return;
> 		}
> 
> 		Next.Process(item);
> 	}
> }
> ```

Thank you. This should be in the official documentation.
