### ISSUE TITLE
Offline support for ApplicationInsightsTarget

### ISSUE THREAD

**Issue by subramaniamb** [microsoft/ApplicationInsights-dotnet#1530]
We have successfully integrated our Xamarin Forms application with Azure Application Insights using Microsoft.ApplicationInsights.NLogTarget. It's working perfect in online scenarios. Our app has an offline capability, so how can we enable offline scenarios also with Microsoft.ApplicationInsights.NLogTarget? Is there any samples for the same?

**Comment by TimothyMothra** [comment]
Our SDK does have support for local storage folders.
You'll want to configure the `ServerTelemetryChannel`

Please review this doc: https://docs.microsoft.com/en-us/azure/azure-monitor/app/telemetry-channels#configurable-settings-in-channels
Pay attention to the data-loss scenarios.
