### ISSUE TITLE
ServerTelemetryChannel files persisted to disk during network outage do not process after network is restored without restarting the application.

### ISSUE THREAD

**Issue by petedzappulla** [microsoft/ApplicationInsights-dotnet#1535]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Execute an application that writes app insights telemetry with a configured ServerTelemetryChannel
2. Disconnect from WiFi
3. Verify that .trn files are being persisted to the configured ServerTelemetryChannel StorageFolder
4. Re-connect to WiFi

##  Actual Behavior
.trn files continue to be persisted to disk after the WiFi connection is restored, and previously persisted files are not processed and sent to App Insights until the application is stopped and restarted at which time the files will be properly processed.

## Expected Behavior
.trn files cease to be persisted and telemetry begins to be sent to App Insights again. All previously persisted .trn files are processed and sent to App Insights without having to restart the application.

## Version Info 
SDK Version : 2.12.0
.NET Version :	Core 3.1 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Windows10
Hosting Info (IIS/Azure WebApps/ etc) : N/A (Console App)

**Comment by TimothyMothra** [comment]
Hi @petedzappulla,
The `ServerTelemetryChannel` uses an exponential backoff logic whenever network errors are encountered. (Min 10 seconds, Max 1 hour).
If you allow your application to continue running, it should eventually resume transmission and clear out the local storage.

This is not documented well and I'm sorry for the confusion this caused. Please feel free to ask any follow-up questions


https://github.com/microsoft/ApplicationInsights-dotnet/blob/7633ae849edc826a8547745b6bf9f3174715d4bd/BASE/src/ServerTelemetryChannel/Implementation/BackoffLogicManager.cs#L172-L197

This wasn't designed to be monitored, but if you need to inspect this you can collect the ETW logs:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/8e9c3964be6ea989276cb290905836749aee4671/BASE/src/ServerTelemetryChannel/Implementation/TelemetryChannelEventSource.cs#L54-L58

**Comment by petedzappulla** [comment]
Thanks for the reply! That makes sense. I just tested it with a much shorter disconnected timespan and it worked perfectly. It would be good to be able to configure the `MaxDelayInSeconds`. In our case, we have thousands of devices that only come online for a minute or so every 30 minutes, and only stay connected for as long as it takes them to push and pull their updates. During the connected period we need the persisted telemetry to be processed. Might have to fork and modify. Appreciate the info!

**Comment by TimothyMothra** [comment]
You're welcome!
I'm going to leave this issue open so we have this on our backlog to update the documentation.
