### ISSUE TITLE
Better documentation for Changing sampling settings in ASP.NET Core

### ISSUE THREAD

**Issue by GeeWee** [microsoft/ApplicationInsights-dotnet#1540]
The documentation [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#configure-sampling-settings)

Seems like it could be documented much better, there's really quite a few ways to shoot yourself in the foot here:

## How to add custom telemetryProcessors
From the docs
```
    // var builder = configuration.DefaultTelemetrySink.TelemetryProcessorChainBuilder;

    builder.Build();

    // If you have other telemetry processors:
    builder.Use((next) => new AnotherProcessor(next));
```

However, looking at the source code, `builder.Use` adds the processor to the `TelemetryProcessorChainBuilder.factories`, which is only used when `.Build()` is called. Adding a processor that simply logged things to the console and adding it before the build, also confirmed this.

We had a custom processor that was meant to do filtering, but unfortunately it didn't (as it wasn't activated) which meant we've run up over 5K in Application Insights bills :(

## Make sure to emphasize that you can't use IOptionsMonitor
Especially when we have a workflow that says "disable adaptive sampling" and then re-activate it later again, I think it's important to emphasize what can go wrong. By habit instead of injecting a `TelemetryConfiguration` I injected an `IOptionsMonitor<TelemetryConfiguration>`.
This does not work, as the settings are not applied when calling `Build()` on the `TelemetryProcessorChainBuilder` you get from that. This `TelemetryConfiguration` is (seemingly) completely cut off from the rest of the Application Insights settings.

Unfortunately, these two mistakes together (no custom processor to filter, and adaptive sampling not being enabled) meant we managed to rack up quite the bill. I think the documentation could use a few helping touches, to prevent anyone else from getting an experience that's equally bad.

## Version Info 
SDK Version : Microsoft.ApplicationInsights.AspNetCore Version=2.8.2
.NET Version : 3.0	 						 
OS : Linux
Hosting Info (IIS/Azure WebApps/ etc) : AKS

**Comment by reyang** [comment]
@GeeWee thanks for letting us know.

The document issue has been fixed [here](https://github.com/MicrosoftDocs/azure-docs/commit/f3611aadf22a59c97e4f3a2d170c6eb3364977f9#diff-fd9dc24c0162dcd81c0b5a013d2bf092).
We will reach out to you and give you a full refund.

Sorry for the inconvenience this has caused.
