### ISSUE TITLE
Do automatic flush in ILoggerProvider.

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1548]
Tracking item to implement suggestion from these:
https://github.com/microsoft/ApplicationInsights-dotnet-logging/issues/276
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/870

Proposal is to react to application lifecycle and call flush automatically.

**Comment by ohadschn** [comment]
Why is this `ILoggerProvider` specific? 
I could be using TelemetryClient dircetly, using it for metrics, etc. 
IMO this should be something like "flush TelemetryClient on ASP.NET Core application exit shutdown".

**Comment by cijothomas** [comment]
> Why is this `ILoggerProvider` specific? I could be using TelemetryClient directly, use it for metrics, etc.
> I think a more generic title for this issue would be something like "flush TelemetryClient on ASP.NET Core application exit shutdown" (which would be relevant for both `ApplicationInsights.AspNetCore` and `ApplicationInsights.WorkerService`).

You are right. We also want to track this for console app using the standalone ApplicationInsightsLoggerProvider.
(Unfortunately, this is not being worked on by anyone, and is not planned for 2020)

**Comment by ohadschn** [comment]
I think we both agree this behavior is necessary for both web (`AddApplicationInsightsTelemetry`) and non-web (`AddApplicationInsightsTelemetryWorkerService`) projects, but my point was that [logger providers](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#logging-providers) are only relevant in the context of `ILogger`:
```cs
public MyClass(ILogger<MyClass> logger)
{
   logger.LogInformation("foo"); //this will be send to all configured logging providers, including AI
}
```

However there are other ways to use AI after enabling it in the web/non-web ASP.NET framework. Specifically, we are doing something like this:
```cs
public MyClass(TelemetryClient client)
{
   client.GetMetric("bar").TrackValue(42);
}
```

AFAIK this has nothing to do with logger providers, yet flushing is very much relevant for it (in fact critical for our short-running process).

**Comment by aaron-0** [comment]
Any updates?

**Comment by cijothomas** [comment]
No updates (I removed stale marker).
