### ISSUE TITLE
DiagnosticTelemetryModule( and HeartBeat) is not added via DI, hence configuration is differently done

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1559]
DiagnosticTelemetryModule( and HeartBeat) is added to TelemetryConfiguration by base SDK and not added via DI like other modules. This means it'll not possible to configure this module via services.ConfigureTelemetryModule<DiagnosticModule>() mechanism.
However, this module is part of the `TelemetryModules.Instance.Modules` singleton, and hence can be retrieved this way for configuration.

## Version Info 
SDK Version :
.NET Version :	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS :
Hosting Info (IIS/Azure WebApps/ etc) :

**Comment by Taudris** [comment]
Is this an adequate upgrade-resistant workaround I can use in production until this gets resolved?

    if (!services.Any(o => typeof(IHeartbeatPropertyManager).IsAssignableFrom(o.ImplementationType)))
    {
        services.AddSingleton<ITelemetryModule, DiagnosticsTelemetryModule>();
    }

**Comment by cijothomas** [comment]
@Taudris `DiagnosticsTelemetryModule` is added, but in a different way. So you dont need to add this yourself. 
What is it that you are trying to achieve? I can try to help based on your actual goal.

**Comment by the-wrangler17** [comment]
I need to be able to customize the heartbeat interval, as well. If the DiagnosticsTelemetryModule is being added in a different way, how can we configure it?

**Comment by cijothomas** [comment]
This issue about heartbeat is not solved fully.
As a temporary workaround for WorkerServices, you can manually add `DiagnosticsTelemetryModule` to DI and configure it's heartbeat interval.

```
services.TryAddSingleton<ITelemetryModule, DiagnosticsTelemetryModule>();
                    services.ConfigureTelemetryModule<DiagnosticsTelemetryModule>((mod,opt) => mod.HeartbeatInterval = TimeSpan.FromSeconds(30));
                    services.AddApplicationInsightsTelemetryWorkerService();
```

**Comment by cijothomas** [comment]
@Taudris Your snippet or mine above should do the job for now.

There is no one actively working to solve this issue right now, so workarounds until then.

**Comment by cijothomas** [comment]
@TimothyMothra is working on addressing this issue. Expecting to ship with next stable release.

**Comment by cijothomas** [comment]
> @Taudris Your snippet or mine above should do the job for now.
> 
> There is no one actively working to solve this issue right now, so workarounds until then.

I think your snippet is the correct one. Mine is most likely incorrect - sorry for that.

**Comment by cijothomas** [comment]
Taggging @TimothyMothra to confirm fix and closing this.
