### ISSUE TITLE
Catch and handle "infinite nested TelemetryInitializer loop"

### ISSUE THREAD

**Issue by zippy1981** [microsoft/ApplicationInsights-dotnet#1561]
## Repro Steps
1. Have a solution where `ILogger` messages are logged to Application Insights traceEvents
2. Add a TraceInitializer like so:

    public class SelfLoggingTelemetryInitializer: ITelemetryInitializer
    {
        private IHttpContextAccessor httpContextAccessor;

        public SelfLoggingRequestTelemetryInitializer(IHttpContextAccessor httpContextAccessor)
        {
            this.httpContextAccessor = httpContextAccessor ?? throw new ArgumentNullException("httpContextAccessor");
        }
        public void Initialize(ITelemetry telemetry)
        {
            if (!(telemetry is RequestTelemetry))
            {
                return;
            }
            var context = this.httpContextAccessor.HttpContext;

            if (context == null)
            {
                return;
            }

            lock (context)
            {
                if (context.RequestServices == null)
                {
                    return;
                }
                var logger = context.RequestServices.GetService<ILogger<NewTelemetryInitializer>>();
				logger.LogTrace("This logger happens to go towards ApplicationInsights.");
                
            }
        }
    }

1. Log elsewhere in your Asp.NET Core Application

##  Actual Behavior
Controllers don't return because of "recursive" Initializer locking each other

## Expected Behavior
At around 10-20 nested Initializers loops deep an exception is thrown.

## Version Info 
SDK Version : 2.5.1
.NET Version :	Core 2.0
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio With the Serilog sink configuring application insights
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Kestrel console app

**Comment by filoe** [comment]
+1
Having same issue.

**Comment by IanKemp** [comment]
See also #1536 .
