### ISSUE TITLE
Issue with ITelemetryProcessor after migrating to aspnet core 2.1

### ISSUE THREAD

**Issue by peter-bozovic** [microsoft/ApplicationInsights-dotnet#1563]
I'm having different behavior since updated aspnet core project from 2.0 to 2.1 and AI library from 2.1.1 to 2.3
Not sure if this might be related to the new version of Entity Framework, but I'm having similar issue with filtering Azure Storage telemetry so I'm starting here.

## Repro Steps
Im using following code to filter SQL requests so that they are not sent to Application Insights:
```
public class DefaultSqlFilter : ITelemetryProcessor {
	private ITelemetryProcessor Next { get; set; }
	public DefaultSqlFilter(ITelemetryProcessor next) {
		this.Next = next;
	}
	public void Process(ITelemetry item) {
		if (item is DependencyTelemetry dependency) {
			if (dependency.Type == "SQL") {
				return;
			}
		}
		this.Next.Process(item);
	}
}
```
And in my startup.cs Configure method:
```
var processorBuilder = TelemetryConfiguration.Active.TelemetryProcessorChainBuilder;
processorBuilder.Use((next) => new DefaultSqlFilter(next));
processorBuilder.Build();
```

##  Actual Behavior
My TelemetryProcessor is never hit with DependencyTelemetry of Type == "SQL".
Even when checking all items going trough the TelemetryProcessor, there is nothing related to the Entity Framework.
However, the Request details in Azure Portal is displaying calls done to the database, they are not filtered.

## Expected Behavior

Telemetry related to SQL call is filtered and not sent to Application Insights and not displayed in Request Details

## Version Info 
SDK Version : aspnet core 2.1 
.NET Version : net47
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : nuGet
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Azure AppService

**Comment by TimothyMothra** [comment]
Note to self: assign to M Bullwinkle

**Comment by TimothyMothra** [comment]
@mrbullwinkle any update?

**Comment by TimothyMothra** [comment]
note to self:
open equivalent issue in Docs repo, and assign to MB.
Will close this issue.

**Comment by TimothyMothra** [comment]
FYI: Paul's code samples were moved to here:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/snapshot-debugger-vm#configure-snapshot-collection-for-applications-using-aspnet-core-20-or-above
