### ISSUE TITLE
Crash from SendRequestAsync is unhandled

### ISSUE THREAD

**Issue by RyanSizemore** [Microsoft/ApplicationInsights-dotnet#157]
We are seeing a crash in our application with the following stack (we have seen ~3 occurrences of this):

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. 
---> System.Net.WebException: The request was aborted: The request was canceled.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.ApplicationInsights.Channel.Transmission.<SendRequestAsync>d__24.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The request was aborted: The request was canceled.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.ApplicationInsights.Channel.Transmission.<SendRequestAsync>d__24.MoveNext()<---
```

Because the exception occurs in a task and is unhandled, we get a TaskUnobserved exception, resulting in our app crashing. It would seem that some level of try/catch is needed to suppress the exception (probably in the Transmission class), since we have no way to reliably suppress the failure at our app's level.

**Comment by SergeyKanzhelev** [comment]
What version of SDK do you use? Is it server app or desktop/store?

**Comment by RyanSizemore** [comment]
Not sure on the version. The assembly shows a version of 0.12.0.17386.

This is a desktop (C#) app.


-       Ryan

**Comment by SergeyKanzhelev** [comment]
@izikl , I believe it was fixed, right? Do you remember exact version?

**Comment by izikl** [comment]
Not sure. @RyanSizemore can you upgrade to a stable released SDK?

**Comment by abaranch** [comment]
@RyanSizemore. Closing the issue, please upgrade at least to the latest stable version. 0.12 is not supported any more.

**Comment by mifurm** [comment]
Team, I have AppInsight SDK installed with versions, which you can see below the picture. This is ASP.Net MVC app and the issue described in here still exsists. 
Here you have the error.
![appinsight](https://user-images.githubusercontent.com/16135464/28605713-719b2a36-71d3-11e7-9c3a-0871fb54162a.png)

And here are my SDK versions. Can you please help?
<package id="Microsoft.ApplicationInsights" version="2.1.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="1.2.1" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.1.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.JavaScript" version="0.15.0-build58334" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Log4NetAppender" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.1.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.1.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.1.0" targetFramework="net461" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.1.0" targetFramework

**Comment by SergeyKanzhelev** [comment]
@mifurm Application Insights SDK has logic to collect unobserved exceptions. It may indicate a problem with your application. Typically it will happen when Task was started and not awaited for by any code. And this task throws an exception. So there is no code to handle this exception. It may indicate a bigger problem with your code.

It's not easy to correlate an unobserver exception with the code that initiated it. Upgrade to 2.4 SDK may help as that version has improved telemetry correlation capabilities.
