### ISSUE TITLE
Write better documentation on self-host aps onboarding to AI using WindowsServer NuGet

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#1570]
We need to update azure documentation [here](https://azure.microsoft.com/en-us/documentation/articles/app-insights-platforms/) and [here](https://azure.microsoft.com/en-us/documentation/articles/app-insights-asp-net/) to include instructions how to onboard self-host applications to Application Insights using WindowsServer NuGet.

**Comment by ank3it** [comment]
Closing old issues
