### ISSUE TITLE
Failed dependency without ResultCode

### ISSUE THREAD

**Issue by AlexKlimovMS** [microsoft/ApplicationInsights-dotnet#1580]
In live streams found following failed dependency without ResultCode:
      "DependencyTypeName": "Http",
      "DocumentType": "RemoteDependency",
      "Duration": "PT0.382S",
      "ResultCode": "",
      "Success": false,

Version of Microsoft.ApplicationInsights.DependencyCollector is 2.3.0-beta1. Could you please investigate/track with telemetry for which failed dependencies SDK fails to resolve ResultCode?

**Comment by cijothomas** [comment]
Closing old issue. Dep collection is now mostly from diagnosticsource callback.
