### ISSUE TITLE
TelemetryItem object cannot be re-used across the TelemetryClient objects

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#159]
**Steps to reproduce:**
 1. New up one RequestTelemetry or EventTelemetry object "Ping"
 2. New up two TelemetryClient objects with the different IKeys: IKey1 and IKey2
 3. Use the same "ping" telemetry object  in both clients to send "ping" telemetry periodically
 4. First Client sends "Ping" telemetry item with IKey1
 5. Second Client sends "Ping" telemetry with IKey1 as well, IKey2 is ignored because context was already initialized for "ping" telemetry item by the first client.
 6. As a result "Ping" telemetry is only send for IKey1 and in a doubled amount...

**Expected Behavior:**
The correct IKey is used (all Lazy Initializers, including Context are run again), Client1 sends this telemetry item to IKey1, client2 to IKey2.

***or***

We prevent this coding pattern (either throw "Cannot use the same TelemetryItem twice" or ...)

This bug is reported by customer who tried to use the product in this way and could not understand why does it behave like that. This might be considered a "Doc bug" if we want to.

The code is simple:

``` csharp
            var configuration1 = TelemetryConfiguration.CreateDefault();
            configuration1.InstrumentationKey = "111";

            var configuration2 = TelemetryConfiguration.CreateDefault();
            configuration2.InstrumentationKey = "222";

            var client1 = new TelemetryClient(configuration1);
            var client2 = new TelemetryClient(configuration2);

            var tcEvent = new RequestTelemetry("Test", DateTime.Now, TimeSpan.FromSeconds(1), string.Empty, true);
            client1.TrackRequest(tcEvent);
            client2.TrackRequest(tcEvent);
```

or even without the TelemetryConfiguration, just with TelemetryClient:

``` charp
            var client1 = new TelemetryClient(configuration1);
            client1.InstrumentationKey="111"
            var client2 = new TelemetryClient(configuration2);
            client2.InstrumentationKey="222"
            var tcEvent = new RequestTelemetry("Test", DateTime.Now, TimeSpan.FromSeconds(1), string.Empty, true);
            client1.TrackRequest(tcEvent);
            client2.TrackRequest(tcEvent);
```

**Comment by madeleinefletcher** [comment]
Added documentation that explicitly recommends against re-using event items.
