### ISSUE TITLE
Not all exceptions tracked using TrackException are shown as exception statistics

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#1590]
On one of the test applications I see exceptions reported by standard `TrackException` that not appearing as exception statistics metric.

After initial investigation - it may be related to https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/511 or can be a separate issue. Potentially an exceptions is thrown while extracting data in the first chance exception callback that prevents metric increment

**Comment by cijothomas** [comment]
ExceptionStats is no longer enabled publicly, hence closing this old issue.
