### ISSUE TITLE
Support collecting non-HTTP dependency calls from 3rd party libraries

### ISSUE THREAD

**Issue by TomMilos** [microsoft/ApplicationInsights-dotnet#1595]
Use DiagnosticSource to collect RDD telemetry from 3rd-party SDKs/libraries. This requires defining the "contract" for dependency collection which later can be implemented directly in particular libraries

The approach we want to use is based on DiagnosticSource Activities - AI ```DependencyTrackingTelemetryModule``` will implement a DiagnosticSource subscriber which will subscribe to all activities following given naming convention (TBD) with possible support of config-based white/blacklists. All of those activities are expected to follow the OpenTracing tag naming convention (https://github.com/opentracing/specification/blob/master/semantic_conventions.md) which will allow the listener to construct meaningful RDD telemetry.

The next steps are to contribute to selected 3rd-party projects in order to add corresponding Activities relevant to given technology

**Comment by milkshakeuk** [comment]
It would be great if MongoDB could be supported especially since this is already officially supported in the [Official Application Insights NodeJs Npm Package](https://github.com/Microsoft/ApplicationInsights-node.js).

**Comment by cijothomas** [comment]
@milkshakeuk There are no additional dependency collection planned for application insights SDK this year. We are investing into OpenTelemetry and any new dependency collection will come through open telemetry integration - The details about the same would be shared in the coming months. (most likely all that users need to do is to simply upgrade to newer version of SDK, and underneath it could use OpenTelemetry.. but these details are not yet designed and hence not shared)
