### ISSUE TITLE
Operationid algo screws up sampling algo

### ISSUE THREAD

**Issue by MaxShehovtsov** [Microsoft/ApplicationInsights-dotnet#160]
New algorithm for creating operationid produces 6 char strings (much shorter than it used to be with guids). This seems to screw up sampling algorithm (DJB hash) which seems to not work properly on short strings (bad distribution, 98+% of hashes have score <= 20, score should be equal to distribution)

This makes sampling work incorrectly.

Proposed solution is to fall back to original guids instead of 6 char ids or investigate a use of a different hash algorithm which works on short strings (NOTE - both .net and JSSDK should use the same algorithm as both can have sampling ON and should sample in/out the same users)

**Comment by SergeyKanzhelev** [comment]
@vitalyf007 - ID is quite random. Can we change sampling algorithm to work fine on small strings?

**Comment by SergeyKanzhelev** [comment]
The decision was to concat the same string to the desired length like this. PR: https://github.com/Microsoft/ApplicationInsights-JS/pull/117

``` js
getSamplingHashCode: function (input) {
        if (input == "") {
            return 0;
        }
             
        var desiredResultLength = 8;
        while (input.length < desiredResultLength){
            input = input.concat(input);
            input = input.substr(0, desiredResultLength);
        }
```


Unit tests:
                    ["ss", 1179811869],
                    ["kxi", 34202699],
                    ["wr", 1281077591],
                    ["ynehgfhyuiltaiqovbpyhpm", 2139623659],
                    ["iaxxtklcw", 1941943012],
                    ["hjwvqjiiwhoxrtsjma", 1824011880],
                    ["rpiauyg", 251412007],
                    ["jekvjvh", 9189387],
                    ["hq", 1807146729],
                    ["kgqxrftjhefkwlufcxibwjcy", 270215819],
                    ["lkfc", 1228617029],
                    ["skrnpybqqu", 223230949],
                    ["px", 70671963],
                    ["dtn", 904623389],
                    ["nqfcxobaequ", 397313566],
                    ["togxlt", 948170633],
                    ["jvvdkhnahkaujxarkd", 1486894898],
                    ["mcloukvkamiaqja", 56804453],
                    ["ornuu", 1588005865],
                    ["otodvlhtvu", 1544494884],
                    ["uhpwhasnvmnykjkitla", 981289895],
                    ["itbnryqnjcgpmfuckghqtg", 1481733713],
                    ["wauetkdnivwlafbfhiedsfx", 2114415420],
                    ["fniwmeidbvd", 508699380],
                    ["vuwdgoxspstvj", 1821547235],
                    ["y", 1406544563],
                    ["pceqcixfb", 1282453766],
                    ["aentke", 255756533],
                    ["ni", 1696510239],
                    ["lbwehevltlnl", 1466602040],
                    ["ymxql", 1974582171],
                    ["mvqbaosfuip", 1560556398],
                    ["urmwofajwmmlornynglm", 701710403],
                    ["buptyvonyacerrt", 1315240646],
                    ["cxsqcnyieliatqnwc", 76148095],
                    ["svvco", 1849105799],
                    ["luwmjhwyt", 553630912],
                    ["lisvmmug", 822987687],
                    ["mmntilfbmxwuyij", 882214597],
                    ["hqmyv", 1510970959],
