### ISSUE TITLE
AppServicesHeartbeatTelemetryModule is not initialized properly if TelemetryConfiguration.Active is not set

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1601]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Create `AppServicesHeartbeatTelemetryModule`
2. Create new TelemtryConfiguration
3. Initialize heartbeat module with the new configuration

##  Actual Behavior
no heartbeats reported. The module tries to find `IHeartbeatPropertyManager` in static singleton `TelemetryModules.Instance`.

The latter is set up by TelemetryConfiguration.Active invocation.

## Expected Behavior
heartbeats work

We should make heartbeats initialized explicitly without static singletons as any other component.
If it's not possible - heartbeat modules should touch Active config/do other precautions to make sure they will start properly

**Comment by cijothomas** [comment]
@TimothyMothra This can be closed now, right?

**Comment by TimothyMothra** [comment]
Liudmila's repro is still valid.
The Module Initialize method only takes a TelemetryConfiguration which itself doesn't have a reference to a TelemetryModules collection. So the Module still has to look at the TelemetryModules.Instance singleton to find Heartbeat.

We exposed a IHeartbeatPropertyManager property so it can be manually set now.

**Comment by cijothomas** [comment]
Got it. This issue is only for those folks who hand create the modules.
Since we provide correct solution for Asp.Net, Asp.Net Core, Console/Worker - I feel this issue can be closed.

**Comment by TimothyMothra** [comment]
I'm okay with that.
