### ISSUE TITLE
Library instrumentation guidance with DiagnosticSource

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1603]
We are looking for help from the tracing community to review out library instrumentation guidance

https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/LibraryInstrumentationGuidance.md

Start of the discussion:
https://github.com/StackExchange/StackExchange.Redis/issues/833

We will be happy to hear your feedback about anything, some exiting concerns:
- no configuration
- no contract 
- Tags vs payload usage
- lack of detail
- efficiency/performance
- concrete vs anonymous types

We hope to come up with the guidance that would work well with library owners and tracing systems.
Our philosophy for tracing still has to follow some principles like
- automagical with (almost) zero configuration
- (almost) zero perf impact when nobody listens to, and runtime sampling and verbosity control when there is a listener
- no additional dependencies, so .NET is traceable itself
- ability to build rich UI on top of it and run our important customer scenarios

We'll publish the result in more official place.

/cc @cwe1ss, @NickCraver, @stebet,  @vancem

Update: I will submit the first PR later this week emphasizing concrete payload types, proposing PascalCase and would provide mode details about sampling/verbosity

**Comment by lucaspimentel** [comment]
With the repo migration, the new link to the document is:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/LibraryInstrumentationGuidance.md
