### ISSUE TITLE
SDK ceiling up CPU on 5-10K/s TrackEvent calls without sending any data

### ISSUE THREAD

**Issue by netgh0st** [microsoft/ApplicationInsights-dotnet#1605]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Implement a processor that drops all Event documents (see [BlockTracesAndEventsTelemetryProcessor.zip](https://github.com/Microsoft/ApplicationInsights-dotnet-server/files/1601960/BlockTracesAndEventsTelemetryProcessor.zip) for example)
2. Implement any logic that would call TrackEvent at a rate of 5-10K calls per second

##  Actual Behavior
Process uses up all CPU, with most of the time spend inside Initialize method

## Expected Behavior
Since no data is being send, no noticeable impact on process CPU time from adding TrackEvent calls

![trackevent dottrace](https://user-images.githubusercontent.com/1855900/34543769-7341640c-f097-11e7-907d-cbbf6eabf70c.png)

## Version Info 
SDK Version : 2.4.0
.NET Version :	4.7					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Windows Server 2016
Hosting Info (IIS/Azure WebApps/ etc) : Cloud Service (PaaS v1)

**Comment by cijothomas** [comment]
Closing old issue.
Even if no data is sent, all TI is still run.
