### ISSUE TITLE
Future request: Also support DocumentDb's TCP protocol connection mode.

### ISSUE THREAD

**Issue by takekazuomi** [microsoft/ApplicationInsights-dotnet#1609]
DocumentDbHttpParser supports only HTTP protocol. I usually use TCP of ConnectionPolicy.ConnectionProtocol.

Current develop branch's DocumentDbHttpParser is wonderful.
Thank you.

**Comment by NatMarchand** [comment]
Hello there,
Any news about this ?
Also, the recommended way of using cosmos with aspnetcore is by making the cosmosclient a singleton. However, it seems that this makes the correlation wrong.

**Comment by cijothomas** [comment]
@NatMarchand No update on this and no one from Application Insights team is working on this.
This feature, along with any other new collections will come via OpenTelemetry route in the future.
