### ISSUE TITLE
Time should be in UTC

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#162]
Time field of the envelope should be in UTC to be accepted by Vortex. It must be in the ISO 8601 UTC format, with a trailing ‘Z’ character. See https://en.wikipedia.org/wiki/ISO_8601#UTC  and for an example see 

Event date time. UTC time when the event was generated on the client. This should be in ISO 8601 format `2013-09-21T21:55:00.9839095Z`

**Comment by abaranch** [comment]
#177
