### ISSUE TITLE
HTTP Referer?

### ISSUE THREAD

**Issue by ohadschn** [microsoft/ApplicationInsights-dotnet#1623]
The HTTP `referer` (referrer) is one of the most interesting headers in analytics IMHO.
Google Analytics use it for their acquisition analysis, and they include it under names like "source" or "referral path".

I couldn't find any equivalent in Application Insights for my ASP.NET Azure Web App. Specifically, I couldn't find any graph/metric for it in the portal, and no corresponding field in the `requests` or `pageViews` Analytics records.

This [SO answer](https://stackoverflow.com/a/29614220/67824) by an MS employee given on April 2015 suggests the following explicit code: ` appInsights.trackPageView(null, null, {urlReferrer: document.referrer});`

Is this still the recommended solution? If so, I'm assuming one should [remove the `appInsights.trackPageView();` call in the default AI JS code snippet](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#trackpageview)?

**Comment by Cloudmersive** [comment]
Can't believe this is not built-in

**Comment by mairaw** [comment]
Is manually adding this still the solution? I wanted to get referral data for the dot.net website app insights.

**Comment by cijothomas** [comment]
No work has been done on this issue, and nothing is planned for this year.
So the exiting recommendation (i think it was to use manual initializers), still remains.

**Comment by No1sBothered** [comment]
This was removed from future milestones, does that mean it will no longer be a consideration?
