### ISSUE TITLE
StartOperation<DependencyTelemetry> does not specify dependency type

### ISSUE THREAD

**Issue by zakimaksyutov** [microsoft/ApplicationInsights-dotnet#1628]
As a result AI UX shows them as Other:

![image](https://user-images.githubusercontent.com/15914532/37582863-0e6c71de-2b0c-11e8-986d-126e2ae89057.png)

Expected - to require to fill a dependency type (note - it should be default option, not an override). Current method should be marked as Obsolete.

**Comment by ank3it** [comment]
@zakimaksyutov : Sorry, just cleaning up. Is this still valid? Does this still require attention.

**Comment by ruifrvaz** [comment]
Hi @ank3it I am currently trying to use StartOperation<DependencyTelemetry> on .net core 3.1 in a v3 azure function and i get the error:  Method not found: 'Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1<!!0> Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation(Microsoft.ApplicationInsights.TelemetryClient, System.Diagnostics.Activity)

I check the package and i see the method there, in assembly: Microsoft.ApplicationInsights, Version=2.17.0.146
the code compiles properly.

Any idea what is happening? From what i understand there is a broken reference somewhere.
Best regards

**Comment by zakimaksyutov** [comment]
@ank3it, unless the override was added and documentation updated I don't think why it wouldn't be still valid.
