### ISSUE TITLE
Allow to start operation with pre-defined root and parent ID

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#163]
`StartOperaiton` API doesn't support scenario when parent ID and root ID were received from different layer and we want to start operation with the existing parent and root ID.

Proposed change - allow `StartOperaition` to receive RequestTelemetry type as an argument

**Comment by pharring** [comment]
👍 to this, but also to allow passing the root ID as a raw value rather than as a ```RequestTelemetry```.

**Comment by SergeyKanzhelev** [comment]
Why only root ID? Any significance for it?

**Comment by pharring** [comment]
Sure, parent ID too, optionally.
i.e.
```C#
public static IOperationHolder<T> StartOperation<T>(this TelemetryClient telemetryClient, string operationName, string operationId = null, string operationParentId = null) where T : OperationTelemetry, new()
{
    ...
    if (!string.IsNullOrEmpty(operationId))
    {
        operation.Telemetry.Context.Operation.Id = operationId;
    }

    if (!string.IsNullOrEmpty(operationParentId))
    {
        operation.Telemetry.Context.Operation.ParentId = operationParentId;
    }

    operation.Telemetry.Start();

    ...

}
```

I'll try to get a PR out for this later tonight.
