### ISSUE TITLE
Correlation does not work within WCF service

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1631]
When WCF service makes async call to http/sql/other dependency, writes traces, or reports exceptions, child telemetries do not correlate to the request telemetry.

It happens because WCF prevents ambient correlation context to flow with the request.
WCF is working to improve this story in future.

# Workaround

Use WCF behavior extensions to restore the context. This [article](https://cgeers.wordpress.com/2011/05/10/wcf-message-logging/) provides examples on how to create and configure the extension.

```csharp
    public class ApplicationInsightsContextRestoreHelper : IDispatchMessageInspector, IServiceBehavior
    {
        public object AfterReceiveRequest(ref Message request, IClientChannel channel, InstanceContext instanceContext)
        {
            // WORKAROUND! TEST CAREFULLY!
           // see https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/941
            var formerActivity = (Activity)HttpContext.Current?.Items["__AspnetActivity__"];
            if (formerActivity != null)
            {
                var newActvity = new Activity(formerActivity.OperationName);
                newActvity.SetStartTime(formerActivity.StartTimeUtc);
                newActvity.SetParentId(formerActivity.ParentId ?? formerActivity.RootId);
                foreach (var baggage in formerActivity.Baggage)
                {
                    newActvity.AddBaggage(baggage.Key, baggage.Value);
                }

                foreach (var tag in formerActivity.Tags)
                {
                    newActvity.AddTag(tag.Key, tag.Value);
                }

                newActvity.Start();

                var requestTelemetry = (RequestTelemetry)HttpContext.Current?.Items["Microsoft.ApplicationInsights.RequestTelemetry"];
                if (requestTelemetry != null)
                {
                    requestTelemetry.Context.Operation.Id = newActvity.RootId;
                    requestTelemetry.Context.Operation.ParentId = newActvity.ParentId;
                    requestTelemetry.Id = newActvity.Id;
                }
            }
            return null;
        }

        public void AddBindingParameters(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase, Collection<ServiceEndpoint> endpoints,
            BindingParameterCollection bindingParameters)
        {
            foreach (ChannelDispatcher dispatcher in serviceHostBase.ChannelDispatchers)
            {
                foreach (var endpoint in dispatcher.Endpoints)
                {
                    endpoint.DispatchRuntime.MessageInspectors.Add(new ApplicationInsightsContextRestoreHelper());
                }
            }
        }
...
```

The workaround has a downside that telemetry reported by HttpModules/Handlers/Filters that happen in request execution pipeline BEFORE workaround will be correlated to telemetry reported in controller only by operation Id:
E.g trace1 was tracked in some HttpModule and trace2 was tracked in the WCF service.
Normally, Request telemetry becomes a parent to both traces (i.e. operation_Id match for traces and request, and request.Id match each trace operation_ParentId).

With the above workaround, operation_Ids would still match for all of them, however, trace1 operation_ParentId would NOT match request.Id, while trace2 parentId would match request Id.

**Comment by ank3it** [comment]
@mrbullwinkle : To create a seperate doc for this, to drive clarity

**Comment by peta** [comment]
Any news on this issue?

**Comment by cijothomas** [comment]
@peta Are you asking if there are plans in Application Insights to make correlation work automatically for WCF services? 
There are no investments planned in Application Insights for WCF area in next 6 months.

**Comment by joymon** [comment]
Any news about AppInsights for WCF as 6 months is over?

**Comment by cijothomas** [comment]
None. Its likely to come via OpenTelemetry route. (OpenTelemetry WCF instrumentation+AzureMonitor exporter, which dont have feature parity with current ApplicationInsights. Don't have an ETA on when or whether it'll have same feature parity as this SDK.)
