### ISSUE TITLE
CPU leak infinite loop DependencyCollector

### ISSUE THREAD

**Issue by Svisstack** [microsoft/ApplicationInsights-dotnet#1632]
## Repro Steps
1.  Create a task with SQL code which ending after the request is finished
2.  Occasionally thread stuck in an infinite loop
3.  Repeat

More discussion and analysis: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/690#issuecomment-420324593

##  Actual Behavior
Occasionally thread stuck in an infinite loop

![1](https://user-images.githubusercontent.com/864295/45377205-33c80c80-b5fa-11e8-9547-eada0c3cf7ba.PNG)

## Expected Behavior
No threads with infinite loops

## Version Info 
Lib version: Microsoft.ApplicationInsights.AspNetCore 2.4.1
.NET Version :	4.7.1 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : VisualStudio
Hosting Info (IIS/Azure WebApps/ etc) : Kestrel

**Comment by OlegoO** [comment]
We updated 
Microsoft.ApplicationInsights.AspNetCore 
Microsoft.ApplicationInsights.PerfCounterCollector |  

from 2.13.1 -> 2.15.0 and now see this picture:
![image](https://user-images.githubusercontent.com/7639413/97575417-5ba2a600-19f5-11eb-94d8-3e983a19f66e.png)

If I download dump, I saw

**109 threads for**
GCFrame
HelperMethodFrame_1OBJ
System.Threading.ManualResetEventSlim.Wait
System.Threading.Tasks.Task.SpinThenBlockingWait
System.Threading.Tasks.Task.InternalWaitCore
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.QuickPulse.QuickPulseServiceClient.SendRequest
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.QuickPulse.QuickPulseServiceClient.Ping
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.QuickPulse.QuickPulseCollectionStateManager.UpdateState
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.StateThreadWorker

**110 threads for**
GCFrame
HelperMethodFrame_1OBJ
System.Threading.ManualResetEventSlim.Wait
System.Threading.Tasks.Task.SpinThenBlockingWait
System.Threading.Tasks.Task.InternalWaitCore
Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.StateThreadWorker
System.Threading.ExecutionContext.RunInternal

We revert back to 2.13.1
