### ISSUE TITLE
Not possible to use public types in Common (shared classes) outside of Web SDK

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#1633]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
Try to use StringUtilities in AspNetCore SDK

##  Actual Behavior
StringUtilities is defined in PerformanceCollector, DependencyCollector, and WindowsServer.
So build fails not being able to resolve type.

Typical way to work it around is to add alias on the assembly and use `extern alias` it in the code to force specific assembly usage.
However it does not work well with nuget packages (https://github.com/NuGet/Home/issues/4989) and [broken with VS2017/fresh msbuild](https://developercommunity.visualstudio.com/content/problem/100351/c-extern-alias-reference-not-working-in-vs2017.html)

So my suggestions are
- never declare public types in common shared items
- move common stuff to base SDK  whenever possible

**Comment by TimothyMothra** [comment]
Just posting an update. 
This continues to be an annoyance. I spoke to Sergey a couple of months ago and we agreed that common helper methods could be added to the base SDK. 

I'm going to close this issue because Liudmila's suggestions have become our best practices.
