### ISSUE TITLE
Question: How to configure telemetry initializer properties in ASP.NET Core app

### ISSUE THREAD

**Issue by ralphhendriks** [microsoft/ApplicationInsights-dotnet#1636]
**Context**
Our app is deployed behind a reverse proxy, and I would like to configure a nonstandard header for retrieving the client IP address from. It is the responsibility of the `ClientIpHeaderTelemetryInitializer` to set the correct client IP address. It has public properties `HeaderNames`, `HeaderValueSeparators`, and `UseFirstIp` that modify its behavior. I think that setting these to the correct values will serve my needs.

**Question**
How do you configure the default added instance of `ClientIpHeaderTelemetryInitializer` in an ASP.NET Core app?

I add Application Insights as per documentation in the `Startup` class by
```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddApplicationInsightsTelemetry();
    // ...
}
```

`.AddApplicationInsightsTelemetry()` adds a number of `ITelemetryInitializer` implementations to the services collection, among which the `ClientIpHeaderTelemetryInitializer`. I did not find the way to set its properties from code anywhere in the docs.

I think the key to the solution must one of the following:
1. After the call to `.AddApplicationInsightsTelemetry()`, retrieve the added instance of `ClientIpHeaderTelemetryInitializer` from the services collection and alter its properties. (What is the proper way to do this?)

2. After the call to `.AddApplicationInsightsTelemetry()`, remove the added `ClientIpHeaderTelemetryInitializer` as per [these instructions](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#removing-telemetryinitializers) and add a fresh instance with the properties set to my needs.

3. Before or after the call to `.AddApplicationInsightsTelemetry()` add another instance of `ClientIpHeaderTelemetryInitializer` with the properties set to my need. I have no idea yet of how these instances might influence each other. I don't think this is a very deterministic way of achieving the desired behavior in the first place.

What is the proper way to do this? All my attempts so far lead to a rather hacky path. Am I missing some parts, or is the API currently lacking the extension points to change the configuration elegantly from code?

The docs might benefit from a hint on how to configure default telemetry initializer in general. I would be willing to contribute once it is clear on how to do this.

**Comment by Dmitry-Matveev** [comment]
I think we leverage `AddSignleton<>`, but not `TryAddSingleton<>`, so trying to register configured initializer beforehand won't work - default one will override yours in DI.

However, retrieving initializer from service collection and modifying its properties is the way to go with the current implementation of in-code configuration in AI ASP.NET Core SDK.

@cijothomas may have some other suggestions when he is back from the break.

Re: documentation: We can close this issue and then open doc issue to publish the right set of steps to configure default Telemetry Initializer. You can open one in this repo or directly on Docs GitHub (Feedback option in the bottom of [doc page](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#removing-telemetryinitializers)).

**Comment by ralphhendriks** [comment]
@Dmitry-Matveev thank you for your answer. I will raise a separate issue on the doc page.

I decided to go with the option to remove the instance of `ClientIpHeaderTelemetryInitializer` that is added by `.AddApplicationInsightsTelemetry()` and then add a fresh instance with my own custom configuration. IMHO this is more explicit and resilient for future changes of the Application Insights SDK implementation (e.g. no longer add the initializer, or switch to lazy/factory-based construction).

This is the code I ended up with:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddApplicationInsightsTelemetry();

    var tiToRemove = services.SingleOrDefault(
        t => t.ImplementationType == typeof(ClientIpHeaderTelemetryInitializer));
    if (tiToRemove != null)
    {
        services.Remove(tiToRemove);
    }
    services.AddSingleton<ITelemetryInitializer>(sp =>
    {
        var contextAccessor = sp.GetRequiredService<IHttpContextAccessor>();
        var ti = new ClientIpHeaderTelemetryInitializer(contextAccessor);
        ti.HeaderNames.Clear();
        ti.HeaderNames.Add("X-Original-Forwarded-For");
        ti.HeaderNames.Add("X-Forwarded-For");
        return ti;
    });
}
```

Note that I changed the part to remove the added service to use `.SingleOrDefault` instead of `.FirstOrDefault`. I want my composition root to throw an exception in the situation that there is more than one instance registered.
