### ISSUE TITLE
ServerTelemetryChannel does not respect what is passed via ApplicationInsights.config

### ISSUE THREAD

**Issue by cleberdantas** [microsoft/ApplicationInsights-dotnet#1637]
```
<TelemetryChannel Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel, Microsoft.AI.ServerTelemetryChannel">
           <EndpointAddress>http://myendpoint/v2/track</EndpointAddress>
</TelemetryChannel>
```
Hi,
It seems like when we set via configuration file (ApplicationInsights.config) the `EndpointAddress` element that this is ignored by `ServerTelemetryChannel` class.

Bellow we can see that when the `Initialize` method is called the property is set with the value inside of `configuration.EndpointContainer.Ingestion`  which is not the same source when loaded via configuration file:

https://github.com/microsoft/ApplicationInsights-dotnet/blob/a26a43f012ef6afca563b43b16ab019698a3f062/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs#L326

https://github.com/microsoft/ApplicationInsights-dotnet/blob/a26a43f012ef6afca563b43b16ab019698a3f062/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs#L118-L122

Is my understanding correct? Is it a problem? Is there a way fix it?

**Comment by Dmitry-Matveev** [comment]
@TimothyMothra can you please look into that?

**Comment by TimothyMothra** [comment]
This looks like a bug. 

This change was introduced in 2.12 when I added support for connection strings.
I added unit tests for as many ways to configure the SDK as I could imagine, but clearly I missed something.

I'm adding this to the top of my todo list, but please give me a couple of days to look at it.
We have some customers already using connection string without issue, so I'll need some time to sit with this and review why I made this change.


2.11
https://github.com/microsoft/ApplicationInsights-dotnet/blob/de4e53d3f0f3166a5b1e6724e56706a053d221ab/src/ServerTelemetryChannel/ServerTelemetryChannel.cs#L303-L312

2.12
https://github.com/microsoft/ApplicationInsights-dotnet/blob/b7cc9ff95e3f5f66ebf098a6e0cad54df16b685d/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs#L317-L333



### Workaround
@cleberdantas I'm sorry for the trouble. 
Thank you for opening an issue.
As a workaround, can you downgrade to 2.11 ?

**Comment by cleberdantas** [comment]
Hi, @TimothyMothra!

Thanks for the quick reply. 

As a "workaround" I've just moved the `EndpointAddress` configuration into a web.config/app.config file and configured this via code with `TelemetryConfiguration.Active.TelemetryChannel.EndpointAddress`, it worked just fine.

Since the ApplicationInsights.config is the default option and it is the way that the docs states how to configure it, I thought it was a good idea the raise the issue.

Cleber

**Comment by TimothyMothra** [comment]
@cleberdantas we're releasing 2.12.1 today that contains the fix for this.
It should be available on NuGet within an hour!

2.13-beta2 should get released later this week, also with this fix.

Thanks again for reporting this issue!
