### ISSUE TITLE
Worker Service Application vs AspNetCore Application when using Serilog to write ApplicationInsights has to be configured differently

### ISSUE THREAD

**Issue by ZeinSleiman** [microsoft/ApplicationInsights-dotnet#1645]
My apologies if this is not an actual bug or an issue. I am trying to use Serilog to write exceptions to Application Insights, however the behavior is different from AspnetCore application. 

### ASPNETCORE
```
When building a web app, the instrumentation key is being populated from the config under application insights and serilog successfully writes to AppInsights

  "ApplicationInsights": {
    "InstrumentationKey": "xxx-xxx-xx-xxx"
  }
```

### Worker Services
```
When building a worker app, the instrumentation key is not populated from the config unless it is specified under the Args section
"WriteTo": [
      {
        "Name": "ApplicationInsights",
        "Args": {
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
        }
      }
    ]
  },
  "ApplicationInsights": {
    "InstrumentationKey": "xxx-xxx-xx-xxx"
  }
```

## Repro Steps
1. Create a new WorkerService app using dotnet new worker
2. Added all these packages:
<PackageReference Include="Serilog" Version="2.9.0" />
 <PackageReference Include="Serilog.Extensions.Hosting" Version="3.0.0" />
 <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
 <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="3.0.4" />

3. Code in the Worker class
```
 var random = new Random();
            while (!stoppingToken.IsCancellationRequested)
            {
                try
                {
                    if(random.Next(2,10) % 2 == 0) {
                        throw new Exception("Locally generated");
                    }
                    _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                    await Task.Delay(1000, stoppingToken);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Logging locally");
                }
            }
```

4.Code in the program.cs
```
 public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog((ctx, config) => config.ReadFrom.Configuration(ctx.Configuration))
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                });
```

##  Actual Behavior
Application Insights Telemetry (unconfigured):

## Expected Behavior
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.xxx-xxx-xx-xxx

## Version Info 
SDK Version :  3.1.1
.NET Version :	3.0					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : 
OS : Windows
Hosting Info (IIS/Azure WebApps/ etc) : running locally using dotnet run 

I am reporting this here since the only difference I found in the code was in this class
TelemetryConfigurationOptions.cs
But I am not sure if this is on Serilog Sink Library. Is there a way to configure the worker service same as application insights?

**Comment by ZeinSleiman** [comment]
I would love to know if this is an issue, not an issue, any workaround. I appreciate any feedback.

**Comment by cijothomas** [comment]
This is best asked in Serilog repo. 
Getting logs in Worker service is documented here: 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service

**Comment by ZeinSleiman** [comment]
Thanks for your reply. I ended posting it on the Serilog repo but I havent heard back from anyone there. I did read the document you shared and it didnt help in explaining the problem.
