### ISSUE TITLE
SDK Diagnostics Mode, emit ETW logs without redeploying an application.

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1653]
This is a continuation of #1059 

We want to introduce a **DiagnosticsMode** into the SDK.
This would be controlled by an environment variable.
A customer could set this instead of redeploying an application, although this would require restarting an application.

### First Version (2.13 milestone)
- Diagnostic Mode would enable the `FileDiagnosticTelemetryModule` to collect ETW logs emitted by the Application Insights SDK.
- The application would need to be restarted for this change to take effect.

### Future suggested features
- To enable without restarting an app.
- To allow the SDK to throw internal exceptions.
- Set the verbosity level of logs to collect.
- Possibly include this the config file to control this on a per-application level. Possibly simpler than manually configuring modules themselves. (Scenario-based config values)

### Technical Spec

Naming is up for debate. Suggestions are "Diagnostic(s)", "DiagnosticMode", "SelfDiagnostics"

- Environment Variable: `APPLICATIONINSIGHTS_DIAGNOSTICS`
    - DataType: String
    - Value: `true/enabled` to turn on. `false/disabled` or delete the variable to turn off. Provides flexibility for new keywords in the future.
    - If not set, SDK default is `false`.
- Environment Variable: `APPLICATIONINSIGHTS_DIAGNOSTICS_LOG_DIRECTORY`
    - DataType: String
    - Value: full path of the directory where the log files would be stored. 
    - If not set, SDK default is `%TEMP%`.

### How to enable

- Windows Command Line: `set APPLICATIONINSIGHTS_DIAGNOSTICS=true`
- PowerShell: `$env:APPLICATIONINSIGHTS_DIAGNOSTICS = 'true'`

**Comment by TimothyMothra** [comment]
@reyang - please review.

@trask, @littleaj - Can you please provide feedback? 
My goal is that this should be generic enough to be implemented by other SDKs so we can have a consistent supportability story. I would love to get your opinions/perspectives.

**Comment by reyang** [comment]
Adding @maxgolov who has similar requirements for our C++ SDKs.

Is there a reason that we prefer the SDK to collect ETW logs generated by itself and pipe it to a file?
Have we considered providing a separate tool which interacts with SDK internal ETW logs?

**Comment by reyang** [comment]
What is the expected behavior if the environment variable is set to something else (e.g. "foo")?

**Comment by TimothyMothra** [comment]
@reyang we already have separate tools that can collect ETW logs. PerfView and StatusMonitor. 
But we have customers who can't install exe or scripts on their production machines (including Azure).
So the intention is for the SDK to collect it's own logs. This is something we've had several customers ask for. :)

If the environment variable is set to an unsupported value, we would revert to the default value.

**Comment by reyang** [comment]
@TimothyMothra I see, thanks.

**Comment by reyang** [comment]
Is `APPLICATIONINSIGHTS_DIAGNOSTICS_LOG_DIRECTORY` a path for a file or folder? What would the file name be? What is the scope of a file (do we use the same file for all the processes/apps?). Do we support non-ASCII path?

**Comment by TimothyMothra** [comment]
@reyang I want to only expose the directory as a variable.

https://github.com/microsoft/ApplicationInsights-dotnet/blob/2bc5654201f001303991ab88e5af9f730fadf772/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/SelfDiagnostics/FileDiagnosticsTelemetryModule.cs#L29-L38

Although the module can be customized with a file name, in my opinion, this doesn't add enough value to justify an extra variable.
In addition to this change, I want to change the default file name to include the UTC date.

**Comment by TimothyMothra** [comment]
Regarding non-ASCII paths, we don't do anything to prevent this.
We do have a validate method which checks for a dozen different possible Exceptions. 
https://github.com/microsoft/ApplicationInsights-dotnet/blob/2bc5654201f001303991ab88e5af9f730fadf772/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/SelfDiagnostics/FileDiagnosticsTelemetryModule.cs#L159

**Comment by reyang** [comment]
> @reyang I want to only expose the directory as a variable.

Agree, in this way I suggest that we update the description from `Value: file path` to `Value: full path of the directory where the log files would be stored`.

**Comment by TimothyMothra** [comment]
I'm postponing this work a few more weeks to better align with the other SDKs.

**Comment by maxgolov** [comment]
@TimothyMothra - I like your implementation. There's a similar implementation in our 1DS C++ SDK, I think we should discuss and normalize on ETW GUID, tooling, file vs system log, and possibly on how we can route the critical failure logs to [Diag Track](https://support.microsoft.com/en-us/help/3080149/update-for-customer-experience-and-diagnostic-telemetry) when running on Windows 10.

**Comment by TimothyMothra** [comment]
@maxgolov I'm VERY interested in the C++ SDK implementation. Lets please discuss offline.

I don't think .NET can change our ETW guids as that would be a breaking change.
For the .NET SDK i have all of those documented here: https://github.com/microsoft/ApplicationInsights-Home/tree/master/Samples/ETW

I'd like to hear your thoughts about tooling. The .NET SDK already supports several tools (see document), but I'm not familiar with Diag Track.

This specific issue is meant to provide a tool-less method for extracting logs. We have several customers (including azure) needing to get logs but can't run additional tools or exes in production and this is impacting our supportability.

**Comment by TimothyMothra** [comment]
I'm abandoning this issue. I will recreate an issue when we finish the spec.
