### ISSUE TITLE
How can I use with .NET Core 3.1 WPF ?

### ISSUE THREAD

**Issue by fatihyildizhan** [microsoft/ApplicationInsights-dotnet#1654]
Is there a chance to totally init on a .NET Standard 2.1 Class Library and call from other projects?

I am using MVVM and tried this on OnStartup and on MainViewModel but didn't work for me. What am I missing?

```
TelemetryConfiguration configuration = TelemetryConfiguration.CreateDefault();
configuration.InstrumentationKey = " *your key* ";
var telemetryClient = new TelemetryClient(configuration);
telemetryClient.TrackTrace("Hello World!");
```

**Comment by pharring** [comment]
Works for me. For client applications, make sure you call `telemetryClient.Flush()` at shutdown, otherwise you'll drop events.

**Comment by fatihyildizhan** [comment]
@pharring Thank you. I am now getting events. Is there a way to see Live Metrics Stream too, Should I track manually?

**Comment by pharring** [comment]
Yes.
First add the Microsoft.ApplicationInsights.PerfCounterCollector nuget package to your app.
Then, see
https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream#classic-aspnet

Note that you can't use ApplicationInsights.config to configure a .NET Core app. You have to use the code snippet.

(If your WPF APP is sophisticated enough to also use Microsoft.Extensions.DependencyInjection, then you can probably act like an ASP.NET Core app and use the one-liner ASP.NET Core approach lower down in that article. I haven't tried it myself.)

**Comment by fatihyildizhan** [comment]
Thank you so much.

**Comment by cijothomas** [comment]
@fatihyildizhan https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#net-corenet-framework-console-application Follow this doc if you want everything setup easily with a one liner. The doc is targetting console/non-http apps, but can be used in WPF as well if desired.
