### ISSUE TITLE
Questions on Restsharp dependency tracking

### ISSUE THREAD

**Issue by biltongza** [microsoft/ApplicationInsights-dotnet#1662]
I know that dependency tracking is enabled automatically for `HttpClient`, I was wondering if there was a way for me to implement this same dependency tracking for RestSharp? Do I just need to use telemetry client to track the request? Also, how do I get my downstream dependencies to use the parent operation ID from my incoming web requests?

**Comment by biltongza** [comment]
I have made some progress on this, I have this call which I use on every restsharp request:
```
private void AddAppInsightsTracking(HttpRequestMessage request)
        {
            var activity = System.Diagnostics.Activity.Current;
            request.Headers.Add(W3CConstants.TraceParentHeader, activity.Id);
            var traceState = activity.TraceStateString;
            if (traceState != null)
            {
                request.Headers.Add(W3CConstants.TraceStateHeader, traceState);
            }
        }
```
This is now successfully correlating between our frontend API and our backend services, however it seems that app insights is not correlating the dependency telemetry from our frontend SPA to the frontend API. 

The `traceparent` header is present on my requests from the SPA, so I had assumed that the frontend API app insights would be smart enough to use that `traceparent` header to set the parent Id on `Activity.Current` but it appears `Activity.Current.Id` and `Activity.Current.ParentId` are always the same. Am I missing something?

**Comment by wilkovanderveen** [comment]
Anyone able to fix this one? Would this work for the HttpClient itself?

**Comment by wilkovanderveen** [comment]
Can someone confirm that _dependency tracking_ does work for _appication insights_ in combination with _RestSharp_?
