### ISSUE TITLE
Question on dependency tracking telemetry support for gRPC in dot net core 3

### ISSUE THREAD

**Issue by fergus3000** [microsoft/ApplicationInsights-dotnet#1663]
I have been reading that dot net core 3 has more closely integrated support for gRPC with [grpc-dotnet](https://github.com/grpc/grpc-dotnet) . Since this new gRPC package uses the existing networking primitives in the .NET Core BCL, will App Insights support dependency tracking out of the box? (in the same way it does for http rest implementations).

I have a service fabric microservices app that uses grpc, where I have tried myself to implement AI dependency tracking for the Grpc.Core package using gRPC interceptors. But there are some issues with the app insights dependency diagram not getting the layout right. Typically tracking internal calls between microservices as external dependency calls.

So I could throw more time into trying to fix my homebrew grpc dependency tracker, or I could instead investigate going over to grpc-dotnet and maybe solve dependency tracking for free :) 

I checked this [msdocs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies) on automatically tracked dependencies tracking but see that grpc is still not listed, but the doc hasnt been updated since last june.

**Comment by lmolkova** [comment]
@fergus3000
unfortunately ApplicationInsights does not track grpc specific information yet (method and status code). However grpc calls are done using HttpClient and you'd get some info with basic HTTP tracing out of the box.

There is a doc PR in progress https://github.com/aspnet/AspNetCore.Docs/pull/16512 that has a bit more info on this.

**Comment by cijothomas** [comment]
Closing in favor of https://github.com/microsoft/ApplicationInsights-dotnet/issues/1669
