### ISSUE TITLE
Logs from WebHost.Run are not written to ApplicationInsights when configuring AddApplicationInsightsTelemetry in ConfigureServices

### ISSUE THREAD

**Issue by arabelaa** [microsoft/ApplicationInsights-dotnet#1667]
### Describe the bug
I want to log exceptions that occur when running the webhost. See below the code I used in Program.cs.
The strange part I noticed is that when adding  `           services.AddApplicationInsightsTelemetry();
` in `ConfigureServices` the logs are not pushed to AI. If I remove the registration it works perfectly fine. I did the exact steps with a sample  ASP.NET Core and the same behavior. 

### To Reproduce
``` C#
 
var host = CreateWebHostBuilder(args).Build();
            var logger = host.Services.GetService<ILogger<Program>>();
            try
            {
                host.Run();
            }
            catch (Exception exception)
            {
                logger.LogCritical(exception, "Host running error");
                //wait for logger
                Task.Delay(TimeSpan.FromSeconds(60)).GetAwaiter().GetResult();
                throw;
            }

public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureLogging((context, builder) =>
                    {
                        builder.AddApplicationInsights(
                            context.Configuration.GetValue<string>(
                                "ApplicationInsights:InstrumentationKey"));
                    }
                );
     }
```

### Further technical details
- ASP.NET Core version 2.2
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\
- The IDE (VS) you're running on, and it's version
 VS 2019

**Comment by Dmitry-Matveev** [comment]
@arabelaa , can you please try using the most recent version of AI SDK? Previous versions had some issues running on .NET Core 3.0.

There is a section in our documentation on how to [migrate from older ILogger implementation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#migrate-from-the-old-applicationinsightsloggerprovider) and a [section about logging from `Program.cs` / `Startup.cs`](https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#capture-ilogger-logs-from-startupcs-and-programcs-in-aspnet-core-apps) (however, that one may not be needed if the log happens after AI is initialized)
