### ISSUE TITLE
Track outgoing gRPC request information

### ISSUE THREAD

**Issue by JamesNK** [microsoft/ApplicationInsights-dotnet#1669]
Outgoing request details:

> ### gRPC client tracing
> 
> The .NET gRPC client uses `HttpClient` to make gRPC calls. Although `HttpClient` writes diagnostic events, the .NET gRPC client provides a custom diagnostic source, activity and events so that complete information about a gRPC call can be collected.
> 
> * Diagnostic source name is `Grpc.Net.Client`.
> * Activity name is `Grpc.Net.Client.GrpcOut`.
>   * Name of the gRPC method invoked by the gRPC call is added as a tag with the name `grpc.method`.
>   * Status code of the gRPC call when it is complete is added as a tag with the name `grpc.status_code`.

https://github.com/aspnet/AspNetCore.Docs/pull/16512

Consider merging the gRPC request with the HttpClient request metrics. HttpClient request will always report a HTTP status code of 200. gRPC request `grpc.status_code` is what is used to track the result of the call.

cc @shirhatti

**Comment by shirhatti** [comment]
We still want this and we haven't forgotten about it 😄

**Comment by cijothomas** [comment]
> We still want this and we haven't forgotten about it 😄

we'll get it via Otel instrumentation + AzMon exporter :D
