### ISSUE TITLE
Issues with kb 2468871

### ISSUE THREAD

**Issue by dbohls** [Microsoft/ApplicationInsights-dotnet#167]
Given that App Insights requires kb 2468871 when using .NET 4.0, we'd like to distribute an internet installer for kb 2468871 with our installer. This issue isn't with App Insights per say, but rather with our ability to deploy apps containing App Insights successfully. I've been looking online for answers to these questions:

1) Does an internet installer for kb 2468871 exist? I see installers at https://support.microsoft.com/en-us/kb/2468871 but we'd need an internet installer due to size limitations.
2) Is it okay to distribute said installers?

I apologize if this is not the correct forum for getting assistance with these issues.

**Comment by SergeyKanzhelev** [comment]
@JoshuaWeber do you have any ideas for @dbohls? 

@dbohls - do you use persistence telemetry channel or in-memory channel?

**Comment by dbohls** [comment]
Hi Sergey,

We will probably end up using the persistence channel since our app would often be used in situations without connectivity, though I'm unhappy that we'd never get telemetry on people who run our app once and never again. I've been wanting to explore some options like testing for connectivity on app start and then only using the in-memory channel if there is no connectivity (obviously banking on the assumption that they would continue to have connectivity at app close).

As for the issue with KB2468871, I think we've decided to have our installer install .NET 4.0 on Windows XP and .NET 4.5 on Windows Vista and later, since .NET 4.5 includes KB2468871. It would simply things for us if we didn't have to worry about XP.

**Comment by dbohls** [comment]
Excuse me, I mean only use the in-memory channel if they DO have connectivity.

**Comment by SergeyKanzhelev** [comment]
installing of 4.5 is totally makes sense.
