### ISSUE TITLE
Could not load file or assembly System.Memory

### ISSUE THREAD

**Issue by jamers99** [microsoft/ApplicationInsights-dotnet#1672]
We are experiencing a FileLoadException in one of our unit test projects when calling TelemetryClient.StartOperation.  It was working in other unit test projects, so we decided to narrow it down. We chopped away all our code to the point of a new blank unit test project and we could still reproduce the issue.

## Repro Steps
1. Run the test in this stripped down, simple project we reproduced the issue with:
[FileNotFoundRepro.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/4170959/FileNotFoundRepro.zip)
#### Or create the project manually
1. Create a .NET Framework MSTest Project (4.7.2, RestoreProjectStyle - PackageReference)
2. Update all NuGet packages (MSTest at 2.1.0)
3. Install Microsoft.ApplicationInsights.WindowsServer (2.12.1)
4. In the default test method, create a new TelemetryClient variable
5. Call TelemetryClient.StartOperation<RequestTelemetry>("test") on that variable
6. Run the test

##  Actual Behavior
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Microsoft.ApplicationInsights
  StackTrace:
   at Microsoft.ApplicationInsights.TelemetryClientExtensions.<>c__DisplayClass3_0`1.<StartOperation>b__0()
   at Microsoft.ApplicationInsights.ActivityExtensions.TryRun(Action action)
   at Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation[T](TelemetryClient telemetryClient, T operationTelemetry)
   at Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation[T](TelemetryClient telemetryClient, String operationName, String operationId, String parentOperationId)
   at Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation[T](TelemetryClient telemetryClient, String operationName)
   at UnitTestProject1.UnitTest1.TestMethod1() in C:\Shared\Temporary\FNF-Repro\UnitTestProject1\ConsoleApp1\UnitTestProject1\UnitTest1.cs:line 14

## Expected Behavior
No exception, the test should pass.
Note that this won't actually report anywhere, but that doesn't make a difference.

## Version Info 
SDK Version : 2.12.1
.NET Version : 4.7.2 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VS
OS : Windows 10 Pro
Hosting Info (IIS/Azure WebApps/ etc) : N/A

**Comment by lmolkova** [comment]
your project missing binding redirect configuration. Unfortunately they are not generated for class libraries in packagereference format. check out this msbuild issue https://github.com/microsoft/msbuild/issues/1310.

You can add app.config with binding redirects similar to 
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

OR

add following options to your project file

```xml
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```

More on [binding redirect](https://netlify.nickcraver.com/blog/2020/02/06/binding-redirects/)

**Comment by petervandivier** [comment]
> More on [binding redirect](https://netlify.nickcraver.com/blog/2020/02/06/binding-redirects/)

n.b. this link is dead without redirect and not indexed on the wayback machine. The live link for this blog is currently https://nickcraver.com/blog/2020/02/11/binding-redirects/
