### ISSUE TITLE
Log4netAppender depends on log4net 2.0.7 on targets that are not .netstandard1.3

### ISSUE THREAD

**Issue by jorisvergeer** [microsoft/ApplicationInsights-dotnet#1675]
During some code cleanup I entoutered an issue with an assemblybinding

After some looking into the code of Log4Net appender I encountered this curious piece of code in the csproj file.

```
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.3' ">
    <PackageReference Include="log4net" Version="2.0.8" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' != 'netstandard1.3' ">
    <PackageReference Include="log4net" Version="2.0.7" />
  </ItemGroup>
````

What is special about netstandard1.3 that only this target deserves 2.0.8?

## Repro Steps
1. Just add reference to Log4NetAppender

##  Actual Behavior
It depends on log4net 2.0.7

## Expected Behavior
It depends on log4net 2.0.8

**Comment by TimothyMothra** [comment]
We regularly find things that aren't supported in netstandard1.x
That's the intent here, but i would have expected this to be the other way around. Usually it's the older version that supports the older framework.
Maybe this was a typo.

Thanks for calling attention to this. I'll take a look at it today
