### ISSUE TITLE
Operation ID mismatch causes correlation issues

### ISSUE THREAD

**Issue by DJ4ddi** [microsoft/ApplicationInsights-dotnet#1676]
I have stumbled upon an issue with some custom components which I cannot correctly correlate across different resources. This is because the root operation IDs are not propagated between components.

## Repro Steps
1. Start a request in any web component.
2. Attempt to correlate the request in any non-web component sending data to a different Application Insights resource.

##  Actual Behavior
The operation ID transmitted to the second component is correct, but is then replaced by a newly generated ID upon starting the request.

After some digging through the source code, I found the cause for this: The default ID generated for an operation is a span ID with 8 byte (see [OperationTelemetry, line 112](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/OperationTelemetry.cs#L112) and [W3CUtilities, line 49](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Extensibility/W3C/W3CUtilities.cs#L49)). However, when an operation is started, the ID is validated as trace with 16 byte (see [TelemetryClientExtensions, line 61](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/TelemetryClientExtensions.cs#L61) and [W3CUtilities, line 38](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Extensibility/W3C/W3CUtilities.cs#L38)). This fails for obvious reasons and the ID is then regenerated without any warning.

The old ID is stored in the legacy ID property, but ignored by all following operations.

## Expected Behavior
Essentially, the behavior described in [this article](https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking#overview) should actually work.
I expect the SDK to not silently regenerate an operation ID that I need to properly group the requests into one transaction. The ID check should not fail to begin with, since it was generated as part of the same pipeline. But if it does fail, there should be a warning logged (instead of quietly breaking things).

## Version Info 
SDK Version : 2.12.1
.NET Version : 4.7.2
How Application was onboarded with SDK : Visual Studio
OS : Windows 10 locally and OS family 6 on Azure
Hosting Info (IIS/Azure WebApps/ etc) : Tested locally using IIS Express and deployed as an Azure AppService combined with an Azure Cloud Service

**Comment by TimothyMothra** [comment]
@lmolkova do you have time to review this?

**Comment by lmolkova** [comment]
We are adopting [W3C Trace-Context standard](https://www.w3.org/TR/trace-context/) and it no longer permits having arbitrary correlation id formats. 

ApplicationInsights SDK makes best effort to keep Ids if they are compatible and if it fails, then it keeps old one in `ai_legacyRootId` custom property. You can consider it as a warning that your id is not compatible. UX (app-map and transaction viewer) also uses this property to correlate telemetry.
Did you have this problem with custom Kusto queries?

If we'll generate a warning about it - how you would want to be notified? Via ApplicationInsights telemetry item like a trace with internal error? Do you want to get notified for every occurrence of this problem? (we do not have mechanism to  NOT charge for this, so unfortunately such warnings could only increase the bill and we'd want to avoid them).
Or do you want to get some warning in debug experience? Would you notice it there?

It sounds like we have a documentation issues:
- we should document that we do not really support arbitrary format for correlation ids
- describe behavior with legacy field population
- provide query example to use legacy field.

I wish we could find a way to communicate something in this case, but I do not see a reasonable way  to do it.

**Comment by DJ4ddi** [comment]
The problem with the standard isn't that I want arbitrary ids, it's the fact that it is inconsistent within the Application Insights SDK. My first component uses the ApplicationInsights.Web package, which automatically assigns an 8 byte id (span id) to the operation. My second component uses ApplicationInsights.WindowsServer and discards that id because it expects a 16 byte id (trace id).

If trace ids are the way you want it to be, that's perfectly fine, but then the first component in the pipeline (Web SDK in my case) should not allow using a shorter one and definitely not generate one itself.

Regarding documentation and reporting: As described above, I did notice the legacy id property. However, I did not consider that a warning (it only made sense after reading the code). Also, it did **not** enable correlating operations across different resources (at least not in the transaction viewer).
A trace warning would perhaps be the most intuitive way, since I've seen several of those before. I do understand that this would be billable and therefore something you wish to avoid. Other options may lack visibility, although anything that stands out during local debugging will certainly be noticed.

**Comment by lmolkova** [comment]
Can you elaborate on 

> My first component uses the ApplicationInsights.Web package, which automatically assigns an 8 byte id (span id) to the operation. My second component uses ApplicationInsights.WindowsServer and discards that id because it expects a 16 byte id (trace id).

Can you explain your apps including versions of AI SDK and which protocol they used to communicate between each other? If you manually propagate ids from queue, can you share how you do it with some code snippets?

**Comment by DJ4ddi** [comment]
### Structure
Component A is an Azure App Service running _Microsoft.ApplicationInsights.Web_, v2.12.1; It receives requests via a WCF SOAP API from mobile clients.
From there, a message is passed through a one-directional Azure Service Bus using _WindowsAzure.ServiceBus_. Because this library does not support automatic context propagation (unlike the newer variant of it), we append the current operation (root) and request id (parent) to enable correlation.
The receiving component B is a Cloud Service running _Microsoft.ApplicationInsights.WindowsServer_, v2.12.1. It reads the messages from the bus and creates a `RequestTelemetry` item with the operation and parent id attached to the message.

### Target state
The ultimate goal is to use different instrumentation keys and Application Insights resources for A and B, but still enable viewing both within one transaction viewer. As per [this documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation), this should be achievable by simply using the same operation id.

### What works
The custom queue instrumentation does its job. Operation and request id are correctly read from the local context and attached as properties to the message (component A):
```
var serviceBusTelemetry = new DependencyTelemetry
{
  Target = this.queueHost, // URL of the queue for transaction viewer display
  Name = "ServiceBus." + queueName,
  Type = "Azure Service Bus",
  Timestamp = DateTime.Now,
};

// Manually set these now because the dependency may run later than the request
// Request is sourced from OperationContext.Current
serviceBusTelemetry.Context.Operation.Id = request.Context.Operation:Id;
serviceBusTelemetry.Context.Operation.ParentId = request.Id;

// These are both span ids with 8 byte / 16 chars
msg.Properties["OperationId"] = request.Context.Operation:Id;
msg.Properties["RequestId"] = serviceBusTelemetry.Id;

/* Do queue work asynchronously and update dependency status */

// We do not use client.StartOperation because of the delayed execution
this.telemetryClient.TrackDependency(serviceBusTelemetry);
```
With this code, the dependency is tracked correctly, even though it does not always run on the request's context.
When a message is fetched, component B starts a request with the ids from the message:
```
var requestTelemetry = new RequestTelemetry
{
  Name = "CloudService." + queueMessage.ContentType,
};
requestTelemetry.Context.Operation.Id = msg.Properties["OperationId"]?.ToString();
requestTelemetry.Context.Operation.ParentId = msg.Properties["RequestId"]?.ToString();

// This discards the span id because it does not have 32 chars
using (var operation = this.telemetryClient.StartOperation(requestTelemetry))
{
  /* Process message */
}
```

### What doesn't work
Component A starts the operation with a 16 character id. This is known in the standard as a shortened trace or span id. Component B does not allow this and replaces it with a 32 character trace id.
Because of this, the requests from A and B have different operation ids and thus can not be correlated across different resources.

**Comment by lmolkova** [comment]
Thanks for the code snippets, it really helps

> Component A starts the operation with a 16 character id. This is known in the standard as a shortened trace or span id. Component B does not allow this and replaces it with a 32 character trace id.

https://github.com/microsoft/ApplicationInsights-dotnet/blob/d032dbfdab3059f894aaa0de139a01231ccb997c/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/OperationTelemetry.cs#L112

this line generates requestTelemetry.Id, not request.Context.Operation.Id, operation.Id should be 16 bytes.

If I create an empty WebApi or MVC app and enable AppInsights, here is what requestTelemetry has in ids (please don't use this way to get requestTelemetry, it's just for debugging!)

![image](https://user-images.githubusercontent.com/2347409/74556695-7ab6e180-4f13-11ea-99de-5bd57a8116fe.png)

---------------------

Where do you get `request` from for this line `serviceBusTelemetry.Context.Operation.Id = request.Context.Operation:Id` ?

```csharp
// Manually set these now because the dependency may run later than the request
// Request is sourced from OperationContext.Current
serviceBusTelemetry.Context.Operation.Id = request.Context.Operation:Id;

...

So it seems `request` telemetry you are working with is not right one or perhaps you changed configuration or didn't mention some details?

To make it right, instead of 
```csharp
// Manually set these now because the dependency may run later than the request
// Request is sourced from OperationContext.Current
serviceBusTelemetry.Context.Operation.Id = request.Context.Operation:Id;
serviceBusTelemetry.Context.Operation.ParentId = request.Id;
```

do

```csharp
this.telemetryClient.Initiralize(serviceBusTelemetry);
```

Also, if you customized your configuration for Azure App Service (component A), please share what was changed.

**Comment by DJ4ddi** [comment]
> this line generates requestTelemetry.Id, not request.Context.Operation.Id, operation.Id should be 16 bytes.

They're always the same for the first request of the pipeline. From your words, I assume that should not be the case?

There is one custom initializer that I mostly copied from the [experimental WCF AI SDK](https://github.com/Microsoft/ApplicationInsights-SDK-Labs/tree/master/WCF) and then forgot (sorry about that). Maybe that is the missing detail and the reason why the request id is used for the operation id.

I'll investigate and report back.

**Comment by DJ4ddi** [comment]
The good news is: I found and fixed the initializer that used the request id as operation id. I can now use the same id for the entire pipeline.

Unfortunately, that didn't help me reach my goal, as the transaction viewer still does not unify items across different resources (even though they have the same operation id). As this isn't within the scope of this issue, I'll close it.

Thank you for helping me find the problem (while I was looking in the wrong place).

**Comment by lmolkova** [comment]
@DJ4ddi 

thanks for the update! the feature that stitches telemetry across AppInsights resources is being under test (it only works over http), it will be released in several month.
