### ISSUE TITLE
Microsoft.ApplicationInsights.WorkerService depends on Microsoft.Extensions.DependencyInjection 2.2 instead of 2.1

### ISSUE THREAD

**Issue by czb182** [microsoft/ApplicationInsights-dotnet#1677]
I noticed that the Microsoft.ApplicationInsights.WorkerService nuget package has a dependency on Microsoft.Extensions.DependencyInjection version 2.2.0.  I see Microsoft.ApplicationInsights.WorkerService being advertising for Asp.Net.Core 2.1+ in documentation so seems like it should depend on Microsoft.Extensions.DependencyInjection 2.1.*. 

I asked on dotnet repo about matching .NET core version against asp.net/extensions and they said it should match, which is why im bringing this up.
https://github.com/dotnet/extensions/issues/2799

**Comment by TimothyMothra** [comment]
Thank you for bringing this to our attention. 
I'll take a look at it and see if we can downgrade the version.

**Comment by eddynaka** [comment]
@cijothomas / @TimothyMothra , I was looking at this issue. I saw that we have some references to DependencyInjection 2.2 in 3 projects:
- TelemetryChannel.Tests
- Ilogger.NetStandard.Tests
- ApplicationInsights.WorkerService

To solve this issue, we would have to downgrade at least to 2.1.0 or 2.1.1. What do you think?

With this, we would be able to accept netcoreapp 2.1, 2.2 and 3.*

Let me know!

Thank you

**Comment by TimothyMothra** [comment]
@eddynaka feel free to start a [WIP] PR (work in progress) with this change.
We'll be looking for tests to validate that this change doesn't impact functionality so please think about how to test this change against the different target frameworks.
If you can verify that we already have test coverage I think that would be sufficient.

**Comment by eddynaka** [comment]
Sure!

To test the WorkerService, I was thinking in creating 3 projects, plug the dlls and check in ApplicationInsights the collected data.

Doing that before the change and after the change. The results have to be the same.

I will check our current automatic tests and see if they keep working as well.
