### ISSUE TITLE
Azure "App Configuration" not respected

### ISSUE THREAD

**Issue by syndicatedshannon** [microsoft/ApplicationInsights-dotnet#1684]
## Issue Summary
`IServiceCollection.AddApplicationInsightsTelemetry()` data is not collected to the `ApplicationInsights:InstrumentationKey` destination set in my "App Service"-connected "App Configuration" service.

The same `APPINSIGHTS_INSTRUMENTATIONKEY` configured directly in my "App Service" "Application Settings" results in successful data collection.

## Repro Steps
1. enable telemetry as instructed here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#enable-application-insights-server-side-telemetry-no-visual-studio but do not configure instrumentation key
 1a. add `IServiceCollection.AddApplicationInsightsTelemetry()` to `ConfigureServices` in Startup.cs
 1b. add the NuGet package Microsoft.ApplicationInsights.AspNetCore 2.12.0
 1c. skip substep 3  (instrumentation key)
2. instead of setting the instrumentation key in appsettings.json as described in step 3 of that documentation link, provide the value via Azure App Configuration Service. Basically:
 2a. Provision an Azure App Configuration service
 2b. Add `IConfigurationBuilder.AddAzureAppConfiguration` to Program.cs with the provisioned connection string
 2c. Add the NuGet package Microsoft.Azure.AppConfiguration.AspNetCore
 2d. Add the instrumentation key as `ApplicationInsights:InstrumentationKey`
 2e. Deploy the application and cause it to call `ILogger.LogError()`

##  Actual Behavior
No telemetry is collected when configured using the above method. Telemetry is collected normally after adding the same InstrumentationKey to the Application Settings via Azure management UI.

## Expected Behavior
I expected telemetry to be collected using this method. Although App Configuration is not specifically referenced, all official documentation and independent guidance (e.g. https://stackoverflow.com/a/50719063/608220) leads me to believe all active configuration sources are valid key sources.

## Version Info 
SDK Version : 2.12.0
.NET Version : Core 3.0			
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Manual addition of NuGet package and AddApplicationInsightsTelemetry()
OS : Linux on Azure App Server
Hosting Info (IIS/Azure WebApps/ etc) : Standard App Service Plan

**Comment by Dmitry-Matveev** [comment]
Can you trace the value that actually gets assigned to IKey in runtime? Is it the one you'd expect and is matching the one previously provided in `appsettings.json`?

You are correct, regardless of IKey source, if the right IKey is provided at the initialization time as a configuration method parameter or as an environment variable `APPINSIGHTS_INSTRUMENTATIONKEY`, the end result should be the same - fully initialized AI with the right Key.

Hence, my suspicion that IKEY was either possibly empty at the moment it was provided to the configuration method (e.g. Configuration Service was not resolving value yet) or IKEY looks different from its standard GUID-like form, e.g. extra quotes.

**Comment by syndicatedshannon** [comment]
mmmm... probably? LOL. We'll have to provision and configure a dev copy of App Configuration service, or remember how to remote debug in Azure. Don't close this if you don't hear back from me today ;)

**Comment by syndicatedshannon** [comment]
@Dmitry-Matveev I just started investigating this further (started configuring another Azure resource group, etc.) and came across a distinction I didn't know existed; host vs. app configuration. I suppose Application Insights uses host configuration? I want to make sure I'm inspecting the right IKey in my efforts.

If I knew when the value needed to be available by. I haven't dug into AI internals to see when the value is actually loaded. I know AI logging isn't available during startup, but maybe the key is loaded earlier?

**Comment by cijothomas** [comment]
@syndicatedshannon 
The follow issue is related.
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1566
By default, SDK looks for ikey in the documented places only. 
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1566#issuecomment-486809909

**Comment by syndicatedshannon** [comment]
@cijothomas Would you please clarify? I'd already read that documentation thoroughly, and reread the relevant section multiple times before reporting a defect. Note that I had not yet seen #1566

By "looks in the documented places only", you mean the specific Application Insights document section you linked, which includes: environment variables, and appsettings.json in the application root?

Note the Azure App Config / Application Settings configuration blade also works, which is not included in the documentation you linked (although it's possible that configuration mechanism also sets environment variables). This appears to be the mechanism used by the in-Azure Applications Insight Enablement Wizard.

**Comment by cijothomas** [comment]
> By "looks in the documented places only", you mean the specific Application Insights document section you linked, which includes only: environment variables, and appsettings.json in the application root?

Yes.

Other Azure experiences like WebApp configuration wizards does this internally. (it sets APPINSIGHTS_INSTRUMENTATIONKEY env variable)

**Comment by cijothomas** [comment]
If your goal is to use ikey from a non-standard place, then use the `.AddApplicationInsightsTelemetry(Configuration) ` overload instead of .AddApplicationInsightsTelemetry()` .

**Comment by syndicatedshannon** [comment]
FYI, the Azure wizard also did this:
![image](https://user-images.githubusercontent.com/905156/75189957-ef103280-5714-11ea-9fc4-68296aa76dd7.png)

**Comment by syndicatedshannon** [comment]
thank you @cijothomas , I appreciate your follow-up.

I definitely don't desire to use a "non-standard place" for configuration. My entire purpose behind refactoring my configuration into Azure App Configuration service is to follow supported standards. 

IConfiguration is probably the gold standard for ASP.NET Core configuration; and supporting a file named `appsettings.json` while not supporting IConfiguration probably would yield surprise to most developers. I haven't looked, but internal to AI configuration load process, I suspect IConfigurationProvider is used.

**Comment by syndicatedshannon** [comment]
Side note, not to call out @Dmitry-Matveev for helping ;), but notice they had the same expectation as I did when they first commented here.

**Comment by syndicatedshannon** [comment]
It's a small amount of work, and not a big deal to add the small extension method to our proprietary code, to load from IConfiguration. I only dispute the definition of standard because I think it's relevant to AI product and documentation quality.

Would love to see either the documentation or product enhanced/improved, but you've given us what we need to solve. Thanks, and cheers!

**Comment by cijothomas** [comment]
I'll close this as no pending questions. Reopen if there are.
