### ISSUE TITLE
Some perf counters aren't collected when app is hosted on Azure WebApp

### ISSUE THREAD

**Issue by tukaef** [microsoft/ApplicationInsights-dotnet#1685]
## Repro Steps
1. Specify the following pefr counters to collect:
- `\.NET CLR Memory(??APP_CLR_PROC??)\# Total committed Bytes`
- `\ASP.NET Applications(??APP_W3SVC_PROC??)\Request Bytes In Total`
- `\ASP.NET Applications(??APP_W3SVC_PROC??)\Request Bytes Out Total`

##  Actual Behavior
The counters aren't collected. The following message is logged:

> AI: Error collecting 3 of the configured performance counters. Please check the configuration.
Counter \.NET CLR Memory(??APP_CLR_PROC??)\# Total committed Bytes: Failed to perform the first read for web app performance counter. Please make sure it exists. Counter: # Total committed Bytes
Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Request Bytes In Total: Failed to perform the first read for web app performance counter. Please make sure it exists. Counter: Request Bytes In Total
Counter \ASP.NET Applications(??APP_W3SVC_PROC??)\Request Bytes Out Total: Failed to perform the first read for web app performance counter. Please make sure it exists. Counter: Request Bytes Out Total

## Expected Behavior
The counters are collected with the values exposed as environment variables as stated here https://docs.microsoft.com/bs-latn-ba/azure/azure-monitor/app/performance-counters#performance-counters-for-applications-running-in-azure-web-apps

## Version Info 
SDK Version : 2.12.1
.NET Version :	4.7 						
Hosting Info  : Azure WebApps

**Comment by tukaef** [comment]
I can see some differences between property names in [CounterFactory.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/PerformanceCollector/Perf.Shared/Implementation/WebAppPerformanceCollector/CounterFactory.cs) and the environment variable properties (an example [here](https://github.com/projectkudu/kudu/wiki/Perf-Counters-exposed-as-environment-variables), I get the same names for `WEBSITE_COUNTERS_ALL`):
- line 588: `commitedBytes` vs `committedBytes`
- line 193: `requestsBytesIn` vs `requestBytesIn`
- line 198: `requestsBytesOut` vs `requestBytesOut`

If the fix would be as simple as changing the property names, I think I could make a PR for this.

**Comment by TimothyMothra** [comment]
@tukaef we gladly accept contributions to our SDK. :)

I don't have the context on PerfCounters. @cijothomas Can you comment?

**Comment by TimothyMothra** [comment]
I got some information about this...
Azure WebApps exposed these perf counters on our team's request.
We think they probably had the initial typos and misspellings.
It's possible that someone on their team corrected the typos, which would have broken our integration. 
This needs some further investigation.

**Comment by cijothomas** [comment]
@TimothyMothra I think AI SDK had this typo from day 1. We can just fix the typos.
 We can take a PR which fixes these typos.
