### ISSUE TITLE
All perf counters stop being collected when any of faulty counters are specified to collect on Azure WebApps

### ISSUE THREAD

**Issue by tukaef** [microsoft/ApplicationInsights-dotnet#1686]
This is a consequence of #1685. When any of the counters in question is specified, the collector stops collecting the other counters after 5-6 successful iterations. 

## Repro Steps
1. Specify any of the following counters to collect:
- `\.NET CLR Memory(??APP_CLR_PROC??)\# Total committed Bytes`
- `\ASP.NET Applications(??APP_W3SVC_PROC??)\Request Bytes In Total`
- `\ASP.NET Applications(??APP_W3SVC_PROC??)\Request Bytes Out Total`
2. Specify any other counter, or just leave the default counters

##  Actual Behavior
After deploy, all counters apart from the faulty ones are collected and sent only 5-6 times (a few minutes). After that, nothing is collected (nor sent).

## Expected Behavior
Non-faulty counters being collected successfully during the app lifetime. 

## Version Info 
SDK Version : 2.12.1
.NET Version :	4.7 						
Hosting Info  : Azure WebApps

**Comment by tukaef** [comment]
This is likely due to WebAppPerformanceCollector.RefreshCounters [throwing an exception](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/PerformanceCollector/Perf.Shared/Implementation/WebAppPerformanceCollector/WebAppPerformanceCollector.cs#L149) when [PerformanceCollectorModule.EnsurePerformanceCountersRegistered](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/PerformanceCollector/Perf.Shared/PerformanceCollectorModule.cs#L363) is called. Since it's not caught on the way, we end up not updating `lastRefreshTimestamp` (line 369). Which in turn makes `EnsurePerformanceCountersRegistered` be always trying to refresh counters, and thus failing.  

One of the solutions is to catch the exception in `WebAppPerformanceCollector.RefreshPerformanceCounter`. 
This would be similar to what's implemented in [StandardPerformanceCollector](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/PerformanceCollector/Perf.Shared.NetStandard20Net45/StandardPerformanceCollector/StandardPerformanceCollector.cs#L187).

**Comment by TimothyMothra** [comment]
Hi, your explanation makes sense.
I don't have time to investigate this right now, but we would gladly accept your PR. :)

**Comment by cijothomas** [comment]
@tukaef Thanks for reporting and investigating the issue. Please submit a PR if you have time.
