### ISSUE TITLE
NLog Application Insights Target needs a fallback for Instrumentation key

### ISSUE THREAD

**Issue by grahambunce** [microsoft/ApplicationInsights-dotnet#1688]
Looking at this source code

```
        protected override void InitializeTarget()
        {
            base.InitializeTarget();
#pragma warning disable CS0618 // Type or member is obsolete: TelemtryConfiguration.Active is used in TelemetryClient constructor.
            this.telemetryClient = new TelemetryClient();
#pragma warning restore CS0618 // Type or member is obsolete

            string instrumentationKey = this.instrumentationKeyLayout.Render(LogEventInfo.CreateNullEvent());
            if (!string.IsNullOrWhiteSpace(instrumentationKey))
            {
                this.telemetryClient.Context.InstrumentationKey = instrumentationKey;
            }

            this.telemetryClient.Context.GetInternalContext().SdkVersion = SdkVersionUtils.GetSdkVersion("nlog:");
        }
```

It appears that if the InstrumentationKey isn't set in the NLog config file (assuming not configuring by code) then NLog will not integrate with AI. My testing seems to demonstrate this; no key in the xml = no AI logging.

This doesn't play nice with Azure DevOps File Transform tasks, which only performs variable substitution on specific config file sections. The hoops needed to get a valid environment appropriate value into the XML are complicated.

e.g. An App Insights instance for DEV, UAT, PROD means you need to have 3 different instrumentation keys, but these cannot be applied by the Azure DevOps Release process as the File Transform task does not support transforming the NLOG config file.

The NLog package should check the targets file (as now) and then fall back (e.g. to an environment variable such as the APPINSIGHTS_INSTRUMENTATIONKEY that is used by everything else). It's inconsistent that the NLOG adaptor needs a different way of configuring itself.

**Comment by snakefoot** [comment]
`InstrumentationKey` is NLog Layout, so you can make your own lookup/fallback-logic:

https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer
https://github.com/nlog/nlog/wiki/Environment-Layout-Renderer
https://github.com/nlog/nlog/wiki/WhenEmpty-Layout-Renderer

Maybe something like this:

`InstrumentationKey="${configsetting=APPINSIGHTS.INSTRUMENTATIONKEY:whenEmpty=${environment=APPINSIGHTS_INSTRUMENTATIONKEY}}"`

**Comment by grahambunce** [comment]
@snakefoot Thanks but this doesn't appear to work. it generates an error when parsing the nlog.config file.

"Error when setting property 'InstrumentationKey' on ApplicationInsightsTarget Target[(unnamed)]" and then on the inner exception: "LayoutRenderer cannot be found: 'environment=APPINSIGHTS_INSTRUMENTATIONKEY' "

I can confirm that APPINSIGHTS_INSTRUMENTATIONKEY exists as an Environment Variable. This is the nlog target:

```
  <targets>
    <target type="ApplicationInsightsTarget"
            name="applicationinsights"
            layout="${date:format=yyyy-MM-dd HH\:mm\:ss.fffff},${logger},${message}">
      <instrumentationKey>${environment=APPINSIGHTS_INSTRUMENTATIONKEY}</instrumentationKey>
    </target>
  </targets>
```

**Comment by snakefoot** [comment]
Sorry about the confusion. Yes `${environment=APPINSIGHTS_INSTRUMENTATIONKEY}` was incorrect (Have updated my comment).

This will lookup the environment variables on the machine. If having access:

`<instrumentationKey>${environment:APPINSIGHTS_INSTRUMENTATIONKEY}</instrumentationKey>`

**Comment by TimothyMothra** [comment]
Thank you both for finding a solution. 
I'm going to reopen this task as a reminder to update our documentation with some more explicit examples.
