### ISSUE TITLE
AI Internal error "An instance of EventSource with Guid XXX already exists."

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1693]
**TODO: Need to add this to the official FAQ.**

The full error is something like this:

> AI (Internal): [Microsoft-ApplicationInsights-Data] ERROR: Exception in Command Processing for EventSource Microsoft-ApplicationInsights-Data: 
> An instance of EventSource with Guid XXX already exists.

This can occur whet the Application Insights SDK is initialized twice in the same process.
This is common in Azure Functions when users try to set up their own TelemetryClient.

The recommended fix is to use dependency injection to grab Function's `TelemetryConfiguration` and create a new `TelemetryClient` from that config object.

Code sample is here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-and-later-2

**Comment by srdan-bozovic-msft** [comment]
I'm using dependency injection and error still appears in the log ...

_public static void Run([TimerTrigger("0 7 * * * *")]TimerInfo myTimer, ILogger log)_

**Comment by danielwcr** [comment]
I also got this error using dependency injection. It happend when I recreated my environment. The function eventually executed sucessfully after manually disabling/enabling app insights in the function app.
