### ISSUE TITLE
ApplicationInsights and log4net logging do not work together

### ISSUE THREAD

**Issue by mnelvers** [microsoft/ApplicationInsights-dotnet#1701]
We have an application that runs as a Windows service.  Over the course of several days it appears to have a memory leak.  The application uses log4net to log information to a table in an Informix database.  That has been working forever.  I attempted to add ApplicationInsights to the application to monitor the memory usage.  I was able to add ApplicationInsights and collect telemetry via an Azure ApplicationInsight object.  However, the log4net logging stopped working and the application ran very slowly.  If I removed ApplicationInsights, the application started logging again and ran normally.

I would greatly appreciate any help in getting both ApplicationInsight and log4net logging working together.

The application is compiled using Visual Studio 2017 with .NET Framework 4.8.
Both log4net and ApplicationInsights were added via Nuget in Visual Studio.
The application runs on a VM with a Windows Server 2012 R2 Standard OS.

I have attached sanitized versions of the app.config and ApplicationInsights.config files.  In the app.config file, there are three comments marking where changes were made for ApplicationInsights.  (The .txt extension was just so I could attach the files.)

[app.config.txt](https://github.com/microsoft/ApplicationInsights-dotnet/files/4237133/app.config.txt)
[ApplicationInsights.config.txt](https://github.com/microsoft/ApplicationInsights-dotnet/files/4237134/ApplicationInsights.config.txt)

**Comment by cijothomas** [comment]
Can you share a small repro app for us to investigate? it is very hard to do any investigations for these issues without a repro app.

**Comment by mnelvers** [comment]
I don’t know when I will get to this, what with the Corona Virus stuff.

Thanks,

Mike
