### ISSUE TITLE
Application Insight Instrumentation Key is empty in AspNet 5 via DI

### ISSUE THREAD

**Issue by lucadibiagio** [Microsoft/ApplicationInsights-dotnet#171]
hi all,
i notice that the instrumentationKey is empty in my asp.net 5 project (1.0.0-rc1-update1)

Steps to reproduce:
- create file with name config.json
- populate the file with  appInisight informations:
{
   "ApplicationInsights": {
    "InstrumentationKey": "<my instrumentation key>"
  }
} 

- read and build configuration:
public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
        {
            Configuration = new ConfigurationBuilder()
               .SetBasePath(appEnv.ApplicationBasePath)
               .AddJsonFile("config.json")
               .Build();
        }

- insert the following line in method ConfigureServices in startup.cs:
  services.AddApplicationInsightsTelemetry(Configuration);

- insert the following lines in method Configure:
           app.UseApplicationInsightsRequestTelemetry();
            app.UseApplicationInsightsExceptionTelemetry();

now when i try to retrieve the TelemetryClient from myController(via Dependency Injection) i notice that the InstrumentationKey is Empty.

regards,

luca

**Comment by abaranch** [comment]
Please check you configuration file. Did you have all open, closing braces in place; did not you add it inside some other configuration section rather that upper most?
Also could you please move this issue to a correct repo: https://github.com/Microsoft/ApplicationInsights-aspnetcore

**Comment by abaranch** [comment]
@lucadibiagio Do you still see the issue?

**Comment by lucadibiagio** [comment]
yes i already have,
i move this question to the correct repo
thank you

**Comment by SergeyKanzhelev** [comment]
@lucadibiagio can you please insert the link to the issue in the different repository. Closing issue for now

**Comment by jittuu** [comment]
Since I also faced the same issue, I moved it to [here](https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/141).
