### ISSUE TITLE
Logging Worker Service Dependency Tracking

### ISSUE THREAD

**Issue by OnamChilwan** [microsoft/ApplicationInsights-dotnet#1716]
I am trying to use ILogger as its recommended that we don't directly inject TelemetryClient but I noticed some oddities doing this and perhaps I have configured something incorrectly.

In a nutshell, I am injecting ILogger and doing some logging. For example:

            using (var scope = this.logger.BeginScope(new Dictionary<string, string>
            {
                { "MyReference", "HelloWorld" }
            }))
            {
                this.logger.LogDebug("Foo");
                this.logger.LogInformation("Bar.");
                var response = await this.httpClient.PostAsync(..); // dependency tracking
            }

What I've noticed is that we don't get depedency tracking being aggregated for free like we do if it was an ASP.NET application. Am I missing something in terms of config? I can see trace lines but the dependencies tracked are against an entirely different `operationId` and not collated when searching it in the portal. How do I aggregate the two? The only way I have been able to do this is to use TelemetryClient directly when writing my logs. 

For example, if I did the same thing  but injecting TelemetryClient in the trace lines and depedency calls are aggregated.

            var op = this.tc.StartOperation<RequestTelemetry>("MyReference", "HelloWorld");
            op.Telemetry.Id = "HelloWorld";
            op.TrackTrace("Foo");
            var response = await this.httpClient.PostAsync(..); // is tracked in AI

I have hooked in App Insights via `services.AddApplicationInsightsTelemetryWorkerService();`

Using:
- NET Core 3.1.101
- Microsoft.ApplicationInsights.WorkerService, Version="2.12.0"
- Microsoft.Extensions.Hosting, Version="3.1.0"
- Microsoft.Extensions.Logging, Version="3.1.0"

What I am expecting to see is when I search for "HelloWorld" in the AI Azure Portal it should aggregate all the logs made within that scope.

**Comment by cijothomas** [comment]
The approach using telemetry clients StartOperation is the right way of doing it as documented here:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#net-corenet-framework-console-application

ILogger scopes cannot be used to group together telemetry.
