### ISSUE TITLE
Custom metric namespace name missing

### ISSUE THREAD

**Issue by zsonglorman** [microsoft/ApplicationInsights-dotnet#1717]
I'm trying to create custom metrics with custom namespaces, but the custom namespace names are not shown on Azure portal - Application Insights - Metrics tab. In the screenshot you can see 3 different custom namespaces, though their names are missing.

![image](https://user-images.githubusercontent.com/19626247/75352881-befa9800-58aa-11ea-988e-cc2130187bd4.png)

Here is the line which sends the metric values via _TelemetryClient_:

`telemetryClient.GetMetric(new MetricIdentifier("MyNamespace", "MetricName")).TrackValue(new Random().Next(1, 5));`

Could you please help me what am I doing wrong, or let me know if this is a bug. Thank you in advance.

**Comment by TimothyMothra** [comment]
Hello, can you please provide two things:
- what's your SDK version?
- Can you please provide us the json object that's being sent from your application? You can capture this from the console output of Visual Studio while debugging, or using a tool like Fiddler. We want to see what was sent to our ingestion to identify is this an ingestion/parsing bug or did the sdk fail to send the custom metric name. You'll want to remove your ikey from your json before sharing.

Please, let me know if you any other questions.

**Comment by zsonglorman** [comment]
Hello, thanks for your answer.

My Microsoft.ApplicationInsights version is 2.13.1.

Here is the JSON sent (namespace is included):

```
{
   "name":"Microsoft.ApplicationInsights.xxx.Metric",
   "time":"2020-02-28T10:33:01.0000000Z",
   "iKey":"xxx",
   "tags":{
      "ai.cloud.roleInstance":"DESKTOP-xxx",
      "ai.internal.sdkVersion":"m-agg2:2.13.1-12554"
   },
   "data":{
      "baseType":"MetricData",
      "baseData":{
         "ver":2,
         "metrics":[
            {
               "ns":"MyNamespace",
               "name":"MetricName",
               "kind":"Aggregation",
               "value":1,
               "count":1,
               "min":1,
               "max":1,
               "stdDev":0
            }
         ],
         "properties":{
            "_MS.AggregationIntervalMs":"60000"
         }
      }
   }
}
```

Surprisingly, today when I checked on Azure Portal, the metric namespace names are shown magically, although I didn't change anything on our side. Was something fixed on your side?

![image](https://user-images.githubusercontent.com/19626247/75542205-9cd65680-5a1f-11ea-9031-e9d6533addd6.png)

Thanks again.

**Comment by TimothyMothra** [comment]
Based on this I don't think there was an SDK bug, and you're on the latest version of our SDK. :)
Our UX team has daily deployments so it's possible that they broke something and then rapidly fixed it. To be honest, I wouldn't know.

I'm sorry you were affected, but I'm happy to hear your issue has been resolved!
I'm going to go ahead and close this issue, but if you have additional questions please don't hesitate to reach out.
