### ISSUE TITLE
ILogger arguments rendered as name of the object in custom dimensions

### ISSUE THREAD

**Issue by reft** [microsoft/ApplicationInsights-dotnet#1722]
Microsoft.ApplicationInsights.AspNetCore 2.13.1

It seems like **TYPED** objects are rendered as strings, (name of the object), in custom dimensions when passed as arguments to ilogger.
When not typed, the arguments are rendered correctly as json.

**Register telemetry:**

`services.AddApplicationInsightsTelemetry();`

**Working log:**

    public class HealthController : ControllerBase
    {
        private readonly ILogger<HealthController> _logger;

        public HealthController(ILogger<HealthController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Get()
        {
            var health = new
            {
                 ok = false
            };

            _logger.LogInformation("HEJ2 {extra}", new { health });

            return Ok(health);
        }
    }

![image](https://user-images.githubusercontent.com/3218213/76159743-c54b0880-6123-11ea-8620-9f511e070c18.png)

**Not working log:**

    public class HealthController : ControllerBase
    {
        private readonly ILogger<HealthController> _logger;

        public HealthController(ILogger<HealthController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Get()
        {
            var health = new HealthViewModel
            {
                 ok = false
            };

            _logger.LogInformation("HEJ2 {extra}", new { health });

            return Ok(health);
        }
    }

![image](https://user-images.githubusercontent.com/3218213/76159735-a9476700-6123-11ea-8a37-762b54fd365e.png)

Please see the health colum in the screenshots.

**Comment by pharring** [comment]
I think you're expecting too much of the logger. It doesn't know about JSON format, it just calls Convert.ToString on properties:

https://github.com/microsoft/ApplicationInsights-dotnet/blob/aee56cd43721bb64fb4e61e1173223471d9a18a7/LOGGING/src/ILogger/ApplicationInsightsLogger.cs#L168

`Convert.ToString` typically calls `ToString()` and the default ToString implementation for new classes is simply to return the type name. Obviously, you can override ToString if you want to supply a different value. The default ToString for anonymous types (the `new { health }` in your example) is to call ToString() on all properties. You'll notice that it's not still not JSON format.

**Comment by reft** [comment]
@pharring I'm currently using a custom ILogger provider which transform the arguments to json, but it seems like application insights doesnt use it. Is there a setting for this or is it not supported? If this worked I wouldn't have to json stringify each argument everytime I would like to log an object.

**Comment by pharring** [comment]
No, Application Insights is its own logger provider and isn't extensible.

I think you're expecting too much from the ILogger framework (in general) and Application Insights (in particular). It's up to each provider to serialize events the way expect. For Application Insights, the formatter arguments (an ILogger's concept) are recorded as custom properties (an Application Insights concept) on the event.

There's been talk of pluggable serializers for ILogger in .NET 5, (the most frequent ask being a structured JSON logger) but nothing planned that I know of.

Out of interest, what is the custom ILogger provider you're using?

**Comment by reft** [comment]
@pharring  I extract the arguments from TState and display it neatly as json for the console log.

    var originalMessage = new KeyValuePair<string, object>();
    foreach (var x in extraFields)
    {
        if (x.Key == "{OriginalFormat}")
        {
            originalMessage = x;
            break;
        }
    }

    if (string.IsNullOrEmpty(originalMessage.Key)) return formattedMessage;

    formattedMessage = originalMessage.Value.ToString();
    var reg = new Regex("{([A-z]*)*}", RegexOptions.Compiled);
    var match = reg.Matches(originalMessage.Value.ToString());

    if (!match.Any()) return formattedMessage;

    foreach (var item in match)
    {
        var parameterName = item.ToString().Replace("{", "").Replace("}", "");
        var parameterValue = extraFields.FirstOrDefault(x => x.Key == parameterName);

        if (!string.IsNullOrEmpty(parameterValue.Key))
        {
            formattedMessage = formattedMessage.Replace(item.ToString(), "");
            ((IDictionary<string, object>)logEntry).Add(new KeyValuePair<string, object>(parameterName, parameterValue.Value));
        }
    }

Ive also tried using the Process ITelemetry middleware but I don't have access to the TState there which is a shame, otherwise I could have used the same implementation as above....

**Comment by reft** [comment]
I solved it by creating a middleware, override the name and custom dimensions, and used ToJson extensions on objects.

You can see it here
https://stackoverflow.com/questions/60582917/application-insights-ilogger-arguments-rendered-as-name-of-the-object-in-custo

**Comment by plaisted** [comment]
@pharring I was expecting this behavior from ILogger / AI as well. We've previously used Serilog + ILogger + Elasticsearch and then ILogger + Google Cloud Logging and in both cases if you pass an object into the log it is turned into a queryable item (not the name of the class, and not just raw JSON text).

Example:
```csharp
var item = new Item { Example = "test" };
_logger.LogInformation("Logging with structure is fun, {@Item}", item);
```
Psuedo-query (depends on log store):
```
select * from Logs where item.Example == "test"
```
would return the log.

It looks like Serilog includes a sink to send to application insights with this functionality by default but not sure how easy it would be to integrate into the apscore AI implementation.

**Comment by pharring** [comment]
Unfortunately, Application Insights has only "key,value" (string, string) pairs for custom dimensions. It just doesn't have a way to represent object hierarchies.
