### ISSUE TITLE
Application Insights Profiler stopped working with MS.AI.AspNetCore 2.14.0-beta3

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-dotnet#1727]
.NET Core Web API (2.1) + MS.AI.AspNetCore 2.14.0-beta3 + AI.Profiler from site extension.

* SDK version: 2.14.0-beta3
  * This does **NOT** repro with previous versions of SDK - 2.14.0-beta2 or 2.13.1.
* .NET Core 2.1 LTS, .NET Core 3.1 LTS, target netcoreapp2.1 / 3.1 accordingly.
* Hosted on Azure Web Apps
* Platform and OS version: Windows

Starting with 2.14.0-beta3, the profiler can't get request events.

Still looking into what is the cause. At the same time, @TimothyMothra @SergeyKanzhelev any direction?

**Comment by xiaomi7732** [comment]
Loop in @Dmitry-Matveev for awareness.

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-dotnet/pull/1715/files#diff-532acfbbd4b63e26096cb70d12ef859dR25 The envelope name changed cause this?

This changed json format over wire too.
{"name":"Microsoft.ApplicationInsights.Dev.79a19363f02545b7a3f4b2eb317a4db7.Request",  
 - beta2

{"name":"AppRequests", - beta2

**Comment by Dmitry-Matveev** [comment]
@cijothomas , yes, we are covering/debugging it offline with @xiaomi7732 , added you to the thread as well.

**Comment by xiaomi7732** [comment]
Verified working with 2.14.0-beta5. Close this one.
