### ISSUE TITLE
Need to document channel behavior on endpoint timeouts

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#1731]
Validate timeout response from SDK. Original suspicion was that ingestion service timeouts cause SDK to timeout and retry. We are lacking documentation on what happens on endpoint timeouts.
a.	What’s the default timeout on SDK? 
b.	Do we retry on timeout?
c.	Is it a good idea to increase the number of workers to a very big number to prevent timeout-caused delays?

**Comment by cijothomas** [comment]
1.
Default timeout is 100 secs. Channel dont expose this as a configurable setting. I wonder if 100 sec is too high?
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L21

2. Yes. 
We catch `OperationCanceledException` (which would occur at 100 sec timeout) and set status a Timeout
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L203-L207

Error policy is configured to handle this timeout.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/ServerTelemetryChannel/Implementation/ErrorHandlingTransmissionPolicy.cs#L75

3. The default workers is now default 10. If there is a backend issue actually occurring causing timeouts, then I don't see how increasing workers can help. The default 10 workers will wait a long time for response, and all the pending telemetry from this time goes into Memory (and Disk if Memory overflows)

FYI @rajkumar-rangaraj as you are working in this area.
