### ISSUE TITLE
Excessive memory consumption by Application Insights metric reporting

### ISSUE THREAD

**Issue by SidShetye** [microsoft/ApplicationInsights-dotnet#1734]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:

* SDK version: `<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.13.1" />`
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): `netcoreapp3.1`
* Hosting Info (IIS/Azure WebApps/etc): `Azure WebApps`
* Platform and OS version: dev, windows 10, prod, linux

If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

**Steps to reproduce.**

1. Add Application insights via `<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.13.1" />` in `.csproj`
2. Edit startup as 

```
public void ConfigureServices(IServiceCollection services)
{
	// Enables Application Insights telemetry collection.
	services.AddApplicationInsightsTelemetry();

	// Remove extra AppInsight data collection per 
	// https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters#customizing-counters-to-be-collected
	// The following code removes EventCounterCollectionModule to disable the module completely.
	var eventCounterModule = services.FirstOrDefault<ServiceDescriptor>
				(t => t.ImplementationType == typeof(EventCounterCollectionModule));
	if (eventCounterModule != null)
	{
		services.Remove(eventCounterModule);
	}

   // snip
}
```
3. Hit F5 in VS and observer memory consumption

**What is the expected behavior?**
1. No additional metrics being collected and sent if we're following https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters#customizing-counters-to-be-collected to limit data collection. 
2. In the event of event collection, there shouldn't be any significant increase in memory consumption.

**What is the actual behavior?**

1. Metrics are STILL being collected and sent. Granted, some the those are not longer being collected but the design + documentation is very poor is users are expected to chase down all edge cases.
2. Memory A 400% increase in memory consumption (!?!)

![image](https://user-images.githubusercontent.com/2595088/76886086-7a28a800-683d-11ea-9c68-3f02aeec67d2.png)

**Comment by cijothomas** [comment]
What you are seeing is not from EventCounter module. But from PerformanceCounter module. Please try disabling it and see if this repros.
There is a known bug in .NET runtime when using Process related perf counters. I will try to find the original issue and link here. But meanwhile remove PerformanceCounter module and run the same experiment.

**Comment by cijothomas** [comment]
Btw - this perf counter issue will not occur for you in production as your prod is in Azure Web Apps. In Azure Web Apps, perf counters are collected differently.

**Comment by SidShetye** [comment]
@cijothomas thanks we already disabled `PerformanceCollectorModule` too but it's really crazy that the collection of such basic performance counters requires going from 105 MB to 360 MB of memory, right? 

Side note on product feedback - between the performance reported in this issue and the [memory leaks](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1678) issue, we feel the quality of Application Insights software is very lacking. We even have an ticket open with Microsoft support (120020121000224) where the Application Insights .net core SDK has a bug that causes it to send very high volume (600%) of `System.Runtime` and `Microsoft.AspNetCore.Hosting` counters. This bug can not only caps your customers data usage but also has a billing impact for no fault of theirs. Anyway, that's a separate topic.

### Disabling modules to conserve memory ?

Back to the topic of disabling modules and reducing memory consumption - what's the best way to ensure we have reliable control on application insights' various sub-modules? 

Seems in `Startup.cs`'s `ConfigureServices(...)`  we could use the 
```
services.AddApplicationInsightsTelemetry(opt => {
	opt.EnablePerformanceCounterCollectionModule = false;
	opt.EnableEventCounterCollectionModule = false;
        // other submodules disabled here if opt-in is default
        // how is azure data collection disabled?
});
```
This would a great pattern to abstract away internals of toggling but only if `ApplicationInsightsServiceOptions` has an `Enable<Submodule>`  boolean for every sub-module. **Does it?**

Especially compared to what's [documented](https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters#customizing-counters-to-be-collected) which requires intimate knowledge of service class names and additional code to remove each one.
```
// The following code removes EventCounterCollectionModule to disable the module completely.
var eventCounterModule = services.FirstOrDefault<ServiceDescriptor>
			(t => t.ImplementationType == typeof(EventCounterCollectionModule));
if (eventCounterModule != null)
{
	services.Remove(eventCounterModule);
}
```

### Memory consumption 

And finally, the core issue of this thread - excessive memory consumption - remains. Can the team investigate to see why simple reporting burns up so much memory?

**Comment by cijothomas** [comment]
1. The memory leak issue (https://github.com/microsoft/ApplicationInsights-dotnet/issues/1678) is investigated by a separate team. Since there is no update on the thread, I can do a follow up.

2.  Bug about EventCounters - Can you describe the bug please or open an issue? EventCounter (https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters) are sent every 60 secs, and the list of default counters are documented as well. The same doc also contains instructions for removal of the module or individual counters.

3. Every Module can be disabled using `ApplicationInsightsServiceOptions`. (in the recent version of the SDK)
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#using-applicationinsightsserviceoptions
The full list of options - https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/NETCORE/src/Shared/Extensions/ApplicationInsightsServiceOptions.cs

Specifically to your questions - Yes , it has "enableXYZModule" for every module.

4. Memory consumption from perf counter:
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1270
This is the original issue tracking it. The issue is inside application insights, but in performance counter library. I will need to find and follow up with owners of this library.

**Comment by SidShetye** [comment]
@cijothomas Thanks, appreciate the swift response. I'll go ahead and close this ticket since #1270 is tracking the same issue. 

Also, thanks for confirming the `enableXYZModule` pattern on `ApplicationInsightsServiceOptions`. IMHO, if that's the case, then the docs ([here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters#customizing-counters-to-be-collected) or [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#removing-telemetryinitializers) - could be other places too) should suggest that pattern for removing specific modules instead of the current search-and-remove-from-service-collection code snippets.

**Comment by cijothomas** [comment]
Yes. The enableXYZModule is only in the newer version of the SDK. 
The doc links to the full set of settings.
![image](https://user-images.githubusercontent.com/5232798/76907774-52006f80-6864-11ea-9c88-41d57ba0b4c2.png)

But you are right - I'm opening doc issue to get it updated to avoid any confusion
