### ISSUE TITLE
Improve supportability of TelemetryChannel.

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1735]
**Is your feature request related to a problem?**
It is currently very hard to do any SDK channel related investigation when customer reports issues with it - like telemetry loss or telemetry delay. The logs necessary for those investigation are not collected by default, and without the logs, there can be no meaningful investigation done about past issues.

**Describe the solution you'd like.**
Proposing to enable on-by-default File based logging for any issues SDK faces - SDK already logs issues using EventSource, and 'Error' level issues are automatically sent to customers ikey using same channel. While this is generally useful, its proven to be lacking to do telemetry loss/ delay investigation.

Proposals:
1. Have SDK log to local file all Error level, and Warning level issues from channel by default. File can be overwritten after a certain size to prevent infinite increase in size.
2, This feature must be turned on by default.
3. Review all the Error/Warning messages sent from channel - We should log when backend response is slower beyond a limit, when back-offs are active.
4. Apart from logs, start emitting metrics about the average response time, # of items in queue. 
   This can be done using EventCounters and published occasionally to the log File. This helps identify if SDK's backlog was huge at any point.

**Describe alternatives you've considered.**
We already have builti-in DiagnosticModule which sent Error level trace to backend. But this uses the same channel as for regular telemetry. This is not a good solution when the issue is about the channel itself.

**Additional context.**
We need to measure the perf impact of having a file logger on by default. Availability of a local file may be difficult in case App Service environments like Web Apps or Functions.

**Comment by cijothomas** [comment]
Bumping again as we saw one customer experience channel issue. An always-on File logging like the one proposed would have quickly helped root cause the issue.

**Comment by TimothyMothra** [comment]
I've already started looking into making it easier to temporarily enable the file logger.
https://github.com/microsoft/ApplicationInsights-dotnet/pull/1724
https://github.com/microsoft/ApplicationInsights-Home/blob/master/CrossSdkCollaboration/Self-Diagnostics.md


I'm in favor of an on-by-default file logging, as long as it can still be overridden by the self-diagnostics config.
We've heard that devops would like to be able to make changes to the application without redeploying the application itself.


One issue that we're going to have, our current file logger doesn't give us control of the file itself.
If we set this to always-on, I think we're going to want to control file size or purge files older than X days.

**Comment by cijothomas** [comment]
Correction to "AlwaysOn". I meant to say "On-By-Default".

One of the key reason why I want this OnByDefault is, if there is a network issue preventing SDK from reaching application insights, the network error is logged. If the network issue persists, then sdk enters exponential backoff mode. 
When one goes to collect logs, if SDK is in back-off mode, there wont be any attempt to connect to application insights backend, hence the logs wont have network error. (unless the app itself is restarted, which most cx dont like).

**Comment by cijothomas** [comment]
@rajkumar-rangaraj is working to implemetn #3 from above proposal - SDK to emit metrics using EventCounter, apart from existing EventSource logs.
