### ISSUE TITLE
NullReferenceException on Cosmos DB dependency collection

### ISSUE THREAD

**Issue by NoahStahl** [microsoft/ApplicationInsights-dotnet#1737]
I'm seeing the exception below, happy to provide any other details. Thanks!

Environment:

Microsoft.ApplicationInsights.AspNetCore 2.13.1
.Net Core 3.1 web or function project, x64 target
Local Windows 10 development on Visual Studio 16.5, and deployed to Azure App Service or Azure Function App

**Steps to reproduce.**
1. Run web project using both Application Insights and Cosmos DB SDK (v4 preview in my case)
2. Locally, observe NullReferenceException from AI when Cosmos queries execute
3. In Azure, observe AI errors logged for same exceptions

Local exception details:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.AI.DependencyCollector
  StackTrace:
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.AzureSdkDiagnosticsEventHandler.OnEvent(KeyValuePair`2 evnt, DiagnosticListener diagnosticListener)
```

AI service trace details:

```
AI (Internal): [Microsoft-ApplicationInsights-Extensibility-DependencyCollector] Failed to handle Azure.Cosmos-Query-Document.Stop event, error = 'System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.AzureSdkDiagnosticsEventHandler.OnEvent(KeyValuePair`2 evnt, DiagnosticListener diagnosticListener)'
```

**Comment by cijothomas** [comment]
Thanks for reporting.
Yes I can see that the code is not doing null checks. Though not sure which line exactly threw exception.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/Shared/Implementation/AzureSdk/AzureSdkDiag
nosticsEventHandler.cs#L82

**Comment by NoahStahl** [comment]
Thanks for confirming, yes it does appear to lack proper null checking. Is there any more information I can provide or is it assignable for fix?

**Comment by cijothomas** [comment]
If you can share a snippet of code making Cosmos DB calls, and the exact version of Cosmos client nuget, that would help. But only if this is very easy for you to get.

**Comment by NoahStahl** [comment]
Sure, I'm using [v4 preview 3](https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/4.0.0-preview3) of the Cosmos SDK.

An example call where AI exception seems to throw:

```
IAsyncEnumerable<Response> responseIterator = cosmosContainer.GetItemQueryStreamIterator(
    query,
    continuationToken: resolvedContinuationToken,
    requestOptions: new QueryRequestOptions()
    {
        PartitionKey = new PartitionKey(partitionKey),
        MaxItemCount = pageSize
    });

await foreach (Response response in responseIterator)
{
// Process response...
```

Hopefully it's just a matter of null checks, but maybe the Cosmos team could be tipped off as well if the preview SDK isn't including tracing data as expected. Thanks!

**Comment by cijothomas** [comment]
Thanks. Will get to this after our current stable SDK release.
