### ISSUE TITLE
Inconsistent implementation of AddApplicationInsightsLoggerProvider in net46 compared to netstandard2

### ISSUE THREAD

**Issue by johnib** [microsoft/ApplicationInsights-dotnet#1742]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: 2.13.1
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): NET461
* Hosting Info (IIS/Azure WebApps/etc): console app
* Platform and OS version: Windows 10

If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

**Steps to reproduce.**
Describe exactly how to reproduce the error. Include a code sample if applicable.

**What is the expected behavior?**
What did you expect to see?

I expect that the following code will also add AI logger provider:

```CSHarp
.ConfigureServices(services => services
    .AddApplicationInsightsTelemetry(options =>
    {
        options.ConnectionString = _settings.ApplicationInsightsConnectionString;
    })
```

**What is the actual behavior?**
What did you see instead?
ILogger traces are not sent to AI, only dependency/requests items do.

**Additional context.**

It seems like for the same nuget version (2.13.1), the net46 DLL has no implementation for `ApplicationInsightsExtensions.AddApplicationInsightsTelemetry.AddApplicationInsightsLoggerProvider`, while in the netstandard2 DLL it has.

Is this expected? I hope not.
Can you please drive a fix for this in the next version? I see there's a beta version available, which suffers from the same inconsistency.

**Comment by cijothomas** [comment]
This is a known limitation. https://github.com/microsoft/ApplicationInsights-dotnet/issues/1312
Apps targeting .NET Framework or older .NET Core (1.0, 1.1), will not have the new logging provider. They remain on the old, now obsolete logging provider.
There aren't much docs on the old provider either.

https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#migrate-from-the-old-applicationinsightsloggerprovider

There are plans to support the new provider for .NET Framework as well, and an active PR in that direction. We haven't been able to prioritize it yet, so I cannot guarantee it'll be in the next version.

**Comment by cijothomas** [comment]
@johnib Someone in our team is looking at this and we expect to fix this before next version.

**Comment by cijothomas** [comment]
This is fixed, and will be available in the upcoming beta5 (~1-2 days), and stable coming in ~2 weeks
