### ISSUE TITLE
Flush Enhancements

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [microsoft/ApplicationInsights-dotnet#1743]
## Issues with flush

Telemetry items are not send immediately, items are batched and flushed by SDK at fixed intervals (default is 30 secs) or whenever buffer is full (default is 500 items). If an application exits right after calling `Track` methods, telemetry may not be sent. To avoid telemetry loss during application shutdown, recommendation is to call `Flush` before app exit and introduce some delay for the `Flush` call to complete. The exact amount of delay isn't predictable and depends on factors like how many items or Transmission instances are in memory, how many are on disk, how many are being transmitted to the back end, and whether the channel is in the middle of exponential back-off scenarios. `Flush` method doesn't return success or failure. `Flush` functionality differs with two built-in channels and following is the difference. 

Sl.No | InMemoryChannel | ServerTelemetryChannel |
| ------------- | ------------- | ------------- |
| 1. | Flush method is synchronous  | Flush method is **not** synchronous |
| 2. | Flush returns once telemetry is sent  | Flush returns once telemetry is queued to Sender/Buffer/Storage queue  |
| 3. | OnAppExit: **No sleep/delay** is required after calling Flush  | 3.	OnAppExit: **Delay is required** after Flush so that telemetries in the queue can be sent by background tasks  |

>**Note:** Ideally, `Flush` method should be used in the shutdown activity of an application.

**Related Issues:** #407 #482 

#### InMemoryChannel
```
// Onboarded with https://www.nuget.org/packages/Microsoft.ApplicationInsights/
class Program
{
    static void Main(string[] args)
    {
        TelemetryConfiguration configuration = TelemetryConfiguration.CreateDefault();
        configuration.InstrumentationKey = "IKEY";
        var telemetryClient = new TelemetryClient(configuration);
        telemetryClient.TrackTrace("Hello World!");

        // before exit, flush the remaining data
        telemetryClient.Flush();
    }
}
```

#### ServerTelemetryChannel
```
// Onboarded with https://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer/
class Program
{
    static void Main(string[] args)
    {
        TelemetryConfiguration configuration = TelemetryConfiguration.CreateDefault();
        configuration.InstrumentationKey = "IKEY";
        var telemetryClient = new TelemetryClient(configuration);
        telemetryClient.TrackTrace("Hello World!");

        // before exit, flush the remaining data
        telemetryClient.Flush();

        // flush is not synchronous so wait for sometime
        Task.Delay(5000).Wait();
    }
}
```
## Proposal
Add **asynchronous** `Flush` method with following capabilities 
- Wait until all telemetry items are sent to server
- During network outages or high telemetry volumes, move telemetry items from sender, buffer to local disk
- Allow caller to decide when to cancel the `Flush` method through `CancellationToken` 
- Indicate flush is **success** or **failure**. Return success indicating that telemetry items are sent either to server or local storage.

```
Task<bool> FlushAsync(CancellationToken cancellationToken);
```

**Comment by XiaofuHuang** [comment]
Hi, I'm using `telemetryClient.Flush();` in Azure function. I found that if the waiting time value is set too small, some items will be lost. I am looking forward to this new feature. Will it be available for Azure Function in the situation which one job is tracking new traces and another job call FlushAsync()?

**Comment by cijothomas** [comment]
@XiaofuHuang What is the reason why you are calling Flush() in Functions? Flush is manually required only if the app/function is about to be shut down.

**Comment by XiaofuHuang** [comment]
> @XiaofuHuang What is the reason why you are calling Flush() in Functions? Flush is manually required only if the app/function is about to be shut down.

Because Azure Function is serverless and automatically scales based on trigger invocations, I don't know when it is actually shut down. Now I call Flush() after each execution to avoid data lost.

Is there any suggestion to avoid data lost in Azure Function?

**Comment by cijothomas** [comment]
I am not sure if calling Flush() for each execution is very efficient. 
Functions shutdown - this is something we need to understand from Functions team. If there is any event which can be subscribed on shutdown, and from which flush can be called.

**Comment by cijothomas** [comment]
@brettsam Can you comment on how Functions handle shutdown? Is an instance shutdown after few seconds on inactivity? Any events to subscribe to, so users can show an instance is being shutdown?

**Comment by brettsam** [comment]
We dispose all services on shutdown and use this to flush, but as pointed about above -- this isn't 100% reliable as we don't know when the flush is complete.

This is where we flush today (see note on the reliability): https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ApplicationInsightsLoggerProvider.cs#L37-L41

**Comment by cijothomas** [comment]
Thanks. Since Azure Functions itself is doing Flush() on shutdown, I'd recommend users to now use Flush on their own. @XiaofuHuang do you have any other question?

Once this new API is shipped, Functions can make use of it to do await FlushAsync(token), and avoid using unknown .Sleep()
This API is likely to be shipped in 2.15 version of SDK, and it typically take couple weeks before its made available in Functions.

**Comment by XiaofuHuang** [comment]
Thank you for your reply, this information is very useful to me.

**Comment by fazhong-ms** [comment]
Hi, @cijothomas , I'm also interested in "FlushAsync". Is there any plan about in which version and when will you release this feature?
