### ISSUE TITLE
Manually tracked exception is not correlated to other request/metrics

### ISSUE THREAD

**Issue by ilmax** [microsoft/ApplicationInsights-dotnet#1745]
I have an asp.net core 3.1 application running in a windows app service on azure and I'm using the [track exception](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#trackexception) feature on the telemetry client to track a custom exception, the application can cope with it and carry on, but I still want to log this exception and have it available in the application insights.

Following the documentation linked above, I'm injecting a `TelemetryClient` and using the `TrackException` method, the data is correctly sent to application insights and it's available there but it's a standalone exception and doesn't take part to the end to end transaction, looking into the data that get stored, I can see that the `operation_id` field in the `exceptions` table is indeed empty. Digging a bit into the issue, I've found the injected `TelemetryClient` has a lot of properties not initialized e.g. the `OperationContext` have all the properties set to null.

Is this the expected behavior? Because I was expecting to be able to just track custom events and have them take part in the end to end transaction automatically.

P.S. application insights is registered via the `services.AddApplicationInsightsTelemetry()` and other than one telemetry initializer and some telemetry filter, my setup is pretty much standard.

Thanks

**Comment by rajkumar-rangaraj** [comment]
We could not recreate an issue with SDK 2.13.1. Did you follow instructions [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#how-can-i-track-telemetry-thats-not-automatically-collected) to perform constructor injection 

Following is the trace from my machine, where manual track exceptions are correlated with automatically tracked request.

```
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.putinstrumentationkeyhere.Exception","time":"2020-03-25T16:02:33.5957166Z","iKey":"putinstrumentationkeyhere","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"cloudroleinstance","ai.user.id":"p33je","ai.operation.id":"303b9f5b7bd7854db0410ce664a271f5","ai.operation.parentId":"edafff1ba1638440","ai.operation.name":"GET Home/Index","ai.location.ip":"::1","ai.internal.sdkVersion":"dotnetc:2.13.1-12554","ai.internal.nodeName":"nodeName"},"data":{"baseType":"ExceptionData","baseData":{"ver":2,"exceptions":[{"id":5024928,"outerId":0,"typeName":"System.NullReferenceException","message":"Object reference not set to an instance of an object.","hasFullStack":true}],"properties":{"AspNetCoreEnvironment":"Development","DeveloperMode":"true"}}}}

Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.putinstrumentationkeyhere.Request","time":"2020-03-25T16:02:28.5522301Z","iKey":"putinstrumentationkeyhere","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"cloudroleinstance","ai.user.id":"p33je","ai.operation.id":"303b9f5b7bd7854db0410ce664a271f5","ai.operation.name":"GET Home/Index","ai.location.ip":"::1","ai.internal.sdkVersion":"aspnet5c:2.13.1","ai.internal.nodeName":"nodeName"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"edafff1ba1638440","name":"GET Home/Index","duration":"00:01:10.2100707","success":true,"responseCode":"200","url":"https://localhost:44338/","properties":{"AspNetCoreEnvironment":"Development","_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.1')","DeveloperMode":"true"}}}}
```
Manual track exception will not correlate if it called from newly created telemetry client instead of injection. If you are still able to recreate an issue, please share a repro for investigation.

**Comment by ilmax** [comment]
Yes, I'm doing proper injection of the `TelemetryClient`, since the behavior should be the one I was expecting, I will try to di deeper and come back with additional info/repro sample

**Comment by cijothomas** [comment]
Just to clarify:
The injected telemetryClient instance will not have context fields populated. The contexts are populated on the individual telemetry items, either by the auto-collection modules, or by one of the telemetry initializers.
The TelemetryClient.TelemetryContext is a like a "helper" method - anything added to telemetryclient's context will be simply copy-pasted to every item tracked with that client. The auto-injected telemetryclient dont have any context in it - its by design.

**Comment by cijothomas** [comment]
@ilmax Where is your TrackException call made? is it done inside same context as the incoming request? A code-snippet would help us investigate more.

**Comment by ilmax** [comment]
@cijothomas thanks for the clarification, the app is an aspnet core web application and I'm using it in conjunction with MediatR so the dependency is injected in the request handler, tomorrow CET time I will investigate more because it feels a bit weird. Any tip on where to focus first?

**Comment by cijothomas** [comment]
If mediatR is using some pub-sub mechanism, then its quite likely that the request context is lost when TrackException is called. You'll be manually required to propogate and populate operationid, operationparentid on the exception telemetry. 

There aren't a lot of doc on this but some:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#data-model-for-telemetry-correlation
https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking

**Comment by ilmax** [comment]
This was working as expected, closing
