### ISSUE TITLE
RichPayloadEventSource is emitting dictionaries to eventSource which ends up being serialized in a possibly non-intuitive way

### ISSUE THREAD

**Issue by moagarMS** [microsoft/ApplicationInsights-dotnet#1747]
I am running ApplicationInsights 2.10.0 with runtime version v4.0.30319. My project is using .NET 4.6 on Windows 10 machines.

In our team, we are using application insights to log events to partner's application insights accounts; however, we also want to log the same event to our internal telemetry store.  For that I was trying to use the ETW events with the provider Microsoft-ApplicationInsights-Data to configure our Monitoring Agent and push it to our telemetry store.

The Monitoring Agent was able to listen to the ETW event, however the event itself is serialized to a different schema than what ends up in APplication Insights. Every property on the TraceTelemetry.MessageData.Properties ends up being serialized into it's own column. The same thing happens for tags (both of them are dictionaries).

I expected that the Properties dictionary is emitted as json formatted as in application insights. 

But instead it's flattened to this:
properties_Count, properties_0_Key, properties_0_Value, ... and so on.

PS: My TraceTelemetry events are ending up in Microsoft-ApplicationInsights-Data/Message Channel, rather then AppTraces channel as per the source code here.

**Comment by cijothomas** [comment]
Only consumers of Microsoft-ApplicationInsights-Data are Visual Studio debugger and ServiceProfiler. I believe the schema is agreed between the only known consumers.

As an alternate, you can implement a new  `ITelemetryChannel` to route events to your internal store. There exists internal only implements inside Microsoft for other backends like Geneva etc.

+ @xiaomi7732 who works in ServiceProfiler team who consumes these events.

**Comment by moagarMS** [comment]
I see. Then we should not really listen to Microsoft-ApplicationInsights-Data if we want to log to Geneva?

Also, how the other consumers could agree on the schema? are the listeners wrapping the dictionary back up?

**Comment by cijothomas** [comment]
Its best to ask other consumers how they handle the data from it. I am not very sure on that.

If your goal is to send same data to multiple ikeys/backend, the use TelemetrySinks approach. Its not very publicly documented, but internal sites should have examples on using it to fork data to multiple places, including Geneva.
