### ISSUE TITLE
Failed to resolve TelemetryConfiguration with Abstract class

### ISSUE THREAD

**Issue by kunwarshesh** [microsoft/ApplicationInsights-dotnet#1748]
Hi,

I'm getting below exception while starting the service. When I removed the AppInsights code, its working without any exception. In addition, when I changed BaseEventHandler class from abstract to normal class, there was no axception. <b>Seems some issue with AppInsights and Abstract class.</b>

<b>Source code in Startup to integrate AppInsights:</b>
<b><i>.Net Core 3.1,  C#</i></b>
services.AddApplicationInsightsTelemetry(this.Configuration["ApplicationInsights:InstrumentationKey"]);
services.AddApplicationInsightsKubernetesEnricher();

<b>Exception:</b>

> {"Timestamp":"2020-03-26T11:37:11.4876202-05:00","Level":"Warning","MessageTemplate":"Failed to resolve TelemetryConfiguration.","Exception":"Autofac.Core.DependencyResolutionException: An exception was thrown while activating ?:Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration -> Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptions.
>  ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(System.Collections.Generic.IEnumerable1[Microsoft.Extensions.Options.IConfigureOptions1[Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration]])' on type 'TelemetryConfigurationOptions'.
>  ---> System.ArgumentException: Cannot instantiate implementation type 'Api.Infra.Handlers.BaseEventHandler' for service type 'Api.Infra.Handlers.BaseEventHandler'.
>  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
>  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(IEnumerable1 descriptors)
>  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine..ctor(IEnumerable1 serviceDescriptors, IServiceProviderEngineCallback callback)
>  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine..ctor(IEnumerable1 serviceDescriptors, IServiceProviderEngineCallback callback)
>  at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable1 serviceDescriptors, ServiceProviderOptions options)
>  at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
>  at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services)
>  at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.BuildServiceBases(IServiceCollection serviceCollection, Action1 applyOptions)
>  at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.ConfigureKubernetesTelemetryInitializer(IServiceCollection serviceCollection, Func1 detectKubernetes, IKubernetesServiceCollectionBuilder kubernetesServiceCollectionBuilder, Action1 applyOptions)
>  at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.<>c__DisplayClass4_0.<AddApplicationInsightsKubernetesEnricher>b__0(TelemetryConfiguration config)
>  at Microsoft.Extensions.Options.ConfigureNamedOptions1.Configure(String name, TOptions options)
>  at Microsoft.Extensions.Options.ConfigureNamedOptions1.Configure(TOptions options)
>  at Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptions..ctor(IEnumerable1 configureOptions)
>  at lambda_method(Closure , Object[] )
>  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
>  --- End of inner exception stack trace ---
>  at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
>  at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable1 parameters)
>  at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable1 parameters)
>  --- End of inner exception stack trace ---
>  at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable1 parameters)
>  at Autofac.Core.Resolving.InstanceLookup.<Execute>b__8_0()
>  at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func1 creator)
>  at Autofac.Core.Resolving.InstanceLookup.Execute()
>  at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
>  at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
>  at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
>  at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
>  at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable1 parameters, Object& instance)
>  at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable1 parameters)
>  at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
>  at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
>  at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
>  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>  at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass2_0.b__0(IApplicationBuilder app)","Properties":{"SourceContext":"Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter","Application":"Service","Environment":"Development"}}

**Comment by cijothomas** [comment]
`AddApplicationInsightsKubernetesEnricher` is not shipped from this repo, and may require opening an issue in the corresponding repo.

Can you remove `AddApplicationInsightsKubernetesEnricher` and see if this repros ? We'd like to isolate the issue as much as possible. 

Also wondering if this has something to do with using non-built-in DI container - Autofac? There are no unit test/func tests validating against this :(

**Comment by kunwarshesh** [comment]
Thanks @cijothomas for quick reply. I'm having strange issue. When I remove either of the AddApplicationInsightsTelemetry or AddApplicationInsightsKubernetesEnricher, it's not throwing any exception. But together it's throwing.

I'm using:
Microsoft.ApplicationInsights.AspNetCore 2.13.1
Microsoft.ApplicationInsights.Kubernetes 1.1.1

**Comment by cijothomas** [comment]
Possibly some conflicts or circular dependency..
@xiaomi7732 Have you seen similar issues?
