### ISSUE TITLE
Duplicate telemetry occasionally sent

### ISSUE THREAD

**Issue by EvanMulawski** [microsoft/ApplicationInsights-dotnet#1749]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: dotnetc:2.11.0-21474 and dotnetc:2.13.1-12554
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): netcoreapp3.1
* Hosting Info (IIS/Azure WebApps/etc): Worker Service
* Platform and OS version: Windows Server 2019

**Steps to reproduce.**
Unknown. Does not occur with a running netcoreapp3.0 service using SDK web:2.10.0-32157.

**What is the expected behavior?**
Telemetry is not duplicated.

**What is the actual behavior?**
Telemetry is occasionally duplicated.

**Additional context.**
Telemetry is occasionally duplicated, visible when searching and querying logs and metrics in the portal. In code, an operation is started using `RequestTelemetry` and then stopped. Dependency collection is automatic. Duplication affects custom event telemetry as well. The duplicates share the same ID and timestamp.

Sample operation ID: `fd2d845197a21749a3708ea92433f374`
Instrumentation key prefix: `5118f031`

![image](https://user-images.githubusercontent.com/1044791/77678108-100fb180-6f67-11ea-8fe2-8a69c2eb0bbe.png)

**Comment by cijothomas** [comment]
Can you post query results with itemId, and ingestion_time() as well for the items which are duplicated?
If they have same itemid, with different ingestion_time(), the duplication occurred in the backend, not in sdk.
If they have differeent itemid, its likely from SDK itself. (like a retry after timeout).

**Comment by EvanMulawski** [comment]
Here is one set:

![image](https://user-images.githubusercontent.com/1044791/77702011-e6b64c00-6f8d-11ea-9532-1379a12cb864.png)

**Comment by CarpeTeknus** [comment]
I'm getting the same behavior with perf counters:
![image](https://user-images.githubusercontent.com/3239280/78257594-12728e00-74c8-11ea-900d-ae3ad2fa8aab.png)

**Comment by cijothomas** [comment]
@CarpeTeknus Can you also verify that the duplicate is occurring at SDK side, using a query similar to the one used by Evan?
In his case, the itemids are different pointing to duplication occurring at SDK side. We'll need to investigate this in detail, right now I don't have free cycles to jump to this. If this becomes more common - then we'd reprioritize this investigation. Hope all understand.

**Comment by CarpeTeknus** [comment]
They don't have the same id, and the structure is different, which leads me to think there are more than one telemetry processor instance added when calling services.AddApplicationInsightsTelemetry:
![image](https://user-images.githubusercontent.com/3239280/79620814-309ed780-80df-11ea-8f12-581e2f9ed6b8.png)

This is the debug window capture with 2 sets of perf counters duplicated, as you can see one set has a different name (extra .Dev):
![image](https://user-images.githubusercontent.com/3239280/79620942-a60aa800-80df-11ea-8a12-31cd157b684d.png)
