### ISSUE TITLE
Add sourcelink support for core

### ISSUE THREAD

**Issue by ssa3512** [microsoft/ApplicationInsights-dotnet#1760]
I am attempting to troubleshoot issues with custom telemetry correlation and it is difficult to step into the app insights library to identify what is going wrong. It would be helpful if the core library (Microsoft.ApplicationInsights) supported sourcelink. This is already supported on the netcore logging library here: https://github.com/microsoft/ApplicationInsights-dotnet/blob/35176da5645f1f65af3ff576b54bc0aa5cf7018a/LOGGING/src/ILogger/ILogger.csproj#L50-L53

**Comment by TimothyMothra** [comment]
note to self: estimate the work, see if we can take this in 2.15

**Comment by TimothyMothra** [comment]
We'll need to follow this general guidance to onboard:
https://github.com/dotnet/sourcelink#using-source-link-in-net-projects

**Comment by TimothyMothra** [comment]
SourceLink has been turned on and will be available in our next 2.15 beta release. :)
