### ISSUE TITLE
Fix issue around checking whether the Activity type is available in ActivityExtensions.

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-dotnet#1761]
There are two issues in the **Microsoft.ApplicationInsights.ActivityExtensions** class: a correctness bug around concurrency, and a potential issue around reflection. The referenced PR addresses both problems (https://github.com/microsoft/ApplicationInsights-dotnet/pull/1762).

Details:

1) The TryRun/Initialize code has a concurrency bug where `isInitialized` is assigned a value before `isAvailable`. The former is assigned a value inside the [Initialize() method](https://github.com/microsoft/ApplicationInsights-dotnet/blob/a185e8fb05ce914af48eff8739e63b5918b50f03/BASE/src/Microsoft.ApplicationInsights/ActivityExtensions.cs#L71) and the later only after that method [returns](https://github.com/microsoft/ApplicationInsights-dotnet/blob/a185e8fb05ce914af48eff8739e63b5918b50f03/BASE/src/Microsoft.ApplicationInsights/ActivityExtensions.cs#L26). As a result, the default value of `isAvailable` may be used (`false`) where `true` would have been appropriate.

2) The `Initialize()` method uses AssemblyLoad(..) to [see if the Activity type is available](https://github.com/microsoft/ApplicationInsights-dotnet/blob/a185e8fb05ce914af48eff8739e63b5918b50f03/BASE/src/Microsoft.ApplicationInsights/ActivityExtensions.cs#L55). This attempts to load a specific assembly with a specific version, and relies on the assumption that if it successes, then the required type is available. This makes an unvalidated assumption about the location of that type. The assumption may be incorrect: If the hosting environment performed non-trivial type redirection; or in the future, if the type should move. Instead of loading the assembly, we can try loading the type directly. This will follow any potential type redirects and avoid any problems related to explicit assembly loads.

**Comment by TimothyMothra** [comment]
close because we're removing this feature
