### ISSUE TITLE
[Question] Application Map in Application Insights shows Question Marks when Using Azure Service Bus Topics

### ISSUE THREAD

**Issue by ZhimaoLin** [microsoft/ApplicationInsights-dotnet#1764]
# Application Map shows a question mark on the edge when Backend2 and Backend3 pull messages from two different subscriptions of Azure Service Bus Topics

## Infrastructure
I have 3 .Net Core 3.1 back-ends: Backend1, Backend2, and Backend3. Backend1 sends messages through Azure Service Bus Topics. Backend2 and Backend3 receive messages from Subscription1 and Subscription2 respectively. 

## Question
When there is only Backend3 receiving messages, Application Map can form an edge between Backend1 and Backend3 with the correct number of calls. 
![image-20200403-221706](https://user-images.githubusercontent.com/22060375/78581703-77dcbc80-77f1-11ea-90ac-15b5d46ce449.png)

When Backend2 and Backend3 receive messages, Application Map can form two edges between Backend1 and Backend2 and between Backend1 and Backend3. However, there is a question mark on the edge.
![image-20200403-203424](https://user-images.githubusercontent.com/22060375/78581955-d30eaf00-77f1-11ea-8117-a05f14bb3dfa.png)

### Here are my questions: 
* What does the question mark on the edge mean?
* Why there is no edge between Backend1 and Service Bus?
* Why there is a question mark? I have checked the Log Analytics on Application Insights, and the `id`, `operation_Id`, and `operation_Parent_Id` are logged correctly for `request` and `dependencies` objects. So, Application Map should display the number of calls on the edge. Is this a bug of `Microsoft.Azure.ServiceBus 4.1.2` or `Microsoft.ApplicationInsights 2.13.1`?
![image](https://user-images.githubusercontent.com/22060375/78582529-a4450880-77f2-11ea-9f73-65b4eaaad81d.png)

## Environment:
 - Name and version of the Library package used: Microsoft.Azure.ServiceBus 4.1.2 and Microsoft.ApplicationInsights 2.13.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .Net Core 3.1
 - IDE and version : Visual Studio 2019 Professional 16.5.2

**Comment by TimothyMothra** [comment]
note to self: reach out to AppMap devs

**Comment by madeleinefletcher** [comment]
Hello!

The question-mark edge appears on Application Map if an app sends requests to a single host name that are received by multiple services. The reason we can’t show metrics for the edge has to do with how we compute metrics on the map.

To compute the edge metrics, we measure calls by host name, not by receiving service. Computing metrics by receiving service would require a query that finds each individual id/parentId match between the two services, which is too computationally intensive. So instead, we compute edge metrics by host name, which is much faster. The downside is that if there are multiple services receiving call via the same host name, we can’t show exactly how many calls went to each receiving service. This is when we show the question mark edge.

We’re aware that this is not the best way to represent queues, and we’re working on adding support for better queue visualizations in the map, so this visualization will eventually be improved.

In the meantime, understand that this is a weakness of the map itself, not anything wrong with your instrumentation.

**Comment by deyanp** [comment]
@madeleinefletcher , I am experiencing the same issue, question marks on all lines from Api Management to the individual microservices (hosted in AKS). Initially all microservices were published on the same hostname with a different path. I changed this so that each microservice has its own hostname (CNAME-d to the same IP behind), but the question marks on the lines between Api Management and the microservices are still there ... What can I do to remove them and get the number of calls etc per edge?

**Comment by tgrandegger** [comment]
@madeleinefletcher: I have the same situation in a customer-tenant, do you have information, if this (convenience-) issue is on some roadmap. Perhaps it is too small a problem, but it would be sooo convenient. 

best regards,
Thomas
