### ISSUE TITLE
Remove NetStandard 1.x

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1767]
Parent: #1160 

Net framework compatibility: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Note that all Test projects should target NetCore2.1 and NetCore3.1. #1769 

#### Remove
- NetStandard 1.1
- NetStandard 1.3
- NetStandard 1.6

#### Replace With
- NetStandard 2.0
- NetStandard 2.1

#### Affected Projects (11 of 17)
- BASE
    - Microsoft.ApplicationInsights
    - ServerTelemetryChannel
- WEB
    - DependencyCollector
    - PerformanceCollector
    - WindowsServer
- LOGGING
    - DiagnosticSourceListener
    - EventSourceListener
    - Log4NetAppender
    - NLogTarget
    - TraceListener
- NETCORE
    - Microsoft.ApplicationInsights.AspNetCore

#### Affected Builds
- Gated build (ADO)
- Linux builds (yml)

#### Action Plan
- First, remove TargetFrameworks from Product. This immediately stops compiling the NetStandard 1.x **Done**
- Second, remove TargetFrameworks from Tests.  **Done**
- Third, cleanup code. Remove preprocessors and delete code forks. It's important to do this one project at a time so we can thoroughly review. (this can be done at any time by anyone on the team)
    - **PerformanceCollector** is fractured into 6 different shared projects. (NetFull, NetStandard, NetStandard.Stubs, NetStandard16.Stubs, NetStandard20, NetStandard20Net45). After deleting NetStandard1.x, this needs to be refactored into only 2 shared projects (Perf.Shared.NetFull, Perf.Shared.NetStandard).

#### Risks
- I noticed right away that some projects currently ONLY compile to netstandard 1.x.

**Comment by TimothyMothra** [comment]
@eddynaka, i merged your first PR.
When you start working again, please work on PerformanceCollector by itself so we can thoroughly review. 
Thanks :)

**Comment by TimothyMothra** [comment]
@eddynaka Next, can you remove the #IF NETCOREAPP1 code branches? These are mostly in our test classes

**Comment by eddynaka** [comment]
Sure!
