### ISSUE TITLE
Using both Worker Service and ASP.NET Core SDK's in the same app?

### ISSUE THREAD

**Issue by EvanMulawski** [microsoft/ApplicationInsights-dotnet#1768]
**Describe your environment.**
Describe any aspect of your environment relevant to the question:
* SDK version: 2.13.1
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): netcoreapp3.1
* Hosting Info (IIS/Azure WebApps/etc): none (VS/debug)
* Platform and OS version: Windows 10 1809

**What are you trying to achieve?**
Host a worker service with an ASP.NET Core web app.

**Additional context.**
Currently, it appears as though you cannot use both `AddApplicationInsightsTelemetryWorkerService()` and `AddApplicationInsightsTelemetry()`. However, adding the ASP.NET Core services directly still does not result in tracking HTTP requests. How can this be achieved?

Changes to default ASP.NET Core Web Application template:

Program.cs
```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureServices(services =>
        {
            // added
            services.AddApplicationInsightsTelemetryWorkerService();
        })
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```

Startup.cs
```csharp
public void ConfigureServices(IServiceCollection services)
{
    // added
    services.AddApplicationInsightsTelemetry();

    services.AddControllers();
}
```

When making a HTTP request, no telemetry is picked up by VS when using both.

**Comment by cijothomas** [comment]
Don't use WorkerService SDK here. Just use the applicationinsights.aspnetcore sdk, and enable it with `    services.AddApplicationInsightsTelemetry();`.

**Comment by EvanMulawski** [comment]
Thanks @cijothomas - that worked. I had a custom package calling and setting up the worker service SDK, but adding that to a web app caused the issue. I removed the AI SDK reference from my custom package and the app is now responsible for configuring the one it needs.

**Comment by cijothomas** [comment]
similar: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1732
