### ISSUE TITLE
TelemetryClient.Context.Operation.Id returns null

### ISSUE THREAD

**Issue by mphidev** [microsoft/ApplicationInsights-dotnet#1770]
I am trying to retrieve the OperationId. I am successfully able to retrieve it with `Request.Headers["traceparent"]`. I was also hoping that the TelemetryClient's Context would also know of the OperationId. However, when I use `TelemetryClient.Context.Operation.Id`, the Context knows nothing about the Operation and returns null.

My environment is
* SDK version: 2.14.0-beta5
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): Standard 2.0
* Hosting Info (IIS/Azure WebApps/etc): IIS
* Platform and OS version: Windows 10

**Comment by cijothomas** [comment]
TelemetryClient's context won't have operation id. OperationID changes per operation and  it'll be populated on individual `ITelemetry` items only.

**Comment by mphidev** [comment]
What do you mean by _OperationId changes per operation_, if this request was triggered by another process, shouldn't this request all be under the same operation, and sharing the same operationID?

**Comment by cijothomas** [comment]
OperationID changes per operation - i meant for a single operation, all telemetry will have same id. Every new operation gets a new id.

**Comment by pramadhav** [comment]
Suppose the client or a microservice wants to send a particular operation ID (say some GUID with custom naming convention), when I try to set it using Operation ID and expect it to appear in AI with the Custom operation, it is showing differently. Operation ID is multiple IDs. Any ideas on how to achieve this?

**Comment by cijothomas** [comment]
> Suppose the client or a microservice wants to send a particular operation ID (say some GUID with custom naming convention), when I try to set it using Operation ID (telemetry.Context.Operation.Id) and expect it to appear in AI with the Custom operation, it is showing differently. Operation ID is multiple IDs. Any ideas on how to achieve this?

I am not clear on what you are trying to achieve. For most customers, operation id is set automatically on telemetry based on the Activity.Current. If you give more specifics on what you are trying to achieve, we can try to help.

**Comment by pramadhav** [comment]
sorry, let me be clear.
Yes, I agree that Operation ID is set automatically. For example, Operation ID: 73943f90118e894cbe14e66bf7bc8ad0. This is an ID and all related traces, requests, exceptions are grouped under this in AI, which the PROD support teams can see. No issues with that.

My questions is how about if an app wants to set a custom operation ID? For example, "password_reset_GUID" on click of a button "Reset Password" button. where GUID is a unique random identifier. I would like to track all the telemetry related to this with a user-friendly operation ID.  This is to help PROD support teams to quickly troubleshoot if any issues. So, I tried to use Itelemetry and set it using Context.Operation.Id with a custom initializer implementation for ITelemetryInitializer. I am not successful yet sending this Custom operation ID. Hope, I am clear on this.

**Comment by cijothomas** [comment]
Most likely you are better off leaving it to application insights to populate operationid, and manually set operationname to "passwordreset".

But that doesn't mean you cannot set your own ids, and it should work.  Please describe the exact steps you did, and what was the expected outcome and actual outcome. I'd suggest to open a new issue, as this issue was about TelemetryClient not having operationid populated.

**Comment by cijothomas** [comment]
Closing as the original question is answered - parsed correlationids are stamped on to individual ITelemetry items, and not on TelemetryClient. TelemetryClient is used to track any number of telemetry, each with separate or same operationid

**Comment by Duke4848** [comment]
@cijothomas Ok but how to get to these `ITelemetry` items through `TelemetryClient`.
I too have problem when I want to log operationId I get null.

**Comment by cijothomas** [comment]
@Duke4848 Can you open a new issue describing your question? (with some example snippets, so its easier to understand what you are trying to achieve)
