### ISSUE TITLE
Application Insight not tracking Postgres SQL quries using Entity Framework Core

### ISSUE THREAD

**Issue by mustakimali** [microsoft/ApplicationInsights-dotnet#1771]
ASP.NET Core 3.1 app running in docker and deployed in kubernetes cluster.

* SDK version: 
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): .NET Core 3.1
* Hosting Info (IIS/Azure WebApps/etc): Kestrel behind ngingx, Docker, Kubernetes
* Platform and OS version: Linux

**Project.csproj**
```xml
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.13.1" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.3" />
```

**Startup.cs**

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddApplicationInsightsTelemetry();
}
```

What did you expect to see?

SQL queries run by Entity Framework Core against Postgres database (hosted in AWS) are not being tracked by Application Insight.

I remember last time I used AppInsight was able to collect SQL Server queries and I expect it to do the same for Postgres as the ORM is still Entity Framework.

**Comment by cijothomas** [comment]
Dependencies are only collected if `System.Data.SqlClient` or `Microsoft.Data.SqlClient` is used.

There is no generic collection of dependencies from Entity Framework - EF itself is not instrumented, the instrumentation is only at SqlClient.

**Comment by mustakimali** [comment]
Ahh thanks for your response.

**Comment by carolineAgicap** [comment]
Hello cijothomas, 

> Dependencies are only collected if System.Data.SqlClient or Microsoft.Data.SqlClient is used.
> 
> There is no generic collection of dependencies from Entity Framework - EF itself is not instrumented, the instrumentation is only at SqlClient.

EF core uses `Microsoft.Data.SqlClient` so it should work though ? It is not showing is appinsight, did I miss a specific configuration ?

![image](https://user-images.githubusercontent.com/81687285/170046383-040ad0bd-a522-4c4c-8dc6-129cbcb00799.png)

**Comment by cijothomas** [comment]
@carolineAgicap Please open a new issue describing the problem you are experiencing, along with relevant config and code snippets, ideally a minimal repro app.
