### ISSUE TITLE
Help with designing a pipeline if it's not possible to directly upload to public Application Insights.

### ISSUE THREAD

**Issue by aluong** [microsoft/ApplicationInsights-dotnet#1772]
**Describe your environment.**
We are running our services in a locked down network, but there are only specific approved/whitelisted private IPs we can have our services called out or POST to.

* SDK version: latest
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file):  .Net Core

**What are you trying to achieve?**

I am looking for assistance with a design such that we move logs out of the locked down network into Application Insights.

Would the easiest path be to create a proxy service?

Essentially, create a custom `ServerTelemetry Channel` for the locked down service that `OnFlush` sends to a approved endpoint with all of messages. Then, that service (outside the locked down network) would just have its own `ServerTelemetry Channel` that I would populate to allow the normal upload mechanism in Application Insights to trigger.

**Additional context.**
There are two kinds of machines/services:

- One that is in a locked down network that can only talk to specific IP addresses.
- The others, outside the locked down network which can talk to the public internet.

**Comment by aluong** [comment]
I discovered the following: https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-endpoints, so I think another option is to use an actual proxy service such as HAProxy that the locked down service can forward all the Application Insights request through.

**Comment by cijothomas** [comment]
Instead of setting individual endpoints, you may use connectionstrings. https://docs.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string
