### ISSUE TITLE
Application Insight - Web Tests & Client Certificates

### ISSUE THREAD

**Issue by ShitalMehta** [Microsoft/ApplicationInsights-dotnet#179]
We @ Enterprise Commerce in Universal Store trying to use App Insight Monitoring and Web Tests in place of current implementation of Key Note. One requirement for us is to be able to Accept Client Certificates and perform some Web Tests.

From what we tried/learned, we can't have App Insight take our Client Certificate and use it when calling Target Application. 

Is this something we have currently OR something in pipeline?

Regards,
Shital Mehta
Enterprise Commerce

**Comment by SergeyKanzhelev** [comment]
@SoubhagyaDash, can you please comment on this?

**Comment by ShitalMehta** [comment]
Thanks Sergey,
If we have or get a solution around this, it will help us unify manority of our Telemetry into one common solution, that shall help Analytics/Forecasting a great deal. We shall wait for Soubhagya's response.

Regards,
 Shital Mehta
 Enterprise Commerce

**Comment by abaranch** [comment]
Client certificate auth is not supported. You can leave user voice request here: http://visualstudio.uservoice.com/forums/121579-visual-studio/category/77108-application-insights
