### ISSUE TITLE
Need to update to System.Diagnostics.DiagnosticSource 5.0

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1790]
I got confirmation that a new release of DiagnosticSource is coming in mid-May.

- fix for facade issue is already merged: https://github.com/dotnet/corefx/pull/42901
- next version will be v4.7.1: https://github.com/dotnet/corefx/pull/42901/files#diff-af9c55fe5b946aaf0416f10e9fd85f19

This is expected to fully resolve our outstanding issues with System.Memory:
- https://github.com/microsoft/ApplicationInsights-dotnet/issues/1707
- https://github.com/microsoft/ApplicationInsights-dotnet/pull/1751

#### TODO
- Review that all projects with a dependency on DiagnosticSource NEED this dependency.
    - Cijo told me that the only expected dependencies are: Base, DependencyCollector, AspNetCore, Web.
    - unknown: PerfCollector, WindowsnServer
- Take a dependency on System.Diagnostics.DiagnosticSource v4.7.1
    - Resolve breaking changes in our SDK
- Remove explicit dependency on System.Memory v4.5.4

#### Next Steps
- Need to understand exactly what changed in DiagnosticSource between 4.6 and 4.7
    - either myself or Cijo will follow up with either Sergey or dotnet owners

**Comment by TimothyMothra** [comment]
@cijothomas I need to schedule some time with you to investigate why the upgrade to DiagnosticSource v4.7.0 failed. If I remember correctly, several of our tests started failing so we abandoned this

**Comment by TimothyMothra** [comment]
Looks like dozens of tests fail associated with Activity and Operations. only Net45 and Net46 are affected.

**Comment by cijothomas** [comment]
We can close this issue now.
