### ISSUE TITLE
OperationId is the same for different operations

### ISSUE THREAD

**Issue by forik** [microsoft/ApplicationInsights-dotnet#1797]
**Describe your environment.**
Describe any aspect of your environment relevant to the question:
* SDK version: 2.13.1
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): netcoreapp3.1
* Hosting Info (IIS/Azure WebApps/etc): Azure IIS AppService
* Platform and OS version: Windows OS

**What are you trying to achieve?**
I have 4 microservices, one of them triggers an operation using a http call via IHttpClientFactory's HttpClient. My understanding was that each of such calls creates unique operationId which is then used for e2e tracing. After some debugging of AI and AspNetCore sources I noticed that actually value of Activity.RootId is being used for operationId (I compared values).

**Additional context.**
After setting IncludeScopes flag to true for Microsoft.Extensions.Logging.Console in the app that triggers execution flow I tried to track TraceId variable from logs in the other apps in my microservices environment, but all the traceIds I found in those apps was a RootId which is being used for all the operations.

As seen from the screenshots below there are way too many items for a single operationId.

End to end view (browser crashes frequently due to number of operations for a single operationId):
![e2e](https://user-images.githubusercontent.com/886162/79719084-61049280-82e6-11ea-8490-d95b8154aa1a.png)

Logs view:
<img width="371" alt="logs" src="https://user-images.githubusercontent.com/886162/79719110-6e218180-82e6-11ea-8f50-1c45513bed14.png">

**Comment by TimothyMothra** [comment]
We need a repro to investigate this issue

**Comment by forik** [comment]
> 
> 
> We need a repro to investigate this issue

One maybe important clarification: the app which is triggering a workflow using a different inctrumentationKey. Anyway, I'll try to provide a repro.

**Comment by cijothomas** [comment]
> > We need a repro to investigate this issue
> 
> One maybe important clarification: the app which is triggering a workflow is using a different inctrumentationKey. Anyway, I'll try to provide a repro.

Yes.  A repro will surely help.
Btw  - you are not doing anything in your code like Activity.DefaultIDFormat = Hierrarchical or anything like that, right?

In .Net Core 3.1, the runtime (httpclient, hosting layer etc) is distributed tracing aware by default, and application insights simply takes values from Activity.TraceID as OperationId. (if you are debugging yourself, Activity.TraceID is something to look for - it should be unique for each unique transaction)

**Comment by forik** [comment]
> Yes. A repro will surely help.
> Btw - you are not doing anything in your code like Activity.DefaultIDFormat = Hierrarchical or anything like that, right?

I explicitly set Activity.DefaultIDFormat = W3C. 

> In .Net Core 3.1, the runtime (httpclient, hosting layer etc) is distributed tracing aware by default, and application insights simply takes values from Activity.TraceID as OperationId. (if you are debugging yourself, Activity.TraceID is something to look for - it should be unique for each unique transaction)

I could have agreed with you, but I saw a value of Activity.RootId and the operationIds in AI portal to be the same.

**Comment by forik** [comment]
@TimothyMothra @cijothomas here's a repository with [repro](https://github.com/forik/ai-repro)

**Comment by cijothomas** [comment]
Took a very brief look - Are you customizing the HttpClient handler? 
related: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1434

**Comment by forik** [comment]
> Are you customizing the HttpClient handler?

Removed HttpClient customization and issue still persists in a websocket related code.

**Comment by cijothomas** [comment]
Don't think websockets are instrumented to collect telemetry from it. They may retain same operationid for as long as the connection is alive.

**Comment by cijothomas** [comment]
{System.Net.Http.DiagnosticsHandler} - This is where the instrumentation exists. Check your HttpClient instance and see if this handler is present. It'd be there by default, but when you customize, it should be retained.

**Comment by forik** [comment]
> Check your HttpClient instance and see if this handler is present. It'd be there by default, but when you customize, it should be retained.

Like I said, I removed any customization from HttpClient. The issue persists when httpClient is being used from a websocket handler middleware.

**Comment by forik** [comment]
Inside my websocker handler instead of injecting a httpClient I started to inject IServiceScopeFactory and every time I send a message to another service I resolve a client from new scope. Eventhough seems like a websocket connection preserves a correlation context and a TraceId remains the same on every call.

**Comment by cijothomas** [comment]
@forik There isn't anything for application insights to do here, as this would fall under unsupported scenario. There are plans to support WebSockets, but no fixed timeline.

**Comment by forik** [comment]
Closing as not related to AI.
