### ISSUE TITLE
Process Private bytes metric should not use PrivateMemorySize64

### ISSUE THREAD

**Issue by shirhatti** [microsoft/ApplicationInsights-dotnet#1802]
**Is your feature request related to a problem?**

The way .NET Core reports `Process.GetCurrentProcess().PrivateMemorySize64` of Windows is different from Linux. On Linux, we just return the VmData from `/proc/self/status`. 

This makes the `Private Process bytes` metric useless on Linux

**Describe the solution you'd like.**
This should be changed to report working set memory on Linux

**Describe alternatives you've considered.**
N/A

**Additional context.**

Unless I’m mistaken, it looks like there is some precedent for the accurate private memory. The AI Java SDK returns [heap + non-heap memory](https://github.com/microsoft/ApplicationInsights-Java/blob/40809cb6857231e572309a5901e1227305c27c1a/core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/ProcessMemoryPerformanceCounter.java#L50-L66) which I assume is closer to working set.

Attaching a screenshot to highlight how large the difference in these values is

![ai2](https://user-images.githubusercontent.com/4734691/79946118-ef872a00-8434-11ea-80f3-91a3063fa760.png)

**Comment by Leonardo-Ferreira** [comment]
I had such an issue, as reported on #2008.
The difference is that I was hosting my code on docker. After moving to AKS and using containerd as infra, the value reported got back to the expected behavior
