### ISSUE TITLE
Long running SQL dependencies show incorrect duration (seconds instead of minutes)

### ISSUE THREAD

**Issue by jawn** [microsoft/ApplicationInsights-dotnet#1803]
* SDK version: 2.13.1
* .NET runtime version (.NET Core): netcoreapp3.1
* Microsoft.Data.SqlClient: 1.1.2
* Hosting Info (IIS/Azure WebApps/etc): IIS
* Platform and OS version: Windows Server

**Steps to reproduce.**
Execute a long running SELECT query that takes 6 to 10 minutes.

**What is the expected behavior?**
Dependency has correct duration (6 to 10 *minutes*).

**What is the actual behavior?**
Dependency has incorrect duration, e.g. 4-6 *seconds*.
The parent request duration is correct.

![image](https://user-images.githubusercontent.com/1705112/79961133-8fb96f00-8486-11ea-8534-fc3b37a135d8.png)

**Additional context.**
Similar issue, but different actual behavior: #1385

**Comment by Alexander-Bartosh** [comment]
Just had a case:
The same query is executed multiple times. 
Some of the executions are throttled by Azure SQL and take about 53 seconds to complete.
Those executions are loggen in AI with duration of about 4 seconds.

@TimothyMothra 
What can be wrong here ? Can caching of data you have mentioned in   #1385 be affected by multiple executions of the query ? 
(There could have been an execution of the same query that took 4 seconds recently )

**Comment by jawn** [comment]
Is any action planned on this issue? While I am a fan of Application Insights, this bug makes it hard to recommend it for proactive production monitoring and analysis.

**Comment by wendlandreas** [comment]
Is there any update on this?
Still happening to me on dotnet 6.0.

**Comment by cijothomas** [comment]
Good chance this is same as https://github.com/open-telemetry/opentelemetry-dotnet/issues/1614
