### ISSUE TITLE
ApplicationInsights does not inherently read ApplicationInsightsServiceOptions from appsettings.json

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1806]
Currently, our SDK does NOT automatically read variables set in an appsettings.json file.

## Proposal

We need to either
- Add this workaround to our official [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#using-applicationinsightsserviceoptions)
- Natively support the appsettings.json

### Option 1. services.Configure<T>()
Every setting in the [ApplicationInsightsServiceOptions](https://github.com/microsoft/ApplicationInsights-dotnet/blob/14c4f88864c93011248263aa17422f61ab53d0f2/NETCORE/src/Shared/Extensions/ApplicationInsightsServiceOptions.cs) can be read by manually calling `services.Configure()`

#### Example Startup.cs
```
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<ApplicationInsightsServiceOptions>(Configuration.GetSection("ApplicationInsights"));
    services.AddApplicationInsightsTelemetry();
}
```

#### Example appsettings.json:
```
{
  "ApplicationInsights": {
    "InstrumentationKey": "ikey",
    "EnableAdaptiveSampling": false,
    "EnablePerformanceCounterCollectionModule": true,
    "EnableAzureInstanceMetadataTelemetryModule": false,
    "EnableRequestTrackingTelemetryModule": true,
    "EnableDependencyTrackingTelemetryModule": false,
    "EnableAppServicesHeartbeatTelemetryModule": false,
    "EnableEventCounterCollectionModule": false,
    "AddAutoCollectedMetricExtractor": false,
    "EnableQuickPulseMetricStream": false,
    "EnableDebugLogger": false,
    "EnableHeartbeat": false,
    "DependencyCollectionOptions": {
      "EnableLegacyCorrelationHeaders": false
    }
  },
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*"
}

```

### Option 2. in-code configuration.

All properties defined in [ApplicationInsightsServiceOptions](https://github.com/microsoft/ApplicationInsights-dotnet/blob/14c4f88864c93011248263aa17422f61ab53d0f2/NETCORE/src/Shared/Extensions/ApplicationInsightsServiceOptions.cs) can be set in code.

This is already documented here: https://docs.microsoft.com/azure/azure-monitor/app/asp-net-core#using-applicationinsightsserviceoptions

## Related issues

#1726 
#1448

**Comment by cijothomas** [comment]
@rajkumar-rangaraj is solving this issue by possibly using the user IConfiguration, if available. So we get values not just from appsettings.json, but from any source (keyvault, env etc) user has added to IConfigurationBuilder.
