### ISSUE TITLE
ILogger with exception should log into both traces and exceptions

### ISSUE THREAD

**Issue by kostrse** [microsoft/ApplicationInsights-dotnet#1807]
Here is a common logging pattern:

```c#
try
{
    ...
}
catch (Exception ex)
{
    _logger.LogError(ex, "This operation failed")
}
```

It would be great to log into **both** trace (with exception in customDimensions) and exception event.

Currently the **TrackExceptionsAsExceptionTelemetry** option allows only one or another.
This is far from ideal because either only exception can be logged with loss of message and other contextual information or trace event but with loss of exception details.

Proposal is to add one more settings flag: **TrackExceptionsAsTraceTelemetry**. So they could be both enabled. It would not break existing code.

**Comment by joaopgrassi** [comment]
Is this still relevant? Looking at the code at `ApplicationInsightsLogger`, when an exception is passed, the `ExceptionTelemetry` contains the original exception and custom message is inside the telemetry properties. 

In the other case, (if `TrackExceptionsAsExceptionTelemetry` is false), the trace also contains the original message + stacktrace in the properties.. so I'm a bit confused why to log again as trace?

Wanted to give this a go but not sure what's expected.

**Comment by abatishchev** [comment]
Yes, I think it still is. Right now exceptions go into a separate table which you need join or correlated. Otherwise by looking into just Trace table you won't see the errors at all.

**Comment by joaopgrassi** [comment]
Yes, that's true, but is that an use case? I never had to join both.. if I'm looking at exceptions usually the exceptions table is enough, I never thought on look at the traces table. Isn't also that some sort of duplication? logging both things twice?

**Comment by abatishchev** [comment]
It's a duplication indeed, I agree. WOuld be great if this could be configurable and turned off by default, i.e. make it opt-in behavior.
Use case: DGrep. Each AI table corresponds to individual table in Geneva which you need to explicitly select when make a query.

**Comment by cijothomas** [comment]
@abatishchev If this use case is for Microsoft internal service, we can solve it separately as there is a new LoggingProvider being written for this service. ( i happen to work on that Microsoft internal solution)

For general Application Insights consumers, this duplication probably don't make sense, as they pay double the cost (billing is based on ingested volume). Everything can be correlation with operationid anyway.

**Comment by joaopgrassi** [comment]
>as they pay double the cost

exactly where my concerns were coming from. Even if it's a opt-in I'm not sure it makes much sense from a customer view (I tend to use it very often so trying to wear my "customer hat" here 😅).

 I'm more than happy to contribute, just want to make sure it makes sense.
