### ISSUE TITLE
Data is being sampled even though sampling is disabled

### ISSUE THREAD

**Issue by Stardox** [microsoft/ApplicationInsights-dotnet#1808]
### Environment
* **AI SDK:** Microsoft.ApplicationInsights.AspNetCore 2.13.1
* **.NET version:** .NET Core 3.1
* **Type:** ASP.NET Core web application
* The application is hosted within Azure as an App Service

### The problem

Occasionally when reviewing App Insights logs of my Web App through Azure portal I notice that some of the entries within given telemetry operation are missing or that the whole telemetry operation is missing completely. By telemetry operation I mean all entries in the context of incoming HTTP request.

This behavior seems to be related to following message bubble which appears on top of App Insights window in Azure:

> Data received from your application is being sampled to reduce the volume of telemetry data retained; only sampled documents will be returned. The sampling may be applied by the Application Insights SDK or on ingestion by Application Insights. Click to learn more.

The message points to [following documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling) which I have walked through already and disabled the sampling both in the SDK and also in portal.

### SDK configuration

This is how I have configured the AI Telemetry Client within my `Startup.cs` class:
```
var aiOptions = new ApplicationInsightsServiceOptions
{
    EnableAdaptiveSampling = false,
    EnableQuickPulseMetricStream = false,
    InstrumentationKey = ikGoesHere
};
aiOptions.RequestCollectionOptions.TrackExceptions = true;
services.AddApplicationInsightsTelemetry(aiOptions);
```

### AI configuration through portal

![image](https://user-images.githubusercontent.com/4964894/80216115-d8ffef00-863d-11ea-86fa-3474bbf912d9.png)

![image](https://user-images.githubusercontent.com/4964894/80216180-f59c2700-863d-11ea-8c5d-301c5531d0b7.png)

![image](https://user-images.githubusercontent.com/4964894/80216221-05b40680-863e-11ea-81b8-42afb5ee91b8.png)

I need to retain **all** telemetry data (even though it is only for couple of days) for diagnostic purposes. How can I achieve that?

**Comment by rajkumar-rangaraj** [comment]
@Stardox , SDK and Server configuration looks fine. Could you please execute the following query and check if data is sampled.

```
union requests,dependencies,pageViews,browserTimings,exceptions,traces
| where timestamp > ago(1d)
| summarize RetainedPercentage = 100/avg(itemCount) by bin(timestamp, 1h), itemType
```
Ref: [Knowing whether sampling is in operation] (https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#knowing-whether-sampling-is-in-operation)

**Comment by Stardox** [comment]
@rajkumar-rangaraj, for majority of results the _RetainedPercentage_ is _100_. However I also see entries where the percentage is _~91_, _~68_ or _~75_ just to name few.

Not sure if this is relevant, by my App Insights resource is in _South Central US_ region.

**Comment by rajkumar-rangaraj** [comment]
@Stardox , If  `RetainedPercentage`  is not equal to 100 in any of the row, then we consider data as sampled. This could also happen if multiple app logging to the same AI component. Could you please validate that only one app is logging data to this component.

**Comment by graham-saunders** [comment]
I'm having this same issue. Data sampling is set to 100% (all data) and with the above query I'm seeing retained percentage at ~53, ~48, ~60, etc.

**Comment by Stardox** [comment]
@rajkumar-rangaraj, there is only one application creating log entries in my AI component.

But even if there were multiple, then theoretically speaking, it would only affect this _retained percentage_ report - It should simply drop / ignore telemetry entries, right?

**Comment by Huss-Dev** [comment]
@Stardox  Did you by any chance find a solution to this issue. Would help if you could share your experience.

Thanks in advance

**Comment by DiscipleDV** [comment]
@Stardox @Huss-Dev @rajkumar-rangaraj 
Try to turn this setting off. It may help.

![image](https://user-images.githubusercontent.com/6018743/103311924-a019e480-4a2c-11eb-8156-8ae8f58eb6ee.png)

**Comment by chertpong** [comment]
We are facing the same issue, it would be great if anyone can share about the root cause of issue.

**Comment by cijothomas** [comment]
If you believe data is being sampled at the ingestion side, despite turning it off, please open support ticket with Azure.

If the SDK is sampling, despite configuring it to do otherwise, please reply here, and we can investigate. Please share a minimal repro for this behaviour.

**Comment by SavaNDragos** [comment]
Seeing same issue with Azure Functions v3, I have in the host.json.
`{
  "version": "2.0",
  "logging": {
    "fileLoggingMode": "always",
    "logLevel": {
      "default": "Trace"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": false,
        "maxTelemetryItemsPerSecond": 20000
      }
    }
  }
}`
the telemetryclient is based on default: new TelemetryClient(TelemetryConfiguration.CreateDefault());

**Comment by cijothomas** [comment]
Please raise Azure functions issue in Azure functions runtime repo, as Functions uses a custom enablement of application insights sdk.

**Comment by Huss-Dev** [comment]
> @Stardox @Huss-Dev @rajkumar-rangaraj Try disabling this setting. As I understand it, this can help as it disables the SDK on the Azure service side, which overrides the SDK on the application side (with its settings).
> 
> ![image](https://user-images.githubusercontent.com/6018743/103311924-a019e480-4a2c-11eb-8156-8ae8f58eb6ee.png)

This solution worked in my case. Once the InterOP with Application Insights was disabled the correct settings got applied.

**Comment by andywarrens** [comment]
We also face this issue:
- in Azure AppInsights: Sampling: `All Data 100%`
- in code: no AppInsights code is added (ASP.NET Core 3.1)
- in App Service > App Insights blade: Interop is `Off`

still for lots of `requests` the itemCount = 1000, or 2000. Rounded off to this value, very strange.

**Comment by andywarrens** [comment]
@cijothomas but what kind of sampling is enabled?  How does it work?

I have a feeling that for a particular `request`, the itemCount is way too high. I expect it to be called around 20-50 times a day. But in reality it's 10.000 (total records is 13, `sum(itemCount)` ~ 10.000)

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling

**Comment by andywarrens** [comment]
Thanks! I've read that page before but I'm still not sure which sampling I have enabled. Because Adaptive and Fixed-rate are configured in code, it seems I have Ingestion Sampling enabled. But then the docs say:
> It discards some of the telemetry that arrives from your app, at a sampling rate that you set. 

But the only place where I can set it, it's set to `All data 100%`. So I wonder if my deduction is correct.
These are the only settings I could find in my App Service related to Application Insights:
![image](https://user-images.githubusercontent.com/81295421/188829436-b15e32a5-5186-429f-9341-e4c42b61300b.png)

**Comment by cijothomas** [comment]
> not sure which sampling I have enabled.

You haven't enabled anything explicitly. When you enable auto-instrumentation (from app service's Application Insights blade - https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps), it enables Application Insights with a default setting. (it includes sampling as well). There is not much control one has if you chose auto-instrumentation. If you want to have full control, then you need to use the SDK based instrumentation.

**Comment by cijothomas** [comment]
> Aha. Thanks for that explanation. It would be great if the docs would add an overview of those default settings.

Please share the feedback in the docs page itself, so it won't get lost in this repo.

**Comment by andywarrens** [comment]
Do you mean a pull request on this repo ([update this file](https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/docs/concepts.md)), or the Github button on the bottom of the Sampling page you shared?

**Comment by cijothomas** [comment]
![image](https://user-images.githubusercontent.com/5232798/189711018-0dcf885e-eab1-4afa-b744-231d759f8f48.png)
This ^, at the bottom of the doc
