### ISSUE TITLE
Unify AspNetCore.ITelemetryProcessorFactory and WorkerService.ITelemetryProcessorFactory

### ISSUE THREAD

**Issue by ohadschn** [microsoft/ApplicationInsights-dotnet#1812]
**Is your feature request related to a problem?**
`Microsoft.ApplicationInsights.AspNetCore` and `Microsoft.ApplicationInsights.WorkerService` each have their own version of `ITelemetryProcessorFactory` (different type, same source code and implementation): https://github.com/microsoft/ApplicationInsights-dotnet/blob/b6896cd40f1d7bced25327549d0ee7c299590838/NETCORE/src/Shared/Implementation/ITelemetryProcessorFactory.cs#L1

In my case I had shared infra that did something like this: 
```cs
services.AddSingleton<ITelemetryProcessorFactory>(builder => new MyProcessor());`
```

This worked great for ASP.NET projects, but failed for WorkerService projects. It was incredicly hard and time consuming to figure out that there are in fact two separate interfaces and the solution is: 

```cs
services.AddSingleton<ApplicationInsights.AspNetCore.ITelemetryProcessorFactory>(builder => new MyProcessor());
services.AddSingleton<ApplicationInsights.WorkerService.ITelemetryProcessorFactory>(builder => new MyProcessor());
```

**Describe the solution you'd like.**
Ideally there would be only one `ApplicationInsights.Shared.ITelemetryProcessorFactory`, so just one line would suffice and such confusion could not take place:
```cs
services.AddSingleton<ITelemetryProcessorFactory>(builder => new MyProcessor());`
```

**Describe alternatives you've considered.**
An alternative, in case they have to remain separate, would be to rename the interface to make it clear which one is used. Something like `IAspNetTelemetryProcessorFactory` / ``IWorkerServiceTelemetryProcessorFactory``.

**Additional Context**
This could be a part of a bigger ask to extract similar shared code (I assume this is not the only example) to a NuGet package such as `Microsoft.ApplicationInsights.Shared`.

**Comment by cijothomas** [comment]
Thanks for sharing the issue. Sorry for the confusion this caused.
I see that your project have both aspnetcore and workerservice SDK in the same project. These packages were written with assumption that only one will be used in a project. If both are used in same project (you are probably doing some shared library for web and worker right?), then using fully qualified name would be the only option.

I can keep this as an enhancement, but a low priority one.
