### ISSUE TITLE
Azure cloud service AI TelemetryClient not working

### ISSUE THREAD

**Issue by dbreshears** [microsoft/ApplicationInsights-dotnet#1822]
Glenn is facing an issue with VS Cloud Services worker role and AI Telemetry Client not working.   The issue he is facing is at https://developercommunity.visualstudio.com/content/problem/1002768/azure-cloud-service-ai-telemetryclient-not-working.html 

Description: 

I have a cloud service running in Azure and the TelemetryClient implemented for ApplicationInsights to report TrackTrace, TrackEvent, and TrackException. These do display to attached remote debug output but not to ApplicationInsights (through the Search facility).

The Exception: Exception thrown: ‘System.TypeInitializationException’ in Microsoft.ApplicationInsights.dll is reported in remote debug Output after every telemetry track event. What could be wrong?

Please advise.

**Comment by cweining** [comment]
More information from the customer (copied from VS Feedback): 

First of all it is a worker role and not a web role. The Microsoft.ApplicationInsights nuget is version 2.14.0. With a very simple telemetry configuration in the cloud server - i.e. new TelemetryClient with an Instrumentation Key, the following output appears in the remote debugging Output screen locally but it is not available in AI Search. From the output screen:
WaWorkerHost.exe Warning: 0 : info Warning ServerSocket Ping recd from client at [::ffff:108.216.108.255]:46700 Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Event","time":"2020-04-27T17:30:23.8275127Z","tags":{"ai.cloud.roleInstance":"RD0003FF9A15E0","ai.internal.sdkVersion":"dotnet:2.13.1-12554"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"Server ping"}}}

Why does the AI message appear in Output but not AI Search? Does it have anything to do with the storage account and how System.Diagnostics is configured? What does the "unconfigured" mean in the AI message above? Some configuration setting in Role properties, ApplicationInsights.config, app.config, ServiceDefinition.csdef, or ServiceConfigurationCloud.cscfg may be the problem but most of them are out-of-the-box so I don't know where to look.

**Comment by cijothomas** [comment]
Application Insights Telemetry (unconfigured): - This means instrumention key is not setup. Visual Studio debugger can still show messages with instrumentation key, but nothing gets sent to actual application insights, unless instrumentationkey is specified.

I'd suggest to double check the instrumentationkey setup.

**Comment by TimothyMothra** [comment]
also note that although the nuget version is "2.14" the json says "2.13.1" is running
