### ISSUE TITLE
Some tests aren't running in DependencyCollector.Tests 

### ISSUE THREAD

**Issue by eddynaka** [microsoft/ApplicationInsights-dotnet#1830]
Hi,

The tests inside the following files weren't running when we were using shared projects:
- ProfilerHttpProcessingTest
- DesktopDiagnosticSourceHttpProcessingTests
- FrameworkSqlProcessingTest
- ClientServerDependencyTrackerTests
- FrameworkHttpProcessingTest

We have to investigate and see if they need to be run or not.

Refs #1827

**Comment by ayenisholah** [comment]
Hi, I am interested in helping but don't know how to begin.

**Comment by cijothomas** [comment]
These tests are important, and should be running. @TimothyMothra any ideas why these were not running?

**Comment by eddynaka** [comment]
@cijothomas , my comments from the previous pr that i found out that: https://github.com/microsoft/ApplicationInsights-dotnet/pull/1827#issuecomment-621402191

Some files were hidden or wasn't being add properly. When we moved to the actual project, we saw that incosistence.

The change: https://github.com/microsoft/ApplicationInsights-dotnet/pull/1827

**Comment by TimothyMothra** [comment]
Let me verify that we fixed this and we can close this Issue

**Comment by eddynaka** [comment]
@TimothyMothra , we added the ignore attribute since some tests weren't passing...

**Comment by TimothyMothra** [comment]
@eddynaka, gotcha. I lost track of this. 
We've made a number of significant improvements to our tests. When you get a moment, can you please create a Draft PR removing the IGNORE?
We can use that PR to continue investigating.
