### ISSUE TITLE
Get Traceparent from C# SDK

### ISSUE THREAD

**Issue by dennis-yemelyanov** [microsoft/ApplicationInsights-dotnet#1831]
**Describe your environment.**
Describe any aspect of your environment relevant to the question:
* SDK version: 2.13.1
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): ASP.NET Core
* Hosting Info (IIS/Azure WebApps/etc): Docker
* Platform and OS version: Linux

**What are you trying to achieve?**
I have a C# (ASP.NET Core) process that needs to call a Python process, for which I want to correlate logs with the caller. It looks like for Python the recommended way is to use the OpenCensus SDK, which requires passing Traceparent in the W3C format.

How can I get the right Traceparent value from AI C# SDK? Looks like there is a GetTraceparent() method on Activity extensions, but this method is marked as obsolete, and I'm also not creating the Activity manually (using TelemetryClient.StartOperation<DependencyTelemetry>() instead). But there seems to be no field available from IOperationHolder<DependencyTelemetry>  that looks like W3C-formatted traceparent (starting with "00-" and ending with "-01").

What's the best way to do this correlation between C# and Python processes?

**Comment by cijothomas** [comment]
Are you calling Python app using HttpClient? If yes, the traceparent header is automatically injected.

If not, you can get traceparent from currentactivity.
When calling `StartOperation`, application insights starts an Activity, which you can access from `Activity.Current`, and its `.Id` field contains the traceparent in W3C format. (`Activity.Current.Id`)

let us know if this helps.

**Comment by dennis-yemelyanov** [comment]
Thank you, @cijothomas , it seems to work this way (and no, the communication between these processes is not through HTTP).

But if I don't want to create an extra operation and just want to get the id associated with the current ASP.NET Core request, is there a way to do it? If best practice is to create a new dependency operation anyway, then I can keep creating it.

Also an additional question related to this, if I have an existing ASP.NET Core application which clients call using the non-W3C format starting with "|" (I think it was called a hierarchical request id or something like that), do I need to do anything to "convert" the non-W3C value to W3C format (so it can be correlated with Python)? Or will `Activity.Current.Id` automatically return the right value (although I'm not sure if it knows which format I want to get)?

**Comment by cijothomas** [comment]
ASP.NET Core creates a new Activity. So even if you dont do StartOperation, you can still access `Activity.Current.Id`.

You may want to wrap the call to python process inside StartOperation<Dependency>, so whatever happens inside that StartOperation will be correlatted together, and Application Insights experiences (which are built around Request, Dependency model) will show the python calls as dependency.

Its a bit complex to explain how SDK interops with older version of itself. If incoming request is from an old SDK, it'd be sending correlation in HierrarchicalFormat, using "request-id" header. If the value is compatible with W3C TraceID, then the new Activity's traceid will be the corresponding part of request-id.
For eg, if an old client sends a request to the Asp.Net core app, with "request-id" = "|40d1a5a08a68c0998e4a3b7c91915ca6.b9e41c35_1.". The portion of request-id between ! and first . is compatible, and  will be treated as TraceID and will be used as the request.Operation.Id. If this asp.net core app is making futher calls to another service, it'll be sending traceparent, with traceid as "40d1a5a08a68c0998e4a3b7c91915ca6". 

This is assuming the incoming request is compatible with traceid. If its not compatible, like request id = "!someid.ddd.aaa.", then its ignored and new TraceId is generated. However, the requestid is still stored as custom property in the req.Properties["ai_legacyRootId"]. (Appinsihgts backend know about these special custom properties)

Even before w3ctrace format became official, our SDKs started generating request-ids, in the w3c compatible format. So unless the calls from very old SDKs, it'd be compatible.

My explanation may not be very clear, so below is the link to actual unit tests validating scenarios like this:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/NETCORE/test/IntegrationTests.Tests/BasicTestWithCorrelation.cs#L119

**Comment by dennis-yemelyanov** [comment]
Thank you for the detailed explanation! I'll try it out to see if it works and dig deeper if there are any issues :)

**Comment by MagdaPaj** [comment]
@cijothomas I know that the issue is closed, but I have a very similar question (regarding good practices). 
That's my code:
```
var operation = _telemetryClient.StartOperation<DependencyTelemetry>("my dependency");
```
And I need the `traceparent` of it. So is it a good practice to use `Activity.Current.Id` or it's better to compose it? I could use `operation.Telemetry.Id` and `operation.Telemetry.Context.Operation.Id` and I would need to figure out from where to get `version` (it seems to be `00`) and `trace-flags` (also seems to be `00` in my case). Composing is a bit more work, but it's a bit more clear what is this `traceparent` value. What would be your advice?

**Comment by cijothomas** [comment]
@MagdaPaj please open a new issue and we can discuss this more there.
