### ISSUE TITLE
Application Insights not correlating full post back dependency calls with server request

### ISSUE THREAD

**Issue by t525** [microsoft/ApplicationInsights-dotnet#1848]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: 2.12
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): .net 4.6.2
* Hosting Info (IIS/Azure WebApps/etc): IIS
* Platform and OS version: Windows 10

If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

**Steps to reproduce.**
I noticed that when a ASP.NET web forms page does a full postback, a new page view in app insight is generated but it is not being correlated with the server request.  All I see in the end to end transaction is a list of dependency calls and then at the end is the page view.  For partial post back (AJAX), only one page view is generated and all dependency calls appear under the server request.

**What is the expected behavior?**
I am thinking that for full post back, the dependency calls should be still linked to the server request.

**What is the actual behavior?**
Dependency calls associated with full post back are not linked to server request.

**Additional context.**

**Comment by t525** [comment]
Any update on this as I will need to have a solution soon for this issue?

**Comment by t525** [comment]
Forgot to mention that I also have W3C distributed tracing enabled.  Is there anything additional that is needed for this to work properly?

**Comment by t525** [comment]
Is there a way that this issue be looked into soon as I need to deploy changes to production?

**Comment by rajkumar-rangaraj** [comment]
PageView is not generated by .NET SDK. JavaScript Application SDK added to an app generates it. What is the version of JavaScript AppInsights SDK?
Could you please share End-to-End Trace if does not contain PII data (Please remove iKey, if present).

**Comment by t525** [comment]
I am using version 2.4.4 of javascript sdk.  This is the snippet that I have on each of my pages:
`<script type="text/javascript">var sdkInstance="appInsightsSDK";window[sdkInstance]="appInsights";var aiName=window[sdkInstance],aisdk=window[aiName]||function(n){var o={config:n,initialize:!0},t=document,e=window,i="script";setTimeout(function(){var e=t.createElement(i);e.src=n.url||"https://az416426.vo.msecnd.net/scripts/b/ai.2.4.4.min.js",t.getElementsByTagName(i)[0].parentNode.appendChild(e)});try{o.cookie=t.cookie}catch(e){}function a(n){o[n]=function(){var e=arguments;o.queue.push(function(){o[n].apply(o,e)})}}o.queue=[],o.version=2;for(var s=["Event","PageView","Exception","Trace","DependencyData","Metric","PageViewPerformance"];s.length;)a("track"+s.pop());var r="Track",c=r+"Page";a("start"+c),a("stop"+c);var u=r+"Event";if(a("start"+u),a("stop"+u),a("addTelemetryInitializer"),a("setAuthenticatedUserContext"),a("clearAuthenticatedUserContext"),a("flush"),o.SeverityLevel={Verbose:0,Information:1,Warning:2,Error:3,Critical:4},!(!0===n.disableExceptionTracking||n.extensionConfig&&n.extensionConfig.ApplicationInsightsAnalytics&&!0===n.extensionConfig.ApplicationInsightsAnalytics.disableExceptionTracking)){a("_"+(s="onerror"));var p=e[s];e[s]=function(e,n,t,i,a){var r=p&&p(e,n,t,i,a);return!0!==r&&o["_"+s]({message:e,url:n,lineNumber:t,columnNumber:i,error:a}),r},n.autoExceptionInstrumented=!0}return o}({instrumentationKey: "xxxxxxxxxxxxxxxxxxxxxxxx",disableCorrelationHeaders: false,enableCorsCorrelation: true,distributedTracingMode: 2});window[aiName]=aisdk;aisdk.queue.push(function(){aisdk.addTelemetryInitializer(function (envelope) {var tags = envelope.tags;if (tags) {tags['ai.user.id'] = "t.sorial";}var data = envelope.data || {};var telemetryItem = envelope.baseData || {};if (envelope.name == Microsoft.ApplicationInsights.Telemetry.PageView.envelopeType) {telemetryItem.name = "Daily Routine/Lab/Requests/Scan Sample";envelope.tags['ai.operation.name'] = telemetryItem.name;}data.portal = "Daily Routine";data.area = "Lab";data.zone = "Requests";data.section = "Scan Sample";});var serverId = "adae697524a40640aa00c9c60cd37acd";aisdk.properties.context.telemetryTrace.traceID  = serverId;});
aisdk.trackPageView();</script>`

**Comment by t525** [comment]
Below is the end to end transaction for the full postback:
![image](https://user-images.githubusercontent.com/59030353/81226832-756cae80-8fb9-11ea-9dfd-e2912c814568.png)

**Comment by t525** [comment]
Was wondering if any solution to my issue was found?

**Comment by t525** [comment]
I also want to clarify that that this is not page view issue but that the dependencies are not being linked to a server request as shown in end to end transaction.

**Comment by rajkumar-rangaraj** [comment]
I'm not able to recreate an issue with default ASP.NET application. We could troubleshoot this issue faster if you could provide a code to repro an issue.

**Comment by t525** [comment]
Can we do a teams session to show you what I am seeing exactly?  Are there known bugs with version 2.12 of the .net sdk with regards to this postback issue?  When you tested, did you do a full postback instead of ajax partial postback?

**Comment by rajkumar-rangaraj** [comment]
I on-boarded Application Insights for default ASP.NET app (no Ajax). On button click, created a  HttpClient call to www.bing.com. 

This operation created Request and Dependency telemetry. Both are correlated and has same operation id. Looks like issue is related to your app. Can you create a small test app and check if you see the same issue.  

```
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.RemoteDependency","time":"2020-05-08T01:48:57.3417950Z","tags":{"ai.cloud.roleInstance":"roleInstance,"ai.operation.id":"8818fcbaf95de242a9eef25d5d4b6eb6","ai.operation.parentId":"6bd9d97cbac06049","ai.internal.sdkVersion":"rdddsd:2.13.1-12554","ai.internal.nodeName":"rajrang-ai.redmond.corp.microsoft.com"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"GET /","id":"aca4e5b16accd94d","data":"https://www.bing.com","duration":"00:00:00.5023011","resultCode":"200","success":true,"type":"Http","target":"www.bing.com","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')"}}}}
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2020-05-08T01:48:57.2910631Z","tags":{"ai.cloud.roleInstance":"roleInstance","ai.user.id":"8x7gy","ai.operation.id":"8818fcbaf95de242a9eef25d5d4b6eb6","ai.operation.parentId":"3c682788ee590546","ai.operation.name":"GET /default.aspx","ai.location.ip":"::1","ai.internal.sdkVersion":"web:2.13.1-12554"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"6bd9d97cbac06049","name":"GET /default.aspx","duration":"00:00:00.6436985","success":true,"responseCode":"200","url":"https://localhost:44311/default.aspx","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.1')"}}}}

```
If you want to perform screen sharing session, we recommend creating [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) to work with our support team.

**Comment by t525** [comment]
Actually this scenario might not match exactly with my case.  My case is this.  I have a page that makes a full post back to server with a button click.  The server then calls a stored procedure to return back data to the page.  The SQL dependency calls logged for the post back are not associated with a server request.  Does that make sense?

**Comment by rajkumar-rangaraj** [comment]
> Server Request A -> Generates Page A
> Full postback from Page A -> Server Request B

Please be aware that these are two different operation. First one is a GET / operation and the next is POST / operation. They don't correlate each other.

If you run your app in Visual Studio and take a look at messages emitted by Application Insights you would be able to figure it out. `ai.operation.name` is generated for each unique operations. 

From you E2E snapshot I could see there are many telemetries. If [sampling](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#turning-off-adaptive-sampling) is turned on that could also cause an issue. Please disable sampling and check.

**Comment by t525** [comment]
How do I disable sampling?

**Comment by rajkumar-rangaraj** [comment]
comment out all AdaptiveSamplingTelemetryProcessor in your ApplicationInsights.config
```
<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel" />
```

**Comment by t525** [comment]
I commented out sampling reference in appinsights.config but I am still dependencies involved for the full postback  not being linked to a server request.  Is this a bug?

**Comment by t525** [comment]
Thoughts on what could be going on as I disabled sampling? I just would like to know if the end to end transaction above is correct for full post backs or there is a potential issue that needs to be looked into.

**Comment by rajkumar-rangaraj** [comment]
There are no known issues. It is difficult to provide action plan without a minimal repro. Please create a small repro and share it.

**Comment by t525** [comment]
From what you see in end to end transaction, is this typical for asp.net full post back?

**Comment by t525** [comment]
So the issue above is for postbacks.  Initial loads are showing correlation properly in our dev environments.    However, when we deployed to test environment the page views are logged but the server request for the page is missing.  What could cause this strange behavior?  Is it sampling still?  This is what we have for sampling.  Do we need to adjust?

`<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
        <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
    </Add>`

**Comment by rajkumar-rangaraj** [comment]
Now the issue is very clear, you have answers for most of the questions. This issue is related to one of the environment. Sampling won't miss request telemetry all the times. But it is worth to disable sampling and test the behavior.

In the web.config, application insights SDK adds following entry
```
      <add name="TelemetryCorrelationHttpModule" type="Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule, Microsoft.AspNet.TelemetryCorrelation" preCondition="managedHandler" />
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web" preCondition="managedHandler" />
```

`ApplicationInsightsWebTracking` is responsible to track request telemetry. Check your web.config and ensure this module entries are present under both `modules` and `httpmodules` section. So you don't need to worry about the classic/integrated pipeline execution in IIS.

**Comment by t525** [comment]
You can close this ticket.  My issue was in custom processor and something was failing there causing the telemetry not to be sent.  I think I have it working now.

**Comment by t525** [comment]
What is the optimal adaptive sampling rate without impacting performance?  We are noticing on high activity days, some telemetry to be missing.  We are currently use default of sending 5 telemetry items per second.
