### ISSUE TITLE
Unable to setup ApplicationInsights to use W3C distributed tracing

### ISSUE THREAD

**Issue by henioStraszny** [microsoft/ApplicationInsights-dotnet#1856]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: 3.1
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): netcoreapp3.1 and netstandard2.1
* Hosting Info (IIS/Azure WebApps/etc): Container in AKS
* Platform and OS version: mcr.microsoft.com/dotnet/core/aspnet:3.1

**Steps to reproduce.**
Add application insides do app:

```csharp
services.AddApplicationInsightsTelemetry();
```
Request data using System.Net.Http.HttpClient.

**What is the expected behavior?**
No request-id is in the http-header for HttpClient calls.

According to documentation in request headers Application Insights should add W3C distributed tracing instead of old request-id [Application Insights documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#enable-w3c-distributed-tracing-support-for-aspnet-core-apps). 

**What is the actual behavior?**
In the header there is request-id .

```
host: ********.com
accept: application/json
authorization: Bearer
request-id: |3abd42e05cd83e45bd27d50331538ba3.1c3347ec038f1643.
traceparent: 00-3abd42e05cd83e45bd27d50331538ba3-1c3347ec038f1643-00
connection: **keep-alive**
```

**Additional context.**
Setup Activity properties do not affect this change
```csharp
Activity.DefaultIdFormat = ActivityIdFormat.W3C;
Activity.ForceDefaultIdFormat = true;	
```

**Comment by cijothomas** [comment]
"request-id" is still added to allow interop with applications using old sdk. (they would'nt know about w3c).

**Comment by henioStraszny** [comment]
Ok, so can I either disable sending request-id or modify it so there is no longer pipe symbol?

**Comment by cijothomas** [comment]
`EnableRequestIdHeaderInjectionInW3CMode` on `DependencyTrackingTelemetryModule` can be set to false to achieve this. (this is true by default)

**Comment by henioStraszny** [comment]
Thanks @cijothomas for help, I was able to disable request-id using ConfigureTelemetryModule extension method:

```csharp
services.AddApplicationInsightsTelemetry();
services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((configModule, options) =>
{
	configModule.EnableRequestIdHeaderInjectionInW3CMode = false;
});
```
