### ISSUE TITLE
ApplicationInsights.OwinExtensions.HttpRequestTrackingMiddleware+<Invoke>d__4.MoveNext

### ISSUE THREAD

**Issue by arunbalajip** [microsoft/ApplicationInsights-dotnet#1862]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: 
"ApplicationInsights.OwinExtensions" Version="0.6.0"
"Microsoft.ApplicationInsights" Version="2.8.1"
"Microsoft.ApplicationInsights.DependencyCollector" Version="2.8.1" 
"Microsoft.ApplicationInsights.PerfCounterCollector" Version="2.8.1" 
"Microsoft.ApplicationInsights.Web" Version="2.8.1" 
"Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" Version="2.8.1" 
"Microsoft.AspNet.WebApi.Owin" Version="5.2.6" 

* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): 
Microsoft.NET Framework 4.6.1
* Hosting Info (IIS/Azure WebApps/etc): 
Azure Service Fabric
* Platform and OS version: 

If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

**Steps to reproduce.**
Describe exactly how to reproduce the error. Include a code sample if applicable.
We are listening to external dependency using Application insights. we are getting errors in OWIN listener package.

**What is the expected behavior?**
What did you expect to see?
No errors. 

**What is the actual behavior?**
What did you see instead?
we are capturing the external calls. We also get these errors too.  

**Additional context.**

![image](https://user-images.githubusercontent.com/20033858/81353644-79163900-907e-11ea-99aa-fbf0ccd89f3d.png)

ApplicationInsights.config 
https://github.com/arunbalajip/Issues/blob/master/ApplicationInsights.config

**Comment by TimothyMothra** [comment]
Hello @arunbalajip,
Can you please fill out the rest of the questionnaire? I'm not sure what kind of issue you're encountering.

It looks like that exception was thrown by `ApplicationInsights.OwinExtensions`. Please note that we don't own that library and we can't provide support for it.

**Comment by arunbalajip** [comment]
Thank you for the quick reply. Do you know who owns the library?

**Comment by TimothyMothra** [comment]
NuGet has a link for both the Project Site and to Contact Owners.
https://www.nuget.org/packages/ApplicationInsights.OwinExtensions/

**Comment by arunbalajip** [comment]
Created the issue with the right project 
https://github.com/marcinbudny/applicationinsights-owinextensions/issues/36
