### ISSUE TITLE
[Asp dotnet core 3.0] AppService logs startup errors. AppInsights don't seem to work.

### ISSUE THREAD

**Issue by satish80** [microsoft/ApplicationInsights-dotnet#1863]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: 
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): dotnet core 3.0 
* Hosting Info (IIS/Azure WebApps/etc): Azure AppService
* Platform and OS version: 

If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

**Steps to reproduce.**
Deploy any build to AppService. The event log would indicate exceptions at startup, though the application works fine.

**What is the expected behavior?**
AppInsights should show the logs and analysis of Failures, Performance.

**What is the actual behavior?**
EventLogs shows the exception System.InvalidOperationException

**Additional context.**

```
Microsoft.AspNetCore.Hosting.Diagnostics EventId: 11 Hosting startup assembly exception Exception: System.InvalidOperationException: Startup assembly Microsoft.ApplicationInsights.StartupBootstrapper failed to execute. See the inner exception for more details. 
---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ApplicationInsights.StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. File name: 'Microsoft.ApplicationInsights.StartupBootstrapper, Culture=neutral, PublicKeyToken=null' 
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext) 
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext) 
at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext) 
at System.Reflection.Assembly.Load(AssemblyName assemblyRef) at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ExecuteHostingStartups() 
--- End of inner exception stack trace --- 
```
</Data>

Tagging @shirhatti

**Comment by TimothyMothra** [comment]
@satish80 we don't own a `Microsoft.ApplicationInsights.StartupBootstrapper`.
Are you using our SDK or are you using the Azure AppService extension?

**Comment by shirhatti** [comment]
Apologies @TimothyMothra. I asked @satish80  to file the bug in this repo. This is from the site extension

**Comment by TimothyMothra** [comment]
No worries @shirhatti.

@ank3it, @rajkumar-rangaraj  what's the correct way to file bugs against the Extension team? Can they do that through the portal itself?

**Comment by santoro1693** [comment]
@satish80 i have same issue, do u have solved?

**Comment by lujianjun19** [comment]
has same problem
