### ISSUE TITLE
Will telemetry collection still happen if no Instrumentation key is provided?

### ISSUE THREAD

**Issue by malichishti** [microsoft/ApplicationInsights-dotnet#1864]
**Describe your environment.**
Describe any aspect of your environment relevant to the question:
* ASP.NET Core 3.1 

I would like to know if my Startup contains following, 

services.AddApplicationInsightsTelemetry();

but i don't specify any instrumentation key in the config or the environment, will it in any way still impact the processing power of the server i.e. will the telemetry collection or sampling still keep on happening even if it is not being sent anywhere?

**Comment by cijothomas** [comment]
Yes. All the overhead of collecting and processing still exists even without ikey. Lack of ikey only prevents the actual sending of data to application insights endpoint.

`DisableTelemetry` on TelemetryConfiguration is better, as it avoids most of the work.

Even better would be disable each individual auto-collection modules using ApplicationInsightsServiceOptions
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#using-applicationinsightsserviceoptions

Best case would be to call/not call services.AddApplicationInsightsTelemetry(); depending on your environment.

**Comment by malichishti** [comment]
Thank you @cijothomas 
Is there any easier way to know if the ikey exists or not? to decide if one should call or not services.AddApplicationInsightsTelemetry();

**Comment by stebet** [comment]
Read it from config, and if it's null or empty, don't call AddApplicationInsightsTelemetry?
