### ISSUE TITLE
Add the traceresponse header

### ISSUE THREAD

**Issue by aelij** [microsoft/ApplicationInsights-dotnet#1865]
**Describe the solution you'd like.**
The W3C Trace Context document also specifies a response header, [traceresponse](https://w3c.github.io/trace-context/#returning-the-traceresponse-field) that can be sent back to the client. This can be very useful to locate entries in the logs.

**Describe alternatives you've considered.**
Create a middleware that adds the header.

**Comment by cijothomas** [comment]
SDK already implements the W3CTraceContext. TraceResponse and other things are draft - we'll consider it once it progresses from draft.
