### ISSUE TITLE
DependencyTelemetry not generated with configured LiveEndpoint ConnectionString

### ISSUE THREAD

**Issue by aluong** [microsoft/ApplicationInsights-dotnet#1866]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: 2.14.0
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): .NET Core
* Hosting Info (IIS/Azure WebApps/etc): Console App
* Platform and OS version: Windows 10

**Steps to reproduce.**
I am proxying all of my AI events through an HAProxy, and things work when I use the IP Address of the server oppose to the FDQN.

I was using the VS Application Insights to debug / repro this locally, and I am seeing the same problem when I was uploading to valid Application Insights endpoints. Consequently, I set the `key` to be an empty string in the examples below.

**Locally**
When I set the `LiveEndpoint` to use `localhost`, it does not generate the DependencyTelemetry event for my Http calls. Specially, the one from the sdk rdddsc:2.14.0-17971. 

```
  "ApplicationInsights": {
    "ConnectionString": "InstrumentationKey='';LiveEndpoint=http://localhost:6001/;
  },
```
However, if I set the `LiveEndpoint` to be the `ip address` (ex: 127.0.0.1), I see the DependencyTelementry event logged to Application Insights.

```
  "ApplicationInsights": {
    "ConnectionString": "InstrumentationKey='';LiveEndpoint=http://127.0.0.1:6001/;
  },
```

**Real Environment**
I have a similar experience in my actual Production environment.

When I use the machine's FDQN or just it's name  `SPECIFICMACHINENAME`, I don't see the DependencyTelemetry event created.

```
  "ApplicationInsights": {
    "ConnectionString": "InstrumentationKey='';LiveEndpoint=http://SPECIFICMACHINENAME:6001/;
  },
```
However, if I set the `LiveEndpoint` to be the `ip address` of the machine the DependencyTelemetry event is created and uploaded.

```
  "ApplicationInsights": {
    "ConnectionString": "InstrumentationKey='';LiveEndpoint=http://<The machine's IP>:6001/;
  },
```

**What is the expected behavior?**
What did you expect to see?

The DependencyTelemetry events should be created with an FDQN or Ip Address.

**What is the actual behavior?**
What did you see instead?

No DependencyTelemetry event is created. Specifically, the one from the `rdddsc:2.14.0-17971` SDK.

**Additional context.**
Specifically, it looks like this event:

![image](https://user-images.githubusercontent.com/1683309/81640229-d689ed00-93d2-11ea-99a7-905fceb86108.png)

Also, I tried Https and it doesn't seem to make any difference.

**Comment by rajkumar-rangaraj** [comment]
@aluong I could not recreate an issue. It is working as expected and hostnames are resolving in my environment. Could you please check the following.

Create a console app, make HttpClient call with hostname/IP and check if this works as expected in your environment. 

Also, in your connectionstring you have specified `LiveEndpoint`. This endpoint is used for live metrics. `IngestionEndPoint` is the place where all telemetries like request, dependency are sent.

**Comment by aluong** [comment]
Are there additional verbose logs I can generate with AppInsights to see why the DependencyTelemetry event is or is not being generated?

**Comment by rajkumar-rangaraj** [comment]
Yes. Collecting [SDK Troubleshooting logs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data#net-framework) should help

**Comment by aluong** [comment]
While attempting to reproduce the issue, I found out the problem goes away for me when I edit the `project` attribute in my .csproj from
```
<Project Sdk="Microsoft.NET.Sdk.Worker">
```
to 
```
<Project Sdk="Microsoft.NET.Sdk">
```

**Comment by rajkumar-rangaraj** [comment]
Thanks @aluong for the repro. Here is the root cause of an issue.

HttClient made from an app: http://localhost:8000
LiveEndPoint: http://localhost:8888

When a dependency call initiated from app has a hostname same of liveendpoint hostname, those specific dependencies are not tracked.

https://github.com/microsoft/ApplicationInsights-dotnet/blob/13217865d1797d44ceb87f87308a602248a6fdbb/WEB/Src/PerformanceCollector/PerformanceCollector/QuickPulseTelemetryProcessor.cs#L168

This code has comment explaining why this check is needed.

**Comment by aluong** [comment]
Thanks for tracking down the root cause.

**Comment by aluong** [comment]
Would it be possible for this check to consider the port as well, because we are forwarding all traffic through this proxy (AI + Other Service API calls). Consequently, the hostname will be the same, but the ports are different.
