### ISSUE TITLE
DefaultApplicationInsightsServiceConfigureOptions depends on obsolete IHostingEnvironment

### ISSUE THREAD

**Issue by george111cz** [microsoft/ApplicationInsights-dotnet#1869]
The [DefaultApplicationInsightsServiceConfigureOptions](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs) is dependent on [IHostingEnvironment](https://github.com/dotnet/aspnetcore/blob/master/src/Hosting/Abstractions/src/IHostingEnvironment.cs) which is obsolete.

This should be replaced, so that it depends on the new IHostEnvironment from Microsoft.Extensions.Hosting namespace.

**Comment by jorismathijssen** [comment]
Is there any (updated) information? We are probably having the same issue.

**Comment by TimothyMothra** [comment]
I'm looking into this as part of the 2.19 milestone.

**Comment by ranjanpoudel1234** [comment]
Hi @TimothyMothra , was this updated in 2.19 ?
