### ISSUE TITLE
No RequestTelemetry created in aspnet core TestServer

### ISSUE THREAD

**Issue by saikatguha** [microsoft/ApplicationInsights-dotnet#1871]
**Describe your environment.** 
* SDK version: dotnetc:2.12.0-21496
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): netstandard2.0
* Hosting Info (IIS/Azure WebApps/etc): In-process **TestServer** in **Azure Functions**
* Platform and OS version: dotnet, Azure Functions 2.x, Windows 10

**Steps to reproduce.**
1. Create a `Startup` class with `services.AddApplicationInsightsTelemetry()` in `ConfigureServices`.
2. Create a test server using `var server = new TestServer(new WebHostBuilder().UseStartup<Startup>())`
3. Execute a request on the test server using `await server.CreateClient().SendAsync(new HttpRequestMessage...)`

**What is the expected behavior?**
ApplicationInsights creates RequestTelemetry for the request just as it would for a normal Kestrel host. Additionally, the created `RequestTelemetry` is dependency injected into `HttpContext.Features` in the request processing pipeline. (This is what happens for normal Kestrel server.)

**What is the actual behavior?**
No RequestTelemetry is created. No `RequestTelemetry` is dependency injected into `HttpContext.Features` in the request processing pipeline.

**Additional context.**
Auto-collection of SQL/HTTP dependencies appears to not work in TestServer request handling pipeline (perhaps due to there not being a RequestTelemetry context).

**Code that works in console app**
```C#
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services) {
            services.AddApplicationInsightsTelemetry();
        }

        public void Configure(IApplicationBuilder app) {
            app.Use(async (context, next) => {
                await context.Response.WriteAsync(context.Features.Get<RequestTelemetry>()?.GetType().Name ?? "RequestTelemetry not found.");
            });
        }
    }

    public class Program
    {
        public static async Task Main(string[] args) {
            var testBuilder = new WebHostBuilder().UseDefaultServiceProvider(options => { }).UseStartup<Startup>();
            var testServer = new TestServer(testBuilder);
            var testClient = testServer.CreateClient();
            var testRequest = new HttpRequestMessage(HttpMethod.Get, "https://localhost:5001/");
            var testResponse = await testClient.SendAsync(testRequest);
            Console.WriteLine(await testResponse.Content.ReadAsStringAsync());
            // Prints: RequestTelemetry
        }
    }
```

**Code that does not work in functions app**
```C#
    public static class Function1
    {
        public class Startup
        {
            public void ConfigureServices(IServiceCollection services) {
                services.AddApplicationInsightsTelemetry();
            }

            public void Configure(IApplicationBuilder app) {
                app.Use(async (context, next) => {
                    await context.Response.WriteAsync(context.Features.Get<RequestTelemetry>()?.GetType().Name ?? "RequestTelemetry not found.");
                });
            }
        }

        [FunctionName("Function1")]
        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log) {
            var testBuilder = new WebHostBuilder().UseDefaultServiceProvider(options => { }).UseStartup<Startup>();
            var testServer = new TestServer(testBuilder);
            var testClient = testServer.CreateClient();
            var testRequest = new HttpRequestMessage(HttpMethod.Get, "https://localhost:5001/");
            var testResponse = await testClient.SendAsync(testRequest);
            return testResponse;
            // Returns: RequestTelemetry not found.
        }
    }
```

**Comment by cijothomas** [comment]
Functions lightup work differently. Its best to post this in functions repo.

**Comment by cijothomas** [comment]
here: https://github.com/Azure/azure-webjobs-sdk

**Comment by saikatguha** [comment]
Posted in functions as https://github.com/Azure/azure-webjobs-sdk/issues/2491
