### ISSUE TITLE
async ITelemetryInitializer implementation for .Net Core 3?

### ISSUE THREAD

**Issue by Ro3A** [microsoft/ApplicationInsights-dotnet#1872]
I have an azure function with TelemetryInitializer that adds the request body to request telemetry. This was working just fine. However, I've just updated from 2.2 to 3.1 and found it threw exceptions due to synchronous I/O exception when reading from request body. 

I've read through the entire thread regarding that issue:  https://github.com/dotnet/aspnetcore/issues/7644

ITelemetryInitializer is implemented with a synchronous public void Initialize method. I suppose it would be possible to implement the async void, but that's a bad practice. To further complicate matters, Azure Functions do not have middleware out of the box, so avoiding TelemetryInitializers in place of middleware is not an option as it is in Web Api. 

This leaves one with choices of running in 2.2 compatibility mode, enabling Synchrnous I/O, or using a hack to call ReadAsync from the synchronous Initialize method.

Will ITelemetryIntializer be updated to use public async Task thus affording one the ability to call ReadAsync on request body? If this will be updated, can you share the timeline on that change?

**Comment by bbrandt** [comment]
Is the workaround here the recommended practice for setting values in the request telemetry that require asynchronous retrieval, such as database values?

https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/686#issuecomment-530353448

**Comment by Ro3A** [comment]
@bbrandt 

Unfortunately, for Azure Functions that's not possible as there is no middleware without custom code. We use middleware in our APIs - but this issue is specific to Azure Functions.

In our functions, lacking middleware, we use ITelemetryInitializer to read the request body. And there really is no great way to handle response bodies, so we have a class / method to handle that when returning the response message.
