### ISSUE TITLE
How to Collect SQLText with AI on Azure ASPNetCore?

### ISSUE THREAD

**Issue by pseabury** [microsoft/ApplicationInsights-dotnet#1876]
**Describe your environment.**
Since moving to NETCore 3, I can't seem to get SQLText collected as part of the AI data.  This has worked in the past by just enabling AI in the portal.  Currently the only SQL reporting I get is a connection:

`tcp:MYDBSERVER.database.windows.net,1433 | MYDBNAME`

* SDK version:  AppInsights 2.14.0
* .NET runtime version :  NETCore 3.1.3
* Hosting Info (IIS/Azure WebApps/etc): Azure Webapp

When all of the AI features are enabled, I expect to see SQL Query text from dependencies, but I don't.  I've created new AppServices and redeployed to them with the same result.

![image](https://user-images.githubusercontent.com/1918526/82386719-b5408680-99fa-11ea-98dc-0d1b9dca4efb.png)

**Comment by cijothomas** [comment]
I assume you have added sdk via nugets. 2.14 has this breaking change as explained here: https://github.com/microsoft/ApplicationInsights-Announcements/issues/28

```
services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((module, o) => { module. EnableSqlCommandTextInstrumentation = true; }); 
```

**Comment by pseabury** [comment]
@cijothomas Yes I added the 2.14 SDK via nuget.  I hadn't explicitly opted in via code config, but I have now and this is working as I expect after the extra steps.

The [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query) linked from the [announcement ](https://github.com/microsoft/ApplicationInsights-Announcements/issues/28)is confusing though as illustrated below.

![image](https://user-images.githubusercontent.com/1918526/82397498-31949300-9a16-11ea-8b39-faf8c3da7b6c.png)

**Comment by anmol-agni** [comment]
@cijothomas Is this applicable to azure functions as well? I added the following line to my startup.cs class
**services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((module, o) => { module. EnableSqlCommandTextInstrumentation = true; });** 

I enabled the SQL monitoring in my function app on azure portal. But still I am not able to see the SQL commands getting logged. Is there anything specific I should do for function apps. 

Thanks in advance.

**Comment by cijothomas** [comment]
@anmol-agni Functions internally use the SDK from this repo. If functions are using the 2.14 version, then yes this change is applicable in functions too. How to turn on this feature in Azure functions - its best asked in the Functions repo, as Functions may require additional setting.

**Comment by cijothomas** [comment]
> @cijothomas Yes I added the 2.14 SDK via nuget. I hadn't explicitly opted in via code config, but I have now and this is working as I expect after the extra steps.
> 
> The [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query) linked from the [announcement ](https://github.com/microsoft/ApplicationInsights-Announcements/issues/28)is confusing though as illustrated below.
> 
> ![image](https://user-images.githubusercontent.com/1918526/82397498-31949300-9a16-11ea-8b39-faf8c3da7b6c.png)

https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query
The doc was updated, obviously sometime *after* you posted. Let us know if you have additional feedback.
