### ISSUE TITLE
Need to anonymise part of information that is logged

### ISSUE THREAD

**Issue by uandrei** [microsoft/ApplicationInsights-dotnet#1877]
**Describe your environment.**
Environment: Azure Function v3 with HTTP trigger

**What are you trying to achieve?**
The azure function receives as input a URL to connect to a storage account, and the URL contains valid SAS token in form of query string. Since the azure function logs any calls to storage accounts as dependencies, it will also log the SAS token. In our case this is problematic as we don't want to have SAS tokens logged at all.

The question basically is if there's a way to configure App Insights so that it either doesn't log the SAS tokens (or any query parameters for that matter) or anonymise the data

**Comment by cijothomas** [comment]
In application insights this can be achieved with TelemetryProcessors:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#filtering

(I dont think Functions support telemetryprocessors - but thats best to confirm in Azure-webjobs-sdk repo)

**Comment by peter-bertok** [comment]
This should be default behavior without requiring any form of customization.
