### ISSUE TITLE
Configuration issue with AzureKeyVault

### ISSUE THREAD

**Issue by Yalpe** [microsoft/ApplicationInsights-dotnet#1878]
Hi,

I noticed a difference in behavior in our docker services when configuring ApplicationInsights InstrumentationKey in a KeyVault using Microsoft.Extensions.Configuration.AzureKeyVault:

ServiceA (WorkerService)
ServibeB (AspNetCore)

The InstrumentationKey is null in appsettings.json and fetched from a KeyVault in our environments.  The result is this:

ServiceA **can** fetch the Instrumentation key using this configuration:
`
public void ConfigureServices(IServiceCollection services)
{
    services.AddApplicationInsightsTelemetry();
}
`

ServiceB **can not** fetch the Instrumentation key using this initialization:
`
public void ConfigureServices(IServiceCollection services)
{
    services.AddApplicationInsightsTelemetry();
}
`

ServiceB **can** fetch the Instrumentation key using this initialization:
`
public void ConfigureServices(IServiceCollection services)
{
    services.AddApplicationInsightsTelemetry(this.Configuration);
}
`

Now I'm not that knowledgeable with dotnet core configurations yet but I think the problem comes from this line https://github.com/microsoft/ApplicationInsights-dotnet/blob/d3319662bf15a1e58341b4e75291f5fe23e4d81b/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs#L31. I assume that since its not using my configuration object I have to force the code to configure the options by passing in the Configuration object https://github.com/microsoft/ApplicationInsights-dotnet/blob/d3319662bf15a1e58341b4e75291f5fe23e4d81b/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L67.

If I compare the code to the WorkerService, I noticed that the IConfiguration is injected instead. https://github.com/microsoft/ApplicationInsights-dotnet/blob/d3319662bf15a1e58341b4e75291f5fe23e4d81b/NETCORE/src/Microsoft.ApplicationInsights.WorkerService/DefaultApplicationInsightsServiceConfigureOptions.cs#L21

Could this be why the behavior is different?

**Comment by cijothomas** [comment]
This is known limitation of Asp.Net Core projects - it doesn't look at user IConfiguration for ikey. 
Worker service SDK does this.

But this is being addressed already, and should be available the next beta version.
cc: @rajkumar-rangaraj

**Comment by cijothomas** [comment]
@Yalpe - Btw your analysis is fully correct! thanks for spending time here, and hopefully no other customers would have to spend time on this, as we;ll have a fix for this very soon!

**Comment by cijothomas** [comment]
will be closed by this PR by @rajkumar-rangaraj  https://github.com/microsoft/ApplicationInsights-dotnet/pull/1850
