### ISSUE TITLE
ILogger.BeingScope should work

### ISSUE THREAD

**Issue by ChadNedzlek** [microsoft/ApplicationInsights-dotnet#1879]
**Is your feature request related to a problem?**
Currently, ILogger<T>.BeginScope just returns null, without doing any scoping.

**Describe the solution you'd like.**
It would be nice if it did something similar to
https://github.com/microsoft/ApplicationInsights-dotnet/blob/a26a43f012ef6afca563b43b16ab019698a3f062/LOGGING/src/ILogger/ApplicationInsightsLogger.cs#L53-L56
so that logging scope information could be tracked

**Describe alternatives you've considered.**
We are currently doing private reflection into this assembly to hook the scope creating back up (because the Provider is internal), so that it works. This is in our production service. This means our code is extremely fragile, so we can't take even minor version changes to this assembly, leaving us in a really bad place.

**Additional context.**

**Comment by cijothomas** [comment]
Not sure what is the ask here. ApplicationInsightsLoggerProvider is already doing this . What is the question/ask here?

**Comment by ChadNedzlek** [comment]
I might have opened this in the wrong repository... I need to find the Logger that isn't doing this (it's the one that you get when you follow the "Add Application Insights to ASP.NET docs"... I'll either update or move the issue in a momement...

**Comment by cijothomas** [comment]
There is an old loggerprovider which did not support scopes. But you shouldn't be using it anyway - all instructions or visual studio onboarding will give you only the new one.

**Comment by ChadNedzlek** [comment]
It does look like that's the case.  I wonder if our weird reflection is causing us to grab the old one, and if we just stopped doing that, we wouldn't have a problem.

Sorry for the wasted time. I'll close the issue. :-)
