### ISSUE TITLE
SQL not logging even though monitor is enabled (rddp:2.14.0-17971)

### ISSUE THREAD

**Issue by jjohnson23112** [microsoft/ApplicationInsights-dotnet#1881]
Cloud service classic
* SDK version: rddp:2.14.0-17971
* .NET runtime version: 4.6.1
* Hosting Info (IIS/Azure WebApps/etc): Cloud Service (classic)
* Platform and OS version: (family 5)

**Steps to reproduce.**
Install nuget package
Follow the steps to add the appinsightsagent folder and the PS file and the bat file
Deploy the cloud service

**What is the expected behavior?**
Expect to see dependencies logged with sql text

**What is the actual behavior?**
Only stored proc executions are logged the others just show the db name and the tcp port and do not show the sql

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-Announcements/issues/28

One need to opt-in to get sql text.

<Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">, 
<EnableSqlCommandTextInstrumentation>true</EnableSqlCommandTextInstrumentation>
</Add>

**Comment by jjohnson23112** [comment]
that fixed it thanks!!
