### ISSUE TITLE
Capturing AspNetCoreHosting counter events

### ISSUE THREAD

**Issue by eduardoluizm** [microsoft/ApplicationInsights-dotnet#1883]
Hello, I'd like to know why this configuration is not called on startup. Only ConfigureEventCounterModuleWithSystemCounters is called.

https://github.com/microsoft/ApplicationInsights-dotnet/blob/76916ab14471a9503c7e1d8d19a2b00507fae74c/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs#L426

Thanks!

**Comment by cijothomas** [comment]
Please refer to this issue:
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1759
