### ISSUE TITLE
AI handling 302 as an error in API Management

### ISSUE THREAD

**Issue by knuthalvor** [microsoft/ApplicationInsights-dotnet#1888]
Tried reporting this in the Home repo, but as that is now archived I'll have a go here.

So we have a .net core application doing a ControllerBase.Redirect ("url") (corresponding to a HTTP 302). However, when this then goes back the chain it is registered as a failure in AI for APIM - see example transaction attached.

As this is related to authentication, this happens quite regularly, and hence clutter the AI Failure overview with these errors.

1. is this really to be interpreted as an error in APIM?
2. what can we do to avoid it beeing logged to AI as an error?
![image](https://user-images.githubusercontent.com/25979569/83516673-cfd52e00-a4d7-11ea-9f1b-4ed58817d5a2.png)

**Comment by TimothyMothra** [comment]
You can add a custom TelemetryProcessor to your configuration and manually change the `requestTelemetry.Success` property to TRUE.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling

**Comment by knuthalvor** [comment]
We've tried this using a custom TelemetryInitializer with no success (https://github.com/Altinn/altinn-studio/blob/5abf01a24eebbed58b013698da723fa49927bb5e/src/Altinn.Platform/Altinn.Platform.Authentication/Authentication/Configuration/CustomTelemetryInitializer.cs#L22)
It looks to me that it is APIM that actually responds to the 302 as a failure in AI - not the application itself.
