### ISSUE TITLE
Dependency Tracker reports HTTP call as 500 but the caller reports a successful execution

### ISSUE THREAD

**Issue by EdmundoMartinez** [microsoft/ApplicationInsights-dotnet#1889]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version: 2.12.0
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): .Net Core 2.2
* Hosting Info (IIS/Azure WebApps/etc): Azure App Service.
* Platform and OS version: Windows (Azure App Service)

If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

**Steps to reproduce.**
Describe exactly how to reproduce the error. Include a code sample if applicable.
Our service is a Web API, it makes an HTTP call to a second service, reads the response and return the response to the caller.
What we notices is that the call from the our service to the second one is reported as success (200), but the dependency tracker logs the dependency as 500.

In the attached image, the second service request is logged as 200 (yellow), our service logged the request as 207 (means it didn't fail with 500) (green), but the dependency is logged with 500 (red):

![image](https://user-images.githubusercontent.com/28586870/83566724-51778c80-a4d5-11ea-993f-c2e4b4315933.png)

**What is the expected behavior?**
The dependency should have been logged with 200 instead of 500.

**What is the actual behavior?**
The dependency is logged with 500.

**Additional context.**
When we see the problem, it happens multiple times in very short amount of times (periods of time about 10s).

**Comment by rajkumar-rangaraj** [comment]
@EdmundoMartinez, App Service has front end and back end executable in his request execution pipeline. Front end process has the ability to change the status that was created by back end.  Correct way to troubleshoot an issue is to collect the Failed Request Tracing in App Service for dependent request and check if it has 500 status in it.

**Comment by EdmundoMartinez** [comment]
Thanks @rajkumar-rangaraj, we will configure Application Insights correctly to log the requests of the second App Service and will review the error logged by the framework.
