### ISSUE TITLE
Which TelemetryChannel/configurations to use in short-lived processes when reliability is a concern?

### ISSUE THREAD

**Issue by AElharouny** [microsoft/ApplicationInsights-dotnet#1895]
**Describe your environment.**
Describe any aspect of your environment relevant to the question:
* SDK version: 2.14.0
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): netcoreapp3.1
* Hosting Info (IIS/Azure WebApps/etc):  Azure Functions v3

**What are you trying to achieve?**
I want a recommendation of which TelemetryChannel to use in my scenario and best configuration I can use.

We are working on a solution that logs all messages coming to Azure Service Bus from a centralised Service Bus queue. We have an Azure Function (Consumption plan) Service Bus trigger. We want to achieve maximum reliability when sending events to application insights based on each message pulled from the queue. Processes are very short-lived, just sending telemetry.  And we are facing the following challenges:

- If we used ServerTelemetryChannel: Azure function can scale down, shutdown the instance before telemetry are flushed, even calling Flush() won't help much as its async.
- If we used InMemoryTelemetryChannel: Flush() is sync which is good, however, it doesn't throw up any exception during transmission, which can cause a message to be lost without being logged. If SDK throws transmission exception, we could have relied on queue retry to retry flushing.

Given that scenario what do you recommend as best configuration to use?

**Comment by rajkumar-rangaraj** [comment]
@AElharouny, Please check proposal in the issue #1743 could help. There is an active PR on it.

**Comment by AElharouny** [comment]
> @AElharouny, Please check proposal in the issue #1743 could help. There is an active PR on it.

That's awesome, proposal is perfect, can't wait to for it to be published!

**Comment by AElharouny** [comment]
I think this should be closed as FlushAsync has been implemented.
