### ISSUE TITLE
Need to be able to turn off metric aggregation

### ISSUE THREAD

**Issue by DavidParks8** [microsoft/ApplicationInsights-dotnet#1896]
**Is your feature request related to a problem?**
When running kubernetes, we are sending metric telemetry from within an asp.net core 3.1 app to geneva hosted on the local vm via statsd. The geneva statsd ingestion does not support ingesting aggregated data, as the geneva agent is designed to aggregate the telemetry automatically.

**Describe the solution you'd like.**
We need the ability to either turn off aggregation, or implement our own aggregator that skips aggregation entirely.

**Describe alternatives you've considered.**
We've considered re-implementing the entire auto collected metrics pipeline (really not ideal).

**Comment by cijothomas** [comment]
The current autocollected metric extractor are tied to Application Insights backend only.
Also, the pre-aggregating API does not allow plugging in a different Aggregator. (This was considered I think initially, but I dont expect any changes to that API in near term).

You alternative would be to use the non-aggregating metric API - TrackMetric() - this doesn't aggregate locally. You can even write a TelemetryProcessor to get the raw metric from this API as well, and do any custom aggregations as desired.

**Comment by DavidParks8** [comment]
Essentially, you are saying that we should implement our own auto collection?

**Comment by cijothomas** [comment]
Please tell me what do you mean by auto-collection in this context? 
We generally use auto-collection to refer the built-in telemetry modules like RequestTrackingModule, DependencyTracking module etc, which collects Requests and Dependencies automatically.

Then there is something called AutoCollectedMetricExtractor, which extracts standard metrics from the collected Requests, and Dependencies. (This component is very much specific to ApplicationInsights backend, as its meaning of StandardMetric is as defined here (https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftinsightscomponents)

Once I understand more of the requirement - I can share more suggestions.

**Comment by DavidParks8** [comment]
I am specifically referring the the AutoCollectedMetricExtractor. We love the metrics it provides and would like to emit them without aggregating the data.

**Comment by DavidParks8** [comment]
We've already replaced the telemetry channel to send to statsd instead of the app insights backend.

**Comment by cijothomas** [comment]
> I am specifically referring the the AutoCollectedMetricExtractor. We love the metrics it provides and would like to emit them without aggregating the data.

Got it. This module is intended to produce **pre-aggregated** metric as expected by ApplicationInsights backend. Hence, it wont expose metric without aggregation.

You'll need to implement CustomAutoCollectedMetricExtractor, if you want to extract the metric without aggregation.
