### ISSUE TITLE
Enable Deterministic builds

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1905]
[NuGet Package Explorer](https://www.microsoft.com/en-us/p/nuget-package-explorer/9wzdncrdmdm3) is a tool that can be used to inspect the contents and quality of a NUPKG.
This shows that our builds are non-deterministic and this needs to be fixed.
Eddy has already started working on this. I'm opening this issue to track his work.

![image](https://user-images.githubusercontent.com/28785781/84196408-ff92b180-aa54-11ea-9da0-81f34737b7c7.png)

https://github.com/microsoft/ApplicationInsights-dotnet/blob/d2e6e7b0ed975485a483f2b67f9be7b02186f9e5/.props/_Nupkg.props#L51-L60

**Comment by eddynaka** [comment]
Right now, we have two files that are appearing as non-deterministic:
```xml
<file id="282" name="E:\A\_work\20\obj\Microsoft.ApplicationInsights\Release\src\Microsoft.ApplicationInsights\net45\.NETFramework,Version=v4.5.AssemblyAttributes.cs" language="C#" checksumAlgorithm="SHA256" checksum="xxxx">
<file id="283" name="E:\A\_work\20\obj\Microsoft.ApplicationInsights\Release\src\Microsoft.ApplicationInsights\net45\Microsoft.ApplicationInsights.AssemblyInfo.cs" language="C#" checksumAlgorithm="SHA256" checksum="xxxx">
```

we are generating two AssemblyInfo's: one from properties/AssemblyInfo.cs and one from the properties from .csproj / .props files. When we do that, we have a non-deterministic problem. To test I moved all content from the .csproj and .props to the AssemblyInfo.cs and added the tag `GenerateAssemblyInfo` as false. With that, just the AssemblyAttributes showed as error.

**Comment by eddynaka** [comment]
One way to validate is:
1. Open the Nuget Package Explorer
2. Open the .nupkg
3. Click in one framework
4. click in the .pdb
5. list to the end, you will probably see two paths that aren't following the raw.git pattern

**Comment by TimothyMothra** [comment]
This is done
<img width="206" alt="image" src="https://user-images.githubusercontent.com/28785781/168399588-e9ab737f-ae85-4a43-8aed-a1bc971b651c.png">
