### ISSUE TITLE
Performance Counters Not showing 

### ISSUE THREAD

**Issue by t525** [microsoft/ApplicationInsights-dotnet#1908]
Describe your environment. Describe any aspect of your environment relevant to the problem:
SDK version: 2.12
.NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): .net 4.6.2
Hosting Info (IIS/Azure WebApps/etc): IIS
Platform and OS version: Windows 10
If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

**Steps to reproduce.**
Describe exactly how to reproduce the error. Include a code sample if applicable.
Performance counters (CPU, Memory, Storage) are not showing in Application Insights.  I have the performance counter setup in appinsights.config and made sure to include the application pool identity user to Performance Monitor and Performance Log user groups.  Is there anything else that needs to be done for this to work?

**What is the expected behavior?**
What did you expect to see?
Performance counter metrics should be shown.

**What is the actual behavior?**
What did you see instead?
Nothing is showing for performance counters.

**Additional context.**

**Comment by TimothyMothra** [comment]
Hello, You can review the trace messages to see if there are any SDK errors.
Here is some more information: https://github.com/microsoft/ApplicationInsights-Home/tree/master/Samples/ETW

This is commonly a permissions error when accessing perf counters.
