### ISSUE TITLE
Different AssemblyName across *.props files

### ISSUE THREAD

**Issue by eddynaka** [microsoft/ApplicationInsights-dotnet#1917]
If we list Test.Props files, we will see some differences:
base/test.props
```xml
  <PropertyGroup>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>
```

dependencycollector/test.props
```xml
  <PropertyGroup>
    <AssemblyName>$(RootNamespace).$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>
```

Web/Test.props
```xml
  <PropertyGroup>
    <AssemblyName>Microsoft.ApplicationInsights.$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>
```

e2etests/test.props
```xml
  <PropertyGroup>
    <AssemblyName>$(RootNamespace).$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>
```

Web/Test/test.props
```xml
  <PropertyGroup>
    <AssemblyName>$(RootNamespace).$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>
```

Question: does it matter what would be the assembly name for our test projects? If no, can we add this section to Test.props inside .props (root folder) and make all reference this?
```xml
  <PropertyGroup>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>
```

**Comment by TimothyMothra** [comment]
I would expect AssemblyNames to be defined in their csproj file.
If I needed to lookup a project's AssemblyName, that's the first place I would inspect.
I'm spot-checking our csprojs and most of them already define the AssemblyName.
I think we should try to remove this from the props.
