### ISSUE TITLE
AddApplicationInsights from ILoggingBuilder does not automatically load configuration like its IServiceCollection counterpart

### ISSUE THREAD

**Issue by jackj93** [microsoft/ApplicationInsights-dotnet#1926]
**Describe your environment.**
Describe any aspect of your environment relevant to the question:
* SDK version: 2.14.0
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): netcoreapp3.1
* Hosting Info (IIS/Azure WebApps/etc): Azure WebApps
* Platform and OS version: Linux

**What are you trying to achieve?**
What did you expect to see?
Using AddApplicationInsights from Program.cs with no parameters, I expect to see the same behavior as if I were to call AddApplicationInsights from ConfigureServices in Startup.cs
other than registering a logging provider with ILogger.

Adding AddApplicationInsights to Startup.cs will try to retrieve the instrumentation key from:
  1. environment variables
  2. appsettings
without additional configuration, but with AddApplicationInsights within ConfigureLogging with ILoggingBuilder this is not the case.

Are there plans to make these two things have the same functionality?

**Comment by cijothomas** [comment]
Which SDK are you using? `Microsoft.ApplicationInsights.AspNetCore` or `Microsoft.Extensions.Logging.ApplicationInsights` ?
Please share code snippets as well (of addapplicationinsights in program.cs/startup.cs) so we can better understand the issue.

**Comment by jackj93** [comment]
The `AddApplicationInsights` comes from the namespace `Microsoft.Extensions.Logging` which I gathered comes from [here](https://github.com/microsoft/ApplicationInsights-dotnet/blob/a26a43f012ef6afca563b43b16ab019698a3f062/LOGGING/src/ILogger/ApplicationInsightsLoggingBuilderExtensions.cs)

Code snippet below:
```csharp
        public static void Main(string[] args)
        {
            Program.CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(
                    (context, logging) =>
                    {
                        logging.ClearProviders();
                        logging.AddApplicationInsights();
                    })
                .ConfigureWebHostDefaults(
                    webBuilder =>
                    {
                        webBuilder.UseStartup<Startup>();
                    });
```

**Comment by cijothomas** [comment]
Please reply to my other questions as well. Also post snippet which you have for startup.cs

**Comment by jackj93** [comment]
I currently do not have anything related to logging in Startup.cs
Are you saying that I need both to be able to use the default `ILogger` with ApplicationInsights?

I'm using both libraries I believe

**Comment by jackj93** [comment]
I read the source code and got my answer. Looks like the behavior is just different between the two.
Thank you for your time
