### ISSUE TITLE
DependencyTrackingTelemetryModule not capturing SQL Commands in telemetry properties.

### ISSUE THREAD

**Issue by BibhutiBhusanDora** [microsoft/ApplicationInsights-dotnet#1935]
**Describe your environment.**
Describe any aspect of your environment relevant to the question:
* SDK version: 
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file): 4.6.1
* Hosting Info (IIS/Azure WebApps/etc): IIS/IISExpress
* Platform and OS version: Windows 7

**What are you trying to achieve?**
What did you expect to see?
I am trying to track the SQL calls made by the dependent dlls(these dlls use SQLClient) , but i am not seeing the SQL Commands.I only see the target SQL DB and the duration that the call have taken in telemetry properties. I have a .net core version of the same application and am able to track the SQL commands without any issue.
ApplicationInsights.config:-
![image](https://user-images.githubusercontent.com/46517093/85855769-6b567780-b7d4-11ea-9428-44420286773e.png)

VS Debug window:-
![image](https://user-images.githubusercontent.com/46517093/85855133-634a0800-b7d3-11ea-9aed-703e92fb2c5b.png)
Packages.config:-
![image](https://user-images.githubusercontent.com/46517093/85855892-9a6ce900-b7d4-11ea-9db3-6f02ea6b5351.png)

**Additional context.**

**Comment by cijothomas** [comment]
Modify ai.config to have EnableSqlCommandTextInstrumentation
<Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">, 
<EnableSqlCommandTextInstrumentation>true</EnableSqlCommandTextInstrumentation>
</Add>

**Comment by BibhutiBhusanDora** [comment]
> <Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">, 
> <EnableSqlCommandTextInstrumentation>true</EnableSqlCommandTextInstrumentation>
> </Add>

Thanks for the quickest response.
As mentioned, changed the ai.config. Still no luck.
For debugging puropose, I wrote a custom telemetry channel and I do see null value is being passed in CommandText.
![image](https://user-images.githubusercontent.com/46517093/85869265-15d89580-b7e9-11ea-88f4-9dd2ab5b3a83.png)

**Comment by cijothomas** [comment]
Are you using System.Data.SqlClient or Microsoft.Data.SqlClient? Which version?
