### ISSUE TITLE
What's the story for .Net Core WinForms and WPF with deprecation of singletons

### ISSUE THREAD

**Issue by sadjadbp** [microsoft/ApplicationInsights-dotnet#1937]
Regarding #1152 with new .Net Core 3.0 and above and WinForms and WPF they don't have ServiceCollection model (dependency injection) specially WPF. What the right way of using singleton and telemetry client?

`var telemetryClient = new TelemetryClient();`

gives deprecation warning.

**Comment by TimothyMothra** [comment]
Try this:

```
var config = TelemetryConfiguration.CreateDefault();
var client = new TelemetryClient(config);
```
