### ISSUE TITLE
Add a way to limit max file size in FileDiagnosticsTelemetryModule

### ISSUE THREAD

**Issue by Pikhulya** [microsoft/ApplicationInsights-dotnet#1938]
We are considering to leverage FileDiagnosticsTelemetryModule in an Azure App Service as a way to log to a file system in emergency cases when App Insights cannot be reached by any reason. But the FileDiagnosticsTelemetryModule doesn't provide a way to limit a max file size and allowing it to grow infinitely doesn't look safe. If this feature is really missing - can you consider it?

**Comment by cijothomas** [comment]
Yes this is a known limitation and will be considered.
@TimothyMothra is working on changes to this area.

**Comment by Pikhulya** [comment]
I wonder if you have updates on the availability.

**Comment by cijothomas** [comment]
This is part of the newly released self-diagnostics capability
https://github.com/microsoft/ApplicationInsights-dotnet/tree/develop/troubleshooting/ETW#self-diagnostics
