### ISSUE TITLE
Dependency Telemetry has result code faulted

### ISSUE THREAD

**Issue by shikhil-gupta** [microsoft/ApplicationInsights-dotnet#1939]
**Describe your environment.** Describe any aspect of your environment relevant to the problem:
* SDK version:  
* .NET runtime version (.NET or .NET Core, TargetFramework in the .csproj file):  netcoreapp2.1
* Hosting Info (IIS/Azure WebApps/etc):  Hosted on Azure using window VMs
* Platform and OS version: Windows 

If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on master.

we are using Application Insight SDK. Here is link of nuget package
https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore

**Steps to reproduce.**
Describe exactly how to reproduce the error. Include a code sample if applicable.
It is difficult to reproduce. 

**What is the expected behavior?**
What did you expect to see?
we should have proper HTTPs Code in Dependency telemetry.

**What is the actual behavior?**
What did you see instead?
We have observed from dependent down stream services that call went through it successfully after checking their logs, 
but still result code in dependency telemetry has **Faulted** Value

**Additional context.**

**Comment by TimothyMothra** [comment]
Can you give us an example of the Faulted value?
Either the quote of the exception message or a screenshot to help us understand.

Please share the version number of the nuget package you're using.

**Comment by shikhil-gupta** [comment]
Hi @TimothyMothra  we are using application insight SDK 2.14.0 and here is exception I saw in Geneva for that request

{"PreciseTimeStamp":"2020-06-30T08:22:06.0077253Z","message":"One or more errors occurred. (An error occurred while sending the request.)","MS_ProcessedByMetricExtractors":"(Name:'Exceptions', Ver:'1.1')","_MS_ProcessedByMetricExtractors":"(Name:'Exceptions', Ver:'1.1')","duration":"0","operation_ParentId":"eae7e0a216066642","sdkVersion":"il:2.14.0-17971","source":"System.Private.CoreLib","timestamp_utc":"2020-06-30T08:22:06.0077019Z","CategoryName":"Microsoft.AspNetCore.Server.Kestrel","ConnectionId":"0HM0RAKQ8B8RN","EventId":"13","EventName":"ApplicationError","FormattedMessage":"Connection id \"0HM0RAKQ8B8RN\", Request id \"0HM0RAKQ8B8RN:00000001\": An unhandled exception was thrown by the application.","Level":"2","RequestId":"0HM0RAKQ8B8RN:00000001","RequestPath":"/api/apps","TraceIdentifier":"0HM0RAKQ8B8RN:00000001","assembly":"System.Threading.Tasks.Task`1, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","innermostAssembly":"System.AggregateException","innermostMethod":"GetResultCore","outerAssembly":"System.Net.Sockets.SocketException","outerMessage":"An existing connection was forcibly closed by the remote host","problemId":"","severityLevel":"3","stackTrace":"   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at Microsoft.Admin.Coherence.Services.RestAPIs.Controllers.AppsController.GetAppList(String workloads) in d:\\dbs\\el\\9e7b\\sources\\dev\\Coherence\\RestAPIs\\Controllers\\AppsController.cs:line 64\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)\r\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.ServiceFabric.Services.Communication.AspNetCore.ServiceFabricMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)","type":"System.AggregateException","_OriginalFormat_":"Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application."}

**Comment by cijothomas** [comment]
Dependencies will have resultcode matching the http code when the http call did receive a response. If the call failed at client side, then there wont be any additional information. Dependency will be marked failure, and the ResultCode will be that of the Task status, which will be Faulted and nothing more. DependencyTracking module does not capture more information.

The above exception is capture by ilogger - it contains the exception. 

There is no bug to investigate. If otherwise, please share a isolated repro and explanation of expected behavior and actual behavior.

**Comment by shikhil-gupta** [comment]
@cijothomas How did you say that above exception is captured by iLogger library?

**Comment by cijothomas** [comment]
"sdkVersion": "il:2.14.0-17971", - this tells who captured a particular telemetry. "il" tells its ilogger. Dependency would have been "rdddsc" or "rdd...something"
https://github.com/microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/SDK-VERSIONS.md
