### ISSUE TITLE
Exception: Method not found: 'Void System.Diagnostics.Tracing.EventSource.WriteEvent(Int32, Int32, System.String)'.

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-dotnet#194]
Framework 4.6
Worker roles crashes with:
_AppDomain Unhandled Exception for role WorkerRole1_IN_0
Exception: Method not found: 'Void System.Diagnostics.Tracing.EventSource.WriteEvent(Int32, Int32, System.String)'.
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource.DiagnoisticsEventThrottlingSchedulerTimerWasCreated(Int32 intervalInMilliseconds, String appDomainName)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnoisticsEventThrottlingScheduler.ScheduleToRunEve_

Failure happens in diagnostics module. Web SDK catches this exception but there would be no internal telemetry available. Core SDK starting from the next SDK version would add Diagnostics module by default. In case there is no global catch in the worker role where it sets instrumentation key, it crashes.
Note: Azure does not support 4.6 now but I ignored the warning and tried to deploy anyway. ApplicationInsights becomes first point of failure.
This should also happen if 4.6 application just uses Core SDK and initializes everything programmatically.

Workaround: http://stackoverflow.com/questions/32097492/method-not-found-void-system-diagnostics-tracing-frameworkeventsource-beginget 

@alancameronwills We need to add this to some troubleshooting page or known issues list
@SergeyKanzhelev We can check method signatures that we use and try to exclude (int, int, string) if that is possible. Though I do not know if that is the only problematic signature.

**Comment by SergeyKanzhelev** [comment]
So you build 4.6 app and deploy to the environment with no 4.6 available? I'm surprised it is the only thing that fails in this case =) 

Why would we crash the application? Can we just catch this exception?

**Comment by abaranch** [comment]
1. We cannot put try/catches around all places that we use EventSource. 2. I did not notice warning about cloud apps and 4.5; nothing prevents you from deploying it, moreover Web Role seemed to worked perfectly fine. When you see this failure that may not be obvious what happened.

**Comment by alancameronwills** [comment]
I guess all we can say is that if you come across this problem, please note that you can't deploy a 4.6 app to Azure (yet). It might look like an AI problem, but you'd likely see the issue elsewhere in your app anyway.

I don't understand your link to the workaround, which is talking about WP8.1.

**Comment by abaranch** [comment]
@alancameronwills Yes, I think it would be great to add a stack and mention that it is not AI problem but that application is deployed to the box that does not have 4.6. For cloud apps your workaround link is good. But that would happen with any application that is compiled as 4.6 and deployed to the box with 4.5 (that I why I included my link; it is a general problem that is not related to AI. We do not need to include it but in one of the answers there is a link to 4.6 installer)

@SergeyKanzhelev If we have documentation I think it is fine to live it as is

**Comment by SergeyKanzhelev** [comment]
Agreed. 

Just for my education - is there a specific function that doesn't exists in 4.6 any longer or the same code choose different overloads depending of which framework we are building it for? Still trying to understand where the problem is.

**Comment by abaranch** [comment]
I do not really know. By the exception message it looks like it is specific to a signature. But since we decided to only document I did not spend time on a deeper investigation.

**Comment by SergeyKanzhelev** [comment]
Yes, this method only available after 4.6: https://msdn.microsoft.com/en-us/library/dn823290.aspx

Method `Initialize` of DiagnosticsTelemetryModule` do not catch exceptions:
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/4dd948ef9c4ca26ecfd6e76adf3e5af0f59d7bcf/src/Core/Managed/Shared/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs#L108

It causes configuration factory to throw when it calls that method:
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/c3a6b645b294ccd569d4c82530abb82d6054557f/src/Core/Managed/Net40/Extensibility/Implementation/TelemetryConfigurationFactory.cs#L270

Which in turn will throw when accessing `Active` configuration.
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/4dd948ef9c4ca26ecfd6e76adf3e5af0f59d7bcf/src/Core/Managed/Shared/Extensibility/TelemetryConfiguration.cs#L46

I'd say we need to have a global catch in initialization so faulty module wouldn't take application down.

**Comment by abaranch** [comment]
Agree. Let's do it.

**Comment by abaranch** [comment]
@alancameronwills I'm closing because we updated SDK to not use problematic methods in the next version.  But it would be nice to have information about this issue on our troubleshooting page
