### ISSUE TITLE
[Suggestion] Log4Net Appender Errors are sent as Traces

### ISSUE THREAD

**Issue by itcotta** [microsoft/ApplicationInsights-dotnet#1940]
In https://github.com/microsoft/ApplicationInsights-dotnet/blob/a26a43f012ef6afca563b43b16ab019698a3f062/LOGGING/src/Log4NetAppender/ApplicationInsightsAppender.cs#L207
at the SendException() function we make use of 
`this.telemetryClient.Track(exceptionTelemetry);`
Would it not make more sense to use TrackException() instead here? 
Because of this in application insights, all exception logs end up as traces.

**Comment by cijothomas** [comment]
`Track` doesn't mean telemetry ends up in trace. 
Please share a repro if you see exceptions ending up in traces due to the usage of `Track`.

**Comment by TimothyMothra** [comment]
Please note that internally, `TrackException` also calls `Track`.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/4c9256c1e81356d731024fc82204ebbc2a05220b/BASE/src/Microsoft.ApplicationInsights/TelemetryClient.cs#L303-L312

The `Track` method accepts all of our telemetry types.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/4c9256c1e81356d731024fc82204ebbc2a05220b/BASE/src/Microsoft.ApplicationInsights/TelemetryClient.cs#L434-L460

**Comment by itcotta** [comment]
I apologize for my misunderstanding then, you may close this ticket!
