### ISSUE TITLE
How to set ConnectionString using ILogger?

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1944]
We have an internal customer using ILogger, and they need to set the ConnectionString but it appears that we don't expose that in the ILogger SDK.

We have a constructor overload that would permit this, but it's currently set to private.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/a26a43f012ef6afca563b43b16ab019698a3f062/LOGGING/src/ILogger/ApplicationInsightsLoggingBuilderExtensions.cs#L90-L100

I propose we set this to public to unblock this customer.

@cijothomas do you know of any workarounds?

**Comment by cijothomas** [comment]
If using, DI then the following should work as shown in doc example
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#console-application

```
services.Configure<TelemetryConfiguration>(
            (config) =>
            {
                config.ConnectionString  = "";
            }
        );
```

**Comment by rajkumar-rangaraj** [comment]
There is an active PR #1643 to make this method as public.

**Comment by TimothyMothra** [comment]
Thanks Raj, We may need to fork this PR and finish it ourselves.

**Comment by TimothyMothra** [comment]
@cijothomas, can you help explain how the DI works?

If a customer makes this call:
```
services.AddLogging(config =>
 {
 config.AddApplicationInsights(instrumentationKey);
 config.AddConsole();
 });
```

Internally, the AddApplicationInsights will case

**Comment by pawel-zolty** [comment]
Hi I would appreciate if this change will be merged. Azure recommend to use connection string instead of Instrumentation keys. But it is impossible to do when I need to configure Logger in ASP.Net core Program.cs

**Comment by cijothomas** [comment]
> Hi I would appreciate if this change will be merged. Azure recommend to use connection string instead of Instrumentation keys. But it is impossible to do when I need to configure Logger in ASP.Net core Program.cs

Agree. this should be prioritized for the coming release.
