### ISSUE TITLE
Attaching UserID doesn't work outside basic scenarios

### ISSUE THREAD

**Issue by mindingdata** [microsoft/ApplicationInsights-dotnet#1947]
* Runtime version netcoreapp3.1
* Local .NET Core

### Describe the bug

This is basically identical to this bug a couple of years ago and we have the exact same problem https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/655

It boils down to this. 

If I create a middleware that sets certain properties for example

```
HttpContext.Items["stuff"] = "abc";
```

In my case I have a middleware layer that sets the User/Organization Id inside the HTTPContext. 

I've created a ITelemetryProcessor as this seems to be the processor that runs *last* e.g. Just before it's about to be sent. I have this code : 

```
public void Process(ITelemetry item)
{
    var requestTelemetry = item as RequestTelemetry;
    if (requestTelemetry != null)
    {
        var something = _httpContextAccessor.HttpContext.Items["stuff"] = "abc";
    }
}
```

If I put a breakpoint inside the TelemetryProcessor *and* inside my Middleware that actually sets the HttpContext items, the TelemetryProcessor runs before my code that sets the things I need to get. 

How can any custom authentication/authorization process ensure that it gets run *before* the request telemetry is sent? Is there a way?

**Comment by cijothomas** [comment]
Please share a minimal repro app showing how the middleware is added and how it populates things.
Telemetryprocessors are called when the Request is completed, so all middleware must have been complete by then. Need to have an isolated repro to investigate this.
