### ISSUE TITLE
TelemetryChannel found a telemetry item without an InstrumentationKey

### ISSUE THREAD

**Issue by parvathya** [microsoft/ApplicationInsights-dotnet#1956]
We keep seeing above error in our application insights traces - We have set the instrumentation key - in fact it logs valid traces most of the time - but we also see this error intermittently
TelemetryChannel found a telemetry item without an InstrumentationKey. This is a required field and must be set in either your config file or at application startup.
below is a code snippet that 
            TelemetryConfiguration.Active.InstrumentationKey = instrumentationKeyValue;
            TelemetryConfiguration.Active.TelemetryInitializers.Add(new ABCTelemetryInitializer(cloudRoleName, cloudRoleInstance));
            services.AddApplicationInsightsTelemetry();
we are using Microsoft.ApplicationInsights.AspNetCore Version=2.14.0

**Comment by cijothomas** [comment]
The snippet uses TelemetryConfig.Active which is not supported for Asp.net core.

https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#configure-the-application-insights-sdk 
Follow the instructions from here to configure ikey and initializers correctly. If you have issues after following this doc, please share a small minimal repro where you see this behavior.
