### ISSUE TITLE
2.15 Docs update: ApplicationInsightsServiceOptions

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1957]
As part of the work for .Active, Heartbeat, and File logging, I'll be introducing new settings to the `ApplicationInsightsServiceOptions`.
These need to be documented when we release the stable version of 2.15

https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#using-applicationinsightsserviceoptions

TODO
- list all new options
- provide description and default value

**Comment by TimothyMothra** [comment]
Is it possible to replace this table with a link to the API doc?
The API doc is supported to auto-update from the XML summary in the SDK itself.
This could eliminate the maintenance on this page.

**Comment by cijothomas** [comment]
Need to include @rajkumar-rangaraj configuration change as well to docs. (it could be tracked elsewhere just mentioning here)

**Comment by cijothomas** [comment]
Can you share the link to the API doc? I dont know if one exist for anything but BASE SDK.

**Comment by TimothyMothra** [comment]
i'm looking for that now

**Comment by TimothyMothra** [comment]
@cijothomas I think you're right. I'm only finding the Base SDK here.
It is current as of 2.14.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.extensibility.implementation.tracing.diagnosticstelemetrymodule?view=azure-dotnet

**Comment by TimothyMothra** [comment]
@mrbullwinkle Do you know how we could get our other SDKs on this site?

**Comment by cijothomas** [comment]
I think its intentional to document just the base sdk - as thats the real API. Everything else is "auto collectors" build on top on the API, and may not be a right candidate for the docs/api page.

**Comment by TimothyMothra** [comment]
Leaving a reminder here...
I think the Functions configuration could be greatly simplified by our improvements to the configuration story. 
https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Extensions/ApplicationInsightsServiceCollectionExtensions.cs#L138-L195

After we release 2.15, I think we could help them simplify this.
