### ISSUE TITLE
Asp.Net core synthetictelemetryinitializer is not configurable.

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#1963]
**Is your feature request related to a problem?**
The SyntheticTelemetryInitializer for Asp.Net Core (https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/SyntheticTelemetryInitializer.cs), is hard coded to detect only the Azure Availability Test traffic. And there is no option to configure it to mark additional sources.
The SyntheticTelemetryInitializer for Asp.Net (https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/Web/Web/SyntheticUserAgentTelemetryInitializer.cs), is configurable, and has a default list which meets most user's requirements (https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/Web/Web/net452/ApplicationInsights.config.install.xdt#L8)

**Describe the solution you'd like.**
Make Asp.Net core syntheticinitializer match the capabilities of asp.net one.

**Describe alternatives you've considered.**
Users have to author own initializer, which is not a good workaround.

**Comment by fabricebauer** [comment]
I have created a separate initializer for this (to avoid impacting this one) for our own private project.
I would like to contribute, and will submit a Pull Request for it.
