### ISSUE TITLE
Automatic/Custom metrics for NLog target

### ISSUE THREAD

**Issue by Alstofor** [microsoft/ApplicationInsights-dotnet#1967]
**Problem**: a project heavily uses NLog as a logging engine because of its ability to send traces to different destinations: file, console, memory, DBs... Thanks for the AppInsights target! It's great we can leverage Azure abilities to work with traces/exceptions without replacing existing targets. What we miss are metrics - in order to add instrumentation we need either duplicate logging handling with explicit use of TelemetryClient or implement our logging layer to combine Azure metrics with file/console/memory output.

**Solution**: it would be nice to have both implicit and explicit metric counters as a part of NLog target.

**Comment by cijothomas** [comment]
There are no investments planned in logging adapters (except ILogger). Metrics and Logs are separate concern, and Application Insights would recommend to have metrics send separately If customer doesn't want to use TelemetryClient directly to emit metrics, the recommended approach is to use EventCounters.
