### ISSUE TITLE
How to disable random profiler data collection

### ISSUE THREAD

**Issue by felipepessoto** [microsoft/ApplicationInsights-dotnet#1970]
How can I disable the automatic random profiles, while still been able to run manually profiles using the "Profile Now" button

**Comment by TimothyMothra** [comment]
Are you asking about the [Azure Application Insights Profiler](https://docs.microsoft.com/en-us/azure/azure-monitor/app/profiler-settings)?

This isn't our product, this github repo is for the DotNet Application Insights SDK.

For help with other products, please open a support request within the UI.
![image](https://user-images.githubusercontent.com/28785781/87993485-7765ea00-ca9f-11ea-8eb5-2861ad892f8f.png)
