### ISSUE TITLE
ILogger: Ability to add a tag and/or CorrelationId to a log entry

### ISSUE THREAD

**Issue by btastic** [microsoft/ApplicationInsights-dotnet#1971]
* Microsoft.Extensions.Logging.ApplicationInsights 2.14.0
* Runtime version: netcoreapp3.1
* Local dev environment

**What are you trying to achieve?**
Add a custom property for every log request while just using `services.AddApplicationInsights("iKey")`.
Something like "Tag" would be great.

We have like 5-6 microservices, each running in a separate pod. We would like to log to one single ApplicationInsights instance, and then filter from there on. Either via the "Tag" I'd love to give each service, or via a separate "CorrelationId" which would be generated by our API gateway, and given further down to each subsequent request in our microservice architecture.

Is anything like that possible? We already had a look at the ELK project, and there is something like that. I was looking for something like that in AI logging.

(for reference: https://github.com/elastic/ecs-dotnet/blob/master/src/Elasticsearch.Extensions.Logging/ReadMe.md)

**What have you tried so far?**
- Had a look at `AddApplicationInsights` configure action whether there was anything..
- Had a look at the other similar issues this repo
- Had a look at TelemetryProcessors, but they don't seem to get executed?

**Comment by cijothomas** [comment]
The right approach is to use TelemetryInitializer - https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#addmodify-properties-itelemetryinitializer

**Comment by btastic** [comment]
Yes you're right. We already implemented the kubernetes package which almost does everything we wanted.

For anyone else looking for something similar: https://github.com/microsoft/ApplicationInsights-Kubernetes

Thanks!
