### ISSUE TITLE
How do you correctly get TelemetryClient dependency injected in ASP.NET Core?

### ISSUE THREAD

**Issue by iamalexmang** [microsoft/ApplicationInsights-dotnet#1972]
Premise:
- Using the latest version (2.14.0) of `Microsoft.ApplicationInsights.AspNetCore`.
- Brand new project
- Following documentation and instructions available here https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core

In a brand new ASP.NET Core project on .NET Core 3.1, I've installed Microsoft.ApplicationInsights.AspNetCore, version 2.14.0. As per the documentation article linked above, I've added an ApplicationInsights configuration section with the InstrumentationKey property inside.
Additionally, I called the `.AddApplicationInsightsTelemetry()` extension method on the services collection, in order to enable Application Insights telemetry collection.

Irrelevant of whether or not I'm doing any additional steps, what I'm getting in terms of dependency inject via parameter constructors at this point is:
- if I add a TelemetryClient parameter to a controller's constructor, the type will be resolved (suggesting that the extension method did configure the type), but it won't get instantiated with any of the telemetry configuration that I might configure. Additionally, it doesn't even contain an instrumentation key. If I would add any telemetry initializers, these would not be added to the injected TelemetryClient either
- if I add a TelemetryConfiguration parameter to a controller's constructor, I get a properly configured telemetry configuration as per the options configured via the ApplicationInsightsServiceOptions object passed as a parameter to AddApplicationInsightsTelemetry method, or the default options.

This suggests that I should either:
- register the TelemetryClient object for dependency injection myself,
- or that dependency inject doesn't work for a TelemetryClient object type

As per https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#how-can-i-track-telemetry-thats-not-automatically-collected, _A singleton instance of TelemetryClient is already registered in the DependencyInjection container, which shares TelemetryConfiguration with rest of the telemetry_. However, this does not seem to be the case.

As per #1152, TelemetryConfiguration.Active, as well as the instantiation of the TelemetryClass constructor in deprecated.

Additionally, as per the same documentation referenced before, "_We don't recommend creating new TelemetryClient instances in an ASP.NET Core application_". 

This does then beg the question - **how would you correctly instantiate it then**? The documented way does not yield the documented results, the only possible way is deprecated or not recommended.

**Comment by iamalexmang** [comment]
For context:
![image](https://user-images.githubusercontent.com/5773281/88299918-936dc380-cd0b-11ea-9d00-0a9f539dd819.png)

**Comment by jcgeorgia** [comment]
I have a similar question: Most Add*() methods for ConfigureServices() take in a Func<IServiceProvider, *>. However, AddApplicationInsightsTelemetry() doesn't, which makes it difficult to access configuration services. What is the recommended way of accessing services / configuring TelemetryConfiguration prior to calling AddApplicationInsightsTelemetry()?

**Comment by cijothomas** [comment]
> I have a similar question: Most Add*() methods for ConfigureServices() take in a Func<IServiceProvider, *>. However, AddApplicationInsightsTelemetry() doesn't, which makes it difficult to access configuration services. What is the recommended way of accessing services / configuring TelemetryConfiguration prior to calling AddApplicationInsightsTelemetry()?

Can you describe what you are trying to achieve? Specifically what are you attempting to use the IServiceProvider for? Is it configuration? or something else?

**Comment by jcgeorgia** [comment]
We are storing our configuration as a singleton object in IServiceCollection. I managed to find a solution to bridge the connection from our object to passing Application Insights the instrumentation key by:
services.AddSingleton<IConfigureOptions<ApplicationInsightsServiceOptions>, ConfigureApplicationInsightsServiceOptions>();
ConfigureApplicationInsightsServiceOptions has a dependency on our singleton configuration object, which does the bridging.
Thanks!

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1882 - is addressed in the current beta. This should make your use case more easy I think.
Essentially this:
Put you instrumentationkey and anything part of ApplicationInsightsServiceOptions into your IConfiguration. And services.AddApplicationInsights() would pick it up.

**Comment by iamalexmang** [comment]
That’s what I did.

Yet the TelemetryClient object, despite being resolved and instantiated, does not contain any of the configured settings.

That is in contrast to the behaviour of the injected TelemetryConfigurations object, which does contain all the properties configured.
Is this a bug?
Is there something else required in order to get the TelemetryClient work like a properly injected object?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cijothomas** [comment]
> Yet the TelemetryClient object, despite being resolved and instantiated, does not contain any of the configured settings.

I responded earlier. The injected TelemetryClient has the exact same TelemetryConfiguration. There is no public property to examine it, unless you are in debugger. But telemetry tracked with the telemetryClient from the DI, will go through the same config.

**Comment by iamalexmang** [comment]
Public property or not, it gets resolved correctly. The TemeltryClient does not.
Would this be the behaviour of a bug?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cijothomas** [comment]
I am not sure why you think TelemetryClient's configuration is not correct. 
Did you use debugger to inspect the TelemetryConfiguration inside the TelemetryClient, and found that it is incorrect?

Please share a minimal sample repro app showing this, we will investigate.

**Comment by iamalexmang** [comment]
For starters, because its InstrumentationKey property is an empty string.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cijothomas** [comment]
I already mentioned that TelemetryClient.InstrumentationKey is not required and not populated.
https://github.com/MicrosoftDocs/azure-docs/issues/59590#issuecomment-663050989

**Comment by iamalexmang** [comment]
Why would it not be populated, if it is available?!

I’m experiencing that none of the events passed to a temeletryclient are sent, irrelevant whether or not I’m calling the Flush method.

However, instantiating a TelemetryClient object and configuring its InstrumentationKey determines the client object to send the telemetry data to Application Insights.

Can you please explain the decision thought of hiding away the available properties from an injectable object?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cijothomas** [comment]
> I’m experiencing that none of the events passed to a temeletryclient are sent, irrelevant whether or not I’m calling the Flush method.

--- please share a repro for this.

Regd. other questions:
Thy existed originally and never removed. Probably best to mark them obsolete. But no work is planned for this in short term.
There are plans to make changes in next major version bump. (no eta)
https://github.com/microsoft/ApplicationInsights-dotnet/issues/826

**Comment by iamalexmang** [comment]
Correct, they always existed. At least when I started to use the SDK 6 years ago - granted, the product was a Visual Studio product then and the Ibiza portal was brand new and didn’t have a blade for Application Insights.

Why does it not get injected?

Also, why does an injected TelemetryConfiguration get resolved with the InstrumentationKey property instantiated?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TimothyMothra** [comment]
Hi @iamalexmang, I'm sorry for the extreme confusion in this case.

Please ignore the `TelemetryClient.InstrumentationKey` property.
This is a legacy field and it's not being used. I've got more information here #826.
We can't remove it completely because it's in the PublicApi. 
We've tried to keep the onboarding examples in our documentation up to date.


**Regarding dependency injection**
I see in your original description that you're retrieving the `TelemetryClient` via dependency injection. 
I would expect any calls to a `TelemetryClient.Track` method should work. If this is not the case, please let me know! 

I think you already discovered that if you get the `TelemetryConfiguration` object from dependency injection has all your settings. 
Let me confirm that the `TelemetryConfiguration` is the source of truth!
If you debug your application you'll find a `TelemetryClient.TelemetryConfiguration.InstrumentationKey` which I expect will have your configured ikey.
You also mentioned that you were looking for your `TelemetryInitializers`, you can find those at `TelemetryConfiguration.TelemetryInitializers`.


## Moving Forward
How can we make this better?
I don't think you're the only customer with this confusion, and I agree we could do more to steer customers away from this property.
Do you think it would help if we mark `TelemetryClient.InstrumentationKey` as NonBrowseable or Obsolete?

**Comment by iamalexmang** [comment]
Thank you for your reply, Timothy. Much appreciated!

I am of the opinion that the onboarding experience is suffering from not highlighting this information (ref. #826) enough. 
Specifically, once I updated my super-old app's SDK, I found that the .Active was obsolete. Fine - the tooltip bound to the XML-based documentation not only clearly explained the API was obsolete, but also referenced a GH thread.
From this point onward, the experience was/is cumbersome. I replied to that thread, just to receive a reply back hours later along the lines of "we're not monitoring this thread; open a different issue". Well then, what's the purpose of the link in the comment in the first place?!
Second, the Instrumentation Key was not marked obsolete. I understand that it may be "legacy", but it was the very property used for years and years before. Hence, considering the scenario which started this thread in the first place (dependency-injection Telemetry Clients), why would the value of the Instrumentation Key be hidden away from the resolved instance of the Telemetry Client via the Instrumentation Key property, without any explanation of any sorts? Until your reply below and the linked GH thread, I must admit I haven't seen a single reference of this either in comments or the docs. If there is one and I skipped it, please accept my sincere apologies. I didn't expect it, and haven't seen it.

I believe you've already picked some ideas from this thread as to how things might be slightly better on the onboarding scenario. I'm happy to jump on a call if you deem it necessary.

**Comment by yahorsi** [comment]
finally what's the proper way to get TelemetryClient ? Inject TelemetryClient  directly using DI?

**Comment by cijothomas** [comment]
> finally what's the proper way to get TelemetryClient ? Inject TelemetryClient directly using DI?

There is no change on this guidance. https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#how-can-i-track-telemetry-thats-not-automatically-collected has the recommended way. If this does not work, then let us know.

**Comment by AgSync-Aaron** [comment]
> > finally what's the proper way to get TelemetryClient ? Inject TelemetryClient directly using DI?
> 
> There is no change on this guidance. https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#how-can-i-track-telemetry-thats-not-automatically-collected has the recommended way. If this does not work, then let us know.

This topic is not covered for ASP.NET Framework applications where I'm not using dependency injection.
So is this a bad idea?
```c#
    public static class TelemetryService
    {
        public static TelemetryClient TelemetryClient => _telemetryClient.Value;

        private static readonly Lazy<TelemetryClient> _telemetryClient = new Lazy<TelemetryClient>(() =>
        {
            return new TelemetryClient(TelemetryConfiguration.Active);
        });
    }
```

**Comment by cijothomas** [comment]
> > > finally what's the proper way to get TelemetryClient ? Inject TelemetryClient directly using DI?
> > 
> > 
> > There is no change on this guidance. https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#how-can-i-track-telemetry-thats-not-automatically-collected has the recommended way. If this does not work, then let us know.
> 
> This topic is not covered for ASP.NET Framework applications where I'm not using dependency injection.
> So is this a bad idea?
> 
> ```cs
>     public static class TelemetryService
>     {
>         public static TelemetryClient TelemetryClient => _telemetryClient.Value;
> 
>         private static readonly Lazy<TelemetryClient> _telemetryClient = new Lazy<TelemetryClient>(() =>
>         {
>             return new TelemetryClient(TelemetryConfiguration.Active);
>         });
>     }
> ```

The linked doc is for Asp.Net Core only.
For Asp.Net, TelemetryConfig.Active is **not** deprecated and is still the recommended way.

**Comment by San-Jeevan** [comment]
```
            TelemetryConfiguration _telemetyconfig = new TelemetryConfiguration("05e383b4-7469-4d30-a8bc-cxxxxxxx");
            services.AddSingleton(typeof(TelemetryClient), new TelemetryClient(_telemetyconfig));
```

**Comment by luisdvalle** [comment]
@iamalexmang so, does your last post mean that at the end you were getting the TelemetryClient correctly instantiated in the first place? you never clarified that mate

**Comment by Nagendracv** [comment]
Damn... This information needs to be fed to ChatGPT!! lol

**Comment by dbmartin00** [comment]
I am an old school Java developer, just now learning how DI works in C# world.  In one context, I had luck registering AppConfig stuff in Program.cs.   But the context in which I'm working now is a shared component library that doesn't have a Program.cs or Startup.cs.  There also doesn't seem to be any existing services.AddSingleton type stuff going on.

The below example is tantalizing, but it's missing the context I need:
 - Where should HomeController be located?
 - How do I register it or TelemetryClient for DI?
 - Do I get an instance of HomeController by DI?  How else can I get an instance... the constructor asks for what I don't have.

As it is, I'm thinking that just putting this class in my code isn't going to have the intended effect.  What are the other steps necessary... remember I have no Program.cs or Startup.cs.   I'm guessing you'll say, "the consuming app".  How do I figure out what the consuming app is in this case?

using Microsoft.ApplicationInsights;

public class HomeController : Controller
{
    private TelemetryClient telemetry;

    // Use constructor injection to get a TelemetryClient instance.
    public HomeController(TelemetryClient telemetry)
    {
        this.telemetry = telemetry;
    }

    public IActionResult Index()
    {
        // Call the required TrackXXX method.
        this.telemetry.TrackEvent("HomePageRequested");
        return View();
    }

**Comment by Nagendracv** [comment]
> I am an old school Java developer, just now learning how DI works in C# world. In one context, I had luck registering AppConfig stuff in Program.cs. But the context in which I'm working now is a shared component library that doesn't have a Program.cs or Startup.cs. There also doesn't seem to be any existing services.AddSingleton type stuff going on.

@dbmartin00 Maybe this is not the best place for the question. However, let me attempt to answer. You can have your classes in your regular project files. However classes must be linked to DI in Program.cs or startup.cs only. Now regular c# library projects don't have these files. So what, you can link them in the projects where you intend to use the c# project library. Essentially the c# library project does not decide where to get the DI object from - the project in which the library will be placed, decides that.

**Comment by dbmartin00** [comment]
My app has a frontend, shared, and backend context.  I could not get DI
working for the frontend or shared.  But DI was working on the backend.  So
I made the backend host a REST API.  The API implementation performed the
tiny amount of effort to track an event.  The frontend calls the API with
the event details when it has information.

It feels ridiculous, but it works.
