### ISSUE TITLE
Endpoint availability is not exposed to the caller code

### ISSUE THREAD

**Issue by ivshch** [microsoft/ApplicationInsights-dotnet#1974]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Microsoft.ApplicationInsights (2.10.0), also checked on 2.14.0. 
* Runtime version: netstandard2.0
* Hosting environment: Azure Web App, also chacked on Windows 10, Windows Server 2016.

### Bug description

Our current task requires to write the human-readable file logs only at the moments when the AppInsights endpoint is unreachable.

This is quite close to what ServerTelemetryChannel does, but without gzipping and using the rolling mechanism. Our current default configuration (large cloud-based project) does not set the StorageFolder parameter for the ServerTelemetryChannel, so the channel does not enable its intermediate disk storage capabilities. Even if we set the StorageFolder it writes the compressed files that are not suitable for the support staff. Our goal is to make a solution that would allow them to investigate the connectivity problems after (for example) a week of AppInsights silence.

Most problem is we don't have an indicator of whether the AppInsights is assuming the connection loss, or assuming the connection is working.

So, investigating the AppInsights sources gives us the two classes that are monitoring the network status:

[NetworkAvailabilityTransmissionPolicy](https://github.com/microsoft/ApplicationInsights-dotnet/blob/7633ae849edc826a8547745b6bf9f3174715d4bd/BASE/src/ServerTelemetryChannel/Implementation/NetworkAvailabilityTransmissionPolicy.cs), and
[BackoffLogicManager](https://github.com/microsoft/ApplicationInsights-dotnet/blob/76916ab14471a9503c7e1d8d19a2b00507fae74c/BASE/src/ServerTelemetryChannel/Implementation/BackoffLogicManager.cs#L50)

Both classes are instantiated quite deep in the internals of the ServerTelemetryChannel class, access to its properties is not possible from the calling code.

Please fix the implementation to allow access to the current endpoint availability state.

### To Reproduce

On any working AppInsights project, at the runtime set the internet connection to the disabled state. While the endpoint is unavailable, there are no exposed properties/events/hooks to know that AppInsights is not sending the data.

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-dotnet/pull/1887 would solve this issue.

**Comment by ivshch** [comment]
Thank you, looks very promising.
Looking forward to seeing the milestone assigned to #1887.

**Comment by cijothomas** [comment]
> Thank you, looks very promising.
> Looking forward to seeing the milestone assigned to #1887.

It is expected to be part of next beta and stable.

**Comment by ivshch** [comment]
Thank you.
I was looking through the code and got a question:
what if the request is failed with the [HttpRequestException](https://github.com/microsoft/ApplicationInsights-dotnet/blob/c3968af8e7660034df11ef7e874c447f16d7b826/BASE/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L164) (in case of general network failure), it seems that the delegate is not invoked?
This probably suits the initial idea of gathering metric of successful requests, but if I'm correct it makes it unusable in our scenario - detecting the connection loss.

Could it improve your solution if the delegate allows you to collect failures also?

**Comment by cijothomas** [comment]
> Thank you.
> I was looking through the code and got a question:
> what if the request is failed with the [HttpRequestException](https://github.com/microsoft/ApplicationInsights-dotnet/blob/c3968af8e7660034df11ef7e874c447f16d7b826/BASE/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L164) (in case of general network failure), it seems that the delegate is not invoked?
> This probably suits the initial idea of gathering metric of successful requests, but if I'm correct it makes it unusable in our scenario - detecting the connection loss.
> 
> Could it improve your solution if the delegate allows you to collect failures also?

The PR is not final code. Feel free to add comments in the PR.

**Comment by rajkumar-rangaraj** [comment]
@ivshch PR has modified code. It should cover your scenario. Could you please check?

**Comment by ivshch** [comment]
Thank you, I am analyzing the change.

Am I right assuming the HttpRequestException would be propagated further without being handled in Transmission?
Is there a way to get some indication that the HttpRequestException occurred? 
I mean the code instantiating the TelemetryChannel.

**Comment by ivshch** [comment]
> @ivshch PR has modified code. It should cover your scenario. Could you please check?

I have checked the modified code. This implementation does not allow us to proceed if the HttpRequestException has occurred.
Maybe you can suggest a workaround for catching it?
