### ISSUE TITLE
EventCounterCollectionModule uses an internal instance of TelemetryClient and so doesn't share the TelemetryContext

### ISSUE THREAD

**Issue by aelij** [microsoft/ApplicationInsights-dotnet#1975]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Microsoft.ApplicationInsights.AspNetCore/2.14.0
* netcoreapp3.1
* Linux

### Describe the bug
The main issue is that context properties (such as `Cloud.RoleInstance` or `GlobalProperties`) are not propagated to telemetries produced by this module.

### To Reproduce
* Set a context property
* Wait for a counter telemetry to be sent

### Suggested solution
While it is possible to solve this by injecting the `TelemetryClient` into the module, I think there is an underlying design issue with `TelemetryContext` - it can't be set during the `ConfigureServices` phase without rewriting the client's registration, e.g.:

```cs
services.AddSingleton(provider =>
            {
                var client = new TelemetryClient(provider.GetRequiredService<TelemetryConfiguration>());
                client.Context.Cloud.RoleInstance = "...";
                return client;
            });
```

While this works, it might be beneficial to inject `TelemetryContext` directly or maybe add it to `TelemetryConfiguration` or to `ApplicationInsightsServiceOptions`.

**Comment by cijothomas** [comment]
Every module, not just `EventCounterCollectionModule` uses its own internal instance of TelemetryClient built using the shared config.
The recommended way is to use `TelemetryInitializers` to enrich any context properties.

This is the first time we got a request to have this - let us know if the TelemetryInitializer approach can achieve your goals.

**Comment by aelij** [comment]
> Every module, not just EventCounterCollectionModule uses its own internal instance of TelemetryClient built using the shared config.

Why? It might've made sense in pre-DI days. Now there's no reason to do this as far as I can see. I also don't understand why `TelemetryContext` is not shared, or part of the configuration as I suggested. If it were, the fact that it's a different client instance wouldn't've mattered.

> The recommended way is to use TelemetryInitializers to enrich any context properties.

This is an expensive a workaround - copying the global properties dictionary on every telemetry.

**Comment by cijothomas** [comment]
Don't think the workaround is expensive. Even if one uses context on TelemetryClient, it is also simply copied to individual item. Its not good from a design perspective, but this will not be touched until we move to next major version (i.e 3.0.0. No eta on this)

**Comment by cijothomas** [comment]
> Why? It might've made sense in pre-DI days. Now there's no reason to do this as far as I can see. I also don't understand why TelemetryContext is not shared, or part of the configuration as I suggested. If it were, the fact that it's a different client instance wouldn't've mattered.

Most of the TelemetryClient/Context/Config pieces existed before DI and Asp.Net core. Unfortunately, even if your suggestions make sense, any improvements to this area will be only part of next major version bump. The work on it is *not* scheduled to start this year, and once we start planning for it, we'll surely include suggestions. We don't have an ETA on when 3.0.0 is coming.

**Comment by aelij** [comment]
Thanks :) I will use your workaround for now
