### ISSUE TITLE
Dependency Collection - Filter/Disable some dependencies

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [microsoft/ApplicationInsights-dotnet#1977]
**Is your feature request related to a problem?**
Currently I have a app that is heavily dependent on database queries. By using the default dependency collection method I end up ingesting (and paying for) a bunch of dependencies telemetry I don't need or use. There should be a way to select which dependencies one wishes to collect automatically.

**Describe the solution you'd like.**
Some sort of black/white list mechanism, where I could either enable all and use the black list to discard a few or disable all and use the white list to enable the ones I want.

**Describe alternatives you've considered.**
Currently I've been using a telemetry processor, but in high volume scenarios such as mine, you can detect app degradation due to the enourmous amount of data on the wire and my not so ideal checks

**Additional context.**
N/A

**Comment by cijothomas** [comment]
Its unfortunate that DependencyTrackingModule doesn't allow options to turn on off sql/http. It does allow turning off diagnoticlistener though.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/DependencyCollector/DependencyTrackingTelemetryModule.cs

Relatively easy change to implement. But we don't have cycles to make this happen in the coming 2 releases.

**Comment by Leonardo-Ferreira** [comment]
@cijothomas tks for the answer! I don't need that right away, but whenever this is available, this is def something I will use right away!

**Comment by Leonardo-Ferreira** [comment]
any news around here @cijothomas? tks in advance

**Comment by cijothomas** [comment]
No updates, and surely not in the radar for next several months.
