### ISSUE TITLE
Extensions to Connection String

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1984]
We've had several partner requests to add additional fields to the [Connection String](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=net).

### Javascript SDK
Javascript has asked us to make the CDN endpoint configurable.

New Property
- Key: JsCdn
- Value: full URL for the javascript sdk. (example: https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js)

### Codeless Attach
Codeless attach has asked us to include the [Live Metrics Authentication API Key](https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream#secure-the-control-channel). 

New Property
- Key: LiveAuthenticationApiKey
- Value: GUID

**Comment by cijothomas** [comment]
Do we treat ConnectionString as a secret? If we include livemetric auth key, then we need to treat connectionstring as secret, right?

**Comment by TimothyMothra** [comment]
The ConnectionString is not a secret, but the AuthenticationApiKey is.
Because of this, the Portal team will not add it to the overview blade and any customer would have to manually include it in their configuration.
