### ISSUE TITLE
Export Telemetry data (including telemetry context) from Azure Data Explorer to Application Insight

### ISSUE THREAD

**Issue by skyovi** [microsoft/ApplicationInsights-dotnet#1990]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
 netcoreapp3.1
Azure Function/Logic App
**What are you trying to achieve?**
I want to export Page View telemetry data (including telemetry context : session, user, location ) from Azure Data Explorer to our own Application Insight. Please let me know how an achieve this?
**What have you tried so far?**
Not tried so far. thinking to try using Azure function which read data from Azure Data Explore and export the data to AI by calling TrackPageView function  TelemetryClient class in Application Insight SDK . But, Not sure how can I override or construct my own TelemetryContext. I want to export including the telemetry context: session, user, location, so that I can leverage the Usage analysis OOB feature in AI

**Comment by cijothomas** [comment]
Use TrackPageView().
Every ITelemetry including pageview has Context, which you can enrich with whatever information.
pagviewTelemetry.Context....

**Comment by skyovi** [comment]
@cijothomas  TelemetryContext is not providing Set Property.  Should I set directly Context.Location.Ip , Context.Session.Id properties?

**Comment by cijothomas** [comment]
Yes.

**Comment by skyovi** [comment]
@cijothomas  I am able to export the page view data to AI. However, it is not accepting data older than 2days.  any help?

**Comment by cijothomas** [comment]
@skyovi This is by design of the backend. Data older than 48 hours is rejected.
