### ISSUE TITLE
Frugal Tip G07: EventSource Allocation Stack

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1994]
This was suggested by Feng Yuan.

> RichPayloadEventSource.Process is costing 4.4 million CPU samples, mostly for allocations data gathering inside System.Diagnostics.Tracing.EventSource implementation.
> 
> Here is the caller code:
> 
>         private void WriteEvent<T>(string eventName, string instrumentationKey, IDictionary<string, string> tags, T data, long flags, EventKeywords keywords)
>         {
>             this.EventSourceInternal.Write(
>                 eventName,
>                 new EventSourceOptions() { Keywords = keywords },
>                 new { PartA_iKey = instrumentationKey, PartA_Tags = tags, _B = data, PartA_flags = flags });
>         }
> 
>         private void WriteEvent(OperationTelemetry item, EventOpcode eventOpCode)
>         {
>             var payload = new { IKey = item.Context.InstrumentationKey, Id = item.Id, Name = item.Name, RootId = item.Context.Operation.Id };
> 
>             if (item is RequestTelemetry)
>             {
>                 this.EventSourceInternal.Write(
>                     RequestTelemetry.EtwEnvelopeName,
>                     new EventSourceOptions { Keywords = Keywords.Operations, Opcode = eventOpCode, Level = EventLevel.Informational },
>                     payload);
>             }
>             else
>             {
>                 this.EventSourceInternal.Write(
>                     OperationTelemetry.TelemetryName,
>                     new EventSourceOptions { ActivityOptions = EventActivityOptions.Recursive, Keywords = Keywords.Operations, Opcode = eventOpCode, Level = EventLevel.Informational },
>                     payload);
>             }
>         }
> 
> EventSource has lots of WriteEvent method variations with quite good implementations. A good indication of a good implementation is no managed heap allocation, no GC handle allocation, no native heap allocation, only stack allocation allowed. 
> 
> But this code is using the most expensive, most general purpose method:
> 
>     public void Write<T>(string eventName, EventSourceOptions options, T data)
>     {
>         if (!this.IsEnabled())
>         {
>             return;
>         }
>         this.WriteImpl<T>(eventName, ref options, ref data, null, null);
>     }
> 
> It’s a method with a generic type. So basically, you’re asking EventSource to serialize data into a binary package and set as user data for ETW event. Its implementation is very expensive, apparently not optimized (because very few people would ever dare to use it).
> 
> Here is one of the method:
> 
>         public override object GetData(object value)
>         {
>             if (this.properties != null)
>             {
>                 List<string> list = new List<string>();
>                 List<object> list2 = new List<object>();
>                 for (int i = 0; i < this.properties.Length; i++)
>                 {
>                     object data = this.accessors[i].GetData((ContainerType)((object)value));
>                     list.Add(this.properties[i].name);
>                     list2.Add(this.properties[i].typeInfo.GetData(data));
>                 }
>                 return new EventPayload(list, list2);
>             }
>             return null;
>         }
> 
> Apparently, there are lots of boxing, casting, list resizing here. Here is GetData call stack: 5,329,936 Hits
> This is too rich for big data engineering’s blood, you can’t use this method in high volume data gathering.
> 
> The right thing to do here is map to the simplest WriteEvent method as match as possible. If you can’t find a good match, then implement your own version (no managed heap allocation, no GC handle allocation, no native heap allocation, only stack allocation allowed).

**Comment by pharring** [comment]
Note that RichPayloadEventSource will be enabled only if you are profiling (see the `!this.IsEnabled()` check before calling `WriteImpl<T>`) so it's a biased case to start with -- naturally the profiling tools are going to zero in on it. I'm not saying it's not worth addressing -- you'd be improving profiling overhead. 

You should look carefully at the raw data here -- not just Feng's summary. There's probably a deeper story as to why the RichPayloadEventSource was enabled during profilng (did it happen to run at the same time as App Insights Profiler was running? -- that's a remarkable coincidence, but it could happen given enough samples.) We've seen bugs in the past where that event provider got "stuck" on by mistake. The exact call-stacks are important to determine which keywords were enabled: Was it just Requests? Or were Exceptions and other telemetry items also being serialized?

Obviously it's important to keep binary compat with the existing provider -- especially the serialization of the anonymous 'payload' type -- that is the reason we use the generic.
