### ISSUE TITLE
ASP.Net Classic - new up a TelemetryClient w/ every request or use singleton?

### ISSUE THREAD

**Issue by jkewley** [microsoft/ApplicationInsights-dotnet#1998]
* List of [NuGet packages]: Latest App Insights
* Runtime version : .Net 4.7
* Hosting environment : Azure Web App / windows

**What are you trying to achieve?**
I have a project which is an asp.net mvc 4.7 web app with web api components. I'm looking for specific guidance on the recommended lifetime for TelemetryClient in this scenario so I can scope it properly when I register it in my DI infrastructure. 

Many of the AI docs which spoke to asp.net classic have been replaced with .net core, which offers native DI features so this isn't a concern. The pages which do speak to asp.net 4.x [always seem to new up a TC instance directly](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#get-a-telemetryclient-instance). I'm curious if this implies that this is the recommended route. In the past I've seen memory leaks with this approach which I believe were related to TelemetryConfiguration being IDisposable.

However, one specific reservation I have about using a singleton instance of TelemetryClient is whether [individual request and user context properties](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#telemetrycontext) would be overwritten on a static client when concurrent requests are executing.

I think lifetime considerations for TelemetryClient would make a good documentation topic, similar to [what MS has done with HttpClient](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)

**Comment by cijothomas** [comment]
If you are using ASP.NET or ASP.NET Core - the general guidance is to reuse TelemetryConfiguration. Its okay to create new TelemetryClients, as long as they use an existing TelemetryConfiguration.

In Asp.Net, when one does new TelemetryClient(), it internally reuses the TelemetryConfiguration.Active singleton, so its okay to new up TelemetryClient() instances.

Any previous "leak" related issues we are aware of - its all coming from not reusing TelemetryConfiguration. For example, if one does the following, it will lead to leak.
```
var config = TelemetryConfig.CreateDefault(), or new telemetryConfig(). // this is not recommended approach
var tc = new TelemetryClient(config);
```

Context on TelemetryClient will be applied to all the telemetry tracked through that instance of TelemetryClient. Not sure I understood your specific concern here.

(Agree a doc update is long overdue here. Nothing is planned here immediately, as the config story is fairly clear in Asp.Net Core with built-in DI, and no new features are shipped for Asp.Net)

**Comment by jkewley** [comment]
Thanks for the insight and investment in a detailed response. Couple of quick follow ups to help me better understand lifecycles.

- If we *do* want to new up our own `TelemetryConfiguration` in classic asp.net is there a supported pattern other than manipulating `TelemetryConfiguratin.Active`? Would we be responsible for disposal of the TelemetryConfiguration which we instantiate? How can that be done once it's been stuffed into TelemetryClient? Is a singleton TelemetryConfiguration instance another way to avoid leaks in this scenario?

- Regarding my question about context - if we have a singleton TelemetryClient in classic asp.net which, through middleware magic, has properties set at `Context.User`, I'm worried that the properties will be overwritten with multiple incoming requests executing in tandem. Does TelemetryClient account for this, or will these features not be reliable with a singleton? Your answer suggests they may be tied to the instance, which should rule out singleton usage.

I do a lot of consulting work helping clients with mission-critical asp.net full framework projects who are looking to instrument with app insights and would benefit from more technical instrumentation details [beyond what is currently available](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net). Curious - because I know those docs used to exist - I've used them.
