### ISSUE TITLE
Identify and reject duplicate transmissions

### ISSUE THREAD

**Issue by rangp** [microsoft/ApplicationInsights-dotnet#2006]
**Is your feature request related to a problem?**
Yes, possibly also related to Bug  #1749. We experienced occasional duplicate log entries in application insights
that we were able to trace back to failed transmissions:
`An error occurred while sending the request. | Unable to read data from the transport connection: Connection reset by peer. | Connection reset by peer`

The ServerTelemetryChannel, which we are using, will then store the transmission in the file system and retry after a certain interval. The issue is that the first transmission was also successful and a networking issue happened for some unknown reason afterwards. So the data gets processed twice.

**Describe the solution you'd like.**

Since each Transmission already has an Id property, I would propose the following solution:
-  Add the id to the HTTP Request that is sent to the server
- Also store the id in the transmission files
- On the server side, implement a logic, that will reject a transmission, if a transmission with the same id has already been processed earlier.

**Describe alternatives you've considered.**
The only alternative I can see is to ensure that no networking issues will happen, where the outcome of the operation is unclear. 
But this will be hard to ensure, since we are using azure kubernetes services and do not have ownership of the network.
Furthermore, I think the SDK should be able to deal with occasional networking issues.

**Comment by cijothomas** [comment]
Thanks for raising this issue. This is a well known limitation, and cannot be solved with SDK changes alone. As you pointed out, this requires Azure backend changes.
As far as I know - there are immediate plan to address this. You can also raise this in the user voice - https://feedback.azure.com/forums/357324-azure-monitor-application-insights

**Comment by rangp** [comment]
Okay, thank you. I'll try to push this issue on user voice, since it is making our queries overly complicated and slow. We always have to correct for the possibility of duplicate logs.
