### ISSUE TITLE
Memory Consumption Values reported is incorrect/not-what-i-expected

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [microsoft/ApplicationInsights-dotnet#2008]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
```
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.14.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.DependencyCollector" Version="2.14.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.14.0" />
```
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
`<TargetFramework>netcoreapp3.1</TargetFramework>`
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic`

### Describe the bug

Application Insights is reporting that my app "Private Bytes" is over 7GB. Right now, 7GB is the amount of memory the whole host is consuming. When I launch this web app on my localhost, it reports a starting memory of around 40-50MB and peaks are around 200-400 MB...

### To Reproduce

Any SDK instrumented web app running on a non-windows docker should show same symptoms.

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1802 same?

**Comment by Leonardo-Ferreira** [comment]
Well, it looks like the same base issue... the difference here is that im hosting in a docker container... idk how that changes things...

**Comment by Leonardo-Ferreira** [comment]
I Adopted AKS as a hosting platform and this is no longer an issue for me.
