### ISSUE TITLE
Application Insights Logs - How client_CountryOrRegion works?

### ISSUE THREAD

**Issue by diepnt90** [microsoft/ApplicationInsights-dotnet#2010]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Pre-Installed Site Extension, version 2.8.37.4238, is running
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Azure app service

Could you please tell us How client_CountryOrRegion works. Which is that client_CountryOrRegion is based on to figure out the country of requests.

Because today we had a spike in traffic and AI logs show that the high traffic from France but on Cloudflare ( we use CF as CDN), it came from Netherland
![image](https://user-images.githubusercontent.com/18731180/91793961-fb38f780-ec43-11ea-9219-78a964fdab9f.png)

requests
| where timestamp > ago(30m)
| summarize sum(itemCount) by client_CountryOrRegion, bin(timestamp, 1m)
| render timechart 

Thank you.

**Comment by TimothyMothra** [comment]
> By default IP addresses are temporarily collected, but not stored in Application Insights. The basic process is as follows:
> IP addresses are sent to Application Insights as part of telemetry data. Upon reaching the ingestion endpoint in Azure, the IP address is used to perform a geolocation lookup using GeoLite2 from MaxMind. The results of this lookup are used to populate the following fields client_City, client_StateOrProvince, client_CountryOrRegion. At this point, the IP address is discarded and 0.0.0.0 is written to the client_IP field.
> https://docs.microsoft.com/en-us/azure/azure-monitor/app/ip-collection#default-behavior

Hi, it's possible that the database we're using to lookup regions based on IP address is out of date. 
Unfortunately, I can't help you with that because that's owned by the service team. 
Please open a support ticket through the portal and someone will be able to help you with that.
