### ISSUE TITLE
[JS Snippet] Missing instrumentation variable injection format

### ISSUE THREAD

**Issue by markwolff** [microsoft/ApplicationInsights-dotnet#2031]
Snippet injection is missing the string formatting placeholders `{0}`, `{1}`, etc

### Current
https://github.com/microsoft/ApplicationInsights-dotnet/blob/9ef100bfa0f63eab48dbba6adae36afabe59ce8e/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Resources.resx#L127

### Expected
https://github.com/microsoft/ApplicationInsights-dotnet/blob/e2d030c3e61e52ac46c3e86ff04709cf21b2931b/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Resources.resx#L125-L130

**Comment by TimothyMothra** [comment]
@markwolff is this causing an issue?

@kryalama removed the placeholders in favor of string replacement:
https://github.com/microsoft/ApplicationInsights-dotnet/pull/2004/files

If there is an issue, we can revert this PR
