### ISSUE TITLE
NLog SDK - log "standard" properties

### ISSUE THREAD

**Issue by yahorsi** [microsoft/ApplicationInsights-dotnet#2036]
Using .NET Framework 4.7.2
AI - 2.14
NLogTarget - 2.14
NLog - 4.7.2

**What are you trying to achieve?**
When logging exceptions and traces using NLog they do not contain standard AI properties like OperationId, ParentId, UserId, SessionId.

**What have you tried so far?**
Tried logging using directly TelemetryClient - works OK out of the box without any extra configuration

Question - Are there any recommendations on how to make standard properties logged when using NLog. What we want to see is all traces and exceptions logged withing session/user. Currently, it works only if we log directly using TelemetryClient

If NLog configuration is not the best way - could it be achieved using a custom Telemetry Initializer?

Thanks a lot
Regards

**Comment by cijothomas** [comment]
All the standard properties are populated by using TelemetryInitializers. All you need to do is: to make sure the config used for Nlog has the set of telemetry initializers which are part of the config for typical Asp.Net Core/Asp.Net telemetey configuration.

**Comment by yahorsi** [comment]
They are populated just fine when using AI explicitly and not when using NLog. The AI and NLog configs are "very standard". My wild guess is that it could be e.g. because NLog logs something async when the context is different

**Comment by cijothomas** [comment]
I meant to say - the Nlog application insights appender must use the same config as used when using AI explicitly.
Can you share a repro so we can better understand whats missing.

**Comment by yahorsi** [comment]
I tied to make a repo but failed, but then I noticed that in "real" app in the NLog config we have async setting for the AI target ON, when I turned it off - things started working as expected.

```
<?xml version="1.0" encoding="utf-8" ?>
<!-- NLOG.config WEB version 1.4 -->
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <extensions>
    <add assembly="Microsoft.ApplicationInsights.NLogTarget"/>
  </extensions>

  <targets async="false">
    <target type="ApplicationInsightsTarget" name="aiTarget" />
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="aiTarget" />
  </rules>
</nlog>
```

So now it works just fine and I'm closing the issue.
