### ISSUE TITLE
Event counters generate a lot of active time series

### ISSUE THREAD

**Issue by NicolasRichard** [microsoft/ApplicationInsights-dotnet#2041]
* Microsoft.ApplicationInsights.AspNetCore (2.14.0)
* Microsoft.ApplicationInsights.Kubernetes (1.1.2)
* netcoreapp3.1
* Kubernetes, Linux

**What are you trying to achieve?**
Lately, we noticed that some metrics we were sending to our Application Insights instance were getting dropped. We opened a support ticket on Azure and it turned out that we were exceeding the [quota for active time series per subscription/region](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview#quotas-and-limits). While trying to identify the list of problematic metrics, I noticed that most entries listed by running this query:

```customMetrics```

were [default event counters](https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters#default-counters-collected). I then ran the following query:

```
customMetrics 
| where name == "System.Runtime|Gen 0 GC Count"
| project name, interval=parse_json(customDimensions)["AggregationInterval"]
| distinct tostring(interval)
```

and I got ~2800 results in the last 12 hours. Here's a sample of the values:

* 59.99983596801758
* 59.99934387207031 
* 59.991455078125
* 60.0001335144043 
* 59.999576568603516
* 59.999366760253906
* 60.00034713745117

Based on my current understanding of what is a time series:
> An active time series is defined as any unique combination of metric, dimension key, or **dimension value** that has had metric values published in the past 12 hours.

Does this mean there are 2800 active time series for that single metric? Is there a known way to circumvent this issue. We currently have ~30 services that are all sending their telemetry to the same ApplicationInsights instance so if my hypothesis is correct, the time series are adding up quickly.

**What have you tried so far?**
To circumvent the issue, I'm planning to add a custom telemetry processor that will round up the _AggregationInterval_ dimension. This way, it will generate a single time series per metric and we're not really using that dimension right now, so we don't really care if the value is rounded up.

**Comment by cijothomas** [comment]
This is an in EventCounter collection module.

1. Starting with 2.15.0-beta3, no counters are collected by default. User has to opt-in to get any counters.
2. Yes, we need to remove high cardinality duration from the dimension. Will try to address this for 2.15 itself.
You workaround of rounding up should work. There is no strong reason to have this duration added - all metrics are aggregated with 1 min interval, and there is no option to customize it. So one can always assume the aggregation interval is 1min. The actual value may drift slightly from exact 60 sec, which caused huge # of time series.
