### ISSUE TITLE
Does setting the MaxTransmissionSenderCapacity property actually work?

### ISSUE THREAD

**Issue by MarkTopping** [microsoft/ApplicationInsights-dotnet#2042]
List of NuGet packages and version that you are using:
Microsoft.ApplicationInsights v2.14.0
Microsoft.ApplicationInsights.WorkerService v2.14.0
Serilog.Sinks.ApplicationInsights v3.1

Runtime version: netcoreapp3.1

Hosting environment: IIS Express on Windows (from the IDE while testing)

**What are you trying to achieve?**

I'm trying to test / prove if we can successfully increase telemetry throughput for applications which sent very large volumes of logs into Application Insights.

The documentation suggests that you can set the MaxTransmissionSenderCapacity property to a value higher than the default of 10 to achieve this.

However, having sent through batches of log entries with the MaxTransmissionSenderCapacity value set as low as 1, and as high as 20, I cannot seem to observe any different in throughput be it for better or worse. I submitted batches of up to 75,000 trace entries via a tight loop.

Furthermore, when large batches are sent, the SDK logs produce the following Warning:

Microsoft.ApplicationInsights.Extensibility.TraceSource Warning: 16 : SenderEnqueueNoCapacity. TransmissionCount: 10. Capacity: 10.

In hundreds of examples of these log messages, the Capacity always has a value of 10; and the TransmissionCount fluctuates between 10 and 11;  The logs present those values regardless of the MaxTransmissionSenderCapacity setting.  i.e. when set to 1, the logs still show a capacity of 10.

I'm poking around the edges here to so if there is a bug around the adherence to the MaxTransmissionSenderCapacity value, or maybe a smaller one whereby the logs are simply emitting the wrong value, or actually are the log entries referring to a different parameter? 

Confirmation as to whether or not setting MaxTransmissionSenderCapacity will actually increase the rate of throughout would be ideal, because as mentioned my test simulations were unable to prove any difference

**Comment by cijothomas** [comment]
Please share the code snippet you used to customize the channel's MaxTransmissionSenderCapacity and we can investigate.
There are no known issues about this property, and it is expected to work as advertised.

**Comment by MarkTopping** [comment]
@cijothomas sure.

I've tried setting it in the Configure() class inside startup.cs as per below; and also in a consuming background worker class which had the TelemetryConfiguration constructor injected into it. 

`public void Configure(IApplicationBuilder app, TelemetryConfiguration telemetryConfiguration)
{
    // other configure code removed

    var telemetryChannel = telemetryConfiguration.TelemetryChannel as ServerTelemetryChannel;
 
    // alternatively
    // var configuration = app.ApplicationServices.GetService<TelemetryConfiguration>().TelemetryChannel as ServerTelemetryChannel;
 
    telemetryChannel.MaxTransmissionSenderCapacity = 25;
}`

**Comment by MarkTopping** [comment]
Interesting.

Having set the property via this code in `startup.cs` instead:

```c#
services.AddSingleton(typeof(ITelemetryChannel), new ServerTelemetryChannel()
{
          MaxTransmissionSenderCapacity = 5
});

services.AddApplicationInsightsTelemetryWorkerService(serviceOptions =>
{
          serviceOptions.EnableDependencyTrackingTelemetryModule = true;
          serviceOptions.InstrumentationKey = Configuration["ApplicationInsights:InstrumentationKey"];
          serviceOptions.EnableAdaptiveSampling = false;
});
```

and then inspecting the logs on a batch intended to put load upon the sdk, then I can now see the following warnings.

Microsoft.ApplicationInsights.Extensibility.TraceSource Warning: 16 : SenderEnqueueNoCapacity. TransmissionCount: 5. Capacity: 5.

The value of 5 is now being respected it seems. 

I find it odd that setting the property at a later point in time during the codes execution does not yield the same effect. Unless the TelemetryChannel object being returned by the TelemetryConfiguration is not the active telemetry channel and so I was setting the property on an inactive TelemetryChannel object? But then why would TelemetryConfiguration give me that? 

This is more a curiosity from this point as the initial question I think has been answered. Time permitting i'll perform further testing on the impact of setting it.

Thanks

**Comment by cijothomas** [comment]
Probably have to do channel.Initialize?
