### ISSUE TITLE
Removing default event properties

### ISSUE THREAD

**Issue by skurik** [microsoft/ApplicationInsights-dotnet#2045]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: __Microsoft.ApplicationInsights, 2.14.0__

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): __net472__

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): __Windows App Service__

**What are you trying to achieve?** Remove the properties attached to all tracked events by default:

![image](https://user-images.githubusercontent.com/951352/92881291-21625280-f40f-11ea-8031-00ded3eeb1ef.png)

**What have you tried so far?**

I tried creating my own telemetry processor:

```
public void Process(ITelemetry item)
{
    item.Context.GlobalProperties.Remove("client_City");

    Next.Process(item);
}
```

and a telemetry initializer (using a similar code) but it seems like these default properties are not accessible via `item.Context.GlobalProperties`.

What is the correct way to remove them?

Thank you.

**Comment by cijothomas** [comment]
The properties highlighted are not part of custom properties. That explains why you cannot remove then using the code snippet above.
AppId, name, ikey etc are not removable.
The client_ ones are auto populated by the backend as well, so likely, not removable..

Any particular reason you want to remove them?

**Comment by skurik** [comment]
@cijothomas I get that __AppId__ and __iKey__ are not removeable.

But __clientType__, __client_IP__, __client_City__ etc. are useless to us and they inflate the size of the ingested events, increasing significantly the Application Insights cost.

Surely there must be a way to set up the telemetry pipeline in such a way that these properties are stripped.

**Comment by cijothomas** [comment]
the client_ ones - 
1. Are you using the Microsoft.ApplicationInsights nuget alone? If yes, client_ things must be empty by default.
2. If you are using any other SDK like (the .Web or .AspnetCore ones), then client_ things are added by a telemetryinitializer. It can be removed. Or You can simply write own initializer to clean it up like below:
item.Context.Location.Ip = string.Empty

If SDK is not sending it (you can validate with a Fiddler capture), but ApplicationInsights backend is still adding it, and you are being billed for that - this is something I can offer to solve from this github repo :) You need to open support ticket with Microsoft to get help, as this is a backend/billing issue.
