### ISSUE TITLE
NET5.0 causing compilation issue in the pipeline

### ISSUE THREAD

**Issue by eddynaka** [microsoft/ApplicationInsights-dotnet#2047]
After we enabled NET5.0 in the PR https://github.com/microsoft/ApplicationInsights-dotnet/pull/2035, we started to see some issues when building: https://github.com/microsoft/ApplicationInsights-dotnet/runs/1101507942

Right now, the rule is disabled, so it won't prevent us from build/test, but we should see what is happening.

Below some issues:
```
CSC(0,0): Error AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldNotContainTypeNames' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
CSC(0,0): Error AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.CancellationTokenParametersMustComeLastAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```

**Comment by TimothyMothra** [comment]
I've seen errors like these before.
These usually come from bugs in the Analyzer itself.
If we can find the source, we should report it to https://github.com/dotnet/roslyn-analyzers

For now, disabling AD0001 will stop these errors from crashing our builds.
When the Analyzers team fixes the rule, we'll get the actual violation in our build log.
