### ISSUE TITLE
how do you distinguish ETW events from plugin events in Application Insights

### ISSUE THREAD

**Issue by sanikolov** [microsoft/ApplicationInsights-dotnet#2048]
Just to be clear I am explaining the terminology first.
ETW stands for event tracing facility and is activated for IIS by these registry lines

```
MicrosoftAppInsights_ManagedHttpModulePath=C:\Program Files\WindowsPowerShell\Modules\Az.ApplicationMonitor\1.1.0\content\Runtime\Microsoft.ApplicationInsights.RedfieldIISModule.dll
MicrosoftAppInsights_ManagedHttpModuleType=Microsoft.ApplicationInsights.RedfieldIISModule.RedfieldIISModule
```

On the other hand, the Application Insights plugin is a native library (a profiler) written in C/C++ which is loaded by the .NET runtime on start and is responsible for instrumenting select methods in certain assemblies. In AI it is used to collect mostly SQL commands and metrics AFAIK.

How can I tell whether events that are stored either locally on a windows box, or remotely on azure, originated from ETW or the plugin?

**Comment by cijothomas** [comment]
Sorry, I am not sure I understood the question. But irrespective of that, none of the ApplicationInsights components are shipped from this repo. (eg: RedFieldIISModule or plugin), and we can support it here.
Please open support ticket with Microsoft to get help on non open-source components.

**Comment by sanikolov** [comment]
Let's not close this ticket plz.
Instead of "events" read "telemetry" in my question above.
I am asking how to identify telemetry that originates from the plugin.
I don't want to confuse it with telemetry that originates from ETW.
Yes, I did open a support request but the support person was not able to fully grasp what I am asking.

**Comment by cijothomas** [comment]
I am not fully grasping the question either :( Could you try to rephrase?

**Comment by sanikolov** [comment]
opened [case 2049](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2049) where I go into as much detail as possible
