### ISSUE TITLE
how do you identify telemetry that originate from App Insights profiler in azure portal?

### ISSUE THREAD

**Issue by sanikolov** [microsoft/ApplicationInsights-dotnet#2049]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:

**_C:\Program Files\WindowsPowerShell\Modules\Az.ApplicationMonitor\1.1.0\content\Instrumentation64\MicrosoftInstrumentationEngine_x64.dll_**<br>
**_C:\Program Files\WindowsPowerShell\Modules\Az.ApplicationMonitor\1.1.0\content\Instrumentation64\Microsoft.ApplicationInsights.ExtensionsHost_x64.dll_**<br>

They were installed as a result of the following powershell commands:

1. Connect-AzAccount<br>
2. Set-AzVMExtension -ResourceGroupName "app_insights_testing_azure" -VMName "windows10standardD2sV3" -Location "East US 2" -Name "ApplicationMonitoring" -Publisher "Microsoft.Azure.Diagnostics" -Type "ApplicationMonitoringWindows" -Version "2.8" -SettingString $publicCfgJsonString -ProtectedSettingString $privateCfgJsonString
3. Enable-InstrumentationEngine

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
net461
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
windows 10 box on Azure running IIS

**What are you trying to achieve?**

Identify which telemetry in azure comes from the 2 DLLs listed above. Most of the telemetry comes from ETW but I don't care about the ETW telemetry, I care only about the telemetry that originated from the 2 DLLs above.

**What have you tried so far?**
Opened 2 support cases with azure support. Support person was not able to help.
Opened case [2048](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2048l) .
Opened a question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/93076/how-do-you-distinguish-etw-events-from-plugin-even.html).

See the image below: it shows approximate location where I expect to find the desired telemetry.
![image](https://user-images.githubusercontent.com/19896827/93110584-86be7980-f683-11ea-8f50-d023d8c18d09.png)

**Comment by cijothomas** [comment]
Understand that you were not able to get proper help for this issue/question. But posting it in this repo is of no use. This repo doesn't contain code for the MicrosoftInstrumentationEngine_x64 or Microsoft.ApplicationInsights.ExtensionsHost_x64. They are no open source, and opening support tickets is the only way to get any support for these.

To figure out which component (shipped from this repo) produced a telemetry item, the following guide of using "sdk_version" inside each telemetry helps:
https://github.com/microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/SDK-VERSIONS.md

**Comment by sanikolov** [comment]
MicrosoftInstrumentationEngine_x64.dll is open source.
See https://github.com/microsoft/CLRInstrumentationEngine .
Not sure about Microsoft.ApplicationInsights.ExtensionsHost_x64.dll.
Does anybody here know who to turn to to get help with Microsoft.ApplicationInsights.ExtensionsHost_x64.dll?
I emailed 3 software engineers from MSFT a week who vouchsafed no reply.

**Comment by cijothomas** [comment]
MicrosoftInstrumentationEngine_x64.dll is open source.
See https://github.com/microsoft/CLRInstrumentationEngine 

- You can open an issue in that repo.

**Comment by sanikolov** [comment]
I can't. This team provides the multiplexing profiler on top of which the App Insights profiler runs in an onboarded fashion.
The only team that can help me is Application Insights.
But it's unclear who to turn to.
