### ISSUE TITLE
App Insights track calls blocking, long wait times

### ISSUE THREAD

**Issue by attrib75** [microsoft/ApplicationInsights-dotnet#2052]
* List of NuGet packages and version that you are using:
  applicationinsights-web 2.2.4
* Runtime version :
  Angular 7.2
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
   Angular app on Azure app service

**What are you trying to achieve?**
 Using telemetry without blocking other calls

**What have you tried so far?**
We're experiencing intermittent huge wait times for App Insights calls and wondering what the issue might be.  One example is pasted here.  A track call is taking over 700 ms to load.  The internet connection is fine and other requests for other endpoints on the web succeed in a much shorter time when this is noticed.  In addition, the 'track' calls seem to block all other calls, making the whole app wait until it is done before other calls can continue.  This may be due to the Chrome's consecutive Ajax request limit.  The issue happens in Chrome and Firefox. 

![AITrackBlockingsmall](https://user-images.githubusercontent.com/1398909/93240478-c3ed3f00-f749-11ea-9e9a-7cb1c5fd8f70.png)

thanks

**Comment by cijothomas** [comment]
Are you referring to javasript sdk? 
please post an issue here: https://github.com/microsoft/ApplicationInsights-JS

**Comment by attrib75** [comment]
Gotcha, thanks
