### ISSUE TITLE
SQL commands WebJob in Azure App Service using SDK + System.Data.Entity

### ISSUE THREAD

**Issue by Bouke** [microsoft/ApplicationInsights-dotnet#2055]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
```
  <package id="Microsoft.ApplicationInsights" version="2.14.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.4.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.14.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.14.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.14.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.14.0" targetFramework="net472" />
```
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): net472
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Azure App Service - WebJob

**What are you trying to achieve?**
Include SQL query with dependency telemetry and record profile traces. "SQL Commands" and "Profiler" are enabled on the Application Insights pane of my App Service. **This is working for the Web application (code-less).**  However I also have a WebJob that's run on an interval for which I want to track SQL commands. I've installed the SDK to track custom events and include default dependency tracking.

**What have you tried so far?**
I've installed the SDK and opt-in to SQL commands:
```
        <Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
            <EnableSqlCommandTextInstrumentation>true</EnableSqlCommandTextInstrumentation>
        </Add>
```

The SDK version for the SQL dependencies is listed as: `rddf:2.14.0-17971`. I'm using System.Data.SqlClient as I'm using System.Data.Entity which (afaik) doesn't support Microsoft.Data.SqlClient.

I would expect that when running on Azure App Service, with Application Insights enabled, and SQL Commands + Profiler enabled would [fulfil the requirements](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query). Those requirements mention "StatusMonitor", but how would one install such a thing on Azure App Service -- is it even required? In my Kudo dashboard I can see that the Application Insights extension is enabled. It is also running a background process named "ApplicationInsightsProfiler.exe", is StatusMonitor complementary to that, do I need both? Or is ApplicationInsightsProfiler.exe sufficient?

However the list of sources (https://XXX.scm.azurewebsites.net/ApplicationInsights) doesn't include the PID of my WebJob.

![image](https://user-images.githubusercontent.com/235882/93254084-15bcb600-f798-11ea-910e-c32f75efa5df.png)

![image](https://user-images.githubusercontent.com/235882/93254287-69c79a80-f798-11ea-8201-0703c29ca549.png)

**Comment by cijothomas** [comment]
Webjobs is not in supported list when using System.Data.SqlClient.
![image](https://user-images.githubusercontent.com/5232798/93254877-ebdea180-f74d-11ea-9c17-85df666eb97f.png)

**Comment by Bouke** [comment]
So that means what with WebJobs it would only work with Microsoft.Data.SqlClient? As I'm using System.Data.Entity, that's doesn't work for me. So that means no SQL tracking for me?

**Comment by cijothomas** [comment]
Yes. You are right. (Sql tracking yes, but full sql query - no)

**Comment by Bouke** [comment]
Ok, not the answer I was hoping for, but at least a definitive answer. Thank you!

**Comment by cijothomas** [comment]
I made a doc change to make it obvious that Web Jobs is not supported for full sql text. It'll go live in few days.

**Comment by Bouke** [comment]
@cijothomas and what about profiler tracing? Is that also not supported for WebJobs?

**Comment by cijothomas** [comment]
Not supported based on my knowledge. There is no option to install a profiler in the sandbox environment of App Service in general. WebApp is special case with what is called "extensions", hence it works in Web Apps.

**Comment by chdtcktt** [comment]
@cijothomas I have double checked and I am running nearly the exact scenario as @Bouke only I am using  Microsoft.Data.SqlClient but I am still unable to see the SQL commands in application insights dependency events. Is there still a bug that needs to be worked out?

Dotnet Core 3.1
Webjobs SDK 3.x
using Microsoft.Data.SqlClient

Configuration:

  `cfg.AddApplicationInsightsWebJobs(opts =>
  {
      opts.InstrumentationKey = ConfigurationResolver.Configuration["APPINSIGHTS_INSTRUMENTATIONKEY"];
      opts.SamplingSettings = new SamplingPercentageEstimatorSettings
      {
          MaxSamplingPercentage = 70
      };
  });`

` cfg.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((module, o) => module.EnableSqlCommandTextInstrumentation = true);`
