### ISSUE TITLE
SQL Commans not showing. IIS On prem + Status Monitor V2

### ISSUE THREAD

**Issue by Eneuman** [microsoft/ApplicationInsights-dotnet#2057]
<package id="Microsoft.ApplicationInsights" version="2.14.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.4.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.14.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.14.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.SnapshotCollector" version="1.3.7" targetFramework="net48" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.14.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.Web.TelemetryChannel" version="1.0.0" targetFramework="net451" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.14.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.14.0" targetFramework="net472" />

Runtime: .Net Framework 4.,8
Hosted on prem in IIS. Windows Server 2012 R2

### Describe the bug

SQL Commands (full text) does not show up in AI portal. Only Database name is logged.

## Repo

I think I have followed every doc to the letter.
1) In my project I enable application insights and deployed it to my server.
2) I added `<EnableSqlCommandTextInstrumentation>true</EnableSqlCommandTextInstrumentation>` to applicationinsights.config file
3) I Installed Application Insight Status Monitor V2 (powershell module) on the server
4) I ran "Enable-ApplicationInsightsMonitoring" with my Instrumentation key map and "-EnableInstrumentationEngine" parameter, on the server
5) Restarted the IIS

No error on any command and no errors in Eventlog
I do receive event in AI but my SQL events have SDK version **rddf:2.14.0-17971**

`Get-ApplicationInsightsMonitoringStatus` shows my app as "AppAlreadyInstrumedted: true"

What can I check to figure out why Application Insight Status Monitor V2, isn't beeing used for the dependency collection?

**Comment by cijothomas** [comment]
From your description, it looks like it should have worked. 
But unfortunately the StatusMonitor V2 module is not open source, and it is not supported via this Github repo - You need to open microsoft support ticket to get help.
