### ISSUE TITLE
Spamming EventSource logs

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#2060]
A customer shared SDK logs.
When capturing Verbose logs, our SDK spams the log file.
This message appears over 20,000+ in a 30 min log (170MB). (VS Code stops counting after 20k) (Notepad++ crashed)

> Microsoft.ApplicationInsights.Extensibility.TraceSource Information: 9 : Ignoring event written from EventSource: Microsoft-ApplicationInsights-Data as no counters from this event source are configured to be collected.

It may be worth investigating in some kind of throttling to limit this.

Source:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/0c5cd658495f78f3b70fd2db6207ba31c702371f/WEB/Src/EventCounterCollector/EventCounterCollector/EventCounterListener.cs#L122

**Comment by cijothomas** [comment]
Its not spamming, it is logging an information. We can change from Info level to Verbose level.
If not interested in EventCounterModule - disable the module itself.
