### ISSUE TITLE
ISupportSampling.SamplingPercentage is not honored by SamplingTelemetryProcessor

### ISSUE THREAD

**Issue by darthkurak** [microsoft/ApplicationInsights-dotnet#2068]
Hi. I tried to use ISupportSampling.SamplingPercentage to set custom sampling percentage via TelemetryInitializer.
Unfortunately it appears that other values than 100 are not honored and are override by global SamplingPercentage.

```
            //// Ok, now we can actually sample:

            samplingSupportingTelemetry.SamplingPercentage = samplingPercentage;
```

Is this a bug or by design? If by design - why so? What harm it could cause if actually TelemetryProcessor would honor SamplingPercentage from telemetry instead override it using global one?

**Comment by darthkurak** [comment]
Bump.

**Comment by darthkurak** [comment]
Would be great if someone could take a look at this issue. Thanks!

**Comment by cijothomas** [comment]
Its not very clear to me the exact issue you are facing. Can you share a small repro demonstrating the issue?
The built-in sampling processors dont apply any sampling, if telemetry is already sampled (i.e have SamplingPercentage set)

**Comment by js8080** [comment]
I seem to be encountering this same issue. I'm trying to disable App Insights Telemetry collection for certain requests such as health checks and metrics scrapes because it ends up just adding a bunch of noise to my telemetry data.

To ignore these requests, I have an ITelemetryInitializer like this:
```csharp
{
    public class TelemetryInitializer : ITelemetryInitializer
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public TelemetryInitializer(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public void Initialize(ITelemetry telemetry)
        {
            if (_httpContextAccessor.HttpContext == null) return;

            var requestTelemetry = telemetry as RequestTelemetry;

            // Is this a TrackRequest() ?
            if (requestTelemetry == null) return;

            // Ignore ALL sampling of metrics and health checks
            if (IgnoreRequest(_httpContextAccessor.HttpContext))
            {
                ((ISupportSampling)telemetry).SamplingPercentage = 0;
                return;
            }
        }
```

I can debug this code and see that `((ISupportSampling)telemetry).SamplingPercentage` is being set to 0 but I still find telemetry data for these requests in App Insights.

**Comment by cijothomas** [comment]
@js8080 The correct way of filtering telemetry is by using TelemetryProcessors : https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#filtering

**Comment by js8080** [comment]
> @js8080 The correct way of filtering telemetry is by using TelemetryProcessors : https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#filtering

That worked, thanks!
