### ISSUE TITLE
Thousands of ObjectDisposedException in WebUserTelemetryInitializer per day

### ISSUE THREAD

**Issue by JeroenJSmit** [microsoft/ApplicationInsights-dotnet#2074]
* All Microsoft.AspNetCore.* assemblies are currently at the latest greatest (3.1.8)
 * Microsoft.ApplicationInsights.AspNetCore itself is latests as well (2.15.0)
 * Azure App Service (windows) using App Insights

### Describe the bug
We are seeing thousands of System.ObjectDisposedException traces per day being logged in Application Insights originating from WebUserTelemetryInitializer with the following stack trace and exception information:

AI (Internal): [Microsoft-ApplicationInsights-Core] [msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebUserTelemetryInitializer, exception message - System.ObjectDisposedException: Request has finished and HttpContext disposed.
Object name: 'HttpContext'.
at Microsoft.AspNetCore.Http.DefaultHttpContext.ThrowContextDisposed()
at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Features()
at Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.TelemetryInitializerBase.Initialize(ITelemetry telemetry)
at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]

It also seems to cause little spikes in CPU usage (to about 100) while the App Service itself is not handling any requests.

If necessary I can share the App Insights key with the one investigating.

**Comment by davidfowl** [comment]
Likely its because the telemetry initializer is running after the request is complete. Can you share the entire call stack?

**Comment by JeroenJSmit** [comment]
This is the entire call stack available in the logged exception

**Comment by JeroenJSmit** [comment]
Maybe helpfull too, but I found this same issue recently in a custom telemtry initializer we had were we tried to enhance RequestTelemtry with some additional properties. The initializer code was only executed for RequestTelemtry **after** the request had already returned rendering the HttpContext null. Our fix was to now do it in middleware.

**Comment by davidfowl** [comment]
> This is the entire call stack available in the logged exception

What code is calling at TelemetryClient.Initialize(ITelemetry telemetry)?

**Comment by JeroenJSmit** [comment]
We are not calling it ourselves, so I was hoping someone in the team would know. From our startup we only call the following methods (snippets) and as I don't think our App Service is restarted 7.9k times a day the initialize calls must originate somewhere in the core

services.AddApplicationInsightsTelemetry(configuration)
services.AddSingleton<TelemetryClient>(provider =>
{
    var telemetryConfiguration = provider.GetService<TelemetryConfiguration>();

    return new TelemetryClient(telemetryConfiguration);
});
var aiOptions = new Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions
{
    EnableAdaptiveSampling = false
};

services.AddApplicationInsightsTelemetry(aiOptions);

**Comment by davidfowl** [comment]
I know you're not calling it yourself but the callstack above is incomplete. Some call on TelemetryClient.Track* is calling into the initializers. I'd like to see where that call is.

**Comment by JeroenJSmit** [comment]
Unfortunately this is all that is available in App Insight. The telemetry itself doesn't have a callstack. This is from the message
