### ISSUE TITLE
Make your own sampling telemetry processor: AKA how do I set itemCount on a TelemetryItem?

### ISSUE THREAD

**Issue by ulf-cab** [microsoft/ApplicationInsights-dotnet#2077]
All versions of AI.

**What are you trying to achieve?**

I want to make a very specific custom sampling telemetry processor that acts on certain application specific properties but still feeds the itemCount value (and adjusted duration values) to AI so that all stats and graphs in the UI (and custom queries) are as correct as can be.

**What have you tried so far?**

Reading the source code for the builtin sampling processors. I can find where the adjusted itemCount values are calculated, but nothing on how they make it into the telemetry items. As far as I can tell right now they get sent off into a callback that no one ever registers :-) Obviously wrong but...

**Comment by cijothomas** [comment]
I think `SamplingPercentage` is what becomes itemCount in the backend.

https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/ServerTelemetryChannel/SamplingTelemetryProcessor.cs#L185

https://github.com/microsoft/ApplicationInsights-dotnet/blob/bde253ff1e30cdc10fed8835313e89062386d155/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Telemetry.cs#L24

**Comment by ulf-cab** [comment]
Aha, ok, thanks, I will try that.

**Comment by ulf-cab** [comment]
Yep, that was it.

Percentage in this case also means just that. So for a value of 1% the actual property value is 1, not 0.01.

itemCount ends up as 1.0 / ( SamplingPercentage _[sampleRate]_ / 100.0 )

Thanks again!
