### ISSUE TITLE
AppInsight Dependency doesn't seem to work with SqlClient

### ISSUE THREAD

**Issue by ewaldtlgs803** [microsoft/ApplicationInsights-dotnet#2079]
This was also reported at dotnet/SqlClient: https://github.com/dotnet/SqlClient/issues/741. @karinazhou recommended me to report this in this repo

I created a sample application and in that app the Dependency is not logged, while the Event that I log manually is actually showing up

![image](https://user-images.githubusercontent.com/29872182/94905551-e96c8f00-0451-11eb-8cc6-b3e031f742d3.png)

![image](https://user-images.githubusercontent.com/29872182/94905693-233d9580-0452-11eb-8628-268a53786813.png)

I made sure that I added the Dependency to the applicationinsights.config

```<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
	<TelemetryInitializers>
		<Add Type="Microsoft.ApplicationInsights.DependencyCollector.HttpDependenciesParsingTelemetryInitializer, Microsoft.AI.DependencyCollector"/>
	</TelemetryInitializers>
	<TelemetryModules>
		<Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
			<ExcludeComponentCorrelationHttpHeadersOnDomains>
				<!-- 
        Requests to the following hostnames will not be modified by adding correlation headers.         
        Add entries here to exclude additional hostnames.
        NOTE: this configuration will be lost upon NuGet upgrade.
        -->
				<Add>core.windows.net</Add>
				<Add>core.chinacloudapi.cn</Add>
				<Add>core.cloudapi.de</Add>
				<Add>core.usgovcloudapi.net</Add>
			</ExcludeComponentCorrelationHttpHeadersOnDomains>
			<IncludeDiagnosticSourceActivities>
				<Add>Microsoft.Azure.EventHubs</Add>
				<Add>Microsoft.Azure.ServiceBus</Add>
			</IncludeDiagnosticSourceActivities>
		</Add>
	</TelemetryModules>
	<ApplicationIdProvider Type="Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.ApplicationInsightsApplicationIdProvider, Microsoft.ApplicationInsights"/>
</ApplicationInsights>
```

[WebApplication1.zip](https://github.com/dotnet/SqlClient/files/5316888/WebApplication1.zip)

Note, the FileNotFoundException is due to this. Is that an issue?

`System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Data.SqlClient.resources, Version=1.13.20136.2, Culture=en-US, PublicKeyToken=23ec7fc2d6eaa4a5' or one of its dependencies. The system cannot find the file specified.'`

**Comment by ewaldtlgs803** [comment]
@karinazhou, I have not received any response after a week. Do you know what is going on here?

**Comment by karinazhou** [comment]
Hi @ewaldtlgs803  It looks like that this issue hasn't been reviewed yet. 

Hi @cijothomas  Can someone from the team have a look at this one?

**Comment by cijothomas** [comment]
APologies for the delay, we'll get to this soon.

**Comment by ewaldtlgs803** [comment]
@cijothomas It has been 13 days ago. Still no update :(
