### ISSUE TITLE
Microsoft.ApplicationInsights.SnapshotCollector release notes

### ISSUE THREAD

**Issue by pharring** [microsoft/ApplicationInsights-dotnet#2080]
This issue contains the release notes for the [Microsoft.ApplicationInsights.SnapshotCollector](https://www.nuget.org/packages/Microsoft.ApplicationInsights.SnapshotCollector) nuget package.

General documentation for the Application Insights Snapshot Debugger is [here](https://aka.ms/Pnv0qt).

Previous release notes for earlier versions are archived here: https://github.com/Microsoft/ApplicationInsights-Home/issues/167

We will update this issue when new versions are published.

_Note: This issue is locked so that only team members can update it. For questions or bug reports on the Snapshot Debugger feature, please file new issues._

**Comment by pharring** [comment]
# [1.3.7.3](https://www.nuget.org/packages/Microsoft.ApplicationInsights.SnapshotCollector/1.3.7.3)

A point release to address a couple of high-impact issues.

## Bug fixes

- Fixed PDB discovery in the wwwroot/bin folder which was broken when we changed the symbol search algorithm in 1.3.6.
- Fixed noisy ExtractWasCalledMultipleTimesException in telemetry.

**Comment by cijothomas** [comment]
@pharring 
Could we create an actual docs page to host the release notes like this -> https://docs.microsoft.com/en-us/azure/azure-monitor/app/web-app-extension-release-notes

The -Home repo is taken private and not publicly visible. We can create a dedicated .doc page and move notes from -home and this issue.

**Comment by pharring** [comment]
The complete release notes have now been migrated to docs.microsoft.com:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/snapshot-collector-release-notes
