### ISSUE TITLE
Failed StartOperation / StopOperation silently rejected

### ISSUE THREAD

**Issue by zakimaksyutov** [microsoft/ApplicationInsights-dotnet#2082]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.ApplicationInsights" version="2.15.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.15.0" targetFramework="net472" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net472" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.6.0" targetFramework="net472" />
  <package id="System.Memory" version="4.5.4" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.3" targetFramework="net472" />
</packages>

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):

<TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):

Windows, console app

### Describe the bug

The request telemetry produced by code below is silently rejected by ingestion endpoint.

--------------------------------
POST https://dc.services.visualstudio.com/v2/track HTTP/1.1
Content-Type: application/x-json-stream
Host: dc.services.visualstudio.com
Content-Length: 604
Expect: 100-continue
Connection: Keep-Alive

{"name":"AppRequests","time":"2020-10-06T21:41:45.2966629Z","iKey":"<reductedikey>","tags":{"ai.cloud.roleInstance":"<reductedmachinename>","ai.operation.id":"ad4c9219a4d30d4490f4e3d5502ad0dc","ai.operation.name":"myoperationname","ai.internal.sdkVersion":"dotnet:2.15.0-44797","ai.internal.nodeName":"<reductedmachinename>"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"e11a12fdade54445","name":"myoperationname","duration":"00:00:00.0025546","success":false,"properties":{"_MS.ProcessedByMetricExtractors":"(Name:'Requests', Ver:'1.1')"}}}}
--------------------------------
HTTP/1.1 400 109: Field 'responseCode' on type 'RequestData' is required but missing or empty. Expected: string, Actual: undefined
Content-Type: application/json; charset=utf-8
x-ms-session-id: 79D0B20A-B2DF-4438-B271-20FC11D99050
Strict-Transport-Security: max-age=31536000
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Name, Content-Type, Accept, Sdk-Context
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3600
X-Content-Type-Options: nosniff
Date: Tue, 06 Oct 2020 21:41:45 GMT
Content-Length: 207

{"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"109: Field 'responseCode' on type 'RequestData' is required but missing or empty. Expected: string, Actual: undefined"}]}
--------------------------------

The end result is that telemetry gets logged when it is successful. But all failures get rejected. This is very error-prone (don't ask me how I discovered it =)).

### Expected behavior

Either SDK should throw an exception or ingestion endpoint should put some default value (for instance, "500" {similarly to how "200" is used for successful cases}).

### To Reproduce

Create a self-contained project using the template of your choice, apply the minimum required code to result in the issue you're observing.

        static void Main(string[] args)
        {
            var telemetryClient = new TelemetryClient();

            var failedOperation = telemetryClient.StartOperation<RequestTelemetry>("myoperationname");
            failedOperation.Telemetry.Success = false;
            telemetryClient.StopOperation(failedOperation);

            telemetryClient.Flush();
            Console.ReadKey();
        }

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
* If we will not be able to repro the behavior you're reporting

**Comment by auslavs** [comment]
I see this has come up on StackOverflow questions, and registered as some stale issues here.
Are there any plans to make this a bit more user friendly / explicit?
