### ISSUE TITLE
Please add detail from ApplicationInsights-dotnet-logging repo README to this one

### ISSUE THREAD

**Issue by IanKemp** [microsoft/ApplicationInsights-dotnet#2083]
https://github.com/microsoft/ApplicationInsights-dotnet-logging/blob/develop/README.md has useful links and code samples for how to integrate AppInsights with well-known logging providers, but that info doesn't seem to appear either in this repo's README or in develop/docs/concepts.md.

At the very least, https://docs.microsoft.com/azure/application-insights/app-insights-asp-net-trace-logs should be linked to from this repo.

**Comment by cijothomas** [comment]
The same content from (old( logging repo is here as well: https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/LOGGING/README.md

**Comment by IanKemp** [comment]
I suppose I should've searched first, huh. Doesn't change the fact that that doc isn't particularly discoverable - I'm also not sure how much of it is still correct/relevant and how much of it is simply repeating what's at https://docs.microsoft.com/azure/application-insights/app-insights-asp-net-trace-logs.

Basically, I'm saying I think there should be *something* about the logging providers in the current README, but I'm not enough of a domain expert to say how extensive that something should be. If I wasn't unsure about that I would've just made a PR to README.md with the link to https://docs.microsoft.com/azure/application-insights/app-insights-asp-net-trace-logs but I want to do what's correct, not just what's easy.

**Comment by IanKemp** [comment]
Not stale.
