### ISSUE TITLE
ExceptionTelemetry clears all Context setting after setting ExceptionTelemetry.Exception

### ISSUE THREAD

**Issue by ameltzerMSFT** [microsoft/ApplicationInsights-dotnet#2086]
* Verified using version 2.14.0 (with .NET 4.5) and 2.15.0 (with .NET 4.5.2)
* Hosting environment is Windows

### Describe the bug
A new context is created in an ExceptionTelemetry instance when using the Exception property setter. This unexpectedly clears any previously set Context values from the object.

### To Reproduce

```powershell
$ex = new-object Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry
$ex.Context.User.AccountId = "AccountId"
$ex.Context.User.AuthenticatedUserId = "AuthUserId"
$ex.Context.User.UserAgent = "ExceptionComponent"

Write-Host "Before"
Write-Host "-----------------------------------------------------"
$ex.Context.User | fl -Force

$ex.Exception = new-object System.Exception

Write-Host "After"
Write-Host "-----------------------------------------------------"
$ex.Context.User | fl -Force
```

Example output:
![image](https://user-images.githubusercontent.com/26661268/95392220-3bc40a80-08ad-11eb-97d5-ee7a88c0ee8b.png)

Observe that in the "Before", the Context.User object is populated with values, and in the "After" it has been cleared away. Looking at the code, it looks like a brand new TelemetryContext is created when the setter for the Exception property is used. 

This seems like unexpected behavior and it is not specifically called out in [the API documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.exceptiontelemetry.exception?view=azure-dotnet#Microsoft_ApplicationInsights_DataContracts_ExceptionTelemetry_Exception). Setting the exception value from outside of the .ctor should not clear the existing Context values.

**Comment by avereshchak** [comment]
+1. It was totally unexpected to me after I implemented a telemetry processor which analyzes and hides sensitive exception data. I had to copy data from original context into a new one created by ExceptionTelemetry.Exception setter.

**Comment by avereshchak** [comment]
It's still there. Double-checked on Microsoft.ApplicationInsight 2.21.
