### ISSUE TITLE
RemoteDependency profiler failed to attach

### ISSUE THREAD

**Issue by Eneuman** [microsoft/ApplicationInsights-dotnet#2099]
Running on a Windows 2012 R2 server with .net Framework 4.8

### Describe the bug
Im trying to find the root cause to why I cannot se any SQL statements in the Azure portal.
My application is instrumented with the following nuget packages:

```
  <package id="Microsoft.ApplicationInsights" version="2.15.0" targetFramework="net48" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.4.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.15.0" targetFramework="net48" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.15.0" targetFramework="net48" />
  <package id="Microsoft.ApplicationInsights.SnapshotCollector" version="1.4.0-pre-2010.1401" targetFramework="net48" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.15.0" targetFramework="net48" />
  <package id="Microsoft.ApplicationInsights.Web.TelemetryChannel" version="1.0.0" targetFramework="net451" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.15.0" targetFramework="net48" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.15.0" targetFramework="net48" />
  <package id="Microsoft.AspNet.TelemetryCorrelation" version="1.0.8" targetFramework="net472" />
```

On the server I have installed ApplicationStatusMonitor V2 and it seems to working fine.
In Azure portal I can see that all logged dependency calls uses SDK version | **rddf**:2.15.0-44797
So thats why I dont get any SQL statement I supose.

Using PerView I tracked down this error:

ThreadID="5 600" ProcessorNumber="0" error="System.InvalidOperationException: Failed to attach extension at Microsoft.Diagnostics.Instrumentation.Extensions.Base.Attach.ExtensionsAttachApi.Attach(String baseFolder, IEnumerable`1 writableLocations, String resourceNamePrefix, String nativeExtensionName, String nativeExtensionId, Int32 nativeExtensionPriority) at Microsoft.Diagnostics.Instrumentation.Extensions.Intercept.Internal.DecoratorInternal.Attach(String baseFolder, IEnumerable`1 writableLocations) at Microsoft.Diagnostics.Instrumentation.Extensions.Intercept.Decorator.InitializeExtension(String modulePath) at Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule.InitializeForRuntimeProfiler() in /_/WEB/Src/DependencyCollector/DependencyCollector/DependencyTrackingTelemetryModule.cs:line 196 at Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule.InitializeForRuntimeInstrumentationOrFramework() in /_/WEB/Src/DependencyCollector/DependencyCollector/DependencyTrackingTelemetryModule.cs:line 339" appDomainName="/LM/W3SVC/11/ROOT-1-132479240724294743" **FormattedMessage="RemoteDependency profiler failed to attach. Collection will default to EventSource implementation**. Error details: System.InvalidOperationException: Failed to attach extension at Microsoft.Diagnostics.Instrumentation.Extensions.Base.Attach.ExtensionsAttachApi.Attach(String baseFolder, IEnumerable`1 writableLocations, String resourceNamePrefix, String nativeExtensionName, String nativeExtensionId, Int32 nativeExtensionPriority) at Microsoft.Diagnostics.Instrumentation.Extensions.Intercept.Internal.DecoratorInternal.Attach(String baseFolder, IEnumerable`1 writableLocations) at Microsoft.Diagnostics.Instrumentation.Extensions.Intercept.Decorator.InitializeExtension(String modulePath) at Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule.InitializeForRuntimeProfiler() in /_/WEB/Src/DependencyCollector/DependencyCollector/DependencyTrackingTelemetryModule.cs:line 196 at Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule.InitializeForRuntimeInstrumentationOrFramework() in /_/WEB/Src/DependencyCollector/DependencyCollector/DependencyTrackingTelemetryModule.cs:line 339" `

My website is running as ApplicationPoolIdentity

Any idea why it cannot attach or where I can continue digging?

**Comment by cijothomas** [comment]
You are right that lack of profiler is the reason why you cannot see SQL statements. Its confirmed as dependncysdkversion if "rddf".

Is this (https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-api-reference#enable-instrumentationengine) the command you ran on your server to install the instrumentationengine? Did that command throw any error? Did you restart the IIS after the above command?

**Comment by Eneuman** [comment]
@cijothomas Yes it is. My Application is also instrumented using the SDK. Does this stop the Application Insight Agent from capturing the SQL commands?

I also found events where the AI Agent said that the application was already intrumented.

**Comment by cijothomas** [comment]
You should *only* have to do Enable-InstrumentationEngine command, restart IIS, restart app.
