### ISSUE TITLE
UWP app does not start with AI 2

### ISSUE THREAD

**Issue by bbougot** [Microsoft/ApplicationInsights-dotnet#210]
I've just upgraded Application Insights to version 2, and I've just had an issue: my app does not launch anymore!

Here's my App.xaml.cs (I'm using Template10)
 
        sealed partial class App : BootStrapper   {
        public App()
        {
            WindowsAppInitializer.InitializeAsync();
            InitializeComponent();
            SplashFactory = e => new ExtendedSplash(e);
        }

        public override async Task OnInitializeAsync(IActivatedEventArgs args)
        {
            // set sync context for ui thread so async void exceptions can be handled, keeps process alive
            AsyncSynchronizationContext.Register();
            await Task.CompletedTask;
        }
    }

OnInitializeAsync is called with AI 1.2.3, and when upgrading to v2, breakpoint is not hit

**Comment by SergeyKanzhelev** [comment]
@izikl please do not use AI 2.0 for UWP applications. There will be migration story from AI 1.2 to Hockey App SDK soon. Sorry for inconvenience.

See this post: https://azure.microsoft.com/en-us/blog/transitioning-mobile-apps-from-application-insights-to-hockeyapp/ and this post: http://hockeyapp.net/blog/2016/03/11/welcome-application-insights-users.html
