### ISSUE TITLE
 Azure Application Insights - Collecting Performance Counter From Azure Service Fabric Nodes Using Azure Application Insights Fails

### ISSUE THREAD

**Issue by TestUser0811** [microsoft/ApplicationInsights-dotnet#2101]
Need to get Performance counter details like CPU, Memory of Azure Service Fabric nodes using Azure Application insights, to understand what specifically limits the load on the Azure SF cluster.

As per [link](https://docs.microsoft.com/en-us/azure/azure-monitor/app/performance-counters#collecting-performance-counters-in-code-for-aspnet-core-web-applications), modified "ConfigureServices" method in our Startup.cs class.

Note: the code shown below is taken from .Netcore2.1 Web API project deployed on Azure service fabric cluster

     using Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector;
     public IServiceProvider ConfigureServices(IServiceCollection services)
       {
        var aiOptions = new Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions();
        aiOptions.EnableAdaptiveSampling = false;
        aiOptions.EnableQuickPulseMetricStream = true;
        aiOptions.InstrumentationKey = "cxxxxxx4-2xx6-xxx1-axxf-071xxxxxxxb";
        services.AddApplicationInsightsTelemetry(aiOptions);

        // The following configures PerformanceCollectorModule.
        services.ConfigureTelemetryModule<PerformanceCollectorModule>((module) =>
        {
            // the application process name could be "dotnet" for ASP.NET Core self-hosted applications.
            module.Counters.Add(new PerformanceCounterCollectionRequest(
      @"\Process([**_dotnet_**])\Page Faults/sec", "DotnetPageFaultsPerfSec")); //not sure "dotnet" is right value here?
        });

        //Add MVC
        services.AddMvcCore(options =>
        {
            options.Filters.Add(new LoggingFilter(_container.GetInstance<IMemoryCache>()));
        });
      }
Also edited .csproj to add the following line

       <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.3.0" />

  <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.3.0" />
Still 'PerformanceCounter' table on Azure Application Insights remains empty. What needs done? What I'm missing?

image

![image](https://user-images.githubusercontent.com/54196915/97294247-c1ffbb00-1873-11eb-935f-9a848b177dc4.png)

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/performance-counters#performance-counters-in-aspnet-core-applications

**Comment by TestUser0811** [comment]
services.ConfigureTelemetryModule<PerformanceCollectorModule>((module) =>
    {
        // the application process name could be "dotnet" for ASP.NET Core self-hosted applications.
        module.Counters.Add(new PerformanceCounterCollectionRequest(
  @"\Process([**_dotnet_**])\Page Faults/sec", "DotnetPageFaultsPerfSec")); **//not sure "dotnet" is right value here?**
    });

BTW data shown on 'PerformanceCounter' table of Azure Application Insights are a**pplication related or infrastructure related?**

While trying out with "Microsoft.ApplicationInsights.AspNetCore" Version="2.8.2" encountering obsolete warning as shown in the attached image, how to overcome? 

    <PackageReference Include="Microsoft.ApplicationInsights.PerfCounterCollector" Version="2.15.0" />
     <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.8.2" />

![image](https://user-images.githubusercontent.com/54196915/97332539-93e4a000-18a0-11eb-94cd-9b2ea257043f.png)

**Comment by cijothomas** [comment]
Please check the doc link I shared above. Perfcounters are not supported in Asp.Net Core applications.

**Comment by TestUser0811** [comment]
But I can able to get 'Perfcounters' from  Asp.Net Core 2.1 applications. 
After upgradation "Microsoft.ApplicationInsights.AspNetCore" from  from Version="2.3.0"  to Version="2.8.2" 

With below code,
     public IServiceProvider ConfigureServices(IServiceCollection services)
        { 
            var aiOptions = new Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions();
            aiOptions.EnableAdaptiveSampling = false;
            aiOptions.EnableQuickPulseMetricStream = true;
            aiOptions.InstrumentationKey = "XXXXX-XXX-XXX-a97xxxxxxxxxxb";
            services.AddApplicationInsightsTelemetry(aiOptions);

            // The following configures PerformanceCollectorModule.
            services.ConfigureTelemetryModule<PerformanceCollectorModule>((module) =>
            {
                // the application process name could be "dotnet" for ASP.NET Core self-hosted applications.
                module.Counters.Add(new PerformanceCounterCollectionRequest(
      @"\Process([dotnet])\Page Faults/sec", "DotnetPageFaultsPerfSec"));
            });

            //Add MVC
            services.AddMvcCore(options =>
            {
                options.Filters.Add(new LoggingFilter(_container.GetInstance<IMemoryCache>()));
                options.Filters.Add(new LoggingFilter(_container.GetInstance<IMemoryCache>()));
                options.ModelBinderProviders.Insert(0, new GrantModelBinderProvider());
            })  

**Screenshot from Application Insight Instance,**

![image](https://user-images.githubusercontent.com/54196915/97336976-aad9c100-18a5-11eb-8cde-ed031572fe55.png)

**Comment by TestUser0811** [comment]
@cijothomas, 

Any update? 
Is the above approach, right approach to get performance counters from .net core2.1 webapi project which inturn runs on  Azure SF cluster?
Getting performance counters using the approach I have mentioned above, is reliable? 
Please clarify.

**Comment by cijothomas** [comment]
There is limited support for perf counters in Asp.Net Core.
Are you seeing *any* perf counters at all? or not seeing the ones you configure additionally?

**Comment by TestUser0811** [comment]
With Microsoft.ApplicationInsights.AspNetCore Version="2.8.2", I'm getting  below performance counters like "Available Bytes", "% Processor Time" etc (attached image for your reference). Not sure these performance counter values are reliable, as they are retrieved by Aps.net core sdk but not by dedicated oms agents. Are performance counter values retrieved by  Asp.Net Core reliable?

My requirement is to get basic  performance counters like CPU & Memory utilization by  Asp.Net Core web api deployed on each Azure fabric cluster nodes not any additional or custom metrics

![image](https://user-images.githubusercontent.com/54196915/97483240-36725100-197d-11eb-8898-77b11770a143.png)

**Comment by cijothomas** [comment]
Your screenshot shows you are *already* getting performance counters. So what is the question?

**Comment by TestUser0811** [comment]
monitoring the system from within the system using  Asp.Net Core, is right approach?

**Comment by cijothomas** [comment]
> monitoring the system from within the system using Asp.Net Core, is right approach?

I cannot offer any official guidance on that part.
Here's what I know:
PerfCounters are published for a lot of "system" things like Memory, Network, and also for Application specific like "Asp.Net, Process CPU" etc.
You can query/ready perfCounters either from Application or from an agent.
Its quite likely multiples app read the same data if they run in same host machine - in those cases collecting it via agent might be most efficient. 
Application Insights SDK support reading perf counters (some limitations aside) - its upto you to decide if you want to leverage that or use an agent based approach.

If you are most interested in knowing about .NET Runtime things like (GC pressure, heap size etc), it *may* be best to use EventCounters. https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters
