### ISSUE TITLE
Broken JSON string in _MS.links truncated at the character limit for custom dimensions

### ISSUE THREAD

**Issue by berkerley123** [microsoft/ApplicationInsights-dotnet#2105]
The SDK truncated the _MS.links JSON at the character limit for custom dimensions, i.e., 8192. 
This caused the details blade failed to parse the truncated JSON and caused "SyntaxError: Unexpected end of JSON input". 
It should instead reduce the items in _MS.links to fit without truncation and produce a valid JSON for downstream service to parse.
We notice this in telemetry from the users of the Details blade and the involved SDK is `rdddsc 2.14.0-17971`.

**Comment by rajkumar-rangaraj** [comment]
This issue might happen with more number of links attached to `Activity`. We could set a hard limit on number of links that could get added to properties. This avoids the value of `_MS.links` property gets truncated.
