### ISSUE TITLE
App Insights Dependency tracking for Azure Cosmos DB with TCP mode

### ISSUE THREAD

**Issue by Kapkan-Lesion** [microsoft/ApplicationInsights-dotnet#2106]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like.**
I have noticed that App insights documentation stated that only HTTP calls are tracked as dependency for Azure Cosmos DB end-to-end and TCP mode is not supported. Is there any plan for Azure to implement something which will allow for TCP mode to be tracked?

**Describe alternatives you've considered.**
Are there any potential code alterations we can do in Azure Function App to make App Insights track this?

**Additional context.**
I am running an Azure Function App connected to Cosmos DB (TCP mode), the idea here is that I want to track Cosmos DB calls in our function app as dependency in end-to-end transaction logs, I do note that TCP is explicitly stated to be not supported in App insights' documentation. More than happy to hear if there are any potential workarounds that can achieve this use case!

**Comment by cijothomas** [comment]
Current option is limited to manual tracking using TrackDependency() API.
The goal is to eventually support automatic tracking of all Azure Services which uses the official Azure SDKs. No ETA yet on when Azure Cosmos DB specifically is going to be supported.

**Comment by CallumRBreen** [comment]
> The goal is to eventually support automatic tracking of all Azure Services which uses the official Azure SDKs. No ETA yet on when Azure Cosmos DB specifically is going to be supported.

Do you know if there is an ETA now?

**Comment by cijothomas** [comment]
Cosmos support is available in latest beta version

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/CHANGELOG.md#version-2220-beta1 has support for Cosmos. 
https://github.com/microsoft/ApplicationInsights-dotnet/pull/2635

**Comment by CallumRBreen** [comment]
> @cijothomas Is there a specific package I need to use? I've tried some of the current preview packages (version 2.22.0-beta1), but none of them seem to pick up the Cosmos dependencies.
> 
> Using a function app v4, net6.0 in-process and Microsoft.Azure.Cosmos 3.31.2 package. Other dependencies are being logged, so AI is working.

Unable to get dependency telemetry to show as well. Using:

.NET 7, C#11
Microsoft.ApplicationInsights 2.22.0-beta1
Microsoft.ApplicationInsights.AspNetCore 2.22.0-beta1
Microsoft.ApplicationInsights.WorkerService 2.22.0-beta1
Microsoft.Azure.Cosmos 3.31.2

@cijothomas is there anything else that I need to configure?

**Comment by cijothomas** [comment]
Could you open a new issue for this? Please include a minimal code snippet showing how you make CosmosDb call as well.
Based on this (https://github.com/microsoft/ApplicationInsights-dotnet/pull/2635#issuecomment-1291127727), its not clear if there is a minimum version of CosmosDb needed for this to work.
