### ISSUE TITLE
Dependencies missing in Azure but are show in Debug window

### ISSUE THREAD

**Issue by mendoncaftw** [microsoft/ApplicationInsights-dotnet#2110]
NETCore 3.1 web api with
`<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.16.0" />`
and on Startup.cs
`services.AddApplicationInsightsTelemetry();`

Have a simple Controller with an endoint with the following code:
```
var startTime = DateTime.UtcNow;
var timer = System.Diagnostics.Stopwatch.StartNew();

var httpClient = new HttpClient
{
    BaseAddress = new Uri("https://www.google.com")
};
await httpClient.GetAsync("/");

_telemetryClient.TrackDependency("HTTP", "HttpClient", "https://www.google.com", startTime, timer.Elapsed, true);

_telemetryClient.Flush();
```

**Requests and Traces/logs show up** on Application Insights Search blade on Azure Portal and also Metrics on their own blade.
**Automatic dependency tracking or manual dependency** tracking shows up locally on VS in the Debug Console but **never on Azure**.
`Application Insights Telemetry: {"name":"AppRequests", ...`

`Application Insights Telemetry: {"name":"AppDependencies",...`

Seems something really simple might be missing but it should work out of the box as HttpClient is an automatically tracked dependency but even the manual code above doesn't show up (with the manual tracking, on VS Debug Console I get the auto dependency tracking message and also the manual one).

**Comment by kirk-marple** [comment]
I just had a similar issue, and I believe it's due to a version mismatch between 2.14 and 2.16 of Microsoft.ApplicationInsights package.

Azure Functions core tools comes with 2.14, and my projects were using 2.16.

If I debugged into it, looking at the TelemetryClient was showing me a package version mismatch.

By backdating my packages to 2.14, now I can see a valid TelemetryClient.

**Comment by mendoncaftw** [comment]
Since you mentioned Fuctions, I also happen to have a Functions project and when integration with Applications Insights I had the mismatch you mentioned (had to downgrade to 2.14) plus all the changes I make to the injected TelemetryConfiguration are ignored (can't change app version, component name, etc). But it's a problem for another time 😄 as I have given up on everything but logging for the moment.

Still, the problem persists on the NETCore API I mention above (no version mismatch warnings + can successfully set the version, cloud role name, etc).
