### ISSUE TITLE
High CPU utilization on Azure Web Apps caused by QuickPulseTelemetryModule

### ISSUE THREAD

**Issue by tatarincev** [microsoft/ApplicationInsights-dotnet#2114]
* Runtime version: netcoreapp3.1, Microsoft.ApplicationInsights.AspNetCore 2.15.0
* Hosting environment: Azure Web App

### Describe the bug

Sometimes without any reason, we run in the high 100% CPU utilization on one of our Azure Web Apps that can only be fixed by restarting the application.

The CPU profiler snapshot is taken from the problem Azure Apps shows the **3-4K**!  stale threads and this hot path 

`Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule.CollectionThreadWorker`
![image](https://user-images.githubusercontent.com/7566324/99709063-5a6e1180-2aa7-11eb-9cf8-beca3647cce5.png)

We use the `Adaptive sampling` rate with default configuration AI. 

We really count on your help, and ready to provide any additional diagnostic data by request

**Comment by firephantomassasin** [comment]
Same here, we are experiencing very high cpu, even restarting the web app doesn't help. The entire server is busted

**Comment by OlegoO** [comment]
same problem for us (

**Comment by cijothomas** [comment]
Thanks all for reporting. Can you confirm the version of the SDK used? The original post said 2.15 - since there was no fixes done around quickpulse/livemetrics, I suspect if this is an issue in 2.15, then it is still an issue in newer version, and most likely older versions as well.

**Comment by cijothomas** [comment]
@tatarincev could you get a process dump and share with us when was CPU is high? (i.e when the repo is still live)

**Comment by tatarincev** [comment]
@cijothomas  Sure, how is a better way to share it with you?

**Comment by tatarincev** [comment]
Previously we used the AI 2.12  version so changes could be introduced between 2.12 and 2.15 versions. We also noticed that in Azure our applications were starting to generate an absolutely enormous qty of telemetry data with type Metrics for 2.15 version after update.
![image](https://user-images.githubusercontent.com/7566324/99981462-16825180-2db2-11eb-91ce-79a4f24e444e.png)

Can we somehow control/reduce/filter the quantity for telemetry that has the type  Metric that system produces? 
Any suggestion is acceptable. We can do the changes in code or in AI settings on the Azure portal

**Comment by cijothomas** [comment]
@tatarincev The new metrics must be EventCounters - a huge set of defaults was collected. But this was removed in 2.15, so you shouldn't see any of them (unless you opt-in). (https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters#default-counters-collected) If its not EventCounters, we'll need to take a closer to find where this additional metric is coming from. You can ofcource write processors to drop it, but its best to find where they are coming from and then fix the root of the issue.

**Comment by cijothomas** [comment]
> @cijothomas Sure, how is a better way to share it with you?

If you have a support plan with Microsoft Azure, you can open a support ticket from the portal.
Otherwise, let me ask around for the suggested way of sharing dumps.

**Comment by tatarincev** [comment]
Yes, we have.  Here is the ticket number 120112325003975 where we attached the diag sessions.

**Comment by tatarincev** [comment]
@cijothomas I see that in the 2.15 version the `ApplicationInsightsServiceOptions.EnableEventCounterCollectionModule`  still has a **true** as default value.  https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/NETCORE/src/Shared/Extensions/ApplicationInsightsServiceOptions.cs#L52

**Comment by cijothomas** [comment]
> @cijothomas I see that in the 2.15 version the `ApplicationInsightsServiceOptions.EnableEventCounterCollectionModule` still has **true** as default value. https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/NETCORE/src/Shared/Extensions/ApplicationInsightsServiceOptions.cs#L52
> This is a little contradictory to what you wrote above.

The module itself is enabled, but has no counters configured. So net effect - there would be no counters collected.

**Comment by tatarincev** [comment]
@cijothomas  I'm pretty sure that we have the default AI configuration without especially opt-in metrics, maybe you have any idea why the application still generate so many telemetry with **Metric** type?  Because it is also a big issue, we exceed the daily quotas very fast.

**Comment by cijothomas** [comment]
> @cijothomas I'm pretty sure that we have the default AI configuration without especially opt-in metrics, maybe you have any idea why the application still generate so many telemetry with **Metric** type? Because it is also a big issue, we exceed the daily quotas very fast.

Could you share a few sample telemetry which are in MetricTelemetry table?

**Comment by tatarincev** [comment]
![image](https://user-images.githubusercontent.com/7566324/99999739-4426c500-2dc9-11eb-9873-41d6e8be98ef.png)
My AI application log doesn't contain such a table

**Comment by cijothomas** [comment]
customMetrics - this is the one we are after.

**Comment by tatarincev** [comment]
![image](https://user-images.githubusercontent.com/7566324/100000415-3c1b5500-2dca-11eb-9777-dcb2886f581e.png)

**Comment by cijothomas** [comment]
@cijothomas This is EventCounter definitely. - Please check the SDKVersion field for these telemetry.

**Comment by tatarincev** [comment]
evtc:2.13.1-12554

**Comment by cijothomas** [comment]
> evtc:2.13.1-12554

Means either your application is still in 2.13 of the SDK, or have another application(s) using 2.13 sending telemetry to this ikey.

**Comment by tatarincev** [comment]
Thanks, I'll check more precisely.  I think the one problem with extra telemetry can be probably solved. 👍  But the problem with the CPU is still relevant, may we count for your help with that? Will you have a chance to look at it digressions that we attached to the ticket?

**Comment by cijothomas** [comment]
> Thanks, I'll check more precisely. I think the one problem with extra telemetry can be probably solved. 👍 But the problem with the CPU is still relevant, may we count for your help with that? Will you have a chance to look at it digressions that we attached to the ticket?

Yes. The support ticket will be looked at following regular process. You should be getting updates in the ticket directly.
We'll post any learnings/bugs/issues back here for everyone else to see.

**Comment by OlegoO** [comment]
@cijothomas  I posted my data here https://github.com/microsoft/ApplicationInsights-dotnet/issues/1632

**Comment by firephantomassasin** [comment]
@tatarincev have you solve this issue?

**Comment by tatarincev** [comment]
@firephantomassasin Not yet, we are temporarily using this workaround to disable collection for dependencies. It helps 100%, but we are "blind" to all dependencies requests. We are still awaiting a solution from the MS/AI team.

```
ApplicationInsights:EnableDependencyTrackingTelemetryModule = false
```

**Comment by firephantomassasin** [comment]
@tatarincev  where did you specify this EnableDependencyTrackingTelemetryModule ? Is it in ApplicationInsights.config file?

**Comment by tatarincev** [comment]
in the appsettings.json

**Comment by OlegoO** [comment]
@cijothoma any feedback?

**Comment by cijothomas** [comment]
@OlegoO no. We just started (today) an investigation based on a support case. There is no update to be shared yet.
Do you have a shareable repro for this behavior? It looks like a bunch of issues are mixed together.

1. Telemetry volume increase due to new customMetrics - this is from EventCounter, and this is already removed from 2.15 onwards.
2. Potential high CPU issue, suspected to be in QuickPulse module.
3. https://github.com/microsoft/ApplicationInsights-dotnet/issues/2114#issuecomment-744408333 says the issue mitigated when DependencyCollection is turned off. Its not yet clear if 2 and 3 are interconnected.

The increase in threadcount with QuickPulse in the stack is concerning, but we haven't got a repro yet - it'd be very helpful if you can share a minimal repro?

**Comment by tatarincev** [comment]
@cijothomas 1. The increase in telemetry volume due to new problems with customMetrics has already been resolved, and you can ignore it.
Although the problem with  High CPU utilization is still relevant, we can't provide you 100% way how to reproduce this issue, we catch it randomly on some of our app instances if do not disable this option `ApplicationInsights:EnableDependencyTrackingTelemetryModule = false`. 
All CPU profiles that we took show the same picture with thousands of stale threads of AI telemetry perf collector.

**Comment by cijothomas** [comment]
@tatarincev Yes.
I was asking if anyone else has luck getting consistent repro. (the fact that the repro is gone when disabling the DependencyTrackingModule is still to be investigated and understood.)

**Comment by cijothomas** [comment]
From the dumps we received and investigated, the issue is not in QuickPulseTelemetryModule, but rather due to the fact than multiple instance of this modules are somehow created. *Every* Application Insights module (like RequestTrackingModule, QuickPulse, DependencyTrackingModule.etc) are present "n" times, as opposed to having a single instance, registered in the DI. QuickPulse contains a background task which polls every 5 sec, thats why its shown in the call stacks.

We do not know why these modules are registered more than once - https://github.com/microsoft/ApplicationInsights-dotnet/blob/81288f26921df1e8e713d31e7e9c2187ac9e6590/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs#L320 shows that calling AddApplicationInsightsTelemetry() multiple times would not result in this, as long as the same IServiceCollection is used. 

Could you check if there is any way the application has multiple IServiceCollections registered ?

**Comment by tatarincev** [comment]
Hi, thanks for your response. 
We checked your hypothesis about multiple registration  AI into IServiceCollection for our application and it seems didn't confirm. We added some diagnostic to our code to be able to see what services are registered in the IServiceCollection in runtime and got this picture. 
![image](https://user-images.githubusercontent.com/7566324/104884915-d1246f80-596f-11eb-92a4-93ee7dcc43b9.png)

By this link, you can find the code that we call in `statup.cs` to register AI for application for our application.  We have double-checked that this code is executed only once. 
https://github.com/VirtoCommerce/vc-platform/blob/master/src/VirtoCommerce.Platform.Web/Telemetry/ServiceCollectionExtensions.cs#L17

In the alternative, I had an unsuccessful attempt with forwarding AI log output into the console to see more details about how many  AI Perf collectors are initialized during runtime. But had no luck.

Maybe you can suggest an alternative way of how we can check how many Perf collector StateThreadWorker are working at the same time? Any point to documentation or examples will be appreciated.

**Comment by tatarincev** [comment]
Finally, we figure out the problem! 
The problem was that we had the following code
`startup.cs`
```C#
...
public void ConfigureServices(IServiceCollection services)
{
...
services.AddApplicationInsightsTelemetry();
//we call services.BuildServiceProvider() many times in other places after adding AI in the DI
}
...
```
We call multiple times the `IServiceCollection.BuildServiceProvider` after AI registration, I know it is bad practice to resolve dependencies during configuration, but at that moment it was a single way for us.

Since the AI initializes all own modules during configuration we got after each `BuildServiceProvider` calls the new running  AI module and all of that leads to a picture with the telemetry data flood and problems with CPU on production.

The solution was pretty simple:
we moved the `services.AddApplicationInsightsTelemetry();`  at the end of `ConfigureServices` method. That completely fixes the problem.

@cijothomas thank you for your help, thank you we managed this issue.

I think the AI product team should consider this case, and do something with initialization to prevent such cases in the future.

**Comment by cijothomas** [comment]
@tatarincev Glad you got resolution.

Asp.Net Core advices against calling BuildServiceProvider() from application code.
https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#ASP0000

**Comment by cijothomas** [comment]
For anyone else facing similar issue:
The way we and @tatarincev was able to confirm that the issue is locally reproing is by collecting SDK logs (https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data#troubleshooting-logs) and check if any module is initialized more than once. We picked DependencyTrackingModule as an example and checked for the text "Initializing DependencyTrackingModule" in the SDK logs. Its expected to occur once, but was occurring multiple times. This confirm the issue is repro-ed locally as well. (It won't likely lead to 100% cpu in local, as the volume is low.)

**Comment by OlegoO** [comment]
> For anyone else facing similar issue:
> The way we and @tatarincev was able to confirm that the issue is locally reproing is by collecting SDK logs (https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data#troubleshooting-logs) and check if any module is initialized more than once. We picked DependencyTrackingModule as an example and checked for the text "Initializing DependencyTrackingModule" in the SDK logs. Its expected to occur once, but was occurring multiple times. This confirm the issue is repro-ed locally as well. (It won't likely lead to 100% cpu in local, as the volume is low.)

You save my day
