### ISSUE TITLE
.Net5.0 Azure Api Web App Throws error on startup

### ISSUE THREAD

**Issue by CoryKoehler** [microsoft/ApplicationInsights-dotnet#2118]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
* Packages:    
```
 Microsoft.ApplicationInsights" Version="2.16.0" 
 Microsoft.ApplicationInsights.AspNetCore" Version="2.16.0" 
```
* Runtime version .Net 5.0
* Azure Web Api App, App Service on Windows

### Describe the bug
Error being thrown on hosting startup when deployed to azure app service. Does not occur locally.
This is an API not seeing this behavior on same azure app service with blazor server side app.

This is similar to previous issues:
https://github.com/dotnet/aspnetcore/issues/14547
https://github.com/dotnet/aspnetcore/issues/17370 

`Category: Microsoft.AspNetCore.Hosting.Diagnostics EventId: 11 Hosting startup assembly exception Exception: System.InvalidOperationException: Startup assembly Microsoft.ApplicationInsights.StartupBootstrapper failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ApplicationInsights.StartupBootstrapper, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. File name: 'Microsoft.ApplicationInsights.StartupBootstrapper, Culture=neutral, PublicKeyToken=null' at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly) at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext) at System.Reflection.Assembly.Load(AssemblyName assemblyRef) at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ExecuteHostingStartups() --- End of inner exception stack trace --- `

### To Reproduce
Deploy azure api web app with .NET Core AppInsights turned on in portal
![image](https://user-images.githubusercontent.com/5295679/100518886-78500c00-3162-11eb-9daa-d5262bc2789f.png)

**Comment by cijothomas** [comment]
Please use Azure support for issues with codeless issues. The codeless product is not opensource, and hence its best to open support ticket to get help with that.

**Comment by CoryKoehler** [comment]
Ok - Will do, thanks
