### ISSUE TITLE
.NET 5 support in Azure?

### ISSUE THREAD

**Issue by IanKemp** [microsoft/ApplicationInsights-dotnet#2119]
When attempting to create a .NET 5 web application in the Azure Portal, Application Insights cannot be selected. According to https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/dot_net_core.md#net-5-early-access-limitations:

> Application Insights is currently not supported for .NET 5 apps, we are working with the Application Insights team to resolve this.

According to this comment https://github.com/microsoft/ApplicationInsights-dotnet/issues/1960#issuecomment-725256663 the support is implemented.

Please can we have some information/ETA on when the Azure Portal will allow the creation of .NET 5 application with AppInsights support?

See also: https://github.com/Azure/app-service-linux-docs/issues/61

**Comment by cijothomas** [comment]
@IanKemp This SDK supports .NET 5. (as you found in the issue #1960)

The "codeless" support in Azure AppService - is a separate issue. The [codeless product](https://docs.microsoft.com/azure/azure-monitor/app/azure-web-apps?tabs=netcore) is not opensource, so the support for it is not going to come from this repo. However, here's what I can share:

There is no codeless support for Azure App Service linux. (This was not supported before .NET 5.0 either) Recommendation is to use the SDK approach.

For windows based Azure App Service, support for .NET5 will be added in the future. No ETA yet for that, its quite likely early 2021. Until then, only SDK based approach can be used there.

**Comment by thelazydogsback** [comment]
Are there updated instructions for manually configuring the AI SDK for (a) .net5 rather than .netcore 4.7 and (b) a web api project rather than MVC (different directory structure and prereqs -- e.g., no system.web.mvc.)
thanks

**Comment by cijothomas** [comment]
> Are there updated instructions for manually configuring the AI SDK for (a) .net5 rather than .netcore 4.7 and (b) a web api project rather than MVC (different directory structure and prereqs -- e.g., no system.web.mvc.)
> thanks

There is no special instructions for .NET5. The same SDK onboarding doc as before. If something is not working with that, please do create an issue.

**Comment by woeterman94** [comment]
Can you give a link to that doc please?

**Comment by patrickjlee** [comment]
For how you can configure a .NET 5.0 app service to use Application Insights, see https://pjlee.net/blog/application-insights-is-not-fully-supported-for-net-50-but-you-can-configure-it-manually.

**Comment by cijothomas** [comment]
Link to official docs for onboarding the SDK (shipped from this repo)
Asp.Net Core. (Supports all officially supported .NET Core version including .NET Core 2.1, 3.1, .NET 5.0 )
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core

Asp.Net (Supports all officially supported .NET Framework, starting with .NET452 and all newer)
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net
