### ISSUE TITLE
No stack traces from exceptions

### ISSUE THREAD

**Issue by marcomorain** [Microsoft/ApplicationInsights-dotnet#212]
I'm currently instrumenting a .NET / WPF app using the Application Insights SDK. Everything is working great, except for Exception tracking.

In Azure I cannot see any stack traces for the exceptions, instead I see the following for an exception logged with `TelemetryClient. TrackException`:

>
> ### Call Stack
> `call stack unavailable`

Do I need to do something extra to track call-stacks? After some searching online, I've seen some people manually add the call-stack as a property of the event. Are there any docs for this?

**Comment by SergeyKanzhelev** [comment]
@izikl can you please take a look?

**Comment by marcomorain** [comment]
Hrm, it seems that the stack-trace is attached when I call `TelemetryClient.TrackException` from inside a `catch`-block.

```c#
TelemetryClient tc = ...; // comes from somewhere
tc.TrackException(new Exception("no trace"));
try {
  throw new Exception("with trace");
} catch (Exception e) {
  tc.TrackException(e);  // does have exception attached.
}
```

I'm not very familiar with the CLR – are stack-traces only attached to exceptions when the stack is being unwound?

**Comment by abaranch** [comment]
It is not related to ApplicationInsights. When you manually create exception is has no stacktrace because it was not thrown.
Check this: new ApplicationException("Test").StackTrace
That would be null, because there is no stack.

**Comment by marcomorain** [comment]
Thanks @abaranch

**Comment by chrisdreams13** [comment]
Sorrry for post in an old closed issue. I create a class (the code bellow) that contains the stacktrace as @abaranch mention (showing the stacktrace in first image) but no matter than "Application Insights Telemetry" json (included also bellow) shows that "hasFullStack" is true, it appear that full stack is not sent (also included an image from app insights), I include part of the stacktrace inside the exception, there's a special format for the stack trace? or what is the correct way to send the satcktrace? is there a spacial name in properties dictionary and where to find a list of special properties?

Thanks a lot.

`public class StackTraceException: Exception
    {
        public StackTraceException(string message, string stackTrace = null) : base(message)
        {
            StackTrace = stackTrace ?? new StackTrace().ToString();
        }

        public override string StackTrace { get; }

        public override string ToString()
        {
            var s = InnerException?.GetType().ToString() ?? GetType().ToString();

            if (string.IsNullOrWhiteSpace(Message))
            {
                s += $": {Message}";
            }

            var stackTrace = StackTrace;
            if (stackTrace != null)
            {
                s += Environment.NewLine + stackTrace;
            }

            return s;
        }
    }` 

![image](https://user-images.githubusercontent.com/6045302/84839613-1b70f700-b003-11ea-81ca-2166f2a2b68c.png)

`Application Insights Telemetry: {
    "name": "Microsoft.ApplicationInsights.XXXXXXXXXXXXXXXXXX.Exception",
    "time": "2020-06-16T23:38:41.4013463Z",
    "iKey": "1f33bee2-eb36-4803-a817-XXXXXXXXX",
    "tags": {
        "ai.cloud.roleInstance": "XXXXXXXXXXXXXXXXXX",
        "ai.internal.sdkVersion": "il:2.10.0-41092"
    },
    "data": {
        "baseType": "ExceptionData",
        "baseData": {
            "ver": 2,
            "exceptions": [{
                    "id": 16605191,
                    "outerId": 0,
                    "typeName": "Core.StackTraceException",
                    "message": "Showing stack trace",
                    "hasFullStack": true
                }, {
                    "id": 13164703,
                    "outerId": 16605191,
                    "typeName": "System.Exception",
                    "message": "Exception to show stacktrace",
                    "hasFullStack": true
                }
            ],
            "severityLevel": "Error",
            "properties": {
                "RequestId": "XXXXXXXXX-0001-f900-b63f-84710c7967bb",
                "ActionName": "LocalService.Controllers.ManagerController.Index (LocalService)",
                "{OriginalFormat}": "C# Http trigger Ping function",
                "FormattedMessage": "C# Http trigger Ping function",
                "ActionId": "XXXXXXXXX-8607-4281-939e-4260af6c1ea4",
                "CategoryName": "Request",
                "RequestPath": "/api/v1/ping"
            }
        }
    }
}`

![image](https://user-images.githubusercontent.com/6045302/84839726-625eec80-b003-11ea-9376-d93c188b428d.png)

`   at Core.StackTraceException..ctor(String message, Exception innerException, String stackTrace)
   at Functions.HttpTrigger.v1.Maintenance.Ping(HttpRequest request, MaintenanceController controller, ICategoryLogger`1 log)
...`
