### ISSUE TITLE
Failure to correlate exceptions with request chains when using Activity and W3C context.

### ISSUE THREAD

**Issue by galvesribeiro** [microsoft/ApplicationInsights-dotnet#2122]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights.WorkerService on the background worker service (Microsoft Orleans) and Microsoft.ApplicationInsights.AspNetCore on the frontend WebAPI. Both on 2.16.0.

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
.Net 5

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
.Net console applications hosted on AKS.

### Describe the bug

When using AI to track the whole call chain across 2 services using `System.Diagnostics.Activity` and `StartOperation`/`StopOperation`, we're passing from one service to another the `Activity.Id` over the wire. The next service in the chain then call `Activity.SetParentId(receivedActivityId)` before calling `StartOperation(activity)`. That works perfectly and all the Request and Dependency telemetry are properly chained together as you may see on the following picture :

![image](https://user-images.githubusercontent.com/4714040/100883836-8f0e9f80-348f-11eb-9c5e-d1aebc17fdc4.png)

However, if we propagate an exception from the bottom of this chain and report it using a `ExceptionTelemetry` on every layer of those calls, it will report the exception on the portal. However, the exceptions are not aligned on the chart with the requests as it is supposed to be:

![image](https://user-images.githubusercontent.com/4714040/100889401-d7c95700-3495-11eb-9792-ba30f52a8df3.png)

The call chain is supposed to appear in the same way as on the first picture but instead of showing successful requests, show the red entries showing the errors/exceptions reported by `ExceptionTelemetry` but instead, they are not properly nested.

### To Reproduce

In an Asp.Net core controller we have something like this:

```cs
.....

var activity = new Activity("IHelloGrain.SayHello");

using var operation = this._telemetryClient.StartOperation<DependencyTelemetry>(activity);
operation.Telemetry.Type = "ORLEANS";

var grainRef = context.Grain.ToString().AsMemory().Slice(15);
operation.Telemetry.Target =
    $"{context.InterfaceMethod.DeclaringType.Name}({new string(grainRef.Span)})";

// Set the current Activity.Id as ParentId so it can be caught by the next service in order to follow on the correlation
RequestContext.Set(TelemetryHeaders.ParentId, activity.Id);

try
{
    // Invoke the external service
    await context.Invoke();
    success = true;
}
catch (Exception exc)
{
    var exceptionTelemetry = new ExceptionTelemetry();
    exceptionTelemetry.Context.Operation.Id = activity.RootId;
    exceptionTelemetry.Context.Operation.ParentId = activity.SpanId.ToString();
    
    exceptionTelemetry.Exception = exc;
    this._telemetryClient.TrackException(exceptionTelemetry);
    throw;
}
finally
{
    operation.Telemetry.Success = success;
    operation.Telemetry.Properties[GRAIN_INTERFACE] =
        context.InterfaceMethod.DeclaringType!.FullName;
    
    this._telemetryClient.StopOperation(operation);
}
```

Then, at the first external service, when the request is received I have this:

```cs
.....

Activity activity = new($"IHelloGrain.SayHello");

// Retrieve the Activity.Id sent by the caller on the request context and set it as the ParentId on the current Activity.
var parentId = RequestContext.Get(TelemetryHeaders.ParentId)?.ToString();
if (!string.IsNullOrWhiteSpace(parentId))
{
    activity.SetParentId(parentId);
}

bool success = false;

var operation =
    this._telemetryClient.StartOperation<RequestTelemetry>(activity);

// Set the ParentId to the this activity id so it can flow along deeper into the call chain.
RequestContext.Set(TelemetryHeaders.ParentId, activity.Id);

try
{
    // Invoke the next external dependency
    await context.Invoke();
    success = true;
}
catch (Exception exc)
{
    var exceptionTelemetry = new ExceptionTelemetry();
    exceptionTelemetry.Context.Operation.Id = activity.RootId;
    exceptionTelemetry.Context.Operation.ParentId = activity.SpanId.ToString();

    exceptionTelemetry.Exception = exc;
    
    this._telemetryClient.TrackException(exceptionTelemetry);
    throw;
}
finally
{
    operation.Telemetry.Success = success;

    this._telemetryClient.StopOperation(operation);
}
```

Then you have the same pair or code to track the request arriving on the next service.

The docs doesn't point exactly how a related telemetry (in this case `ExceptionTelemetry`) is supposed to be added properly to the chain.

My guess is that the following fields are not being properly set:

```cs
exceptionTelemetry.Context.Operation.Id = activity.RootId;
exceptionTelemetry.Context.Operation.ParentId = activity.SpanId.ToString();
```

So, is that a bug or are we doing something wrong with those `ExceptionTelemetry` properties?

Thank you!

**Comment by galvesribeiro** [comment]
Since we didn't heard form anyone here we've opened a ticket on Pro Direct support (120120224005188) but they are still investigating without any clues on what is going on.

It would be good to have some hands from the SDK team since the backend looks like are lost...

Thank you!

**Comment by toddfoust** [comment]
Hello galvesribeiro. We're seeing some data getting dropped due to invalid json. This is likely why we cannot build out the full e2e tree for that scenario. Thank you for the sample application. I'll setup the repro, investigate this and report back.

**Comment by toddfoust** [comment]
We have been able to isolate the problem. The silo app is sending invalid json telemetry, so we drop those records, specifically the Request Telemetry which is created in the TelemetryHelpers.GrainCallTelemetryReporter.Invoke(IIncomingGrainCallContext) method. 

If you collect a Fiddler Trace, then launch a debug version of Silo, followed by a debug version of AIPI, then repro the failing scenario by sending a request to https://127.0.0.1:5001/Hello?fail, then you will see a requests out to dc.services.visualstudio.com (the App Insights ingestion point) that returns a HTTP 400 response. When looking at the details of that failed attempt to send request telemetry to App Insights we get these details...

### Request
```json
{
    "data": {
        "baseType": "RequestData",
        "baseData": {
            "ver": 2,
            "id": "14da59e1cee42645",
            "name": "HelloGrain.SayHello",
            "duration": "00:00:02.6802651",
            "success": false,
            "properties": {
                "DeveloperMode": "true",
                "_MS.ProcessedByMetricExtractors": "(Name:'Requests', Ver:'1.1')",
                "GRAIN_IMPLEMENTATION": "SiloApp.HelloGrain",
                "GRAIN_INTERFACE": "GrainInterfaces.IHelloGrain",
                "PlayerWhoMadeRequest": "AnonymousRequest"
            }
        }
    }
}
```
### Response
```json
{
    "itemsReceived": 1,
    "itemsAccepted": 0,
    "errors": [{
        "index": 0,
        "statusCode": 400,
        "message": "**109: Field 'responseCode' on type 'RequestData' is required but missing or empty. Expected: string, Actual: undefined**"
    }]
}
```
According to the [Request Schema](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/Schema/PublicSchema/RequestData.bond), that response code field is required. 

    [MaxStringLength("1024")]
    [Description("Result of a request execution. HTTP status code for HTTP requests.")]
    60: required string 	 responseCode;


The request telemetry that gets created for the exception scenario never gets the responseCode field set. To fix this issue, you just need to make sure that the responseCode field gets set on the operation, while trapping for and handling the exception. 

Within your repro project, open the GrainCallTelemetryReporter.cs code file, find the Invoke(IIncomingGrainCallContext) method within the finally{} block just add a response code, say something like below, prior to calling StopOperation. 

    operation.Telemetry.ResposneCode = "500";

After doing that you should see the exception reported in the full parent-child e2e tree that you are expecting. I'll have Francisco reach out to you on your open case for any follow up questions on this. 

Cheers
-Todd

**Comment by galvesribeiro** [comment]
Hello!

I just got an email from the support engineers on my case related to this problem. They suggested the same thing (I don't know if you guys were aligned on that).

So, understood the problem and will make some tests tomorrow and hopefully this is the case.

Regardless, this is a bad experience for the users. I'm not making API request myself sending JSON. They are made by the AI SDK NuGet Packages which I would expect to validate the required fields and throw an exception in case something wasn't set and is required. Another way to avoid that is by setting a default StatusCode like 200 to all Request or Dependency telemetry objectes. Since AI is not _specifically_ for HTTP workloads, I would go even further and not make that field mandatory at all since like in my case, Orleans is not an HTTP workload but instead a TCP socket service.

Will report back my findings Tomorrow. Thanks!

**Comment by galvesribeiro** [comment]
I just tested and it works.

I would strongly advise to change the SDK to comply with that field being a requirement. Not just silently fail.

Thank you! Will update the support ticket.

**Comment by toddfoust** [comment]
That's great. Also, thank you for the feedback. You are right, if the ingestion endpoint performs a very standard validation on all incoming data, and we have a public schema for it, then it's fair to ask our client SDKs to participate in that validation for required fields prior to sending those payloads over to the ingestion endpoint. I'll reach out to the team on this request. 

Cheers
Todd

**Comment by cijothomas** [comment]
SDK is designed to not throw exceptions from any `Track...()` methods in general, even if bad data is present. It should have logged the issue in EventSource (as with any other issues). Its debatable whether SDK should have fallen back to some default ResultCode.

**Comment by galvesribeiro** [comment]
Ok. We lost a week and had to use a Sev A support ticket to get this sorted out. If the exception was thrown, we could have saved all this time (and money). If throwing is not an option, some default value should be set. Having only the EventSource logs is very difficult to debug and I believe 99% of the users of AI would never know what todo. 

The docs are clear about the requirement of that field over the REST API but, we are not using the REST API and it is expected by any SDK/library consumer that the input should be validated and if anything fail, it should guard itself and not silently fail.

**Comment by cijothomas** [comment]
Yea fully agree SDK should do something better than this! I was just emphasizing that throwing Exceptions is not generally allowed from a telemetry sdk.

**Comment by cijothomas** [comment]
Closing this as the original issue is resolved.

There are lot of opportunities to improve data validation strategy which can be tracked separately. (Most likely, these issues are going to be handled in the Opentelemetry route, not in this repo)
