### ISSUE TITLE
Availability Test in Application Insights atuomatically disables

### ISSUE THREAD

**Issue by ketaanhshah** [microsoft/ApplicationInsights-dotnet#2124]
Hi All,
We have a very simple Application Insights Availability Test (That hits an HTTPS URL across 4 US regions) (basically it hits our App Service).
What we have observed it this Availability test automatically stops (not a fixed scheduled) but it abruptly stops and then what we have to do is go back to Availability test Edit the Test and Save it again so that it restarts.
This is really weird as we have checked the Activity log also and nothing is reported in it about someone stopping the Test, etc.

Any help on how this can be tackled? As abrupt stoppage of Availability Test (Tests getting grayed out) is really serious as we wont know if there is any outage untill someone reports back on the service.

Thank you,

**Comment by cijothomas** [comment]
AvailabilityTest is not a feature shipped from this repo. Please get support from [Azure Support Center](https://azure.microsoft.com/support/create-ticket/)
