### ISSUE TITLE
Application Insights API 2.1.0-beta1 install failing from Nuget Package

### ISSUE THREAD

**Issue by drobertson123** [Microsoft/ApplicationInsights-dotnet#213]
I just upgraded to the latest pre-release of Application Insights using Nuget in VS 2015 Update 2 RC. Everything looks successful from the install, but the packages have all been wiped from my projects. At this point all my projects are "Unable to locate Dependency Microsoft.ApplicationInsights >= 2.1.0-beta1"

These are ASP.NET core project targeting DNX 4.5.1

Below are some snippets from the Nuget install:

Installing NuGet package Microsoft.ApplicationInsights.2.1.0-beta1.
Successfully installed 'Microsoft.ApplicationInsights 2.1.0-beta1' to XXXXXXX
========== Finished ==========
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\XXXXXXX\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe "C:\Users\XXXXXXX\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "C:\Users\XXXXXXX\Source\Repos\XXXXXXX\tests\XXXXXXX" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231
  CACHE https://www.nuget.org/api/v2/
Restoring packages for C:\Users\XXXXXXX\Source\Repos\XXXXXXX\tests\XXXXXXX\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.ApplicationInsights'
Unable to locate Dependency Microsoft.ApplicationInsights >= 2.1.0-beta1
Writing lock file C:\Users\XXXXXXX\Source\Repos\XXXXXXX\tests\XXXXXXX\project.lock.json
Restore complete, 676ms elapsed
Errors in C:\Users\XXXXXXX\Source\Repos\XXXXXXX\tests\XXXXXXX\project.json
    Unable to locate Dependency Microsoft.ApplicationInsights >= 2.1.0-beta1
NuGet Config files used:
    C:\Users\XXXXXXX\AppData\Roaming\NuGet\nuget.config
Feeds used:
    https://www.nuget.org/api/v2/
    C:\Program Files (x86)\Microsoft Web Tools\DNU

**Comment by abaranch** [comment]
Could you please try again? We were just uploading these nuget packages. I guess you were lucky enough to start updating when not all nugets were indexed yet.

**Comment by drobertson123** [comment]
I guess I had the dubious pleasure of being the first download. It did look funny that the download count was 0.

I went ahead and upgraded back to "Microsoft.ApplicationInsights": "2.1.0-beta1"

It looks like everything worked great this time. Problem solved.

Tip for the Nuget team. New packages should not be published until all the files are loaded properly.

thanks for the help.

**Comment by abaranch** [comment]
I'm sorry you had this issue. We try to publish all nugets together but today symbol server was returning 500 so it took longer than usual.

**Comment by drobertson123** [comment]
No big deal. Probably the easiest project related problem I dealt with today.

BTW, the comment about Nuget was directed more at the fact that they should have a stage/publish system that would prevent these issues and not at your group in any way.
