### ISSUE TITLE
Is there a possibility to log a StackOverflowException?

### ISSUE THREAD

**Issue by MartinDemberger** [microsoft/ApplicationInsights-dotnet#2136]
I have a Service Fabric Application running. Yesterday I had performance impacts and found a console output which informs about a StackOverflowException but I couldn't find any stack trace or something more. AppInsights and ServiceFabric were both green.

So I took one memory dump after another and looked into the last one before the process goes down. Then it was no problem finding the problem.

Is there a possibility to configure AppInsights to log a StackOverflowExceptoin and create a dump in this case?

**Comment by cijothomas** [comment]
Apart from offering TrackException API to log any exception, there is no feature provided by this SDK to auto-trigger process dump.
