### ISSUE TITLE
Default dependency types modify Name/Target server-side

### ISSUE THREAD

**Issue by theEyeD** [microsoft/ApplicationInsights-dotnet#2138]
When sending SQL Dependency Telemetry to App Insights, the values for Name and Target are overwritten based on what appears in the Logs search results.  If Name and Target are modified in a TelemetryProcessor the new values are ignored/overwritten, which is not the expected behavior. If Name, Target **and** Type are all modified, the modified values appear as expected.

**Comment by theEyeD** [comment]
As a workaround, I have updated the Type to be "(" + Type + ")".

**Comment by cijothomas** [comment]
Could you explain the issue with an issue/screenshots? Its not clear where/who is overwriting. Is it SDK? or by Azure backend? Some examples would really help us understand more.
