### ISSUE TITLE
Not able to send log4net logs to application insights

### ISSUE THREAD

**Issue by aryanPatilhm2** [microsoft/ApplicationInsights-dotnet#2139]
**What I am trying to achieve**
Hello, I have dotnetcore service which is running in Kubernetes. For logging I have used the log4net. I am trying to send the logs of service to application-insights but the logs are not showing there.

**What I have tried so far**
Below configuration I have added in my service for application insights.
* Runtime version: netcoreapp3.1 version-2.31.0.1

* Hosting environment: Azure-cluster

**app-service.csproj**
```
<ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.16.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.Log4NetAppender" Version="2.16.0" />
    ...
<ItemGroup>
```
**log4net.config**
```
   ...
<appender name="aiAppender" type="Microsoft.ApplicationInsights.Log4NetAppender.ApplicationInsightsAppender, Microsoft.ApplicationInsights.Log4NetAppender">
  <InstrumentationKey name="AppInsightsKey" value="abcdefgh-abcd-abcd-abcd-abcdefghijkl" />
  <layout type="log4net.Layout.PatternLayout">
    <conversionPattern value="%message%newline"/>
  </layout>
</appender>
```
**startup.cs**
```
 public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
            Logger.ConfigureLog4Net("./logs/app.log", Configuration)
            ...
        }
 public void ConfigureServices(IServiceCollection services)
        {
            // The following line enables Application Insights telemetry collection.
            services.AddApplicationInsightsTelemetry();
            services.AddSingleton<ITelemetryInitializer, CloudRoleNameTelemetryInitializer>();
            // This code adds other services for the application.
            services.AddMvc();
            ...
        }
```
**CloudRoleNameTelemetryInitializer.cs**
```
using System.Net;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.Channel;
using Microsoft.ApplicationInsights.Extensibility;
public class CloudRoleNameTelemetryInitializer : ITelemetryInitializer
{
   public void Initialize(ITelemetry telemetry)
    {
      // set custom role name here
      telemetry.Context.Cloud.RoleName = "app-service";
    }
}
```
I have also added the `APPINSIGHTS_INSTRUMENTATIONKEY` environment variable for service. I am able to see the requst information for service but not logs. Only 2 logs are showing in log section of application-insights but it is not from application(log4net).
`No XML encryptor configured. Key {XXX-XXX-XXX-XXX-XXX} may be persisted to storage in unencrypted form.`
`Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.`
Below are some links I have explored
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-trace-logs
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/1053
https://medium.com/@muralimohan.mothupally/application-insights-integration-with-log4net-e1bef68fe3c8
https://blog.ehn.nu/2014/11/using-log4net-for-application-insights/
https://jan-v.nl/post/using-application-insights-in-your-log4net-application/

But still logs are not addiing in the application insights. Is there anything I am missing here? Also is it possible to add Console.WriteLine logs to application-insights as like in nodejs app we can send it by enabling the application-insights modules configuration?

Thanks...

**Comment by cijothomas** [comment]
@aryanPatilhm2 I don't think we have proper support for this log4net in Asp.Net core, as log4net relies on TC.Active, which is an obsolete concetp for Asp.Net Core.

Could you try the following?
var aiOptions = new ApplicationInsightsServiceOptions();
aiOptions.EnableActiveTelemetryConfigurationSetup = true;
aiOptions.InstrumentationKey = ikey;
services.AddApplicationInsightsTelemetry(aioptions);

**Comment by hrkyemba** [comment]
@cijothomas , do you have plans to improve support for log4net in Asp.Net Core? Until you do, can we rely on your workaround or is it likely to stop working soon?

**Comment by cijothomas** [comment]
Almost all investments are around Ilogger based API only. No work is planned for better log4net support.
The workaround will work in 2.* versions. 
In 3.* version, we'll remove obsolete methods (including .Active). There are not ETA on when will 3.* start shipping, but its not likely this year.
