### ISSUE TITLE
[Bug] Memory usage when upload file to DataLake gen2

### ISSUE THREAD

**Issue by Marusyk** [microsoft/ApplicationInsights-dotnet#2140]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights.AspNetCore 2.14.0
Microsoft.ApplicationInsights.WorkerService 2.14.0
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): netcoreapp3.1
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Linux Docker

I'm using Azure.Storage.Files.DataLake to send data every minute from my C# code with enabled Application Insights

```
services.AddApplicationInsightsTelemetryWorkerService();
```

There are a lot of operations with Datalake (now it's more than 5000 per hour). 
I got a lot of memory usage of my application (each file ~150 bytes).

App without Application Insights enabled, after 3 days uptime: ~96Mb
App with  Application Insights disabled, after 6 hours uptime: ~900Mb

Could you please suggest how to avoid AI memory leak?

I've tried but no success
```
public class DependencyTelemetryFilter : ITelemetryProcessor
    {
        private ITelemetryProcessor Next { get; set; }

        public DependencyTelemetryFilter(ITelemetryProcessor next)
        {
            Next = next;
        }

        public void Process(ITelemetry item)
        {
            if (item is DependencyTelemetry elem && elem.Contains("dfs.core.windows.net"))
            {
                return;
            }

            Next.Process(item);
        }
    }
```

**Comment by cijothomas** [comment]
@Marusyk Could you share the code snippet used to make datalake calls? This issue can occur if the azure-data-lake sdk is used incorrectly as well, so it'd be great if you can share a small repro or code snippet doing datalake calls.

**Comment by Marusyk** [comment]
I'm using Azure.Storage.Files.DataLake to send data every minute from my C# code.
```
public class DataLakeStorage : IFileStorage
{
	private readonly DataLakeServiceClient _dataLakeClient;

	public DataLakeStorage(FileStorageOptions options)
	{
		var sharedKeyCredentials = new StorageSharedKeyCredential(options.AccountName, options.AccountKey);
		_dataLakeClient = new DataLakeServiceClient(new Uri($"https://{options.AccountName}.dfs.core.windows.net"), sharedKeyCredentials);
	}

	public async Task Add(string containerName, string path, string name, object data)
	{
		DataLakeFileSystemClient fileSystemClient = _dataLakeClient.GetFileSystemClient(containerName.ToLower());
		await fileSystemClient.CreateIfNotExistsAsync();

		DataLakeDirectoryClient directoryClient = fileSystemClient.GetDirectoryClient(path);
		DataLakeFileClient fileClient = await directoryClient.CreateFileAsync(name);

		await using var stream = new MemoryStream();
                await JsonSerializer.SerializeAsync(stream, data, data.GetType());
                stream.Position = 0;
                await fileClient.AppendAsync(stream, 0);
                await fileClient.FlushAsync(stream.Length);
	}
}
```

The `DataLakeStorage` is registered as a Singleton in web application.
Also, tried `await fileClient.UploadAsync(stream, overwrite: true);` instaed of
```
await fileClient.AppendAsync(stream, 0);
await fileClient.FlushAsync(stream.Length);
```
and added
```
 <PropertyGroup>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>
```
but the same result. It uses a lot of memory.

**Comment by cijothomas** [comment]
@Marusyk The code does not appear to be concerning. I wanted to first see if this is related to https://github.com/microsoft/ApplicationInsights-dotnet/issues/1867.
As this is not related, could you share a repro project for us to do deeper investigation?

**Comment by Marusyk** [comment]
@cijothomas 
Actually, you need only this code with 
`services.AddApplicationInsightsTelemetryWorkerService();` to reprocude it.

call every few seconds:

`await _instance.Add("containerName", DateTime.Now.ToString(), "name", new { Name = "name", Time = DateTime.Now });`

**Comment by Marusyk** [comment]
any updates?

**Comment by wesselkranenborg** [comment]
We are also facing this issue. We now implemented a regular restart of our service but that is far from ideal.

**Comment by Marusyk** [comment]
Hi @cijothomas, can anyone help with it?

**Comment by Marusyk** [comment]
The issue is not fixed
