### ISSUE TITLE
Improving: Log custom properties of custom exceptions

### ISSUE THREAD

**Issue by oshastitko** [microsoft/ApplicationInsights-dotnet#2141]
If we have custom exception with custom properties like this:

```
public class InvalidStatusCodeException : Exception

{

    public HttpStatusCode ReceivedStatusCode { get; set; }

    public string ApiUrl { get; set; }


    public InvalidStatusCodeException(HttpStatusCode receivedStatusCode, string apiUrl) 

    {

        ReceivedStatusCode = receivedStatusCode;

        ApiUrl = apiUrl;

    }

}

```

these custom properties are not logged to Application Insights if this exception is fired.

One of the ways to log it in app Insight: add custom message, like this:

`
- [ ] public InvalidStatusCodeException(HttpStatusCode receivedStatusCode, string apiUrl) : base($"Invalid Status code for request: '{apiUrl}', received code: {receivedStatusCode}")

`

but I don't want to prepare message on exception level (no way to sorting/filtering, can be localization etc).

It would be great to log custom properties for custom exceptions

**Comment by pharring** [comment]
You can do this (yourself) with an `ITelemetryInitializer` and a bit of reflection.
