### ISSUE TITLE
Get traceparent for telemetry operation

### ISSUE THREAD

**Issue by MagdaPaj** [microsoft/ApplicationInsights-dotnet#2146]
Environment:
* ApplicationInsights SDK 2.16.0
* ASP.NET Core

**What are you trying to achieve?**
I'm starting a `DependencyTelemetry` operation:
```
var operation = _telemetryClient.StartOperation<DependencyTelemetry>("my dependency");
```
And I need to get a `traceparent` for it.

From [this issue](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1831#issuecomment-621467615) I see that I can use `Activity.Current.Id`. But I would like to know if that's still a good practice.  

 The other option could be composing [traceparent ](https://www.w3.org/TR/trace-context/#traceparent-header):
* by using `operation.Telemetry.Id` as `parent-id` 
* and `operation.Telemetry.Context.Operation.Id` as `trace-id` 
* and I would need to figure out from where to get `version` (it seems to be 00) and `trace-flags` (also seems to be 00 in my case). 

Composing is a bit more work, but it's more clear what is this `traceparent` value. It seems a bit weird that I have the `operation` but I use `Activity.Current` to get `traceparent`. 

What is the best approach to get `traceparent`? Is it a bad idea to compose it as I explained above?

**Comment by cijothomas** [comment]
What is the use case of obtaining the traceparent? 

Yes, activity.current.id is the correct way of obtaining it. You cannot compose traceflags, as its depending on sampling decision. (currently applicationinsights doesn't change the traceflags, it simply passes it as is to the next hop).

**Comment by MagdaPaj** [comment]
Thank you @cijothomas, I'll keep using `Activity.Current.Id` as `traceparent`.

We want to propagate a context to Kafka as Kafka header. So potentially future services will consume it and we'll be able to track requests across all services and have proper distributed tracing. And we want to be compliant with [W3C protocol](https://www.w3.org/TR/trace-context-protocols-registry/#registry).

**Comment by cijothomas** [comment]
You can take a look at how HttpClient is doing the propagation here:
https://github.com/dotnet/runtime/blob/35e935441c4c88611b6635cbf4a0f482cbad863c/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L287

(Its just injecting activity.current.id)
