### ISSUE TITLE
Support end to end tracing with new Service Bus library

### ISSUE THREAD

**Issue by JoshLove-msft** [microsoft/ApplicationInsights-dotnet#2151]
**Is your feature request related to a problem?**
We have released a new Service Bus library - https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.0.1
End to end tracing doesn't currently work for the new library - see https://github.com/Azure/azure-sdk-for-net/issues/18002

**Describe the solution you'd like.**
App insights has [special handling](https://github.com/microsoft/ApplicationInsights-dotnet/blob/81288f26921df1e8e713d31e7e9c2187ac9e6590/WEB/Src/DependencyCollector/DependencyCollector/Implementation/EventHandlers/ServiceBusDiagnosticsEventHandler.cs) to look for the span names from the old library. It seems this would need to be expanded to include the new library span names, which can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Diagnostics/DiagnosticProperty.cs#L46-L156).

**Additional context.**
A similar change was made for the new Event Hubs library - https://github.com/microsoft/ApplicationInsights-dotnet/pull/1674

**Comment by JoshLove-msft** [comment]
Hi, just wanted to see if there is any timeline on when this would be available. We have users asking for this functionality in Service Bus.

**Comment by psiservices-dbrink** [comment]
What's it take to get a response on this from the app insights team?

**Comment by psiservices-dbrink** [comment]
@TimothyMothra - any way to get an acknowledgement from your team on this?

**Comment by lmolkova** [comment]
fixed in #2593
