### ISSUE TITLE
How to mark source to show on Application Map.

### ISSUE THREAD

**Issue by Olli64** [microsoft/ApplicationInsights-dotnet#2152]
Greetings!

We have currently multiple sources that send requests to our systems.

We would like to see those systems(applications) show up on application insights "Application Map".

Is this anyhow possible without the sender having application insights?

For example, 

If I have a system that sends us new orders

Can I somehow show that on Application Map without having to pass our application insights instrumentatioKey etc for them?

I can modify request and headers as they come through front door and api management as I wish.

I know from IP source and from auth token the source so I can map it to correct client if possible.

Is there some header value or other that I could modify to make Application Insights parse that request to show on Map?

Is it only possible that the request should go to https://dc.services.visualstudio.com/v2/track so it will be shown there?

We have application insights on api management and our whole backend (running in AKS).

See picture below with "Client1" and "Client2" modified to picture.

![image](https://user-images.githubusercontent.com/34423910/105146407-a28dcc80-5b08-11eb-967d-5598729cdf82.png)

**Comment by cijothomas** [comment]
> Is this anyhow possible without the sender having application insights?

Don't think so. Only those components which sent their telemetry to ApplicationInsights, and you have access to their telemetry will be visible here.
