### ISSUE TITLE
End-To-End transaction: from API Management to Azure Functions to ServiceBus not working

### ISSUE THREAD

**Issue by erwinkramer** [microsoft/ApplicationInsights-dotnet#2153]
I'm using the Function v3.0.15193.0 runtime hosted on Windows in an elastic plan inside a vnet. 

Libraries inside my solution (i'm running from a package file):
```
  <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
```

I'm not specifying any Application Insights reference, since I rely on the build-in support in the Azure Function magic. 

In API Management, I specified the _W3C_ correlation protocol instead of the _Legacy_ option. 

### Describe the bug

I'm trying to get the End-to-end transaction flow working. Currently, I see my API Management resource and Azure Function resource in the same flow, so far so good. 

After the Azure function (http trigger), it should show the Service Bus queue request (not working) and the function behind that service bus queue (it shows the function _information_ logging and _request_ calls in app insights, but there is no relation with the previous function, nor with the servicebus from the trigger). 

In the first function I'm passing in the message to the queue by making the servicebus message myself, with the following decoration on top of the function:
`[ServiceBus("queue-x", Connection = "y")] out Message sbMessage`

With a message object like this:
`sbMessage = new Message(Encoding.UTF8.GetBytes(a.b.ToString()))
                {
                    CorrelationId = correlationId
                };`

Similar issues are described here: https://stackoverflow.com/questions/58939510/end-to-end-correlation-for-api-management-functions-and-servicebus and here https://stackoverflow.com/questions/65131102/azure-app-insights-issue-with-end-to-end-tracing

Both describe different solutions, which both feel like workarounds. Or am I missing something?

**Comment by cijothomas** [comment]
If you're running the application in Azure Functions, please file an issue [here](https://github.com/Azure/azure-functions-host/issues/new/choose).

**Comment by erwinkramer** [comment]
Thanks, opened here: https://github.com/Azure/azure-functions-host/issues/7081
