### ISSUE TITLE
How-To "send custom telemetry to Azure Monitor" ?

### ISSUE THREAD

**Issue by suprak** [microsoft/ApplicationInsights-dotnet#2154]
Reading the documentation for [custom metrics in Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview).
The first bullet mentions,
> Instrument your application by using the Azure Application Insights SDK and send custom telemetry to Azure Monitor.

But I have not been able to find any code examples or further documentation.
So how exactly can we use the AI SDK to send custom telemetry events to Azure Monitor?

For context we are running some VMSS instances and want to leverage Azure Monitor for exposing some additional metrics.

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/get-metric

**Comment by suprak** [comment]
Thanks for that link but these metrics would be published for Application Insights Metric Monitor, not the VMSS one?

Can we use the `GetMetric` to publish custom metrics for the VM/VMSS instances?
If so, what `InstrumentationKey` would we use?

**Comment by cijothomas** [comment]
Right. There is no ability in this SDK to send data to VMSS resource itself, as that would require separate authentication, and is not ikey based.

Based on my knowledge, there is no SDK which wraps this API : https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-store-custom-rest-api

**Comment by suprak** [comment]
For others who stumble on this,

- [Custom Metric REST API for Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-store-custom-rest-api)
- [Acquire Managed Identity token](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#overview)

Get identity token and use it to publish your own metrics.

**Comment by cijothomas** [comment]
If you want to, please open an issue here to provide an SDK for this purpose:
https://github.com/Azure/azure-sdk-for-net
