### ISSUE TITLE
Provide a timeout option for Flush()

### ISSUE THREAD

**Issue by DanSeefeldt** [Microsoft/ApplicationInsights-dotnet#216]
## Provide a timeout option for Flush()

We'd like the ability to specify a timeout for `Flush()` which would cancel the operation and return if the timeout was exceeded.  Our scenario is a short running .NET Core application with telemetry being uploaded at the end of the app by calling `Flush()` before exiting.  In some cases, network latency is causing the app to hang before exiting.  We'd rather lose the telemetry data than delay the app.

### Issue Details:

When running our app, we're seeing reasonable return times for the `Flush()` command in almost all cases, with the network connected and without.  The failing case for us is when we're running our app in a Docker container and the host's network is disconnected.  In this case, the app acts as if it's connected but cannot reach the network resource, resulting in a 40 second delay while the network call times out.

**Comment by AlexBulankou** [comment]
Thanks Dan! We'll collect feedback on how typical your case is to see if we need to make it part of the API. As a workaround would doing something like this help:
```
            Thread thread = new Thread(() =>
            {
              telemetryClient.Flush();
            });
            thread.Start();
            if (!thread.Join(1000*5)) // wait 5 seconds
            {
                thread.Abort();
            }
```

**Comment by daniel-kun** [comment]
I'd give a +1 here. It's not a must-have-feature, but it is something that a) I expect any API to IO operations to provide and b) I have wished in the past, but then it was not important enough to put effort into (especially testing).

**Comment by LakshanF** [comment]
+1 for the feature since the .NET Core telemetry scenario is on a critical CLI tool where time lags are noticeable.
