### ISSUE TITLE
Events/Traces are not send from .NET Framework project to Application Insights located in Germany West Central Location

### ISSUE THREAD

**Issue by Uriil** [microsoft/ApplicationInsights-dotnet#2160]
* List of [NuGet packages] and version that you are using: Microsoft.ApplicationInsights 2.12.0, but also can reproduce with latest codebase from this repo 
* Runtime version: net461, net48:
* Hosting environment: Azure Web App, Windows

### Describe the bug

The bug is very strange, but I can reproduce it easily. I cannot send events/traces from .NET Framework(tested in 4.7.2, 4.8) project to Application Insights located in Germany West Central location.

If I changed AI location to West Europe - it works
If I change target framework to .NET Core (tested in 3.1) - it works

I was able to debug Microsoft.ApplicationInsights project up to Transmission.SendAsync(), and found that in problem on next line:

    using (var response = await client.SendAsync(request, ct.Token).ConfigureAwait(false))

response.Content has next value:

{"itemsReceived":6,"itemsAccepted":0,"errors":[{"index":0,"statusCode":308,"message":"Ingestion is allowed only from stamp specific endpoint - Location: https://germanywestcentral-0.in.applicationinsights.azure.com/v2/track"},{"index":1,"statusCode":308,"message":"Ingestion is allowed only from stamp specific endpoint - Location: https://germanywestcentral-0.in.applicationinsights.azure.com/v2/track"},{"index":2,"statusCode":308,"message":"Ingestion is allowed only from stamp specific endpoint - Location: https://germanywestcentral-0.in.applicationinsights.azure.com/v2/track"},{"index":3,"statusCode":308,"message":"Ingestion is allowed only from stamp specific endpoint - Location: https://germanywestcentral-0.in.applicationinsights.azure.com/v2/track"},{"index":4,"statusCode":308,"message":"Ingestion is allowed only from stamp specific endpoint - Location: https://germanywestcentral-0.in.applicationinsights.azure.com/v2/track"},{"index":5,"statusCode":308,"message":"Ingestion is allowed only from stamp specific endpoint - Location: https://germanywestcentral-0.in.applicationinsights.azure.com/v2/track"}]}

Looks like request is getting redirected, but code does not handle it

### To Reproduce

    class Program
    {
        static void Main(string[] args)
        {
            var tc = new TelemetryClient(new TelemetryConfiguration(""));

            while (true)
            {
                tc.TrackTrace($"New message12: {Guid.NewGuid()}");
                Thread.Sleep(5000);
            }
        }
    }

**Comment by TimothyMothra** [comment]
Hello @Uriil please open a Support Ticket for this issue.

**Comment by Uriil** [comment]
@TimothyMothra  You mean "New support request" on Azure Portal in Application Insights resource?

**Comment by TimothyMothra** [comment]
@Uriil yes. Here's the link [Azure Support Center](https://azure.microsoft.com/support/create-ticket/).

**Comment by CodedBeard** [comment]
@Uriil did you get any response from support? I've been trying to fix what appears to be the same issue for the past 3 days, but we use North Europe region.

**Comment by Uriil** [comment]
They asked me some additional questions and told that they will come back to my ticket on 29th of January

**Comment by Uriil** [comment]
@CodedBeard they suggested me to use connection string instead of instrumentation key, which is worked for me

(TelementryClient has separate property ConnectionString and it contains endpoint)

**Comment by pharring** [comment]
Yes, I learned recently that all the "new" regions *require* ConnectionString for ingestion.
