### ISSUE TITLE
It is not possible to overwrite ApplicationInsights:InstrumentationKey specified in appsettings.json

### ISSUE THREAD

**Issue by vladimir-zhuk-epam** [microsoft/ApplicationInsights-dotnet#2162]
https://github.com/microsoft/ApplicationInsights-dotnet/blob/5c999c8cfcea81ebe9c7f589456e368a68f4b040/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/DefaultApplicationInsightsServiceConfigureOptions.cs#L42

**Comment by cijothomas** [comment]
Could you share a snippet demonstrating the issue? Want to make sure we understand the issue correctly.

**Comment by vladimir-zhuk-epam** [comment]
Please use the following sequence to reproduce the issue:
dotnet new web -n App1
cd .\App1\
dotnet add package Microsoft.ApplicationInsights.AspNetCore
code appsettings.json
{
  "ApplicationInsights:InstrumentationKey" : "00000000-0000-0000-0000-000000000000"
}
code Startup.cs
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplicationInsightsTelemetry();
            var provider = services.BuildServiceProvider();
            var configuration = provider.GetService<Microsoft.Extensions.Configuration.IConfiguration>();
            Console.WriteLine(configuration["ApplicationInsights:InstrumentationKey"]);
            var options = provider.GetService<Microsoft.Extensions.Options.IOptions<Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions>>().Value;
            Console.WriteLine(options.InstrumentationKey);
        }
dotnet user-secrets init
dotnet user-secrets set ApplicationInsights:InstrumentationKey 11111111-1111-1111-1111-111111111111
dotnet run
Building...
C:\AppInsights\App1\Startup.cs(20,28): warning ASP0000: Calling 'BuildServiceProvider' from application code results in an additional copy of singleton services being created. Consider alternatives such as dependency injecting services as parameters to 'Configure'. [C:\AppInsights\App1\App1.csproj]
11111111-1111-1111-1111-111111111111
00000000-0000-0000-0000-000000000000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\AppInsights\App1
