### ISSUE TITLE
How to get the unsent telemetry items when handling the TransmissionStatusEvent?

### ISSUE THREAD

**Issue by ivshch** [microsoft/ApplicationInsights-dotnet#2163]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Microsoft.ApplicationInsights (2.15.0)
* Runtime version: netstandard2.0
* Hosting environment: Azure Web App, also checked on Windows 10, Windows Server 2016.

**What are you trying to achieve?**

Our current task requires to write the human-readable file logs only at the moments when the AppInsights endpoint is unreachable.

This is quite close to what ServerTelemetryChannel does, but without gzipping and with using the rolling mechanism. Our goal is to make a solution that would allow the support to investigate the connectivity problems after (for example) a week of AppInsights silence. Although the total amount of the logs collected may appear very long, the most valuable information may be found in the first few log lines - and this is our problem right now.
How to get the first lines that were not delivered?

**What have you tried so far?**
We are planning to implement ITelemetryChannel that is writing a rolling log file but only turned on if the ServerTelemetryChannel experiencing connection problems. We also plan to implement a TelemetryModule to set up logging.

We have attached a handler to a ServerTelemetryChannel
```csharp
telemetryChannel.TransmissionStatusEvent += delegate(object sender, TransmissionStatusEventArgs args)
{
    if (args.Response.StatusCode == 999)
    {
         // The endpoint was not reached.
    }
};
```
and found that due to the asynchronous nature of TelemetryChannel we have a bunch of messages that were not delivered by a channel at the moment when we receive the TransmissionStatusEvent.

The question is - is there a way to know exactly what telemetry items were not delivered?
We are currently thinking of a circular buffer to hold every item, but it does not give us reliable information of what was or was not sent by a ServerTelemetryChannel.

**Comment by rajkumar-rangaraj** [comment]
@ivshch Please check the samples in PR https://github.com/microsoft/ApplicationInsights-dotnet/pull/1887. Object `sender` is a `Transmission` and you could access telemetry items in `Transmission`.
