### ISSUE TITLE
Unable to access the RequestTelemetry from middleware classes

### ISSUE THREAD

**Issue by mkariyap** [microsoft/ApplicationInsights-dotnet#2164]
Below code is in **InvokeMethod(HttpContext context)** function. I was trying to access requestTelemtry in the Exception middleware. I ran in debug mode and checked this.

catch (UnauthorizedAccessException exception)
            {
                RequestTelemetry requestTelemetry = context?.Features?.Get<RequestTelemetry>();
            }
If I try to access the requestTelemetry it is null.

@johnkwaters
@cijothomas

Can you please help me in this.

**Comment by mkariyap** [comment]
@johnkwaters
@cijothomas

**Comment by mkariyap** [comment]
@johnkwaters
@cijothomas any updates on this?

**Comment by cijothomas** [comment]
Please share a minimal repro to investigate this.

**Comment by mkariyap** [comment]
In our app we are planning to access the RequestTelemetry and log the information when it throws an UnauthorizedAccessException 401.

This is a new addition thing that we are trying to do. When we try create and access the requestTelemetry object inside the catch block we were getting it as null.
