### ISSUE TITLE
How to use a fixed version of the JS SDK with the snippet?

### ISSUE THREAD

**Issue by Piedone** [microsoft/ApplicationInsights-dotnet#2165]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Microsoft.ApplicationInsights.AspNetCore (2.16.0)
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): netcoreapp3.1
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Azure App Service, Windows.

**What are you trying to achieve?**

I'd like all AI SDK changes in my app to happen explicitly. This is given with the versioning of the NuGet package, it doesn't auto-update in production, I update it explicitly and then test it when needed. However, the JS SDK used by `JavaScriptSnippet` seems to always be the latest one. This has bitten me when something changed there, breaking the code I extended it with, without me changing anything. Thus, I'd like to somehow say that "now I'm using the JS SDK version 1.2.3". Is this possible?

My code in question is BTW one that sets the operation ID for page view-request correlation because that somehow didn't work for me automatically (Razor):

```html
<script>
    appInsights.queue.push(function () {{
        // Up until a couple days ago this used appInsights.-->properties<--.context.telemetryTrace.traceID.
        appInsights.context.telemetryTrace.traceID = '@System.Diagnostics.Activity.Current.RootId';
    }});
</script>
```

**What have you tried so far?**
I thought about using a hand-crafted version of the snippet but I don't see how such a version could be specified. All snippets just use the auto-updating https://js.monitor.azure.com/scripts/b/ai.2.min.js script.

**Comment by TimothyMothra** [comment]
I'm sorry you didn't get a response on this issue sooner.
My team can't answer this because we don't own the snippet. 
I think this question would be better asked on https://github.com/Microsoft/ApplicationInsights-js

**Comment by Piedone** [comment]
I'm using `JavaScriptSnippet` so wouldn't this affect this project too?

**Comment by TimothyMothra** [comment]
The JavaScript team owns and maintains the snippet. It's their API.

**Comment by Piedone** [comment]
Alright, opened https://github.com/microsoft/ApplicationInsights-JS/issues/1738.
