### ISSUE TITLE
Should we update the default endpoints for profiler and snapshot?

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-dotnet#2166]
https://github.com/microsoft/ApplicationInsights-dotnet/blob/81288f26921df1e8e713d31e7e9c2187ac9e6590/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Endpoints/Constants.cs#L14-L18

Default endpoint for Profiler: https://profiler.monitor.azure.com
Defualt endpoint for Snapshot Debugger: https://snapshot.monitor.azure.com 

```csharp
        /// <summary>Default endpoint for Profiler.</summary>
        internal const string DefaultProfilerEndpoint = "https://agent.azureserviceprofiler.net/"; // <----- New default: https://profiler.monitor.azure.com

        /// <summary>Default endpoint for Snapshot Debugger.</summary>
        internal const string DefaultSnapshotEndpoint = "https://agent.azureserviceprofiler.net/"; // <--- New default: snapshot.monitor.azure.com
```

**Comment by xiaomi7732** [comment]
tag @pharring

**Comment by xiaomi7732** [comment]
Also tag @cweining.

**Comment by TimothyMothra** [comment]
Feel free to submit a PR for this
