### ISSUE TITLE
Application Insights creating slow requests.

### ISSUE THREAD

**Issue by vanwinkelseppe** [microsoft/ApplicationInsights-dotnet#2167]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights.AspNetCore Version: 2.14.0
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
netcoreapp3.1
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
Azure Web App, App Service on Windows, West-Europe, S1
* ApplicationInsightsServiceOptions
We have EnableAdaptiveSampling disabled for tracking purposes.

**What are you trying to achieve?**
Investigating why Application Insights is causing these delays in our webrequests. Making them slow.

**What have you tried so far?**
We have been investigating a lot of routes tracking the responsiveness of our api calls. From the dependencies to all external possibilities of network. After some profilings with 'EventSourceLogger' in the diagnostics panel of the App Service we see a general trend in our slow api calls.

Here is an example. A lot of our requests seem to be blocked for a duration of 2000-5000. Is there any explanation to why this happens? Or what we can do to improve this duration?
![image](https://user-images.githubusercontent.com/9077926/107036398-e1cf4500-67b9-11eb-80b4-e940da350f70.png)

**Comment by pharring** [comment]
From the screenshot something is calling TelemetryClient.Flush. I can't tell what component it is -- looks like some module names have been obscured/redacted. `Flush` is expensive -- so, if it's called on _every_ request, it's going to be a major bottleneck -- as you've discovered.
Can you reveal what component is calling Flush? Can you configure it not to do that?

In the past, I've seen this problem with a System.Diagnostics.TraceListener enabled with "autoflush=true". Do you happen to have that?

**Comment by pharring** [comment]
Actually, I see it lower down: Niko.Cloud.Events.Services.EventService.TrackSupportEvent (from the niko.cloud.events assembly)
Is this one of your own namespaces? Can you share the code?

In short, this *isn't* an App Insights bug. Flush is expensive. Don't use it in production except in shutdown scenarios where you absolutely have to guarantee that telemetry is delivered before process exit.

**Comment by pharring** [comment]
One other thing: That TelemetryClient is using the InMemoryChannel. You should consider using the ServerTelemetryChannel for production services.

**Comment by vanwinkelseppe** [comment]
Thanks @pharring! We were not aware that the Flush is that expensive!
