### ISSUE TITLE
"Working Set - Private" PerformanceCounter is reporting "# Gen 0 Collections" values

### ISSUE THREAD

**Issue by jordansjones** [microsoft/ApplicationInsights-dotnet#2175]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Microsoft.ApplicationInsights.PerfCounterCollector v2.10.0
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): net472
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Azure Windows App Service

**What are you trying to achieve?**
The ability to measure and report he Private Working Set on a per process basis.

**What have you tried so far?**
Adding `<Add PerformanceCounter="\Process(??APP_WIN32_PROC??)\Working Set - Private" />` to my ApplicationInsights.config and reporting this issue.

In looking at the code in the `master` branch, I have noticed that the switch statement in `CounterFactory.GetCounter` for `"\Process(??APP_WIN32_PROC??)\Working Set - Private"` falls through to `"\.NET CLR Memory(??APP_CLR_PROC??)\# Gen 0 Collections"`:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/c9d95e701e2474b7eb3b46ae7953b6c7570356ab/WEB/Src/PerformanceCollector/PerformanceCollector/Implementation/WebAppPerformanceCollector/CounterFactory.cs#L525-L529

Is there a reason for this? If so, could a code comment be added explaining the reason why?

**Comment by cijothomas** [comment]
Likely a bug. Have to check history to see this was a bug from day 1 or a bug introduced later.
(Btw, this is in web apps only where there is no direct access to perf counters, so some special env variables are used to read it indirectly).

**Comment by jordansjones** [comment]
@cijothomas Does that mean that Performance counters for memory or CPU usage are per app service instead of per process?

**Comment by cijothomas** [comment]
> @cijothomas Does that mean that Performance counters for memory or CPU usage are per app service instead of per process?

No. Any reason why you asked?

**Comment by jordansjones** [comment]
> > @cijothomas Does that mean that Performance counters for memory or CPU usage are per app service instead of per process?
> 
> No. Any reason why you asked?

Just wanted to make sure that webjob process on the same app service report correct values. Thank you.

**Comment by cijothomas** [comment]
Got it.
The special env variable mechanism in WebApps returns the value for the process which is querying it. So the process/cpu value will be that of the process asking for it.

**Comment by jordansjones** [comment]
I apologize in advance for resurrecting this issue, but I am still seeing that `"\Process(??APP_WIN32_PROC??)\Working Set - Private"` falls through to the next case and I am wondering if this was determined to be the desired behavior?
