### ISSUE TITLE
Live metrics not showing data while application insights logs

### ISSUE THREAD

**Issue by anjoiype** [microsoft/ApplicationInsights-dotnet#2176]
After upgrading `Microsoft.ApplicationInsights` from 2.3 to 2.7.1, the live metrics shows as no app is connected, but while searching logs and performance monitor we are able to see data. Further analysis found that live metrics will work only if correct Instrumentation key is given in `ApplicationInsights.config` file. Currently Instrumentation key is set programmatically as given below.
```
public class FooInitializer : ITelemetryInitializer
{
    public void Initialize(ITelemetry telemetry)
    {
        if (telemetry == null)
        {
            throw new ArgumentNullException(nameof(telemetry));
        }            
        telemetry.Context.InstrumentationKey = WebConfigurationManager.AppSettings[<InstrumentationKey>];
    }
}
```
In `Global.asax.cs`
```
protected void Application_Start()
{    
    TelemetryConfiguration.Active.TelemetryInitializers.Add(new FooInitializer ());
}
```
No telemetry initializers other than default ones are added in `ApplicationInsights.config`

**Note:** We are using .net framework 4.5.1

**Comment by cijothomas** [comment]
InstrumentationKey must be either specified in the AI.config file, or if setting programmatically, then it must be done in the beginning of the application (like Global.aspx.cs), using TelemetryConfig.Active.InstrumentationKey = "ikey goes here".

Overrriding ikey field for individual item is not the correct way of providing ikey.

**Comment by anjoiype** [comment]
It is initialized in Application_Start of global.asax.cs. Currently the issue is only with live metrics. Other logs in AI are showing data like request, failures etc. correctly. So if ikey was not configured properly then whole AI logs would have affected right?

**Comment by cijothomas** [comment]
The code snippet you have shared above shows ikey is set on individual telemetry only. I don't see TelemetryConfig.Active.InstrumentationKey being set.

**Comment by cijothomas** [comment]
> So if ikey was not configured properly then whole AI logs would have affected right?
You are overriding ikey using initializer for each item. This is not respected by LiveMetrics as it expects ikey to be coming from the config, not on individual item.

**Comment by anjoiype** [comment]
It works after adding using TelemetryConfig.Active.InstrumentationKey. Thanks @cijothomas
