### ISSUE TITLE
How sampling and retained samples works - locally and in distributed system

### ISSUE THREAD

**Issue by darthkurak** [microsoft/ApplicationInsights-dotnet#2180]
Hi everyone.
I have question about sampling and how it exactly works.
In documentation was said, that samples are sampled in or sampled out together due to single operation_id.
Is this also works in distributed scenario (operation_id which spans over multiple services)?
What are exactly conditions to make given operation_id fully retained or fully sampled? 
In documentation was said that happens when, for example, request fail. Then all related telemetry is retained. 
But:
1. It means success == false or 5xx code?
2. This condition must happen on request which initiated operation_id or any request in operation_id? 
3. Are there other "examples" where samples are together sampled or retained?
4. How this under the hood works? 

I am asking, because from my observation it seems that for request which failed with 404 in service B, but it didn't initiated operation_id, i lost:
- dependency HTTP (from service A to service B) 
- dependency to Azure Cosmos (from service B) 

I have fixed sampling. 

![image](https://user-images.githubusercontent.com/4254758/109420879-14451a00-79d5-11eb-87c8-d14fdfd1c53e.png)

**Comment by darthkurak** [comment]
Actually, i did some more testing, and it seems that described behavior (retaining related telemetry when request fail) doesn't work. 
Documentation states:

> "The sampling decision is based on several rules that aim to preserve all interrelated data points intact, maintaining a diagnostic experience in Application Insights that is actionable and reliable even with a reduced data set. For example, if your app has a failed request included in a sample, the additional telemetry items (such as exception and traces logged for this request) will be retained. Sampling either keeps or drops them all together. As a result, when you look at the request details in Application Insights, you can always see the request along with its associated telemetry items.
> 
> The sampling decision is based on the operation ID of the request, which means that all telemetry items belonging to a particular operation is either preserved or dropped. For the telemetry items that do not have an operation ID set (such as telemetry items reported from asynchronous threads with no HTTP context) sampling simply captures a percentage of telemetry items of each type."

I checked this with bare, minimum web api app (asp .net core 3.1) with forecast controller. Enabled fixed sampling. I put Request in Exclude Types.
One action calls another one (twice, in parallel), and in the end, has throw exception.

```
        [HttpGet("some")]
        public Task Some()
        {
            var taskList = new List<Task>
            {
                _httpClient.GetAsync("https://localhost:5001/weatherforecast"),
                _httpClient.GetAsync("https://localhost:5001/weatherforecast")
            };

            Task.WhenAll(taskList);

            throw new Exception();
        }
```
This is result in app insights: 
![image](https://user-images.githubusercontent.com/4254758/109429345-9c3e1a80-79fb-11eb-96cd-90fcd268bd0c.png)
See? No dependencies (they was filter out by SamplingProcessor

**Comment by cijothomas** [comment]
I cannot comment fully without seeing the full repro, but here are general thoughts:
If you excluded Request from being sampled, then you essentially overrode sampling decision. i.e if a Request was supposed to be dropped, it'd still be retained as Request is excluded from sampling. Dependency was eliminated as it was not excluded.

Could you try with no exclusions list and see if it matches expectation?

**Comment by darthkurak** [comment]
Forgive for resurrecting question.
Let's start with big thanks for clarification.
When i have no exclusions - it works as expected.
At least in that specific matter (items being sampled together or dropped together due to same operation_id)
But i would like to hear answer for other questions:
Which rules decide to drop given operation_id?
I observe that operations which fail with 500 error code - also are sampled
Can i configure somehow SDK to preserve related items which fail for specific codes? 
In the end - i would like to have all operation_id's which results in 5xx codes with preserved telemetry, and all other - sampled.

**Comment by darthkurak** [comment]
In documentation is written: `The sampling decision is based on several rules`
Beside operation_id rule - what are other rules?

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#how-sampling-works the 2nd paragraph explains the several rules. 
There is no other rule based on anything other than operation_id.

**Comment by darthkurak** [comment]
Another question: Are sampling somehow group telemetries before applying sampling and set itemCount base on group item count?
In another word - if I see some telemetry for example: Request - Forecast/GetForecast - itemCount = 67 - does itemCount reflects how many Forecast/GetForecast calls was made to this endpoint (but 66 was sampled), or it is sum of all Request on the service (66 was sampled, but actually we don't know how many calls was made for specific endpoint)

**Comment by dzendras** [comment]
@darthkurak That's an excellent question! I fail to find any documentation that explains that clearly. @cijothomas could you please clarify?

**Comment by dzendras** [comment]
Found the answer in another [issue](https://github.com/microsoft/ApplicationInsights-dotnet/issues/1980).
