### ISSUE TITLE
TelemetryChannel & ingestion endpoint configuration

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#2184]
At the moment, our public api permits users to do this: (***not recommended***)
```csharp
var serverTelemetryChannel = new ServerTelemetryChannel { EndpointAddress = "VALUE"};
TelemetryConfiguration config = new TelemetryConfiguration(
   instrumentationKey: "00000000-0000-0000-0000-000000000000",
   channel: serverTelemetryChannel
   );
serverTelemetryChannel.Initialize(config);
var clientTest = new TelemetryClient(config);
```

The expectation is that if an endpoint needs to be set, it should be set on the connection string.
Our public documentation recommends this:
```csharp
TelemetryConfiguration config = new TelemetryConfiguration {
    ConnectionString = "InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=VALUE",
    TelemetryChannel = new ServerTelemetryChannel(),
};
var clientTest = new TelemetryClient(config);
```

**Comment by 23min** [comment]
What is the current status on this?
Since a week, we are seeing that our code that uses only an `instrumentationKey` no longer logs to Application Insights.
When we change to ConnectionString, it works again.
Was the Application Insights API upgraded? (We are using 2.16.0 of the SDK)

**Comment by cijothomas** [comment]
> Since a week, we are seeing that our code that uses only an instrumentationKey no longer logs to Application Insights.
> When we change to ConnectionString, it works again.

While ConnectionString is recommended, its not mandatory unless you are using special cloud regions (https://docs.microsoft.com/azure/azure-monitor/app/custom-endpoints?tabs=net#regions-that-require-endpoint-modification).
if you are not on this special regions, and telemetry is lost if not using connectionstring, then you need to file a support ticket with Azure .

**Comment by 23min** [comment]
Thanks @cijothomas, we did.

**Comment by 23min** [comment]
@TimothyMothra Do you know when this breaking change will take effect?

The reason I ask is that we experience the symptoms of this change. However, we don't find any information that using a connection string is already a requirement.
