### ISSUE TITLE
Getting error: System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource when running app in linux container

### ISSUE THREAD

**Issue by drhXC** [microsoft/ApplicationInsights-dotnet#2187]
Setup an ASP.NET Core application to use Microsoft.ApplicationInsights.AspNetCore. Runs fine locally (MacOS), but when published as a linux app and deployed to a linux instance, it throws the below error when attempting to call AddApplicationInsightsTelemetry.

```
2021-03-17T09:59:25.953-04:00 [APP/PROC/WEB/0] [ERR] Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
2021-03-17T09:59:25.953-04:00 [APP/PROC/WEB/0] [ERR] File name: 'System.Diagnostics.DiagnosticSource, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
2021-03-17T09:59:25.953-04:00 [APP/PROC/WEB/0] [ERR] at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetry(IServiceCollection services)
```

Configuration:
.NET core 3.1
Linux
Dependencies
Microsoft.AspNetCore.Owin 3.1.1
Microsoft.AspNetCore.Server.Kestrel 2.2.0
Microsoft.ApplicationInsights.AspNetCore 2.17.0
System.Diagnostics.DiagnosticSource 5.0.1

I set the application key by environment variable (APPINSIGHTS_INSTRUMENTATIONKEY). I have verified that I am are setting it properly. I have also ran a variation where I do set the key inside of the appsettings.json, but that also returns the same error. 

I have also tried downgrading Microsoft.ApplicationInsights.AspNetCore to 2.16.0, but that did not help.

Is there a known issue and/or workaround for this configuration?

**Comment by qdraw** [comment]
I have the same issue. Version 2.15.0 is for me the latest version that works. I'm running by the way on .Net core 3.1.102 and 'linux-arm'

**Comment by kirk-marple** [comment]
We have a similar problem on Windows, anything above 2.15.0 brings in System.Diagnostics.DiagnosticSource which is 5.0.x.

I really wish they hadn't taken a dependency on something from the 5.x versioning because it currently breaks within any app running pre-.NET 5.0.

Our Azure Functions are still on .NET Core 3.1, and if I upgrade AppInsights past 2.15, I start to get missing method exceptions.

Personally, I think this isn't right.  On non-.NET 5.0, it shouldn't be depending on anything from 5.x versioning.

![image](https://user-images.githubusercontent.com/13594550/112258631-0aa18180-8c24-11eb-9289-a03126a2db75.png)

**Comment by cijothomas** [comment]
There shouldn't be any issues with using System.Diagnostics.DiagnosticSource 5.X in, say, .NET Core 3.1 apps. The DiagnosticSource package is fully backward compatible. (we can continue to expect that application insights SDK always require the latest DS package, irrespective of the actual framework where the app is running.)

If anyone can share a minimal repro app showing issues with the latest SDK + DS 5.0, that'd be helpful.

@kirk-marple For Functions, its recommended to open an issue in the Functions repo. (Also I don't think it is ever recommended to directly install ApplicationInsights package in Functions due to versioning issues. But this is best asked/resolved in Functions repo)

**Comment by cijothomas** [comment]
> I really wish they hadn't taken a dependency on something from the 5.x versioning because it currently breaks within any app running pre-.NET 5.0.

Could you elaborate on this and share a sample which repros this issues.

**Comment by kirk-marple** [comment]
> @kirk-marple For Functions, its recommended to open an issue in the Functions repo. (Also I don't think it is ever recommended to directly install ApplicationInsights package in Functions due to versioning issues. But this is best asked/resolved in Functions repo)

What I found was the latest Microsoft.Azure.WebJobs.Logging.ApplicationInsights pulls in Microsoft.ApplicationInsights 2.17.0, and that has the 5.x dependency on System.Diagnostics.DiagnosticSource, which starts giving the missing method exception problems.

From what I understand with the Functions hosting, this is a known limitation, and we need to be careful pulling in .NET 5.x bits into Functions.  We've had to be very careful upgrading to anything 5.x in our common assemblies, which our Functions app references, or we start to get version compatibility issues. (Functions has started to rollout 5.x support, but we use Durable Functions which aren't expected to be compatible til .NET 6 or 7.)

I'll have to spend the time creating a separate solution/project to repro this; it's difficult to carve out of our bigger application right now.

But I literally hit this problem when I upgraded Microsoft.Azure.WebJobs.Logging.ApplicationInsights to 3.0.27 from 3.0.25, and pushed our function app to Azure, and started hitting these errors:

Method not found: 'Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1<!!0> Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation(Microsoft.ApplicationInsights.TelemetryClient, System.Diagnostics.Activity)'.

**Comment by cijothomas** [comment]
@kirk-marple If webjobs 3.0.27 is bringing in a version of ApplicationInsights, which is not supported in the Functions infra, then it must be reported in Functions repo. Functions+ApplicationInsights integration is handled separately in that repo.

Outside of Functions - This SDK is always expected to require the latest DS version as it requires features from the latest version of DS, and cannot operate with lower versions.

**Comment by kirk-marple** [comment]
I hear you, we have the same problem if we update Microsoft.ApplicationInsights from 2.15.0 to 2.17.0 in our common assemblies.

We need access to Microsoft.ApplicationInsights to reference TelemetryClient in our base classes, which are used in web services and console apps, not just our functions.  So we have to reference it in our common assemblies.

> Outside of Functions - This SDK is always expected to require the latest DS version as it requires features from the latest version of DS, and cannot operate with lower versions.

Gotcha, it's just troublesome as a developer where, even if we keep our apps to .NET Core 3.1 and don't pull in anything intentionally from 5.x versioning, we get broken by updating to all the latest Nuget packages (which aren't using 5.x versioning).

Unless I'm missing something and we're doing something wrong here, in your opinion?

**Comment by cijothomas** [comment]
S.D.DS is an out-of-band package and is expected to work with app running in **all** supported .NET versions, not just the .NET5 apps.

Do you have an example where a .NETCore3.1 app is broken, when updating DiagnosticSource to 5.0? Its fully backward compatible, and should not cause any issues. if it is causing issues, we need to investigate why.

**Comment by kirk-marple** [comment]
@cijothomas I'll have to create a standalone project to repro this; it would be hard right now to break this out of our multiple projects/solutions.  I'll work on this and post back a sample when ready.

**Comment by epenet** [comment]
I would like to add a note...
We had five applications all running fine with was working fine with a direct dependency to ApplicationInsights  v2.16.0

Without making any changes to the project dependencies, or any changes to the initialisation routines, one of the applications now refuses to launch with the same error...
The only code updates were in  updates were a few wwwroot files (css/js) and a few middleware functions (cs).

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.Diagnostics.DiagnosticSource, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetry(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetry(IServiceCollection services, Action`1 options)
   at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetry(IServiceCollection services, String instrumentationKey)
```

**Comment by kirk-marple** [comment]
@cijothomas I've stripped down our code into a reproducible sample.

https://github.com/kirk-marple/function-app-missingmethodexception

Simply updating from 2.15.0 to 2.16.0 or 2.17.0 causes the missing method exception.

```
[2021-04-05T21:01:48.941Z] System.Private.CoreLib: Exception while executing function: HttpFunction. FunctionApp: Method not found: 'Microsoft.ApplicationInsights.Extensibility.IOperationHolder`1<!!0> Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation(Microsoft.ApplicationInsights.TelemetryClient, System.Diagnostics.Activity)'.
```

**Comment by cijothomas** [comment]
@kirk-marple The repro is a functions app and I recommend opening issue in Functions repo (as mentioned earlier https://github.com/microsoft/ApplicationInsights-dotnet/issues/2187#issuecomment-805969343)

**Comment by kirk-marple** [comment]
Going to do that as well, thanks.  I was following up on your prior request:

> Could you elaborate on this and share a sample which repros this issue

**Comment by cijothomas** [comment]
Yea, i was looking to get repro app for non-functions case. (Functions runtime use a special way of loading AI or DS packages. )

**Comment by cijothomas** [comment]
https://github.com/kirk-marple/function-app-missingmethodexception/blob/master/FunctionApp.csproj#L30 - This sounds incorrect. Per my understanding, Functions doesn't allow user to take **direct** dependency on ApplicationInsights.

**Comment by kirk-marple** [comment]
Just simplified it further, and still get the error.  We need to take a dependency on that, so we can use TelemetryClient.StartOperation.

 <PackageReference Include="Microsoft.ApplicationInsights" Version="2.17.0" />

**Comment by cijothomas** [comment]
You dont need to add application insights direct dependency to add custom logging:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#log-custom-telemetry-in-c-functions
