### ISSUE TITLE
Trace logs are missing randomly in production (Even after calling Flush, adding .Sleep and disabling sampling)

### ISSUE THREAD

**Issue by ash-kmr** [microsoft/ApplicationInsights-dotnet#2189]
Nuget packages:
 - log4net version 2.0.11
 - Microsoft.ApplicationInsights 2.9.1
 - Microsoft.ApplicationInsights.Log4NetAppender 2.8.1
 - Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 2.9.1
 - Microsoft.ApplicationInsights.WindowsServer 2.9.1

Runtime: 
- .Net framework 4.7.2

Hosting Environment:
- Its a console app running on windows.

I am sending trace logs from my console application to application insights. through the entire runtime of the application, it sends 40 logs to application insights if it completed successfully. The application is deployment on multiple VMs. I am receiving variable number of logs from each VM even though all are succeeding. Some are sending 10 logs, some all 40 etc. There is no specific logs that are being missed. Sometimes the initial ones are missed, some times the middle ones, sometimes the last ones.

Also - when I create a console application on my dev machine, and try to send the same 40 logs in sequence to application insights, it works. 

I have tried using both InMemoryChannel and ServerTelemetryChannel

I also set the MaxTelemetryItemsPerSecond to 10000 (which should effectively disable sampling in my scenario) and added Event;Trace;Exception;Dependency to ExcludedTypes.

After all this, still I am missing logs from ApplicationInsights randomly.

Is there any reason this could be happening? Is there any way to check if the SDK is working properly in the VMs ?

**Comment by cijothomas** [comment]
Since you mentioned console app - are you ensuring that the app is not exiting before SDK flushes out telemetry?

**Comment by ash-kmr** [comment]
@cijothomas I added a 50 seconds sleep after Flush to ensure that. Is there any way I can check whether the Flush completed or not?

**Comment by cijothomas** [comment]
Unfortunately, if you are using ServerTelemetryChannel, there is no way. This is being addressed currently, and would be available in the coming versions.

1.  Confirm if the data loss is due to sampling: https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#knowing-whether-sampling-is-in-operation
2. Try a bigger Sleep after flush. 

Since you mentioned InMemoryChannel also produce same behaviour, I doubt if its due to Flush.. as the Flush() in InMemoryChannel is sync flush, and should have flushed all telemetry.
Follow https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data doc and get SDK logs, which might give additional hints.

**Comment by ash-kmr** [comment]
according to this:

union requests,dependencies,pageViews,browserTimings,exceptions,traces
| where timestamp > ago(1d)
| summarize RetainedPercentage = 100/avg(itemCount) by bin(timestamp, 1h), itemType

there is no data loss due to sampling.

I'll try to see if I find something in SDK logs.

**Comment by linocontreras** [comment]
I'm having a very similar issue with a console app and InMemmoryChannel. Some of the trace messages are created under an operation (dependency), but when I look for the operation id on the dependencies I cannot find it.

At other times, the custom events that were produced around the same time of trace messages are not present on the AppInsights portal but the traces are. I haven't found any pattern either so it looks pretty much random. 

I haven't found any indication of sampling either.
