### ISSUE TITLE
Custom TelemetryProcessor does not receive TraceTelemetry generated by Microsoft.ApplicationInsights.NLogTarget

### ISSUE THREAD

**Issue by CalinMPopa** [microsoft/ApplicationInsights-dotnet#2192]
* List of NuGet packages:
    "Microsoft.ApplicationInsights.AspNetCore" Version="2.17.0"
    "Microsoft.ApplicationInsights.NLogTarget" Version="2.17.0"

* Runtime version: : netcoreapp3.1
* Hosting environment: Windows

I have created a custom ITelemetryProcessor to reduce the amount of telemetry that gets uploaded to AppInsights.
My processor receives DependencyTelemetry, RequestTelemetry, ExceptionTelemetry and MetricTelemetry but no TraceTelemetry (generated by NLOG). My traces are correctly uploaded to AppInsights.

My code looks like:

                    services.AddApplicationInsightsTelemetryProcessor<IdentityServerTelemetryProcessor>();
                    services.AddApplicationInsightsTelemetry(Configuration);
                    services.AddSingleton<ITelemetryInitializer, CloudRoleNameTelemetryInitializer>(serviceProvider => new CloudRoleNameTelemetryInitializer("my-service"));
                   services.AddApplicationInsightsTelemetryProcessor<IdentityServerTelemetryProcessor>();

Thank you for your help.

**Comment by cijothomas** [comment]
I don't think NLog and Asp.Net Core combination is well supported. NLog uses TC.Active, and Asp.Net Core uses a different TelemetryConfig using DI.  This might explain why the TelemetryProcessor is not seeing logs from NLog, as its using a different config, than the one you are adding your processor to.
You could try to add the custom TelemetryProcessor to the TC.Activity configuration and its likely to be picked up by the NLog appender.

**Comment by cijothomas** [comment]
Related issue with another logging adapter in Asp.net Core https://github.com/microsoft/ApplicationInsights-dotnet/issues/2139

**Comment by snakefoot** [comment]
NLog ver. 5.0 improves [integration with dependency-injection](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#logfactory-with-dependency-injection), so one can resolve dependencies (Like TelemetryProcessor) in a lazy fashion if necessary..
