### ISSUE TITLE
ImmediatePurgeDataOn30Days broken

### ISSUE THREAD

**Issue by rhollamby** [microsoft/ApplicationInsights-dotnet#2228]
I am trying to deploy the following Bicep Module via a DevOps pipeline (see below). But get the error show below which indicates that the ImmediatePurgeDataOn30Days cannot be set. But the documentation clearly shows this is a valid, optional property. 
https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/components?tabs=bicep

Any ideas why?

##[debug]     | 1:18:57 AM - The deployment 'c17c34d3-b82b-4c6d-9df0-496ae4aa6812' failed with error(s). Showing 3 out
##[debug]     | of 3 error(s). Status Message: ImmediatePurgeDataOn30Days cannot be set on current api-version
##[debug]     | (Code:BadRequest)  Status Message: Template output evaluation skipped: at least one resource
##[debug]     | deployment operation failed. Please list deployment operations for details. Please see
##[debug]     | https://aka.ms/DeployOperations for usage details. (Code:DeploymentOperationFailed)  Status Message:
##[debug]     | At least one resource deployment operation failed. Please list deployment operations for details.
##[debug]     | Please see https://aka.ms/DeployOperations for usage details. (Code: DeploymentFailed)  - {   "code":
##[debug]     | "BadRequest",   "message": "ImmediatePurgeDataOn30Days cannot be set on current api-version",  
##[debug]     | "innererror": {     "diagnosticcontext": "bde7c90c-caf7-44c0-91f1-a188652ed8e9",     "time":
##[debug]     | "2021-04-13T01:17:48.6788341Z"   } } (Code:BadRequest)   CorrelationId:
##[debug]     | a662b903-41aa-4204-aee4-a8e987c9dce7

`param region string
param appInsights_name string
param logAnalaticsResourceID string
param appInsights_30DayPurge bool

resource appInsightsResource 'Microsoft.Insights/components@2020-02-02-preview' = {
  name: appInsights_name
  location: region
  kind: 'string'
  tags: {
    displayName: 'AppInsight'
    ProjectName: appInsights_name
  }
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalaticsResourceID
    ImmediatePurgeDataOn30Days: appInsights_30DayPurge
    IngestionMode: 'LogAnalytics'
  }
}

output APPINSIGHTS_INSTRUMENTATIONKEY string = appInsightsResource.properties.InstrumentationKey
`

**Comment by cijothomas** [comment]
@rhollamby This issue doesn't seem to have any connection to the SDK shipped from this repo. If you think this SDK is involved, please share additional details on the version, code snippet used , and expected behavior vs actual behaviour.

Please re-open if you think this is an SDK bug/issue.
