### ISSUE TITLE
Make sampling be configurable by telemetry types

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-dotnet#223]
We would like to add a possibility to exclude certain telemetry types from sampling.

**Proposal**:
Make sampling telemetry processors (both Fixed rate and Adaptive) configurable.
We would like to add a configuration setting that indicates what telemetry types would be sampled.

**Defaults**:
By default all telemetry items except MetricTelemetry would be sampled (as before).

**Example:**

```
<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
    <SampledTelemetry>Dependency;Exception;PageView;PerformanceCounter;Request</SampledTelemetry>
</Add>
```

```
<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.SamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
    <SampledTelemetry>Dependency;Exception;PageView;PerformanceCounter;Request</SampledTelemetry>
</Add>
```

**SampledTelemetry possible values** (these are envelope type names except for dependency):

- Dependency

- Event

- Exception

- Metric

- PageView

- PerformanceCounter

- Request

- Message

Note that with proposed changes you can add multiple sampling telemetry processors and configure samling settings separately for different telemetry types. For example you can use fixed rate sampling for traces and adaptive sampling for everything else.

**Comment by kartang** [comment]
Will there be possible correlation scenario where we miss the correlation between different event types, as we no more sample at user ID/operation id level, which assures that all telemetry for a particular operation is either in or out?

**Comment by abaranch** [comment]
We do not change sampling algorithm. If item needs to be sampled we still use user, operation and session as before.

**Comment by AlexBulankou** [comment]
Instead of `Message`, I would call it `Trace`, I think this is more known with customers.
Also just wanted to include the full snippet of how adaptive sampling telemetry processor will look, including MaxTelemetryItemsPerSecond property

```
<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
      <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>      
      <SampledTelemetry>Dependency;Exception;PageView;PerformanceCounter;Request </SampledTelemetry>
</Add>
```

**Comment by danhadari** [comment]
I don't think we need this flexibility. IMHO, this over complicates the sampling definition. I think we should only let the user to _EXCLUDE_ traces & custom events of the sampling program, adaptive or fixed rate.

**Comment by AlexBulankou** [comment]
@danhadari, we discussed this and believe that proposed API doesn't introduce any more complexity compared with a simple flag to exclude custom events and traces. In API design we are striving for consistency, which means that similar types of objects should ideally have similar behaviors. A flag that only enables excluding some of the types but not the others would result in user confusion. Additionally we already had requests from users to exclude certain other types from sampling, for instance, exceptions in one example and everything but dependencies in another example. Proposed solution enables these scenarios while keeping configuration simple and easy to understand.

**Comment by DasCode** [comment]
Is it possible to take this a step further and apply different sampling rates to certain kinds of traffic. I have some requests/dependencies that happen very often I'd like to sample aggressively, and I have other less common requests/dependencies that I'd like to do minimal sampling on to ensure I am able to capture some instances.

**Comment by AlexBulankou** [comment]
Here's a [sample](https://blogs.msdn.microsoft.com/albulank/2016/04/29/extending-appinsights-telemetry-processor-to-specify-what-types-to-sample/) and [code](https://github.com/AlexBulankou/ai-samples/blob/master/ConfigurableAdaptiveSamplingTelemetryProcessor.cs) that extends current adaptive sampling telemetry processor to allow specifying what telemetry types to sample. It follows the API as proposed here. 
@DasCode what you're proposing would definitely add complexity to implementation and testing. At this time we haven't had customers requesting this level of customization. However you can follow [this example](https://github.com/AlexBulankou/ai-samples/blob/master/ConfigurableAdaptiveSamplingTelemetryProcessor.cs) to encapsulate standard telemetry processor inside your wrapper that will provide additional sampling on top base sampling and you can choose any heuristics.

**Comment by SergeyKanzhelev** [comment]
Instead of adding logic to `AdaptiveSamplingTelemetryProcessor` is it better idea to make it to not process any field that has `SamplingPercentage` already set to some value. We can than have a processor that will set `SamplingPercentage` to 1 for events or any other type you specify. This way we can satisfy @DasCode requirement as it will be possible to sample specific types more aggressively just before the `AdaptiveSamplingTelemetryProcessor` will apply it's logic

**Comment by SergeyKanzhelev** [comment]
Proposed solution will also allow to exclude a specific event from the sampling in code by setting it's `SamplingPercentage` to 1

**Comment by AlexBulankou** [comment]
Excluding events from sampling is already achieved by Anastasia's proposal. What you're suggesting is allowing customers to set more agressive sampling for some times of telemetry. I am worried about exposing this option because it will break the transaction completeness  - you won't get everything within the sample. I don't think we have had any asks for this other than the question above from @DasCode.

**Comment by SergeyKanzhelev** [comment]
Sure. Implementing different sampling will require lot's of code. So it wouldn't be much easier than it is now. Simple respect `SamplingPercentage` will allow to disable sampling for specific event from code easier

**Comment by AlexBulankou** [comment]
I see. So you are proposing to inject a new telemetry processor in front of sampling telemetry processor that would be set SamplingPercentage=1 for the events that should be excluded from sampling? Or you are also proposing to allow customers specify custom percentage in this new telemetry processor, not merely excluding?

**Comment by abaranch** [comment]
Also we would have one more dependency order restriction.

**Comment by SergeyKanzhelev** [comment]
Agree. I'm fine with that proposal. If you can make a change to simplify reporting un-samplable events without duplicating the entire configuration - it will be great.

**Comment by abaranch** [comment]
Questions:
1. Do we have 2 alternative properties: SampledTelemetry and NonSampledTelemetry so you can you the one where you list would be shorter?
2. Do we want to ban MetricTelemetry and PerformaceCounter so they cannot be sampled ever?

**Comment by SergeyKanzhelev** [comment]
I'd recommend to specify types to "Exclude" rather than "Include". So if I'm missing telemetry - I'll add it to exclusion list instead of remembering all data types
Metrics and counters are non-sampled ever.

**Comment by abaranch** [comment]
Implemented
