### ISSUE TITLE
Application Insights is not capturing simple exception telemetry when using ILogger.Log(LogLevel, Exception, string)

### ISSUE THREAD

**Issue by stevieray8450** [microsoft/ApplicationInsights-dotnet#2236]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: **"Microsoft.ApplicationInsights" Version="2.17.0"** and **"Microsoft.ApplicationInsights.AspNetCore" Version="2.15.0"**
* Runtime version: **netcoreapp3.1**
* Hosting environment: **Windows; IIS Express during local development and on-prem IIS server**

### Describe the bug

When invoking `ILogger.Log` as mentioned [here ](https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#what-application-insights-telemetry-type-is-produced-from-ilogger-logs-or-where-can-i-see-ilogger-logs-in-application-insights) and [here](https://github.com/MicrosoftDocs/azure-docs/issues/30986#issuecomment-493196290), no exception telemetry is getting captured or recorded. I can observe this from Visual Studio 2019 as well as inside the Azure Application Insights instance accessed via the Azure Portal.

Other telemetry -- dependencies, metrics, and requests, for example -- get recorded as expected, and are accessible via Visual Studio 2019 and Azure Portal.

### To Reproduce
`ApplicationInsights:InstrumentationKey` and `Logging:ApplicationInsights:LogLevel:Default` are coming from Azure App Configuration and are configured with the correct instrumentation key (confirmed by the fact that we have other expected telemetry getting recorded) and "Information" value, respectively.

Repro code. Simple API controller:
```
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestProject.Enum;

namespace TestProject.Web.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class PipelineController : ControllerBase
    {
        private readonly ILogger<PipelineController> simpleLogger;

        public PipelineController(ILogger<PipelineController> simpleLogger)
        {
            this.simpleLogger = simpleLogger;
        }

        /// <summary>
        /// Queues a pipeline extraction
        /// </summary>
        [HttpPost]
        [Route("Queue")]
        public IActionResult Queue(Payload payload, Profile profile)
        {
            simpleLogger.Log(LogLevel.Error, new ArgumentException(), "just a test");

            try
            {
                throw new ArgumentException();
            }
            catch (ArgumentException e)
            {
                simpleLogger.Log(LogLevel.Error, e, "just a test");
                return BadRequest(e.Message);
            }
        }
    }
}
```

Demonstrating registration at Startup:
```
using Microsoft.AspNetCore.Server.IISIntegration;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.FeatureManagement;
using Web.Model.Validation;

namespace Web
{
    public class Startup
    {
        public IConfiguration Configuration { get; }

        public Startup(IConfiguration configuration) => Configuration = configuration;

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAzureAppConfiguration();

            services.AddControllers().ConfigureApiBehaviorOptions(options =>
            {
                options.InvalidModelStateResponseFactory = context =>
                {
                    return InvalidRequestResponse.GetBadRequestObjectResult(context);
                };
            });

            services.AddOptions();
            services.AddFeatureManagement();
            services.AddAuthentication(IISDefaults.AuthenticationScheme);

            services.AddApplicationInsightsTelemetry();
        }
    }
}

```

**Result**: neither call to `ILogger.Log` results in exception telemetry getting recorded

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
* If we will not be able to repro the behavior you're reporting

### For Immediate Support

For immediate support relating to the Application Insights .NET SDK we encourage you to file an [Azure Support Request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) with Microsoft Azure instead of filing a GitHub Issue in this repository. 
You can do so by going online to the [Azure portal](https://portal.azure.com/) and submitting a support request. Access to subscription management and billing support is included with your Microsoft Azure subscription, and technical support is provided through one of the [Azure Support Plans](https://azure.microsoft.com/support/plans/). For step-by-step guidance for the Azure portal, see [How to create an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). Alternatively, you can create and manage your support tickets programmatically using the [Azure Support ticket REST API](https://docs.microsoft.com/rest/api/support/)

**Comment by rajkumar-rangaraj** [comment]
@stevieray8450 Could you please provide a small repro (an archive or a repo) that will help us to investigate this issue.

**Comment by stevieray8450** [comment]
@rajkumar-rangaraj , sure. Please see https://github.com/stevieray8450/AiTest and supply your own instrumentation key in appsettings.json. Thank you!

**Comment by cijothomas** [comment]
https://github.com/stevieray8450/AiTest/blob/master/Program.cs#L20 The Logging provider is replaced  with Serilog, so the logs don't get sent to ApplicationInsights.

**Comment by stevieray8450** [comment]
@cijothomas Thanks for pointing that out. Yet dependency, metric, and request data gets recorded. It seems like I should be able to  still collect that exception telemetry, too. How could I get that?

**Comment by cijothomas** [comment]
If you replace the logging system with Serilog, (as in the repro you shared), no logging provider can get the logs. (not just application insights, anything like ms.ext.logging.console).
You can simply comment out the following lines (https://github.com/stevieray8450/AiTest/blob/master/Program.cs#L20-L25) to get logs flowing to ApplicationInsights (and any other providers).

If you want to keep Serilog as the main provider, and have serilog forward it to others (in the repro, it look like its forwarding to Console), then you need to configure Serilog to sent to ApplicationInsights (I have seen that they do have a sink for application insights as well). Its best to ask in Serilog repo on how to set up that.
