### ISSUE TITLE
App Insights Status monitor v2 does not capture SQL command text

### ISSUE THREAD

**Issue by Danthar** [microsoft/ApplicationInsights-dotnet#2237]
I have been working on this issue for a while now. It works perfectly from my localhost but when i deploy it to my on premise machine, i cannot get it to work.

I noticed that a few days ago the docs where changed: https://github.com/MicrosoftDocs/azure-docs/commit/1fbd05fab441f1a7221fbbd9f55f87a395ca7c17

But im unsure what this means. Does this mean that its no longer supported? or that this step is no longer needed?
Also the status functions that are part of the powershell module are not really helpfull, neither is the troubleshooting docs. Because the status functions show a list of things, but its unclear what this means. And the troubleshooting docs only describe what might be wrong, but nothing on how this can be fixed.

We are in the application referencing 2.17.0 and i noticed the Az.ApplicationMonitor still uses 2.9. Might that be an issue?

**Comment by cijothomas** [comment]
The doc change reflect the fact that if you are using SMV2 alone, there is no need of changing AI.config. (infact, Ai.Config changes are not allowed in SMv2)

If your case, I think you are using a Asp.Net app, with 2.17 version of the SDK. And you want to see full SQL text capture.
The following doc lists the exact steps required in your case:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query
1. Use SMV2 and install instrumentation engine.
2. Restart IIS
3. Make AI.config changes.
4. Restart app to take Ai.Config changes in effect.

The fact that 2.17 is used by you vs 2.9 in SMv2 shouldn't have any impact on SQL text collection.


(if you have any additional feedback about the docs, please open doc issues right from the docs page.)

**Comment by Danthar** [comment]
First, thx for your feedback.

So we did those steps you describe. Except for the 3th step since our ai.config file already contains all the settings we need. And yet, it does not work. And im having a hard time trying to diagnose what the problem is.
Especially since when i start the application locally, on which i did the same steps. It works. Which i verify by checking in AI which SDK is being used for logging. From my local machine it correctly reports an 'rddp' type SDK, but from the on-premise machine it reports an 'rddf' type SDK. 

I have been looking at these docs: [troubleshooting](https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-troubleshoot). And i used for example the 'Get-ApplicationInsightsMonitoringStatus -InspectProcess' command. And sure enough there is a list of DLL's there. 
But i have no idea:
- if its complete
- if its correct
- if there is anything loaded that might be an issue

I tried comparing whats loaded and configured with what it shows on my local machine, but i cannot find anything that stands out.

I also manually verified the registry settings and other stuff that the module configures, to ensure that it happened correctly, but it all seems to be in order.
So im kinda stumped.

**Comment by cijothomas** [comment]
For immediate support, I'd suggest to open support ticket with Microsoft Azure.

Since you were able to make it work in local environment, but not in server, you can collect the logs from the server and see if that gives some hints - something which says why instrumentationengine is not dropped correctly.

**Comment by Danthar** [comment]
I would love to see some logs, but. how ? Eventlog is empty. And the application itself is not generating any relevant logs either.

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/status-monitor-v2-troubleshoot#collect-etw-logs-by-using-perfview

**Comment by Danthar** [comment]
Ok so perfview basically confirmed the behavior i was seeing.
I compared it with a trace of my local machine, and confirmed that absolutely nothing is happening.

So i went the nuclear option, and manually deleted all traces of the Az.ApplicationMonitor on the machine.
Then i reinstalled it.

And now it works.
Why did it fail in the first place? Beats me.
