### ISSUE TITLE
Unable to trace events using Application Insights once support for .NET 5 is added in the client library

### ISSUE THREAD

**Issue by abhipsaMisra** [microsoft/ApplicationInsights-dotnet#2239]
We are using the following nuget package for logging our test suite traces to application insights:
`<PackageReference Include="Microsoft.ApplicationInsights" Version="2.14.0" />`

However, once we added support for .NET 5 into our library and test code, we no longer see the log traces being flushed to application insights.
Is this a known compatibility issue, or would this be addressed if we update to the latest version: https://www.nuget.org/packages/Microsoft.ApplicationInsights/2.17.0

**Comment by jamdavi** [comment]
@abhipsaMisra Does this only happen when we compile our libraries with .net5.0 as the target framework? Can we try enabling logging as explained here? https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data#troubleshooting-logs

@rajkumar-rangaraj Hey Raj, can you answer the question @abhipsaMisra asked? If there are known issues with .net5.0 we'd like a confirmation of that, or if the suspicion is its something we're doing we'd like a good path to start with.

cc: @reyang, @cijothomas

**Comment by cijothomas** [comment]
There is no known issues with .net5.0 for application insights.

its not clear what the issue in this post is - please share minimal repro app showing the issue - that'd help us understand/investigate the issue.

**Comment by abhipsaMisra** [comment]
Sorry about the delay in responding. Our sample app with only app insights on .NET 5 worked as expected. It looks like there is an application-level implementation issue at our end which is causing the issue for us. We'll investigate it. This issue can be closed.
