### ISSUE TITLE
ApplicationInsightsLogger not removing curly braces from "{OriginalFormat}" when Scope is a Composite Format String

### ISSUE THREAD

**Issue by utpilla** [microsoft/ApplicationInsights-dotnet#2240]
**Is your feature request related to a problem?**
ApplicationInsightsLogger populates a property named `{OriginalFormat}` when `Scope` is a [Composite Format String](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting#composite-format-string)

For example for the following code

![image](https://user-images.githubusercontent.com/66651184/116301638-21705200-a755-11eb-9c0f-4802c35d3009.png)

These are the properties logged by `ApplicationInsightsLogger`:

"CategoryName":"AppInsightsScopeTest.TestApplication",
**"{OriginalFormat}"**:"TestScope {ScopeColumn1} and {ScopeColumn2}",
"OriginalFormat":"Test application is starting",
"ScopeColumn2":"5678",
"ScopeColumn1":"1234"

**Describe the solution you'd like.**
There are no curly braces in the key, possibly name it something like `Scope_OriginalFormat` to not replace the `OrginalaFormat` of the log message.

**Describe alternatives you've considered.**
Use a `TelemetryInitializer` to achieve the same

**Additional context.**
Some backends do not allow for keys to have curly braces in them.

**Comment by cijothomas** [comment]
Closed via https://github.com/microsoft/ApplicationInsights-dotnet/pull/2362
