### ISSUE TITLE
ApplicationInsightsLogger losing"{OriginalFormat}" information of outer Scopes when Scopes are a Composite Format String

### ISSUE THREAD

**Issue by utpilla** [microsoft/ApplicationInsights-dotnet#2241]
**Is your feature request related to a problem?**
ApplicationInsightsLogger populates a property named `{OriginalFormat}` when `Scope` is a [Composite Format String](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting#composite-format-string) but only stores the last scope's original format. The outer scope information is lost.

For example, for the following code:

```
using (testLogger.BeginScope("TestScope {ScopeColumn1} and {ScopeColumn2}", 1234, 5678))
            {
                using (testLogger.BeginScope("Inner scope {scopeNum}", 1))
                {
                    testLogger.LogInformation("Testing");
                }
            }
```

These are the properties logged by `ApplicationInsightsLogger`:

"CategoryName":"AppInsightsScopeTest.TestApplication",
**"{OriginalFormat}"**:"Inner scope {scopeNum}",  <-- This only has the inner most scope's formatted string information
"OriginalFormat":"Testing",
"ScopeColumn2":"5678",
"ScopeColumn1":"1234"
"scopeNum":"1"

**Describe the solution you'd like.**
Information about each scope's formatted string is retained. Something like this:
`"{OriginalFormat}":"=> TestScope {ScopeColumn1} and {ScopeColumn2} => Inner scope {scopeNum}"`

Or have one `{OriginalFormat}` key for each of the scopes that have a composite format string prefixed with `=>` to signify the depth of the scope. For example,

```
" => {OriginalFormat}":"TestScope {ScopeColumn1} and {ScopeColumn2}"
"=> => {OriginalFormat}":"Inner scope {scopeNum}"
```

**Describe alternatives you've considered.**
N/A

**Additional context.**
N/A

**Comment by cijothomas** [comment]
using (testLogger.BeginScope("TestScope {mytestcolumn} and {ScopeColumn2}", 1234, 5678))
            {
                using (testLogger.BeginScope("Inner scope {scopeNum}", 1))
                {
                    testLogger.LogInformation("Testing {mytestcolumn}", mycolumnvalue);
                }
            }


The similar issue (of overwriting) exists even for properties from Log statement as well.

**Comment by cijothomas** [comment]
For every property obtained from Scope, we might prefix with scopeN (where N is scope depth), to avoid this overwrites.
```
if (this.ExternalScopeProvider != null)
                {
                    StringBuilder stringBuilder = new StringBuilder();
                    int scopeDepth = 0;
                    this.ExternalScopeProvider.ForEachScope(
                        (activeScope, builder) =>
                        {
                            // Ideally we expect that the scope to implement IReadOnlyList<KeyValuePair<string, object>>.
                            // But this is not guaranteed as user can call BeginScope and pass anything. Hence
                            // we try to resolve the scope as Dictionary and if we fail, we just serialize the object and add it.

                            if (activeScope is IReadOnlyCollection<KeyValuePair<string, object>> activeScopeDictionary)
                            {
                                foreach (KeyValuePair<string, object> item in activeScopeDictionary)
                                {
                                    if (item.Key == "{OriginalFormat}")
                                    {
                                        dict[$"scope{scopeDepth}OriginalFormat"] = Convert.ToString(item.Value, CultureInfo.InvariantCulture);
                                    }
                                    else
                                    {
                                        dict[$"scope{scopeDepth}{item.Key}"] = Convert.ToString(item.Value, CultureInfo.InvariantCulture);
                                    }
                                }
                            }
                            else
                            {
                                builder.Append(" => ").Append(activeScope);
                            }

                            scopeDepth++;
                        },
                        stringBuilder);

                    if (stringBuilder.Length > 0)
                    {
                        dict["Scope"] = stringBuilder.ToString();
                    }
                }
```
