### ISSUE TITLE
End of Life for .NET Core 2.1 (August 21, 2021)

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#2251]
## .NET Core 2.1 is officially scheduled to reach end of life on [August 21, 2021](https://dotnet.microsoft.com/platform/support/policy/dotnet-core#:~:text=august%2021%2C%202021)

- Official Statement: https://dotnet.microsoft.com/platform/support/policy/dotnet-core

Using this Issue to track planned changes.

- [x] Remove this framework from all projects
- [x] Remove this framework from all build definitions
- [x] Individual package references should be replaced with framework references wherever possible. (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-5.0&tabs=visual-studio)
    - [x] `WindowsServer.Tests.csproj`: 
     `AzureInstanceMetadataEndToEndTests` depends on `AzureInstanceMetadataServiceMock` which creates an in-proc server to handle HTTP requests. 
     This is being addressed in a separate issue #2357 
    - [ ] `Microsoft.ApplicationInsights.AspNetCore.Tests.csproj`
    See also: https://weblog.west-wind.com/posts/2020/Feb/26/Working-with-IWebHostEnvironment-and-IHostingEnvironment-in-dual-targeted-NET-Core-Projects
    > 'IHostingEnvironment' is obsolete: 'This type is obsolete and will be removed in a future version. 
         The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.'
         
- [ ] Consolidate extra dependencies in AspNetCore taken to address security issue: #2199 #2243
- [x] Verify all projects have test coverage for all supported versions of dotnet.
  This is being addressed in a separate issue #2379
- [ ] Update changelog

**Comment by HamsterExAstris** [comment]
Just to make sure I understand: is this issue only deprecating the .NET Core 2.1 _runtime_, or was support for ASP.NET Core 2.1 on the .NET Framework runtime (which is [still under support](https://dotnet.microsoft.com/platform/support/policy/aspnet#dotnet-core)) dropped too?
