### ISSUE TITLE
Retrieve information from App Insights programmatically

### ISSUE THREAD

**Issue by ssghoda** [microsoft/ApplicationInsights-dotnet#2256]
We are sending service requests, trace logs, exceptions to App Insights using .NET SDK.

Currently, the only way to visualize this App Insights information is by transforming it using Power BI into dashboards.
Is there a way to write a C# program and retrieve that information from App Insights programmatically such as retrieving service requests, trace logs, or exceptions of past 7 days, past month, past 3 months or so?

**Comment by cijothomas** [comment]
https://dev.applicationinsights.io/quickstart
