### ISSUE TITLE
Offline storage of ServerTelemetryChannel never used 

### ISSUE THREAD

**Issue by bklooste** [Microsoft/ApplicationInsights-dotnet#227]
Console app

            var channel = new ServerTelemetryChannel();
            channel.DeveloperMode = true;
            channel.StorageFolder = @"C:\src\AppInsights";
            channel.MaxTelemetryBufferCapacity = 2; // no memory
            channel.MaxTransmissionStorageCapacity = 100000;
            channel.MaxTransmissionBufferCapacity = 1000; 
            channel.Initialize(TelemetryConfiguration.Active);

            TelemetryConfiguration.Active.TelemetryChannel = channel;
            TelemetryConfiguration.Active.InstrumentationKey = "xyz";
            TelemetryConfiguration.Active.TelemetryChannel.DeveloperMode = true;

           var assemblyName = System.Reflection.Assembly.GetExecutingAssembly().GetName();
            telemetry = new TelemetryClient(config);
            telemetry.Context.User.Id = Environment.UserName;
            telemetry.Context.Session.Id = Guid.NewGuid().ToString();
            telemetry.Context.Device.OperatingSystem = Environment.OSVersion.ToString();
            telemetry.Context.Component.Version = assemblyName.Version.ToString();
            telemetry.Context.Properties["Application"] = assemblyName.Name;

        for (;;)
            {
                telemetry.TrackEvent(new EventTelemetry
                {
                    Name = "Button1Clicked",
                    Timestamp = DateTime.UtcNow,

                });
                Thread.Sleep(4000);
           }

Pull out cable and no files created  , I have debugged as well.

**Comment by abaranch** [comment]
Thank you for reporting the issue. We will investigate.

**Comment by abaranch** [comment]
@bklooste Could you please either use correct iKey and check that you do not have any failures in the portal or collect verbose traces and check that you do not have failures there. [Instructions](http://apmtips.com/blog/2015/11/07/application-insights-self-diagnostic/) 
Does your application has access to  "C:\src\AppInsights"?

**Comment by bklooste** [comment]
Key is correct ( just did not want to publish here) and it does upload from sender/ buffer.  With a breakpoint i see no writes . However changing the right on the folder to Everyone rather than the default  all logged in users does appear to create files ( i would have thought for console all logged in users should be sufficient) .. Will investigate more.. Note no Insight errors  on earlier fail

**Comment by kartang** [comment]
Glad that it permissions fixed the problem. Thank you for reporting the issue.
