### ISSUE TITLE
ServerTelemetryChannel Initialize ignores configuration

### ISSUE THREAD

**Issue by bklooste** [Microsoft/ApplicationInsights-dotnet#228]
ServerTelemetryChannel Initialize ignores configuration

**Comment by abaranch** [comment]
Could you please provide more information in the issue?

**Comment by bklooste** [comment]
Initialize Method on ServerTelemetryChannel in current source branch ignores TelemetryConfiguration param

**Comment by abaranch** [comment]
We do not need TelemetryConfiguration object. The only thing that we need is Initialize the instance after all properties are set. It is intended.
