### ISSUE TITLE
Console application with WorkerServiceSDK does not log information level

### ISSUE THREAD

**Issue by elias-rod** [microsoft/ApplicationInsights-dotnet#2283]
DESCRIPTION
A NET 5 console application with DI is not logging information level logs. The appsettings.json file has the following configuration:
```
{
  "ApplicationInsights": {
    "InstrumentationKey": ""
  },
  "Logging": {
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Information"
      }
    },
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}
```

Startup.cs>ConfigureServices
```
services.AddLogging();
services.AddApplicationInsightsTelemetryWorkerService();
```
REPRO PROJECT
Using [your example solution](https://github.com/microsoft/ApplicationInsights-dotnet/tree/develop/examples/WorkerServiceSDK/ConsoleAppWithApplicationInsights) and adding (according to [your documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#net-corenet-framework-console-application)) any of the filters from below does not log information level logs.

`services.AddLogging(loggingBuilder => loggingBuilder.AddFilter<Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider>("Category", LogLevel.Information));`
nor
`services.AddLogging(loggingBuilder => loggingBuilder.AddFilter<Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider>("ApplicationInsights", LogLevel.Information));`

**Comment by cijothomas** [comment]
Are you having a console application, or a .NET WorkerService application? For console app, there is no appsettings.json from which settings are parsed.

The following line is configuring to capture logs if Information level or above, and with the name "Category". Are you logging using category as "Category" ?

```
services.AddLogging(loggingBuilder => loggingBuilder.AddFilter<Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider>("Category", LogLevel.Information));
```

Please share minimal repro app so we can help.

**Comment by elias-rod** [comment]
I'm sorry to read that, the repro project I shared is a console app indeed:
![image](https://user-images.githubusercontent.com/12984787/119807027-1fff8a00-beb9-11eb-85a1-b1838fcb6075.png)

Anyway, I have forked your project and modified it according to [your documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#net-corenet-framework-console-application), you just need to put you Azure Application Insights key: https://github.com/elias-rod/ApplicationInsights-dotnet/tree/develop/examples/WorkerServiceSDK/ConsoleAppWithApplicationInsights

It's not logging information logs, IT IS ONLY logging warning logs.

**Comment by cijothomas** [comment]
https://github.com/elias-rod/ApplicationInsights-dotnet/blob/develop/examples/WorkerServiceSDK/ConsoleAppWithApplicationInsights/ConsoleAppWithApplicationInsights/Program.cs#L51 -- the logger in this line has a category of Program. I dont see logging config modified to pick Informational logs of that category. Or you can set Information from all categories as well 
```
builder.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.Information);
```

**Comment by elias-rod** [comment]
Great! So it seems that the category is tied to a class and an empty string works like a wildcard. It looks to me as a very different configuration way compared to other Application Insights setups. I wonder why none of the following worked though:

1. Removing the generic "ApplicationInsightsLoggerProvider"
2. Using builder.SetMinimumLevel(LogLevel.Information)
3. Passing an IConfiguration to the AddApplicationInsightsTelemetryWorkerService overload using the appsettings.json from above (this last one was attempted in another simple console project with a working custom DI)

Just for curiosity, is there any alternative way of making this work in a console app?

**Comment by cijothomas** [comment]
For ILogger, ApplicationInsights SDK does not do any filter. Everything is done by the ILogger infra itself, and this is same for all LoggingProviders.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#control-logging-level
