### ISSUE TITLE
Duplicate custom events with same timestamp but different ingestion time in Application Insights

### ISSUE THREAD

**Issue by VaishaliGanesh** [microsoft/ApplicationInsights-dotnet#2304]
Hello,

I have created a custom events in Application Insights for tracking. However, I found few events are duplicated with the same timestamp and operation ID but only the ingestion time differs. It seems there could be some intermittent issues on the ingestion of ApplicationInsights that create this duplication. But it does not seem to be constant and is related to specific incidents.

Please let me know to resolve this issue.

Thanks in advance.

**Comment by cijothomas** [comment]
Its quite possible if ingestion takes a long time to respond (100sec or more). In that case, sdk assumes data is lost, and retries. If ingestion does succeeds, it'll result in duplicates.

(also its possible that duplicates can occur purely in the backend as well)

**Comment by cijothomas** [comment]
> Please let me know to resolve this issue.

Given this is not something you are causing, i don't think you can do anything in the sdk.
