### ISSUE TITLE
Make MaxDimensionsCount configurable

### ISSUE THREAD

**Issue by RcRonco** [microsoft/ApplicationInsights-dotnet#2307]
**Is your feature request related to a problem?**
We use Application insights in our app and we need support for up to 15 dimensions

**Describe the solution you'd like.**
What do you want to happen instead? What is the expected behavior?
Raise the maximum dims or make it configurable to override this behavior

**Describe alternatives you've considered.**
Which alternative solutions or features have you considered?

**Additional context.**
Add any other context about the feature request here.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Metrics/MetricIdentifier.cs#L15

**Comment by cijothomas** [comment]
This limitation is not a artificial limit imposed by the SDK, but is a limitation of the backend. So unless backend supports more, this SDK cannot do anything.
