### ISSUE TITLE
Skipping client_City and client_StateOrProvince from AppInsights events

### ISSUE THREAD

**Issue by matkoch** [microsoft/ApplicationInsights-dotnet#2308]
**What are you trying to achieve?**

I'm using ApplicationInsights inside a console application. Currently, I'm setting `s_client.Context.Location.Ip` to `N/A` to avoid the resolution of geographic information. Particularly, `client_City` and `client_StateOrProvince` might be an issue due to GDPR. It would be great if I could just get `client_Country`, but I don't know how.

**What have you tried so far?**

I've tried setting the properties manually, but they'll only appear under `customDimensions`.

**Comment by developerMCSI** [comment]
I have the same problem.
Client side (UI JS) I can override the values as shown in [https://github.com/microsoft/ApplicationInsights-JS/issues/1360#issuecomment-686662388]

Server side I can't set the same attributes.
They are not public properties.

How can we do?
