### ISSUE TITLE
FileLoadException: Could not load file or assembly 'System.Memory

### ISSUE THREAD

**Issue by yadavsachin** [microsoft/ApplicationInsights-dotnet#2309]
Getting this exception.

FileLoadException: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

I have added below tag in app.config
```
<dependentAssembly>
        <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1"/>
 </dependentAssembly>
 ```

**Comment by TimothyMothra** [comment]
Hi @yadavsachin , not enough information to investigate.
Can you share a minimal repro application that reproduces this?
