### ISSUE TITLE
AI.Web 2.0.0 is incompatible with AI 2.0.1

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/ApplicationInsights-dotnet#231]
I'm constantly being notified by NuGet about an update for AI, from 2.0.0 to 2.0.1.
However, I'm unable to update my ASP.NET app since it also uses AI.Web 2.0.0 which has dependency on AI.WindowsServer which has very strict dependency on AI = 2.0.0.
Is it by design? Are there plans to address/relax this?

**Comment by AlexBulankou** [comment]
@abatishchev thanks for bringing this up! We are painfully aware of this issue. 2.0.1 was introduced to resolve the issue that is specific to now retired device SDK and is not intended for Web scenarios. Please ignore 2.0.1 if you are only looking to upgrade to stable SDKs.
 However if you would like to try an Beta version, we are encouraging all customers to upgrade to 2.1.0-beta4 (https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/2.1.0-beta4) which is effectively our 2.1 release candidate. In a few weeks we are planning 2.1 stable release that will replace 2.0 and 2.0.1, so the issue you are describing will be resolved then.

**Comment by abatishchev** [comment]
Hi Alex, thanks for the explanation!
My main goal was to make sure the team is aware. I think my team can wait few more weeks and will update to the stable version.
Thanks again,
Alex
MPSIT Engineering
