### ISSUE TITLE
Configure an custom IIS User for tracking performance data on premises

### ISSUE THREAD

**Issue by Robert-Zandberg** [microsoft/ApplicationInsights-dotnet#2321]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
* Microsoft.ApplicationInsights - V2.15.0
* Microsoft.ApplicationInsights.DependencyCollector - V2.15.0
* Microsoft.ApplicationInsights.WindowsServer - V2.15.0
* Microsoft.ApplicationInsights.PerfCounterCollector - V2.15.0
* Microsoft.ApplicationInsights.Web - V2.15.0
* Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel - V2.15.0
* Hosting environment: VM Azure -  Windows (Windows Server 2019 Datacenter) - IIS 
* ASP.NET 4.6.1

Hi All,

I would like to add a custom IIS user for tracking the performance measurements. For security reasons we don't want to give the IIS_IUSER group rights for our sites. I hope that there's some kind of configuration that I can do in the ApplicationInsights.config file.

At the moment, we can't track any performance data for our sites running on a on premises server.

Hope there's already an solution or there 👍

**Comment by cijothomas** [comment]
There is no configuration in ApplicationInsights for changing/adding IIS users. If the process has permission to read perf counters, then applicationinsights sdk, which is part of user process, will be able to read the counters.
