### ISSUE TITLE
Proposal: Allow Self-Diagnostic to collect additional event source.

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#2326]
## Propasol
Add optional configuration to Self-Diagnostics to collect logs from additional event sources.

## Remarks
This is to address an issue I've discovered with AAD.
If Authentication fails, customers will first assume something is wrong with the AI SDK.
After collecting logs, we can discover exceptions thrown from the Azure.Identity library.
We would then need to work with the customer to collect new logs from the Azure.Identity library.
This workflow can by simplified if the Self-Diagnostic feature can be extended to collect additional logs from other event sources.

## Current config:
```
{
  "LogDirectory": ".",
  "FileSize": 1024,
  "LogLevel": "Warning"
}
```

## Option 1
Add a new json setting: `"CollectAzureEventSource": "true"`.
When enabled, this will copy the implementation from here: https://github.com/Azure/azure-sdk-for-net/blob/fd17302049ab45c87f2b8524e4b5046db8cc856c/sdk/core/Azure.Core/src/Diagnostics/AzureEventSourceListener.cs#L61-L64

Pros:
- simple to implement

Cons:
- changes in the Azure.Core or Azure.Identity libraries would necessitate changes in our sdk.

## Option 2
Add a generic config to specify exact EventSourceNames or EventSourceTraitName/Value pairs.

```
"AdditionalEventSources": [
    {
        name: "<NAME>"
    },
    {
        traitName: "<NAME>"
        traitValue: "<VALUE>"
    }
]
```

Pros:
- enables us to collect logs in future scenarios

**Comment by TimothyMothra** [comment]
Pinging @xiang17 @cijothomas @rajkumar-rangaraj @reyang for comment.

**Comment by reyang** [comment]
What I think we need to do: log our own error and give clue about what could be wrong.
The Azure.Identity troubleshooting should be covered by Azure.Identity, not another SDK.
