### ISSUE TITLE
How to make each web job in an app service to appear with its own name on the Application Map 

### ISSUE THREAD

**Issue by andriysavin** [microsoft/ApplicationInsights-dotnet#2335]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights.WorkerService Version="2.17.0"
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
Net 5.0

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
 Azure Web App (WebJobs)

**What are you trying to achieve?**
I have a web app service dedicated for running web jobs. The web jobs are mainly plain console apps (not using WebJobs SDK), which run periodically. They all use the same AI instance. They communicate with other services and databases, and those dependencies are tracked correctly. However, on the Application map all web jobs are shown as a single apllication with the name of the hosting app service. The same is true for any other places where dependency tracking is used, e.g. when trying to understand where an error originates from on the Failures blade I have to dive into call stacks to figure out which web job failed in some particular case. So what I would like to have is a way to hint the AI client that it represents not a whole app service, but a particular application with its own name. Note that I'm not using AI explicitly (e.g. I don't instantiate any types from AI SDK, I'm just adding automatic tracking using `AddApplicationInsightsTelemetryWorkerService`).

**What have you tried so far?**
Nothing

**Comment by cijothomas** [comment]
see if this helps: https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-map?tabs=net#set-or-override-cloud-role-name

**Comment by andriysavin** [comment]
@cijothomas That helped, thanks a lot!
