### ISSUE TITLE
Schema for Appinsight data model needs to be updated

### ISSUE THREAD

**Issue by mrkuntal** [microsoft/ApplicationInsights-dotnet#2352]
**Is this a document under https://docs.microsoft.com/en-us/azure/azure-monitor/**
If yes, [file issue against the document repo](https://github.com/MicrosoftDocs/azure-docs/issues/new).

**Does the document belong to this repo?**
If yes, please describe the issue and what you expect to see.
![image](https://user-images.githubusercontent.com/83991386/128178643-bcec0bf0-07ef-43ac-8509-daf64fbe0863.png)
The documentation is not updated as per the schema

**Comment by cijothomas** [comment]
Could you clarify which documentation is being referred to?
