### ISSUE TITLE
When logging from within a nested operation the log's message "Operation Name" is set to top level operation name

### ISSUE THREAD

**Issue by elimarkov** [microsoft/ApplicationInsights-dotnet#2366]
Microsoft.ApplicationInsights.WorkerService 2.18.0
Microsoft.Extensions.Logging.ApplicationInsights 2.18.0
Microsoft.Extensions.Hosting 5.0.0
Microsoft.Extensions.Hosting.WindowsServices 5.0.1

Runtime=.NET 5.0.8 (5.0.821.31504)

This is the only code needed (I used LinqPad)

```
using (IOperationHolder<RequestTelemetry> topHolder = telemetryClient.StartOperation<RequestTelemetry>("TopOperation1"))
{
	logger.LogWarning("top holder log 1");

	using (IOperationHolder<RequestTelemetry> innerHolder = telemetryClient.StartOperation<RequestTelemetry>("InnerOperation1"))
	{
		logger.LogWarning("inner holder log 1");
	}
}
```

Log message in App Insights:

![image](https://user-images.githubusercontent.com/6180805/129347837-1bf530cd-c4ab-4471-b73d-37ea47e653f7.png)

**Comment by steviecurtis** [comment]
According to https://learn.microsoft.com/en-us/azure/azure-monitor/profiler/profiler-trackrequests "Calling StartOperation<RequestTelemetry> within another StartOperation<RequestTelemetry> scope isn't supported. You can use StartOperation<DependencyTelemetry> in the nested scope instead. "
