### ISSUE TITLE
The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by winseros** [microsoft/ApplicationInsights-dotnet#2368]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: 
   * Microsoft.ApplicationInsights.AspNetCore:2.17.0 
   * Microsoft.ApplicationInsights.WorkerService:2.17.0
* Runtime version: net5.0

### Describe the bug

Both packages _Microsoft.ApplicationInsights.AspNetCore_ and _Microsoft.ApplicationInsights.WorkerService_ use the same namespace for their extension methods with the same extension methods names. That causes build errors when your code has to reference both packages.

[Microsoft.ApplicationInsights.WorkerService/ApplicationInsightsExtensions.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/91e1217eaeca1052e389f68c00a6b7ec6882b752/NETCORE/src/Microsoft.ApplicationInsights.WorkerService/ApplicationInsightsExtensions.cs)

[Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/91e1217eaeca1052e389f68c00a6b7ec6882b752/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs)

### To Reproduce

1. Create a project
2. Reference both packagages: _Microsoft.ApplicationInsights.AspNetCore_ and _Microsoft.ApplicationInsights.WorkerService_
3. Try to configure ApplicationInsights, e.g. `services.AddApplicationInsightsTelemetryProcessor<T>();`
4. Receive the build error: 
    ```
    Error CS0121 : The call is ambiguous between the following methods or properties: 'Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetryProcessor<T>(Microsoft.Extensions.DependencyInjection.IServiceCollection)' and 'Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetryProcessor<T>(Microsoft.Extensions.DependencyInjection.IServiceCollection)'
   ```

**Comment by cijothomas** [comment]
These packages are intended for usage in different types of workloads, and are not designed to be used in the same project. Could you elaborate on the need for having *both* of these in the same project?

**Comment by winseros** [comment]
It is a single executable that can work either as a web application or as a background app. Depending on the command line passed.

**Comment by ltouro** [comment]
Came accross the same problem. One executable that has two threads: one for background work and other for an API.

**Comment by siewers** [comment]
I honestly think this issue should be reopened. It's a rather odd design choice to not allow different assemblies to be used in the same project without namespace conflicts. 
The only workaround I've found is to alias the assemblies and the create an extern alias.
This, however, shouldn't be necessary, but since the SDK code is littered with preprocessor directives, I can only assume this was a deliberate design choice.
I would have preferred a core package with shared logic and the a specialized packages for each workload, in different namespaces.

**Comment by filipreft** [comment]
@siewers please share how u solved this in code.

**Comment by siewers** [comment]
I ended up solving it by creating two separate projects, but the solution I mentioned above was as follows:
Add NuGet package references to both the WorkerService and AspNetCore ApplicationInsights SDKs and add an alias to each package, like this:
```xml
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" Aliases="AIAspNetCore" />
<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" Aliases="AIWorkerService" />
```
(The actual alias you use doesn't matter as long as it's unique)

Now, when you need to use either package, you'd have to do something like this:
```cs
// In a file that uses AspNetCore
extern alias AIAspNetCore;
using AIAspNetCore::The.Namespace.From.ApplicationInsightsAspNetCore.Package;
using SomeType = AIAspNetCore::You.Get.The.Point;
```

For another file that needs to use the WorkerService assembly, use `extern alias AIWorkerService` at the top instead.

Now, I haven't actually tested this, but theoretically it should work and the entire concept about using `extern alias` is to solve this exact issue: Two different assemblies sharing the same fully-qualified type names.

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias

I hope it helps.

**Comment by filipreft** [comment]
@siewers Thanks alot! It works perfectly in my class library. Big thanks.
