### ISSUE TITLE
Xamarin Forms Android fails due to AppDomain.CurrentDomain.BaseDirectory

### ISSUE THREAD

**Issue by jmichas** [microsoft/ApplicationInsights-dotnet#2373]
### Describe the bug
When using Microsoft.ApplicationInsights 2.12.0 on Xamarin Forms Android with Serilog.Sinks.ApplicationInsights configuring a Sink fails because on line 58 in file  https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Platform/PlatformImplementation.cs
there is this:
`configFilePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ApplicationInsights.config");`
`AppDomain.CurrentDomain.BaseDirectory` is null on Android.
I guess the Android project does not get caught in the `#if NETSTANDARD` on line 40 so when the read xml code runs it fails.

Probably could either add a catch for the exception thrown if path1 on `Path.Combine` is null or change the `#if` to include Android projects.

### To Reproduce

Create a self-contained project using the template of your choice, apply the minimum required code to result in the issue you're observing.

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
* If we will not be able to repro the behavior you're reporting

### For Immediate Support

For immediate support relating to the Application Insights .NET SDK we encourage you to file an [Azure Support Request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) with Microsoft Azure instead of filing a GitHub Issue in this repository. 
You can do so by going online to the [Azure portal](https://portal.azure.com/) and submitting a support request. Access to subscription management and billing support is included with your Microsoft Azure subscription, and technical support is provided through one of the [Azure Support Plans](https://azure.microsoft.com/support/plans/). For step-by-step guidance for the Azure portal, see [How to create an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). Alternatively, you can create and manage your support tickets programmatically using the [Azure Support ticket REST API](https://docs.microsoft.com/rest/api/support/)

**Comment by lafritay** [comment]
Making things worse, this continues to fire every 10 seconds or so which makes debugging Android projects nearly impossible.
