### ISSUE TITLE
Logic App workflow not linked to Application Insights

### ISSUE THREAD

**Issue by esyker** [microsoft/ApplicationInsights-dotnet#2374]
I am trying to create an azure application insights action group with a Logic app.
The idea is to link the action group to an alert so that users are notified through a Microsoft Teams Channel, as explained in this link: [https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/azure-monitor-alert-notification-via-teams/ba-p/2507676](https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/azure-monitor-alert-notification-via-teams/ba-p/2507676).

I am having troubles in adding the Logic App to an action group.

When selecting an action in the action group, the Logic App does not appear as a Logic App but as an Azure Function App and in the Azure function parameter the workflow does not appear.

See in this image that the Logic App does not appear as a Logic App, but as an Azure function. However, the workflow "testTC" does not appear in "TCedocDiogo", so I can't select the workflow I created.
![Screenshot (12)](https://user-images.githubusercontent.com/50277636/130329523-1571641f-37ce-40c4-8171-13f50cfbd5ab.png)

In this image, check that the logic app does not appear as a logic app (it appears as an Azure function like in the previous image):
![Screenshot (13)](https://user-images.githubusercontent.com/50277636/130329546-18f709eb-1424-48f5-a906-b564a1ab8e5c.png)

However the logic app is correctly configured and in the resource group.
See these images:
![Screenshot (14)](https://user-images.githubusercontent.com/50277636/130329573-20f26a43-4f3e-46cf-94d3-e5cd604ed87c.png)
![Screenshot (15)](https://user-images.githubusercontent.com/50277636/130329576-0586dfa8-062a-4480-bc3c-c5686f1cd94a.png)
![Screenshot (16)](https://user-images.githubusercontent.com/50277636/130329579-ff565f99-7828-41e8-9366-2a50fd2da0b9.png)

Am I doing something wrong or is this a bug of the Logic Apps (2.something out of 5 score)?
The workflow "testTC" of the Logic App "TCedocDiogo" does not appear in the action group drop down menu.
All the resources are deployed on the same location and resource group so this is not the problem as well.
It also says in the dropdown menu that only functions with Http Trigger are displayed, which is the case. My workflow starts with an HttpTrigger.

**Comment by esyker** [comment]
Can anyone try to replicate the behaviour.
You should use an http trigher in the workflow.
This is totally unexpected that it does not appear the workflow in the available options on the action group and is a serious bug.

**Comment by cijothomas** [comment]
@esyker this repo is for questions about the application insights .NET Sdks. It looks like you have a question about general application insights. This is not the right forum for that.

Please open the issue against the docs pages, based on whichever doc you are following.

**Comment by esyker** [comment]
Just for future reference, if anyone has the same problem, I was able to call the logic app workflow by calling it as a WEB hook, using the URL provided in the Logic APP as the webhook.

**Comment by JasonDWilson** [comment]
I was able to call a function from an Action Group so that might be a good alternative.

![image](https://user-images.githubusercontent.com/57236874/232902004-b0320eb7-ab9c-4566-850d-7977da63d859.png)
