### ISSUE TITLE
EventCounters in ASP.NET framework 4.8

### ISSUE THREAD

**Issue by esyker** [microsoft/ApplicationInsights-dotnet#2375]
Are Event Counters only available for ASP.NET core and not for ASP.NET framework?

[https://docs.microsoft.com/pt-pt/azure/azure-monitor/app/eventcounters](https://docs.microsoft.com/pt-pt/azure/azure-monitor/app/eventcounters)

Couldn't find any documentation for ASP.NET framework, in my case 4.8.

This is also what seems from the github repo documentation:

[https://github.com/Microsoft/ApplicationInsights-dotnet](https://github.com/Microsoft/ApplicationInsights-dotnet)

**Comment by cijothomas** [comment]
The package is netstandard2.0, so you can use it in .NET core and .NET framework.

**Comment by esyker** [comment]
Yes I know I can use these classes in the SDK, but how do I configure the services to use the EventCountCollector, since there is no ConfigureServices function in ASP.NET? No example from the documentation [https://docs.microsoft.com/pt-pt/azure/azure-monitor/app/eventcounters](https://docs.microsoft.com/pt-pt/azure/azure-monitor/app/eventcounters).

Also I checked that you cant configure dependency injection (configure services in ASP.NET):
[https://stackoverflow.com/questions/45222923/asp-net-classic-owin-startup-configureservices-not-called ](https://stackoverflow.com/questions/45222923/asp-net-classic-owin-startup-configureservices-not-called ).

I tried calling the EventCountCollector and initialize with the current configuration in the Utilities Class. 

`
namespace Utilities
{
    public class AppInsightsTelemetry
    {
        private static Microsoft.ApplicationInsights.Extensibility.EventCounterCollector.EventCounterCollectionModule
                            collector = new Microsoft.ApplicationInsights.Extensibility.EventCounterCollector.EventCounterCollectionModule();
        
        static AppInsightsTelemetry()
        {
            collector.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active);
        }

        public static void EventCounterCollector(string eventSourceName, string eventCounterName)
        {
            collector.Counters.Add(new EventCounterCollectionRequest(eventSourceName, eventCounterName));
        }
    }

}
`

Then in Global.asx.cs, in Application_Start I tried to configure the EventCountCollector, calling the utilities function.

`
        void Application_Start(object sender, EventArgs e)
        {
            Utilities.AppInsightsTelemetry.EventCounterCollector("Clicked button", "Clicked button Count");
        }
`

However this approach did not work.
Can you help me with this one please? Provide a link if possible for documentation on how to configure the services in ASP.NET framework, since I can only find documentation for ASP.NET core.

**Comment by cijothomas** [comment]
Please try the below:
```
var eventCounterModule = new EventCounterCollectionModule();
eventCounterModule.Counters.Add(new EventCounterCollectionRequest("MyEventSource", "MyCounter")); // keep adding all your counters
eventCounterModule.Initialize(TelemetryCofiguration.Active);
```

(I assume you have already setup ikey,channel etc to TelemetryConfiguration.Active)

**Comment by esyker** [comment]
So I have done this inside Global.asax.cs Application_Start function and it does not work. All the other metrics are tracked correctly but no EventCounter metric appears.

`
protected void btnSubmit_Click(object sender, EventArgs e)
        {
            Utilities.AppInsightsTelemetry.TrackEvent("Clicked button", new Dictionary<string, string> { { "BtnType", "Contact" } },
                null);
}
`

`
        void Application_Start(object sender, EventArgs e)
        {
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            RouteTable.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = System.Web.Http.RouteParameter.Optional }
            );
            Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active.InstrumentationKey = INSTRUMENTATION_KEY;
            Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active.ConnectionString = CONNECTION_STRING;

            Microsoft.ApplicationInsights.Extensibility.EventCounterCollector.EventCounterCollectionModule
                            collector = new Microsoft.ApplicationInsights.Extensibility.EventCounterCollector.EventCounterCollectionModule();
            collector.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active);
            collector.Counters.Add(new Microsoft.ApplicationInsights.Extensibility.EventCounterCollector.EventCounterCollectionRequest("Clicked button", "Clicked button count"));

        }
`

**Comment by cijothomas** [comment]
> I think I need to attach this to the service, like in the ASP.NET core syntax, isn't it? 

No.
There are plenty of unittests on it, which has working sample codes:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/EventCounterCollector/EventCounterCollector.Tests/EventCounterCollectionModuleTests.cs

**Comment by esyker** [comment]
I have everything correctly configured. All the other events both client-side and server-side appear (requests, pageViews, exceptions, traces) appear. When I make an event of type "Clicked button" no metric of type "Clicked button count" appears in customMetrics. However the "Clicked button" event appears in customEvents.

Do I have to define a metric in another way? 
I tried to make the configuration you said (I had already done before you said it) inside Application_Start and inside the buttonSubmit_Click event.
Neither of these approaches work.
I have checked in run time inside Application_Start with the debugger and both instrumentation key and channel are properly set. Additionally, if this wasn't enough, I initialized the collector inside btnSubmit_onClick function, in case there was an error in doing it inside Application_Start because Application Insights haven't already started or something out of my scope. 

Is it because I need to manually add a line to add EventCounterCollectors to ApplicationInsights.config? I think when I had the module through nugget package the configuration line with EventCounterCollector should be added. Nevertheless, I only see a line concerning PerfCollectors.

Check my configuration file:

```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
  <TelemetryModules>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector">
      <!--
      Use the following syntax here to collect additional performance counters:
      
      <Counters>
        <Add PerformanceCounter="\Process(??APP_WIN32_PROC??)\Handle Count" ReportAs="Process handle count" />
        ...
      </Counters>
      
      PerformanceCounter must be either \CategoryName(InstanceName)\CounterName or \CategoryName\CounterName
      
      NOTE: performance counters configuration will be lost upon NuGet upgrade.
      
      The following placeholders are supported as InstanceName:
        ??APP_WIN32_PROC?? - instance name of the application process  for Win32 counters.
        ??APP_W3SVC_PROC?? - instance name of the application IIS worker process for IIS/ASP.NET counters.
        ??APP_CLR_PROC?? - instance name of the application CLR process for .NET counters.
      -->
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule, Microsoft.AI.PerfCounterCollector" />
  </TelemetryModules>
  <TelemetrySinks>
    <Add Name="default">
      <TelemetryProcessors>
        <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor, Microsoft.AI.PerfCounterCollector" />
      </TelemetryProcessors>
    </Add>
  </TelemetrySinks>
</ApplicationInsights>
```

**Comment by esyker** [comment]
@cijothomas You can try it yourself. Change the instrumentation key for one of yours and see with your eyes:

[https://dev.azure.com/linkestagiodiogomoura/SampleWebAppTransfer](https://dev.azure.com/linkestagiodiogomoura/SampleWebAppTransfer)

**Comment by esyker** [comment]
Guess there is a way to configure EventCounterCollectors as for PerformanceCounterCollectors through the .config file. There is no documentation for that however, so I am going to replicate the syntax from here:


```
<Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector">
      <Counters>
        <Add PerformanceCounter="\Objects\Processes"/>
        <Add PerformanceCounter="\Sales(photo)\# Items Sold" ReportAs="Photo sales"/>
      </Counters>
    </Add>
```

**Comment by esyker** [comment]
Sorry to inportunate you, but maybe I made a mistake.
Now that I setup the PerfCountCollectors ( which are not working for some random reason), I realized thay probably the EvenCountCollector isn't a collector for customEvents generated for log analytics, but a collector for events generated using EventCounter class, isn't it?
Thanks for your  help,
Diogo
