### ISSUE TITLE
Can not use PersistenceChannel 1.2.3 with AI-core 2.0

### ISSUE THREAD

**Issue by nishy2000** [Microsoft/ApplicationInsights-dotnet#238]
Can not use PersistenceChannel 1.2.3 with AI-core 2.0.
PersistenceChannel constructor is failed. This constructor refers **internal** Microsoft.ApplicationInsights.Channel.TelemetryBuffer class.
AI-core 1.x has exposed this class to PersistenceChannel assembly. But AI-core 2.0 has not exposed.

I think that the following changes have been affected.

commit 51148c7803af92a38791e5c5343f215748835363  @abaranch 
https://github.com/Microsoft/ApplicationInsights-dotnet/commit/51148c7803af92a38791e5c5343f215748835363#diff-864967c9d98e52470149c3d54c787e68

/src/Core/Managed/Shared/Properties/AssemblyInfo.cs
  -[assembly: InternalsVisibleTo("Microsoft.ApplicationInsights.PersistenceChannel" + AssemblyInfo.PublicKey)]

**Comment by abaranch** [comment]
PersistenceChannel  was intended for Devices SDK. After acquisition of HockeyApp new devices SDK development is not happening and there will be no SDK updates.
Pleas read [this](https://azure.microsoft.com/en-us/blog/transitioning-mobile-apps-from-application-insights-to-hockeyapp/) 
You can either switch to HockeyApp or continue using 1.2.3.
