### ISSUE TITLE
Logging Level to Ignore AI Internal Error Messages (100)

### ISSUE THREAD

**Issue by esyker** [microsoft/ApplicationInsights-dotnet#2385]
* Runtime version : ASP.NET framework 4.8

**What are you trying to achieve?**
Trying to ignore internal messages (logging level 0) in ASP.NET 4.8 framework.
Set logging level to 1.

**What have you tried so far?**
I have read the documentation at:
[https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#logging-level](https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#logging-level)

According to this documentation it is possible to set things up in JSON config:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Microsoft": "Error"
      }
    }
  }
}
```

Or in code:
```
Host.CreateDefaultBuilder(args)
    .UseStartup<Startup>()
    .ConfigureLogging(builder =>
    {
        builder.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.Warning);
        builder.AddFilter<ApplicationInsightsLoggerProvider>("Microsoft", LogLevel.Error);
    });
```

However, neither of these approaches work in ASP.NET 4.8 since there ins't this JSON config object and the ServicesConfig function.

**Comment by cijothomas** [comment]
For Asp.Net, follow the non-host model:
https://docs.microsoft.com/dotnet/core/extensions/logging?tabs=command-line#non-host-console-app
