### ISSUE TITLE
EventCounters Logs location traces vs customMetrics

### ISSUE THREAD

**Issue by esyker** [microsoft/ApplicationInsights-dotnet#2394]
**Is this a document under https://docs.microsoft.com/en-us/azure/azure-monitor/**
Yes, [https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters#customizing-counters-to-be-collected](https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters#customizing-counters-to-be-collected).

**Does the document belong to this repo?**
My EventCounters appear as traces in Application Insights, but according to documentation should appear as customMetrics.

Also not sure what is happening but the traces security level seems completely random. I run eventCounters and the severity is "Critical". Then I created another event source and the severity is "Information". Is there even a way to configure these traces severity and other properties through the EventCounters?

**Comment by cijothomas** [comment]
Please share a minimal repro app showing this issue. Also add screenshots where the EventCounters are shown as traces instead of customMetrics.

**Comment by esyker** [comment]
@cijothomas So I discovered this is due to me using the EventSourceListener.
Again, I configured the EventCounter as in the docs [https://docs.microsoft.com/pt-pt/azure/azure-monitor/app/eventcounters](https://docs.microsoft.com/pt-pt/azure/azure-monitor/app/eventcounters):

in Global.asax.cs:
```
void Application_Start(object sender, EventArgs e)
        {
            // Code that runs on application startup
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            WebApplicationHelp.Configs.createEventSource("Sample.EventCounter.Minimal");
            Microsoft.ApplicationInsights.Extensibility.EventCounterCollector.EventCounterCollectionModule
                            collector = new Microsoft.ApplicationInsights.Extensibility.EventCounterCollector.EventCounterCollectionModule();
            collector.Counters.Add(new Microsoft.ApplicationInsights.Extensibility.EventCounterCollector.EventCounterCollectionRequest("Sample.EventCounter.Minimal", "Sample.EventCounter.Minimal Count"));
            collector.Initialize(Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active);
        }
```

Then in the function I created a class according to the provided example [https://docs.microsoft.com/pt-pt/dotnet/core/diagnostics/event-counters#conditional-counters](https://docs.microsoft.com/pt-pt/dotnet/core/diagnostics/event-counters#conditional-counters):

```
namespace WebApplicationHelp
{
    [EventSource(Name = "Sample.EventCounter.Minimal")]
    public sealed class _EventCounter : EventSource
    {
        public static readonly _EventCounter Log = new _EventCounter();

        private System.Diagnostics.Tracing.EventCounter _requestCounter;

        private _EventCounter(){
            _requestCounter = new System.Diagnostics.Tracing.EventCounter("request-time", this);
        }

        public void Request(string url, long elapsedMilliseconds)
        {
            WriteEvent(1, url, elapsedMilliseconds);
            _requestCounter.WriteMetric(elapsedMilliseconds);
        }

        protected override void Dispose(bool disposing)
        {
            Dispose();
            //_requestCounter?.Dispose();
            _requestCounter = null;

            base.Dispose(disposing);
        }
    }
}
```

As you can see inside the Request method, the WriteEvent is a call from the superclass (EventSource) and the _requestCounter.WriteMetric is a call from the EventCounter class.
The WriteMetric call is reported as a Trace in Microsoft Application Insights. The requestCounter.Metric should be reported in the customMetrics, according to the docs. 
However, even though I configured the EventCounter to be reported in Application_Start, by defining the EventSource Name to be collected, nothing appears in Application Insights.
Only the WriteEvent call appears as a trace.

Also in the ApplicationInsights.config file I have the following configuration:
```
<Add Type="Microsoft.ApplicationInsights.EventSourceListener.EventSourceTelemetryModule, Microsoft.ApplicationInsights.EventSourceListener">
      <Sources>
        <!-- Replace/add your own EventSources as necessary. -->
        <Add Name="Sample.EventCounter.Minimal" Level="LogAlways" />
      </Sources>
    </Add>
```
Please note that, before adding the EventSourceListener module [https://www.nuget.org/packages/Microsoft.ApplicationInsights.EventSourceListener](https://www.nuget.org/packages/Microsoft.ApplicationInsights.EventSourceListener), I had just the EventCounterCollector module [https://www.nuget.org/packages/Microsoft.ApplicationInsights.EventCounterCollector/](https://www.nuget.org/packages/Microsoft.ApplicationInsights.EventCounterCollector/).

Isn't the EventCounterCollector module supposed to work like this? Nothing reported to Application Insights, just the EventSourceListener works, but this is not very useful since it shows in Traces.

**Comment by esyker** [comment]
@cijothomas This is the repo of my app in case you want to test it: [https://dev.azure.com/linkestagiodiogomoura/_git/SampleWebAppTransfer?path=%2FWebApplicationHelp](https://dev.azure.com/linkestagiodiogomoura/_git/SampleWebAppTransfer?path=%2FWebApplicationHelp).
Can you test it in 5 minutes and see what I am saying?
That would be much appreciated!
Also, in fact, the issue related to some methods of the EventCounter not working are related to my runtime version. I made a issue on .NET github and it was answered there:
[https://github.com/dotnet/runtime/issues/58408#issuecomment-908818339](https://github.com/dotnet/runtime/issues/58408#issuecomment-908818339).

Please help me with this one! I think I am very near to the solution, but something is missing or maybe this shouldn't be the approach for my runtime version, since all the docs are for .NET Core. Maybe the EventCounter class shouldn't be used for ASP.NET 4.8!

**Comment by esyker** [comment]
UPDATE:

I replicated the Unit Tests provided at:

[https://github.com/microsoft/ApplicationInsights-dotnet/blob/0c5cd658495f78f3b70fd2db6207ba31c702371f/WEB/Src/EventCounterCollector/EventCounterCollector.Tests/EventCounterCollectionModuleTests.cs](https://github.com/microsoft/ApplicationInsights-dotnet/blob/0c5cd658495f78f3b70fd2db6207ba31c702371f/WEB/Src/EventCounterCollector/EventCounterCollector.Tests/EventCounterCollectionModuleTests.cs).

Turns out that maybe it is not even the event source Listener, but really the EventCounter produving those traces, since in this example is really only the EventCounter making the calls.

However, there is something odd happening.
Basically all the Asserts pass but the ones related to the count of the objects (another is commented but I think there is no problem).

I commented this Assert since the class EventCounterCollectorEventSource is internal to System.Diagnostics.Tracing.
```
                Assert.IsTrue(CheckEventReceived(eventListener.EventsReceived, nameof(EventCounterCollectorEventSource.IgnoreEventWrittenAsCounterNotInConfiguredList)));

```

And the only Asserts that do not work are related to count:

```
Assert.IsTrue(itemsReceived.Count >= 1);
Assert.AreEqual(expectedSum, sum);
Assert.AreEqual(expectedCount, count);
``` 

So this seems something Internal to my System???
Anyway event though there is no count, there appear Traces at Application Insights:

These traces have severity level critical but contain the name of the EventSource used by the EventCounter:
[query_data.csv](https://github.com/microsoft/ApplicationInsights-dotnet/files/7083865/query_data.csv)

Image with one of these traces:
![Screenshot (24)](https://user-images.githubusercontent.com/50277636/131502136-9a0d3333-efd4-42c3-8b34-b17128fea7d4.png)

Again, I have been able to send information with the requestCounter.WriteMetric of the previous post. But that is not at all what I inted. I want them to show in customMetrics. 
Additionally that WriteMetric function was very ill functional since if I changed the EventID a weird runtime error Array out of Index appeared. But anyway those traces reported a URL and a Metric:
![Screenshot (25)](https://user-images.githubusercontent.com/50277636/131502621-4c7e8b60-a2a9-47d7-b85a-4c01f2ed4970.png)

Check the Url and ellapsed miliseconds parameters that I passed are reported to Application Insights.

**Comment by esyker** [comment]
@cijothomas no help? Please provide some insights. If you could clone the repo will be great. As I said, everything is configured correctly so I don't really understand what's going on.

**Comment by cijothomas** [comment]
@esyker I am unsure what is the issue being faces.
EventCounter - are only expected to show up as CustomMetric. It looks like you are mixing it up with EventSource (https://www.nuget.org/packages/Microsoft.ApplicationInsights.EventSourceListener). which is expected to show up as Traces table. This is by design.

If this is not your question, please share the minimal repro app, along with a **concise** description of Expected behavior vs Actual behavior.

**Comment by esbenbach** [comment]
Might be i misunderstood something, but arent EventCounters also an EventSource, meaning that if we use EventSource listener for our regular "EventSources" we also end up with traces for our metrics?

This seems to be the behaviour I am observing at least.

If this is indeed the designed behaviour, how can we go about using both EventCounters and have the EventSourceListener filter out "counters" - because its generating a lot of traces!

**Comment by esbenbach** [comment]
@esyker not sure how much this is relevant to you anymore, but I had a support case for this and someone on the product group confirmed this is "by design".

Basically since EventCounters are also Event Sources, they might get registered twice (depending on how you register your event sources).

They recommended that Event Counters are disabled when configuring Event Sources:
```C#
services.ConfigureTelemetryModule<EventSourceTelemetryModule>((module, o) =>
{
    module.DisabledSources.Add(new DisableEventSourceRequest() { Name = "Microsoft-AspNetCore-Server-Kestrel" });
}
```
I ended up writing a `ITelemetryProcessor` for filtering instead:
```C#
public class FilteringTelemetryProcessor : ITelemetryProcessor
{
    private readonly ITelemetryProcessor next;

    public FilteringTelemetryProcessor(ITelemetryProcessor next)
    {
        this.next = next;
    }

    public void Process(ITelemetry item)
    {
        if (this.OkToSend(item))
        {
            this.next.Process(item);
        }
    }

    private bool OkToSend(ITelemetry item)
    {
        return item switch
        {
            TraceTelemetry traceTelemetry when IsEventPayloadTrace(traceTelemetry) => false,
            _ => true
        };
    }

    private static bool IsEventPayloadTrace(TraceTelemetry trace) => trace.Properties.TryGetValue("Payload", out var payload) && payload.Equals("System.Diagnostics.Tracing.EventPayload");
}
```


I hope this helps someone in the same boat as me.
