### ISSUE TITLE
EventCounter class does not contain field documentation example

### ISSUE THREAD

**Issue by esyker** [microsoft/ApplicationInsights-dotnet#2395]
I am using the code from the documentation present at this link.:

[https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counter-perf](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counter-perf).

The code is this:
```
using System.Diagnostics.Tracing;

[EventSource(Name = "Sample.EventCounter.Minimal")]
public sealed class MinimalEventCounterSource : EventSource
{
    public static readonly MinimalEventCounterSource Log = new MinimalEventCounterSource();

    private EventCounter _requestCounter;

    private MinimalEventCounterSource() =>
        _requestCounter = new EventCounter("request-time", this)
        {//does not work
            DisplayName = "Request Processing Time",
            DisplayUnits = "ms"
        };

    public void Request(string url, long elapsedMilliseconds)
    {
        WriteEvent(1, url, elapsedMilliseconds);
        _requestCounter?.WriteMetric(elapsedMilliseconds);
    }

    protected override void Dispose(bool disposing)
    {
        _requestCounter?.Dispose();//does not work
        _requestCounter = null;

        base.Dispose(disposing);
    }
}
```

However, when I use the code on VS2019 the IDE imeddiatly tells me that EventCounter class does not contain .Dispose() method and also the DisplayName and DisplayUnits properties.
These are the lines that give problems:
```
private MinimalEventCounterSource() =>
        _requestCounter = new EventCounter("request-time", this)
        {//does not work
            DisplayName = "Request Processing Time",
            DisplayUnits = "ms"
        };

protected override void Dispose(bool disposing)
    {
        _requestCounter?.Dispose();//does not work

```

When I inspected the class, this is in fact true. The definition of the class just contains this:
```
namespace System.Diagnostics.Tracing
{
    //
    // Summary:
    //     Provides the ability to collect statistics for very frequent events through the
    //     System.Diagnostics.Tracing.EventSource class.
    public class EventCounter
    {
        public EventCounter(string name, EventSource eventSource);

        public void WriteMetric(float value);
    }
}
```
 Why is the official example from Microsoft not working? Is this related to my run-time version which is different from the example which is .NET core (mine is ASP.NET framework 4.8 WebForms).

**Comment by cijothomas** [comment]
This repo is for reporting issues with ApplicationInsights .NET SDK only. You should report issues with dotnet docs, in that repo itself.

(Also, your assessment that the issue is due to Asp.Net is correct. EventCounter has lot of features available only in netstandard2.1)
