### ISSUE TITLE
ILogger BeginScope not logging kvpair when value is empty string

### ISSUE THREAD

**Issue by afratila** [microsoft/ApplicationInsights-dotnet#2402]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
From the .csproj file:
    "Azure.Identity" Version="1.3.0" 
    "Azure.Security.KeyVault.Secrets" Version="4.1.0" 
    "Microsoft.ApplicationInsights" Version="2.16.0" 
    "Microsoft.Azure.ApplicationInsights.Query" Version="1.0.0" 
    "Microsoft.Azure.Management.DataFactory" Version="4.13.0" 
    "Microsoft.Azure.OperationalInsights" Version="1.0.0" 
    "Microsoft.Azure.Services.AppAuthentication" Version="1.6.0" 
    "Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" 
    "Microsoft.NET.Sdk.Functions" Version="3.0.11" 
    "Microsoft.Rest.ClientRuntime.Azure.Authentication" Version="2.4.1" 
    "Newtonsoft.Json" Version="13.0.1" 
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): netcoreapp3.1
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Azure Function App on Windows

### Describe the bug

When using `ILogger.BeginScope(IDictionary<string, object>)`, key-value pairs where the value is an empty string `""` will not appear in output Application Insights logs. I would have expected the key-value pair to appear in the logs, with the value being an empty string.

### To Reproduce
A simple Azure Function app below, with a timer that fires every 5 minutes. 
```
using System;
using System.Collections.Generic;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

[FunctionName("SampleFunction")]
public static void Run([TimerTrigger("0 */5 * * * *")] TimerInfo myTimer, ILogger log)
{
    IDictionary<string, object> sampleDict = new Dictionary<string, object>{ { "nonemptykey", "value" }, { "emptykey", "" } };

    using (log.BeginScope(sampleDict)) 
    {
         log.LogInformation("log message here");
    }
}

```
Assuming this function app is connected to an Application Insights (necessary for this code to demonstrate the issue), the expected log would contain a field `customDimensions` which itself is an object. Among the properties in `customDimensions`, we expect the 2 key-value pairs in `IDictionary sampleDict`, keys formatted as `prop__nonemptykey` and `prop__emptykey`. However, as shown below, the kvpair with an empty string as the value, `prop_emptykey` is missing from `customDimensions` in the log, while `prop_nonemptykey`, the key-value pair with a not-empty string value is present.

![image](https://user-images.githubusercontent.com/16578879/131723139-2a5a7d10-bafb-4e9d-999f-3be3d5a3d3bd.png)

### For Immediate Support

For immediate support relating to the Application Insights .NET SDK we encourage you to file an [Azure Support Request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) with Microsoft Azure instead of filing a GitHub Issue in this repository. 
You can do so by going online to the [Azure portal](https://portal.azure.com/) and submitting a support request. Access to subscription management and billing support is included with your Microsoft Azure subscription, and technical support is provided through one of the [Azure Support Plans](https://azure.microsoft.com/support/plans/). For step-by-step guidance for the Azure portal, see [How to create an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). Alternatively, you can create and manage your support tickets programmatically using the [Azure Support ticket REST API](https://docs.microsoft.com/rest/api/support/)

**Comment by adloweltd** [comment]
This issue still exists from what I can tell. It's a shame it got closed. Can it be reopened?
