### ISSUE TITLE
Stop that goddamn telemetry!

### ISSUE THREAD

**Issue by WrongBit** [microsoft/ApplicationInsights-dotnet#2405]
I compiled my simple C# desktop app. And UNEXPECTEDLY my app asks access to external website! (from MS network) What the hell is that??? Why MS inject their virus code into my app?? Nowhere I asked VS to inject any "telemetry" sh*****it into my program!  Stop your VIRUS practice and leave my code untouched! I don't want your telemetry and stop injecting this rubbish into my programs!

**Comment by cijothomas** [comment]
There is no product shipped from this repo which automatically inject any telemetry. User must *explicitly* install the nuget packages shipped from this repo to enable telemetry.
If VS is injecting any telemetry without you asking, please report it to the VS. 

If by VS, you meant Visual Studio, then you can report issues from Help->Send feedback ->Report a problem
![image](https://user-images.githubusercontent.com/5232798/132057612-480a1703-1efe-4e8f-b704-5c6fb24db596.png)
