### ISSUE TITLE
Can DependencyCollector and Web packages be used independently without App Insights instance?

### ISSUE THREAD

**Issue by kenans** [microsoft/ApplicationInsights-dotnet#2410]
Hi I'm trying to collect ASPNET Core requests and dependency calls with `Microsoft.ApplicationInsights.Web` and `Microsoft.ApplicationInsights.DependencyCollector` packages, then log to an endpoint (STDOUT/flat file/other servers) other than App Insights. I wonder if it is achievable?

**Comment by TimothyMothra** [comment]
Hi @kenans 
Our SDK has the concept of a `TelemetryChannel` which handles serialization and sending to an endpoint.
You can implement your own `ITelemetryChannel` that meets your needs.
Also, be aware that the `Microsoft.ApplicationInsights.Web` package is meant for Asp.Net.
If you're using Asp.Net Core, you should use `Microsoft.ApplicationInsights.AspNetCore`.
You can find some guides on this repo's Readme: https://github.com/microsoft/ApplicationInsights-dotnet


Lastly, if you're looking for a truly vendor-agnostic solution you may consider Open Telemetry: https://github.com/open-telemetry/opentelemetry-dotnet
