### ISSUE TITLE
Can't find docs after Consolidating 

### ISSUE THREAD

**Issue by 304NotModified** [microsoft/ApplicationInsights-dotnet#2413]
The [old repo](https://github.com/Microsoft/ApplicationInsights-dotnet-logging) has described how to setup the NLog target in the readme.

![image](https://user-images.githubusercontent.com/5808377/133509949-ccd95824-5c89-4d7a-af3b-bb614e5a1bb5.png)

Where could I find this documentation now? I can't find it. I seems wrong to link to an archived repository

**Comment by TimothyMothra** [comment]
I think you're looking for this: https://github.com/microsoft/ApplicationInsights-dotnet/tree/develop/LOGGING/src/ILogger

**Comment by snakefoot** [comment]
Or more likely this one: https://github.com/microsoft/ApplicationInsights-dotnet/tree/develop/LOGGING
