### ISSUE TITLE
Refactor Shared Dependency Injection Related Code

### ISSUE THREAD

**Issue by simbaja** [microsoft/ApplicationInsights-dotnet#2417]
**Is your feature request related to a problem?**

I was looking through how to abstract the logging configuration for my application, which is a combination of workers and ASP.NET Core applications.  I have need to configure the telemetry modules for both of these types of applications.  However, looking through the source, the internal code will only call the configure that is related to either the ServiceWorker or AspNetCore version of the library because the code is configured as shared and will end up being in two different namespaces.

Specifically, [this section](https://github.com/microsoft/ApplicationInsights-dotnet/blob/ede19dee6caeb4c57afa0aa8ef3ff068687a43d3/NETCORE/src/Shared/Implementation/TelemetryConfigurationOptionsSetup.cs#L82) of code configures either an Microsoft.ApplicationInsights.**AspNetCore**.ITelemetryModuleConfigurator or an Microsoft.ApplicationInsights.**WorkerService**.ITelemetryModuleConfigurator, but not both.  Regardless of whether it's using AspNetCore/WorkerService, it should be able to leverage common dependency injection.

**Describe the solution you'd like.**

If you refactor the shared dependency injection related code into its own package, you can reference it from both ServiceWorker and AspNetCore.  The DI code would always have the same namespace, and therefore you could add it as a dependency to application libraries and enable it to work in both contexts without issue.  I think that this can be done without breaking existing code because you can add forwarders in the current namespace that redirect to the new DI package (just mark them as obsolete so that people know there's a new way, of course).

**Describe alternatives you've considered.**

The only way around this that I see for now is to create two libraries myself (one that links to ServiceWorker and another that links to AspNetCore) and then link each app to that.  However, that essentially duplicates code so isn't optimal.

**Additional context.**
Add any other context about the feature request here.

**Comment by TimothyMothra** [comment]
I'm sorry but at this time we're not considering creating a new package to perform dependency injection.
These two packages (WorkerService and AspNetCore) are separate by design as they are not expected to be used together in the same project.

**Comment by simbaja** [comment]
@TimothyMothra, I'm not sure I was clear in the use case above.  I'm not trying to use both packages in the same project, I'm trying to leverage a common logging abstraction that can be used in both types of projects.  The use case is more like the following:

**Optimal:**

Project.Logging.DI <- contains the dependency injection related setup for all projects in the solution (linked to new DI project)
Project.App1 <- linked to AspNetCore and Project.Logging.DI
Project.App2 <- linked to WorkerService and Project.Logging.DI

**Right now, you have to do something more like the following:**

Project.Logging.DI <- contains the dependency injection related setup for all project in the solution
Project.Logging.DI.AspNetCore <- linked to AspNetCore, adds DI for for asp.net related projects
Project.Logging.DI.WorkerService <- linked to WorkerService, adds DI for worker service related projects
Project.App1 <- linked to AspNetCore and Project.Logging.DI.AspNetCore
Project.App2 <- linked to WorkerService and Project.Logging.DI.WorkerService

The second approach, though it works, it causes repeats of the same DI (and potentially other) code, which violates the DRY principles.  

This is because the shared code in the implementation ends up in two different namespaces instead of its own namespace which can then be leveraged more effectively by consumers.
