### ISSUE TITLE
Error "Attempted to get a metric series by specifying 2 dimension(s), but this metric has 3 dimensions" with Get-Metric method -Microsoft.ApplicationInsight

### ISSUE THREAD

**Issue by niki33** [microsoft/ApplicationInsights-dotnet#2426]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:

![image](https://user-images.githubusercontent.com/22556067/135040263-45a54b4f-9f0f-4698-8364-9935ae9951c5.png)

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):

  netcoreapp3.1

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):

It's an Azure Function

### Describe the bug
Error "Attempted to get a metric series by specifying 2 dimension(s), but this metric has 3 dimensions" with Get-Metric method of telemetry client

Error:
"Attempted to get a metric series by specifying 2 dimension(s), but this metric has 3 dimensions"
Exception:
System.ArgumentException:
   at Microsoft.ApplicationInsights.Metric.TryGetDataSeries (Microsoft.ApplicationInsights, Version=2.17.0.146, Culture=neutral, PublicKeyToken=xxxxxx)
   at Microsoft.ApplicationInsights.Metric.TryGetDataSeries (Microsoft.ApplicationInsights, Version=2.17.0.146, Culture=neutral, PublicKeyToken=xxxxxx)
   at Microsoft.ApplicationInsights.Metric.TrackValue (Microsoft.ApplicationInsights, Version=2.17.0.146, Culture=neutral, PublicKeyToken=xxxxxx)

Code:
` string source = string.IsNullOrEmpty(this.logger.PStore[Constants.CurrentKey]) ? "NA" : this.logger.PStore[Constants.CurrentKey];
  string cId = string.IsNullOrEmpty(this.logger.Store[Constants.CId]) ? "NA" : this.logger.Store[Constants.CId];

public virtual void GetMetric(string metricId, string source = "", string cId = "")
    {
        Metric metric = this.TelemetryClient.GetMetric(metricId, "Source", "CorrelationId");
        metric.TrackValue(1, source, cId);
    }`
      
### To Reproduce
Run the above code.

**Comment by cijothomas** [comment]
If you're running the application in Azure Functions, please file an issue [here](https://github.com/Azure/azure-functions-host/issues/new/choose).

If not, please re-open this issue and share a minimal repro app we can run.

**Comment by niki33** [comment]
[ConsoleApp4.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/7255069/ConsoleApp4.zip)

@cijothomas , I have attached the basic code..There are 2 issues.

1.) Running this directly ...This doesn't Log the metric into Appinsight but I can see it in VS output window.
2.) Using this code in a CL and consuming that as NuGet, gives the same issue as mentioned above.

**Comment by cijothomas** [comment]
_Please share a minimal repro app we can run._

^^ please see the above.
