### ISSUE TITLE
Possible bug with functional tests and server telemetry

### ISSUE THREAD

**Issue by lukos** [microsoft/ApplicationInsights-dotnet#2428]
* Microsoft.ApplicationInsights 2.18.0
* Microsoft.ApplicationInsights.AspNetCore 2.18.0
* Microsoft.ApplicationInsights.SnapshotCollector 2.18.0
* netcoreapp3.1
* Local (Windows 10 Enterprise) and Windows Server 2019 Standard

### Describe the bug

I am seeing attempts made to log AI data to the web, despite DisableTelemetry being set to true. My experience in both places is slightly different so will describe them separately.

### To Reproduce

We have a dotnet core 3.1 web service which has a functional tests project attached to it (NUnit console app). The web service has app insights installed and some code in Startup that disables telemetry in the development and build environments. It does NOT have an appinsights key in appsettings.json, only appsettings.Production.json.

While debugging a network problem on a build server (Windows Server 2019) using Fiddler proxy, I noticed many calls to /v2/track and also requests to /metadata/instance/compute (which I think is related to Azure App Services, which we don't use). These didn't seem to have any payload but the metadata calls all returned 502, which is likely to be affecting the test performance.

I was then trying to debug this on my local machine to see if I could work out how the functional tests project might be picking up the AI configuration. The tests project does not have AI installed but obviously picks it up with its dependency on the web service. It uses the WebApplicationFactory and the same startup as the web service with the disable telemetry call in it. I debug the tests and the DisableTelemetry is definitely called. The test project does not have an AI key in it. When I run the functional tests in Visual studio, I see stuff like this logged:

`Application Insights Telemetry: {"name":"AppEvents","time":"2021-09-29T16:25:51.2117090Z","iKey":"8a28de91-bcf6-44ac-9242-f7a64f1146b8","tags":{"ai.application.ver":"1.4.0.0","ai.device.osVersion":"Microsoft Windows 10.0.19043","ai.cloud.roleInstance":"/PU6k0iJgzHB","ai.session.id":"9mXc7bOAIDHN","ai.internal.sdkVersion":"dotnetc:2.18.0-315","ai.internal.nodeName":"DEV-01.ourdomain.local"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"TelemetryProcessorCreated","properties":{"TelemetryProcessor":"SnapshotCollectorTelemetryProcessor Problems:Count=0","Runtime":".NET Core 3.1.19"}}}}`

I do not recognise the "iKey", which I assume is the app insights key and it is not one of our accounts (potentially could be an old one). I have no idea why anything is being logged.

Even if this is the server telemetry, it should be disabled if it is disabled in code and goodness knows where it picks this up from.

**Comment by lukos** [comment]
I enabled the telemetry locally with the correct key and I continue to see the event above (with the wrong key) as well as some additional events that contain the correct key. AppEvents is always the wrong key and the others like AppRequests etc. are the correct key.

**Comment by lukos** [comment]
OK, this is being caused by the snapshots collector. Once I remove that, it stops trying to log the invalid events and also stops logging the dependency to /metadata/instance/compute, which is erroring. Should I raised a bug in the snapshot collector repo?

**Comment by pharring** [comment]
This is being handled at https://github.com/microsoft/ApplicationInsights-SnapshotCollector/issues/17
