### ISSUE TITLE
Is there a way to set ClourRoleName to the NLog ApplicationInsights target?

### ISSUE THREAD

**Issue by ionmincu** [microsoft/ApplicationInsights-dotnet#2432]
**Question**:
Is there a way to set the `ClourRoleName` from the `telemetryClient` from the NLog target ? 

**What are you trying to achieve?**
Using the NLog ApplicationInsights target I want to be able to specifty / override the `telemetry.Context.Cloud.RoleName`.

**What have you tried so far?**
Searching on Google and looking at the current implementation [here ](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/LOGGING/src/NLogTarget/ApplicationInsightsTarget.cs)

I've also found that setting `WEBSITE_HOSTNAME` will have the desired effect, but does it have other effects? This does not seem to be documented.

**Comment by cijothomas** [comment]
You can use TelemetryInitializer and override the telemetry.Context.Cloud.RoleName.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#addmodify-properties-itelemetryinitializer

Make sure to add the initializer to the right configuration. I believe for NLog, it must be TelemetryConfiguration.Active(in .NET core and .NET Framework both)

**Comment by ionmincu** [comment]
@cijothomas `TelemetryConfiguration.Active` is marked as obsolete
