### ISSUE TITLE
Is manually calling `TelemetryClient.Flush` (or `FlushAsync`) necessary for custom metrics?

### ISSUE THREAD

**Issue by SethNuteGarmin** [microsoft/ApplicationInsights-dotnet#2437]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights.WorkerService 2.18.0
(I also tried using the Microsoft.ApplicationInsights.AspNetCore 2.18.0 nuget package with the same results)

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
.net 5

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
IIS Express on Windows 10, stand-alone Kestrel on windows server version 2004 VMs

**What are you trying to achieve?**
Send custom metrics using the AI SDK. Have these custom metrics appear under both the log-based metrics and time-series metric view in the "Metrics" tab of the AI Azure UI.

**What have you tried so far?**
The behavior I am seeing is that the custom metrics always show under the log-based metrics, but will only show as time-series custom metrics under their custom namespace if I periodically call `Flush` or `FlushAsync` on the `TelemetryClient`. I am logging this issue to understand if this is intended behavior or not? Seemingly all of the documentation I have read suggests you don't need to manually invoke a flush expect on application shutdown.

How I am configuring DI:
```
services.AddSingleton(typeof(ITelemetryChannel), new ServerTelemetryChannel());
services.AddApplicationInsightsTelemetryWorkerService();
```

How I am sending the custom metric using an injected `TelemetryClient`
```
new MetricIdentifier("customMetricName", "customMetricNamespace", "customMetricDimension");
_telemetryClient.GetMetric(id).TrackValue(1, "a");
```

When doing this without calling flush I only see the metrics appear here (and in the log explorer customMetrics table), regardless of how long I leave the application running or wait for the time-series metrics to appear in the portal:
![logBasedMetrics](https://user-images.githubusercontent.com/90720794/136851034-e9d5e41a-0c31-4db3-86a8-e30dcdafbc3f.png)

If I setup a timer and periodically call flush every 60 seconds or so then I begin seeing the custom metrics namespace and the metric here:
![timeseriesMetric](https://user-images.githubusercontent.com/90720794/136851166-742aa5ef-abde-4d39-8a04-5a7fc030e7ca.PNG)

Below is a very simple `dotnet new webapi` app that I added AI to when testing this out. `AiHostedService` is an added `IHostedService` that receives the `TelemetryClient` via DI and sends metrics using a few timers. 
[ai-console.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/7325181/ai-console.zip)

**Comment by cijothomas** [comment]
There is no need for flushing explicitly, unless the worker app itself is being shutdown. 
(If you run the app under visual studio, you should be seeing the customMetric in the VS Debug windows once every minute, without any flush.)

Application Insights Telemetry sample (just portions of it): {"name":"AppMetrics",...."ai.internal.sdkVersion":..."ns":"MetricNamespace","name":"MyMetric","kind":"Aggregation","value":6,"count":6,"

**Comment by cijothomas** [comment]
> Seemingly all of the documentation I have read suggests you don't need to manually invoke a flush expect on application shutdown.

This is correct.
