### ISSUE TITLE
Data lost when I use the custom Metrics

### ISSUE THREAD

**Issue by 928PJY** [microsoft/ApplicationInsights-dotnet#2438]
* Runtime version :
   * .Net 5.0
   * Microsoft.ApplicationInsights: 2.18.0
* Hosting environment: Windows

We are using custom Metrics to track our build data, here is our [code](https://github.com/dotnet/docfx/blob/v3/src/docfx/lib/log/Telemetry.cs#L41), let's take the `BuildLog` metrics as a sample, in one round build of the repository, there are about 109k entries, and from the request, we catch by fiddler, there are 3 API calls, and totally about 1.3k aggregated entries in the API calls, and the sum of all the aggregated metrics value is about 16k.  
and the tracked value is different each time we run our application(we have made sure that we generate the same data each time).  
So does that means our metrics data has been sampled? if so is there any way to disable the sampling?

**Comment by cijothomas** [comment]
There is no sampling for Metrics, but you might be hit with capping issues.

Could you check dimension capping https://docs.microsoft.com/en-us/azure/azure-monitor/app/get-metric#dimension-and-time-series-capping ?

**Comment by 928PJY** [comment]
Great! Thanks @cijothomas, that helps.
