### ISSUE TITLE
Make TelemetryClient.Track(ITelemetry) publicly usable

### ISSUE THREAD

**Issue by jbattermann** [Microsoft/ApplicationInsights-dotnet#244]
The [TelemetryClient has a public .Track()](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Core/Managed/Shared/TelemetryClient.cs#L294) method that takes an ITelemetry instance but its [documentation states](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Core/Managed/Shared/TelemetryClient.cs#L291), that one shall not use it directly because its AI internal.

I am maintaining an [AI specific logger implementation](https://github.com/serilog/serilog-sinks-applicationinsights/) for [the Serilog logging framework](https://serilog.net/) and the AI implementation does create the ITelemetry instances (ExceptionTelemetry, Trace- or EventTelemetry currently) and I was wondering whether I could call the [TelemetryClient.Track()](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Core/Managed/Shared/TelemetryClient.cs#L294) method without having to worry that it'll go away short-term?

Basically I'd like to make the [AI logger itself a bit more open / generic](https://github.com/serilog/serilog-sinks-applicationinsights/issues/15) in terms of how logs are sent and ideally [I'd rather call .Track() instead of the Telemetry-specific methods](https://github.com/jbattermann/serilog-sinks-applicationinsights/blob/master/src/Serilog.Sinks.ApplicationInsights/Sinks/ApplicationInsights/ApplicationInsightsSinkBase.cs#L149).

What I am asking is basically whether the [TelemetryClient.Track()](https://github.com/Microsoft/ApplicationInsights-otnet/blob/master/src/Core/Managed/Shared/TelemetryClient.cs#L294) method is _truly_ _internal (and then I'd suggest making it actually internal from an API perspective) or safe to use publicly and if so, update the documentation accordingly (and maybe add a `null` check for the telemetry parameter).

Having it public but "prohibited" to use only via its doc is somewhat confusing and in my case, unfortunate.

**Comment by SergeyKanzhelev** [comment]
We have no plans to remove it and using it ourselves. So you can rely on it. We will consider making it officially public in the next major version.

**Comment by jbattermann** [comment]
Great, thanks @SergeyKanzhelev :+1:
