### ISSUE TITLE
Memory leak in Microsoft.ApplicationInsights.WorkerService

### ISSUE THREAD

**Issue by valxv** [microsoft/ApplicationInsights-dotnet#2463]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: 
```xml
<ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.18.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
</ItemGroup>
```
* Runtime version: net5.0
* Hosting environment: Windows 10, Linux

### Describe the bug

Memory leaks every 60 seconds inside `Microsoft.ApplicationInsights.WorkerService` NuGet package.

### To Reproduce

Follow the steps to create a simple console application as described in [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service#net-core-30-worker-service-application).

Run application in Debug mode. After every 60 seconds, the amount of RAM increases for ~15 MB:
![image](https://user-images.githubusercontent.com/7983178/139831278-16d7d0de-e3e4-460c-b015-931a5b828ae7.png)

with creation a lot of instances of
`ConcurrentDictionary<String, Tuple<DateTime, PerformanceCounterCategory, InstanceDataCollectionCollection>>    <0x21AB2249D30> [Static variable Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.Implementation.PerformanceCounterUtility.cache]`

**Comment by valxv** [comment]
There are also a couple of smaller subsequent increases in 1 MB and then consumed memory does not grow anymore.

**Comment by TimothyMothra** [comment]
The first time Performance Counter is accessed, it creates a lot of managed objects for tracking. 

I'm going to close this issue because this is not a leak.
