### ISSUE TITLE
Provide support for App Insights Connection String in NLog 

### ISSUE THREAD

**Issue by nschwarz1** [microsoft/ApplicationInsights-dotnet#2464]
**Is your feature request related to a problem?**
If so, provide a concise description of the problem.

Microsoft recommends using the **Connection String** to connect to Application Insights over the **Instrumentation Key**. But the NLog target _ApplicationInsightsTarget_ does currently not support using the Connection String (NLog configuration API, see https://github.com/Microsoft/ApplicationInsights-dotnet-logging#nlog). 

**Describe the solution you'd like.**
What do you want to happen instead? What is the expected behavior?

ApplicationInsightsTarget to support the ConnectionString as well as the Instrumentation Key.

**Describe alternatives you've considered.**
Which alternative solutions or features have you considered?

- Using the Instrumentation Key: Not recommended by Microsoft
- Providing Connection String in the ApplicationInsights.config: Can not get the Connection String from the web.config which is useful for deployments to multiple environments.
- Providing Connection String via TelemetryConfiguration.Active.ConnectionString: Not working for NLog logging, seems the Connection String needs to be added explicitly to the NLog target.

**Additional context.**
Add any other context about the feature request here.

**Comment by TimothyMothra** [comment]
Are you using an AspNet Core application?

We deprecated the `TelemetryConfiguration.Active` singleton in favor of using dependency injection.
We have this setting for backward compatibility:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/a232106b4bc44f0c90bb623627f6e12d11f37681/NETCORE/src/Shared/Extensions/ApplicationInsightsServiceOptions.cs#L138-L145

Can you please try this workaround and let us know if this works for you?

**Comment by nschwarz1** [comment]
I am using .Net Framework, so this doesn't apply, right?

**Comment by cijothomas** [comment]
> I am using .Net Framework, so this doesn't apply, right?

Correct.
In .NET Framework, you can use TC.Active and set connecting string directly.

**Comment by snakefoot** [comment]
> @cijothomas In .NET Framework, you can use TC.Active and set connecting string directly.

Think the original poster, wanted to configure this through the NLog-config, just like one can with Instrumentation Key.

**Comment by cijothomas** [comment]
> > @cijothomas In .NET Framework, you can use TC.Active and set connecting string directly.
> 
> Think the original poster, wanted to configure this through the NLog-config, just like one can with Instrumentation Key.

Thanks for correcting! I incorrectly assumed this was just a question. 

This is a feature ask for NLog appender to support connectionstring - there are no features planned for any of the logging adapters other than the ILogger provider.

**Comment by nschwarz1** [comment]
> > @cijothomas In .NET Framework, you can use TC.Active and set connecting string directly.
> 
> Think the original poster, wanted to configure this through the NLog-config, just like one can with Instrumentation Key.

Yes exactly, thank you for clarifying this.

**Comment by snehapar9** [comment]
Is there a potential workaround to integrate Application Insights with NLog using Connection String. Looks like NLog target ApplicationInsightsTarget only supports Instrumentation Key

**Comment by snakefoot** [comment]
Notice the upcoming ver. 3 should allow use of ConnectionString. See also: #3001

Alternative there also this fork:
- https://github.com/hangy/NLog.Targets.ApplicationInsights
