### ISSUE TITLE
"TelemetryChannel found a telemetry item without an InstrumentationKey" on WorkerService

### ISSUE THREAD

**Issue by thinh-ng** [microsoft/ApplicationInsights-dotnet#2467]
I have an issue where application insight log showing a lot of "TelemetryChannel found a telemetry item without an InstrumentationKey" on some of my microservices, some are APIs, some are worker services. 

After applying `.AddApplicationInsightsTelemetry(option => option.EnableActiveTelemetryConfigurationSetup = true)` according to [issue #2070](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2070) the error goes away for web API.

However, for the worker service `EnableActiveTelemetryConfigurationSetup` doesn't existed in `Microsoft.ApplicationInsights.WorkerService.ApplicationInsightsServiceOptions` so the workaround above can't be applied

Is there any workaround for app insight for worker services?

**Comment by cijothomas** [comment]
For the issue #2070, the root cause was NLogAdapter not having correct TelemetryConfiguration, fixable with the workaround https://github.com/microsoft/ApplicationInsights-dotnet/issues/2070#issuecomment-733227455.

Before giving any workaround for worker service, need to first identify the root cause here. Are you using NLogAdapter in worker service? or any other logging adapter?

**Comment by thinh-ng** [comment]
Hi @cijothomas, all of our worker use Serilog, setup as follow: 
```
hostBuilder.UseSerilog((hostingContext, services, loggerConfiguration) =>
{
    loggerConfiguration.WriteTo.ApplicationInsights(
         services.GetRequiredService<TelemetryClient>(),
         TelemetryConverter.Traces,
         LogLevel.Information);
});
```

**Comment by cijothomas** [comment]
Its best to ask this question in Serilog forum. Serilog must be using incorrect telemetry configuration, but I am not an expert in serilog to confirm.

**Comment by adrien-constant** [comment]
> Hi @cijothomas, all of our worker use Serilog, setup as follow:
> 
> ```
> hostBuilder.UseSerilog((hostingContext, services, loggerConfiguration) =>
> {
>     loggerConfiguration.WriteTo.ApplicationInsights(
>          services.GetRequiredService<TelemetryClient>(),
>          TelemetryConverter.Traces,
>          LogLevel.Information);
> });
> ```

I also use Serilog and got the same error.

**Comment by cijothomas** [comment]
@adrien-constant See my earlier response https://github.com/microsoft/ApplicationInsights-dotnet/issues/2467#issuecomment-966389136

We cannot help with the Serilog issue. Serilog/something inside it is relying on incorrect configuration. Only the owners of that component can help here.

**Comment by thinh-ng** [comment]
This had been solved using the following code, the cause is Serilog get `TelemetryClient` before its `InstrumentationKey` is set using `AddApplicationInsightsTelemetryWorkerService(instrumentationKey)`
```
var telemetryClient = services.GetRequiredService<TelemetryClient>();
telemetryClient.InstrumentationKey = appInsight.InstrumentationKey;
loggerConfiguration.WriteTo.ApplicationInsights(
    telemetryClient,
    TelemetryConverter.Traces,
    logLevel);
```
