### ISSUE TITLE
Non-trace (i.e., Exception, Critical and Warning) level messages incorrectly logged as Traces, and Traces (including Debug and Information level messages) are not being logged in an Asp.Net 5.0 Azure Hosted Service

### ISSUE THREAD

**Issue by rastogip2011** [microsoft/ApplicationInsights-dotnet#2471]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Microsoft.ApplicationInsights.AspNetCore 2.17.0
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): net5.0
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Azure Worker Service on Windows

### Describe the bug

The task is to log traces and exceptions from a worker service to the App Insights. All the steps given in the documentation were followed.

The issue: 
- Exceptions are being logged as traces
- Critical messages are being logged as traces
- Warnings are being logged as traces
- Traces are **not being logged**
- Information messages are not being logged
- Debug messages are not being logged

Here is the code written to log these properties:

                _logger.LogTrace("Trace @ TRY3 directly from PrashantDevBox");
                _logger.LogError("Exception @ TRY3  directly from PrashantDevBox");
                _logger.LogInformation("TRY3  @ AppInsights directly from PrashantDevBox");
                _logger.LogWarning("Warning @ TRY3  directly from PrashantDevBox");
                _logger.LogDebug("Debug from @ TRY3  directly PrashantDevBox");
                _logger.LogCritical("Critical @ TRY3  directly from PrashantDevBox");

And, here are the traces that were captured:
![image](https://user-images.githubusercontent.com/35422675/141610848-7e9adbac-c961-4f6f-85e8-ff4a6d289ae5.png)

### To Reproduce

The example given in the library is also having the same problem: https://github.com/microsoft/ApplicationInsights-dotnet/tree/develop/examples/BackgroundTasksWithHostedService

To reproduce the above result, you need to update the instrumentation key and add the above-mentioned code to line 30 in Worker.cs file.

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
* If we will not be able to repro the behavior you're reporting

### For Immediate Support

For immediate support relating to the Application Insights .NET SDK we encourage you to file an [Azure Support Request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) with Microsoft Azure instead of filing a GitHub Issue in this repository. 
You can do so by going online to the [Azure portal](https://portal.azure.com/) and submitting a support request. Access to subscription management and billing support is included with your Microsoft Azure subscription, and technical support is provided through one of the [Azure Support Plans](https://azure.microsoft.com/support/plans/). For step-by-step guidance for the Azure portal, see [How to create an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). Alternatively, you can create and manage your support tickets programmatically using the [Azure Support ticket REST API](https://docs.microsoft.com/rest/api/support/)

**Comment by deepakku-work** [comment]
Can someone please look into this and let us know if this is a known issue? This is affecting the our diagnosability of our service. Thanks!

**Comment by BishopBarber** [comment]
I had the issue of exceptions being logged as traces and I found a convenient way to fix work around the issue. You can use the overload method `LogError(this ILogger logger, Exception exception, string message, params object[] args)`, which seems to correctly log the error as an exception.

**Comment by cijothomas** [comment]
> The issue:
> 
> Exceptions are being logged as traces
> Critical messages are being logged as traces 
> Warnings are being logged as traces
> Traces are not being logged
> Information messages are not being logged
> Debug messages are not being logged

All ILogger logs are expected to be logged as TraceTelemetry.
All ILoggger logs with Exception passed to it are logged as ExceptionTelemetry.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#what-application-insights-telemetry-type-is-produced-from-ilogger-logs-where-can-i-see-ilogger-logs-in-application-insights


If you seeing only logs from a certain LogLevel or above, then consult this document:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#how-do-i-customize-ilogger-logs-collection

**Comment by cijothomas** [comment]
If anyone is seeing ILogger.Log calls with Exception, being stored as TraceTelemetry, please share a minimal repro app, so we can investigate.

**Comment by cijothomas** [comment]
> I had the issue of exceptions being logged as traces and I found a convenient way to work around the issue. You can use the overload method `LogError(this ILogger logger, Exception exception, string message, params object[] args)`, which seems to correctly log the error as an exception.

This is the correct way of logging exceptions. How were you doing it differently? Were you using the raw ILogger.Log (https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger.log?view=dotnet-plat-ext-6.0#microsoft-extensions-logging-ilogger-log-1(microsoft-extensions-logging-loglevel-microsoft-extensions-logging-eventid-0-system-exception-system-func((-0-system-exception-system-string)))) API? even in that case, ExceptionTelemetry is expected to be produced.
