### ISSUE TITLE
EnableDependencyTrackingTelemetryModule and appsettings.json

### ISSUE THREAD

**Issue by pzbyszynski** [microsoft/ApplicationInsights-dotnet#2479]
### Describe the bug

I am trying to configure AI in web api using `appsettings.json` file. 

According to:
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1882 and https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#configuration-recommendation-for-microsoftapplicationinsightsaspnetcore-sdk-2150-and-later

I should be able to include following section in my `appsettings.json` to disable dependency tracking. Unfortunately dependencies are still beeing tracked. Any comment on that would be appriciated
```
"ApplicationInsights": {
    "EnableDependencyTrackingTelemetryModule": false
  }
```

I am using `Microsoft.ApplicationInsights.AspNetCore 2.19.0`. Any comment on that would be appriciated

**Comment by cijothomas** [comment]
Could you share the code used to enable ApplicationInsights?

I tried a new web app (ASP.NET Croe 5.0), added Microsoft.ApplicationInsights.AspNetCore 2.19.0, added`services.AddApplicationInsightsTelemetry();` to ConfigureServices. and the following is my appsettings.json, and it is picking up `EnableDependencyTrackingTelemetryModule` (and instrumentationkey) correctly.

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "ApplicationInsights": {
    "InstrumentationKey" : "mykey",
    "EnableDependencyTrackingTelemetryModule": false
  },
  "AllowedHosts": "*"
}

```

**Comment by robwe** [comment]
I had the same issue. It turned out that the reason was the following according to the documentation:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core 
"If services.AddApplicationInsightsTelemetry(aiOptions) is used, it overrides the settings from Microsoft.Extensions.Configuration.IConfiguration."
The default for aiOptions is to set everything to true.
