### ISSUE TITLE
Items appear out of order due to millisecond resolution

### ISSUE THREAD

**Issue by cmeeren** [microsoft/ApplicationInsights-dotnet#2484]
Consider the screenshot below. Telemetry (including requests, traces, and events) that have the same millisecond may appear out of order. I have indicated the correct order.

<img width="757" alt="image" src="https://user-images.githubusercontent.com/7766733/144190542-560bd011-557e-4094-aeac-c492816f604b.png">

I don't know if this is a bug in the SDK, Azure Portal ingestion, or Azure Portal front-end.

As you can probably appreciate, this consistently causes unnecessary confusion when viewing logs.

Possibly related old issues:
* http://web.archive.org/web/20200916210726/https://github.com/Microsoft/ApplicationInsights-Home/issues/189
* http://web.archive.org/web/20200916210725/https://github.com/Microsoft/ApplicationInsights-Home/issues/190

Versions etc.:

* Microsoft.ApplicationInsights.AspNetCore 2.19.0
* net6.0 (happens on net5.0, too, and earlier IIRC)
* Azure Web App / App Service on Windows (happens on Linux, too, IIRC)

**Comment by TimothyMothra** [comment]
Hello,
Reading the history.. it sounds like our SDK is sending the extra precision (microseconds) but the ingestion service is trimming it to milliseconds. 

Here is sample output from the SDK:
> Application Insights Telemetry: {"name":"AppEvents","time":"2021-12-01T17:42:36.0089148Z","iKey":"put_actual_ikey_here","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"TL-XPS","ai.internal.sdkVersion":"dotnetc:2.20.0-74","ai.internal.nodeName":"TL-XPS"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"sampleevent","properties":{"MyCustomKey":"MyCustomValue","DeveloperMode":"true"}}}}

The datatime:
> 2021-12-01T17:42:36.0089148Z

--
We (sdk team) cannot speak for the ingestion service.

You can open a support ticket and ask for clarification from the ingestion team. Feel free to reference this github issue.

**Comment by cmeeren** [comment]
Where exactly should I open the support ticket?

**Comment by TimothyMothra** [comment]
There's a few links here: https://github.com/microsoft/ApplicationInsights-dotnet#support

**Comment by cmeeren** [comment]
Reported. Thanks!

**Comment by cmeeren** [comment]
For the record, support ticket was closed with the following summary. So it seems this may be fixed at some point.

> **Problem:**
> Telemetry is truncated and only milliseconds remain.
>
> **Mitigation Steps:**
> This is by design as this is not supported today. However, we have a work item to support nano second precision that we may pick up in 3–6-month timeframe.
