### ISSUE TITLE
Why is Visual Studio 2022 sending loads of requests to dc.services.visualstudio.com?

### ISSUE THREAD

**Issue by sebasijan** [microsoft/ApplicationInsights-dotnet#2490]
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):

     net5.0

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):

    asp.net webapi 
    Windows 10 
    Visual Studio 2022

**What are you trying to achieve?**

I would like the application to stop sending constant track requests to `dc.services.visualstudio.com` when debugging locally, these requests are polluting dev tools and often give 439 http statuses

as per [this SO question](https://stackoverflow.com/questions/69902118/how-to-stop-visual-studio-2022-sending-requests-to-dc-services-visualstudio-com), this never happened in VS 2019, and the ticket regarding this has a [response from MS](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-Application-Insights-/1578628) telling us to open a ticket here

**What have you tried so far?**

The suggested answer on SO is to disable ApplicationInsightsTelemetry in the application, but that does not work which is unsurprising as the issue seems to be specific to VS 2022

**Comment by cijothomas** [comment]
Have you enabled ApplicationInsights SDK in your application? If yes, it'll collect and send telemetry. You can disable it yourself, since you added the SDK.

If you are *NOT* adding ApplicationInsights SDK, and still telemetry is sent from your application when running from VS 2022 - report the issue to VS itself. (Help - > Send feedback ->Report a problem)

**Comment by sebasijan** [comment]
@cijothomas I have disabled it as per the [SO answer](https://stackoverflow.com/questions/69902118/how-to-stop-visual-studio-2022-sending-requests-to-dc-services-visualstudio-com) , ie

```
#if !DEBUG
services.AddApplicationInsightsTelemetry();
#endif

```

and 
```

#if DEBUG
TelemetryConfiguration.Active.DisableTelemetry = true;
TelemetryDebugWriter.IsTracingDisabled = true;
#endif

```

are you aware of any further disabling that one could do?

As mentioned, this has already been raised with MS but they told us to come here
