### ISSUE TITLE
Potential net6 App Insights Memory Leak 

### ISSUE THREAD

**Issue by Bharts8** [microsoft/ApplicationInsights-dotnet#2491]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
  \<PackageReference Include="Microsoft.ApplicationInsights" Version="2.19.0" />
  \<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.19.0" />
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
 net6
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
 Azure Web App

### Describe the bug

Created a net6 project hosted in Azure Web App to host a reasonably simple REST API. After running for about a day noticed extremely high memory usage akin to a memory leak application insights described in #1678 
Was able to capture memory dump and find 26.5k long running net tasks seemingly coming from Microsoft.AI.PerfCounterCollector

![image](https://user-images.githubusercontent.com/19439374/145482399-3f7b05e7-6df2-482d-ab37-e6cd486e0160.png)

![image](https://user-images.githubusercontent.com/19439374/145482716-98b8d845-adc1-4b19-a0bd-a595238ea025.png)

Mitigated by using versions
    \<PackageReference Include="Microsoft.ApplicationInsights" Version="2.11.0" />
    \<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.8.2" />

**Comment by TimothyMothra** [comment]
Hi @BPHartel Can you share a minimal repro? This would allow us to collect a dump to investigate.

**Comment by ercquest** [comment]
I am also seeing this issue and it may prevent us from using App Insights

**Comment by MisinformedDNA** [comment]
> Was able to capture memory dump and find 26.5k long running net tasks seemingly coming from Microsoft.AI.PerfCounterCollector

![image](https://user-images.githubusercontent.com/1784452/173085058-1ab3ffd8-9319-42e3-b962-a0bef1122fda.png)

`26564` is the thread ID, not the number of threads.
