### ISSUE TITLE
Build of dotnet31 / dotnet5 fails on Alpine Linux due to case-ambiguous folder

### ISSUE THREAD

**Issue by ayakael** [microsoft/ApplicationInsights-dotnet#2498]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: ApplicationInsights v2.4.0-sourcebuild (53b80) 
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): dotnet3.1 and dotnet5
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Alpine Linux 3.15

### Describe the bug

Build of dotnet31 / dotnet5 fails on Alpine Linux due to case-ambiguous folder on ApplicationInsights v2.4.0-sourcebuild (53b80) due to looking for  src/Core/Managed/net40/Utils.cs in src/Core/Managed/Net40/Utils.cs

### To Reproduce
Build dotnet31 or dotnet5 on Alpine Linux using following APKBUILD: https://gitlab.alpinelinux.org/ayakael/aports/-/tree/testing/dotnet/testing/dotnet31 without application-insights_fix-net40-location.patch.

### Fix
Move  src/Core/Managed/Net40/CorrelationHelper.cs to src/Core/Managed/net40 to remove case-ambiguious folder Net40.

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
* If we will not be able to repro the behavior you're reporting

### For Immediate Support

For immediate support relating to the Application Insights .NET SDK we encourage you to file an [Azure Support Request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) with Microsoft Azure instead of filing a GitHub Issue in this repository. 
You can do so by going online to the [Azure portal](https://portal.azure.com/) and submitting a support request. Access to subscription management and billing support is included with your Microsoft Azure subscription, and technical support is provided through one of the [Azure Support Plans](https://azure.microsoft.com/support/plans/). For step-by-step guidance for the Azure portal, see [How to create an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). Alternatively, you can create and manage your support tickets programmatically using the [Azure Support ticket REST API](https://docs.microsoft.com/rest/api/support/)

Made as part of Alpine Linux dotnet31 / dotnet5 packaging project, see dotnet/source-build#2695

**Comment by TimothyMothra** [comment]
Hello, it's not clear what you're asking. 
We don't have a file named `CorrelationHelper.cs`.

**Comment by ayakael** [comment]
Thank you for your reply! I'm sorry for the confusion - this is bug that appears within dotnet's source-build build on both 3.1 and 5.0, which uses the v2.4-sourcebuild despite it being *really* old. I'm the package maintainer for dotnet on Alpine Linux, the above fix is what made the build work for me.

Although, this could very much be source-build's problem, in which case maybe another solution should be developed. Maybe it's a matter of source-build using v2.20? I'm not entirely sure if this would work within source-builds environment, but I'll investigate further.

**Comment by ayakael** [comment]
@dagood @omajid Did ya'll experience this issue with source-build and Fedora packaging? I've exerienced this with dotnet31, dotnet5 and, if memory serves, dotnet6 on Alpine.

**Comment by omajid** [comment]
This is really surprising. I have been building source-build (3.1, 5.0, 6.0) on various Linux distributions (Fedora, RHEL, CentOS) using various case-sensitive filesystems (btrfs, ext4, xfs) and never seen this bug before. A case sensitive file name in ApplicationInsights has never been an issue. Not sure why Alpine is seeing this problem.

**Comment by ayakael** [comment]
Indeed! Alpine's build process has its fair of strange issues like this that really bewildered me last August when I was figuring it out. It was a hell of a process finding that I had to make neutralise the ambiguity using the above fix for things to move along. There's nothing specific to Alpine's file system management that should cause this issue. I'll build without the patch, and share the logs when I find the time.

**Comment by omajid** [comment]
I just tried it out in an alpine container:

```
$ podman run -it docker.io/library/alpine /bin/sh
/ # cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.0
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
/ # apk add ....
/ # git clone https://github.com/dotnet/source-build 
/ # cd source-build/
[ apply patch to do less work ]
# ./build.sh
...  [21:35:37.91] Building 'application-insights'                                                                       
  Running command:                                                                                                    
    Using custom build target                                                                                         
    Log: /source-build/artifacts/logs/application-insights.log                                                        
    With Environment Variables:                                                                                       
      DotNetBuildFromSource=true                         
      DotNetRestorePackagesPath=/source-build/packages/restored/                                                      
      DOTNET_INSTALL_DIR=/source-build/.dotnet/            
      DOTNET_PATH=/source-build/.dotnet/                                                                              
      DOTNET_HOST_PATH=/source-build/.dotnet/dotnet                                                                   
      _InitializeDotNetCli=/source-build/.dotnet/                                                                     
      _DotNetInstallDir=/source-build/.dotnet/                                                                        
      _InitializeToolset=/source-build/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj                
      StabilizePackageVersion=true                                                                                    
      PB_IsStable=true                                                                                                
      IsStableBuild=true                                                                                              
      DotNetFinalVersionKind=release                                                                                  
      DropSuffix=true                                                                                                 
      DotNetUseShippingVersions=true                                                                                  
      PreReleaseVersionLabel=                                                                                         
      PackageVersionStamp=                                 
      PB_VersionStamp=                                                                                                
      ContinuousIntegrationBuild=true                                                                                 
      MSBUILDDISABLENODEREUSE=1                            
      OfficialBuildId=20220113.1                                                                                      
      BUILD_BUILDNUMBER=20220113.1                                                                                    
      GitCommitCount=1103                                  
      GitCommitHash=53b80940842204f78708a538628288ff5d741a1d                                                          
      GitInfoCommitHash=53b80940842204f78708a538628288ff5d741a1d                                                      
      SourceRevisionId=53b80940842204f78708a538628288ff5d741a1d                                                       
      RepositoryCommit=53b80940842204f78708a538628288ff5d741a1d                                                       
      COMMIT_SHA=53b80940842204f78708a538628288ff5d741a1d                                                             
      GIT_COMMIT=53b80940842204f78708a538628288ff5d741a1d  
      RepositoryType=Git                                                                                              
      DeterministicSourcePaths=false                       
      SourceRoot=/source-build/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d/     
  [21:35:45.68] Building 'application-insights'...done                                                                
  New NuGet package(s) after building application-insights:                                                           
    -> Microsoft.ApplicationInsights 2.0.0                                                                            
  known-good using package version properties saved at /source-build/artifacts/obj/x64/Release/PackageVersions.props.p
re.known-good.xml                                                                                                     
  Checked cache for conflicts with source-built nupkgs. Took 00:00:00.0005429                                         
  Finding project directories...                                                                                      
  Writing package usage data...                                                                                       
  Writing package usage data... done. Took 00:00:00.9085060 
...

```

And here's the changes to do less work: https://gist.github.com/omajid/a9f13935986dac5f4424db521c96a045 (just so I can get feedback earlier).

**Comment by ayakael** [comment]
This issue is confirmed non-existent on dotnet6, thus I am closing it. dotnet31 and dotnet5 are on their way out, so I'm not worried about fixing this.
