### ISSUE TITLE
Implement Open Source Sigining

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#25]
See [Open-Source-Signing](https://github.com/dotnet/corefx/wiki/Open-Source-Signing) for details on Open Source Signing.

Here is .NET build tool repo [task](https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/OpenSourceSign.cs) to implement it.

Today csc do not support OSS signing. Work item tracking it here [Roslyn #1171](https://github.com/dotnet/roslyn/issues/1171).

**Comment by upendras** [comment]
Per readme on build-tools repository, 
**Note**: Please note that these tools are currently not meant for consumption outside of the .NET Core projects.

**Comment by SergeyKanzhelev** [comment]
Does this task work? =) We can talk to .NET team to change this statement.

**Comment by SergeyKanzhelev** [comment]
cc: @upendras, @abaranch
