### ISSUE TITLE
Indefinite blocking in Application Insight sync-over-async call 

### ISSUE THREAD

**Issue by MariiaHubenko** [microsoft/ApplicationInsights-dotnet#2504]
We've experienced blocking Application Insight code in 2 different solutions. One of the solutions runs as ASP.NET Core 2,0 and the other one is ASP.NET Framework (with .NET Framework 4.6.2). Sync-over-async blocking caused outages with 2 different scenarios.

o	.NETFramework,Version=v4.6.2/win7-x64
o	In ASP.NET Core application the Microsoft.ApplicationInsights.dll version is 2.5.0.61767. 
o	In ASP.NET Framework application the Microsoft.ApplicationInsights.dll version is 2.3.0.41907

**Scenario №1 (ASP.NET Core 2.0)**

In the asp.net core application we are using Application Insights Telemetry in the following way:
•	In _Startup.cs_ the ApplicationInsights Telemetry is registered:
```cs
public void ConfigureServices(IServiceCollection services)
    {
        ...
        services.AddApplicationInsightsTelemetry(Configuration);
        ....
    }
```
•	AppInsight configuration is added to _config.json_ file that is loaded to asp.net core application on startup:
```json
"ApplicationInsights": {
                              "InstrumentationKey": "{KEY GUID}",
                              "MinimumLevel": "Warning",
                              "DeveloperMode": true,
                              "TelemetryEnabled": true
               },
               "Logging": {
                              "IncludeScopes": false,
                              "LogLevel": {
                                             "Default": "Warning",
                                             "System": "Warning",
                                             "Microsoft": "Warning"
                              },
               "ApplicationInsightsLoggingEnabled": true,
                              "SerilogLoggingEnabled": true
```
The `Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptions` singleton object gets created lazily on the first http request. The `TelemetryConfigurationOptions` constructor is called from Dependency Injection. However inside the constructor it tries to dispose internal `InMemoryTransmitter` object and makes a request to endpoint address, which by default is "https://dc.services.visualstudio.com/v2/track". In `Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.DequeueAndSend(...)` method the async Task with IO http request is blocked by `.Wait()` method: https://www.screencast.com/t/uh2TaZXG. At this point executing thread blocks indefinitely in a sync-over-async call. Please see attached _StackTraceASPNetCore.txt_ file with the stack trace of a blocked thread.

Also since `Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptions` is created from DI, blocked thread acquires a lock on `Microsoft.Extensions.DependencyInjection.ServiceProvider.ResolvedServices` property. This lock is contended by every thread which resolves object using DI. Considering that application heavily relies on DI, almost every Worker thread that runs http requests in parallel will try to acquire the same lock. However thread which blocked in sync-over-async App Insight code never releases this lock. 
As the result application freezes and number of threads constantly grows with every request. Please see an example in attached DebugDiag reports:
•	Thread №28 blocked in deadlock: _wn0ldwk0004UI_Sitecore.Commerce.Engine_76048_CrashHangAnalysis.mht_
•	Thread №11 blocked in deadlock: _wn0ldwk0005EU_Sitecore.Commerce.Engine_13048_CrashHangAnalysis.mht_ 

**Scenario №2 (targetFramework 4.6.2)**

In ASP.NET Framework application blocking occurs only upon shutdown (when unloading domain). The `Microsoft.ApplicationInsights.Channel.InMemoryChannel` instance gets flushed. Please see the attached _StackTraceForAspNetFramework.txt_. 

The thread blocks indefinitely. It doesn't acquire any critical locks so application continues to work. Also IIS Overlapping recycle is enabled by default, so new domain starts in parallel. However old domain never unloads because of the the blocked thread that synchronously waits for App Insight Task. It keeps domain alive with all its allocated memory and causes high memory usage. 

Please see a screenshot: https://www.screencast.com/t/2F2XYIGVXPgj. 

Additionally we've attached Debug Diag report from the affected ASP.NET Framework process: _WN1LDWK0004PD_w3wp_6672_CrashHangAnalysis.mht_

**NOTE**

The async method `Microsoft.ApplicationInsights.Channel.Transmission.SendAsync(...)` which is waited synchronously, creates a Task  which sends request to AppInsight Endpoint (https://dc.services.visualstudio.com/v2/track). It looks like this request never times out. Also this Task doesn't have any cancelation token.

In both scenarios the blocking doesn't look like a sync-over-async deadlock:
- ASP.NET Core application can’t experience sync-over-async deadlocks since ASP.NET Core doesn’t provide any SynchronizationContext anymore: https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html.
- In case of ASP.NET Framework application - the blocked thread doesn't have SynchronizationContext object in the stack. 

Also, we've checked how the problematic method `Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.DequeueAndSend(…)` works in the latest Microsoft.ApplicationInsights 2.19 and discovered a weird logic: 
•	Blocked thread synchronously waits for async Task from `Send` method: https://www.screencast.com/t/0FeR5tO8 
•	Async Send` method creates a new instance of `Transmission` class: https://www.screencast.com/t/yETXXimh
•	The client timeout is set to infinite value: https://www.screencast.com/t/24cg4CAdvUNF
Does it means that internal Task may take indefinite amount of time to complete? Can this be the root cause of long blocking of the thread with synchronous wait? What are the further steps to diagnose this blocking? 

Additionally could you please let us know how to distinguish sync-over-async deadlocks from simple long-running Tasks that are waited synchronously instead of being awaited?

[StackTraceASPNetCore.txt](https://github.com/microsoft/ApplicationInsights-dotnet/files/7757538/StackTraceASPNetCore.txt)
[DebugDiagReports.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/7757691/DebugDiagReports.zip)
[StackTraceForAspNetFramework.txt](https://github.com/microsoft/ApplicationInsights-dotnet/files/7757877/StackTraceForAspNetFramework.txt)
[WN1LDWK0004PD_w3wp_6672_CrashHangAnalysis.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/7757908/WN1LDWK0004PD_w3wp_6672_CrashHangAnalysis.zip)

**Comment by TimothyMothra** [comment]
@MariiaHubenko

Please review our documentation on TelemetryChannels here: https://docs.microsoft.com/azure/azure-monitor/app/telemetry-channels#built-in-telemetry-channels
The `InMemoryChannel` is intended for synchronous workloads whereas the `ServerTelemetryChannel` is for asyncronous workloads.


Also, you're using very old versions of the Application Insights SDK (v2.3 was released in 2017 and v2.5 was released in 2018).
There have been countless bug fixes and enhancements, especially to the TelemetryChannels. 
Please upgrade to the latest v2.20 which was released a few weeks ago.


Lastly, you mentioned that you're using ASP.NET Core 2.0. 
Please note that this version has reached end-of-life and is no longer supported.
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by MariiaHubenko** [comment]
@TimothyMothra Thank you for your response.

However it looks like `ServerTelemetryChannel` also performs sync-over-async call when Disposing, since `.GetAwaiter().GetResult()` also blocks calling thread: 
https://github.com/microsoft/ApplicationInsights-dotnet/blob/405fd6a9916956f2233520c8ab66110a1f9dcfbc/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs#L340

Additionally I've downloaded latest version of [ApplicationInsights]( https://www.nuget.org/packages/Microsoft.ApplicationInsights) from nuget but I can't find `ServerTelemetryChannel` class there. Am I missing something?

In ASP.NET Framework we still rely on `InMemoryChannel` for sync loads. As described above when flushing `InMemoryChannel` object, it made http request internally but never responded. Please refer to the attached Debug Diag reports showing blocked threads: 
- In case of ASP.NET Framework blocking occurred on background thread, and not web request thread - so it didn't timeout on its own. 
- In case of ASP.NET Core - there are no OOTB timeouts on Tasks/Requests unless `CancellationToken` is added. 

In Microsoft.ApplicationInsights.dll versions 2.5.0.61767 and 2.3.0.41907 there are no cancelation tokens added to internal tasks executed when flushing `InMemoryChannel`. Could you please confirm whether latest Microsoft.ApplicationInsights.dll ensures a finite timeout for internal requests/Tasks when disposing `InMemoryChannel` and `ServerTelemetryChannel` objects? If so, is this timeout configurable?

**Comment by TimothyMothra** [comment]
`ServerTelemetryChannel` is in a different package: https://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel/

The timeout is not configurable, but you can provide your own `CancellationToken` to the `FlushAsync` methods:


https://github.com/microsoft/ApplicationInsights-dotnet/blob/ba9fc0e274fab6f7632cd0bc8650b4bddfd0e803/BASE/src/Microsoft.ApplicationInsights/TelemetryClient.cs#L681-L690


https://github.com/microsoft/ApplicationInsights-dotnet/blob/ba9fc0e274fab6f7632cd0bc8650b4bddfd0e803/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs#L343-L350

**Comment by MariiaHubenko** [comment]
@TimothyMothra Thank you. 

There are still a couple of questions left:

- `Flush` method of `InMemoryChannel` or `ServerTelemetryChannel` makes sync-over-async call and it is prone to deadlock in ASP.NET apps. In this case what is the correct way to dispose `InMemoryChannel` or `ServerTelemetryChannel` in sync ASP.NET Framework app? 

- `Transmission` class makes http request with `HttpClient` and its timeout is set to infinite value by default: https://github.com/microsoft/ApplicationInsights-dotnet/blob/ba9fc0e274fab6f7632cd0bc8650b4bddfd0e803/BASE/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L26
Is this timeout ever going to be used? Or is it overridden by CancelationTokens?

**Comment by TimothyMothra** [comment]
We don't have any recommendations for disposing the SDK.

It's only necessary to call `Flush` or `FlushAsync` when your application is shutting down. 

I believe the timeout was set to indefinite to give the telemetrychannels as much time as possible to fully transmit telemetry. I confirmed that the cancellation token is inspected at multiple locations in the call stack and can be used to forcibly cancel the flush operation.

**Comment by cijothomas** [comment]
> Is this timeout ever going to be used? Or is it overridden by CancelationTokens?

Overridden. 
https://github.com/microsoft/ApplicationInsights-dotnet/blob/ba9fc0e274fab6f7632cd0bc8650b4bddfd0e803/BASE/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L183

https://github.com/microsoft/ApplicationInsights-dotnet/blob/ba9fc0e274fab6f7632cd0bc8650b4bddfd0e803/BASE/src/Microsoft.ApplicationInsights/Channel/Transmission.cs#L192

**Comment by DhamodharanSiva** [comment]
I am also facing the same deadlock issue in our .Net core 3.1 application.Is this still not fixed?

![SyncOverAsync](https://user-images.githubusercontent.com/94168642/167631949-e3047fab-3ca4-4639-a210-c8a9c57ee670.jpg)
