### ISSUE TITLE
Azure Application Insights showing duplicate entries

### ISSUE THREAD

**Issue by DeepMalh44** [microsoft/ApplicationInsights-dotnet#2509]
We are using Azure Function App, Azure SQL server and API management a very simply solution and we are reporting all our telemetry back to Application Insights. Right now we are trying to review some performance issue and what we are observing is that Application Insights is showing duplicate records (screenshot below). Anyone know how we can avoid this duplicate entries and have a clean hierarchical flow of telemetry data?

![img1](https://user-images.githubusercontent.com/12475114/148255991-bd2c15fb-2a07-4fa0-9d3a-7a65137e2907.png)

UPDATE: 01/05/2022: We created a new Application Insights Instance and just created out of the box Function App From Azure portal and attached this instance of App Insights (no custom code nothing just sample code) and still we see DUPLICATE telemetry for that new function App as shown below from the App Insights logs:

![img2](https://user-images.githubusercontent.com/12475114/148256025-cad9c553-1723-4d12-94e0-65e1bea512f7.png)

Also posted the same issue here:  https://stackoverflow.com/questions/70475470/azure-application-insights-showing-duplicate-entries

**Comment by cijothomas** [comment]
If you're running the application in Azure Functions, please file an issue [here](https://github.com/Azure/azure-functions-host/issues/new/choose).

**Comment by ketaanhshah** [comment]
hello @cijothomas this issue is not alone with Function Apps, this is happening across all azure service we have on board .. and Telemetry for all these Azure components is  getting duplicated, I just posted my question with simple one service (function app in this case) but in my environment I have SQL Server logs, Service bus, functions apps, etc.. and Telemetry is duplicated for everything.

**Comment by cijothomas** [comment]
Can you share a non-function repro app showing this behavior for us to review if the config is correct?
Also check this FAQ: https://docs.microsoft.com/en-us/azure/azure-monitor/app/telemetry-channels#does-the-application-insights-channel-guarantee-telemetry-delivery-if-not-what-are-the-scenarios-in-which-telemetry-can-be-lost

Additionally, the duplication is possible in backend as well. (you'll need to open support ticket to get someone to investigate that)

**Comment by Elsa2604** [comment]
Same issue for me : Duplication of log entries in application insights.
I'm using bot framework composer and i have configured the instrumentation key and connection string in advanced app setting json and publishing profile. 
![AppInsight](https://user-images.githubusercontent.com/104147442/175033358-491e5fbf-f318-46cd-9126-8830ab80171c.png)

**Comment by Sudheerkumar** [comment]
Hi, This issue still persists any possible resolution?

**Comment by Elsa2604** [comment]
Hi,

Actually I face this still. I double checked with my Dev resources but when
it comes to prod resource, still I'm facing the same problem.

**Comment by flatproject** [comment]
Same problem here for nearly a year. All logs are duplicating.

![image](https://user-images.githubusercontent.com/18282373/177287389-f947dc43-4ff7-4bd0-91a8-4cfbe7e8bcdf.png)

**Comment by Elsa2604** [comment]
If your using workspace application insights, refer this https://docs.microsoft.com/en-us/answers/questions/775202/workspace-based-app-insights-vs-diagnostic-setting.html  
Usage of both both diagnostic settings and workspace-based Application Insights cause double data

**Comment by torbennehmer** [comment]
I can confirm this behavior in my case as well (no Azure function, but a customized Dynamics 365 Finops instance). Especially parallelized (10+ Threads) tasks emit the effect. There is a lot of data, that doesn't get duplicated, that tends not to run parallelized as well. We might have a synchronization problem here. Unfortunately, this also means that I have not yet been able to explicitly trigger the effect on my installation.

**Comment by mis046** [comment]
Our application have duplicate logs & custom events in our Application Insights (running in workspace-based mode with another Log Analytics). I confirmed that we don't have a diagnostic setting that forwards the logs. 

We are running on Java and are using 'com.microsoft.azure:applicationinsights-runtime-attach:3.3.1' & 'com.microsoft.azure:applicationinsights-core:2.6.4'. But still want to share here. Maybe this isn't an agent specific problem.

**Comment by fifuente** [comment]
I'm having a similar issue where I see the same log twice in an Azure Function slot. One log has set the SessionId and ParentId while the other does not.

Also noticed that the SDKVersion seems to be different in the telemetry:

![image](https://user-images.githubusercontent.com/109823223/217674555-dbb72009-7b71-4452-b138-2844b6c087e0.png)
![image](https://user-images.githubusercontent.com/109823223/217674604-95fdd4ae-cccb-4f81-ab6b-8edd9856063c.png)

I wonder what the problem is since I have the same code deployed to two different slots (Prod and PPE), and only the PPE slot is having this issue.

**Comment by wpinto-ahc** [comment]
Does anyone know why this is happening? I have the same problem, but the only duplicated entries are coming from *exceptions*

**Comment by hybridtechie** [comment]
Same issue happening for me - Logs from APIM being duplicated. No diagnostic setting present.

**Comment by Rui-Pires** [comment]
Same issue here, I think.
Finding random duplicates of customEvents on workspace.

**Comment by adearriba** [comment]
Anyone solved this?

**Comment by flatproject** [comment]
I commented three years ago about it and its still happening. It will never get resolved so dont waste your time here. Just accept it that you will see the same log up to 10 times consuming your storage, paying a premium for it, and Azure cannot do anything about it.

**Comment by mattmccleary** [comment]
Hi @flatproject, I chatted with the team. If you're seeing duplication of all your data, it is most likely from diagnostic settings like we said above. If that's not it, can you open a support ticket? Please reference this issue. Let me know when that's done, and we can make sure this gets troubleshooted.

**Comment by flatproject** [comment]
Hi @mattmccleary, I have functions without diagnostic settings that duplicate the logs and i also have app service instances with diagnostic logs enabled that duplicate the logs. If i disable the diagnostic logs in the app sevice instances then i have the Microsoft Defender for Cloud complaining. I will open a support ticket next week when im back from annual leave and refefence it here for visibility.
