### ISSUE TITLE
Trace is logged as exception.

### ISSUE THREAD

**Issue by vsarunov** [microsoft/ApplicationInsights-dotnet#2515]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):

**What are you trying to achieve?**
 Currently all the logs that are logging an exception appear as `Exceptions` in Application insights, we need to keep them as Traces.
**What have you tried so far?**
Worked -> Removing the exception and passing exception message with stack trace instead. 
Did not work -> Overriding the logging in `MinimumLevel`.
Did not work -> Using `ITelemetryInitializer` to override it.

I have found a similar issue however this is the opposite of what we are trying to achieve https://github.com/serilog/serilog-sinks-applicationinsights/issues/134

**Comment by mic-max** [comment]
The ILogger class has a [method that you can include the exception](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger.log?view=dotnet-plat-ext-6.0#microsoft-extensions-logging-ilogger-log-1(microsoft-extensions-logging-loglevel-microsoft-extensions-logging-eventid-0-system-exception-system-func((-0-system-exception-system-string)))), are you using this?

In Application Insights you can configure whether the exceptions appear as `Exceptions` vs Traces
See [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/ilogger#what-application-insights-telemetry-type-is-produced-from-ilogger-logs-where-can-i-see-ilogger-logs-in-application-insights)

**Comment by vsarunov** [comment]
Perfecto!
