### ISSUE TITLE
Does the SDK support semantic logging when used with ILogger in dot net core?

### ISSUE THREAD

**Issue by prateekprshr-nith** [microsoft/ApplicationInsights-dotnet#2516]
Does the SDK support semantic logging out of the box when used in dot net core via `ILogger`?
For e.g. if I do `logger.LogInformation("The device id is {deviceId}", deviceId)`, will `deviceId` appear as a column in the `trace telemetry` table, enabling the ability to query on it?

We are an internal MS team, so let me know if there is any other official channel to discuss this.

**Comment by cijothomas** [comment]
> logger.LogInformation("The device id is {deviceId}", deviceId), will deviceId appear as a column in the trace telemetry

No.  It won't be a dedicated column (the schema is fixed), but DeviceId will be part of the Properties collection, so you can query for it without doing string parsing.

**Comment by prateekprshr-nith** [comment]
So anything which is a part of properties collection appears as a column and we can query it?

**Comment by cijothomas** [comment]
CustomProperties doc:
https://docs.microsoft.com/azure/azure-monitor/app/api-custom-events-metrics#custom-measurements-and-properties-in-analytics
