### ISSUE TITLE
Incorrect way to inject TelemetryConfiguration

### ISSUE THREAD

**Issue by lommez** [microsoft/ApplicationInsights-dotnet#2520]
That documentation below is not up to date:

[https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#log-custom-telemetry-in-c-functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#log-custom-telemetry-in-c-functions)

Is not possible to inject the TelemetryConfiguration in that way.

The right way it to use IOptions<TelemetryConfiguration>

**Comment by cijothomas** [comment]
Please report the doc issue right in the doc page itself.
For Azure functions:
If you're running the application in Azure Functions, please file an issue [here](https://github.com/Azure/azure-functions-host/issues/new/choose).
