### ISSUE TITLE
Application insights/Function logging http auth headers in telemetry stream

### ISSUE THREAD

**Issue by AbhiMsft** [microsoft/ApplicationInsights-dotnet#2526]
If you're running the application in Azure Functions, please file an issue [here](https://github.com/Azure/azure-functions-host/issues/new/choose).

We have an azure function on netcoreapp3.1 and using Microsoft.ApplicationInsights and Microsoft.ApplicationInsights.DependencyCollector 2.20.0 version. We started o use HTTP client factory to call downstream services. 

Where http client is logging auth headers and application insights is collecting the telemetry and logging into pipeline. We tried ItelemetryInitializer to redact telemetry but we couldn't able to get this telemetry in the code. 

AI versions: 
Microsoft.ApplicationInsights: 2.20.0
Microsoft.ApplicationInsights.DependencyCollector : 2.20.0

Function host.json:

"logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    }
  }

Telemetry client injection in function startup:

builder.Services.AddSingleton<TelemetryClient>((serviceProvider) =>
            {
                string instrumentationKey = configuration.GetValue<string>("AppInsights:InstrumentationKey");
                var telemetryConfiguration = TelemetryConfiguration.CreateDefault();
                telemetryConfiguration.InstrumentationKey = instrumentationKey;
                DependencyTrackingTelemetryModule depModule = new DependencyTrackingTelemetryModule();
                depModule.Initialize(telemetryConfiguration);
                return new TelemetryClient(telemetryConfiguration);
            });

![image](https://user-images.githubusercontent.com/98358742/150869017-c9e69cd2-f4da-4afc-9053-f6b607cce97f.png)

**Comment by cijothomas** [comment]
If you're running the application in Azure Functions, please file an issue [here](https://github.com/Azure/azure-functions-host/issues/new/choose)

^^ Please check the above.

> application insights is collecting the telemetry and logging into pipeline.

ApplicationInsights has no in-built feature to collect http headers. If user is logging it to `ILogger` and ApplicationInsightsProvider is enabled, it'll be sent to ApplicationInsights (same with any other provider). To fix that, user must not log anything sensitive to ILogger. 

If you see ApplicationInsight is *automatically* capturing http headers, please share a repro app (*outside Azure Functions*), which show application insights is collecting this telemetry, and we can investigate.
