### ISSUE TITLE
Set custom namespace for default logs and metrics

### ISSUE THREAD

**Issue by caseyzhang123** [microsoft/ApplicationInsights-dotnet#2533]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Microsoft.ApplicationInsights.AspNetCore 2.20.0
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):  netcoreapp3.1
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Windows

**What are you trying to achieve?**
I would like to emit the default metrics, eg server response time and dependency duration, in a custom namespace.  They are going to the "microsoft.insights/components" namespace by default, and I'd like to send them to a different namespace to separate them out from other metrics we already have.

**What have you tried so far?**
I tried adding the following to our startup code to override the DefaultMetricNamespace, but it didn't work:
```
        public void ConfigureServices(IServiceCollection services)
        {
            MetricIdentifier.DefaultMetricNamespace = "SyncServiceDefaultMetrics";
            services.AddApplicationInsightsTelemetry();
```

I have also confirmed this is the payload being POSTed to dc.services.visualstudio.com/v2/track when running locally:
```
{
  "name": "AppMetrics",
  "time": "2022-02-04T01:55:01.0000000Z",
  "iKey": "<my instrumentation key>",
  "tags": {
    "ai.application.ver": "1.0.0.0",
    "ai.cloud.roleInstance": "<my desktop>",
    "ai.internal.sdkVersion": "m-agg2c:2.20.0-103",
    "ai.internal.nodeName": "<my desktop>"
  },
  "data": {
    "baseType": "MetricData",
    "baseData": {
      "ver": 2,
      "metrics": [
        {
          "ns": "SyncServiceDefaultMetrics",
          "name": "Dependency duration",
          "kind": "Aggregation",
          "value": 1579.6766,
          "count": 4,
          "min": 342.7602,
          "max": 452.5697,
          "stdDev": 40.621188530402456
        }
      ],
      "properties": {
        "DeveloperMode": "true",
        "Dependency.Type": "Azure blob",
        "_MS.IsAutocollected": "True",
        "cloud/roleInstance": "<my desktop>",
        "_MS.AggregationIntervalMs": "827000",
        "cloud/roleName": "Unknown",
        "Dependency.Success": "True",
        "operation/synthetic": "False",
        "dependency/resultCode": "200",
        "AspNetCoreEnvironment": "Development",
        "dependency/performanceBucket": "250ms-500ms",
        "dependency/target": "<my storage account>.blob.core.windows.net",
        "_MS.MetricId": "dependencies/duration"
      }
    }
  }
}
```

But in the Azure Portal it shows up under Application Insights standard metrics anyways
![image](https://user-images.githubusercontent.com/21297459/152610346-2b5e0033-64e7-41b9-805c-1deaee83fb54.png)

**Comment by cijothomas** [comment]
There are standard metrics and they have special meaning in ApplicationInsights, and you cannot customize the namespace for it. It'll be rejected by backend (as you already noted).

For metrics by users themselves (using TrackMetric() or GetMetric().TrackValue()), yes you can put namespace of your choice.
