### ISSUE TITLE
Operation ID not being picked up from StartOperation

### ISSUE THREAD

**Issue by apilosofms** [microsoft/ApplicationInsights-dotnet#2536]
* List of NuGet packagesand version that you are using:
  * Microsoft.ApplicationInsights.WorkerService (2.20.0)
  * Microsoft.Extensions.Hosting (6.0.1)
* Runtime version:
  * net50
* Hosting environment:
  * Console app on Windows.

### Describe the bug

**Overall goal**: Multiple functions/apps are chained together via queue messages. We want to pick up a custom tracking ID from the queue message and use it in AI's "operation_Id" (and operation_parentId) fields for all telemetry from each function.

In all cases below the bugs show up when we have multiple threads running with a singleton `TelemetryClient`. In production this happens in an Az Function (out-of-proc model) using `AddApplicationInsightsTelemetryWorkerService` to register the singleton. The functions are invoked in parallel for multiple requests, [seemingly] causing a threading issue.

**Bug v1**: If we explicitly set `telemetryClient.Context.Operation.Id = myTrackingId` in a given function invocation, then we notice some invocations will use the ID from other requests; feels like a classic race condition where the ID gets overwritten by another invocation. This seems to make sense since the setter for Operation.Id is just a simple setter; no lock or anything like that.

**Bug v2**: We were advised to put our telemetry inside a `using (var op = telemetryClient.StartOperation<...>(name, opId, ...))` block. This was supposed to herd all telemetry calls within that block to use the same operation ID - namely the one supplied when creating the operation. However, as the code sample below shows, the operation ID passed into the `StartOperation` function is not used when logging to AI; it doesn't seem to affect anything.

I have a feeling this might be just me not knowing the right way to do this; but I'm finding it really difficult to get an answer.

### To Reproduce

Run the attached code. My expectations are that the `Console.Writeline` statements in the main loop will show the same operation ID supplied to `StartOperation`. Even if not, I would at least expect that ID to show up in the AI log as the `operation_Id` field. Neither of those happens; instead we get an auto-generated operation ID in AI.

#### Example of what I'm seeing in AI:

```
traces
| where message !contains operation_Id 
| take 50
```
![image](https://user-images.githubusercontent.com/41029545/153319939-a7a9616d-f197-4c2a-a845-7ed7dca07738.png)

#### Code sample:
[AppInsightsBadOpIdRepro.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/8037350/AppInsightsBadOpIdRepro.zip)

**Comment by cijothomas** [comment]
Is the passed operationid W3CTraceContext compatible? If not it'll be ignored, and a new one will be generated.

**Comment by apilosofms** [comment]
To make sure I understand, you're asking if the `Operation.Id` that I set matches the specification for `trace-id` here?:
https://www.w3.org/TR/2021/REC-trace-context-1-20211123/#trace-id

If so, the answer is no. It includes some characters (dashes) that aren't permitted, and isn't 16 bytes in length. Let me see if things repro with a more suitable ID...

**Comment by apilosofms** [comment]
I tested by generating a 16-char entry with only numbers/lowercase (example: `00000000000task7`), and I got the same behaviour.

But more to the point, the operationID generated internally (since it ignores mine) is much longer than 16 chars. Example: `f4e3a913fd06c7314b5ca88bb15c71df`.

Maybe I'm looking at the wrong spec?

**Comment by cijothomas** [comment]
create a new activity yourself, and use its Activity.TraceId as the operation id to make sure you use a compatible id.

**Comment by apilosofms** [comment]
I don't think it's the format. When using the TraceTelemetry override, I can log operation IDs which don't look anything like that format.
