### ISSUE TITLE
Fields "operation_Id" and "operation_ParentId" not being logged when using TrackException

### ISSUE THREAD

**Issue by apilosofms** [microsoft/ApplicationInsights-dotnet#2541]
* List of NuGet packages:
  * microsoft.applicationinsights.workerservice 2.20.0
  * microsoft.extensions.hosting 6.0.1
* Runtime version: **net5**
* Hosting environment: **Windows console**

### Describe the bug

**Behavior:**
Calling `TrackException(ExceptionTelemetry telemetry)` does not record `operation_Id` or `operation_ParentId`, despite the fact that the `ExceptionTelemetry.Context.Operation.Id` has been set.
![image](https://user-images.githubusercontent.com/41029545/154163561-0ef20354-5b94-4986-ba21-9ece8833cb1b.png)

For trace (as opposed to exception) telemetry, calling `TrackTrace(TraceTelemetry telemetry)` **does** record these two values.

**Expected:**
Exceptions should behave the same way as traces in this case, so that we can correlate them.

### To Reproduce
The console app below runs a few threads which each logging both a track and an exception, setting the operation ID. Entries generated in the exceptions table are missing the data.

Note that you need to sub your AI instrumentation key.
[AppInsightsBadOpIdRepro.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/8075255/AppInsightsBadOpIdRepro.zip)

**Comment by apilosofms** [comment]
It looks like this is also the case for `TrackEvent`.

**Comment by auslavs** [comment]
I'm getting the same issue using .NET 6 with an App Service.
Using Microsoft.Extensions.Logging's ILogger I can create traces with the ParentId and OperationId populated, but if I use TrackTrace or TrackException these values are non-existent.
