### ISSUE TITLE
Filter Dependency will lost correlation

### ISSUE THREAD

**Issue by virtualcca** [microsoft/ApplicationInsights-dotnet#2542]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:2.19.0
* Runtime version : net5
* Hosting environment : Linux

Refer the documentation here https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling 
I removed fast dependencies using filter

But I found that after doing this, the telemetry correlation was messed up, and I couldn't see the calling relationship in appinsights.

For example, if a calls b, there will be a request of a, the following dependencies of a, and then a request of b, with a clear hierarchical relationship between a(request)->a(dependencies)->b(request)

After filtering is used, it becomes a request with a and b at the same level (dependencies are deleted)

I found that the telemetry correlation uses the id of a (reqeust) as the parentid of a (dependencies), and then uses the id of a (dependencies) as the parentid of b (request) to achieve the association, but after using filter, the relationship is hit Broken. 
So I would like to ask if there is a way to use filtering, do not let a (dependencies) id in the header of the http request sent by a to be given to b (request) as her parentid, but use a (request) ) of the id

**Comment by cijothomas** [comment]
I think this is just expected behavior. With the dependency telemetry filtered out, the correlation will be broken.
(Sampling takes the approach of either keep all telemetry from same operation or drop all - dropping some part from a same operation will cause broken traces.)
