### ISSUE TITLE
Differentiate between unhandled exception and first chance exception in Azure ApplicationInsights portal 

### ISSUE THREAD

**Issue by iqb-dawn** [microsoft/ApplicationInsights-dotnet#2545]
I have the below code,

            try
            {
                await _repo.Add(new SomeClass
                {
                });
            }
            catch(DbUpdateException dbEx)
            {
               // handled
            }

The exception is handled but I am seeing the exception is logged in Azure portal in ApplicationInsights service.

Do ApplicationInsights log first chance exceptions? If yes how can we differentiate/filter first-chance and unhandled exceptions in the portal?

**Comment by iqb-dawn** [comment]
Any update from the team?

**Comment by iqb-dawn** [comment]
Is there is a way to disable first chance exceptions?

**Comment by cijothomas** [comment]
I do not think ApplicationInsights automatically captures First Chance exceptions.
The SQL Example you have might be a bug - could you share a minimal repro app, so we can suggest a fix/workaround?

**Comment by iqb-dawn** [comment]
@cijothomas We are daily seeing the same exception in Azure Portal (in Failures tab). 

Also, we are seeing exceptions are logged twice in the portal which also shows that both first-chance and un-handled exception are getting logged.

**Comment by cijothomas** [comment]
Please share a minimal repro app. Its not possible to figure out this without a repro.

**Comment by iqb-dawn** [comment]
Do you need repro just with try catch block?

**Comment by cijothomas** [comment]
No. Fully Self-contained repro, showing the SDK configuration, and the code which triggers exception collection.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by iqb-dawn** [comment]
@cijothomas just created a simple app deployed into Azure,

```
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace AppInsights.FirstChanceException.MinimalRepo
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services) {
            services.AddApplicationInsightsTelemetry().AddMvc();
            services.AddDbContext<MyContext>(options =>
            {
                options.UseSqlServer("Server=tcp:DBName.database.windows.net,1433;Initial Catalog=DB;Persist Security Info=False;User ID=i1;Password=DbPass;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;");
            });
            }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, MyContext contex) =>
            app.UseRouting().UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                contex.Database.EnsureCreated();
            });
    }

    [Route("")]
    public class HomeController : ControllerBase
    {
        private readonly MyContext context;

        public HomeController(MyContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                await context.AddAsync(new Model
                {
                    UserId = 1,
                    Id = 1,
                });
                await context.SaveChangesAsync();
            }
            catch (DbUpdateException dbEx)
            {
                return Ok("Error Caught");
            }

            return Ok("Error Not Caught");
        }
    }

    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions<MyContext> options) : base(options)
        {
        }
        public DbSet<Model> Models { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Model>().HasKey(m => new { m.Id, m.UserId });
        }
    }
    public class Model
    {
        public int Id { get; set; }

        public int UserId { get; set; }
    }
}

```

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.20.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.2" />
	</ItemGroup>
</Project>

```

![image](https://user-images.githubusercontent.com/87642965/164890440-93bdecda-f25d-444a-b740-b5c2461af55e.png)


![image](https://user-images.githubusercontent.com/87642965/164890434-ea16aaa7-ccf5-4e30-aaeb-0a647f2e2394.png)

**Comment by cijothomas** [comment]
Thanks for sharing the repro. Could you also share the sdkverison field value from the collected ExceptionTelemetry?

**Comment by iqb-dawn** [comment]
What do you mean sdkverison from the collected ExceptionTelemetry? I have only reference `Microsoft.ApplicationInsights.AspNetCore` (see above) and enable application insights from Azure portal/

**Comment by iqb-dawn** [comment]
Ah you mean from the portal? This is `SDK version | il:2.20.0-103`

**Comment by iqb-dawn** [comment]
The category name is `Microsoft.EntityFrameworkCore.Update` which means `Microsoft.EntityFrameworkCore` is sending this exception to ApplicationInsight (even though exception is handled). This look like issue is from EF team side.
