### ISSUE TITLE
Accessing Request body inside ITelemetryInitializer's Initialize method throws Object Disposed error

### ISSUE THREAD

**Issue by vidhyasagarreddy** [microsoft/ApplicationInsights-dotnet#2546]
I was wiring up Telemetry's custom properties with required contents from the Request and running into issues with accessing Request body. Seems like the same issue was there on older repo but was closed without actual fix, which instead suggested a custom middleware (https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/686).

Any roadmap in near future on this ?

**Comment by cijothomas** [comment]
> Any roadmap in near future on this ?

No. Feature to automatically read request body is not coming in the near future.

**Comment by Insighter2k** [comment]
I would suggest to use a custom middleware. We are able to read request and response bodies if we want to (by activating / deactivating it) for debugging purposes.
The middleware enables you to customize not even that, but you can write additional middleware classes which enables even further error or information handling.

**Comment by vidhyasagarreddy** [comment]
This is just a work around. I would not want to write additional piece of middleware just to handle this

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0 .New middleware from asp.net core 6.0 makes this easy to do.
