### ISSUE TITLE
How do I inject IHttpContextAccessor into custom TelemetryInitializer , from a 4.8 framework web application?

### ISSUE THREAD

**Issue by sushanti** [microsoft/ApplicationInsights-dotnet#2551]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Microsoft.ApplicationInsights (2.20.0)

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): v4.8

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Windows

**What are you trying to achieve?**
I'm trying to create a custom telemetry initializer (HttpContextRequestTelemetryInitializer) like the one mentioned in the [official Microsoft docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling) and then use it in a .NET framework 4.8 app. The code for the telemetry initializer looks something like this - 
```
public class HttpContextRequestTelemetryInitializer : ITelemetryInitializer
{
    private readonly IHttpContextAccessor httpContextAccessor;

    public HttpContextRequestTelemetryInitializer(IHttpContextAccessor httpContextAccessor)
    {
        this.httpContextAccessor =
            httpContextAccessor ??
            throw new ArgumentNullException(nameof(httpContextAccessor));
    }

    public void Initialize(ITelemetry telemetry)
    {
        var requestTelemetry = telemetry as RequestTelemetry;
        if (requestTelemetry == null) return;

        var claims = this.httpContextAccessor.HttpContext.User.Claims;
        Claim oidClaim = claims.FirstOrDefault(claim => claim.Type == "oid");
        requestTelemetry.Properties.Add("UserOid", oidClaim?.Value);
    }
}
```
**What have you tried so far?**
I'm able to use HttpContextRequestTelemetryInitializer as a singleton in .NET core application. But I'm not sure how to make it work in a .NET Framework 4.8 app, given that there are complexities of adding dependency injection and lack of httpContextAccessor in .NET Framework 4.8.

**Comment by cijothomas** [comment]
I am not sure where you got this example from - I don't see that in any official docs. If it is in any official doc - please share here (so as to remove it from the doc)

It won't work for ASP.NET.
It may work for ASP.NET Core, but definitely not safe.
You may look at the example initializers in this repo and borrow that approach for ASP.NET and ASP.NET Core.

**Comment by pharring** [comment]
@cijothomas see https://docs.microsoft.com/azure/azure-monitor/app/api-filtering-sampling#add-information-from-httpcontext

**Comment by cijothomas** [comment]
Thanks @pharring for sharing. I'll open a doc issue to remove it or fix it.

Old discussions: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1313

**Comment by cijothomas** [comment]
@sushanti Please use the approach from the existing initializers in this repo for aspnet and aspnetcore.
I have opened a doc issue to address the correctness issue.

**Comment by sushanti** [comment]
Thanks!
