### ISSUE TITLE
Custom metrics saved as log based metrics?

### ISSUE THREAD

**Issue by v-oleg** [microsoft/ApplicationInsights-dotnet#2554]
netcoreapp3.1
Azure function on a dedicated app service
Microsoft.ApplicationInsights nuget package version is 2.20.0
host.json
```
{
    "version": "2.0",
    "logging": {
        "fileLoggingMode": "debugOnly",
        "logLevel": {
            "Function": "Information",
            "Integrations.TrackingUpload.Scheduler.SchedulerFunction": "Information",
            "Host.Results": "Information",
            "default": "Warning"
        },
        "applicationInsights": {
            "samplingSettings": {
                "excludedTypes": "Request,Exception",
                "isEnabled": true
            }
        }
    }
}
```

I'm trying to create custom metrics with custom namespaces, but metrics save under the log-based metrics namespace (see screenshot1). And sometimes custom metrics saved under custom namespace (Screenshot2)

The line to send metrics:
`telemetryClient.GetMetric(new MetricIdentifier("Integrations.TrackingUpload", "OrdersScheduled", "Type", "PlatformSource", "StoreIntegrationId")).TrackValue(1, "WooCommerceV2", "WithoutSerialNumbers", "1");`

Here is a json sent
```
{
    "name": "AppMetrics",
    "time": "2022-03-12T01:33:04.0000000Z",
    "iKey": "xxx",
    "tags": {
        "ai.cloud.roleInstance": "ILC002856967610",
        "ai.operation.id": "2d156447005c3b4ab7eaafbbb8bd8deb",
        "ai.operation.parentId": "3745a5d600a9e84d",
        "ai.operation.name": "SchedulerFunction",
        "ai.location.ip": "0.0.0.0",
        "ai.internal.sdkVersion": "af_m-agg2c:2.17.0-146",
        "ai.internal.nodeName": "ILC002856967610"
    },
    "data": {
        "baseType": "MetricData",
        "baseData": {
            "ver": 2,
            "metrics": [{
                "ns": "Integrations.TrackingUpload",
                "name": "OrdersScheduled",
                "kind": "Aggregation",
                "value": 5,
                "count": 3,
                "min": 1,
                "max": 2,
                "stdDev": 0.4714045207910313
            }],
            "properties": {
                "LogLevel": "Information",
                "InvocationId": "43270bca-8914-4a13-87d9-c661bc8564d1",
                "ProcessId": "8592",
                "HostInstanceId": "038e03a6-f06c-4b96-b7d5-2b33849e74aa",
                "PlatformSource": "WooCommerceV2",
                "Type": "WithoutSerialNumbers",
                "_MS.AggregationIntervalMs": "57000",
                "Category": "Function.SchedulerFunction",
                "StoreIntegrationId": "1"
            }
        }
    }
}
```

Based on the [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics#pre-aggregated-metrics) using GetMetric() should result in pre-aggregated metrics. 

Could you please help to figure out what is going on? Am I missing something?

Thank you1 

Screenshot1
![image](https://user-images.githubusercontent.com/82014227/157999388-66bf0146-a4dc-474e-9a74-486c688f8649.png)

Screenshot2
![image](https://user-images.githubusercontent.com/82014227/157999818-e70ead65-3c9d-4412-8b26-44633762dabb.png)

**Comment by cijothomas** [comment]
If you're running the application in Azure Functions, please file an issue [here](https://github.com/Azure/azure-functions-host/issues/new/choose), as Azure Functions uses a special integration with Application Insights.
If this is reproducible outside Azure Functions, you can open issue in this repo.
