### ISSUE TITLE
All telemetry is listed exactly twice

### ISSUE THREAD

**Issue by cernuto** [microsoft/ApplicationInsights-dotnet#2555]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that we are using:

1. Microsoft.Orleans.Hosting.ServiceFabric (3.6.0)
2. Microsoft.ApplicationInsights (2.20.0)

* Runtime version is net 6

* Hosting environment is Service Fabric, Orleans, 1-node local cluster. Application Insights is hosted in Azure

All telemetry is duplicated as shown:

![image](https://user-images.githubusercontent.com/37497959/158006442-1add6158-11af-4f27-b752-e1e7b54cae1b.png)

We've tried a few different things for our ILogger DI to no avail:

- logger.AddApplicationInsights() ILogger
- Serilog with logger.AddSerilog()
- Custom ILoggerProvider with TelemetryClient(). Step through in our ILogger implementation instantiated by our provider shows items being received and propagated to TelemetryClient one time only, with no dupes. For this reason we believe the dupes issue is occurring downstream.

The debug output window does not show duplicates when used as a sink. Local file entries do not show dupes either. All traces of anything (dlls,etc..) Application Insights-related has been removed from the solution, and then rebuilt.

**Comment by cijothomas** [comment]
If you can share a minimal repro app, we can quickly tell if the SDK has been setup correctly.
Also, if the sdkversion field from the telemetry can be shared, that can offer some hints about this as well.

**Comment by cernuto** [comment]
An update: I created a 2nd instance of Application Insights in Azure, directed the telemetry to it, and the dupes are gone in the 2nd instance. So, I have something configured wrong somewhere with the 1st AI instance? Strange, what could it be?

![image](https://user-images.githubusercontent.com/37497959/158726299-20df52fa-8202-4d21-ad57-ca78a47304f3.png)

**Comment by cijothomas** [comment]
Without a repro application, its not possible to tell.. You may have added ApplicationInsights twice... Might be an issue in application insights backend.. Not possible to conclude anything without a repro app. (To check whether backend issue - need to open a support ticket with Azure).

I'll close this issue now, as the original issue is resolved.
