### ISSUE TITLE
EnableQuickPulseMetricStream set to false not taking effect 

### ISSUE THREAD

**Issue by AndyHiron** [microsoft/ApplicationInsights-dotnet#2557]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights 2.20.0
Microsoft.ApplicationInsights.WorkerService 2.20.0
and
Microsoft.Extensions.DependencyInjection 6.0.0
Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0
Microsoft.Identity.Client.Desktop 4.41.0
System.Runtime.CompilerServices.Unsafe 6.0.0

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
NetFramework4.7.2

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
Windows

### Describe the bug
Attempting to override the default setting of EnableQuickPulseMetricStream from true to false has not had the desired effect, i.e., telemetry output contains "AppMetrics" entries detailing the memory, processor and IO stats for the machine that the app is running on. The entries appear at a frequency of one minute.

Two attempts have been made to disable the default setting. The first was by calling the ConfigureTelemetryModule method:
```
services = new ServicesCollection();

////
services.ConfigureTelemetryModule<QuickPulseTelemetryModule>(
        (module, o) =>
        {
                 o.EnableQuickPulseMetricsStream = false;
        });

services. AddApplicationInsightsTelemetryWorkerService(myInstrumentationKey);
////
var serviceProvider = services.BuildServiceProvider();
var telemetryClient = serviceProvider.GetRequiredService<TelemetryClient>();
```

The second attempt was by creating an ApplicationInsightsServiceOptions object - replacing the code above between the pair of "////" with the following
```
var appInsightsOptions = new Microsoft.ApplicationInsights.WorkerService.ApplicationInsightsServiceOptions
{
        EnableQuickPulseMetricsStream = false,
        InstrumentationKey = myInstrumentationKey
}

services. AddApplicationInsightsTelemetryWorkerService(appInsightsOptions);
```
Neither approach was successful: am I doing something wrong, or is there a bug preventing EnableQuickPulseMetricStream being recognised as false?

Thank you

**Comment by cijothomas** [comment]
> telemetry output contains "AppMetrics" entries detailing the memory, processor and IO stats for the machine that the app is running on

^ This is unrelated to `EnableQuickPulseMetricsStream`

**Comment by AndyHiron** [comment]
Thank you for the clarification. In case it is of benefit to others to know, after further investigation I found that it was ApplicationInsightsServiceOptions EnablePerformanceCounterCollectionModule that I needed to disable.
