### ISSUE TITLE
String.empty will still result in capturing NodeName and RoleInstance of computer

### ISSUE THREAD

**Issue by StevenBucher98** [microsoft/ApplicationInsights-dotnet#2558]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: 2.15.0
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): 2.20.0
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Windows, Linux, Mac.

### Describe the bug

We noticed we were unintentionally collecting computer node name in our PowerShell telemetry. We did a fix back in the fall and had the values for `Context.GetInternalContext().NodeName` and `Context.Cloud.RoleInstance` as `string.Empty`. This however did not fix the issue as expected and was recently brought to our attention. We created a new fix that can be seen here in this PR. https://github.com/PowerShell/PowerShell/pull/16981/files

We wanted to be sure you were aware of this regression and if there is any plans to add validation to ensure we do not regress again?

cc: @SteveL-MSFT, @JamesWTruher, @TravisEz13

**Comment by cijothomas** [comment]
If you populate a non-empty string to role/instance, then the built-in initializers does not override them.
