### ISSUE TITLE
How can I configure the TelemetryClient when using ApplicationInsightsTraceListener?

### ISSUE THREAD

**Issue by asos-richardgibson** [microsoft/ApplicationInsights-dotnet#2561]
* **Nuget packages:**
   ```
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.20.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.TraceListener" Version="2.20.0" />
   ```
* **Target framework:** `<TargetFramework>net6.0</TargetFramework>`
* **Hosting environment:** Console App

**What are you trying to achieve?**

I'm trying to move from a custom-written logger to using the ApplicationInsightsTraceListener, but as far as I can tell there's no way to configure the TelemetryClient used; the ApplicationInsightsTraceListener always simply instantiates its own one.

Before, I had code such as this:

```
        var telemetryConfiguration =
            new TelemetryConfiguration(config["ApplicationInsights:InstrumentationKey"])
            {
                TelemetryChannel = new InMemoryChannel(),
                TelemetryInitializers =
                {
                    new CustomTelemetryInitializer()
                }
            };

        var telemetryClient = new TelemetryClient(telemetryConfiguration)
        {
            Context =
            {
                Cloud =
                {
                    RoleName = typeof(Program).Assembly.GetName().Name,
                    RoleInstance = Environment.MachineName
                }
            }
        };
```

and I was then wrapping the telemetry client up in my own logging abstraction. I'd like to move over to using the ApplicationInsightsTraceListener but I have no way to bring this customisation code over because ApplicationInsightsTraceListener doesn't have a constructor that takes a TelemetryClient.

What am I supposed to do in this scenario? I also looked into making modifications to TelemetryConfiguration.Active but that's been deprecated. I currently don't see any way of using the `ApplicationInsightsTraceListener` with any TelemetryInitializers or the ability to set the cloud role name or instance.

**Comment by cijothomas** [comment]
For logging adapters (except ILogger), the only workaround is to use `TelemetryConfiguration.Active`, even though its obsolete.

**Comment by cijothomas** [comment]
Closing as the original qn is answered.

**Comment by siewers** [comment]
Would it be possible to create a constructor overload that accepts a TelemetryConfiguration?
