### ISSUE TITLE
EnableEventCounterCollectionModule set to true not taking effect

### ISSUE THREAD

**Issue by Jithesh-Menon** [microsoft/ApplicationInsights-dotnet#2567]
List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights 2.20.0
Microsoft.ApplicationInsights.WorkerService 2.20.0
and
Microsoft.Extensions.DependencyInjection 6.0.0
Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0
Microsoft.Identity.Client.Desktop 4.41.0
System.Runtime.CompilerServices.Unsafe 6.0.0

Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the *.csproj file):
NetFramework4.7.2

Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
Windows

**What are you trying to achieve?**
Attempting to set the EnableEventCounterCollectionModule to true has not had the desired effect while running from a WPF application. I am expecting the events to be appeared in the app insights logs as described in the MSDN documentation :- https://docs.microsoft.com/en-us/azure/azure-monitor/app/eventcounters particularly for the property "AppRoleInstance" with my machine name associated with it.

var appInsightsOptions = new Microsoft.ApplicationInsights.WorkerService.ApplicationInsightsServiceOptions
{
        EnableEventCounterCollectionModule = true,
        InstrumentationKey = myInstrumentationKey
}

services. AddApplicationInsightsTelemetryWorkerService(appInsightsOptions);

The above was the approach I tried but wasn't successful: am I doing something wrong, or is there a bug preventing EnableEventCounterCollectionModule being recognised?

**Comment by Jithesh-Menon** [comment]
Hi Cijo,

Appreciate the quick turn around.

As you mentioned in your comment, I have opt-in "System.Runtime". Please see the code I have tried below.

 services.TryAddSingleton<ITelemetryModule, EventCounterCollectionModule>();
                    services.ConfigureTelemetryModule<EventCounterCollectionModule>(
                        (module, o) =>
                        {
                            // This removes all default counters, if any.
                            module.Counters.Clear();

                            // This adds a user defined counter "MyCounter" from EventSource named "MyEventSource"
                            module.Counters.Add(new EventCounterCollectionRequest("MyEventSource", "MyCounter"));

                            // This adds the system counter "gen-0-size" from "System.Runtime"
                            module.Counters.Add(new EventCounterCollectionRequest("System.Runtime", "gen-0-size"));
                        }
                    );
                    services.AddApplicationInsightsTelemetryWorkerService(appInsightsOptions);

But still in the logs, I don't see any events for customer metrics.
customMetrics 
| where name contains "System.Runtime"

**Comment by Jithesh-Menon** [comment]
Thank you for your prompt suggestion. But unfortunately we are using NetFramework4.7.2 version and dotnet-counters documentation mention about .Net Core 3.0 SDK and later versions.

**Comment by cijothomas** [comment]
I dont think EventCounters would work in NetFramework apps.
