### ISSUE TITLE
AddAutoCollectedMetricExtractor set to true not taking effect

### ISSUE THREAD

**Issue by Jithesh-Menon** [microsoft/ApplicationInsights-dotnet#2568]
List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights 2.20.0
Microsoft.ApplicationInsights.WorkerService 2.20.0
and
Microsoft.Extensions.DependencyInjection 6.0.0
Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0
Microsoft.Identity.Client.Desktop 4.41.0
System.Runtime.CompilerServices.Unsafe 6.0.0

Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the *.csproj file):
**NetFramework4.7.2**

Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
**Windows**

What are you trying to achieve?
Attempting to set the AddAutoCollectedMetricExtractor to true has not had the desired effect while running from a **WPF application**. I am expecting the metrics about Requests/Dependencies to be appeared in the app insights logs as described in the MSDN documentation :- [https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#using-applicationinsightsserviceoptions](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#using-applicationinsightsserviceoptions) particularly for the property "AppRoleInstance" with my machine name associated with it.

```
var appInsightsOptions = new Microsoft.ApplicationInsights.WorkerService.ApplicationInsightsServiceOptions
{
AddAutoCollectedMetricExtractor = true,
InstrumentationKey = myInstrumentationKey
}
services. AddApplicationInsightsTelemetryWorkerService(appInsightsOptions);
```

NB:- **I could see the AppMetrics telemetry information in the output window of Visual studio, but not getting the same info in app insights while querying**

Query used:- 
**TimeRange :- Last 24 hours**
Scope:- Resource level - App insights 
```
customMetrics
| where cloud_RoleInstance hasprefix "MyMachine"
```
Scope:- Subscription level
```
AppMetrics
| where AppRoleInstance hasprefix "MyMachine"
```

The above was the approach I tried but wasn't successful: am I doing something wrong, or is there a bug preventing AddAutoCollectedMetricExtractor being recognised? Also we don't have enough documentation on "AddAutoCollectedMetricExtractor" setting.

Also, would it be possible to confirm which all settings of app insights flag support .NetFramework 4.7.2. Because some of the below flags doesn't work the way it should while using it in .NetFramework.

**1. EnablePerformanceCounterCollectionModule
2. EnableDiagnosticsTelemetryModule
3. EnableEventCounterCollectionModule
4. EnableDependencyTrackingTelemetryModule
5. EnableAppServicesHeartbeatTelemetryModule
6. EnableAzureInstanceMetadataTelemetryModule
7. EnableQuickPulseMetricStream
8. EnableAdaptiveSampling
9. EnableHeartbeat
10. AddAutoCollectedMetricExtractor
11. RequestCollectionOptions.TrackExceptions
12. EnableRequestTrackingTelemetryModule**

**Comment by Jithesh-Menon** [comment]
Can someone please check and assist on this query?

**Comment by cijothomas** [comment]
>  I am expecting the metrics about Requests/Dependencies to be appeared in the app insights logs

`AddAutoCollectedMetricExtractor` does not send anything to logs. It only sends metrics to the metrics store, and only queryable from MetricExplorer.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics#pre-aggregated-metrics

**Comment by Jithesh-Menon** [comment]
Hi @cijothomas ,

Ok.. So does this mean, if I disable **AddAutoCollectedMetricExtractor**  app insights settings option in my application, will it stop sending app metrics to metrics store..?

**Comment by cijothomas** [comment]
> For instance, I am capturing the App Metrics of Server response time from Metrics store by enabling this setting. If I disable this, will it stop sending Server response time metric details to Metric store.?

Yes.

**Comment by Jithesh-Menon** [comment]
Thank you!

But in my case, I could still see the Server response time metric log present in Metric store even after disabling "AddAutoCollectedMetricExtractor" setting.

**Comment by cijothomas** [comment]
If you disable it from SDK, then backend automatically produce the metric and store in Metrics store.

**Comment by cijothomas** [comment]
> If you disable it from SDK, then backend automatically produce the metric and store in Metrics store.

This is *purely* at backend.

**Comment by Jithesh-Menon** [comment]
Alright. If that is the case, is there any way to ensure enabling/disabling of this setting works fine as expected..?

Because, even if we disable it from code, the metrics logs are still getting updated with server response time. Which is slightly confusing.

**Comment by cijothomas** [comment]
> Alright. If that is the case, is there any way to ensure enabling/disabling of this setting works fine as expected..?
> 
> Because, even if we disable it from code, the metrics logs are still getting updated with server response time. Which is slightly confusing.

I am not sure which part is confusing. This is as documented (https://docs.microsoft.com/en-us/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics#pre-aggregated-metrics)
![image](https://user-images.githubusercontent.com/5232798/162452629-17a27c2b-5c35-4f0a-bd0c-cd4aa4392838.png)


The `AddAutoCollectedMetricExtractor` setting is an SDK setting, and it control whether SDK produces pre-agg metrics. And it works as expected.

Backend has so many features, (auto creating metrics being one of them), and you cannot control all of them from this SDK. (To the best of my knowledge, there is no way to turn off backend from doing this. But you may open a Azure support ticket to see if Azure can disable it in backend. This repo can offer help with SDK questions only, for anything about backend, I'd suggest support ticket route.)

**Comment by Jithesh-Menon** [comment]
Thank you @cijothomas for the detailed explanation. :)
