### ISSUE TITLE
EnableAdaptiveSampling with "excludedTypes" not taking effect

### ISSUE THREAD

**Issue by Jithesh-Menon** [microsoft/ApplicationInsights-dotnet#2570]
List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights 2.20.0
Microsoft.ApplicationInsights.WorkerService 2.20.0
and
Microsoft.Extensions.DependencyInjection 6.0.0
Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0
Microsoft.Identity.Client.Desktop 4.41.0
System.Runtime.CompilerServices.Unsafe 6.0.0

Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the *.csproj file):
**NetFramework4.7.2**

Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
**Windows**

### Describe the bug
Attempting to use the default setting of EnableAdaptiveSampling - true and setting exclude types has not had the desired effect. i.e, trying to exclude the "Dependency" from the app insights logging [_and also tried with "Request"_] still logs details into app insights for the cloud role instance (my machine) that the app is running on. 

Referred the below links :-
[Configuring adaptive sampling for ASP.NET applications](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#adaptive-sampling)
[https://github.com/toddkitta/azure-content/blob/master/articles/application-insights/app-insights-sampling.md](https://github.com/toddkitta/azure-content/blob/master/articles/application-insights/app-insights-sampling.md)

**Approach:- Configure adaptive sampling in code**
EnableDependencyTrackingTelemetryModule and EnableAdaptiveSampling settings set to **true**

```
 var telemetryConfig = serviceProvider.GetRequiredService<TelemetryConfiguration>();

  var builder = telemetryConfig.DefaultTelemetrySink.TelemetryProcessorChainBuilder;

  // Alternately, the following configures adaptive sampling with 5 items per second, and also excludes
  // DependencyTelemetry from being subject to sampling.
  builder.UseAdaptiveSampling(maxTelemetryItemsPerSecond:5, excludedTypes: "Dependency");

  builder.Build();
```

But the above approach didn't reflect and does provide results for KQL query.

```
union requests,dependencies,pageViews,browserTimings,exceptions,traces
| where cloud_RoleInstance contains "MyMachine"
and timestamp >= todatetime('2022-04-04T12:19:00.775Z') 
and timestamp <= todatetime('2022-04-04T12:22:13.538Z')
```

Please check and advise.

Thank you.

**Comment by cijothomas** [comment]
Please share a minimal repro application demonstrating the issue. its not clear how are you concluding "not taking effect".
code sample, along with the actual queries used to validate if sampling is done would help us understand the question better.

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#knowing-whether-sampling-is-in-operation

**Comment by cijothomas** [comment]
>  app insights by excluding the "Dependency"

ExcludedTypes in UseAdaptiveSampling - means just the opposite. i.e Dependency items are *NOT* considered for sampling, means they are *always* sent. You want the opposite, based on your description.

**Comment by Jithesh-Menon** [comment]
Thank you!

So, how could we ensure the Dependency is not considered for sampling while it is present in application insights logs.

Could you please advise?

**Comment by cijothomas** [comment]
// Alternately, the following configures adaptive sampling with 5 items per second, and also excludes
  // DependencyTelemetry from being subject to sampling.
  builder.UseAdaptiveSampling(maxTelemetryItemsPerSecond:5, excludedTypes: "Dependency");

**Comment by Jithesh-Menon** [comment]
> // Alternately, the following configures adaptive sampling with 5 items per second, and also excludes // DependencyTelemetry from being subject to sampling. builder.UseAdaptiveSampling(maxTelemetryItemsPerSecond:5, excludedTypes: "Dependency");

This code will ensure Dependency is being excluded from Sampling. But how could we verify it got excluded..? Could you please provide a clarification on that..?

**Comment by tlsun0921** [comment]
i tried to exclude the following types in ApplicationInsights.config from sampling 
![image](https://user-images.githubusercontent.com/131897323/234937502-92873552-cd26-4fc9-8f88-51c074d673cd.png)

after more than 1 day i run the query to confirm, request type is still sampled.
![image](https://user-images.githubusercontent.com/131897323/234937680-51820578-a9a3-4a78-81a4-4c944701921a.png)

anyone know if there is anything wrong? thank you
