### ISSUE TITLE
How to configure ApplicationInsight to get connection string from web.config or keyvault or programmatically?

### ISSUE THREAD

**Issue by hercul1017** [microsoft/ApplicationInsights-dotnet#2571]
Nuget: Microsoft.ApplicationInsights; and bunch of Microsoft.AI.* started packages.
Runtime: net48
Hosting environment: Windows 10 for dev and prod will be in Azure
Application: ASP.NET MVC app .NET 4.8

**What are you trying to achieve?**
I am trying to setup dev, test and production environment in Azure. For that, I want to get  app insight connection string value from web.config then from keyvault.  Other suggestions also welcomed. 

**What have you tried so far?**
I tried to create telemetryclient by supplying config value, but it didn't work. It always get connectionstring value from ApplicationInsight.config file. 

Thanks

**Comment by cijothomas** [comment]
> I tried to create telemetryclient by supplying config value, but it didn't work. 

Need to see how you are doing this to see if this is right/wrong.

`TelemetryConfiguration.Active` is the recommended way to modify ConnectionString, for .NET Framework apps.
