### ISSUE TITLE
Insert custom TelemetryProcessor at specific place in the processing pipeline

### ISSUE THREAD

**Issue by luk355** [microsoft/ApplicationInsights-dotnet#2572]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: 
   **Microsoft.ApplicationInsights.AspNetCore v2.20.0**
* Runtime version:
   **net6.0**
* Hosting environment: 
   **Windows**

**What are you trying to achieve?**

In my use-case I need to drop specific telemetry items. In order to do so, I want to add custom TelemetryProcessor into the processing pipeline. The default processing pipeline with sampling disabled consists of `AutocollectedMetricsExtractor -> QuickPulse -> TransmissionProcessor` processors. I thought it would be useful to still collect metrics and have QuickPulse integration for dropped items so I really wanted to place my processor just before the `TransmissionProcessor`. So the pipeline would look like:

```AutocollectedMetricsExtractor -> QuickPulse -> CUSTOMPROCESSOR -> TransmissionProcessor```

The same problem is present for processing pripeline with sampling enabled.

**What have you tried so far?**
* `AddApplicationInsightsTelemetryProcessor<TProcessor>()` extension method will always add processor at the very start of the processing pipeline
* `DefaultTelemetrySink.TelemetryProcessorChainBuilder.Use<TProcessor>()`  will also only allow to insert to very start
* there seems to be no way to achieve this on `TelemetryConfiguration` configuration class

**Comment by cijothomas** [comment]
For example: hand-creating QuickPulse should follow similar approach as here: https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Shared/Implementation/TelemetryConfigurationOptionsSetup.cs#L297

**Comment by cijothomas** [comment]
> AddApplicationInsightsTelemetryProcessor<TProcessor>() extension method will always add processor at the very start of the processing pipeline

I am not so sure if this is true... Depending on if the above was added Before/After services.AddApplicationInsightsTelemetry(), it might do the trick for you? Please try this and let us know

**Comment by luk355** [comment]
thanks for your response, @cijothomas. 

> I am not so sure if this is true... Depending on if the above was added Before/After services.AddApplicationInsightsTelemetry(), it might do the trick for you? 

unfortunately, this does not work. The order of the registrations of telemetryProcessor and AppInsightsTelemetry does not affect the processor order.

I got what I needed working by disabling built-in processors and manually building the processor pipeline via custom `IConfigureOptions<TelemetryConfiguration>` implementation.
