### ISSUE TITLE
A couple of questions about contextual data not being included

### ISSUE THREAD

**Issue by johnknoop** [microsoft/ApplicationInsights-dotnet#2577]
If this is the wrong repository to ask these questions, please point me to the right one so that I can open a ticket in there instead.

## Background

I’ve been using Serilog with the Serilog.Sinks.ApplicationInsights sink for years, but it’s increasingly obvious that this package is no longer actively maintained, and so a lot of things are not working anymore.

I’m exploring the possibility of throwing out Serilog and adopting `Microsoft.Extensions.Logging.ApplicationInsights` instead. But before doing that, I’m spending some time researching what isn’t working today and to what extent it’s because of Serilog, or if the fault lies with `Microsoft.ApplicationInsights.AspNetCore`.

### What I need

I want all my **traces**, **requests** AND **exceptions** in AI to contain
- The user id (email)
- The tenant id (user organization)
- Operation id for correlation
- The entire URL including query (when in the context of an HTTP request)

For the first three, it should use the AI tags `ai.user.id`, `ai.user.accountId` and `ai.operation.id`, correct?

## What I've found

In order to know what is working and what is not, I'm intercepting the raw data that is sent to AI and here’s what I’ve found:

### For ASP.NET requests

By default, the RequestTelemetry that get created by `Microsoft.ApplicationInsights.AspNetCore` don’t get the correct `ai.operation.id` tag. Instead of the ASP.NET trace identifer, it's just some guid. So I have to add some code in the beginning of the ASP.NET request pipeline, but that’s ok since I want to do that in order to set the `user.id` tag anyway:

```cs
.Use(async (context, next) =>
{
    var requestTelemetry = context.Features.Get<Microsoft.ApplicationInsights.DataContracts.RequestTelemetry>();
    
    if (context.User.Identity?.IsAuthenticated == true)
    {
        if (context.User.TryGetCurrentUserEmail(out var userEmail))
        {
            requestTelemetry.Context.User.AuthenticatedUserId = userEmail;
            requestTelemetry.Context.User.Id = userEmail;
        }
        
        var tenantKey = context.User.GetCurrentTenantKeyOrDefault();
        
        if (tenantKey != null)
        {
            requestTelemetry.Context.User.AccountId = tenantKey;
        }
    }
    
    var correlationId = context.TraceIdentifier;
    
    requestTelemetry.Context.Operation.Id = context.TraceIdentifier;
}
```

But the fact that I have to do this last line tells me that something is probably wrong, because why wouldn’t a package named Microsoft.ApplicationInsights.**AspNetCore** know to use the ASP.NET trace identifier as the operation id? Can someone confirm whether this is to be expected or not?

Also, the RequestTelemetry seems to have the wrong `ai.cloud.roleInstance`, which means the `ITelemetryInitializer` I’ve registered isn’t working for RequestTelemetries (but it **_is_** working for ExceptionTelemetries strangly enough). What might be the cause of this?

### For uncaught exceptions occuring within the scope of an ASP.NET request

Ok, now my RequestTelemetries have all the contextual data I want. Let’s take a look at exceptions. It turns out ExceptionTelemetries are lacking `user.id` and `operation.id`, even when the exception is thrown within the span of a request. So it doesn’t inherit these values from the spanning request.

Weirdly enough, it does have a property called `RequestId`, which is the correct ASP.NET trace identifier. So it does get _some_ data from the ASP.NET request, but not from the RequestTelemetry. Is this to be expected?

Also, even stranger, the ExceptionTelemetry DOES have the correct `ai.cloud.roleInstance` (which the RequestTelemetry lacked) so exception telemetry _does_ seem to be affected by ITelemetryInitializer whereas RequestTelemetries _don’t_. Can someone elaborate on this?

So the tags I need to manually add to each ExceptionTelemetry are:
- `ai.operation.id`
- `ai.user.accountId`
- `ai.user.id`

I've searched the web for ways to do this, but I've come up short. Any suggestions?

### For hosted services

I have a bunch of BackgroundServices and my problem today is that _traces_ are collected and sent to AI automatically through the Serilog.Sinks.ApplicationInsights sink, but these traces don’t get the correct context, even though I’m setting all contextual data using the Serilog equivalent of _logger.BeginScope. So I’m looking into how this would be solved, if I were to ditch Serilog.

I found [this page](https://docs.microsoft.com/en-us/azure/azure-monitor/app/worker-service) which suggests starting a `RequestTelemetry `operation in the hosted service:

```cs
using _telemetryClient.StartOperation<Microsoft.ApplicationInsights.DataContracts.RequestTelemetry>("some operation", "correlationId");
```

The page also suggests I’d install the `Microsoft.ApplicationInsights.WorkerService` package, but it’s not clear what I get from that package.

The first thing I notice is that the only way to get contextual data included is by doing so manually. I try and add a `_logger.BeginScope` just to test if it gets included, but it doesn’t. Can this be achieved by installing Microsoft.Extensions.Logging.ApplicationInsights? 

The second thing I notice is that exceptions in hosted service aren’t collected, even when they are thrown within the scope of a` using _telemetryClient.StartOperation(...)`.

This means I have to catch and manually call `TrackException`. Ok, cumbersome but doable. But the context from the ambient RequestTelemetry isn’t copied to the ExceptiontTelemetry automatically, forcing me to do this:

```cs
var ex = new Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry(new Exception("Oops exception in hosted service"));
ex.Context.User.AccountId = "TENANT_KEY";
ex.Context.Operation.Id = "correlationId";
_telemetryClient.TrackException(ex);
```

So what exactly did I get by installing Microsoft.ApplicationInsights.WorkerService?

### Minor thing you might wanna look into:
Doing _telemetryClient.StartOperation<Microsoft.ApplicationInsights.DataContracts.RequestTelemetry>("some operation", "correlationId") will put “correlationId” in the “ai_legacyRootId” property and not in the “ai.operation.id” tag. So I have to also set xxx.Telemetry.Context.Operation.Id.

### Also minor thing that isn’t a problem, just a little peculiar:
Also, when I inspect the data sent to AI, the RequestTelemetry started inside the hosted service contains a “responseCode” property in the BaseData collection, wich the value 200. Which is a little weird since there’s no HTTP request going on.

**Comment by cijothomas** [comment]
> I’ve been using Serilog with the Serilog.Sinks.ApplicationInsights sink for years, but it’s increasingly obvious that this package is no longer actively maintained, and so a lot of things are not working anymore.

Serilog sink is not owned by this repo.

**Comment by cijothomas** [comment]
> By default, the RequestTelemetry that get created by Microsoft.ApplicationInsights.AspNetCore don’t get the correct ai.operation.id tag. Instead of the ASP.NET trace identifer, it's just some guid

operation.id follows the https://www.w3.org/TR/trace-context/ specification. If you see it is not following the spec, open a new issue, with minimal repro app.

**Comment by cijothomas** [comment]
> Also, the RequestTelemetry seems to have the wrong ai.cloud.roleInstance, which means the ITelemetryInitializer I’ve registered isn’t working for RequestTelemetries (but it is working for ExceptionTelemetries strangly enough). What might be the cause of this?

Open a separate issue with a minimal repro app for this one.

**Comment by cijothomas** [comment]
Closing this issue - Check responses above.
1. This repo doesn't own serilog sinks, so can't help with issues from that.
2. For everything else, please open specific issue, with minimal repro. Its hard to say anything without specific repro step/repro app.

**Comment by johnknoop** [comment]
@cijothomas 

> Serilog sink is not owned by this repo.

I'm aware of that. That was just for context/background.

> Closing this issue - Check responses above.

What about all my questions? These are not bug reports. I don't know whether it's supposed to work like that or not. That's why I opened a "question" ticket and not a "bug report".

Please don't be so hasty to close this ticket, it took me a whole day of research to prepare it. Maybe you can leave it open until someone has had the chance to address my questions?

**Comment by johnknoop** [comment]
I've extracted the questions, please tell me if I need to create separate issues for each one or if it's ok to keep them in this issue.

### Question 1:

I want to make sure that all the telemetry is enriched with the ASP.NET trace identifier as operation id. In my project, this isn't happening automatically but that's ok, I can add it manually, but I want to make sure I add it to the correct property. Is `[telemetry].Context.Operation.Id` the place to store correlation id's? Because I'm also seeing that `ExceptionTelemetry` by default gets the ASP.NET trace identifier in it´s `Properties["RequestId"]`. So which is it? Should I put it in `[telemetry].Context.Operation.Id` or in `[telemetry].Properties["RequestId"]`? Or does it depend on the type of telemetry (RequestTelemetry vs ExceptionTelemetry)?

### Question 2:

`ExceptionTelemetry` are generated automatically when an uncaught exception occures within an ASP.NET request. Can someone point me to the recommended way of enriching these telemetries with contextual data such as the id of the current user?

### Question 3

What exactly does the `Microsoft.ApplicationInsights.WorkerService` package add? It's not clear from reading the documentation. It's recommended to add that package if you use hosted services, but since you still have to manually call `TelemetryClient.StartOperation` or `TelemetryClient.TrackException` in your hosted service, I don't see what the purpose of the `Microsoft.ApplicationInsights.WorkerService` package is. Can someone explain or point me to a text that describes this?

### Question 4

This question is also about hosted services in combination. I'm curious about the `Microsoft.Extensions.Logging.ApplicationInsights` package. If I install this package and log an exception in my hosted service, will that package then make sure to include the properties from the log scope in the resulting `ExceptionTelemetry`? Meaning, can I replace this code:
```cs
catch (Exception exception) { 
	var exceptionTelemetry = new Microsoft.ApplicationInsights.DataContracts.ExceptionTelemetry(exception);
	exceptionTelemetry.Context.User.AccountId = "TENANT_ID";
	exceptionTelemetry.Context.Operation.Id = "CORRELATION_ID";
	_telemetryClient.TrackException(exceptionTelemetry);
}
```
with this code
```cs
using (_logger.BeginScope(new Dictionary<string, string>
{
	["ai.user.accountId"] = "TENANT_ID",
	["ai.operation.id"] = "CORRELATION_ID",
}))
{
	_logger.LogWarning(exception, "...");
}
```
?

And if so, are those the correct strings to use as keys in the dictionary?

Thanks
John

**Comment by cijothomas** [comment]
I've extracted the questions, please tell me if I need to create separate issues for each one or if it's ok to keep them in this issue.

^ Please create separate issues with a matching Title (for future discoverability as well :))

**Comment by johnknoop** [comment]
Ok, i'll do that later tonight. Pasting this picture here in the meantime to help me remember later.

![image](https://user-images.githubusercontent.com/3394270/163438899-4ee93fc8-3d20-479d-a48c-2eebfd8c08ea.png)
