### ISSUE TITLE
How to use ASP.NET Trace Identifier as operation id?

### ISSUE THREAD

**Issue by johnknoop** [microsoft/ApplicationInsights-dotnet#2579]
I've added the `Microsoft.ApplicationInsights` and `Microsoft.ApplicationInsights.AspNetCore` packages to a .NET 6 project.

For the `RequestTelemetry` and `ExceptionTelemetry` sent to AI, I would like to use the autogenerated ASP.NET trace identifier to correlate multiple operations belonging to the same logical business transaction.

Is the `[telemetry].Context.Operation.Id` property the correct property used for this purpose? Because if so, it doesn't have the ASP.NET trace identifier as value by default.

In order to see what data actually gets sent to AI, I'm calling a controller action where I'm throwing an exception.

In this example request, the ASP.NET trace identifier was `0HMGVKORJ8R0B:00000002`. But when I inspect the `RequestTelemetry `sent to Application Insights, it has some GUID as `ai.operation id` instead.

```json
{
	"name": "AppRequests",
	"time": "2022-04-16T12:39:57.7980415Z",
	"iKey": "495b57dd-a45c-46b1-a940-cc9b7739b8e3",
	"tags": {
		"ai.cloud.role": "WebApp",
		"ai.cloud.roleInstance": "laptop1",
		"ai.user.id": "w1Ago/JiXNxFob2ELzGcMg",
		"ai.operation.id": "1328d445f4a63570e839095b1c6e71ac",
		"ai.operation.name": "GET ItemTree/Get",
		"ai.location.ip": "::ffff:172.24.0.1",
		"ai.internal.sdkVersion": "aspnet5c:2.20.0+51c3ed8aa3f32209edf01168f9136a3ac8486c5d",
		"ai.internal.nodeName": "22ab4e1751cf.localdomain"
	},
	"data": {
		"baseType": "RequestData",
		"baseData": {
			"ver": 2,
			"id": "0783d7e5664fd19f",
			"name": "GET ItemTree/Get",
			"duration": "00:00:00.4940005",
			"success": false,
			"responseCode": "500",
			"url": "http://localhost:5000/api/itemtree",
			"properties": {
				"DeveloperMode": "true",
				"AspNetCoreEnvironment": "Development",
				"_MS.ProcessedByMetricExtractors": "(Name:'Requests', Ver:'1.1')"
			}
		}
	}
}
```

Is there a way to get it to use the ASP.NET trace identifier instead? I know I can do it manually by adding a middleware delegate to the request pipeline like so:

```cs
.Use(async (context, next) => 
{
context.Features.Get<RequestTelemetry>().Context.Operation.Id = context.TraceIdentifier;
await next();
})
```
With this code, the `ai.operation.id` tag in the generated json gets the ASP.NET trace identifier as value, but is this really necessary, or might I have misconfigured the application somehow?

For `ExceptionTelemetry` it's a slightly different story. It actually has the ASP.NET trace identifer, albeit in the wrong place:

```json
{
	"name": "AppExceptions",
	"time": "2022-04-16T13:05:16.9561422Z",
	"iKey": "495b57dd-a45c-46b1-a940-cc9b7739b8e3",
	"tags": {
		"ai.cloud.role": "WebApp",
		"ai.cloud.roleInstance": "laptop1",
		"ai.user.id": "w1Ago/JiXNxFob2ELzGcMg",
		"ai.operation.id": "56a52a3a7e1c4bed8d0ff019b5afc0f5",
		"ai.operation.parentId": "c40f97f19b2c1eb9",
		"ai.operation.name": "GET ItemTree/Get",
		"ai.location.ip": "::ffff:172.24.0.1",
		"ai.internal.sdkVersion": "il:2.20.0-103",
		"ai.internal.nodeName": "22ab4e1751cf.localdomain"
	},
	"data": {
		"baseType": "ExceptionData",
		"baseData": {
			"ver": 2,
			"exceptions": [...],
			"severityLevel": "Error",
			"properties": {
				"DeveloperMode": "true",
				"EventId": "1",
				"ParentId": "0000000000000000",
				"_MS.ProcessedByMetricExtractors": "(Name:'Exceptions', Ver:'1.1')",
				"RequestPath": "/api/itemtree",
				"CategoryName": "Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware",
				"OriginalFormat": "An unhandled exception has occurred while executing the request.",
				"SpanId": "c40f97f19b2c1eb9",
				"FormattedMessage": "An unhandled exception has occurred while executing the request.",
				"RequestId": "0HMGVKORJ8R0B:00000002",
				"AspNetCoreEnvironment": "Development",
				"TraceId": "56a52a3a7e1c4bed8d0ff019b5afc0f5",
				"EventName": "UnhandledException",
				"ConnectionId": "0HMGVKORJ8R0B"
			}
		}
	}
}
```
As you can see, the ASP.NET trace identifier shows up, not in `tags["ai.operation.id"]` tag, but in `data.baseData.Properties.RequestId`. What is this property used for?

**Comment by cijothomas** [comment]
Correlation in ApplicationInsights SDK is based on https://www.w3.org/TR/trace-context/. The operation id is the "traceid" from the W3CTraceContext specification.

You may override it with anything custom, but it can break correlation.

The operationid for ExceptionTelemetry (or any telemetry) within the context of the Request, will automatically inherit the same operationid as the parent RequestTelemetry.

> It actually has the ASP.NET trace identifer, albeit in the wrong place:
The ExceptionTelemetry shown above is collected by LoggerProvider. It stores everything from Log state and Log Scopes into custom properties. There is no special casing for "RequestId".

**Comment by cijothomas** [comment]
> data.baseData.Properties.RequestId. What is this property used for?

ApplicationInsights does not use it. Its just like any other custom property.

**Comment by johnknoop** [comment]
> You may override it with anything custom, but it can break correlation.

The reason I need this is that me ASP.NET app publishes messages onto a service bus, and these messages contains a correlation id which the receiving applications use when logging traces to AI. And to my understanding, the recommended values to use as correlation id's for this purpose are the ASP.NET trace identifiers. Or is there a better way?

> The operation id is the "traceid" from the W3CTraceContext specification.

But which property in the intercepted JSON blob is it that AI uses for correlation? It can't be `data.baseData.properties.TraceId` because that property is only present on the ExceptionTelemetry and not on the RequestTelemetry. I suspect it's the `tags["ai.operation.id"]` property that is used for correlation. Can you confirm this?

> The operationid for ExceptionTelemetry (or any telemetry) within the context of the Request, will automatically inherit the same operationid as the parent RequestTelemetry.

But that's not the behavior I'm seeing. I've added a middleware delegate early in the request pipeline (upstream from when the endpoints are executed) that sets the  `requestTelemetry.Context.Operation.Id` property to a custom value. Then I throw an exception in the controller.

When I inspect the intercepted JSON blobs, I see two objects: One with `"name": "AppRequests"`, which has a property called `tags["ai.operation.id"]` that has a value corresponding to the `requestTelemetry.Context.Operation.Id` that I set in the middleware. The other object, with `"name": "AppException"`, has a different value in `tags["ai.operation.id"]`. Is this because it was generated by LoggerProvider? And why isn't it automatically inherited even if it's generated by LoggerProvider?

**Comment by cijothomas** [comment]
> And to my understanding, the recommended values to use as correlation id's for this purpose are the ASP.NET trace identifiers.

Where is this recommendation from? I'd like to see if there is any doc which recommends this, and suggest fixing it there.

**Comment by cijothomas** [comment]
> > And to my understanding, the recommended values to use as correlation id's for this purpose are the ASP.NET trace identifiers.
> 
> Where is this recommendation from? I'd like to see if there is any doc which recommends this, and suggest fixing it there.

ASP.NET Core natively understands W3CTraceContext, and creates `Activity` following that spec. This allows correlation (traceid is stored in Application Insights as operation id).

**Comment by cijothomas** [comment]
> tags["ai.operation.id"] property that is used for correlation. Can you confirm this?

Yes. The above is internal serialization details. The TelemetryContext.Operation.Id is the public API.

**Comment by cijothomas** [comment]
> One with "name": "AppRequests", which has a property called tags["ai.operation.id"] that has a value corresponding to the requestTelemetry.Context.Operation.Id that I set in the middleware. The other object, with "name": "AppException", has a different value in tags["ai.operation.id"]

Yes. By overriding OperationId for the parent RequestTelemetry to something custom, the correlation will be broken. (unless you manually override the same for ExceptionTelemetry as well).

(All telemetry correlations in-proc and based on `Activity.Current`. If any telemetry was manually overridden with custom operationid (instead of the default Activity.Current.TraceId), then it'll break correlation, unless the same overrides are done *manually* to each and every telemetry.)

**Comment by johnknoop** [comment]
> Where is this recommendation from? I'd like to see if there is any doc which recommends this, and suggest fixing it there.

It's not from any official AI documentation, but `Request.TraceIdentifier` is widely used as correlation id throughout the ASP.NET community.

> ASP.NET Core natively understands W3CTraceContext, and creates Activity following that spec. This allows correlation (traceid is stored in Application Insights as operation id).

So the GUID's that I'm seeing as default values of the `TelemetryContext.Operation.Id` property are W3CTraceContext trace ids? Do you know if there's anyway to access them in my application code? Like, is it available on `HttpRequestMessage` or something? Because I might as well use those as correlation id's on my service bus messages, instead of the TraceIdentifiers.

And do you know if `Request.TraceIdentifier` will also be harmonized with W3CTraceContext in the future?

**Comment by pharring** [comment]
> Do you know if there's anyway to access them in my application code? 
`Activity.Current.RootId`

**Comment by pharring** [comment]
Since you mentioned Service Bus correlation, you may be interested in the following article:
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing?tabs=net-standard-sdk-2

**Comment by johnknoop** [comment]
@pharring thanks! By the way, some sources suggest to use `Activity.Current.TraceId` and not `RootId`. What would be the difference? I've not been able to figure that out.

**Comment by pharring** [comment]
If you know that your activity ID format is `ActivityIdFormat.W3C`, then you can use `Activity.Current.TraceId.ToHexString()`.
Otherwise, `TraceId.ToHexString()` will return "000000..."
I feel that `.RootId` is safer because it works regardless of the activity ID format. It's also less typing.

**Comment by cijothomas** [comment]
`Activity.Current.TraceId` would be the "correct" one. `RootId` existed even before the W3CTraceContext was adopted by `Activity`. (Its true that the values match IFF ID format is set to W3C.

**Comment by cijothomas** [comment]
> And do you know if Request.TraceIdentifier will also be harmonized with W3CTraceContext in the future?

I am unsure of that. Its best to ask this in asp.net repo. https://github.com/dotnet/aspnetcore
You may want to bet on the W3CTraceContext, as that is an industry standard, and language/platform independent.

**Comment by cijothomas** [comment]
@johnknoop If all the questions for this issue is answered, please close this issue.

**Comment by johnknoop** [comment]
Thanks
