### ISSUE TITLE
Custom metric splitting on multiple dimensions

### ISSUE THREAD

**Issue by razvanim-uipath** [microsoft/ApplicationInsights-dotnet#2582]
On a custom metric I have multiple dimensions i.e. Service, Status, etc. I am interested in splitting the timeseries by multiple dimensions at the same time. For example when I split by both Service and Status I would see a TimeSeries for each active combination (Service1 - Status1 at time 1, Service 2 - Status 2 at time 1, and so on).

Currently the UI is limiting to splitting on only a single dimension, which makes investigation cumbersome. I.E. when I see that the Status is "Failed", I have to manually filter through all Service Instances, to see which one failed.

![image](https://user-images.githubusercontent.com/76792494/164552921-06a2c80a-7cc7-4732-bbc1-cb678180ba73.png)

**Comment by cijothomas** [comment]
This repro is for SDK related issues only. UI enhancements/suggestion are not to be posted here, as no one from the UI team is watching this repo.

**Comment by cijothomas** [comment]
https://feedback.azure.com/d365community/forum/8849e04d-1325-ec11-b6e6-000d3a4f09d0
