### ISSUE TITLE
Can't Correlate items logged within StartOperation

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [microsoft/ApplicationInsights-dotnet#2590]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:  
Microsoft.ApplicationInsights Version="2.20.0"
Microsoft.Extensions.DependencyInjection Version="6.0.0"
Microsoft.ApplicationInsights.DependencyCollector Version="2.20.0"
Microsoft.ApplicationInsights.AspNetCore Version="2.20.0"
Microsoft.ApplicationInsights.WorkerService Version="2.20.0"

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): net6
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): AKS, latest .net image, but also reproducible on MAC OSX (latest version of everything, os, vs for Mac, etc...)

### Describe the bug

When you start a operation using the StartOperation Api, the traces that occur within the context of that operation DO NOT carry the parent_operation_id of the operation, they carry a new one. Because the StartOperation may take place inside a already running operation (like a request), you can't determine if the traces belong to the sub operation or the main operation. This problem gets much worse if your global operation triggers multiple sub operations

Possibly related to #2536

### To Reproduce

[SampleSDKProblem.zip](https://github.com/microsoft/ApplicationInsights-dotnet/files/8617521/SampleSDKProblem.zip)

```
curl --location --request GET 'http://localhost:5000/WeatherForecast' \
--header 'traceparent: 00-0af7651916cd43dd8448eb211c80319a-b7ad6b7169200000-01' 
```

Results obtained:
<img width="630" alt="Screen Shot 2022-05-03 at 23 05 29" src="https://user-images.githubusercontent.com/5585339/166614524-8abd86f3-fe60-474f-af5b-84d908c53eb9.png">

<img width="563" alt="Screen Shot 2022-05-03 at 23 05 38" src="https://user-images.githubusercontent.com/5585339/166614537-88ee4583-e88f-4281-972d-e87a1351ec69.png">
<img width="596" alt="Screen Shot 2022-05-03 at 23 06 11" src="https://user-images.githubusercontent.com/5585339/166614540-22735f9f-ff38-4b0e-a3ce-9d18565c50a3.png">

### Expectation

The expectation is that there were a way to correlate the traces (img 3) to the operation (img 2) that "triggered" them, like the operation_parentId...

**Comment by Leonardo-Ferreira** [comment]
Curiously, on the console output, for the log of the transaction, there is the ID that will be used by the traces:

> Application Insights Telemetry: {"name":"AppTraces","time":"2022-05-04T22:35:55.7864190Z","iKey":"afae4f83-f817-44dc-82be-752ec5c3e108","tags":{"ai.application.ver":"1.0.0","ai.cloud.role":"Logging Middleware Test Client","ai.cloud.roleInstance":"MacBook-Pro.local","ai.operation.id":"0af7651916cd43dd8448eb211c80319a","ai.operation.parentId":"**aaa556efa12d9be5**","ai.operation.name":"POST WeatherForecast/PostEcho","ai.location.ip":"::1","ai.internal.sdkVersion":"dotnetc:2.20.0-103","ai.internal.nodeName":"MacBook-Pro.local"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"operation 1 teste","severityLevel":"Verbose","properties":{"DeveloperMode":"true","AspNetCoreEnvironment":"Development"}}}}
Application Insights Telemetry: {"name":"AppTraces","time":"2022-05-04T22:35:55.7908930Z","iKey":"afae4f83-f817-44dc-82be-752ec5c3e108","tags":{"ai.application.ver":"1.0.0","ai.cloud.role":"Logging Middleware Test Client","ai.cloud.roleInstance":"MacBook-Pro.local","ai.operation.id":"0af7651916cd43dd8448eb211c80319a","ai.operation.parentId":"**aaa556efa12d9be5**","ai.operation.name":"POST WeatherForecast/PostEcho","ai.location.ip":"::1","ai.internal.sdkVersion":"dotnetc:2.20.0-103","ai.internal.nodeName":"MacBook-Pro.local"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"operation 2 teste","severityLevel":"Verbose","properties":{"DeveloperMode":"true","AspNetCoreEnvironment":"Development"}}}}
Application Insights Telemetry: {"name":"**AppDependencies**","time":"2022-05-04T22:35:55.7811370Z","iKey":"afae4f83-f817-44dc-82be-752ec5c3e108","tags":{"ai.application.ver":"1.0.0","ai.cloud.role":"Logging Middleware Test Client","ai.cloud.roleInstance":"MacBook-Pro.local","ai.operation.id":"0af7651916cd43dd8448eb211c80319a","ai.operation.parentId":"9adeca595dce6218","ai.operation.name":"POST WeatherForecast/PostEcho","ai.location.ip":"::1","ai.internal.sdkVersion":"dotnetc:2.20.0-103","ai.internal.nodeName":"MacBook-Pro.local"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"teste 1","id": **"aaa556efa12d9be5" <<<----- LOOK HERE**, "duration":"00:00:00.0132592","success":true,"properties":{"_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","DeveloperMode":"true","AspNetCoreEnvironment":"Development"}}}}

**Comment by cijothomas** [comment]
I am not sure which part is unexpected here? It looks like everything is working as expected. https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation

**Comment by cijothomas** [comment]
[HttpGet]
        public IEnumerable<WeatherForecast> Get() // This whole will be part of the RequestTelemetry. The RequestTelemetry itself gets the same traceid as passed via traceparent, and will have parent as the spanid from the passed in traceparent.
        {
            var op = _logger.StartOperation<DependencyTelemetry>("OP 1");  // This will create a DependencyTelemetry1, as child of the above RequestTelemetry

            _logger.TrackTrace("I came from OP 1");  //will be child of DependencyTelemetry1
            _logger.TrackTrace("I also came from OP 1");//will be child of DependencyTelemetry1
            _logger.TrackTrace("I also me from OP 1");//will be child of DependencyTelemetry1

            _logger.StopOperation(op);

            var op2 = _logger.StartOperation<DependencyTelemetry>("OP 2"); // This will create a DependencyTelemetry2, as child of the above RequestTelemetry 

            _logger.TrackTrace("I came from OP 2!!!!"); //will be child of DependencyTelemetry1
            _logger.TrackTrace("I also came from OP 2!!!!"); //will be child of DependencyTelemetry1
            _logger.TrackTrace("I also me from OP 2!!!!"); //will be child of DependencyTelemetry1

            _logger.StopOperation(op2);

            return null;
        }

**Comment by cijothomas** [comment]
Its hard to manually correlate from the console output, but you can use https://docs.microsoft.com/en-us/azure/azure-monitor/app/transaction-diagnostics

Closing as no issue. Reopen if you have further questions/something not working as described.
