### ISSUE TITLE
Can I use `ActivitySource.StartActivity` instead of `TelemetryClient.StartOperation`?

### ISSUE THREAD

**Issue by johnknoop** [microsoft/ApplicationInsights-dotnet#2596]
My .NET 6 Asp.Net app has some background services that runs code periodically, and I want each of those runs to be traced as distinct operations.

Currently I'm using `TelemetryClient.StartOperation` for this purpose, but I would like to switch to the `System.Diagnostics.ActivitySource.StartActivity` API instead.

According to [this page](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-collection-walkthroughs) it should be possible to use `ActivitySource.StartActivity` and have them collected by AI:

> Distributed tracing telemetry is automatically captured after configuring the Application Insights SDK for [ASP.NET](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net) or [ASP.NET Core](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core) apps, or by enabling [code-less instrumentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/codeless-overview).

I've registered a singleton `ActivitySource` which I'm using to start activities, but any time I call `_activitySource.StartActivity` it just returns `null`, which is a sign that no-one is listening for it. And this is weird, because I have both `Microsoft.ApplicationInsights` and `Microsoft.ApplicationInsights.AspNetCore` installed.

Any idea what might be wrong?

**Comment by pharring** [comment]
The Application Insights SDK uses the static Activity.Current property to determine the current activity. Unfortunately, as you've discovered, Activity.Current isn't set unless someone's listening.

You can try adding this workaround somewhere in your startup code:

```csharp
ActivitySource.AddActivityListener(new ActivityListener
{
    ShouldListenTo = _ => true,
    Sample = (ref ActivityCreationOptions<ActivityContext> _) => ActivitySamplingResult.AllDataAndRecorded
});
```

This adds a dummy global listener which has the side-effect of setting Activity.Current even when no-one else is listening.

**Comment by cijothomas** [comment]
`ActivitySource` is a newly introduced concept in DiagnosticSource to mainly address OpenTelemetry scenarios., This repo does not support it (i.e you cannot replace telemetryCLient.StartOperation with activitySource.StartActivity).

The OpenTelemetry based ApplicationInsights is in preview right now - check docs : https://docs.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=net

The OpenTelemetry based ApplicationInsights is hosted *NOT* in this repo... Its here : https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter

**Comment by cijothomas** [comment]
![image](https://user-images.githubusercontent.com/5232798/167503459-cf196189-48ff-4014-9f9e-4c332555eac6.png)
https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-collection-walkthroughs#collect-traces-using-application-insights

**Comment by cijothomas** [comment]
> The Application Insights SDK uses the static Activity.Current property to determine the current activity. Unfortunately, as you've discovered, Activity.Current isn't set unless someone's listening.
> 
> You can try adding this workaround somewhere in your startup code:
> 
> ```cs
> ActivitySource.AddActivityListener(new ActivityListener
> {
>     ShouldListenTo = _ => true,
>     Sample = (ref ActivityCreationOptions<ActivityContext> _) => ActivitySamplingResult.AllDataAndRecorded
> });
> ```
> 
> This adds a dummy global listener which has the side-effect of setting Activity.Current even when no-one else is listening.

^ This is correct, but as mentioned in my previous comment, this method is not going to work for ApplicationInsights SDK :) 
i.e users must use telemetryClient.StartOperation ,or switch to OTel preview, and use activitySource.StartActivity.

**Comment by johnknoop** [comment]
@cijothomas thanks!

> users must use telemetryClient.StartOperation ,or switch to OTel preview

Which path would you recommend? Is the OpenTelemetry preview mature enough to adopt for production purposes, or should I go with telemetryClient.StartOperation for the time being?

**Comment by cijothomas** [comment]
If you are okay with the limitations listed here : https://docs.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=net#limitations-of-the-preview-release , you can use the OTel preview. OTel itself is stable and is used by companies in production.

(If you follow the AzureMonitor Exporter repo, you can see that several of the limitations are addresses/being addressed, but not yet released to nuget.)
