### ISSUE TITLE
Dependencies do not contain cloud role name and user auth id properties

### ISSUE THREAD

**Issue by LiangZugeng** [microsoft/ApplicationInsights-dotnet#2603]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Microsoft.ApplicationInsights.AspNetCore, 2.20.0

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
.NET 6

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
Ubuntu 18.04

**What are you trying to achieve?**
I would like the Application Map to properly visualize the dependency calls, currently it shows an empty node from which all dependencies are called, it should show that all dependency calls are from the Backend node which is the application instance.
<img width="801" alt="image" src="https://user-images.githubusercontent.com/20870130/170827608-acbbe7c4-170f-4e0b-befa-7302e1ea5650.png">

I checked the dependency details in Logs and found there is no cloud role name or any user id/auth id/account id set in those dependency details.
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/20870130/170827737-90214bf8-29e6-45a7-b936-fe57148aa2a0.png">

The cloud role name and user id/auth id are added to requests using a TelemetryInitializer as follows.
```
    public class RequestTelemetryInitializer : ITelemetryInitializer
    {
        public void Initialize(ITelemetry telemetry)
        {
            if (telemetry is ISupportProperties telProperties &&
                telemetry is RequestTelemetry t)
            {
                var userId = GetAuthenticatedUserId();
                if (!string.IsNullOrEmpty(userId))
                {
                    telemetry.Context.User.Id = telemetry.Context.User.AuthenticatedUserId = userId;
                }

                var cloudRoleName = config?.CloudRoleName;
                if (!string.IsNullOrEmpty(cloudRoleName))
                {
                    telemetry.Context.Cloud.RoleName = cloudRoleName;
                }
            }
        }
```
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/20870130/170827893-903587e7-0554-48d3-9503-f8b8acadad98.png">

**Comment by pharring** [comment]
From the code snippet you sent, your custom telemetry initializer works only for RequestTelemetry items. You need a similar one to add the RoleName for DependencyTelemetry items (I don't think the AuthenticatedUserId is relevant here)

**Comment by LiangZugeng** [comment]
@pharring thank you very much. Yes, it's my mistake filtering out DependencyTelemetry items in the initializer, I created a new initializer class to process dependency items and the issue was solved.
