### ISSUE TITLE
Why were all previous packages deprecated on Nuget.org?

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/ApplicationInsights-dotnet#2607]
On [NuGet](https://www.nuget.org/packages/Microsoft.ApplicationInsights/), all previous versions of Microsoft.ApplicationInsights have been marked as deprecated. I've never seen a package mass deprecate all previous versions. (It's rare that I see the deprecated feature used at all.) Why was this done?

![image](https://user-images.githubusercontent.com/1784452/173088837-eb753fa4-7e2f-4c29-9ed2-c4bde040f4d7.png)

**Comment by cartersocha** [comment]
Hey @MisinformedDNA,

That's a great question. We're subject to the [Azure SDK Lifecycle & support policy](https://azure.github.io/azure-sdk/policies_support.html). A requirement of that policy is that we only formally support the most recent minor version of our SDKs & we expect customers to be on the latest version. Unfortunately we haven't always followed the policy strictly. To become compliant we've started marking our old minor versions as deprecated.

Note you can still use the packages without any issues, only a warning should be thrown during the build, but if you open a support case then you'd be directed to use the most recent minor version first. Outdated SDK minor versions have been a major driver in support requests but the update typically solves the problem. 

Major versions changes are a slightly different story that fall under the more formal Azure deprecation process as that would involve breaking changes.

I hope this info helps!

**Comment by MisinformedDNA** [comment]
But no one else in Azure is doing what you are doing, see [Azure.Core](https://www.nuget.org/packages/Azure.Core), [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs/12.13.0-beta.1), [Azure.Security.KeyVault.Secrets](https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets), [Azure.Identity](https://www.nuget.org/packages/Azure.Identity), etc.

Your team is the only one I've seen that is deprecating packages in this way. Is there a plan for this to be consistent?

**Comment by cartersocha** [comment]
I can't speak for the other teams and how they choose to enforce the policy. Our support data drove us to more strictly enforce the existing policy. 

I've heard some talk of maturing the Azure SDK deprecation process to where the services process is today but I'm not sure where those discussions are today.
