### ISSUE TITLE
Telemetry item gets lost when property value ends with a backslash

### ISSUE THREAD

**Issue by NielsFilter** [Microsoft/ApplicationInsights-dotnet#261]
I noticed that some custom events do not get to the portal, but show up correctly in the output window in Visual Studio. I realised the cause is a property value that ends with a backslash.

No errors are thrown and telemetry item is simply "lost"

Here's what I tested:
- Issue happens with both **In-Memory Channel** and **Server Channel**
- Backslashes **within** the property value works fine
- Property value **beginning** with a backslash works fine

I simplified the code down to the following console app to reproduce:

    static void Main(string[] args)
    {
        TelemetryConfiguration.Active.InstrumentationKey = "*****MyKey*****";
    
        var validProps = new Dictionary<string, string>
        {
            {"WorksFine", @"`Does_Not_End_With_Backslash\1234567890-=[];',./~!@#$%^&*()_+{}:|<>?"}
        };
    
        var failedProps = new Dictionary<string, string>
        {
            {"DoesNotWork", @"Testing\"}
        };
    
        var client = new TelemetryClient();
        client.TrackEvent("No Properties - This works");
        client.TrackEvent("Valid Properties - This works", validProps);
        client.TrackEvent("Failed Properties - Does not work", failedProps);
    
        TelemetryConfiguration.Active.TelemetryChannel.Flush();
    }

**Comment by abaranch** [comment]
Thank you for reporting the issue. We will investigate.

**Comment by abaranch** [comment]
We found an issue in backend processing logic. Fix is checked in but there are no deployments this week. I will close the issue when fix is in prod.

**Comment by NielsFilter** [comment]
Thanks for the update.

**Comment by abaranch** [comment]
Fix is in prod
