### ISSUE TITLE
Start / Stop telemetry modules at runtime

### ISSUE THREAD

**Issue by LoloActemium** [microsoft/ApplicationInsights-dotnet#2616]
Hello,

I tried to activate/deactivate Telemetry module like PerformanceCollectorModule at runtime (I know that I can do it at start-up).
I wanted to keep Telemetry activated for all other modules (like DependendecyTracking).

What about having a "Start" or "Stop" fucntionnality at the module level ?

I also tried to extend/wrap PerformanceCollectorModule but the class is marked as sealed, so no way to achieve my goal.

Kind regards,
Laurent Wehrlen.

**Comment by cijothomas** [comment]
There is no such thing capability to turn off/on ad-hoc for modules.

**Comment by LoloActemium** [comment]
And removing the sealed modifier on PerformanceCollectorModule , is it something that can be considered ?

**Comment by cijothomas** [comment]
Not likely. Most new investments are going to be in OpenTelemetry based instrumentations.

(You can try to dispose the module when not needed, and new up another one when needed.)

**Comment by LoloActemium** [comment]
Everything is "injected" with dependency injection, so it's a bit more tricky to dispose / recreate modules at runtime (they are injected as Singletons). Or, I missed something in DI mecanism :)
Thanks for responding.
