### ISSUE TITLE
Grpc 

### ISSUE THREAD

**Issue by davidelettieri** [microsoft/ApplicationInsights-dotnet#2625]
* Microsoft.ApplicationInsights.AspNetCore 2.20.0
* Grpc.AspNetCore 2.40.0
* .net 6 on windows 10

**What are you trying to achieve?**
Distributed tracing with http request and Grpc

**What have you tried so far?**
I created 3 project, 2 aspnet core web apis (API1 and API2) and 1 aspnet core grpc (GRPC). API1 has an endpoint that calls both API2 and GRPC. Both everything appears in application insights but entry for GRPC has wrong parent id, I would expect it to be indented as the previous HTTP call.

![image](https://user-images.githubusercontent.com/5262655/179029381-1dbab93e-0dff-4f4a-8ad8-e4eac63b4f5b.png)

**Comment by cijothomas** [comment]
Unfortunately, ApplicationInsights does not have support for Grpc library.

**Comment by davidelettieri** [comment]
Ok thanks
