### ISSUE TITLE
When required sring field is not provided substitute it with a short string

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-dotnet#263]
Currently is response code is not provided we send responseCode: responseCodeisarequiredfieldforMicrosoft.ApplicationInsights.DataContracts.RequestTelemetry which is very long. Substitute it on "n/a".
Same applies to all other required string fields.

**Comment by shklar** [comment]
I totally agree :)
The unreasonably long string currently shown looks weird and takes up too much space,
