### ISSUE TITLE
Provide an option for disable the initialization of TraceTelemetry properties with the logging state

### ISSUE THREAD

**Issue by liguori** [microsoft/ApplicationInsights-dotnet#2637]
The user should have control over the exact information to be send as Traces in Application Insights.

When instrumenting an ASP.NET Application, all the logs emitted via ILogger are sent to Application Insights as Traces initialized in the [PopulateTelemetry](https://github.com/microsoft/ApplicationInsights-dotnet/blob/405fd6a9916956f2233520c8ab66110a1f9dcfbc/LOGGING/src/ILogger/ApplicationInsightsLogger.cs#L156) method as follows:
- Message =  formatter(State)
- CustomDimensions = all the items of the State dictionary 

In some context the user just needs to rely on the Message and doesn't need all the information that the State object contains.

A good idea could be provide an option to the [ApplicationInsightsLoggerOptions](https://github.com/microsoft/ApplicationInsights-dotnet/blob/405fd6a9916956f2233520c8ab66110a1f9dcfbc/LOGGING/src/ILogger/ApplicationInsightsLoggerOptions.cs#L15) that disable this behavior, a bool property could be enough:
``` C#
 public bool IncludeStateAsCustomDimensions { get; set; } = true;
```
So that by modifying this line: [ApplicationInsightsLogger.cs#L171](https://github.com/microsoft/ApplicationInsights-dotnet/blob/405fd6a9916956f2233520c8ab66110a1f9dcfbc/LOGGING/src/ILogger/ApplicationInsightsLogger.cs#L171) taking account of the option:

``` C#
  if (this.applicationInsightsLoggerOptions.IncludeStateAsCustomDimensions  && state is IReadOnlyCollection<KeyValuePair<string, object>> stateDictionary)
  {
```
the user can choose whether include the state or not.

**Comment by XVincentX** [comment]
I think we should remove the hands
