### ISSUE TITLE
How can I consume counters?

### ISSUE THREAD

**Issue by verdysh** [microsoft/ApplicationInsights-dotnet#2641]
Hi!
ASP .NET Core application, built on .NET 6.
Microsoft.ApplicationInsights.AspNetCore, version 2.21.0-beta1

I want my custom counter will be in Azure. Here is the counter:

```
Meter MyMeter = new("MyCompany.MyProduct.MyLibrary", "1.0");
Counter<long> MyFruitCounter = MyMeter.CreateCounter<long>("MyFruitCounter");
var rnd = new Random();
var metricsTask = CheckMetrics();

async Task CheckMetrics()
{
    while (true)
    {
        var value = rnd.Next(1, 10);
        Console.WriteLine(value);
        MyFruitCounter.Add(value, new("name", "apple"), new("color", "red"));
        await Task.Delay(1000);
    }
}
```

Here is a code which I hoped will be pass this counter to Azure:

```
builder.Services.ConfigureTelemetryModule<EventCounterCollectionModule>(
	(module, o) =>
	{
		// This removes all default counters, if any.
		module.Counters.Clear();

		// This adds a user defined counter "MyCounter" from EventSource named "MyEventSource"
		module.Counters.Add(new EventCounterCollectionRequest("MyEventSource", "MyCounter"));
		module.Counters.Add(new EventCounterCollectionRequest("MyCompany.MyProduct.MyLibrary", "MyFruitCounter"));

		// This adds the system counter "gen-0-size" from "System.Runtime"
		module.Counters.Add(new EventCounterCollectionRequest("System.Runtime", "gen-0-size"));
	}
);
```

As a result I see in Azure System.Runtime|gen-0-size metric, but don't see anything else.
I assume Meter and Counter API - they are not what is being listened by EventCounterCollectionModule. Is it so?
If yes, is the only way to add my counter is to use EventSource API?
Can't I use Counter API and ApplicationInsights-dotnet package? A goal of using Counter API now is further ability to change ApplicationInsights-dotnet to OpenTelemetry .NET when it will be support metrics.

**Comment by TimothyMothra** [comment]
@verdysh, This repo is for the Application Insights .NET SDK.
This SDK does not support OpenTelemetry.

Instead, please try the Azure Monitor Exporter: 
https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter

**Comment by verdysh** [comment]
Meter, Counter are in the System.Diagnostics.DiagnosticSource assembly which is part of .net core I thought. Because of this I thought this abstractions aren't related to OpenTelemetry or any specific packages for collection telemetry. I was wrong and these abstractions had been created exactly for being able to use them in open telemetry? In other words these abstractions doesn't have direct relations to OpenTelemetry but OpenTelemetry is based to them?

**Comment by verdysh** [comment]
Could anybody gives answer please.
