### ISSUE TITLE
how to trouble shoot 'AI: Process was called on the TelemetrySink after it was disposed, the telemetry data was dropped.'?

### ISSUE THREAD

**Issue by xieofxie** [microsoft/ApplicationInsights-dotnet#2648]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):

Microsoft_ApplicationInsights_AspNetCore_Version: 2.18.0
netcoreapp3.1 & Windows 

**What are you trying to achieve?**

We are seeing 'AI: Process was called on the TelemetrySink after it was disposed, the telemetry data was dropped.' what does it mean and how could we trouble shoot it? Thanks~

We need some hint about why this would happen

**What have you tried so far?**

Search the internet but nothing helpful like https://github.com/search?q=Process+was+called+on+the+TelemetrySink+after+it+was+disposed%2C+the+telemetry+data+was+dropped.&type=code

**Comment by TimothyMothra** [comment]
For context, this error is thrown from here:
https://github.com/microsoft/ApplicationInsights-dotnet/blob/288d34438bf5f4f2a893363c94a6b62e09f58505/BASE/src/Microsoft.ApplicationInsights/Extensibility/TelemetrySink.cs#L205-L211
https://github.com/microsoft/ApplicationInsights-dotnet/blob/288d34438bf5f4f2a893363c94a6b62e09f58505/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/CoreEventSource.cs#L533-L541


The `TelemetrySink` is a member of the `TelemetryConfiguration` and would only be disposed if the `TelemetryConfiguration` was disposed.

You should review your code and confirm that you're only creating one instance of `TelemetryClient` and `TelemetryConfiguration` for the entire lifetime of your application.

**Comment by xieofxie** [comment]
It worked, thanks! We replace the singleton in `AddApplicationInsightsTelemetry`

**Comment by isaacabraham** [comment]
@xieofxie do you have an example of replacing the singleton in that call? I have exactly the same issue.

**Comment by ThunderDev1** [comment]
Same problem here, I'm curious what your fix was exactly @xieofxie

**Comment by xieofxie** [comment]
@isaacabraham @ThunderDev1 Here is what I did:

```
        // https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Implementation/TelemetryConfigurationOptions.cs
        // the above one creates a configuration so we should not use it
        private class TelemetryConfigurationOption : IOptions<TelemetryConfiguration>
        {
            public TelemetryConfiguration Value => TelemetryConfiguration.Active;

            public TelemetryConfigurationOption(IEnumerable<IConfigureOptions<TelemetryConfiguration>> configureOptions)
            {
                var configureOptionsArray = configureOptions.ToArray();
                foreach (var c in configureOptionsArray)
                {
                    c.Configure(this.Value);
                }
            }
        }

        public static void Configure(IServiceCollection services, bool isWebJob)
        {
            services.AddApplicationInsightsTelemetry();
           // after the above, replace the TelemetryClient & IOptions<TelemetryConfiguration>
            var descriptor = services.Single(descriptor => descriptor.Lifetime == ServiceLifetime.Singleton && descriptor.ServiceType == TelemetryClient.GetType());
            services.Remove(descriptor);
            services.AddSingleton(YourTelemetryClient);

            descriptor = services.Single(descriptor => descriptor.Lifetime == ServiceLifetime.Singleton && descriptor.ServiceType == typeof(IOptions<TelemetryConfiguration>));
            services.Remove(descriptor);
            services.AddSingleton<IOptions<TelemetryConfiguration>, TelemetryConfigurationOption>();
            ...
```

**Comment by cijothomas** [comment]
^ Looks like some hack. Won't recommend doing this.

**Comment by hswami** [comment]
Our setup looks like this:

`

var enableAppInsights = Configuration.GetValue("ApplicationInsights:Enable", false);
//Add Application Insights logging & telemetry, and the Kubernetes Enricher
if (enableAppInsights)
{
    //Application Insights Logging
    services.AddSingleton(typeof (ITelemetryChannel), new ServerTelemetryChannel());
    services.AddApplicationInsightsTelemetry(Configuration);
    services.AddCloudRoleNameInitializer($"{APIServiceName} API");

    //Add Profiler to initialize trace data to Application Insights
    services.AddServiceProfiler(Configuration);

    services.AddApplicationInsightsKubernetesEnricher();
}
`

We never instantiate the telemetry client or the options or any other part of AI in our code and we still have this problem.

**Comment by hswami** [comment]
If the "hack" posted by @xieofxie works, then that would be indicative of a bug somewhere that the hack is working around.

> For context, this error is thrown from here:
> 
> https://github.com/microsoft/ApplicationInsights-dotnet/blob/288d34438bf5f4f2a893363c94a6b62e09f58505/BASE/src/Microsoft.ApplicationInsights/Extensibility/TelemetrySink.cs#L205-L211
> 
> 
> https://github.com/microsoft/ApplicationInsights-dotnet/blob/288d34438bf5f4f2a893363c94a6b62e09f58505/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/CoreEventSource.cs#L533-L541
> 
> The `TelemetrySink` is a member of the `TelemetryConfiguration` and would only be disposed if the `TelemetryConfiguration` was disposed.
> 
> You should review your code and confirm that you're only creating one instance of `TelemetryClient` and `TelemetryConfiguration` for the entire lifetime of your application.

This doesn't help us because we never create or request or inject or otherwise use `TelemetryClient` and `TelemetryConfiguration` in our code at all.

**Comment by hswami** [comment]
Our configuration looks like this:

`"ApplicationInsights": {`
`  "Enable": true,`
`  "LogMessageFormat": "${message} ${exception:format=ToString,Data}",`
`  "InstrumentationKey": "<guid>",`
`  "EnableRequestTrackingTelemetryModule": true,`
`  "EnableAdaptiveSampling": true,`
`  "EnableActiveTelemetryConfigurationSetup": true`
`}`

**Comment by yaseen22** [comment]
Dears, any update of this issue ?
We're working with .NET 8, and we're facing this issue at out WebAPI projects and Azure functions projects as well.

For WebAPI Projects, we're using this :
services.AddApplicationInsightsTelemetry(options => options.ConnectionString = applicationInsightsConnectionString);

for Azure functions, we're using this :
services.AddApplicationInsightsTelemetryWorkerService(options => options.ConnectionString = applicationInsightsConnectionString);
services.ConfigureFunctionsApplicationInsights();

**Comment by aniliht** [comment]
I'm seeing this in some of my console apps and function apps.  Using packages under .NET8:

```
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.23.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.23.0" />
```

**Comment by AndreasJilvero** [comment]
My finding is that these messages occur in tandem with ServiceProfiler-events.

**Comment by aniliht** [comment]
It looks like our app had multiple instances of Dependency Injection containers.  Cleaning that help resolve.
