### ISSUE TITLE
How can I add custom property to telemtry?

### ISSUE THREAD

**Issue by verdysh** [microsoft/ApplicationInsights-dotnet#2650]
Hi!
I have ASP .NET Core app, built on .NET 6.
Microsoft.ApplicationInsights.AspNetCore, version 2.20.0

Here is telemetry item which shows incoming http request:
![image](https://user-images.githubusercontent.com/21305997/182919113-339b3014-b5a5-4799-bfdd-fdc8e5bc5c25.png)

I want to add some custom information to telemetry items. It would be great if I could choose which telemetry items should contain it, which shouldn't. But it would be nice even if I could add necessary information to all telemetry items without being able to choose specific telemetry items.

I thought I need to add something into Bag or into Tag of corresponding activity. I did that.
```
var activityFeature = context.Features.Get<IHttpActivityFeature>();
activityFeature?.Activity.AddBaggage("TenanId", tenantId);
activityFeature?.Activity.AddTag("TenantIdTag", tenantId);
```

As a result I don't see neither TenanId nor TenantIdTag in telemetry item.
I see TenanId set as property in the logs. But I want to see it in telemetry.

Is it possible to do that?

**Comment by pharring** [comment]
You have a couple of options:
1. Add an `ITelemetryInitializer` to the services collection in `ConfigureServices` to augment all telemetry items (not just requests, but dependencies, exceptions and traces).
2. Add middleware that gets the current RequestTelemetry from the HttpContext features (i.e. `var requestTelemetry = context.Features.Get<RequestTelemetry>();`). You can then add to the Properties bag on the RequestTelemetry.

**Comment by TimothyMothra** [comment]
@verdysh, yes you can use TelemetryInitializers with any application.
See also this doc: https://docs.microsoft.com/azure/azure-monitor/app/api-filtering-sampling

**Comment by verdysh** [comment]
Thanks!
