### ISSUE TITLE
Not all logs get into ApplicationInsights

### ISSUE THREAD

**Issue by verdysh** [microsoft/ApplicationInsights-dotnet#2658]
Hello!

Microsoft.ApplicationInsights.AspNetCore, version 2.20.0
ASP .NET Core app, runs on .NET 6

I was doing some test with my app. I made 50 requests, inside each one logs are written. As a result I see in ApplicationInsights about 12-15 log items. But there should be 50 of them.

How to ensure that all logs are placed in ApplicationInsights?

**Comment by javedali-dev** [comment]
This is happing to me as well. I'm only seeing the log that has the severity of Error even though I'm setting up the minimum log level as Trace.
Steps to reproduce:
1. Create new dotnet webapi project.
    `dotnet new webapi`
2. Install Microsoft.ApplicationInsight.AspNetCore package : 
   `<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />` 
                                                             or
    `dotnet add package Microsoft.ApplicationInsights.AspNetCore`
3.  setting up minimum log level in appsettings.json:
    ```"ApplicationInsight": {
      "LogLevel": {
        "Default": "Trace"
      }
    }```
4. write some logs with different log levels:
    ```_logger.LogTrace("This is Trace Log");
    _logger.LogDebug("This is Debug Log");
    _logger.LogInformation("This is Info Log");
   _logger.LogError("This is Error Log");```

After sending a request to the endpoint you will only see "This is Error Log" in the app insight.

**Comment by verdysh** [comment]
Here is solution:
`builder.Services.AddApplicationInsightsTelemetry(opt => opt.EnableAdaptiveSampling = false);`
**opt.EnableAdaptiveSampling = false**
