### ISSUE TITLE
Email Alert notification with exception details

### ISSUE THREAD

**Issue by Anusri-Varier** [microsoft/ApplicationInsights-dotnet#2676]
What I want to achieve, **Get the messages details / exception details in the email notification as a custom property.**

What i am able to do, **I am able to create an alert rule for the log traces.**

This is a question to understand if there is a possibility to create an email alert with the complete exception details or message as one of the properties in the email. If there is a possibility , please provide the complete information regarding the same. 

If this is a wrong channel, please assign the issue to the right channel

thankyou

**Comment by TimothyMothra** [comment]
This is the GitHub repo for the Application Insights .NET SDK.
Our SDK does not send email alerts.

I think you need to create an Azure support request.
https://learn.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request
