### ISSUE TITLE
Allow using AddApplicationInsightsTelemetryWorkerService/AddApplicationInsightsTelemetry without adding the logging integration to facilitate integrating with serilog or other logging providers

### ISSUE THREAD

**Issue by timstokman** [microsoft/ApplicationInsights-dotnet#2677]
**Is your feature request related to a problem?**
I'm currently using application insights through serilog. If you use `AddApplicationInsightsTelemetryWorkerService` or `AddApplicationInsightsTelemetry` it will automatically add the application insights logging provider. This will cause it to emit events twice. There's no easy way to add application insights w/o the logger provider. See this ticket for more details: https://github.com/serilog-contrib/serilog-sinks-applicationinsights/issues/180

**Describe the solution you'd like.**
Overloads or an extra parameter for `AddApplicationInsightsTelemetryWorkerService` and `AddApplicationInsightsTelemetry` that allow you to not add the logger provider.

**Describe alternatives you've considered.**
My current workaround for this issue is this:

```
        /// <summary>
        /// Add application insights without immediate logging integration
        /// </summary>
        /// <param name="services">Service collection</param>
        /// <param name="options">Application insights options</param>
        /// <returns>The service collection</returns>
        public static IServiceCollection AddApplicationInsightsTelemetryWorkerServiceWithoutLogging(this IServiceCollection services, ApplicationInsightsServiceOptions options)
        {
            services.AddApplicationInsightsTelemetryWorkerService(options);

            // Application insights immediately integrates with the logging. We want integration through serilog, so remove that integration.
            Type[] loggingTypesToRemove = new[] { typeof(ILogger<>), typeof(ILoggerProvider), typeof(ILoggerFactory) };
            var descriptorsToRemove = services.Where(descriptor => loggingTypesToRemove.Contains(descriptor.ServiceType)).ToList();

            foreach (var descriptor in descriptorsToRemove)
            {
                services.Remove(descriptor);
            }

            return services;
        }
```

Bit of a hack, I'd rather avoid this.

**Additional context.**
-

**Comment by cijothomas** [comment]
You can use Filer to not send any logs to ApplicationInsightsProvider.
`builder.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.None);`
