### ISSUE TITLE
How can I automatically report app shutdown?

### ISSUE THREAD

**Issue by rido-min** [microsoft/ApplicationInsights-dotnet#2678]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:

```
 <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
```

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
*
```
    <TargetFramework>net6.0</TargetFramework>
```

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):

```
raspberry pi 3 (arm-linux)
```

**What are you trying to achieve?**

I'm using a Worker app and would like to instrument application crashes or shutdowns

**What have you tried so far?**

```cs
_applicationLifetime.ApplicationStarted.Register(() => _telemetryClient.TrackTrace("Start worker service"));
_applicationLifetime.ApplicationStopping.Register(() => _telemetryClient.TrackTrace("Stopping worker service"));
_applicationLifetime.ApplicationStopped.Register(() => _telemetryClient.TrackTrace("Stopped worker service"));

```

**Comment by TimothyMothra** [comment]
I'm not familiar with raspberry pi, so I can't give specific advice to this.

Assuming you can debug this locally, you can see telemetry in the Visual Studio Output console.
When your application is shutting down, you'll want to Flush the client to ensure that telemetry is cleared from the buffer.

**Comment by rido-min** [comment]
Forget about raspberry pi, it should work the same on .NET/Windows.

The question is more about best practices to capture unexpected shutdowns/exceptions of a dotnet worker app using `Microsoft.ApplicationInsights.WorkerService`

**Comment by TimothyMothra** [comment]
**Regarding the Application Insights SDK**
Internally our [TelemetryChannels](https://learn.microsoft.com/azure/azure-monitor/app/telemetry-channels) hold telemetry in a buffer before transmitting in a batch.
If the application has an unexpected shutdown, all telemetry in that buffer will be lost.
If your application is shutting down normally, we recommend [Flushing the TelemetryClient](https://learn.microsoft.com/azure/azure-monitor/app/api-custom-events-metrics#flushing-data).



We don't have any recommendations for unhandled exceptions.
I would like to share this doc from OpenTelemetry which lists some additional information for your consideration: [Unhandled Exception](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/reporting-exceptions/README.md#unhandled-exception).


**Regarding best practices of a dotnet worker app**
This would be a question for the `WorkerService` product.
