### ISSUE TITLE
Read Dependency HttpRequest and HttpResponse Content in a non-blocking way in Application Insights Telemetry Initializers

### ISSUE THREAD

**Issue by mavsankar** [microsoft/ApplicationInsights-dotnet#2679]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using: Microsoft.ApplicationInsights.AspNetCore-2.15.0
* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): netcoreapp3.1
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): NA

**What are you trying to achieve?**
I have an application in .net core 3.1 using Application Insights sdk for telemetry. I have the below code for logging dependency response body in App insights dependency telemetry. However, this:```var responseBody = httpResponse.Content.ReadAsStringAsync().GetAwaiter().GetResult();``` being a blocking call is causing thread starvation resulting in latencies for the services' users. I cannot make the method async Task as the interface ```ITelemtryInitializer``` doesn't support it. Is there a way to make this non-blocking or any other way to do the same without thread starvation?
```
public class DependencyEnhanceInitializer : ITelemetryInitializer
{
    public void Initialize(ITelemetry telemetry)
    {
        var dependecyTelemetry = telemetry as DependencyTelemetry;
        if (dependecyTelemetry == null) return;

        if (dependecyTelemetry.TryGetOperationDetail("HttpResponse", out object response)
            && response is HttpResponseMessage httpResponse)
        {
            var responseBody = httpResponse.Content.ReadAsStringAsync().GetAwaiter().GetResult();
            if (!string.IsNullOrEmpty(responseBody))
                dependecyTelemetry.Properties.Add("ResponseBody", responseBody);
        }
    }
}
```

**What have you tried so far?**
I am able to see a lot of difference in response times by load testing with and without this piece of code. This has been observed irrespective of the hosting environment.

**Comment by TimothyMothra** [comment]
Unfortunately, the `ITelemetryInitializer` wasn't designed for async tasks.

Regarding your question, how to read `HttpRequest` and `HttpResponse` Content in a non-blocking way.
This would be a question for the AspNET Core product: https://github.com/dotnet/aspnetcore

I did a brief search for: asp net core request body logging and found this article:
https://learn.microsoft.com/aspnet/core/fundamentals/http-logging

**Comment by mavsankar** [comment]
This is for incoming requests and not outgoing requests; I am looking for outgoing requests

**Comment by cijothomas** [comment]
> This is for incoming requests and not outgoing requests; I am looking for outgoing requests

Use ILogger to log the outgoing request. And have Application Insights capture ILogger logs.
