### ISSUE TITLE
DependencyTelemetry is not grouped with other operations

### ISSUE THREAD

**Issue by hallatore** [Microsoft/ApplicationInsights-dotnet#268]
Calls to Remote Dependencies are always empty in requests, and Dependencies are never grouped with the request context.

It seems that Dependencies don't get grouped correctly which makes it harder to find correlations.

**Comment by hallatore** [comment]
This might be the wrong repo as I see the problem is with https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/master/Src/DependencyCollector/Shared/DependencyTrackingTelemetryModule.cs

It seems that it can't find the current context for http requests, so they aren't tied to the correct operation id.

**Comment by abaranch** [comment]
Currently it is by design. We are looking into ways how we can improve it.
Duplicate: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/106
