### ISSUE TITLE
How is the "problemId" field populated?

### ISSUE THREAD

**Issue by tompazourek** [microsoft/ApplicationInsights-dotnet#2687]
Hi, it seems to me that the `problemId` field in Application Insights is somehow generated from the call stack. It looks like it finds the first frame that's not a "system" one (starting with `System.*` or `Microsoft.*`) and uses that.

However, I couldn't find this logic anywhere... Can you please describe how this functionality works? Is there some way how to customize the behavior (e.g. pick which namespaces are considered system and are skipped, and which namespaces are considered as "My Code")?

Thank you

**Comment by cijothomas** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/LogsHelper.cs#L133
No ability to customize this currently. Also, this is often *not* send from sdk, but instead calculated at ingestion side.

**Comment by tompazourek** [comment]
I'm confused. Isn't `Azure.Monitor.OpenTelemetry.Exporter` on the client side? I'm asking about the ingestion side that you mentioned. Also, I'm not using OpenTelemetry at all, I use the ordinary `Microsoft.ApplicationInsights` packages. And to add to that, the logic in the code you linked also doesn't match my experience at all...

Example call stack as I see it in Application Insights is:

```
{"level":0,"method":"Microsoft.AspNet.SessionState.SessionStateModuleAsync.QueueRef","assembly":"Microsoft.AspNet.SessionState.SessionStateModule, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","line":0}
{"level":1,"method":"Microsoft.AspNet.SessionState.SessionStateModuleAsync+<GetSessionStateItemAsync>d__74.MoveNext","assembly":"Microsoft.AspNet.SessionState.SessionStateModule, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","line":0}
{"level":2,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0}
{"level":3,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0}
{"level":4,"method":"Microsoft.AspNet.SessionState.SessionStateModuleAsync+<AcquireStateAsync>d__65.MoveNext","assembly":"Microsoft.AspNet.SessionState.SessionStateModule, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","line":0}
{"level":5,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0}
{"level":6,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","line":0}
{"level":7,"method":"Microsoft.AspNet.SessionState.TaskAsyncHelper.EndTask","assembly":"Microsoft.AspNet.SessionState.SessionStateModule, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","line":0}
{"level":8,"method":"System.Web.HttpApplication+AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute","assembly":"System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0}
{"level":9,"method":"System.Web.HttpApplication+<>c__DisplayClass285_0.<ExecuteStepImpl>b__0","assembly":"System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0}
{"level":10,"method":"MyCode.Wrapper.Wrap1","assembly":"MyCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","line":42,"fileName":"..."}
{"level":11,"method":"MyCode.Wrapper.Wrap2","assembly":"MyCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","line":46,"fileName":"..."}
{"level":12,"method":"System.Web.HttpApplication.ExecuteStepImpl","assembly":"System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0}
{"level":13,"method":"System.Web.HttpApplication.ExecuteStep","assembly":"System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","line":0}
```

Yet, the `problemId` is detected as `System.Web.HttpException at MyCode.Wrapper.Wrap1`. This is incorrect as the problem occurs in the `SessionStateModuleAsync` on top, but somehow it looks like Application Insights is ignoring the stack frames starting with `Microsoft` and `System` and picks the first stack frame with `MyCode`. The logic around detecting `problemId` seems strange to me, but I cannot find it explained anywhere...

**Comment by cijothomas** [comment]
How ingestion generates ProblemId is not documented anywhere. The link I provided above shows how the SDK calculates it. I was assuming the logic is same, but it looks like they are not. @rajkumar-rangaraj Do you have more idea about this? (I think we should stop producing the ProblemId at clientside, as ingestion seems to have a diff. logic for the same)
