### ISSUE TITLE
Do we need the Microsoft.Data.SqlClient in ASP.NET Core applications for Advanced SQL Tracking?

### ISSUE THREAD

**Issue by drauch** [microsoft/ApplicationInsights-dotnet#2688]
The docs say for ASP.NET Core you only need to turn it on:

```
services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((module, o) => { module. EnableSqlCommandTextInstrumentation = true; });
```

Then it says for _old_ ASP.NET applications you need Microsoft.Data.SqlClient. Is it assumed that one uses this SqlClient in ASP.NET Core applications? Do we need it in ASP.NET Core applications as well or does it work with the old System.Data.SqlClient in ASP.NET Core as well?

Best regards,
D.R.

**Comment by cijothomas** [comment]
In ASP.NET Core, you do not need anything other than enabling the `EnableSqlCommandTextInstrumentation` to true.
