### ISSUE TITLE
ParentId of AppTraces  is equal to current SpanId

### ISSUE THREAD

**Issue by wkoeter** [microsoft/ApplicationInsights-dotnet#2690]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
```xml
<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
```

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
```xml
<TargetFramework>net6.0</TargetFramework>
```

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):`

ASP.NET Core Web API. Local debugging.

### Describe the bug

I have an application insights log in `AppTraces` or `Traces` depending on your scope when querying. It is created when calling a controller from a console application using header:
`traceparent = 00-6139a7888ccd3c8a352952c9f27abe31-d3dd9224178d8155-00`

The controller logs the following:
```csharp
_logger.LogWarning($"Writing from API2 Activity.ParentId: {t.ParentId}");
_logger.LogWarning($"Writing from API2 Activity.TraceId: {t.TraceId}");
_logger.LogWarning($"Writing from API2 Activity.ParentSpanId: {t.ParentSpanId}");
_logger.LogWarning($"Writing from API2 Activity.SpanId: {t.SpanId}");
```

The application insights logline contains the following information.
```
Writing from API2 Activity.ParentId: 00-6139a7888ccd3c8a352952c9f27abe31-d3dd9224178d8155-00
Writing from API2 Activity.TraceId: 6139a7888ccd3c8a352952c9f27abe31
Writing from API2 Activity.ParentSpanId: d3dd9224178d8155
Writing from API2 Activity.SpanId: b9c9312ac7c25cd2
```

When wanting to correlate the `Requests` logging, I noticed the following:
- When correlating logging from Requests
   - The id = the current Activity.SpanId: b9c9312ac7c25cd2
   - The operationId = the current Activity.TraceId: 6139a7888ccd3c8a352952c9f27abe31
   - The parentId = the current Activity.ParentSpanId: d3dd9224178d8155

This all seems perfect. However, when wanting to correlate the `AppTraces` logging
   - The id column is not there
   - The operationId = the current Activity.TraceId: 6139a7888ccd3c8a352952c9f27abe31
   - The parentId = the current Activity.SpanId: b9c9312ac7c25cd2

This is weird. Because it says that the parentId is the current span. Conceptually that is not accurate. To support that this is confusing, in the app traces logging of one of the loglines the following information is stored. Which has 2 different `ParentId`'s on different levels, and a `ParentId` that matches a `SpanId`.

| property | value |
|---|---|
| line.Message | Writing from API2 Activity.SpanId: b9c9312ac7c25cd2|
| line.OperationId |  6139a7888ccd3c8a352952c9f27abe31 |
| line.ParentId | **b9c9312ac7c25cd2** |
| line.Properties.TraceId | 6139a7888ccd3c8a352952c9f27abe31 |
| line.Properties.ParentId | d3dd9224178d8155 |
| line.Properties.SpanId | **b9c9312ac7c25cd2** |

**I would expect the `ParentId`'s to contain the same value, and that the `ParentId` is never equal to the current `Span`. For `Requests` this is the case, for `Traces` this is not.**

### To Reproduce

Program.cs (Web API Template + Application Insights added)
```csharp
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services
    .AddApplicationInsightsTelemetry()
    .AddControllers();

var app = builder.Build();

// Configure the HTTP request pipeline.
app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();
app.Run();

```

Default WeatherForecastController with added logging
```csharp
[HttpGet]
public IEnumerable<WeatherForecast> Get()
{
   var t = Activity.Current;

   _logger.LogWarning("Writing from API2");

   _logger.LogWarning($"Writing from API2 Activity.ParentId: {t.ParentId}");
   _logger.LogWarning($"Writing from API2 Activity.TraceId: {t.TraceId}");
   _logger.LogWarning($"Writing from API2 Activity.ParentSpanId: {t.ParentSpanId}");
   _logger.LogWarning($"Writing from API2 Activity.SpanId: {t.SpanId}");

   return Enumerable.Range(1, 5).Select(index => new WeatherForecast
   {
      Date = DateTime.Now.AddDays(index),
      TemperatureC = Random.Shared.Next(-20, 55),
      Summary = Summaries[Random.Shared.Next(Summaries.Length)]
   })
   .ToArray();
}
```

We will close this issue if:

* The repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
* If we will not be able to repro the behavior you're reporting

### For Immediate Support

For immediate support relating to the Application Insights .NET SDK we encourage you to file an [Azure Support Request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) with Microsoft Azure instead of filing a GitHub Issue in this repository. 
You can do so by going online to the [Azure portal](https://portal.azure.com/) and submitting a support request. Access to subscription management and billing support is included with your Microsoft Azure subscription, and technical support is provided through one of the [Azure Support Plans](https://azure.microsoft.com/support/plans/). For step-by-step guidance for the Azure portal, see [How to create an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). Alternatively, you can create and manage your support tickets programmatically using the [Azure Support ticket REST API](https://docs.microsoft.com/rest/api/support/)

**Comment by cijothomas** [comment]
https://learn.microsoft.com/en-us/azure/azure-monitor/app/correlation

If you do logging (logger.Log..) from inside the scope of an Activity(Span), then that Span is the parent of the Log (TraceTelemetry). i.e the Log will have its operation.ParentId set to the SpanId of the current activity. The span itself may have other parent.
