### ISSUE TITLE
How to integration test with app insights?

### ISSUE THREAD

**Issue by matthiasguentert** [microsoft/ApplicationInsights-dotnet#2692]
I am working on an open-source project that enriches app insights request telemetry with the HTTP request/response body. This is realized with a custom middleware component. You can find the project here: https://github.com/matthiasguentert/azure-appinsights-logger. 

Unfortunately, I am having difficulties properly testing that telemetry is really getting enriched and sent. While researching (aka. googling), I found people providing their own `ITelemetryChannel` implementation for testing. 

However, this didn't work for me. At least I couldn't get the debugger to halt at any breakpoint set in any method of my [FakeTelemetryChannel.cs](https://github.com/matthiasguentert/azure-appinsights-logger/blob/ipmasking/test/ApplicationInsightsRequestLoggingTests/FakeTelemetryChannel.cs). 

I might be doing something wrong in the way I set up the DI container for testing (see my test [here](https://github.com/matthiasguentert/azure-appinsights-logger/blob/e3bf4839c94ac8bb575501eb7c13bbdf016b26a6/test/ApplicationInsightsRequestLoggingTests/BodyLoggerMiddlewareTests.cs#L188)). 

Any input on how to properly mock `ServerTelemetryChannel` or any other way to test this scenario would be highly appreciated! Thanks in advance.

**Comment by TimothyMothra** [comment]
In your test you're adding your Channel as a singleton: `services.AddSingleton<FakeTelemetryChannel>();`


I think you need to give it the name of the interface like this: 
https://github.com/microsoft/ApplicationInsights-dotnet/blob/23181177558f2b2879dc6bf411fdf0b7d3edc479/NETCORE/test/Microsoft.ApplicationInsights.AspNetCore.Tests/Extensions/ApplicationInsightsExtensionsTests/AddApplicationInsightsTelemetryTests.cs#L1207


Try that and let us know if that works.

**Comment by matthiasguentert** [comment]
Thanks for replying and good catch! Now my fake implementation gets called. However, it only receives a call to `Dispose` and my `SentTelemetries` collection (see below) is always empty. 

Also, the DI container doesn't hold any implementation of `ITelemetryChannel` (besides my fake one, of course). According to the documentation I would have expected two instances (InMemory and ServerTelemetryChannel) to be registered. 

Any more ideas? 

```
public class FakeTelemetryChannel : ITelemetryChannel
{
    public ConcurrentBag<ITelemetry> SentTelemtries = new();
    public bool IsFlushed { get; private set; }
    public bool? DeveloperMode { get; set; }
    public string EndpointAddress { get; set; }

    public void Send(ITelemetry item)
    {
        SentTelemtries.Add(item);
    }

    public void Flush()
    {
        IsFlushed = true;
    }

    public void Dispose()
    {
    }
}
```

**Comment by TimothyMothra** [comment]
I would expect only one TelemetryChannel.
When you set the singleton for ITelemetryChannel, that's the one that the `TelemetryConfiguration` should take. This is exactly what that unit test I linked above is validating :) 


You can take a look at our example apps.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/23181177558f2b2879dc6bf411fdf0b7d3edc479/examples/AspNetCoreWebApp/Startup.cs#L28-L50

When resolving objects from DI, you can inspect the `TelemetryConfiguration` and confirm that this matches your expected configuration.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/23181177558f2b2879dc6bf411fdf0b7d3edc479/examples/AspNetCoreWebApp/Controllers/HomeController.cs#L22-L30

**Comment by matthiasguentert** [comment]
I am feeling stupid. The test setup works as intended. The issue I am facing is related to concurrency. The test finishes earlier than the call to `FakeTelemetryChannel.Send`. That's why the debugger only breaks at the `FakeTelemetryChannel.Dispose`. 

```
public class FakeTelemetryChannel : ITelemetryChannel
{
    public List<ITelemetry> SentTelemtries = new();
    public bool IsFlushed { get; private set; }
    public bool? DeveloperMode { get; set; }
    public string EndpointAddress { get; set; }

    public void Send(ITelemetry item)
    {
        SentTelemtries.Add(item);
    }

    public void Flush()
    {
        IsFlushed = true;
    }

    public void Dispose()
    {
    }
}
```

When I block the thread for a second, the test succeeds...

```
[Fact]
public async void BodyLoggerMiddleware_Should_Disable_Ip_Masking()
{
    // Arrange            
    using var host = await new HostBuilder()
        .ConfigureWebHost(webBuilder =>
        {
            webBuilder
                .UseTestServer()
                .ConfigureTestServices(services =>
                {
                    // Set fake client IP 
                    services.AddSingleton<FakeRemoteIpAddressMiddleware>();
                    
                    // Register stub telemetry channel for testing
                    services.AddSingleton<ITelemetryChannel, FakeTelemetryChannel>();
                    
                    // Register app insights infrastructure
                    services.AddApplicationInsightsTelemetry();
                    
                    // Add request body logging middleware
                    services.AddAppInsightsHttpBodyLogging(o =>
                    {
                        // Ensure middleware kicks in on success status
                        o.HttpCodes.Add(StatusCodes.Status200OK);
                        o.DisableIpMasking = true;
                    });
                })
                .Configure(app =>
                {
                    app.UseMiddleware<FakeRemoteIpAddressMiddleware>();
                    app.UseAppInsightsHttpBodyLogging();
                    app.Run(async context =>
                    {
                        // Send request body back in response body
                        await context.Request.Body.CopyToAsync(context.Response.Body);
                    });
                });
        })
        .StartAsync();

    // Act
    var response = await host.GetTestClient().PostAsync("/", new StringContent("Hello from client"));
    
    // Assert
    Thread.Sleep(TimeSpan.FromSeconds(1)); // UGLY, ugly way to synchronize 

    var channel = host.Services.GetService<ITelemetryChannel>() as FakeTelemetryChannel;
    var body = await response.Content.ReadAsStringAsync();
    body.Should().Be("Hello from client");

    channel.Should().NotBeNull();
    channel?.SentTelemtries.Should().HaveCount(1);
    var requestItem = channel?.SentTelemtries.First() as RequestTelemetry;
    
    requestItem.Should().NotBeNull();
    requestItem?.Properties["ClientIp"].Should().Be("127.168.1.32");
}
```

So I need to rephrase my initial question: How can I properly synchronize these threads to get rid of `Thread.Sleep()`?

**Comment by TimothyMothra** [comment]
Unfortunately, a short wait would be necessary here because a unit test is so short lived. 

We do recommend Flushing and waiting when an application is shutting down.
- https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#flushing-data
- https://learn.microsoft.com/en-us/azure/azure-monitor/app/console#full-example

I understand this is not ideal for a unit test. You might instead consider implementing a SpinWait pattern here. 
For an example see [this from OpenTelemetry](https://github.com/open-telemetry/opentelemetry-dotnet/blob/6ce883b7f4998335d005eaa1b8bab54d9dcb5795/test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs#L886-L892)

**Comment by matthiasguentert** [comment]
> Unfortunately, a short wait would be necessary here because a unit test is so short lived.
> 
> We do recommend Flushing and waiting when an application is shutting down.
> 
> * https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#flushing-data
> * https://learn.microsoft.com/en-us/azure/azure-monitor/app/console#full-example
> 
> I understand this is not ideal for a unit test. You might instead consider implementing a SpinWait pattern here. For an example see [this from OpenTelemetry](https://github.com/open-telemetry/opentelemetry-dotnet/blob/6ce883b7f4998335d005eaa1b8bab54d9dcb5795/test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs#L886-L892)

Nice! The SpinWait pattern solves this issue for me! Wasn't aware of it! Thanks again for your support!

**Comment by peter-barnet-qs-newday** [comment]
> Unfortunately, a short wait would be necessary here because a unit test is so short lived.
> 
> We do recommend Flushing and waiting when an application is shutting down.
> 
> * https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#flushing-data
> * https://learn.microsoft.com/en-us/azure/azure-monitor/app/console#full-example
> 
> I understand this is not ideal for a unit test. You might instead consider implementing a SpinWait pattern here. For an example see [this from OpenTelemetry](https://github.com/open-telemetry/opentelemetry-dotnet/blob/6ce883b7f4998335d005eaa1b8bab54d9dcb5795/test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs#L886-L892)

Adding this, from the advice above, got my flaky tests on RequestTelemetry to stabilise:
    `await Services.GetRequiredService<TelemetryClient>().FlushAsync(CancellationToken.None);`

**Comment by qualitas-software** [comment]
> Unfortunately, a short wait would be necessary here because a unit test is so short lived.
> 
> We do recommend Flushing and waiting when an application is shutting down.
> 
> * https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics#flushing-data
> * https://learn.microsoft.com/en-us/azure/azure-monitor/app/console#full-example
> 
> I understand this is not ideal for a unit test. You might instead consider implementing a SpinWait pattern here. For an example see [this from OpenTelemetry](https://github.com/open-telemetry/opentelemetry-dotnet/blob/6ce883b7f4998335d005eaa1b8bab54d9dcb5795/test/OpenTelemetry.Instrumentation.AspNetCore.Tests/BasicTests.cs#L886-L892)

From the advice above, adding this before my assertions got my flaky tests on RequestTelemetry to stabilise:
    `await Services.GetRequiredService<TelemetryClient>().FlushAsync(CancellationToken.None);`
