### ISSUE TITLE
Tracking MongoDb Dependencies

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [microsoft/ApplicationInsights-dotnet#2694]
**Is your feature request related to a problem?**
Yes, I can't monitor my mongodb without extensive base-code changes

**Describe the solution you'd like.**
To have the SDK capturing MongoDb dependencies as it does for Sql Server. https://www.nuget.org/packages/mongodb.driver would suffice

**Describe alternatives you've considered.**
Wrapping every query with a dependency telemetry

**Additional context.**
No additional context required

**Comment by NikolaSivkov** [comment]
Hey @Leonardo-Ferreira, just last week I've used this package https://www.nuget.org/packages/MongoDB.ApplicationInsights
in our codebase, even though it hasn't been updated in 2 years, it's still a valid & working way to do it.
