### ISSUE TITLE
Optimize ServerTelemetryChannel for Console App

### ISSUE THREAD

**Issue by jezzsantos** [microsoft/ApplicationInsights-dotnet#2696]
Hello,

A question around optimizing the `ServerTelemetryChannel` for use in a desktop console application.

## Context 
I have a CLI that usually only executes for a few hundred milliseconds, in normal operation. It does its thing and exits.
The user is going to be using it perhaps once, or perhaps several times in quick succession.

The telemetry that is created with each use is vital for tracking their usage.

We normally raise about ~10 telemetry events (using `telemetryClient.TrackEvent()`), and we may need to do a `telemetryClient.TrackException()` as well if the CLI raises an exception. No other telemetry is reported.

We clearly want to support being offline, since many laptops are offline when using this CLI, and they go online at some time in the future.

However, when we run and the laptop is online we want to blast all the stored telemetry to the cloud before we shut down.

## Current Solution

We are using the `ServerTelemetryChannel` and we are forcing it to store locally (using `channel.StorageFolder`)

Currently, playing with this config:
```
            var channel = new ServerTelemetryChannel();
            channel.StorageFolder = GetStoragePath();
            channel.MaxTelemetryBufferCapacity = 2; // nothing stored in memory, send immediately to disk
            channel.MaxTelemetryBufferDelay = TimeSpan.FromSeconds(1);
            channel.MaxTransmissionSenderCapacity = 100; // blast 100 at a time to cloud
            channel.MaxTransmissionStorageCapacity = 10000000; //store as much as needed 10MB
            channel.MaxTransmissionBufferCapacity = 2; // ?Confused about this and MaxTelemetryBufferCapacity 
```

and we are calling `telemetryClient.Flush()` on the `Dispose()` method of our classes that use the `TelemetryClient` while the CLI is running.

## Problem

Not seeing any transmissions stored locally. Not seeing any telemetry arrive in Azure.

## Question

My question is how to configure it so that no telemetry is ever left in memory when it exits, AND how to make it blast any stored transmissions as soon as it is started up again, as quick as possible?

Can someone offer some insights and guidance on how to optimize these settings for this?

**Comment by dialedin2014** [comment]
I am also having trouble getting telemetry sent to disk in a console app. 

There is a todo item in the source file.  Maybe it's not implemented.  See line 46.  https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs

**Comment by cijothomas** [comment]
> I am also having trouble getting telemetry sent to disk in a console app.
> 
> There is a todo item in the source file. Maybe it's not implemented. See line 46. https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs

could you clarify what is "not implemented" part that you are looking?

**Comment by cijothomas** [comment]
> My question is how to configure it so that no telemetry is ever left in memory when it exits,

Use the FlushAsync which was added in https://github.com/microsoft/ApplicationInsights-dotnet/pull/2202

**Comment by dialedin2014** [comment]
> > I am also having trouble getting telemetry sent to disk in a console app.
> > There is a todo item in the source file. Maybe it's not implemented. See line 46. https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs
> 
> could you clarify what is "not implemented" part that you are looking?

The part that writes the telemetry output to a local folder

**Comment by cijothomas** [comment]
> > > I am also having trouble getting telemetry sent to disk in a console app.
> > > There is a todo item in the source file. Maybe it's not implemented. See line 46. https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs
> > 
> > 
> > could you clarify what is "not implemented" part that you are looking?
> 
> The part that writes the telemetry output to a local folder

where does it say "write telemetry output to local folder" is not implemented? It is already implemented and is available for a very long time.

**Comment by dialedin2014** [comment]
> > > > I am also having trouble getting telemetry sent to disk in a console app.
> > > > There is a todo item in the source file. Maybe it's not implemented. See line 46. https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs
> > > 
> > > 
> > > could you clarify what is "not implemented" part that you are looking?
> > 
> > 
> > The part that writes the telemetry output to a local folder
> 
> where does it say "write telemetry output to local folder" is not implemented? It is already implemented and is available for a very long time.

It's not clear (to me at least) what the comment implies.  [This is the excerpt](https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/BASE/src/ServerTelemetryChannel/ServerTelemetryChannel.cs).  The line number is 43, not 46.

`#if NETFRAMEWORK
        [SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Justification = "WebApplicationLifecycle is needed for the life of the application.")]
        public ServerTelemetryChannel() : this(new Network(), new WebApplicationLifecycle())
#else
        // TODO: IApplicationLifecycle implementation for netcore need to be written instead of null here.
        public ServerTelemetryChannel() : this(new Network(), null)
#endif`

**Comment by cijothomas** [comment]
^ this is unrelated, and you can ignore it.
