### ISSUE TITLE
Question: Correlate operations over EventGrid for non-function apps.

### ISSUE THREAD

**Issue by Hjortsberg** [microsoft/ApplicationInsights-dotnet#2708]
Hi AppInsights team!

**Goal:**
I have some services that communicate by EventGrid (using EventGridEvent format), I now want to correlate the executions in AppInsights so that I can get a clear transaction diagnostics graph.

**Problem**
Each incoming request gets a new operationId instead of respecting the `traceparent` in the event data. I want all related executions bundled under the same operationId.

**What I've tried**
**Approach 1**
I followed the guide in [this Microsoft Devblog](https://devblogs.microsoft.com/azure-sdk/distributed-tracing-with-azure-functions-event-grid-triggers/) and didn't get it to work properly. 
Incoming event data example:
```json
[
    {
        "id": "54b02002-c4a2-4c2c-90ba-42a3d314fe92",
        "subject": "sub",
        "data": {
            "traceparent": "00-1e5375115ac40d1a4ef591e38a09d67e-a74667057eb7c657-00",
            "tracestate": "|1e5375115ac40d1a4ef591e38a09d67e.a74667057eb7c657."
        },
        "eventType": "type",
        "dataVersion": "1",
        "metadataVersion": "1",
        "eventTime": "2020-09-23T03:02:17.8952709Z",
        "topic": "topic"
    }
]
```
In my controller I call this as soon as possible:
```csharp
LinkContext(Activity.Current, baseEvent);
```

```csharp
public static void LinkContext(Activity? activity, EventModel eventData)
{
    if (activity != null && IsValidTraceparent(eventData.Traceparent))
    {
        var link = new AzureMonitorLink(eventData.Traceparent.Substring(3, 32),
            eventData.Traceparent.Substring(36, 16));

        activity.AddTag("_MS.links", JsonSerializer.Serialize(new[] { link }));
        activity.TraceStateString = eventData.Tracestate;
    }
}

private static bool IsValidTraceparent(string? traceparent) => traceparent != null &&
                                                               traceparent.StartsWith("00-") && traceparent.Length == 55;
private readonly record struct AzureMonitorLink(string operation_Id, string id);
```
The Resulting ai request data does not contain `_MS.links` in properties!:
```json
{
	"name": "AppRequests",
	"time": "2022-11-07T23:58:51.8043764Z",
	"iKey": "redacted",
	"tags": {
		"ai.application.ver": "1.0.0.0",
		"ai.cloud.roleInstance": "redacted",
		"ai.operation.id": "025e2f9f276320d3c8494451f488c18f",
		"ai.operation.name": "POST EventGridListener",
		"ai.location.ip": "::1",
		"ai.internal.sdkVersion": "aspnet5c:2.20.0+51c3ed8aa3f32209edf01168f9136a3ac8486c5d",
		"ai.internal.nodeName": "redacted"
	},
	"data": {
		"baseType": "RequestData",
		"baseData": {
			"ver": 2,
			"id": "2d4bcd89afa880e7",
			"name": "POST EventGridListener",
			"duration": "00:00:02.9236110",
			"success": true,
			"responseCode": "200",
			"url": "https://localhost:5001/",
			"properties": {
				"tracestate": "|1e5375115ac40d1a4ef591e38a09d67e.a74667057eb7c657.",
				"_MS.ProcessedByMetricExtractors": "(Name:\u0027Requests\u0027, Ver:\u00271.1\u0027)",
				"DeveloperMode": "true",
				"AspNetCoreEnvironment": "Development"
			}
		}
	}
}
```
What seems to fail is to link the operationIds to each other using `Activity.AddTag("_MS.links", JsonSerializer.Serialize(new[] { link }))`. I researched this and found [this old issue](https://github.com/microsoft/ApplicationInsights-dotnet/issues/562#issuecomment-696236846) and it seems that I should use a `TelemetryInitializer` for non-Azure Functions. 

**Approach 2**
This seems to at least link in the operationId from the body, but the transaction diagnostics graph does not show related telemetry.
And there are now 3 operationIds in the transaction diagnostics graph when I only want 1.
```csharp
RequestTelemetry requestTelemetry = HttpContext.Features.Get<RequestTelemetry>();
requestTelemetry.Properties.Add("_MS.links", JsonSerializer.Serialize(new[] { link })); //link is of type AzureMonitorLink as above
```
**Approach 3**
Here I tried to re-assign the OperationId on the Request telemetry object in the HttpContext with the traceId part from the `traceparent`. This didn't work.
```csharp
RequestTelemetry requestTelemetry = HttpContext.Features.Get<RequestTelemetry>();
requestTelemetry.Context.Operation.Id = event.Traceparent.Substring(3, 32); // assign the HTTP context operation id, the id from the body
```

How can I solve this? Am I supposed to use the incoming `traceparent` and `tracestate` from body, in a telemetry initializer?  I understand that I shouldn't read the body inside a telemetry initializer. 

Any help is greatly appreciated!

**Comment by cijothomas** [comment]
>         activity.AddTag("_MS.links", JsonSerializer.Serialize(new[] { link }));

^ If this tag not being added to the Req/Dependency telemetry, then you can write an initializer, which populated activity tags into properties. Could you try that.

**Comment by Hjortsberg** [comment]
@cijothomas
I modified my code to instead set the links on the telemetry properties. like so:
```csharp
public static void LinkContext(Activity? activity, EventModel eventData, RequestTelemetry telemetry)
{
    if (activity != null && IsValidTraceparent(eventData.Traceparent))
    {
        var link = new AzureMonitorLink(eventData.Traceparent.Substring(3, 32),
            eventData.Traceparent.Substring(36, 16));

        telemetry.Properties.Add("_MS.links", JsonSerializer.Serialize(new[] { link })); // Add MS.links to telemetry properties instead
        activity.TraceStateString = eventData.Tracestate;
    }
}
```
I do realize that this method only links the upstream `traceId` to the requestTelemetry and not exception and metrics telemetry, but I'm okay with that for now.

This correctly adds the previous `traceId` and it shows up correctly in the transaction diagnostics graph like this:
![Screenshot from 2022-11-10 12-47-57](https://user-images.githubusercontent.com/17297258/201092438-4ef28008-be73-4a97-8feb-881c8a9f8193.png)

BUT only if the linked `traceId` resides in the same ApplicationInsights instance! Please see below attached image, trying to highlight the difference. Here, the transaction diagnostics view claims that "No operation with id d1e29294fbb8140c5b440ec878a9314a could be found. It may have been sampled out.". It does exist, just in another Application Insights instance for the application that is sending the Event to eventgrid.
![operationIdinotherApplicationInsightsInstance](https://user-images.githubusercontent.com/17297258/201092374-3631949e-23ed-4b5c-9535-3ab9375c3bc7.png)

So my new question is, can I only link and correlate traces within one Application Insights instance?

**Comment by Hjortsberg** [comment]
I just tried a different approach. 
Utilizing the built in feature of EventGrid [dynamic-headers](https://learn.microsoft.com/en-us/azure/event-grid/delivery-properties#setting-dynamic-header-values), configuring these to extract the value from `data.traceparent` and `data.tracestate` seems to solve **everything** for me! 🥳

This is the result I was chasing where all the requests correlate using the same operationId (trace-id) and I can see it in Transaction diagnostics. Unfortunately this creates a dependency on a upstream service (eventgrid) for the tracing to work. But I can live with that. :)

![success](https://user-images.githubusercontent.com/17297258/201105694-fd1fb727-12bf-4f02-809b-955cfd47c6f6.png)
