### ISSUE TITLE
Clock implementation is faulty

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#271]
This clock implementation is faulty:
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/1ccd5b466451db1884b242b6a58b3e9401a1fbcf/src/Core/Managed/Shared/Extensibility/Implementation/Clock.cs#L31

This implementation will accumulate error when windows adjusts time on the computer:

``` csharp
public DateTimeOffset Time 
{ 
    get { return InitialTimeStamp + OffsetStopwatch.Elapsed; } 
} 
```

**Comment by SergeyKanzhelev** [comment]
Same in OperationWatch in server:
``` csharp
        public static DateTimeOffset Timestamp(long elapsedTicks)
        {
            // Stopwatch ticks are different from DateTime.Ticks. 
            // Each tick in the DateTime.Ticks value represents one 100-nanosecond interval. 
            // Each tick in the ElapsedTicks value represents the time interval equal to 
            // 1 second divided by the Frequency.
            return StartTime.AddTicks(Convert.ToInt64(elapsedTicks * HundredNanosecondsPerTick));
        }
```

**Comment by abaranch** [comment]
CoreSDK fixed. OperationWatch is not fixed.

**Comment by cijothomas** [comment]
Closing this issue as this is fixed for base sdk. For web sdk, new issue is opened: Microsoft/ApplicationInsights-dotnet-server#286
