### ISSUE TITLE
Swapping from PersistenceChannel to ServerTelemetryChannel for desktop apps

### ISSUE THREAD

**Issue by aaron-0** [microsoft/ApplicationInsights-dotnet#2719]
We use Application insights throughout our system, spanning cloud and desktop apps (winforms, wpf & webview2 based).

The desktop apps have been using a fork of the no longer supported PersistenceChannel for a number of years.

Are you able to advise if there is anything I should consider before using ServerTelemetryChannel within a desktop app?

Some context:
* desktop apps all operate in a partial internet environment
* some desktop apps are single instances, others are multi

**Comment by TimothyMothra** [comment]
Hi. Please review this doc: https://learn.microsoft.com/azure/azure-monitor/app/telemetry-channels

**Comment by aaron-0** [comment]
Thanks for the link Timothy. I've reviewed the document. The most important part is probably that items > 48h are discarded. I can see this happening occasionally for our desktop apps.

I found this project https://github.com/novotnyllc/AppInsights.WindowsDesktop which has brought PersistanceChannel as far as .net 5 / AI 2.18. I'll look at replacing our own fork with that one.
