### ISSUE TITLE
Can't copy UserAgent request header from request to RequestTelemetry.Context.User.UserAgent

### ISSUE THREAD

**Issue by maryammadzadeh** [microsoft/ApplicationInsights-dotnet#2722]
Below is a very simple implementation of an initializer for grabbing the UserAgent since it's no longer in the request telemetry object.

If we set the requestTelemetry.Context.User.UserAgent to a value, its not transferred (?) to application insights (i don't see it in log analytics), but if we set the agent to the Context.User.Id property, it does.

Is the UserAgent property no longer possible to set and see in application insights? Is there a recommended way to do this now? Or is this a bug? I know that AI no longer supports adding the UserAgent by default in the sdk, but why can't we override it? 
```
public class UserAgentHeaderTelemetryInitializer : ITelemetryInitializer
{
    readonly IHttpContextAccessor _httpContextAccessor;

    public UserAgentHeaderTelemetryInitializer(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public void Initialize(ITelemetry telemetry)
    {
        if (telemetry is RequestTelemetry requestTelemetry)
        {
            if (_httpContextAccessor.HttpContext.Request.Headers.TryGetValue(HeaderNames.UserAgent, out var userAgent))
            {
                requestTelemetry.Context.User.UserAgent = userAgent; <---- doesn't work
                requestTelemetry.Context.User.Id = userAgent;        <---- does work
            }
        }
    }
}
```
Environment

- Netcore 6
- Azure AppService
- Windows
- "Microsoft.ApplicationInsights.AspNetCore" Version="2.20.0"

Thanks for reviewing this.

**Comment by pharring** [comment]
Dupe of #558
See https://github.com/Microsoft/ApplicationInsights-Announcements/issues/3 for an explanation.
@cijothomas, I think we should add an ObsoleteAttribute on the Context.User.UserAgent property, with text that points to docs.

**Comment by maryammadzadeh** [comment]
Its not exactly a dupe since im trying to understand why setting userid works but not useragent? I am asking for a recommendation.

**Comment by pharring** [comment]
I wouldn't use User.Id instead of UserAgent because the Portal has some custom UI and dashboards around "user cohorts" that expects User.Id and User.AuthenticatedId to be stable, unique user identifiers. 

My recommendation is to use a custom property.

**Comment by maryammadzadeh** [comment]
Ok, thanks. Yeah, having that the property depreciated would help future integrators. Thanks for the quick response. I guess we can close this.

For anyone who wants to do this, use this

```
  if (telemetry is RequestTelemetry requestTelemetry)
            {
                if (_httpContextAccessor.HttpContext.Request.Headers.TryGetValue(HeaderNames.UserAgent, out var userAgent))
                {
                    requestTelemetry.Properties.Add(HeaderNames.UserAgent, userAgent);
                }
            }
```

**Comment by cijothomas** [comment]
> Dupe of #558 See [microsoft/ApplicationInsights-Announcements#3](https://github.com/microsoft/ApplicationInsights-Announcements/issues/3) for an explanation. @cijothomas, I think we should add an ObsoleteAttribute on the Context.User.UserAgent property, with text that points to docs.

Thanks.
@TimothyMothra Could you add Obsolete attribute?

**Comment by rgueldenpfennig** [comment]
> > Dupe of #558 See [microsoft/ApplicationInsights-Announcements#3](https://github.com/microsoft/ApplicationInsights-Announcements/issues/3) for an explanation. @cijothomas, I think we should add an ObsoleteAttribute on the Context.User.UserAgent property, with text that points to docs.
> 
> Thanks. @TimothyMothra Could you add Obsolete attribute?

I just ran into this issue as well. An `Obsolete` attribute with further details would be really helpful and time saving here.
