### ISSUE TITLE
TelemetryProcessor is not getting initialized in worker service

### ISSUE THREAD

**Issue by vikneshrajspui** [microsoft/ApplicationInsights-dotnet#2726]
I am trying to suppress `ServiceBusReceiver.Receive` with a telemetry processor to filter it. But the telemetry processor is not getting initialized so it is not working.
I could see the TelemetryInitializer is getting initialized and is working. 
Target framework is `net6.0`.
Microsoft.ApplicationInsights.WorkerService - `2.21.0`
Following is my configuration
```
 services.AddApplicationInsightsTelemetryWorkerService(configuration);
 services.AddSingleton<ITelemetryProcessorFactory>(builder => new TelemetryFilterProcessorFactory(configuration));
 services.AddSingleton<ITelemetryInitializer, WorkerSamplingTelemetryInitializer>();
```
Also tried the alternate way of adding a telemetry processor to encounter this issue - ambiguity between method error
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1520

Above TelemetryProcessor works with Microsoft.NET.Sdk.Web on following configuration
```
 services.AddApplicationInsightsTelemetry();
 services.AddSingleton<ITelemetryProcessorFactory>(builder => new TelemetryFilterProcessorFactory(configuration));
```
Appreciate your suggestion to resolve this issue.

**Comment by cijothomas** [comment]
https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service#add-telemetry-processors Could you try this approach and add some Procesor and see if it gets picked up?

**Comment by jarvan-jiang** [comment]
If your application is start from webapi, you must use the ASPNETCORE version:
`builder.Services.AddSingleton<Microsoft.ApplicationInsights.AspNetCore.ITelemetryProcessorFactory>`
