### ISSUE TITLE
ITelemetryInitializers log filter is not configurable for azure functions using host.json

### ISSUE THREAD

**Issue by AbhiAgarwal192** [microsoft/ApplicationInsights-dotnet#2727]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:

Microsoft.ApplicationInsights.WorkerService version 2.21.0

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file): net7.0
* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.): Windows

### Describe the bug

I want to call ITelemetryInitializer for information level logs to update the message before it gets logged to application insights but the log filter is not working properly. ITelemetryInitializer gets called only for log level warning and above.

I tried configuring the log level filter as below but it didn't work:

{
    "version": "2.0",
    "logging": {
        "logLevel": {
            "default": "Information"
        },
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": false
            }
        }
    }
}

It works when I try to achieve the same using code as shown below:

services.AddLogging(loggingBuilder => loggingBuilder.AddFilter<Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider>("", LogLevel.Information));

### To Reproduce

Here is the repo link to reproduce the issue:
https://github.com/AbhiAgarwal192/azure-functions-dotnet-worker 

In the project, I have created a TelemetrySanitizer class which is an implementation of ITelemetryInitializer and added it to FunctionApp azure function.

To reproduce the issue:

1) Put a breakpoint in line 36 of TelemetrySanitizer.cs.
2) Run the FunctionApp azure function locally.
3) After the function app is hosted locally, call the HttpTriggerSimple endpoint.
4) Observe that TelemetrySanitizer is only called for log level warning and above.

### For Immediate Support

For immediate support relating to the Application Insights .NET SDK we encourage you to file an [Azure Support Request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) with Microsoft Azure instead of filing a GitHub Issue in this repository. 
You can do so by going online to the [Azure portal](https://portal.azure.com/) and submitting a support request. Access to subscription management and billing support is included with your Microsoft Azure subscription, and technical support is provided through one of the [Azure Support Plans](https://azure.microsoft.com/support/plans/). For step-by-step guidance for the Azure portal, see [How to create an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). Alternatively, you can create and manage your support tickets programmatically using the [Azure Support ticket REST API](https://docs.microsoft.com/rest/api/support/)

**Comment by AbhiAgarwal192** [comment]
Is there an update here?

**Comment by cijothomas** [comment]
_I want to call ITelemetryInitializer for information level logs to update the message before it gets logged to application insights but the log filter is not working properly. ITelemetryInitializer gets called only for log level warning and above._

Only warning or above is captured by default if you enabled application insights worker service.
https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service#ilogger-logs


_I tried configuring the log level filter as below but it didn't work:_

That looks incorrect. See below:
https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core?tabs=netcorenew%2Cnetcore6#how-do-i-customize-ilogger-logs-collection

**Comment by AbhiAgarwal192** [comment]
These doesn't work. Please try reproducing with the steps mentioned in the bug.

**Comment by cijothomas** [comment]
I can reopen if you have a repro outside Azure Functions.
Functions is a special case, and is not part of this repo.

See:
If you're running the application in Azure Functions, please file an issue [here](https://github.com/Azure/azure-functions-host/issues/new/choose).
