### ISSUE TITLE
CorrelationVector isn't displayed on the portal

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/ApplicationInsights-dotnet#273]
I'm assigning a value to `ITelemetry.Context.Operation.CorrelationVector` inside a custom `ITelemetryInitializer` but this value isn't displayed anywhere on the portal, isn't searchable either.
I want to use it as a correlation id. Is it correct? Should I use something else instead?

**Comment by SergeyKanzhelev** [comment]
`CorrelationVector` is not supported yet. We will be improving the correlation story. Meanwhile please use `Operaiton.Id` and `Operation.ParentId` as well as `RequestTelemetry.Id`

**Comment by SergeyKanzhelev** [comment]
If you have a scenario when you need `CorrelationVector` - let me know.

**Comment by abatishchev** [comment]
Don't have a specific or complex scenario, just have read at https://libraries.io/github/SergeyKanzhelev/BO that this likely would the right approach. Oh, that was you! :)

**Comment by SergeyKanzhelev** [comment]
It will be. We will post on [Azure blog](https://azure.microsoft.com/en-us/blog/tag/application-insights/) when the correlation will be improved. Thanks for the interest!
