### ISSUE TITLE
visual studio and docker-compose not working

### ISSUE THREAD

**Issue by AnthonyDewhirst** [microsoft/ApplicationInsights-dotnet#2731]
I already created the following ticket: https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/issues/189 but have been advised to raise it here instead:

I created a brand new .net 6 web app and selected enable docker support, I then copied in the latest app insights and configured.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>98a17432-a18a-471c-b956-6cd9f60a0ca3</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.ApplicationInsights.Profiler.AspNetCore" Version="2.5.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
	</ItemGroup>

</Project>
```

```c#
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddApplicationInsightsTelemetry();
builder.Services.AddRazorPages();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();
```

and (appsettings.development.json):
```json
{
  "DetailedErrors": true,
  "Logging": {
    "LogLevel": {
      "Default": "Information"
    }
  },
  "ApplicationInsights": {
    "InstrumentationKey": "<guid>"
  }
}
```

I then ran using "docker" - not docker compose
The AI telemetry appeared straight away. All was well.

I then used the instructions at https://learn.microsoft.com/en-us/visualstudio/containers/tutorial-multicontainer?view=vs-2022 to ad the docker-compose project. 

I then started using "docker-compose". Now the application insights are no longer collected by visual studio.

**Comment by AnthonyDewhirst** [comment]
Hi @TimothyMothra I have been advised to tag you in this issue

**Comment by cijothomas** [comment]
Not sure how we can help... Have you ensured that the appsettings is correctly copied when running in docker? Or try hardcoding instrumentation key in code itself.

**Comment by AnthonyDewhirst** [comment]
I was under the impression that you didn't need a instrumentation key to see the results in visual studio. 
This isn't about the logging appearing in Application Insights in the portal, this is about developer mode and seeing the values in visual studio.
Either way, the value is in app settings correctly.
As I said, all I chose to do is change the setting from docker, to docker-compose and the values do not show in visual studio.
Hard coding the values is not a great idea anyways, as this is production code for a real application with many moving parts, and the chances of one of the devs accidentally saving a change like that would be high.

**Comment by dbreshears** [comment]
I was able to repoduce this. Thanks for the feedback and creating the developer community issue @AnthonyDewhirst.  I added a bug to our internal backlog to look into why this isn't working with Compose projects.

**Comment by dbreshears** [comment]
This is now resolved internally.  It should make its way out in the next 17.6 Preview release

**Comment by AnthonyDewhirst** [comment]
Great.
Does that mean it will also be in 17.5.2?

**Comment by dbreshears** [comment]
No, unfortunately 17.5.2 is already locked down.   With that said I am not sure this would meet the 17.5 servicing bar.
