### ISSUE TITLE
Can I control what exactly dependencies to write?

### ISSUE THREAD

**Issue by verdysh** [microsoft/ApplicationInsights-dotnet#2732]
Hello!
Asp .NET Core 6, hosted in Azure
Microsoft.ApplicationInsights.AspNetCore, 2.20.0
Here is my configuration

```
services.AddApplicationInsightsTelemetry(opt => opt.EnableAdaptiveSampling = false);
services.ConfigureTelemetryModule<DependencyTrackingTelemetryModule>((module, o) => module.EnableSqlCommandTextInstrumentation = true);
services.ConfigureTelemetryModule<EventCounterCollectionModule>(
	static (module, o) =>
	{
		module.UseEventSourceNameAsMetricsNamespace = true;
		var metrics = new Dictionary<string, List<string>>
		{
			["System.Runtime"] = new List<string>
			{
				"time-in-gc", "alloc-rate", "cpu-usage", "exception-count",
				"gc-heap-size", "gen-0-gc-count", "gen-0-size", "gen-1-gc-count", "gen-1-size",
				"gen-2-gc-count", "gen-2-size", "loh-size", "poh-size", "gc-fragmentation",
				"monitor-lock-contention-count", "active-timer-count", "assembly-count",
				"threadpool-completed-items-count", "threadpool-queue-length", "threadpool-thread-count",
				"working-set", "il-bytes-jitted", "method-jitted-count", "gc-committed-bytes"
			}
		};
		foreach (var kv in metrics)
			foreach (var counterName in kv.Value)
				module.Counters.Add(new EventCounterCollectionRequest(kv.Key, counterName));
	}
);
```

`opt.EnableAdaptiveSampling` is set to false because at some moment I understood that some logs are missed. After I had set it to false, this problem was gone.

At some moment we switched more traffic to the app and then we noticed that we pay more than $100 per day for Log Analytics. CTO was upset about that and then he made upset me.

The next query from Azure logs:
```
union dependencies, requests, exceptions, traces
| summarize count() by name
| order by count_ desc

```
returns the next result:

> SQL: tcp:server,1433 | DbName - 2,353,563
> ServiceBusReceiver.Receive - 587,948
> ServiceBusReceiver.Complete - 581,008
> Message - 456,886
> ServiceBusSender.Send - 456,882
> SQL: tcp:server,1433 | DbName - 369,730
> ServiceBusProcessor.ProcessMessage - 53,726

These are top results. I don't know why it didn't collapse `SQL: tcp:server,1433 | DbName` but it is not important for now.

From the result above we see that the biggest part of all the logs takes SQL queries.
Second place takes Service Bus. As I understand all the items besides SQL in my top results, there are logs of Service Bus.

I've thought that I don't need all the logs all the time. Maybe while investigating something, but not all the time. For example I can refuse SQL logs. Also I think I don't need all the logs from Service bus. I want to see only when message was sent to SB and when message was received from SB. I don't want to see all communication with SB because it's not what I really need.

I did't see any options in `ApplicationInsightsServiceOptions` nor in `DependencyTrackingTelemetryModule`. Also I looked into source code and I didn't find there any possibilities to manage this.

Can I restrict writing dependencies and make ApplicationInsights-dotnet to write not all but what I really need?

**Comment by cijothomas** [comment]
There is no fine tuned on/off switch in DepedencyTelemetryModule. It does have switches to turn off Azure calls. 
Alternatively, you can use TelemetryProcessors to filter out unwanted telemetry.

**Comment by verdysh** [comment]
Thanks! At first sight it seems it's what I need.
