### ISSUE TITLE
Application Insight in isolated Function app 

### ISSUE THREAD

**Issue by MianNajmi** [microsoft/ApplicationInsights-dotnet#2735]
I am facing issue in moving my function app code from in process to isolated process.  Here is my application insight code which i am using in my startup.cs. i am not using APPINSIGHTS_INSTRUMENTATIONKEY configuration.

 class Startup : FunctionsStartup
{

    public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
    {

        builder.ConfigurationBuilder.AddApplicationInsightsSettings(applicationInsightsInstrumentationConectionstring);

        }

    public override void Configure(IFunctionsHostBuilder builder)
    {
        builder.Services.AddApplicationInsightsTelemetry();

    }
}

Now i want to move it to program.cs for function app isolated process. i have tried different ways but it is not writing logs to application insight.

**Comment by cijothomas** [comment]
Functions uses a different way to integrating application insights.
If you're running the application in Azure Functions, please file an issue [here](https://github.com/Azure/azure-functions-host/issues/new/choose).
