### ISSUE TITLE
SQL Calls are not captured when using Microsoft.Data and InstrumentationEngine installed

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#2736]
When instrumentation engine is installed, DependencyCollector uses that to do byte-code injection and collect SQL Telemetry in .NET Framework apps, instead of relying on EventSource callbacks from System.Data.SqlClient, Microsoft.Data.SqlClient.

However, DependencyCollector only decorates (bytecode injects) System.Data.SqlClient to use with instrumentation engine, and not Microsoft.Data.SqlClient. : https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/WEB/Src/DependencyCollector/DependencyCollector/Implementation/ProfilerRuntimeInstrumentation.cs#L71

This results in no SQL calls being collected when all of the following conditions are met:
1. .NET Framework application
2. Using Microsoft.Data.SqlClient.
3. Have instrumentation engine enabled.

Workaround for now is to disable instrumentation engine or switch to System.Data.SqlClient.

**Comment by cijothomas** [comment]
The issue existed from 2019 itself when Microsoft.Data.SqlClient came out first. It could be treated as a bug or a feature request to support Ms.Data.SqlClient in instrumentation engine. Treating as a low priority for now. 

If you are affected, please comment below.

**Comment by byme8** [comment]
I would say it is a must-have feature. Without it, it can be tricky to investigate what is going on in your app. I don't see why it is a low priority.

> If you are affected, please comment below
I am affected, but I don't think you will get many responses here. Most devs who care about the feature know that it doesn't work for at least four years. So, they definitely have other telemetry SDKs in place for now. They will not come back to check if it is fixed or not. Looks like I have to select the same approach.

**Comment by cijothomas** [comment]
Its treated as low priority because we have only a single reported issue, and that was reported only a month or so ago. (despite this issue being present from day1)
