### ISSUE TITLE
AppInsight logs are not being shown from a .NET Framework 4.7.* web api

### ISSUE THREAD

**Issue by ctorresunimag95** [microsoft/ApplicationInsights-dotnet#2737]
Hi all, I am following this [documentation ](https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net) to enable monitoring in ASP .NET web application running in .NET Framework 4.7.2. I just created a sample app and followed the steps the document presents.

Once I run the app I can see in the debug console ap insight object logs
![image](https://user-images.githubusercontent.com/25542676/214869620-73a50d1e-a109-47d3-a2df-6e911a492cec.png)

Also, on the Visual Studio app insight page, I can see the traces of the request for my test application.
![image](https://user-images.githubusercontent.com/25542676/214873736-e9a627ae-1132-42e6-bfe2-97ab76914e40.png)

However, once I check app insight I can not see any logs. The only weird things I can see in mi local console after the app insights log object is displayed are some exceptions like this

```csharp
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
```

The application is running on IIS. Also, when the app starts I see the following message.

```csharp
"message":"AI: Diagnostic message: Performance counters are unavailable when the application is running under IIS Express. Use EnableIISExpressPerformanceCounters element with a value of 'true' within the Performance Collector Module element to override this behavior."
The parameters to the Event method do not match the parameters to the WriteEvent method. This may cause the event to be displayed incorrectly.
```

**Comment by cijothomas** [comment]
https://learn.microsoft.com/en-us/troubleshoot/azure/azure-monitor/app-insights/asp-net-troubleshoot-no-data#collect-logs-with-perfview Please collect sdk internal logs, so get a good idea why telemetry is not flowing.
