### ISSUE TITLE
Question: Ensure event is not touched by adaptive sampling

### ISSUE THREAD

**Issue by TobiasLaving** [microsoft/ApplicationInsights-dotnet#2739]
Hello,

First of I'm not sure this is the appropriate channel, if not I apologize. 

We run the default settings for application insights, meaning adaptive sampling, but want to be able to ensure certain insights will not be sampled. Sometimes we replay certain failed events in our system, and being able to ensure those events have application insights would be very helpful.

Perhaps this could be achieved by dynamically turning adaptive sampling on/off, or there is another way to achieve this?

Any ideas on how to approach this would be appreciated!

**Comment by cijothomas** [comment]
https://learn.microsoft.com/en-us/azure/azure-monitor/app/sampling?tabs=net-core-new#frequently-asked-questions Check the last one from the FAQ.
