### ISSUE TITLE
Confusion about ILogger, metrics, events and TelemetryClient

### ISSUE THREAD

**Issue by apilosofms** [microsoft/ApplicationInsights-dotnet#2753]
I don't know if this is a deliberate design choice or a documentation issue or just my confusion.

My code took a dependency on `ILogger`; it does some things nicely (eg; scopes, different loggers for different environments) and the docs generally suggest that it's the latest/greatest. We use the console logger in the dev environment and add the AI logger in staging/production. Meanwhile, all working nicely.

Now comes the time to add some metrics and events, which I'm used to from when I used `TelemetryClient` directly in previous projects. They're excellent because the Azure Monitor (nee AppInsights) UI knows how to treat the `customMetrics`/`customEvents` tables differently, making it easy to generate reports.

Turns out `ILogger` doesn't really do metrics/events - it just does traces/exceptions. After a bunch of searching around, I figure I have to rip it all out and use something else (maybe `TelemetryClient` directly, maybe SeriLog, maybe OpenTelemetry, etc). I don't want to do this because my code is pretty reliant on `ILogger` (esp scopes).

... So I maybe I have two concepts: "logging [traces]" and "logging [metrics]". If I add a `TelemetryClient` in my DI setup I can then take a dependency on both and use them for different things. I really dislike this, but I could make it work.

Except; it's really unclear to me what happens if I use **both** `AddApplicationInsights()` as well as `services.AddSingleton(new TelemetryClient(...))`. This will instantiate two instances of the `TelemetryClient` class. Is that ok? Are they going to conflict? How would I even know? I was hoping that `AddApplicationInsights()` would register a `TelemetryClient` internally, but it doesn't seem to.

All this feels very forced, making me suspicious that I'm missing something obvious. On the one hand Microsoft says "_Come use Azure Monitor, the UI is great!_", and on the other hand "_Use ILogger, which doesn't support the former all that well_".

What is it that I'm missing?
Thanks in advance!

**Comment by cijothomas** [comment]
_I was hoping that AddApplicationInsights() would register a TelemetryClient internally, but it doesn't seem to._

It does. If using standalone logger provider only, then see https://learn.microsoft.com/en-us/azure/azure-monitor/app/ilogger#im-using-the-standalone-package-microsoftextensionsloggingapplicationinsights-and-i-want-to-log-more-custom-telemetry-manually-how-should-i-do-that
If using a[[;ocatopm omsogjts fpr as[met cpre. tjem see tjos " https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core?tabs=netcorenew%2Cnetcore6#how-can-i-track-telemetry-thats-not-automatically-collected

**Comment by cijothomas** [comment]
"Use ILogger, which doesn't support the former all that well".

ILogger is the logging API and is only the logging API. There is no feature in ILogger to support metrics.

**Comment by apilosofms** [comment]
## This part is helpful!
Thank you Cijo; those docs you linked to are explicit; they are what I was hoping to find!

In my case I am using the standalone `Microsoft.Extensions.Logging.ApplicationInsights`, so it seems I do have to manually create a `TelemetryClient` (using the same configuration). They create it in the controller; I will add it as a singleton in DI.

## This part makes me think I'm going the wrong way:
However, reading more of those docs there is a section which pertains more closely to my app (since it's a long-running console app using DI):
https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service#net-corenet-framework-console-application

This suggests I shouldn't be using `Microsoft.Extensions.Logging.ApplicationInsights` at all, but rather `Microsoft.ApplicationInsights.WorkerService`!

## ... But this part seems to conflict with the one above:
There's also this doc right beside which supposedly pertains to ".net console" (same thing as above?) which describes a different process completely:
https://learn.microsoft.com/en-us/azure/azure-monitor/app/console

What I'm doing now "works" (ie; I see logs in AI), but is it the wrong way to do things? Should I be using `WorkerService` instead? Is my logging going to fail in unexpected ways using my current method?

## Finally - an aside:
Your last message said:

> ILogger is the logging API and is only the logging API.

My take on it is this: It's reasonable to think that logging _includes_ metrics (and exceptions and events) because:
- They're all stored in the same place (Az Monitor / AI)
- They're investigated in the same place (the Az Monitor UI)
- TelemetryClient has "taught" us this over the years
- Other logging packages do the same

**Comment by cijothomas** [comment]
> This suggests I shouldn't be using Microsoft.Extensions.Logging.ApplicationInsights at all, but rather Microsoft.ApplicationInsights.WorkerService!

I dont think any doc suggests the above. Each package is meant for different purposes, and if the docs are not clear - open doc issues right in that page.

**Comment by cijothomas** [comment]
> My take on it is this: It's reasonable to think that logging includes metrics (and exceptions and events) because:
> 
> They're all stored in the same place (Az Monitor / AI)
> They're investigated in the same place (the Az Monitor UI)
> TelemetryClient has "taught" us this over the years
> Other logging packages do the same

AzMonitor/AI stores (and shows) metrics in a different place. 
Irrespective of that, I dont think a particular product (AzMonitor) should determine what ILogger should be doing. This is a qn/suggestion to the ILogger docs/repo anyway.
