### ISSUE TITLE
How to use Azure App Insights in .Net Core without connectionstring

### ISSUE THREAD

**Issue by da-ms-22** [microsoft/ApplicationInsights-dotnet#2755]
We have a .Net Core project using Azure Applicaiton Insights. The project is configurated to access App Insights via Managed Identity. Below article shows connectionstring is still needed even DefaultAzureCredential is used. And our tests confirmed this. Is there a way to use Managed Identity to access App Insights without connectionstring? Thank you.

https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication

**Comment by pharring** [comment]
No. You always need a ConnectionString because it holds the InstrumentationKey that identifies which Application Insights resource to use.

**Comment by da-ms-22** [comment]
Thank you.
