### ISSUE TITLE
Telemetry Initializer for log masking

### ISSUE THREAD

**Issue by hjc1983** [microsoft/ApplicationInsights-dotnet#2760]
Is there some documentation of how to use telemetry initializer for masking the sensitive information in log statements? 

I found there is a similar post on [ApplicationInsights-Java](https://github.com/microsoft/ApplicationInsights-Java/issues/1605), wonder if there is something similar in dotnet or doco about it?

**Comment by 304NotModified** [comment]
I can share some code we use for this:

(MaskQueryStringValue is a more complex method which is probably different for your use case)

```c#
public class AnonymizeDataTelemetryInitializer : ITelemetryInitializer
{
    public void Initialize(ITelemetry telemetry)
    {
        if (telemetry is RequestTelemetry request)
        {
            if (request.Url != null)
            {
                // warning, the URL property could be null while the typing says not. See https://github.com/microsoft/ApplicationInsights-dotnet/issues/2601
                request.Url = request.Url.MaskQueryStringValue();
            }
        }
}
```

and registering:

```c#
services.AddSingleton<ITelemetryInitializer, AnonymizeDataTelemetryInitializer>();
```
