### ISSUE TITLE
Grant rights to Azure Function to Get Existing Alerts and to Change their State

### ISSUE THREAD

**Issue by JasonDWilson** [microsoft/ApplicationInsights-dotnet#2771]
#### Is your question related to a specific version? If so, please specify:
.Net 7

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I have 2 Azure Functions that need to be able to interact with log alerts in application insights.  I have enabled managed identities for these roles and tried to give them the Contributor role in in just Application Insights.  My code threw the following error: a Exception: Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed exception.

I tried granting the identities the owner role in both Application Insights and then in the entire resource group with the same result.
![image](https://user-images.githubusercontent.com/57236874/232900977-a9c9b6ba-c10e-47a0-90e9-e30bdca74729.png)

The functions work properly when run locally, but not when published to Azure even though they have the same rights that I do.

Here is the code that I am using to get a bearer token to use with the resource manager Rest API:

``` Csharp
        try
        {
            token = await GetAccessTokenAsync("https://management.azure.com/.default");
        }
        catch(Exception ex)
        {
            var result = $"Error retrieving token: {ex.Message}";
            _logger.LogError(ex, result);
            return result;
        }

        public async Task<string> GetAccessTokenAsync(string resourceId)
        {
            var tokenCredential = new DefaultAzureCredential();
            var accessToken = await tokenCredential.GetTokenAsync(
                new TokenRequestContext(scopes: new string[] { resourceId }));
            return accessToken.Token;
        }
```

Please advise on how I should proceed.

Thank you,

Jason

**Comment by TimothyMothra** [comment]
This repo is for the Application Insights .NET SDK.
You appear to be having issues with your Application Insights resource in the Azure Portal.

We can't help you with that. Please open a support request through the portal.
 https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by JasonDWilson** [comment]
Maybe you can help me with using SDK to do get alerts and change their state.  Wasn't able to find that in the documentation
