### ISSUE TITLE
How to make activities created by ASP.NET Core have the property `Recorded` equal to `true` with the Application Insights SDK

### ISSUE THREAD

**Issue by ghost** [microsoft/ApplicationInsights-dotnet#2775]
When using the Application Insights SDK in a web application, the activity `Microsoft.AspNetCore.Hosting.HttpRequestIn`, created by ASP.NET Core, has the property `Recorded` equal to `false` (trace-flag 00).

This breaks scenarios where this application calls another application (with an HTTP call for example) and the second application uses the OpenTelemetry SDK. By default, the OpenTelemetry SDK uses a sampler based on the [parent activity](https://github.com/open-telemetry/opentelemetry-dotnet/blob/88e8439efa5e833194890d2a569ebd61596a5992/src/OpenTelemetry/Trace/ParentBasedSampler.cs) which will discard all activities if the trace-flag is not equal to `Recorded` (even the first activity is dropped according to my tests). A possible solution is to override the default sampler in the second application (e.g. [AlwaysOnSampler](https://github.com/open-telemetry/opentelemetry-dotnet/blob/88e8439efa5e833194890d2a569ebd61596a5992/src/OpenTelemetry/Trace/AlwaysOnSampler.cs)) but the second application have to be aware of this behaviour.

Is there any way to make activities created by ASP.NET Core have the property `Recorded` equal to `true` when using the Application Insights SDK (which is the case by default when using the OpenTelemetry SDK)?

cc @cijothomas

**Comment by cijothomas** [comment]
Due to the fundamental difference in the way Application Insights Sampler works (it "tail-based" sampling, vs "head-based" in OpenTelemetry), this is not feasible (without lot of hacks). This was explored in the past (https://github.com/microsoft/ApplicationInsights-dotnet/issues/2156) and it was abandoned.

**Comment by cakescience** [comment]
Thank you for your prompt answer.

Can you confirm that changing the default sampler used by the OpenTelemetry SDK (e.g. [AlwaysOnSampler](https://github.com/open-telemetry/opentelemetry-dotnet/blob/88e8439efa5e833194890d2a569ebd61596a5992/src/OpenTelemetry/Trace/AlwaysOnSampler.cs)) is a suitable solution in this type of scenario (one application that uses the Application Insights SDK and a second that has migrated to OpenTelemetry)?
