### ISSUE TITLE
How to correlate trace telemetry like parent child relation ship

### ISSUE THREAD

**Issue by lypan** [microsoft/ApplicationInsights-dotnet#2776]
Hi,
  If I use start operation an request.telemetry first, then whenever I log any trace telemetry, it will show up under that request telemetry
Ex: 
The trace will have operation Id which is same as request operation id
```
start request telemetry
log trace telemetry .... etc
stop request telemetry
```
<img width="548" alt="image" src="https://user-images.githubusercontent.com/1889632/236379861-650db08d-efae-4216-a7d8-8b378ce4b3c6.png">

  But if I log trace telemetry in parent then children function

```
log trace telemetry in parent
log trace telemetry in child1
log trace telemetry in child2
```

The trace I see in app insight **won't have operation Id**

My question is that how do I let those trace under same parent have same operation Id, so I can easily correlate/summarize the trace

Ex:
  When I see the parent trace telemetry, I want to use operation Id to correlate related child trace telemetry under it.

**Comment by cijothomas** [comment]
TraceTelemetry is not an operation (with an start and end); its just a point-in-time log entry. And hence the TraceTelemetry itself cannot have the notion of children. 
Only Operations (Request,DependencyTelemetry) can have children.

**Comment by lypan** [comment]
So the trace telemetry won't have operation id
Only if they are under Operations(request/dependency)
Is it correct understanding?

**Comment by cijothomas** [comment]
Yes.

Also check the docs on this : https://learn.microsoft.com/en-us/azure/azure-monitor/app/distributed-tracing-telemetry-correlation
