### ISSUE TITLE
Channel should not send old data from local storage

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-dotnet#278]

**Comment by abaranch** [comment]
May be we want to send a single trace instead of the whole batch so customer can investigate the missing data issue.

**Comment by abaranch** [comment]
We are updating channel in the scope of this: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/318
This enchantments may be obsolete.

**Comment by SergeyKanzhelev** [comment]
It is implemented. 

See [this](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/TelemetryChannels/ServerTelemetryChannel/Shared/Implementation/TransmissionStorage.cs#L199-L200)

```
// The injestion service rejects anything older than 2 days.
if (file.DateCreated > DateTimeOffset.Now.AddDays(-2)) 
```

PR: https://github.com/Microsoft/ApplicationInsights-dotnet/pull/326/
