### ISSUE TITLE
Turning on AppInsights on Application Service breaks container initialisation

### ISSUE THREAD

**Issue by r-modica-cti** [microsoft/ApplicationInsights-dotnet#2781]
We have a site hosted on an Azure App Service which was happily running a sink via serialog to Application Insights but at some point in the last few weeks the container that we push to the app service (This is a Slot if that makes any difference) cannot start up and the only way we are able to resolve that is to disable Application insights on the App Service.

Errors are really light on the ground, the only error we are receiving is:

`Failed to initialize AppInsights IPA volume`

The docker logs simply show:

`Stopping site ct-api-prod because it failed during startup.`

But no volumes are currently defined for the container and no information about the error above can be located anywhere.  This is a really big issue for us as we cannot run any logging for a production application currently as we have to turn off app insights to be able to have functioning application.

**Comment by TimothyMothra** [comment]
Hello @r-modica-cti ,
It sounds like you're using the [Application Insights Extension for App Service](https://learn.microsoft.com/azure/azure-monitor/app/azure-web-apps). This repo is for the SDK only.

For support with the Extension, please open a [support request via the portal](https://learn.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).
