### ISSUE TITLE
Telemetry Items not sent on shutdown

### ISSUE THREAD

**Issue by NielsFilter** [Microsoft/ApplicationInsights-dotnet#281]
# My Context
Some custom events do not get sent just before shutdown (desktop application).

I'm using the `ServerTelemetryChannel` and `Flush` the channel on shutdown to ensure items get sent.

I understand that `ServerTelemetryChannel`'s `Flush()` is **synchronous** and therefore I assumed that my events will be sent before shutdown completes. However this isn't working as expected.

# Simplifying the problem
I created a simple console application that:
- sends a custom event just before shutdown
- I added various delays after flushing
- I used both Telemetry client and serverchannel flushing (which shouldn't make a difference in my scenario)
- Each test ran 100 times
- I checked how many items made it to the portal.
- Ran the tests with developer mode `true` and `false` to compare

# Results
_Note: Delay is in seconds and received means items showed up in the portal_
## Results for Dev Mode (DeveloperMode = true)
![image](https://cloud.githubusercontent.com/assets/4918407/17594341/3fbe4d9c-5fe9-11e6-9ed5-d6a93cdef0c7.png)

## Results for Release Mode (DeveloperMode = false)
![image](https://cloud.githubusercontent.com/assets/4918407/17594330/3a2014ba-5fe9-11e6-9dd0-6a7ff5fe1d2a.png)

# Conclusion
Tests showed me that in my context:
- Dev Mode is irrelevant
- Flushing with Client or Channel is irrelevant
- Only from 2 seconds delay after flushing do telemetry items come through consistently
- I'm still losing telemetry items even after a minute delay.

# My Concerns
1. Why is the flush not synchronous as I thought it to be?
2. Why did I never get 100% of the telemetry items, even after a long delay?

# Sample code

    static void Main(string[] args)
    {
        TelemetryConfiguration.Active.InstrumentationKey = "*** My Key ***";
    
        var telemetryChannel = new ServerTelemetryChannel();
        telemetryChannel.Initialize(TelemetryConfiguration.Active);
        TelemetryConfiguration.Active.TelemetryChannel = telemetryChannel;
    
        new TelemetryClient().TrackEvent($"Test event");
    
        TelemetryConfiguration.Active.TelemetryChannel?.Flush();
        Thread.Sleep(1000 * 1); // 1 second delay
    
        // Shutdown
    }

**Comment by abaranch** [comment]
Flush is not synchronous. Using it would increase chances of sending data out but there is no guarantee. Channel is designed for server applications like WCF, AspNet and cloud app services. It subscribes to domain unload event to save data on disk which is irrelevant in case of desktop app. Before transition to HockeyApp we had persistence channel that had synchronous Flush. Nuget package is still out there. But recommendation is to transition to HockeyApp. https://azure.microsoft.com/en-us/documentation/articles/app-insights-windows-desktop/.

**Comment by NielsFilter** [comment]
Thank you very much for the reply.

This is a bit misleading because the [flush method comment here] (https://github.com/Microsoft/ApplicationInsights-dotnet/blob/4dd948ef9c4ca26ecfd6e76adf3e5af0f59d7bcf/src/TelemetryChannels/ServerTelemetryChannel/Shared/ServerTelemetryChannel.cs#L210 ) says it is synchronous.

Our "main" application is a service that is successfully using the `ServerTelemetryChannel`. This desktop application in question is a type of "tool" which runs on the desktop making calls to our service. Why I mention this is that we would like this telemetry to also be captured in the same Application Insights service as the "main" application, so I'd prefer not to split telemetry between HockeyApp and Application Insights.

- Is there an event or callback on the Server Channel once items get sent?
- Or possibly block on the flush until items are sent?
- Or maybe a way to check whether some items have not been sent yet?

I appreciate the help.

**Comment by abaranch** [comment]
Thank you for pointing to the incorrect comment, I fixed it.
Unfortunately answer to all your questions is no. In case of shutdown I expect InMemoryChannel work better but it does not have any retries or persistence storage. That what we actually do for sending unhandled exceptions in worker roles: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/master/Src/WindowsServer/WindowsServer.Shared/UnhandledExceptionTelemetryModule.cs#L26 )
Other option would be to write your own channel, but that would require a lot of work from your side.

**Comment by dnduffy** [comment]
We could look at providing hooks to flush on app tear down; this has application in ASP.NET as well as in desktop apps.

**Comment by NielsFilter** [comment]
Thank you for the responses and advice. I ended up going with the In-Memory channel, it actually makes more sense in my scenario and it works **Great!!** Just for interest sake, I assume InMemory Channel flushes synchronously, is that correct?

I re-ran the same "shutdown benchmark" as posted in my question:

# Results for Dev Mode (DeveloperMode = true)
![image](https://cloud.githubusercontent.com/assets/4918407/17665061/cb41beaa-62f8-11e6-9724-c1c06b4225f8.png)

# Results for Release Mode (DeveloperMode = false)
![image](https://cloud.githubusercontent.com/assets/4918407/17665066/d0cb33d8-62f8-11e6-92f9-b93fe1c4dcb1.png)

*Results are near perfect! Only one miss (15 sec delay) which I can definitely live with!

**Comment by abaranch** [comment]
Yes, it is synchronous. Great that it works for you, it is the easiest solution.
