### ISSUE TITLE
LogLevel/SeverityLevel not being sent to AppInsights from console app

### ISSUE THREAD

**Issue by nayanshah** [microsoft/ApplicationInsights-dotnet#2810]
**Is your feature request related to a problem?**
`ILogger` messages in console apps can be forwarded to AppInsights using `AppInsightsLogger` but those are missing `LogLevel`. This makes is really difficult to filter messages based on severity. 

**Describe the solution you'd like.**
`LogLevel` or `SeverityLevel` should be included in all messages. `CategoryName` is included in `customDimensions` for each message and same could be done for LogLevel. 

This is already done for AppInsights messages forwarded from Azure Functions, so having some parity would be great. 

**Describe alternatives you've considered.**
One alternative would be calling not using `ILogger` implementation but would require explicitly calling `TelemetryClient` for each message, which is overkill.

**Comment by cijothomas** [comment]
https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/LOGGING/src/ILogger/ApplicationInsightsLogger.cs#L95 The ILogger provider in this repo is already adding Severity. If you do not see that, please share a **minimal** repro app.

"AppInsightsLogger" is not something this repo has, but I guess its a typo ?

**Comment by nayanshah** [comment]
Yes, I was referring to `ApplicationInsightsLogger.cs` and expecting the Severity to show up in `customDimensions` since AzureFunctions adds LogLevel there. 

But I do see separate column for Severity, so things are working as expected.

**Comment by cijothomas** [comment]
>  customDimensions since AzureFunctions adds LogLevel there.

^ would be a bug in AzureFunctions.
