### ISSUE TITLE
Using both TelemetryWorkerService and ApplicationInsightsLogger (question)

### ISSUE THREAD

**Issue by daningalla** [microsoft/ApplicationInsights-dotnet#2813]
In my console app, I referenced `Microsoft.Extensions.Logging.ApplicationInsights` and configured the logger using an `InMemoryChannel`. When I run the program, it creates trace telemetry which is visible in the Azure Portal App Insights instance.

When I add in the telemetry worker service, e.g. `services.AddApplicationInsightsTelemetryWorkerService()`, it begins tracking dependency telemetry across HTTP requests, Azure storage, etc. Problem is, when I add the telemetry worker service, my app stops sending traces. Is there a conflict somewhere in the service registrations? Does the worker service create its own channel that overrides the `InMemoryChannel`?.

Basic setup:
```csharp
using var telemetryChannel = new InMemoryChannel();
var host = new HostBuilder()
    .ConfigureAppConfiguration(...)
    .ConfigureLogging((context, logger) =>
    {
        logger.ClearProviders()
            .AddConsole()
            .AddApplicationInsights(
                configureTelemetryConfiguration: telemetry =>
                {
                    telemetry.TelemetryChannel = telemetryChannel;
                    telemetry.ConnectionString = context.Configuration["ConnectionStrings:ApplicationInsights"];
                    telemetry.SetAzureTokenCredential(new DefaultAzureCredential());
                },
                configureApplicationInsightsLoggerOptions: options =>
                {
                    options.TrackExceptionsAsExceptionTelemetry = true;
                    options.FlushOnDispose = true;
                    options.IncludeScopes = true;
                }
            );
    })
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
    })
    .Build();

var logger = host.Services.GetRequiredService<ILogger<Program>>();

try
{
    var telemetryClient = host.Services.GetRequiredService<TelemetryClient>();
    using var operation = telemetryClient.StartOperation<RequestTelemetry>("operation");
    logger.LogInformation("Application started successfully");

    // Other dependency calls, HTTP, storage, etc.
    
    telemetryClient.TrackEvent("Startup request event completed");
    await telemetryClient.FlushAsync(CancellationToken.None);
}
catch (Exception exception)
{
    logger.LogError(exception, "Unhandled exception occurred");
}
finally
{
    await telemetryChannel.FlushAsync(CancellationToken.None);
    await Task.Delay(2500);
}
```

**Comment by cijothomas** [comment]
> Does the worker service create its own channel that overrides the InMemoryChannel?.

It uses own channel. Check this doc if you want to change it. https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service#configure-the-telemetry-channel


`AddApplicationInsightsTelemetryWorkerService()` changes the config to only capture Warning or above by default.
https://learn.microsoft.com/en-us/azure/azure-monitor/app/worker-service#ilogger-logs

Is there any reason why you want to add the LoggerProvider explicitly? `AddApplicationInsightsTelemetryWorkerService` automatically does that, so there should be no need to add LoggerProvider separtely.

**Comment by daningalla** [comment]
Thanks @cijothomas, removed adding the logger and trace telemetry is now being reported. 

The logging framework is not applying filter rules defined in my json configuration files. Essentially, I have to add a filter rule in code for the AppInsights logger to bump the trace minimum level down to Info from Warning. That seems like it is an issue in the logging framework itself and not this SDK.

**Comment by daningalla** [comment]
Apparently you have to pass configuration specifically to the logger, `builder.AddConfiguration(builderContext.Configuration`.
