### ISSUE TITLE
What does the webgrease license apply to?

### ISSUE THREAD

**Issue by omajid** [microsoft/ApplicationInsights-dotnet#2814]
This is a non-open source license mentioned in the third-party-noticies

https://github.com/microsoft/ApplicationInsights-dotnet/blob/176977315c049183ece2ccab4416b0bedd1ea80b/WEB/ThirdPartyNotices.txt#L31

https://github.com/microsoft/ApplicationInsights-dotnet/blob/176977315c049183ece2ccab4416b0bedd1ea80b/WEB/ThirdPartyNotices.txt#L501-L622

Is there any code in this repo under this license? Does it only apply to the binary/build of the "Visual Studio Application Insights SDK for .NET Web Applications"?

**Comment by TimothyMothra** [comment]
I looked into this. There are more references in our archived repo: https://github.com/search?q=repo%3Amicrosoft%2FApplicationInsights-dotnet-server%20webgrease&type=code

Seems like these two references you found are leftovers from our old test framework that's no longer in use.
