### ISSUE TITLE
How to exclude specific Trace from getting sampled out in AppInsights using in .net 6,7

### ISSUE THREAD

**Issue by inishantmishra** [microsoft/ApplicationInsights-dotnet#2820]
Our Log messages either, Info, Warning, or Error sometimes get sampled out. That's okay, but some logs are very important and we don't wanna lose them. 
I read multiple articles to use TelemeteryProcessor or TelemeteryInitizlizers but it doesn't help.

I want some of my logs which are important, those logs should never get sampled out. When I implemented the telemetry processors and initializers I found that these logs are now even getting more sampled out as compared to other logs.

Please help how to do that.

@cijothomas

**Comment by cijothomas** [comment]
https://learn.microsoft.com/en-us/azure/azure-monitor/app/sampling#frequently-asked-questions Check this. It has guidance on this.

**Comment by cijothomas** [comment]
Sorry to hear that. But I cannot help without seeing a *minimal* repro of the issue, showing what have you attempted to fix this!

**Comment by inishantmishra** [comment]
@cijothomas 
Here is the repo link. https://github.com/inishantmishra/TestAzureDotnetIsolatedFunction/tree/master
I have an Azure Function- LoggingPOCFunction
which has 3 logging. 1 should get Sample with whatever logic exists for adaptive sampling and 2 logging should never be sampled.

I created an extension method that uses those 2 Loggings.
Kindly review and let me know what am i missing it here?

**Comment by cijothomas** [comment]
If you're running the application in Azure Functions, please file an issue [here](https://github.com/Azure/azure-functions-host/issues/new/choose).
