### ISSUE TITLE
SQL queries not being logged on Application Insights for Azure Cloud Services

### ISSUE THREAD

**Issue by meghavi87** [microsoft/ApplicationInsights-dotnet#2826]
I have application Insights Agent installed on web role and worker role instances in Azure Cloud Service. The Dependency telemetry logs the full SQL query text for web roles but not for worker roles.

For web roles, the sdk version logged is rddp:2.9.1-26132
For worker roles, the sdk version logged is rddf:2.9.1-26132

The application insights agent is installed for both web roles and worker roles by adding a startup tag to call the install agent PowerShell script. 

The environment variables for profiling on the worker roles are as follows:
COR_ENABLE_PROFILING=1
COR_PROFILER={324F817A-7420-4E6D-B3C1-143FBED6D855}
MicrosoftInstrumentationEngine_Host={CA487940-57D2-10BF-11B2-A3AD5A13CBC0}

Actual Behavior
Everything is logged correctly on Application Insights (Requests, Traces, Dependencies), but I don't see SQL Queries on SQL Server dependencies for Worker roles. Web roles have the SQL Queries logged.

Expected Behavior
SQL Queries should be displayed for Worker roles.

Version Info
SDK Version : rddf:2.9.1-26132
.NET Version : 4.8
Hosting Info: Azure Cloud Services. Web role and Worker Role

**Comment by cijothomas** [comment]
Worker roles are not supported, unfortunately. Only IIS based apps are supported.
https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query

**Comment by meghavi87** [comment]
I found this repo https://github.com/MohanGsk/ApplicationInsights-Home/tree/master/Samples/AzureEmailService
I have a similar code which does not log the SQl queries

**Comment by cijothomas** [comment]
Check my comment above. This is unsupported

**Comment by meghavi87** [comment]
Thanks! Could you please point to the exact section in the document which mentions worker role is not supported. I only see mention of Azure Cloud Service being supported.
