### ISSUE TITLE
ExcludedTypes example?

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet#286]
I was looking for an example on how to use ExcludedTypes property on AdaptiveSamplingTelemetryProcessor available from 2.2 Beta1 and couldn't find any. Can you share an example and even better, update the release entry for https://github.com/Microsoft/ApplicationInsights-dotnet/releases/tag/v2.2.0-beta1 with an example on how to use ExcludedTypes property. Thanks!

**Comment by abaranch** [comment]
I updated release notes and added xml documentation to excludedTypes.
