### ISSUE TITLE
Live metrics doesn't show logger traces when a custom log level is set

### ISSUE THREAD

**Issue by andriusiSun** [microsoft/ApplicationInsights-dotnet#2868]
* Packages:
    * Microsoft.ApplicationInsights.AspNetCore 2.22.0
* Runtime version: net8.0
* Hosting environment: Azure App Service

### Describe the bug

I have a very basic ASP.NET Core application:

```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddApplicationInsightsTelemetry();

var app = builder.Build();

app.MapGet("/test", (ILogger<Program> logger) =>
{
    logger.LogInformation("information");
    logger.LogWarning("warning");
    logger.LogError("error");
    logger.LogCritical("critical");

    return Results.Conflict();
});

app.Run();
```

Everything works well: Warning, Error, and Critical traces are being printed into Live metrics.
I can also see those traces in Monitoring Logs.

However when I add this to my `appsettings.json`:

```
{
  "Logging": {
     "ApplicationInsights": {
       "LogLevel": {
         "Default": "Information"
      }
    }
  }
}
```

or this

```
builder.Logging.AddFilter<ApplicationInsightsLoggerProvider>(string.Empty, LogLevel.Information);
```

I stopped seeing logs being printed into Live Metrics.

Note: Monitoring Logs still works well: I can find Information, Warning, Error, and Critical traces.

**Comment by cijothomas** [comment]
https://learn.microsoft.com/en-us/azure/azure-monitor/app/live-stream?tabs=dotnet6#sample-telemetry-custom-live-diagnostic-events 
LiveMetrics don't show all Logs by default, so you need to change the filter to show up all Logs, including Information level
