### ISSUE TITLE
TelemetryConfigurationFactory.GetManagedType eats exceptions, making it hard to track down issues when module cannot be instantiated.

### ISSUE THREAD

**Issue by belav** [microsoft/ApplicationInsights-dotnet#2884]
### Describe the bug

We have a fairly large complex net48 web application. Using OwinStartup it sets up a custom event for `AppDomain.CurrentDomain.AssemblyResolve` to make most binding redirects unnecessary. They are only required in a few situations.

When implementing ApplicationInsights, we were not getting any telemetry from our web application.

Comparing it to a new net48 web application, I eventually figured out that `Microsoft.ApplicationInsights.Web.AspNetDiagnosticTelemetryModule,` was not being included.

After more debugging, I figured out that this method in `TelemetryConfigurationFactory` was eating an assembly load exception.

```c#
        private static Type GetManagedType(string typeName)
        {
            try
            {
                return Type.GetType(typeName);
            }
            catch (IOException)
            {
                return null;
            }
        }
```

Or in other words, `TelemetryConfigurationFactory` was not creating and initializing an instance of `AspNetDiagnosticTelemetryModule` because while trying to find the `Type`, an `IOException` was thrown.

I had to add a call to `Type.GetType("Microsoft.ApplicationInsights.Web.AspNetDiagnosticTelemetryModule, Microsoft.AI.Web")` to our startup to track down the missing binding redirects.

### To Reproduce

I spent a bit of time trying to create a reproduction repo, but was unsucessful. The other catches in this file all log the problems that occur, it seems like at the very least this exception should also be logged in the same manner.

**Comment by cijothomas** [comment]
Thanks!

Internal logs are still emitted : https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/TelemetryConfigurationFactory.cs#L374

The current reflection based loading of modules in no longer done for modern app like asp.net core, .net core. (also in the case of OpenTelemetry based solutions). Closing as there is no plan to make any changes here.
