### ISSUE TITLE
Redis Telemetry not appearing on Application Insights

### ISSUE THREAD

**Issue by adeelakhan** [microsoft/ApplicationInsights-dotnet#2889]
* List of [NuGet packages](https://github.com/microsoft/ApplicationInsights-dotnet#nuget-packages) and version that you are using:
Application Insights Kubernetes Version: 7.0.0
Application Insights SDK Version: 2.22.0

* Runtime version (e.g. net461, net48, netcoreapp2.1, netcoreapp3.1, etc. You can find this information from the `*.csproj` file):
net8

* Hosting environment (e.g. Azure Web App, App Service on Linux, Windows, Ubuntu, etc.):
AKS

### Describe the bug
When reviewing the application map for a dotnet application hosted on AKS we noticed no telemetry to redis endpoints/dependency. Case #2407250010001728 was raised with Microsoft and MS engineer advised to raise a case directly with engineering as they don't support this package.

### To Reproduce

Go to Application Insights for the specific AKS cluster.
Click on Application Map.
Redis Dependency does not appear on the map although the highest amount of traffic is sent/received from that endpoint.

Expected behavior

Screenshots
![image](https://github.com/user-attachments/assets/ec790890-21e1-462a-a366-e5c4eb0c8047)
![image](https://github.com/user-attachments/assets/4621f8fd-ba98-405f-ae50-35e6ffc96ab8)

![image](https://github.com/user-attachments/assets/59b8441f-a141-4e2b-8f38-1bd9af3674d9)

Additional context

AKS support group have asked to raise an issue with App Insights directly, refer https://github.com/microsoft/ApplicationInsights-Kubernetes/issues/368

Microsoft support email pasted below,
Hi Adeel,

Thanks for your time, I really appreciate your cooperation.
We have discussed the symptom on the meeting and provided a suggestion, please kindly refer to following meeting minutes for your reference:

Symptom
Application Map not showing all endpoints such as [lwccachesydney.redis.cache.windows.net](https://urldefense.com/v3/__http:/lwccachesydney.redis.cache.windows.net__;!!MfzFaTml5A!iR7kHzZ7Zwx_vJebxJ-aVkgnzDsD7iioMvbCw37EY-AZncmHUEDNfDEz4UWHopPHT61NpILpmn0-EoGYzW7XIXBOKg$)

Analysis
Application Map will visualize two telemetry type requests and dependency.
We have queried Redis log over the past 7 days, there is no record being captured which is why the Redis didn’t appear in the Application Map.

By checking the telemetry further, we found that SDK version is ai-K8S[7.0.0.0](https://urldefense.com/v3/__http:/7.0.0.0__;!!MfzFaTml5A!iR7kHzZ7Zwx_vJebxJ-aVkgnzDsD7iioMvbCw37EY-AZncmHUEDNfDEz4UWHopPHT61NpILpmn0-EoGYzW4bp5m53g$) and all those telemetries were captured by ai-k8s:x.x.x.x

As per your developer team’s confirmation, they added package in the source code.
I have double checked this version with our K8S team and engineering team, Unfortunately, I was told that this specific SDK is beyond CSS knowledge and scope, it is supported by our engineering team directly.

Suggestion
To address this issue further, please kindly ask your developer team to raise this question on GitHub.
[GitHub - microsoft/ApplicationInsights-Kubernetes: Enrich the telemetry data for .NET applications running inside containers that are managed by Kubernetes.](https://urldefense.com/v3/__https:/github.com/microsoft/ApplicationInsights-Kubernetes__;!!MfzFaTml5A!iR7kHzZ7Zwx_vJebxJ-aVkgnzDsD7iioMvbCw37EY-AZncmHUEDNfDEz4UWHopPHT61NpILpmn0-EoGYzW6cXWLDWQ$)

Hope this makes sense for you and kindly let me know if you have further questions.

Regards,
Jason

**Comment by xiaomi7732** [comment]
@OsvaldoRosado Can you take a look at this? Do I understand correct that the problem is that there's no baked in telemetry module for Redis?

**Comment by cijothomas** [comment]
You are right. There is no automatic collection of Redis calls, so it must be manually collected. https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#automatically-tracked-dependencies

No plan to add the new feature in this repo as well, given this is already supported in OpenTelemetry by using https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.StackExchangeRedis along with OTel based AzureMonitor distro : https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=aspnetcore

Hope the new OTel based approach is good enough to meet the needs.
