### ISSUE TITLE
Truncated SQL commands

### ISSUE THREAD

**Issue by rfreire** [Microsoft/ApplicationInsights-dotnet#290]
SQL commands get truncated for SQL dependencies at 1024 characters. There should be some way to customize the max length to avoid this issue.

**Comment by rfreire** [comment]
Sorry, but why is this just an 'enhancement'?
Currently what I get from AI is:
SELECT [column_list] .... {truncated}

To be honest, this is completely useless for me... just like not having the command at all. It seems to be an important issue as the full sql command is required to figure it out what's going on.
Besides, I'm using EF (code first) which generates large sql commands that I don't (and don't want to) have control on.

Thanks!

**Comment by dnduffy** [comment]
The current schema has 1024 bytes for storing that field.
There is a schema update coming which will increase it to 8192.
If you can't wait for the schema update to be deployed you can store your queries in a custom property which can currently handle 8K.

**Comment by rfreire** [comment]
Great!
Can I ask you for an approx. time frame for the schema update?
I'd like to have an idea to plan accordingly.

Thanks!

**Comment by abaranch** [comment]
It should be out with the next beta for which we do not have strict timelines right now. I would expect it to be end of September, begging of October.

**Comment by cijothomas** [comment]
Closing this as the schema is already updated.
