### ISSUE TITLE
Database and Collection names are not displayed correctly for CosmosDB SDK 3.43

### ISSUE THREAD

**Issue by piotr-rojek** [microsoft/ApplicationInsights-dotnet#2903]
* Microsoft.Azure.Cosmos 3.43.1
* Microsoft.ApplicationInsights 2.22.0
* NET 8
* Azure Web App

### Describe the bug

After changes to Azure/azure-cosmos-dotnet-v3 OpenTelemetryAttributeKeys.cs done in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4622, the code in microsoft/ApplicationInsights-dotnet AzureSdkDiagnosticsEventHandler.cs cannot find database and collection names anymore. 

![image](https://github.com/user-attachments/assets/2f32e2b0-5557-4bd3-ba49-2f457f9cd319)

### To Reproduce

* Create .net console app from a template; 
* enable application insights; 
* enable cosmosdb + CosmosClientOptions.DisableDistributedTracing = false

We will close this issue if:

* AzureSdkDiagnosticsEventHandler.SetCosmosDbProperties() supports both the old and the new (OTEL compatible) property names

**Comment by reyang** [comment]
@lmolkova FYI.

**Comment by reyang** [comment]
@rajkumar-rangaraj could you follow up with Azure SDK team to see if any test / process improvements should be made?

**Comment by piotr-rojek** [comment]
Fixed in CosmosDB SDK 3.44.1/3.45

**Comment by askmorken** [comment]
This issue looks to be reintroduced in 3.46.x and 3.47.0
