### ISSUE TITLE
The default behavior of only sending >= `LogLevel.Warning` ILogger messages is non-obvious and not easily configurable

### ISSUE THREAD

**Issue by DrEsteban** [microsoft/ApplicationInsights-dotnet#2905]
## **Is your feature request related to a problem?**
By default, when `services.AddApplicationInsightsTelemetry()` is used, only ILogger messages logged with Warning or higher are sent to AI's "traces" table. This behavior isn't well documented, is unnecessarily hard to override, and is [**hard coded**](https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs#L427) into the SDK. (Not configurable via appsettings in any way.)

Users can only see that it exists or change the behavior by inspecting the `LoggerFilterOptions` with a `Configure()`/`PostConfigure()`:
![Image](https://github.com/user-attachments/assets/ccf4a7a3-fb0e-42ab-a41b-ef3cc01beee8)

## **Describe the solution you'd like.**
Rather than being [**hard coded**](https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs#L427) into the SDK, this setting should be configurable in an obvious & documented way.

Solutions like:
**In-code:**
```csharp
services.AddApplicationInsightsTelemetry(o =>
{
    o.MinimumLogLevel = LogLevel.Information;
});
```

**appsettings.json**
```json
{
  "logging": {
    "applicationInsights": {
      "logLevel": "Information"
    }
  }
}
```

## **Describe alternatives you've considered.**
I'm currently solving it in a very dirty way by adding a `PostConfigure<LoggerFilterOptions>()`:
```csharp
builder.Logging.Services.PostConfigure<LoggerFilterOptions>(x =>
{
    // Is this necessary? Or will the override below take precedence?
    // Doing it anyway to be safe.
    var existingRule = x.Rules.First(r => r.ProviderName?.EndsWith(".ApplicationInsightsLoggerProvider") ?? false);
    x.Rules.Remove(existingRule);

    // Override
    x.AddFilter<ApplicationInsightsLoggerProvider>(level => level >= LogLevel.Information);
});
```

## **Additional context.**
#2471 touched on this issue.

I also found this StackOverflow: https://stackoverflow.com/questions/77754230/azure-application-insight-logs-only-warning-and-higher

**Comment by cijothomas** [comment]
https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#how-do-i-customize-ilogger-logs-collection

Check if this doc is helpful.

**Comment by DrEsteban** [comment]
Doh... 🤦🏻 Thank you for that @chapterjason!

What was confusing me was the default Warning filter was still in the list:
![Image](https://github.com/user-attachments/assets/453faea3-cff8-42c4-9d09-d099b87b2766)

...but what I apparently missed was the existence of a new filter that gets added if you specify that in the appsettings 😞 Which appears to take precedence!

Disregard :)
