### ISSUE TITLE
Do not throw when channel not set

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#295]
When channel is not set any `TrackFoo` operation throws unhandled exception.

Exception thrown here:
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/1ccd5b466451db1884b242b6a58b3e9401a1fbcf/src/Core/Managed/Shared/Extensibility/Implementation/TransmissionProcessor.cs#L43

Exception is unhandled:
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/e0c93977e9aa05616ecc22c5b11ef39f8cb4587f/src/Core/Managed/Shared/TelemetryClient.cs#L310

Need to:
1. Set channel to default.
2. Make sure `TrackFoo` doesn't throw non-system (like OutOfMemory) exceptions.

**Comment by abaranch** [comment]
Why are you sayin it is not initialized by default? https://github.com/Microsoft/ApplicationInsights-dotnet/blob/0110215df15bca47aa7fc7ee92c46f30d909dead/src/Core/Managed/Net40/Extensibility/Implementation/TelemetryConfigurationFactory.cs#L76

**Comment by SergeyKanzhelev** [comment]
How then you can end up with the exception like customer reported?

**Comment by abaranch** [comment]
They may have created TelemetryConfiguration using constructor instead of CreateDefault. You do not want to put initialization logic in there. Do you have more info on that?

**Comment by abaranch** [comment]
@SergeyKanzhelev Do you agree that we should close the issue or do you propose to initialize channel if TelemetryConfiguration is created using constructor (and not CreateDefault)?

**Comment by SergeyKanzhelev** [comment]
Alternatively we can make it on "Track"
