### ISSUE TITLE
Add interface to implementations of ITelemetry that support Metrics property

### ISSUE THREAD

**Issue by TheXenocide** [Microsoft/ApplicationInsights-dotnet#307]
I'm writing an initializer that records custom metrics and I'm having to check many different possible implementation types to access their individual `IDictionary<string, double> Metrics { get; }` property signatures. It would be nice if I could just check `if (telemetry is ISupportMetrics)` or something similar.

**Comment by SergeyKanzhelev** [comment]
Sure, thanks for the feedback. 

cc: @vitalyf007 FYI
