### ISSUE TITLE
Stop AI tracing

### ISSUE THREAD

**Issue by tom-r-o** [microsoft/ApplicationInsights-dotnet#310]
I noticed that in TelemetryDebugWriter there's code that writes to VS's output window (line #56). Is there an option to disable it? 
It interferes with my ability to debug my application...

**Comment by SergeyKanzhelev** [comment]
Use this: 

``` csharp
TelemetryDebugWriter.IsTracingDisabled = true;
```

**Comment by Leonardo-Ferreira** [comment]
@SergeyKanzhelev this does more than stop writing on the debug output window! it stops insights recording at all! my "Data From last Debug Session" now is completely empty...

**Comment by SergeyKanzhelev** [comment]
Visual Studio relies on debug output data to show the session's data. We have plans to switch to ETW instead. @gardnerjr can share more details

**Comment by gardnerjr** [comment]
Yes, the VS tools get this information by watching the debug output.

@Leonardo-Ferreira  we've discussed at various point adding a right click option in the output window for "show application insight output" that would hide/show the output, without having to disable output from the sdk itself.

**Comment by dasjestyr** [comment]
"we've discussed at various point adding a right click option in the output window for "show application insight output" that would hide/show the output, without having to disable output from the sdk itself."

This seems to be the most appropriate solution imo. One almost _expects_ to find it there.

**Comment by alexvy86** [comment]
Is there an issue to track adding that option, or moving away from using the Debug window? I'm also very eager to get rid of those messages and I'd like to follow the discussion.

**Comment by SergeyKanzhelev** [comment]
@gardnerjr any updates on this?

**Comment by SergeyKanzhelev** [comment]
temporary re-opening the issue to follow up on the plans

**Comment by gardnerjr** [comment]
It's been discussed but never prioritized.

I've added `User Story 1049894: Add functionality to hide AI output in the debug output window` to our backlog, but I can't make any promises on if it will get scheduled in 15.4.  The next VS update is a servicing release and is very tightly scoped.

**Comment by erictor** [comment]
Thank you for adding User Story 1049894.   I'm willing to wait until it can be scheduled.   It's helpful to know that it is on the backlog.

**Comment by user1568891** [comment]
Is there an update to the filter? Since the telemetry appears in the Application Insights search most don't have a need for it to still be in the debug, and it really makes any other debug output really hard to read.

**Comment by RyanTaite** [comment]
Any update on this? Would really like an option setting somewhere to not have to scroll through hundreds of lines of AI Telemetry to see my one line of debug output.

**Comment by SergeyKanzhelev** [comment]
@gardnerjr do you know if this work was scheduled yet?

**Comment by gardnerjr** [comment]
No work has been scheduled for it.  If you haven't already, you might want to submit an item directly from the VS feedback tool as well, especially if this is an asp.net related thing.  Some other teams outside of AI are starting to take over work in our VS extension to make their experiences better.  This would be one place we could maybe get another team to help out.

**Comment by RyanTaite** [comment]
Will do.

Looks like there is one thread active on it right now: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/19370182-add-filter-for-application-insights-debug-events-i

Though it was posted in late May of 2017, so hopefully it gains more traction/notice.

**Comment by Hassmann** [comment]
Please. It really has become more than a nuisance that the same service we happily use to understand our code runs denial-of-service against another major source of "application insight". 
A jealous and ruthless mistress, although otherwise quite sexy. Please silence her.

**Comment by SergeyKanzhelev** [comment]
Nope, it is not documented, but it is used. For instance for integration with Application Insights profiler. This provider: `Microsoft-ApplicationInsights-Data` exposes events in the form very close to debug output JSON. I believe intelliTrace is using ETW and my assumption was that they have solved all problems you mentioned.

However, you know Visual Studio and all scenarios better than me. So if the feature of hiding strings from Output window is more viable - I'm all for it!

Thank you for looking into it again.

**Comment by EnCey** [comment]
Any updates? Is there a workaround, like a way to filter the debug window contents or something ..?

**Comment by hallidev** [comment]
Since @EnCey asked in 2018, I might as well ask again - is there any way to shut off this ridiculous output spamming my developers and I constantly?

Is this something we're going to be asking about in 2030? Humanity got to the moon faster. How is this not a change that requires a grand total of 5 lines of code?

Is there a workaround for this? More than 90% of the output from my entire (large) codebase is Application Insights spam. And no, we don't want to disable AppInsights entirely for local development, we just want the output window spam to *stop*.

**Comment by cijothomas** [comment]
@hallidev No work is done to fix this in SDK or Visual Studio tooling. Please upvote the issue here, to help SDK team increase its priority.

You may want to submit additional feedback to Visual Studio using its feedback link, to get it prioritized by Visual Studio team.
![image](https://user-images.githubusercontent.com/5232798/101530577-f6709780-3946-11eb-912e-546725d9c4c4.png)

**Comment by hallidev** [comment]
Thanks - I've suggested the feature. Worth noting is that there was a previous request that was closed. Hope this one makes it.

**Comment by Muhomorik** [comment]
@hallidev , can you share the link?

**Comment by hallidev** [comment]
@Muhomorik Sure - https://developercommunity2.visualstudio.com/t/Implement-a-way-to-suppress-Application-/1281265?port=1025&fsid=ea327805-24a9-47aa-a5ed-7c7d8f636a7f&entry=myactivity

**Comment by user1568891** [comment]
Bump?
