### ISSUE TITLE
Exception using trying to use Persistent Channels with Serilog

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/ApplicationInsights-dotnet#311]
Hi,

On configuring persistent channels like
```
// Set the App Insights Global Key
Microsoft.ApplicationInsights.Extensibility.
                    TelemetryConfiguration.Active.InstrumentationKey = appInsightsKey;

var configuration = new TelemetryConfiguration()
{
         InstrumentationKey = appInsightsKey,
         TelemetryChannel = new PersistenceChannel()
};
```

I get the following exception

`Attempt by method 'Microsoft.ApplicationInsights.Channel.PersistenceChannel..ctor(System.String, Int32)' to access method 'Microsoft.ApplicationInsights.Channel.TelemetryBuffer..ctor()' failed.`

This is in a Web API 2 project using OWIN, any ideas what could be wrong ?

**Comment by johnkattenhorn** [comment]
I've also tried this

```
            TelemetryConfiguration.Active.InstrumentationKey = appInsightsKey;
            TelemetryConfiguration.Active.TelemetryChannel = new PersistenceChannel();
```

But I get the same error.

**Comment by SergeyKanzhelev** [comment]
You need to use [Server telemetry channel](http://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel) with the OWIN application. It includes persistence and optimized for server scenarios. `PersistenceChannel` is used for devices monitoring and will not be efficient for the high volume applications monitoring
