### ISSUE TITLE
Allow to send IPv6

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#316]
@OsvaldoRosado with your latest improvements [this](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/1ccd5b466451db1884b242b6a58b3e9401a1fbcf/src/Core/Managed/Shared/Extensibility/Implementation/LocationContext.cs#L36) check is no longer needed.

Also please update schema: [here](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/37cec526194b833f7cd676f25eafd985dd88d3fa/Schema/PublicSchema/ContextTagKeys.bond#L50) and [here](https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/ContextTagKeys.bond#L36). Note files in both locations are auto-generated

**Comment by abaranch** [comment]
SDK was updated. Schema descriptions was not.

**Comment by SergeyKanzhelev** [comment]
https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/ContextTagKeys.bond#L36
