### ISSUE TITLE
EventSource Id's should be unique between AI SDK's

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-dotnet#322]
In order to more easily debug event source messages it might be helpful to have each SDK library event source use a different range of Id's (e.g. Core = 1-99, Channels = 100-199, Web = 200-299, etc.)

**Comment by abaranch** [comment]
Please consider using Keywords for filtering rather id ranges. That would be more memory efficient because EventSource internally allocates memory for all elements even if you skip a large range.

**Comment by SergeyKanzhelev** [comment]
Closing as we should be able to distinguish events by provider name and/or Keywords if needed

**Comment by dnduffy** [comment]
We can do it by provider name, it's just annoyingly long in a UI when they all start with the same namespace string.
