### ISSUE TITLE
Move to netstandard1.4 instead of dotnet5.4

### ISSUE THREAD

**Issue by DamianEdwards** [Microsoft/ApplicationInsights-dotnet#335]
The `dotnet54` TFM is effectively deprecated. The package should instead be targeting the requisite .NET Standard version (`netstandard1.4`). Currently, applications targeting .NET Core (like ASP.NET Core apps on .NET Core) are required to specify imports in order to use Application Insights which isn't the desired experience.

**Comment by dnduffy** [comment]
Moved to https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/277

**Comment by dnduffy** [comment]
My apologies, I thought you were referring to the imports in the .NET Core SDK.

**Comment by zeroskyx** [comment]
Any news on the topic?

**Comment by dnduffy** [comment]
Just merged: https://github.com/Microsoft/ApplicationInsights-dotnet/pull/365
