### ISSUE TITLE
Convert PCL project to .NET Core

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#336]
[This project](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Core/Managed/PCL/Core.PCL.csproj) is only used for .NET Core target framework. Need to convert it to the Core project.

While doing it include [this API](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Core/Managed/Operation.AL.Shared/Operation.AL.Shared.projitems) to the project

**Comment by SergeyKanzhelev** [comment]
Also ensure that this list of references is up to date: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/d3d4e3cef6e29d430f7865d6807132feb8676aac/src/Core/NuGet/Core/Package.nuspec#L32-L50

**Comment by SergeyKanzhelev** [comment]
This is copy from https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/238

**Comment by dnduffy** [comment]
Are you sure we should convert it rather than add .NET Core in addition to PCL?

**Comment by SergeyKanzhelev** [comment]
We do not use PCL. Why keep maintaining it?

**Comment by dnduffy** [comment]
In case we need to bring back older device support again?

**Comment by SergeyKanzhelev** [comment]
We will bring it back if needed. No need to drag the weight, especially when Hockey App will have feature parity and will be well optimized for devices experiences.

**Comment by iusafaro** [comment]
It would be nice to move GetMachineName() implementation to .NET Core - now it's empty in PlatformImplementation for PCL.

**Comment by SergeyKanzhelev** [comment]
Completed by @pharring

**Comment by SergeyKanzhelev** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet/pull/451
