### ISSUE TITLE
Support loading Instrumentation Key from Environment Variable

### ISSUE THREAD

**Issue by christopheranderson** [Microsoft/ApplicationInsights-dotnet#337]
Just as the NodeJS sdk does, it would be nice if we could load the Instrumentation Key from an environment variable without having to do so explicitly in our code. Ideally, they'd use the same key - `APPINSIGHTS_INSTRUMENTATIONKEY`

Currently have to do this:

```csharp
private static string key = TelemetryConfiguration.Active.InstrumentationKey = System.Environment.GetEnvironmentVariable("APPINSIGHTS_INSTRUMENTATIONKEY", EnvironmentVariableTarget.Process);
```

**Comment by SergeyKanzhelev** [comment]
beta3 will have it: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/d3d4e3cef6e29d430f7865d6807132feb8676aac/CHANGELOG.md#L7
