### ISSUE TITLE
Consider replacing server telemetry channel storage implementation

### ISSUE THREAD

**Issue by dnduffy** [microsoft/ApplicationInsights-dotnet#338]
If we continue to see high load perf issues, after the last round of fixes, then I think we should consider replacing the current implementation for server telemetry channel storage, that uses separate files for each transmission, with a mutex guarded single "log" file implementation (along the lines of journaling file systems and light weight recoverable virtual memory).  Instead of concurrent multi-threaded access to a potentially large number of individual files we could investigate the perf of a single buffered file that holds multiple transmissions up to a configurable size limit.  Or perhaps a hybrid approach that still has multiple files but where each file contains multiple transmissions and the files are size aligned to a secondary buffer size to keep the implementation simple and yet still cut down on the amount of individual disk accesses also.

**Comment by rajkumar-rangaraj** [comment]
Closing old issue
