### ISSUE TITLE
APPINSIGHTS_INSTRUMENTATIONKEY env var logic doesn't work for QuickPulse

### ISSUE THREAD

**Issue by iusafaro** [Microsoft/ApplicationInsights-dotnet#340]
QuickPulse doesn't honor ikey set on the telemetry item level, it does look only to the global ikey set at configuration.

**Comment by SergeyKanzhelev** [comment]
@tokaplan why QP doesn't read ikey from the items? This is a valid scenario when customer sets the ikey in telemetry initializer.

**Comment by SergeyKanzhelev** [comment]
I recommend to set it on configuration level [here](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/37cec526194b833f7cd676f25eafd985dd88d3fa/src/Core/Managed/Net40/Extensibility/Implementation/TelemetryConfigurationFactory.cs#L64). And keep the existing logic as well

**Comment by SergeyKanzhelev** [comment]
Also please create a separate bug in https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues so Quick Pulse will work correctly when customer sets the key per telemetry client or per telemetry item

**Comment by tokaplan** [comment]
Submitted PR #346, please review

**Comment by tokaplan** [comment]
PR merged.

**Comment by SergeyKanzhelev** [comment]
Can you pls create a separate bug in  https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues so Quick Pulse will work correctly when customer sets the key per telemetry client or per telemetry item. Then we can close this issue

**Comment by tokaplan** [comment]
Issue #199.
