### ISSUE TITLE
NullReferenceException in DiagnosticsEventListener.OnEventWritten

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#341]
@gardnerjr and @ericc1103 reported `NullReferenceException` in the following stack:

```
at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsEventListener.OnEventWritten(EventWrittenEventArgs eventSourceEvent)
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
```

**Comment by gardnerjr** [comment]
@SergeyKanzhelev is there any way for us to disable this at all?

Some way to get a call into `telemetryconfigurationfactory.initialize` with an empty list of modules so that diagnostics module doesn’t get added at all?

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/37cec526194b833f7cd676f25eafd985dd88d3fa/src/Core/Managed/Net40/Extensibility/Implementation/TelemetryConfigurationFactory.cs

**Comment by SergeyKanzhelev** [comment]
How do you create telemetry configuration today? I'd recommend to instantiate it directly like this "var t = new TelemetryConfiguration();" and never use `TelemetryConfiguration.Active`. This way you are in full control on which modules will be added

**Comment by gardnerjr** [comment]
it doesn't look like we reference TelemetryConfiguration anywhere directly, it looks like we literally just do: 

    var client = new ApplicationInsights.TelemetryClient();
    client.Context.InstrumentationKey = theIkey;

and then go on our way and set other properties and call methods on that client?

**Comment by dnduffy** [comment]
You will get the default configuration then (.Active as Sergey pointed out).

**Comment by SergeyKanzhelev** [comment]
What's the implementation of `ApplicationInsights.TelemetryClient`?

**Comment by gardnerjr** [comment]
`ApplicationInsights.TelemetryClient` is the SDK `TelemetryClient`.  We *also* have a class `TelemetryClient` which is our wrapper around the AI TelemetryClient to isolate it from other code to allow it to be delay loaded, queued, etc.  (we're required to push loading of the real AI assemblies later during startup and queue up telemetry until we're "allowed" to load and send telemetry later.

so hypothetically, if we just add a `var t = new TelemetryConfiguration();` to our startup code we can control this?

**Comment by SergeyKanzhelev** [comment]
You need to use this configuration when construct client as well:

``` csharp
var t = new TelemetryConfiguration();
var client = new TelemetryClient(t);
```

**Comment by gardnerjr** [comment]
that gives me : "Telemetry channel should be configured for telemetry configuration before tracking telemetry." so there must be a *little* more configuration to do if i do that above?

**Comment by gardnerjr** [comment]
var t = new ApplicationInsights.Extensibility.TelemetryConfiguration
            {
                InstrumentationKey = ourIkey; 
                TelemetryChannel = new ApplicationInsights.Channel.InMemoryChannel(),
            };

looks like explicitly setting the channel was all i needed (though i'm now setting ikey there too.)

**Comment by SergeyKanzhelev** [comment]
I'm glad you figured this out.

**Comment by SergeyKanzhelev** [comment]
For the main thread: I'm not closing bug as we still need to understand what may cause a `NullReferenceException` in this code.

**Comment by cijothomas** [comment]
Not clear what caused this, but added a safety check to prevent nullreference.

**Comment by cijothomas** [comment]
Fixed via
https://github.com/Microsoft/ApplicationInsights-dotnet/pull/410
