### ISSUE TITLE
Inconsistent data between RequestTelemetry and Request ETW event

### ISSUE THREAD

**Issue by northtyphoon** [Microsoft/ApplicationInsights-dotnet#343]
The Success property of RequestTelemetry is updated in [sanitizing](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Core/Managed/Shared/DataContracts/RequestTelemetry.cs#L205) which is after Request ETW event is generated.  The sanitizing also updates other properties like name, url. 

The sanitizing process causes the data is different between RequestTelemetry and Request ETW event.

**Comment by SergeyKanzhelev** [comment]
@dnduffy , the plan to get rid of sanitize method seems not to be working. It is a good idea to sanitize before event source as well. So maybe generate both - Sanitize and Serialize methods?

**Comment by SergeyKanzhelev** [comment]
@northtyphoon , can you please add a call to `Sanitize` before the RichEventSource? I think this is reasonable.

BTW, do you know how big of events ETW supports? Do we need more aggressive sanitization in the case of ETW reporting?

**Comment by northtyphoon** [comment]
@SergeyKanzhelev OK. I will send PR. 

The limit of ETW event is 64K including header. The event will be dropped if the size is greater than 64K. https://msdn.microsoft.com/en-us/library/windows/desktop/aa363668(v=vs.85).aspx. 

I think current sanitation cap will work for most cases.
