### ISSUE TITLE
Mention changes in CHANGELOG.md

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#366]
@vitalyf007 I forgot to ask in PR - please update the CHANGELOG in 2.3.0-beta1 branch: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/2.3.0-beta1/CHANGELOG.md

**Comment by vitalyf007** [comment]
Change log updated in 2.3.0 beta 1 branch.
