### ISSUE TITLE
Mark aggregated metrics with the dedicated sdkVersion

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#367]
@vitalyf007 - it will be nice to have an sdkVersion set to the special value on metrics aggregated using the new aggregators.

The only gotcha here is that for the modules using those aggregators we need to allow to set their own sdkVersion. Like exception statistics tracking module will have it's own sdkVersion.

**Comment by SergeyKanzhelev** [comment]
Here is how it done for web:

Helper class:
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/75373e57dcf8d646c54ee188461c373f2cc98939/Src/Web/Web.Net45/Implementation/SdkVersionUtils.cs

Use of it. In your case you can set it on telemetry item itself:
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/75373e57dcf8d646c54ee188461c373f2cc98939/Src/Web/Web.Shared.Net/ExceptionTrackingTelemetryModule.cs#L59

Fallback to the default (for reference):
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Core/Managed/Shared/TelemetryClient.cs#L419

**Comment by AlexBulankou** [comment]
Already done?
