### ISSUE TITLE
Obsolete Message is incorrect

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#368]
This 
```
"DependencyTelemetry.DependencyKind" is obsolete: "Use DependencyTypeName"
```
should be

```
"DependencyTelemetry.DependencyKind" is obsolete: "Use Type"
```

**Comment by SergeyKanzhelev** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/d22722286e203ffee0a2fada1219ae776e11c720/src/Core/Managed/Shared/DataContracts/DependencyTelemetry.cs#L210

**Comment by dnduffy** [comment]
Thanks

**Comment by dnduffy** [comment]
Fixed in the pull request: https://github.com/Microsoft/ApplicationInsights-dotnet/pull/377/files
