### ISSUE TITLE
Can't set properties or metrics properties in PageViewTelemetry class

### ISSUE THREAD

**Issue by ichpuchtli** [Microsoft/ApplicationInsights-dotnet#384]
If you want to track page views in .net you can't provide provide the properties or metrics property as it is a read only.

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Core/Managed/Shared/DataContracts/PageViewTelemetry.cs#L126

Expected:
I can set the properties and metrics properties in the page view telemetry class

Actual:
I can only specify page name, duration, sequence, timestamp and uri.

**Comment by SergeyKanzhelev** [comment]
You cannot set your collection as properties, but you can add properties one by one:

``` csharp
var t = PageViewTelemetry();
t.Properties.Add("a", "b")
```
