### ISSUE TITLE
Cannot install AI for .NET Core 1.0 webapp

### ISSUE THREAD

**Issue by jochenvw** [Microsoft/ApplicationInsights-dotnet#386]
When trying to add Application Insights to a File > New Project - .NET Core WebApp, I'm getting the following error:

<img width="798" alt="ai_install_error" src="https://cloud.githubusercontent.com/assets/17111555/20885213/df1e7e32-baef-11e6-959b-0d0ee346c392.png">

<img width="799" alt="project" src="https://cloud.githubusercontent.com/assets/17111555/20885215/e147f3e6-baef-11e6-837d-e6bef7cb4583.png">

**Comment by SergeyKanzhelev** [comment]
CC: @dnduffy, @AlexBulankou 

Here is the workaround: https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/279

Sorry for the inconvenience. We are working on releasing a compatible version.

**Comment by jochenvw** [comment]
OK - thanks!

**Comment by jochenvw** [comment]
Thanks - the workaround works on `project.json` though. I've converted to `project.csproj`. Looking forward to the fix!
