### ISSUE TITLE
[Metrics] Document the new metric aggregation API

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#388]
Write samples on how to use the new Metrics Aggregation API. I propose to cover the following contexts:

1. I’m using custom performance counters. How can I replace them with Application Insights metrics
  a. Raw, rate counters
  b. Percentage counters
2. I’m new and I want to start reporting a custom metric. What’s the easiest I can do to start reporting metrics
  a. Report the rate of something (processed queue items)
  b. Report the size of something (current number of items in the queue)
  c. Report how many retries service makes
  d. % of items we failed to process
3. I’m `MetricTelemetry` in older SDK. What are the recommendations on move to the new SDK.

For those scenarios - ideally it should be end-to-end experience of code example, alert settings and chart settings in Metrics Explorer to view data.

**Comment by SergeyKanzhelev** [comment]
cc: @macrogreg

**Comment by macrogreg** [comment]
We should document things once we are happy with the API, but this is not blocking to release 2.4-Beta1, is it?

**Comment by SergeyKanzhelev** [comment]
not relevant now
