### ISSUE TITLE
Local Storage not working for Server Channel

### ISSUE THREAD

**Issue by andymacourek** [microsoft/ApplicationInsights-dotnet#390]
Local storage does not seem to be working for failed sends

            var channel = new ServerTelemetryChannel();
            channel.EndpointAddress = @"https://www.endpointdoesnotexists.com";
            channel.StorageFolder = @"D:\FileTest";
            channel.Initialize(TelemetryConfiguration.Active);
            TelemetryConfiguration.Active.TelemetryChannel = channel;

I have used PerfView and I see errors like ThreadID="18,900" FormattedMessage="[msg=Log verbose];[msg=Peek failed while getting files from storage. Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Andy\AppData\Local\Microsoft\ApplicationInsights\vstelAIF-312cbd79-9dbb-4c48-a7da-3cc2a931cb70'. 

This is not even the instrumentation key I am using.

**Comment by dnduffy** [comment]
That looks like a Visual Studio log and not one of yours.

**Comment by andymacourek** [comment]
I used PerfView to see why the files were not getting written.  This is in the Event List under Microsoft-ApplicationInsights-Core/LogVerbose.  The error traces to Microsoft.ApplicationInsights.Channel.Storage.GetFiles

Also, I am using 2.1 from NuGet.

**Comment by eggapauli** [comment]
Were you able to solve this? I have the same problem.

**Comment by cijothomas** [comment]
Closing old issues. Please re-open if needed.
