### ISSUE TITLE
FW 4.0 of Persistence.Test compiles against FW 4.5

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#40]
See https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/Test/Persistence.Test/Persistence.Net40.Tests/PersistenceChannel.Net40.Tests.csproj#L10. Needs to be fixed to 4.0

**Comment by abaranch** [comment]
Closing since we plan to remove devices SDK
