### ISSUE TITLE
Is there a way to disable/enable/throttle telemetry types dynamically (while the app is live) 

### ISSUE THREAD

**Issue by eriksteinebach** [Microsoft/ApplicationInsights-dotnet#411]
We would like to be able to build a management page where we can enable and disable telemetry (by type) when we need to, so we are not always logging all information. Or better even would be if we could throttle the sampling way up or down based on need. We don't want to have to recycle the app to do this. 

As far as I can see, currently the only option is to change the configuration file? Which requires an app recycle to be loaded? Is there another way in code?

**Comment by SergeyKanzhelev** [comment]
Implement `ITelemetryProcessor`: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#filtering-itelemetryprocessor

This telemetry processor can receive configuration in real time and apply different logic depending on it. 

You can differentiate by telemetry type and call the standard SamplingTelemetryProcessor for every telemetry type.

Once implemented - consider sharing it with others on GitHub as this is quite interesting scenario.
