### ISSUE TITLE
ServerTelemetryChannel needs some re-architecting

### ISSUE THREAD

**Issue by dnduffy** [microsoft/ApplicationInsights-dotnet#417]
There are a couple problems with the server telemetry channel that need re-architecting/partial rewriting to solve.
1. The threading issue identified in #414 occurs at the buffer level and prevents any of the file caching code from being reached which breaks the "guarantee" of sending data.
2. The logic flow in the server telemetry channel is heavily based on events, multiple threads/tasks, and distributed handling of response codes across different files which makes the code horribly confusing to read, learn, understand, debug, and maintain.  A much simpler approach needs to be devised.

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/413 I had something similar already. Close either this one or the other.

**Comment by dnduffy** [comment]
#413 is a subset with specific details, let's keep both for now.
