### ISSUE TITLE
Add NetStandard 1.3 version of core SDK

### ISSUE THREAD

**Issue by pharring** [Microsoft/ApplicationInsights-dotnet#433]
We would like to use ```TelemetryClientExtensions.StartOperation``` from .NET Core apps (including within the ApplicationInsights-aspnetcore repo, for eaxmple).

Right now, when we reference Microsoft.ApplicationInsights from a .Net Core app, we pick up the "netstandard1.3" version which comes from the output of the Core.PCL project.

I tried adding a reference to the Operation.AL.Shared project to Core.PCL but it failed because it couldn't find ```AsyncLocal<T>```. Interestingly, ```AsyncLocal<T>``` _is_ available in netstandard1.3, but Core.PCL can't reference it because it targets .Net 4.5 (which corresponds to netstandard1.1)

I propose that we create a new "Core.NetStandard" project and add in the necessary pieces to support ```TelemetryClientExtensions``` (including the recent change I made to fire ETW events). It would target netstandard1.3 (equivalent of Net46) and the NuGet package would pull in netstandard1.3 binaries from the output of that project instead of Core.PCL

I'd be willing to do this, but it's a substantial change, so I'm seeking guidance before I embark (e.g. perhaps you already have this planned).

**Comment by dnduffy** [comment]
We would like to replace the PCL with .NET Core, the only catch is we need a build server that builds VS 2017 projects.  There has already been some discussion of this in email and I think here on GitHub also, the only blocker is someone having time to try it out.  If you have time that would be great, you can sync with @karolz-ms who is also working on this as well I believe.  I can help provide info on the MicroBuild environment we use.

**Comment by pharring** [comment]
Thanks. Is the move to 2017 planned or is it a case of "it'll happen when it happens"? Obviously we'd want to coordinate that sort of thing with everyone on the team and update build definitions. I'll sync up with @karolz-ms offline.

**Comment by pharring** [comment]
This has been resolved with #451 
It will be in SDK version 2.4
