### ISSUE TITLE
versions of Base and TelemetryChannel NuGets mismatched

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#462]
@pharring do you know why the versions of NuGets after upgrade to VS2017 could differ? Microsoft.ApplicationInsights.2.4.0-beta1-build**01645**.nupkg and Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.4.0-beta1-build**01646**.nupkg

**Comment by SergeyKanzhelev** [comment]
Maybe we can do something like this: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/dirs.proj#L6

**Comment by pharring** [comment]
I suspect it's because the AssemblyInfo files are generated in two passes (Restore and Build). Our algorithm for build numbers quantizes to the nearest 5 minutes, so it could happen that the build number ticks over during the build. This might go away once we move TelemetryChannel to be an SDK project and thus they both build in the same phase.

**Comment by pharring** [comment]
Though, you might be right that setting the version once in dirs.proj should work (that happens before we start the main build). Probably the Core project isn't picking that up.

**Comment by SergeyKanzhelev** [comment]
Do you think this will help https://github.com/Microsoft/ApplicationInsights-dotnet/pull/465 ?

**Comment by SergeyKanzhelev** [comment]
Hm, it seems that the version is cached somewhere. Third build in a row produces the same version of NuGet's... I'll look into it later, let me know if you have ideas

**Comment by SergeyKanzhelev** [comment]
Ok. I changed:

![image](https://cloud.githubusercontent.com/assets/9950081/23922333/28548f34-08bf-11e7-92d0-6b59b0e5c666.png)

Yes, I think when you started using different file for NuGet version definition - it all broke. Let me try how it will work with cleaning of sources and then I'll revert changes if it will not help to unblock myself

**Comment by pharring** [comment]
Nice fix. Thank you!

**Comment by SergeyKanzhelev** [comment]
And it worked =)
