### ISSUE TITLE
WCF Client Tracking Not Working

### ISSUE THREAD

**Issue by lukos** [Microsoft/ApplicationInsights-dotnet#473]
I have an MVC 5 app that is calling a WCF service using wsHttpBinding and a client certificate. The client was created with SvcUtil.exe and works fine although Application Insights does not see these calls as dependencies and does not log them.

The documentation talks about HTTP-based bindings but it is unclear specifically which bindings are being talked about here and what the alternatives are if the default SDK does not work correctly for the binding I am using.

I am going to manually include a TrackDependency call for every call to the service which is annoying but should work for now.

**Comment by tomasr** [comment]
@lukos: What .NET version are you running your app on? Also, you don't mention if you're running in AppService or on-premise and have the Status Monitor tool installed.

Normally, the HTTP-based dependency tracking should work in your case, I think though it provides limited information in some scenarios (like not being able to tell you what operation of the service was called).

We also have some experimental support for WCF dependency tracking independent of the built-in HTTP-based one in the [WCF SDK](https://github.com/Microsoft/ApplicationInsights-SDK-Labs/tree/master/WCF), which will also work with things like `NetTcpBinding`. You could try installing this package and enabling it (see the docs in the link mentioned) and we'd love any feedback on how it works for you.

**Comment by lukos** [comment]
Hi @tomasr The app and service are both running on 4.5.2. The app is running on App Services and the service running on a cloud service.

Is the package you are working on designed for the web service or for the web app? Thanks.

**Comment by tomasr** [comment]
@lukos It supports both scenarios:

- You can install it on your WCF service to provide telemetry on the service side
- You can install it on the client Web Application and enable the client-side dependency tracking to capture calls to the web service.

**Comment by lukos** [comment]
I'll give it a go. Thanks

**Comment by tomasr** [comment]
FYI, if you're running on App Service, then the WebApp should be using 4.6, so you should've seen at least something. Do you have the AppInsights Profiler enabled on the web app? You can do this from the Kudu Gallery, if I remember correctly.

**Comment by lukos** [comment]
I've seen a few things logged but it seems really inconsistent. I have manually added the tracking for now, which is very helpful trying to debug performance problems mentioned by a customer.
