### ISSUE TITLE
SDK stops sending telemetry and does not start again.

### ISSUE THREAD

**Issue by dnduffy** [Microsoft/ApplicationInsights-dotnet#480]
There is logic in the ServerTelemetryChannel to set the sender and buffer capacities to 0 in the event of a server error response (408 timeout, 500 internal error, and 503 service unavailable) and then a timer is supposed to re-enable sending after some back-off time period.
We have had at least one confirmed instance where sending does not get re-enabled and stays stuck at 0.  We speculate we have had a couple other instances as well but we don't have the logs to prove those.
Eventually the disk buffer fills and all telemetry after that is discarded but the overhead of the logic attempting to send and save the unsent data still exists.

**Comment by Dmitry-Matveev** [comment]
Let's investigate if it's a regression in 2.3 and whether we should take it as part of the stable release. We've got dump for the repro.

**Comment by iusafaro** [comment]
Investigation showed that it can happen if SDK received two different error responses (PartialSuccess and InternalServerError for instance) at the same time, then it goes to the situation with sender and buffer capacities equal to 0 and never came back. Let's see if there're any other cases leading to the same situation.
