### ISSUE TITLE
Client side Problem ID calculation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#493]
Problem ID should be calculated on SDK and the algorithm should be the same as for exceptions statistics

**Comment by j2jensen** [comment]
I'd also suggest that the algorithm should be composed in a way that makes it easy to use pieces of when customizing our own problem ID. For example, the logic of creating the problem ID text for a given StackFrame is something I'd like to be able to use, but I'd also like to do things like ensuring any methods with `[DebuggerHidden]` attributes are not considered when selecting the stack frame to produce the problem ID for.
