### ISSUE TITLE
CPU Metric normalization

### ISSUE THREAD

**Issue by iusafaro** [Microsoft/ApplicationInsights-dotnet#514]
A query like:

performanceCounters  | summarize avg(value) by name, category 

would return:
name	category	avg_value
% Processor Time	Process	(no change from today)
% Processor Time	Processor	(no change from today)
CPU Utilization by Process	ApplicationInsights	Calculated by the SDK as (Process/% Processor Time) / Number of Cores

**Comment by SergeyKanzhelev** [comment]
wrong repository. You need to move it to `-dotnet-server`
