### ISSUE TITLE
TelemetryClient.InstrumentationKey is not the same as configuration.InstrumentationKey

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet#525]
1. Create a new TelemetryClient:
```
    var client = new TelemetryClient(configuration);
```

2. Expected:
`client.InstrumentationKey` equals to `configuration.InstrumentationKey`

3. Actual: `client.InstrumentationKey` is empty string.

**Comment by SergeyKanzhelev** [comment]
dup for https://github.com/Microsoft/ApplicationInsights-dotnet/issues/348. See discussion there. Closing for now.
