### ISSUE TITLE
Pre-aggregated metric for "Exceptions thrown" is missing marker properties.

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-dotnet#531]
Hi @SergeyKanzhelev ,

This is in a build of 2.4-Beta1 from last Friday, so if something has changed, please let me know and ignore otherwise..

When I look at the pre-aggregated metrics for e.g. dependencies (similar for requests) I am seeing the following custom properties:

a1) _MS.AggregationIntervalMs:	60000
a2) _MS.IsAutocollected:			True
a3) Dependency.Success:		False
a4) Dependency.Type:			Azure table
a5) _MS.MetricId:				dependencies/duration

However, when I look at exceptions, I am seeing these prperties:

b1) _MS.AggregationIntervalMs:	60000
b2) problemId:					System.Data.SqlClient.SqlException at System.Data.SqlClient.SqlConnection.OnError:94
b3) operationName:			GET DateTimeQueries2

We need to add the properties (a2) and (a5) so that the DRAFT API can work with them correctly.
I think this is blocking for 2.4-beta1 since otherwise DRAFT will not be able to expose those metrics in a consistent manner.
What are your thoughts?

I have filed to track.

G))

**Comment by macrogreg** [comment]
Btw, based on the IDs I see under our reference [https://dev.applicationinsights.io/apiexplorer/metrics?appId=DEMO_APP&apiKey=DEMO_KEY&metricId=exceptions%2Fcount], the metric ID should probably be **exceptions/count**. However, please make sure that the semantic of your metric is indeed the same as what we already have under that ID (maybe you are counting not the same set of exceptions?). In case of doubt, please consult the DRAFT team before finalizing the metric ID.

Thanks.

**Comment by SergeyKanzhelev** [comment]
I changed it to enhancement as ideally we need to move the aggregation logic to the pre-aggregation telemetry processor. And then fully align with the rest of metrics calculation flow. For now the only purpose to use the same property is to let loaders know to not extract the metric from these exception examples. Would you please make sure it is supported! thanks

**Comment by SergeyKanzhelev** [comment]
CC: @kstevenham

**Comment by cijothomas** [comment]
closing as exception telemetry is now correctly pre-aggregated with all correct dimensions
