### ISSUE TITLE
Make request.duration and dependency.duration optional to avoid interpreting missing results as zeros.

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet#532]
Today both [request ](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/Schema/PublicSchema/RequestData.bond#L18) and [remote dependency ](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/Schema/PublicSchema/RemoteDependencyData.bond#L27) require duration field in schema. This forces implementation to report zero duration for cases when duration cannot be measured correctly.   
The consequence is that depending on how many such cases we have we, the data can be significantly skewed.    
Additional negative consequence is that with aggregated data, we cannot reliably differentiate between the very fast cases and cases where duration cannot be determined, making it harder to identify detection issues.

Proposal:

1. Make both optional in schema
2. Change API layer to allow optional fields in DependencyTelemetry and RequestTelemetry
3. Validate E2E

Once we agree on 1&2 we can open related changes on Node.JS, JS, Java

@Dmitry-Matveev @SergeyKanzhelev @cijothomas, others, thoughts?

**Comment by SergeyKanzhelev** [comment]
What will the `null` mean semantically? `Request` and `Dependency` represents the operation that has start and duration. One should be able to rely on the fact that there is a duration, not write the conditional statements whenever need to calculate the average execution time.

So I'd say that the data collection should be fixed. In some (many) cases `0` may be legitimate duration.

Please reopen if disagree
