### ISSUE TITLE
Limit batch to 65536 to align with the backend 

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#534]
The setting that should control the property is set to the incorrect value of 1024 Kb, not 64 Kb.

`MaxTransmissionBufferCapacity`
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/151509eac5e23fcbd09f3a8989a35d1099703957/src/TelemetryChannels/ServerTelemetryChannel/Shared/ServerTelemetryChannel.cs#L150

`this.Buffer.Capacity`
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/228f714dfeae7617283b8931501e6ecb0dd2d5d5/src/TelemetryChannels/ServerTelemetryChannel/Shared/Implementation/Transmitter.cs#L44

```
private const int DefaultCapacityInKiloBytes = 1024;
private int capacity = DefaultCapacityInKiloBytes * 1024;
```
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/151509eac5e23fcbd09f3a8989a35d1099703957/src/TelemetryChannels/ServerTelemetryChannel/Shared/Implementation/TransmissionBuffer.cs#L15

![image](https://cloud.githubusercontent.com/assets/9950081/24987985/ccc02a42-1fb7-11e7-94a0-79ed0260aa57.png)

Workaround is to set:

```
((ServerTelemetryChannel)TelemetryConfiguration.Active.TelemetryChannel).MaxTransmissionBufferCapacity = 64 * 1024;
```

**Comment by cijothomas** [comment]
We can take it for 2.4 stable if the fix is trivial.

**Comment by SergeyKanzhelev** [comment]
This may be more complex than just a limit change. This particular issue was caused by the single event's size larger than 65K
