### ISSUE TITLE
Quick-pulse telemetry doesn't seem to support multiple instrumentation keys in a single app

### ISSUE THREAD

**Issue by Piedone** [Microsoft/ApplicationInsights-dotnet#535]
Is it supported to send live stream data to multiple AI accounts, i.e. using multiple instrumentation keys within a single app? It doesn't seem so - if this is indeed the case, consider this a feature request please.

We have a two-layer AI config model in a multi-tenant ASP.NET application (think of tenants as "sub-applications"; see [this blogpost](https://azure.microsoft.com/blog/integrating-application-insights-into-a-modular-cms-and-a-multi-tenant-public-saas/) about it): There is a single instrumentation key for the whole app but a different `TelemetryConfiguration` object for each tenant AND for each tenant there is additionally another key and another, second `TelemetryConfiguration` (to have separate tenant-level telemetry). In this setup live stream is not working for tenants, just for the app-level account.

It seems that since `QuickPulseTelemetryModule` needs to be initialized with a single `TelemetryConfiguration` we can only use the app-level key here. Since there can be only a single `QuickPulseTelemetryModule` per app domain, it doesn't seem to be possible to hook up the tenant-level `TelemetryConfiguration`s with it.

**Comment by dnduffy** [comment]
I do not believe that this is directly supported.
However, since you can create multiple TelemetryConfigurations with different instrumentation keys, perhaps you can subclass the QuickPulseTelemetryModule and override any checks for singularity.  That would be kind of a hack though. ;)

**Comment by Piedone** [comment]
I looked into the decompiled code (the module doesn't seem to be open source), the issues seems to be indeed that there is a single `QuickPulseServiceClient` used in the module, which is configured with data generated from the `TelemetryConfiguration` used when initializing.

**Comment by SergeyKanzhelev** [comment]
Moved to the `-server` repository: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/465
