### ISSUE TITLE
Missing exception telemetry for 500 requests

### ISSUE THREAD

**Issue by FeiDeng** [Microsoft/ApplicationInsights-dotnet#539]
trying to understand the life cycle of telemetry. I have pass an exception to Telemery. However it is not able to show up in Application Insights. I got 800+ requests that have 500 status code as response, but none of the exception get logged. Anything I can do pop the exception?

**Comment by SergeyKanzhelev** [comment]
@FeiDeng your question got lost among other issues. I'm sorry for this.

Application Insights pipeline and data optimization techniques explained in this [msdn articles](https://msdn.microsoft.com/magazine/mt808502). 

One of two things happened from how I read the explanation - exception telemetry objects got sampled to save on storage or exceptions wasn't associated with the request telemetry.

We'd need more details on how exactly you are tracking exceptions to be able to nail down the problem.
