### ISSUE TITLE
Make MetricManager API private for the 2.4 stable release

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#540]
In my opinion we can keep MetricProcessors as QuickPulse took a dependency on it and MetricProcessors API will likely stay no matter how the API surface will look like for the customer

CC: @AlexBulankou @Dmitry-Matveev @cijothomas @tokaplan @kstevenham

**Comment by AlexBulankou** [comment]
+1 on keeping MetricProcessors public

**Comment by SergeyKanzhelev** [comment]
Why? Which feature will use those? If there are no use for now - let's not open it

**Comment by AlexBulankou** [comment]
@SergeyKanzhelev you said: "In my opinion we can keep MetricProcessors as QuickPulse took a dependency on it and MetricProcessors API will likely stay no matter how the API surface will look like for the customer". So I was agreeing :)

**Comment by kstevenham** [comment]
If the MetricManager is private then the MetricProcessors should also be private. The MetricManager is the one that calls the MetricProcessors.

**Comment by SergeyKanzhelev** [comment]
@AlexBulankou I changed my mind after talking to VitalyG and Keith
