### ISSUE TITLE
Exception Telemetry sanitize does not sanitize message

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#546]
Sanitize is only trimming properties etc, but not message itself.
https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/ExceptionDetails.bond#L19

Also need to make sure everything is conforming to the schema above. At present ingestion is rejecting exception only if above 65K. As per schema it should be 32K. But the following doc says 10K.
https://github.com/Microsoft/azure-docs/blob/master/includes/application-insights-limits.md

**Comment by eddynaka** [comment]
Hi all, is this still a issue?
I looked in to the docs, and I think it is up to date (it's showing 64KB).

**Comment by cijothomas** [comment]
Sanitize need to trim message to ensure the limit is not exceeded. This is not fixed.
