### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by cijothomas** [Microsoft/ApplicationInsights-dotnet#548]
Docs says use Metric Manager as recommended way from 2.4 version onwards.
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#send-metrics

There is no 2.4 stable version yet, and even if there is, MetricManager is internal so can't use.

**Comment by SergeyKanzhelev** [comment]
CC: @vgorbenko, @macrogreg

**Comment by macrogreg** [comment]
Created a PR:
https://github.com/Microsoft/azure-docs/pull/1772

**Comment by SergeyKanzhelev** [comment]
Resolved
