### ISSUE TITLE
TelemetryConfigurationFactory should be able to read numbers in hexadecimal format

### ISSUE THREAD

**Issue by karolz-ms** [Microsoft/ApplicationInsights-dotnet#551]
Currently it is not possible for numeric properties in the configuration to use hexadecimal numbers. For example 
```xml
<Add ProviderName="Microsoft-Windows-PowerShell" Keywords="128" />
```
works but
```xml
<Add ProviderName="Microsoft-Windows-PowerShell" Keywords="0x80" />
```
does not.

Using hexadecimal values is very convenient when the property represents some flags. We should support it.

The reason this does not work today is that `TelemetryConfigurationFactory.LoadInstanceFromValue()` method calls into `Convert.ChangeType()`, which does not support hexadecimal values. For numeric properties we should try harder. For example, if the value starts with `0x` or `0X`, we could attempt `Int32.TryParse()` with `AllowHexPrefix` set before falling back to `Convert.ChangeType`.

**Comment by SergeyKanzhelev** [comment]
Good idea. Would you send a PR?

**Comment by karolz-ms** [comment]
Will do

**Comment by Dmitry-Matveev** [comment]
@karolz-ms did you have time to take a look at this?

**Comment by karolz-ms** [comment]
Sorry :-*/ 

Not in foreseeable future
