### ISSUE TITLE
Migrating from the azure site extension to a direct reference

### ISSUE THREAD

**Issue by xt0rted** [Microsoft/ApplicationInsights-dotnet#554]
I've been using the application insights site extension on azure but would like to transition to referencing the sdk directly.

Is there any documentation outlining what packages and/or settings need to be setup in order to keep the same configuration?

To remove the site extension is there anything that has to be done beside deleting it?

**Comment by SergeyKanzhelev** [comment]
Install this NuGet: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/

When updating the application - make sure to select an option to "delete extra files" like explained [here](http://stackoverflow.com/questions/32623397/azure-web-app-delete-all-files-before-publish) to make sure there are no leftovers from Application Insights extension in the application folder.

I suggest you to keep the extension. It will detect that the application was on-boarded on Application Insights and will not re-enable monitoring. However it will improve data collection by enabling extra collection features. Like it will allow to collect SQL statement and HTTP verb.

I'm closing the issue, but feel free to re-open it if you have follow up questions

**Comment by xt0rted** [comment]
I finally got around to directly referencing the sdk in my project. I left the site extension on and have the most current sdk from NuGet with the default configuration it setup for me. In my Live Metrics Stream I'm seeing the following traces
> AI: Performance counter is not available in the web app supported list. Counter is \Memory\Available Bytes.

> AI: Performance counter is not available in the web app supported list. Counter is \Processor(_Total)\% Processor Time.

Is there something I should turn off in the config or are these expected and the configuration is ok?
