### ISSUE TITLE
Context.User.UserAgent is not transferred

### ISSUE THREAD

**Issue by marnilss** [Microsoft/ApplicationInsights-dotnet#558]
I have an Azure App Service that I have extended with a TelemetryInitializer to collect the UserAgent string from the requests, and writes it to client.Context.User.UserAgent.
I can run it locally and when looking at the data from the last debug session, in Visual Studio, I can see that the property "User agent string" in the details view of Trace/Request/Dependency matches the caller.
But when looking at the data transferred to the Azure Application Insights resource, everything but the "User agent string" is there.

Why is there a discrepancy between what is collected, and what is transferred? We previously also discovered that the Context.Device.Id isn't transferred either. If the properties are considered obselete and shouldn't be used any more, why not mark them with ObseleteAttribute and then after a release or two, actually remove them.

I'm using version 2.3.0 of the Microsoft.ApplicationInsights NuGet package.

**Comment by SergeyKanzhelev** [comment]
Sorry for confusion. Please read details here:
https://github.com/Microsoft/ApplicationInsights-Announcements/issues/3
