### ISSUE TITLE
Telemetry processor not getting requests.

### ISSUE THREAD

**Issue by tokaplan** [Microsoft/ApplicationInsights-dotnet#561]
In the process of deploying and redeploying a //build demo app to a Azure Web Apps (with the checkbox to remove previously deployed files unchecked), our PMs have run into an issue when:
- with both Snapshot collection telemetry processor and QuickPulse telemetry processor enabled, QuickPulseTelemetryProcessor would not receive any requests. It would receive all other telemetry types, but not requests.
- with Snapshot collection telemetry processor commented out from AI.config, QuickPulse telemetry processor would start receiving requests as expected.
- that reproed in a stable manner until the checkbox to clean out old files before deployment was set, at which point the repro was lost.
- during the repro, the main pipeline would still send out the requests that were not making it to the QuickPulseTelemetryProcessor.

**Comment by Dmitry-Matveev** [comment]
The issue if fixed. The root cause was in the initialization logic of Diagnostic Source subscribers. The second call failed with the Null Reference Exception. Having several modules at the same time that require Diagnostic Source led to this issue.
