### ISSUE TITLE
Using AI to instrument code / subclassing OperationTelemetry

### ISSUE THREAD

**Issue by AleRoe** [microsoft/ApplicationInsights-dotnet#565]
Hello!

I'm currently using AI to instrument a long running process which consists of several consecutive processing steps. The intention is to understand how long each method takes and to collect relevant processing metrics for each step (using custom properties and metrics). All steps are accumulated under a single OperationID so that I can view the complete telemetry for the process in ApplicationInsights Search.

To achieve this, I am currently “abusing” RequestTelemetry and DependenyTelemetry together with the TelemetryClient.StartOperation() method within a static wrapper class. When the long running process starts, I create a RequestTelemtry and for any processings steps I use a DependencyTelemetry. This works very nicely and allows me to graphically view the durations and metrics for the whole process.

What bothers me is that RequestTelemetry and DependencyTelemetry are both tailored towards typical web-based applications (as actually most of ApplicationInsights is), with properties that are not relevant to pure method executions (such as ResponseCode or URL). While this is more of a cosmetic issue, I thought it would be nice if I could just inherit from OperationTelemetry (which handles all the duration computation) and create my own MethodTelemetry object. Unfortunately, this does not work because many of the required methods to initialize an OperationTelemetry are internal. I assume this is the case because the ApplicationInsights Service itself can only handle specific, predefinded Telemetry types.

So my questions are:
Are there any plans to allow custom Telemetry objects or is there some way to subclass OperationTelemetry?
Would it make sense to add a MethodTelemetry object to the SDK?

I’m aware that I could just use EventTelemetry instead, adding in the timestamps and duration computation myself.
But it doesn’t “feel” right, as an Event is more of an atomic, on-shot incident as opposed to something that has a start and end.
Also, I’m not sure how well I can see dependencies and sequences when using Events in ApplicationInsights Search. At least not as nicely as when using Requests and Dependencies…

Any thoughts? 

Kind regards
Alexander

**Comment by Dmitry-Matveev** [comment]
Related to #593

**Comment by maxbog** [comment]
Hi, I'm also interested in such functionality. Any plans to add it to AppInsights?

**Comment by derekgreer** [comment]
+1 On this.  Our team has a Kafka daemon and we are using RequestTelemetry as the top level operation given the absence of a more appropriate OperationTelemetry derivative.

**Comment by FBryant87** [comment]
I'm confused by this also, is there really no timed duration metric out the box - does it have to be a Request or Dependency being measured?
