### ISSUE TITLE
Programatically create equivalent of AI.config Defaults

### ISSUE THREAD

**Issue by cijothomas** [Microsoft/ApplicationInsights-dotnet#566]
AI.config has a bunch of default settings like list of initializers, modules, processors, and various others. For someone programatically configuring AI settings, there should be a method like 'CreateDefaultAI' which constructs the default TelemetryConfiguration matching the default AI.config.

**Comment by Dmitry-Matveev** [comment]
So far there is no clear design on this feature, and we track ASP.NET Core configuration separately. Closing this issue for now.
