### ISSUE TITLE
Out of Memory Exception while using Application Insight with ASP.NET Core Web Application

### ISSUE THREAD

**Issue by patrickCode** [Microsoft/ApplicationInsights-dotnet#570]
Our ASP.NET Core Web Application have been crashing on huge load for the past few weeks. We are seeing the error - "An exception was thrown by a TaskScheduler.Exception of type 'System.OutOfMemoryException' was thrown." On debugging the application we found that the memory issue is happening due to the addition of "Application Insights Services" in the MVC pipeline.
`services.AddApplicationInsightsTelemetry(Configuration);`

![image](https://user-images.githubusercontent.com/16106642/27333567-f46dcdb2-55e3-11e7-9491-d315d1cd391a.png)

We are using "Microsoft.ApplicationInsights.AspNetCore 2.0.0".
How do we resolve this issue? Are we missing any best practice method of using application insight?

**Comment by pakrym** [comment]
Do you still have this snapshot? If you expand path to root what is holding onto all these AI objects?

**Comment by Dmitry-Matveev** [comment]
@patrickCode , could you please provide us with the snapshot/repro to investigate? Closing for now.
