### ISSUE TITLE
Expose a public method for copying TelemetryContext.

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-dotnet#579]
We should expose a public API for an efficient deep copy for objects of type Microsoft.ApplicationInsights.DataContracts.TelemetryContext.

_Reasons_:

ITelemetry exposes a property Context of type TelemetryContext. End users and SDK add-on authors may want to track multiple telemetry items with the same, previously defined context. Currently, the mechanism for doing that is to set the Context property of a TelemetryClient and use that client to track respective items. However, this approach ties together the Context (a set of properties related to telemetry being sent) and the pipeline configuration (a set of properties related to how and where it is being sent). This is unfortunate. For example, forward looking metrics features require setting the Context of a MetricTelemetry item independently from information about the channel and the pipeline.

TelemetryContext has internal methods for _efficiently_ deep-copying information from other TelemetryContext objects. However, this is not accessible to features in non-Core packages. I propose we expose a respective API publicly.

_Possible solutions_:

There are at least 3 approaches (specific names are just suggestions):

a) A copy ctor "TelemetryContext(TelemetryContext template)".
b) A clone method "TelemetryContext TelemetryContext.DeepCopy()".
c) A copyfrom method "void TelemetryContext.InitializeFrom(TelemetryContext template)".

I recommend solution (c) for the following reason:
Currently all core implementations if ITelemetry have getters, but not setters for their respective Context properties. A sub-system that tries to create many telemetry items (of any specific core type) with a specified context as described above would need to expose additional ctors or setters that allow specifying a copied context. However, if we allow initializing an existing default context using a template, no such changes are necessary.

**Comment by macrogreg** [comment]
I am happy to do the work if there is consensus about it.

**Comment by SergeyKanzhelev** [comment]
Great! I think it will be very handy to have this method.

@karolz-ms did you plan also to create one for https://github.com/Microsoft/ApplicationInsights-dotnet/issues/559?

**Comment by karolz-ms** [comment]
@macrogreg @SergeyKanzhelev I have added a deep copy method to the TelemetryContext as part of #559 work, but I kept it internal, and I do not think it is really applicable. 

The tricky part is that in the current implementation the TelemetryContext is not really independent from its telemetry. What I mean is that object returned by  ITelemetry.Context shares the properties dictionary with its ITelemetry. I need to clone the whole telemetry instance, which means I need to make the new TelemetryContext use the already-cloned, existing properties dictionary of the new (freshly cloned) telemetry. This is a different scenario from what Greg is looking for.

Given the above I think option (c) is _the only good way_ to proceed... but it is also a separate work item.

**Comment by SergeyKanzhelev** [comment]
Will it be easier if we will detach item properties from context properties? We can merge them on serialization. Do you think it will be easy to understand the difference between context properties and item properties?

**Comment by karolz-ms** [comment]
From implementation perspective I do not think the original proposal is difficult to implement. We already have code in TelemetryClient.Initialize(ITelemetry) that does initialize telemetry context from the context held by the TelemetryClient.

As to detaching item properties from context properties... not sure if this would be easier to understand. It would also be a breaking change (today you can set a property on the item and rely on the fact that the context will have it, or vice versa).
