### ISSUE TITLE
Remove the setter TelemetryConfiguration.Active

### ISSUE THREAD

**Issue by macrogreg** [Microsoft/ApplicationInsights-dotnet#580]
The setter is an internal API that is never called. Let's remove it to reduce confusion. I am happy to do the work.

**Comment by SergeyKanzhelev** [comment]
it is still being used in tests:

![image](https://user-images.githubusercontent.com/9950081/27893616-98df6de6-61bb-11e7-8a47-95fd3727f1bc.png)
