### ISSUE TITLE
Expose TelemetryClient.TelemetryConfiguration publically.

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-dotnet#581]
TelemetryClient brings together 3 concepts: Properties of items sent through it (Context), information about how and where to send the items (TelemetryConfiguration) and APIs to do the sending (TrackXxx(..) methods). Although both of the former aspects are required to create a client (TelemetryConfiguration.Active is used as default, but implicitly, that information is still encapsulated), only the Context is exposed outside of Core.

This is unfortunate: A consumer of a TelemetryClient may want to access information about how and where the client will deliver data. For example, metrics are aggregated across all clients within the same configuration, but separately between pipeline configurations. So, aggregation logic needs to be able to ask a client, what its telemetry configuration instance is.

The proposed change is to make the existing internal TelemetryClient.TelemetryConfiguration property public.

**Comment by SergeyKanzhelev** [comment]
It was explicitly made private so there will be no confusion and undesired consequences. When one changes anything in `TelemetryClient.Configuration` the change can affect other clients. This can be unexpected.

We also never had a real life scenarios where this was needed and not enough just to keep configuration object around.

**Comment by macrogreg** [comment]
I see this as a yet another of the TelemetryClient layering. :(
My goal is to build an extension method outside of Core that does something like that (very simplified):

public static void TrackMetricValue(this TelemetryClient client, string metric, double value)
{
    client.TelemetryConfiguration.GetMetricAggregator(metric).TrackValue(value);
}

If there is an alternative way to achieve this effect, please let me know so I can explore it.

**Comment by macrogreg** [comment]
I am looking at this method:

        /// <summary>
        /// This method is an internal part of Application Insights infrastructure. Do not call.
        /// </summary>
        /// <param name="telemetry">Telemetry item to initialize.</param>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public void Initialize(ITelemetry telemetry)
        {
                ...

We could consider a similar approach.
