### ISSUE TITLE
Upgrading SDK adds AdaptiveSamplingTelemetryProcessor to ApplicationInsights.config twice.

### ISSUE THREAD

**Issue by MS-TimothyMothra** [Microsoft/ApplicationInsights-dotnet#583]
When upgrading the SDK, the AdaptiveSamplingTelemetryProcessor is added to ApplicationInsights.config twice:

```
<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
<MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
<IncludedTypes>Event</IncludedTypes>
</Add>
```

**Comment by SergeyKanzhelev** [comment]
by design. One include Events, another exclude. See changelog for explanaition

**Comment by SidShetye** [comment]
@SergeyKanzhelev can you copy paste the explanation here? Google ranks this page for the "issue" but it's unclear where the appinsight team keeps it's changelog or where to search inside.

**Comment by caveman-dick** [comment]
If you look at the Faqs on the docs here it explains it: https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#frequently-asked-questions

It isn't clear at all when looking at the config but does make sense when you read the explanation. :)
