### ISSUE TITLE
User ID should be propagated with the Activity

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#591]
User ID is used to calculate sampling. Thus it should be propagated thru async/await and cross the boundaries of a single component. So distributed trace will not be broken by sampling

**Comment by lmolkova** [comment]
Propagating userid is a security concern and overhead as we only need to know on the downstream service that request was sampled upstream based on user id. Also, there is no need to calculate it on each boundary.
I believe correlation-context and flags were designed exactly for this purpose.

**Comment by SergeyKanzhelev** [comment]
user id represents an anonymous user id and not a PII information. However I hear your concern and we need to discuss what will be the best way to implement it.

Simply passing `sampled` flag may 
1. break statistics on downstream components as upstream service may be responsible for very specific calls which will suddenly dominate statistics
2. break promise of AdaptiveSampling telemetry processor that controls the cost of monitoring.

So further design discussions required on the "correct" implementation.

**Comment by SergeyKanzhelev** [comment]
Also this https://github.com/Microsoft/ApplicationInsights-dotnet/issues/221 may help for certain scenarios

**Comment by zakimaksyutov** [comment]
I think passing userId/hash of userId might lead to information disclosure (tracking).

**Comment by Dmitry-Matveev** [comment]
There is a new proposal on the table, we'll open a separate discussion soon.
