### ISSUE TITLE
Implement generic DiagnosticSource listener

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#592]
Generic DiagnosticsSource listener (may be part of DependencyCollection nuget package) will be helpful to simplify support of a new platforms and technologies.

This work may require implementing a new type of operation - something in between of Requests and Dependencies

**Comment by lmolkova** [comment]
Related to https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/609

**Comment by MS-TimothyMothra** [comment]
@lmolkova Is this task finished?

**Comment by lmolkova** [comment]
@MS-TimothyMothra I think it's addressed with https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/662

@TomMilos is behind this work, not me

**Comment by lmolkova** [comment]
Perhaps it's a duplicate of https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/665
