### ISSUE TITLE
Do not create a new HttpClient for every Transmission

### ISSUE THREAD

**Issue by cwe1ss** [Microsoft/ApplicationInsights-dotnet#594]
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Core/Managed/Shared/Channel/Transmission.cs#L62 creates a new HttpClient instance for every transmission.

See e.g. https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/ for why this is wrong (it creates too many sockets and they stay open for too long).

**Comment by SergeyKanzhelev** [comment]
Thank you for reporting the issue. Feel free to send a PR.

**Comment by cwe1ss** [comment]
Not sure if I have time for it. Would you agree to this approach:

* Make the HttpClient instance a static variable on Transmission
* Each transmission gets a timeout value but HttpClient only has a global `Timeout`-property. According to the [HttpClient](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L415) source, a possible workaround would be:
* * Set the global Timeout to "Infinite"
* * Use the `SendAsync` overload that takes a CancellationToken and pass a token that expires after the Transmission-timeout value

Does this need additional tests in [TransmissionTest.cs](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/Test/CoreSDK.Test/Shared/Channel/TransmissionTest.cs)?

**Comment by SergeyKanzhelev** [comment]
I'd say move it away from the transmission class and make HttpClient be owned by the sender. This way the lifecycle of a single HttpClient is much easier to control. And there will be no problems of one httpclient shared by multiple senders and attempts to send data the same time.

**Comment by cwe1ss** [comment]
I agree to that. However there's conditional `#if` behavior with `HttpClient` and the old `WebRequest` in there, so this would probably require a bigger refactoring and I definitely don't want to do that right now.

**Comment by SergeyKanzhelev** [comment]
@cwe1ss with the approach you proposed you'll need to synchronize access to static variable. Do you have an idea how to make it efficient?

It may not be a huge refactoring if you'll keep some wrapper class in Sender that will be used by transmissions.

**Comment by kogir** [comment]
HttpClient is thread safe if used correctly. You don't need to synchronize access to it, just its construction.

Safe methods:
```
CancelPendingRequests
DeleteAsync
GetAsync
GetByteArrayAsync
GetStreamAsync
GetStringAsync
PostAsync
PutAsync
SendAsync
```
See https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.110).aspx#Anchor_5

**Comment by SergeyKanzhelev** [comment]
Thanks @kogir! It makes sense now to go with the simpler fix and just reuse a static `HttpClient`.

**Comment by cijothomas** [comment]
Closing via #857
