### ISSUE TITLE
Implement IDisposable on TelemetryClient and call Flush

### ISSUE THREAD

**Issue by cwe1ss** [Microsoft/ApplicationInsights-dotnet#596]
This request is related to #407 (Blocking `Flush`)

When using `TelemetryClient` with a DI library it would be great if we could rely on the auto-disposal features to flush all open telemetry data. 

Example: ApplicationInsights-aspnetcore adds `TelemetryClient` as a singleton to the DI library. In order to flush messages on shutdown, people currently have to use other events (`IApplicationLifetime`) to call `Flush` manually. If `TelemetryClient` would implement `IDisposable` and call `Flush` within it, this would happen automatically when the ASP.NET Core shuts down (and disposes the underlying DI service provider).

I would create a PR if you agree to this request.

PS: We then still need a blocking Flush for ServerTelemetryChannel as requested in #407 to get a fully reliable solution.

**Comment by SergeyKanzhelev** [comment]
`IDisposable` is like a virus. Owning of `IDisposable` should make itself `IDisposable`. We intended to make `TelemetryClient` easy to use - create, store. Thus it doesn't implement disposable.

It also often used to fire and forget of a single event. Immediate Flush will make Flush less useful.

You can always implement a simple disposable wrapper that will behave the way you describe if it is intended use.
