### ISSUE TITLE
Correct documentation about Telemetry Channels

### ISSUE THREAD

**Issue by Dmitry-Matveev** [microsoft/ApplicationInsights-dotnet#597]
Official documentation [here ](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-configuration-with-applicationinsights-config#telemetry-channel) states that `ServerTelemetryChannel` stores data in the memory buffer. It's not a complete story about the Server Telemetry Channel and led to confusion in several cases (this channel stores transmissions in local storage).

In addition, the same documentation page only mentions `PersistenceChannel` as the other option, we might want to add `InMemoryChannel` there.

**Comment by cijothomas** [comment]
Addressed with new doc onchannel.
