### ISSUE TITLE
Null Ref Exception when InstrumentationKey is null

### ISSUE THREAD

**Issue by TheRealPiotrP** [Microsoft/ApplicationInsights-dotnet#613]
We are building some middleware for ASP.NET Core which takes advantage of AI's handling of the `Request-Id` header. While testing the middleware we wanted to enable AI but did not want to report any telemetry. We therefore created:
```
var appInsightsOptions =
                new ApplicationInsightsServiceOptions
                {
                    DeveloperMode = Environment.IsDevelopment()
                };
```

Note that there is no Instrumentation  Key. Invoking `services.AddApplicationInsightsTelemetry(appInsightsOptions);` with these options succeeds. However, our component under test later makes Web Requests via an HttpClient. These invocations result in a NRE with no useful debugging information. 

We worked around this issue by adding an empty-string Instrumentation Key to our AI Options:
```
var appInsightsOptions =
                new ApplicationInsightsServiceOptions
                {
                    DeveloperMode = Environment.IsDevelopment(),
                    InstrumentationKey = ""
                };
```

### Expected:
There are two obvious options:
 - Enable HttpClient to work when AI is enabled but an Instrumentation Key is not provided. This is preferred, since AI seems to work [e.g. it reads an incoming request's `Request-Id` header and propagates it to `Activity.Current.Id`] so long as we don't invoke an HttpClient.
 - Provide an actionable exception. This would probably be some sort of argument exception when invoking AddApplicationInsightsTelemetry without an Instrumentation Key.

**Comment by SergeyKanzhelev** [comment]
@lmolkova can you please take a look?

**Comment by lmolkova** [comment]
Here is a stack trace from @piotrpMSFT 

```
{"message":"An unhandled exception occurred.","exception":"System.NullReferenceException: Object reference not set to an instance of an object.\n   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.ApplicationInsightsUrlFilter.get_EndpointLeftPart()\n   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.ApplicationInsightsUrlFilter.IsApplicationInsightsUrlImpl(String url)\n   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.HttpCoreDiagnosticSourceListener.OnActivityStart(HttpRequestMessage request)\n   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.HttpCoreDiagnosticSourceListener.OnNext(KeyValuePair`2 evnt)\n   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)\n   at System.Diagnostics.DiagnosticSource.StartActivity(Activity activity, Object args)\n   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\n   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n
```

So the issue happens on netcoreapp 2.0

According to @piotrpMSFT it *frequently* reproduces on Linux and  *sometimes* on Mac.
I was not able to repro it on Windows: no exception happens with null or empty ikey.

Potentially the issue is some static initialization race condition that happens when dependency call is done before the AI fully initialized

Perhaps exception happens here: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/ApplicationInsightsUrlFilter.cs#L34, however it's not clear how TelemetryChannel could be null.

```
        private string EndpointLeftPart
        {
            get
            {
                string currentEndpointAddressValue = null;

                // Cache AI endpoint URI
                if (this.telemetryConfiguration != null)
                {
                    // EXCEPTION ???
                    string endpoint = this.telemetryConfiguration.TelemetryChannel.EndpointAddress;
                    if (!string.IsNullOrEmpty(endpoint))
                    {
                        // The TelemetryChannel is used which defines the production endpoint in ApplicationInsights.config.
                        currentEndpointAddressValue = endpoint;
                    }
                }

                if (this.cachedEndpointLeftPart.Key != currentEndpointAddressValue)
                {
                    this.cachedEndpointLeftPart = this.GetEndpointLeftPart(currentEndpointAddressValue);
                }

                return this.cachedEndpointLeftPart.Value;
            }
        }
```

@cijothomas do you know if we have a way to collect event source traces on Mac?

As a workaround, problem should be solved by using real AI resource for free plan.

**Comment by piotrpMSFT** [comment]
Some updates on this issue:
- I have a fairly reliable repro on Windows, but not in Visual Studio. Running `dotnet test` from the command line reproduces the issue with similar frequency to Mac.
- Adding a InstrumentationKey for test scenarios, as suggested above, did not resolve the issue. I do not have a viable workaround at this time.

**Comment by lmolkova** [comment]
@piotrpMSFT 
Since the workaround did not help, it seems absence of ikey is not the problem.

for the code you shared with me previously, for the test scenarios you have `services.AddTransient<TelemetryClient>()` 

Any particular reason why it's transient?

Can you repro the issue if you add it as singleton?

**Comment by piotrpMSFT** [comment]
I changed this to singleton with no observed difference.

**Comment by piotrpMSFT** [comment]
In addition to the change above, we've changed the affected tests to execute serially. This led to a new callstack that may yield some hints:

```
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
     at Microsoft.ApplicationInsights.Extensibility.Implementation.TransmissionProcessor.Process(ITelemetry item)
     at Microsoft.ApplicationInsights.TelemetryClient.Track(ITelemetry telemetry)
     at Microsoft.ApplicationInsights.AspNetCore.DiagnosticListeners.HostingDiagnosticListener.EndRequest(HttpContext httpContext, Int64 timestamp)
     at Proxy_Method_From_<>f__AnonymousType2`1_To_Void OnHttpRequestInStop(Microsoft.AspNetCore.Http.HttpContext)(Object , Object , IProxyFactory )
     at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write(String diagnosticName, Object parameters)
     at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
     at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
     at System.Diagnostics.DiagnosticSource.StopActivity(Activity activity, Object args)
     at Microsoft.AspNetCore.Hosting.Internal.HostingApplicationDiagnostics.StopActivity(HttpContext httpContext, Activity activity)
     at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.DisposeContext(Context context, Exception exception)
     at Microsoft.AspNetCore.TestHost.TestServer.ApplicationWrapper`1.DisposeContext(TContext context, Exception exception)
     at Microsoft.AspNetCore.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
```

**Comment by lmolkova** [comment]
@piotrpMSFT 
based on the traces I collected running your tests, I see that you have multiple subscriptions active to the same DiagnosticsSources.
It means that between the tests ApplicationInsights is not properly disposed.

We will check further why it does not happen, but running your tests one by one (in separate processes, not serially) works fine.

**Comment by piotrpMSFT** [comment]
Thanks @lmolkova! Are there ways in which we may be creating and not disposing these subscriptions in e.g. logging infrastructure? Any tell-tale APIs we should be looking for?

**Comment by lmolkova** [comment]
It appears that web host was not disposed properly by tests, i.e. AppInsights objects were not disposed and every test created a new AI modules.
The exception is misleading and unrelated to the issue.

@dnduffy @SergeyKanzhelev 
Please prioritize it. 
Could we detect that AI was not disposed and is being initialized again? Could we prevent it to happen?
I remember spending at least a day debugging a similar disposing-related issue in AspNetCore SDK tests and I think it's not critical, but important to quickly diagnose such problems.

**Comment by dnduffy** [comment]
I believe the .NET Core SDK prevents duplicate initialization from calling both AddApplicationInsights and/or UseApplicationInsights more than once but I don't recall anything in the base SDK like that.  It should be safe to make multiple TelemetryClient and TelemetryConfiguration instances and/or to reuse the default Active config instance.  There used to be a check in the base to make sure a null or empty instrumentation key resulted in logging a message to the console instead of trying to actually send data, I'm not sure what the code is currently like though after the changes for multiple channels.

**Comment by lmolkova** [comment]
@dnduffy 
the problem I have seen is NOT related to ikey, but to the fact that AddApplicationInsights is called multiple times in the same process. So this is not safe at least under some conditions.

**Comment by lmolkova** [comment]
And it reporduces with AI SDK 2.4, so multi channel is not related

**Comment by dnduffy** [comment]
Sounds like the base SDK init needs to be made idempotent the way the .NET Core SDK was.
@cijothomas

**Comment by bytemaster-0xff** [comment]
FYI - This may be purely anecdotal, but I recently set "DeveloperMode" in my AI config to true, I started receiving the `get_EndpointLeftPart` null reference exception about every other time while my app was initializing.  I then turned off that feature and that error seems to have gone away.  At least the last 20 or so times I tried starting my app.

**Comment by bytemaster-0xff** [comment]
With more testing, it doesn't seem related to that, I still haven't tracked down the original source but found that if I start/stop a WebHost, it does something nasty to the internals that are connecting to remote servers via HttpClient.  Anyway, I found a work around, but still don't understand how/why this was happening.

**Comment by mkosieradzki** [comment]
Any news on making AddApplicationInsights idempotent? Multiple calls to `AddApplicationInsights` is a common practice in Service Fabric... in many different kind of scenarios including: SharedProcess hosting model, multiple listeners...

**Comment by lmolkova** [comment]
It seems I have found the root cause for this issue.

It looks like the problem is not `AddApplicationInsights`  not being idempoted - it is.
The problem is multiple WebHosts running in the same process. I.e. there are several instances of ServiceProvider and each of them has full and valid set of ApplicationInsights services.

However since there are a lot of singletons (i.e. static instance, not the DI kind of singleton), their lifetime is not limited to the WebHost.

It's easy to repro with following tests:
1. Sequential web host creation  - seems to work just fine
```csharp
        public async Task TwoWebHostsSequentially()
        {
            using (var host1 = BuildWebHost(new string[0], 5000))
            {
                Task.Run(() => host1.Run());
                await hc.SendAsync(request);
            }

            using (var host2 = BuildWebHost(new string[0], 5001))
            {
                Task.Run(() => host2.Run());
                await hc.SendAsync(request);
            }
        }
```

2. Parallel web host creation - works, however, dependencies are reported twice for each host ( perhaps because of DiagnosticListener subscriptions)

```csharp
        [Fact]
        public async Task TwoWebHostsInParallel()
        {
            using (var host1 = BuildWebHost(new string[0], 5000))
            using (var host2 = BuildWebHost(new string[0], 5001))
            {
                Task.Run(() => host1.Run());
                Task.Run(() => host2.Run());

                var request1 = new HttpRequestMessage(HttpMethod.Get, "http://localhost:5000/api/values");
                await hc.SendAsync(request1);

                var request2 = new HttpRequestMessage(HttpMethod.Get, "http://localhost:5001/api/values");
                await hc.SendAsync(request2);
            }
        }
```

3. one of the hosts is disposed while another is active

```csharp
        [Fact]
        public async Task TwoWebHostsAfterOneIsDisposed()
        {
            var host1 = BuildWebHost(new string[0], 5000);
            var host2 = BuildWebHost(new string[0], 5001);

            Task.Run(() => host1.Run());
            Task.Run(() => host2.Run());

            var request1 = new HttpRequestMessage(HttpMethod.Get, "http://localhost:5000/api/values");
            await hc.SendAsync(request1);
            host1.Dispose();

            var request2 = new HttpRequestMessage(HttpMethod.Get, "http://localhost:5001/api/values");
            await hc.SendAsync(request2);
        }
```

It results in 

```
Test Name:	testrepro.UnitTest1.TwoWebHostsAfterOneIsDisposed
Test FullName:	testrepro.UnitTest1.TwoWebHostsAfterOneIsDisposed
Test Source:	c:\repo\delme\aspnetcore\testrepro\UnitTest1.cs : line 71

Result StackTrace:	
at Microsoft.ApplicationInsights.DependencyCollector.Implementation.ApplicationInsightsUrlFilter.get_EndpointLeftPart()
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.ApplicationInsightsUrlFilter.IsApplicationInsightsUrlImpl(String url)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.HttpCoreDiagnosticSourceListener.HttpCoreDiagnosticSourceSubscriber.<OnNext>b__6_0(String evnt, Object r, Object _)
   at System.Diagnostics.DiagnosticListener.IsEnabled(String name, Object arg1, Object arg2)
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at testrepro.UnitTest1.<TwoWebHostsAfterOneIsDisposed>d__5.MoveNext() in c:\repo\delme\aspnetcore\testrepro\UnitTest1.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.


```
@mkosieradzki 
I believe that what's happen in your case. Could you confirm?

## Root cause:
TelemetryConfiguration being a singleton (static instance) is reused by host2.
When the host1 is disposed, it causes TelemetyConfiguration instance to be disposed.
This results in TelemetryChannel underneath to be disposed and set to null

So when app insights in host2 attempt to track dependency, it leads to the call to null telemetry channel.

**Comment by mkosieradzki** [comment]
@lmolkova thanks for doing all the analysis for this case. I confirm that this is the bigger part of the case, however I am still observing (after doing a workaround and reusing a single instance of DependencyTrackingTelemetryModule In multiple WebHosts) that some HttpRequests originating from OUTSIDE of the WebHost are throwing the aforementioned exception (I don’t know whether it is a lifetime or CallContext related issue).

It would be important to make sure requests coming from outside of the WebHosts are not broken as well.

Example from the ServiceFabric world: a service is exposing some listeners (each one is a WebHost) and a backup loop which is creating backups using AzureStorageSDK under some conditions backups are failing. One should not make any assumptions about the lifetime of listeners when compared to the backup loop...

**Comment by lmolkova** [comment]
@mkosieradzki 

dependency tracking happens beyond WebHosts and relies purely on .NET - it is not aware of AspNet DI and web hosts and does not respect it's boundaries. 
On our side we should make sure: 
- dependency tracking never ever throws no matter what
- we do not reuse telemetry configuration between web hosts
- we DO reuse dependency tracking listeners between hosts or make sure they only track *their* dependencies

BTW, we create a dependency tracking module per web host. you could easily check it with this test
```csharp
            var host1 = BuildWebHost(new string[0], 5003);
            var host2 = BuildWebHost(new string[0], 5004);

            var depTracking1= host1.Services.GetServices(typeof(ITelemetryModule)).First();
            var depTracking2= host2.Services.GetServices(typeof(ITelemetryModule)).First();
            depTracking1 != depTracking2 at this point
```
Perhaps your workaround causes telemetry configuration to be re-created and this is the real workaround.

**Comment by mkosieradzki** [comment]
@lmolkova Yup, sounds reasonable. It also explains why it works only partially ;).

**Comment by lmolkova** [comment]
@mkosieradzki 
BTW, would you mind sharing your workaround?

**Comment by mkosieradzki** [comment]
@lmolkova I am sorry for the delay.

I am not very proud of this workaround:

```
        private static readonly Lazy<DependencyTrackingTelemetryModule> dependencyTrackingModule = new Lazy<DependencyTrackingTelemetryModule>(() =>
        {
            var module = new DependencyTrackingTelemetryModule();

            var excludedDomains = module.ExcludeComponentCorrelationHttpHeadersOnDomains;
            excludedDomains.Add("core.windows.net");
            excludedDomains.Add("core.chinacloudapi.cn");
            excludedDomains.Add("core.cloudapi.de");
            excludedDomains.Add("core.usgovcloudapi.net");
            excludedDomains.Add("localhost");
            excludedDomains.Add("127.0.0.1");

            var includedActivities = module.IncludeDiagnosticSourceActivities;
            includedActivities.Add("Microsoft.Azure.EventHubs");
            includedActivities.Add("Microsoft.Azure.ServiceBus");

            return module;
        });

        private static IServiceCollection AddApplicationInsightsTelemetryProper(this IServiceCollection services, string instrumentationKey)
        {
            services.AddApplicationInsightsTelemetry(instrumentationKey);

            var invalidDependencyTrackingModule = services.FirstOrDefault(x => x.ImplementationType == typeof(DependencyTrackingTelemetryModule));
            services.Remove(invalidDependencyTrackingModule);
            services.AddSingleton<ITelemetryModule>(dependencyTrackingModule.Value);

            return services;
        }

        public static void Cleanup()
        {
            if (dependencyTrackingModule.IsValueCreated)
                dependencyTrackingModule.Value.Dispose();
        }
```

`Cleanup` is called after the hosting application exists...

It strongly improves application stability, however still causes failures.

It was basing on the, probably wrong, assumption that the cause for the exception below, was that ApplicationInsightsUrlFilter was accessing the already disposed `DependencyTrackingTelemetryModule`.

So I tried to prevent the disposal using `AddSingleton` override with the manual lifetime contol over the one with automatic disposal.

It basically worked (or seemed to work) for all the requests originating from the WebHost (that's a huge improvement), but as I wrote before it was failing for the requests originating from the backup loop outside of the WebHost.

```
Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.ApplicationInsightsUrlFilter.get_EndpointLeftPart()
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.ApplicationInsightsUrlFilter.IsApplicationInsightsUrlImpl(String url)
   at Microsoft.ApplicationInsights.DependencyCollector.Implementation.HttpDesktopDiagnosticSourceSubscriber.b__7_0(String evnt, Object r, Object _)
   at System.Diagnostics.DiagnosticListener.IsEnabled(String name, Object arg1, Object arg2)
   at System.Diagnostics.HttpHandlerDiagnosticListener.RaiseRequestEvent(HttpWebRequest request)
   at System.Diagnostics.HttpHandlerDiagnosticListener.HttpWebRequestArrayList.Add(Object value)
   at System.Net.Connection.StartRequest(HttpWebRequest request, Boolean canPollRead)
   at System.Net.Connection.SubmitRequest(HttpWebRequest request, Boolean forcedsubmit)
   at System.Net.ServicePoint.SubmitRequest(HttpWebRequest request, String connName)
```
