### ISSUE TITLE
Adaptive Sampling ExcludeTypes is not working

### ISSUE THREAD

**Issue by skykarthick** [Microsoft/ApplicationInsights-dotnet#618]
I'm currently using Application Insights Status Monitor for a DNN (ASP.NET) Application hosted in IIS. I saw that "Dependency" is being called >30 time for every second, which uses our daily cap (64mb per day). I was trying to user Adaptive Sampling to Exclude the telemetry type "Dependency". Therefore, I've changed the ApplicationInsights.config 

`<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
      <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
      <ExcludedTypes>Dependency</ExcludedTypes>
</Add>`

Which does not actually excludes the "Dependency" Type. Then, I've went through the tutorial https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#filtering and Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.SamplingTelemetryProcessor.cs file 

I found the bug in line 168

 //// If telemetry was excluded by type, do nothing:
            if (!this.IsSamplingApplicable(item.GetType()))
            {
//Here we're going to skip the event based on the configuration
                if (TelemetryChannelEventSource.Log.IsVerboseEnabled)
                {
                    TelemetryChannelEventSource.Log.SamplingSkippedByType(item.ToString());
                }
//After logging, it should be just return statement as far as i understood from the tutorial 
                this.Next.Process(item); //This line has to be removed, i guess. 
                return;
            }

**Comment by olaj** [comment]
Have i misunderstood this feature? I thought that the "ExcludedTypes" was to "disable sampling for these types and log everything"?

I'm looking for a way to exclude exceptions from sampling and log everything related to exceptions so i can track down rare exceptions as well.

**Comment by zakimaksyutov** [comment]
@olaj, you're correct. "ExcludesTypes" is supposed to disable sampling for these types, so everything is passed.

@skykarthick, the code snippet you pointed is correct - if telemetry type is excluded from sampling then it should be passed as is.

@skykarthick, if you want to completely disable Dependency telemetry then you can write TelemetryProcessor and don't pass Dependency telemetry:

```
    public class NullTelemetryProcessor : ITelemetryProcessor
    {
        private ITelemetryProcessor Next;

        public NullTelemetryProcessor(ITelemetryProcessor next)
        {
            this.Next = next;
        }

        public void Process(ITelemetry item)
        {
            if (item is DependencyTelemetry)
            {
                return;
            }

            this.Next.Process(item);
        }
    }
```

**Comment by zakimaksyutov** [comment]
@skykarthick, I'm closing this bug, please reopen if I misunderstood something.
