### ISSUE TITLE
WCF Services using net.tcp

### ISSUE THREAD

**Issue by haldiggs** [Microsoft/ApplicationInsights-dotnet#619]
we currently use ApplicationInsights for all of our WCF http services. We also have a few using a net.tcp endpoint for which we don't get any telemetry from. Is there any practice for this? 

Just looking for ideas. I was thinking I might just have to write manual telemetry events.

**Comment by SergeyKanzhelev** [comment]
Will this work https://github.com/Microsoft/ApplicationInsights-SDK-Labs/tree/master/WCF? 
CC: @tomasr

**Comment by SergeyKanzhelev** [comment]
please re-open if it's not what you need
