### ISSUE TITLE
[AIQL] Add function for extension/promotion of dynamic values

### ISSUE THREAD

**Issue by mamaso** [Microsoft/ApplicationInsights-dotnet#623]
Pretty sure this issue is not in the right location, but help forward it along for me :)

If I have a customDimensions dynamic { a: 1, b: 2} it can be quite cumbersome to access these properties:

`extend a = customDimensions.a, b = customDimensions.b`

I'd love to see a command in the query language that allows automatic extension of top level dynamic properties - something along the lines of `extend-dynamic customDimensions`, which would essentially evaluate to the individual `extend` statements above.

Alternately, it would be nice to have custom column support for events, rather than all properties & metrics going to the `custom*` dynamic object

**Comment by mamaso** [comment]
Alternately, it would be nice to have custom column support for events, rather than all properties & metrics going to the `custom*` dynamic object

**Comment by SergeyKanzhelev** [comment]
@kghelani, @eternovsky can you please take a look at this feature request? Any plans to simplify this expirience?

@mamaso - for some scenarios you can use [open schema](https://azure.microsoft.com/resources/samples/guidance-appinsights-openschema/). Unfortunately uploading documents with Open Schema is bit trickier. Another option is to go with OMS [Log Analytics](https://docs.microsoft.com/azure/log-analytics/log-analytics-data-sources-custom-logs)

**Comment by eternovsky** [comment]
There's a few similar things you can do off the top of my head, but nothing exactly like what you're asking for.

One option is to [mvexpand](https://docs.loganalytics.io/docs/Language-Reference/Tabular-operators/mvexpand-operator) followed by a [pivot](https://docs.loganalytics.io/docs/Language-Reference/Tabular-operators/evaluate-operator/pivot), though the pivot must (today) be the last command in a given query.

Another option is to use the [buildschema](https://docs.loganalytics.io/docs/Language-Reference/Aggregation-functions/buildschema()) function to determine the common schema of the dynamic column, and then build a query based on it. At that point though, unless the schema is very wide, it's probably easier to just manually reference the individual members. 

I would urge you to please add a request for such an operator on our [UserVoice](https://feedback.azure.com/forums/357324-application-insights/category/161991-analytics) which we rely on to help us prioritize asks.

**Comment by SergeyKanzhelev** [comment]
@mamaso I'm closing the issue for now. Please reopen if you need more information. Also post on uservoice as Evgeny suggested
