### ISSUE TITLE
Consolidate ways to set RoleName and version

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-dotnet#630]
In our project, applications run in docker containers. Applications do not control all the properties (i.e. version and some other context), such properties are controlled by 'orchestrator'. We also want applications to set RoleName automatically (it's null by default and it breaks app map).

We are interested in .net core applications (not necessarily ASP.NET Core).

Currenlty different .NET SDK flavors support different ways to set RoleName and Component Version:

-  *RoleName*: In ASP.NET (Classic) and ASP.NET Core sdk, there are different implementations of `AzureWebAppRoleEnvironmentTelemetryInitializer` ([classic](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/master/Src/WindowsServer/WindowsServer.Shared/AzureRoleEnvironmentTelemetryInitializer.cs) and [core](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/AzureWebAppRoleEnvironmentTelemetryInitializer.cs))
They initialize RoleName from `WEBSITE_SITE_NAME` env variable that (perhaps is set in Antares)

-  *Version*: In AspNet Core SDK there is [`ComponentVersionTelemetryInitializer`](https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/master/src/Microsoft.ApplicationInsights.AspNetCore/TelemetryInitializers/ComponentVersionTelemetryInitializer.cs) that works with `ApplicationInsightsServiceOptions.ApplicationVersion` that could be set in user code.

Ability set application name and version make sense for any application  - even console app and should be consistent for all .NET flavors.

# Proposal
RoleName, Component Version and arbitrary context should be set from environment variables. 
Suggested names: 
- `APPINSIGHTS_APP_NAME` for RoleName
- `APPINSIGHTS_APP_VERSION` for component version
- `APPINSIGHTS_APP_CONTEXT_<Key>`=`<Value>` for the context

Environment variables are cross-platform and cross-technology (i.e. could be used on .net fx. .net core, linux, windows, with docker or without it, for service fabric), they do not require ANY changes in user code, that simplifies configuration, especially for projects that run in multiple environments.

There are other projects that require similar features: when app does not control all context e.g  [ApplicationInsights for ServiceFabric](https://github.com/Microsoft/ApplicationInsights-ServiceFabric/blob/develop/src/ApplicationInsights.ServiceFabric/Shared/FabricTelemetryInitializer.cs)

We created [ApplicationInsights-ServiceContext](https://github.com/lmolkova/ApplicationInsights-ServiceContext/blob/master/src/Microsoft.ApplicationInsights.ServiceContext/ServiceContextTelemetryIntitializer.cs) and will be releasing it for our users, however, we believe this functionality belongs to the base AI SDK.

**Comment by lmolkova** [comment]
I also suggest that all other AI SDKs should have the same feature to have a consistent story.

/cc: @SergeyKanzhelev @Dmitry-Matveev @dnduffy

**Comment by karolz-ms** [comment]
Environment variables are the standard mechanism to pass configuration information to cloud and/or contenerized applications. Docker, K8s etc. have direct support for passing them to containers. In many cases it is considered best practice to use env. variables e.g. https://12factor.net/config https://thenewstack.io/best-practices-for-developing-cloud-native-applications-and-microservice-architectures/  It makes a lot of sense for AI SDK to support them natively. We can start with what @lmolkova proposed here and expand as necessary.

**Comment by lmolkova** [comment]
@SergeyKanzhelev brought a couple of interesting points:

1) How is this problem solved in Zipkin or Opentracing?
To the best of my knowledge, Zipkin does not have cross-platform, generic configuration, it supports e.g. getting application name through spring attributes.
Opentracing does not define application name or version tags and leaves it up to users.

2) [Azure Instance Metadata Service](https://github.com/harijayms/Azure-Instance-Metadata/blob/master/Instance-Metadata.md)
Provides extensive information about VM.
While this may be useful in many cases, it does not provide any information about services/apps that run in VM.

**Comment by SergeyKanzhelev** [comment]
My worry is that we will invent the new set of environment variable names that nobody uses and nobody will know about. And setting those variables will be in hand of developers (instead of a platform itself) and will be error-prone.

This is why I'm asking for the anyhow standard names as well as some platform-provided identity providers.

So I'd suggest to make names non-AI specific as well as understand at least couple platforms that will support those out of the box.


@davidebbo, if we will define variable for the telemetry's application name and version - do you think you can set them in KuDu alongside the `HOST_NAME` and `COMMIT_ID`?

**Comment by davidebbo** [comment]
@SergeyKanzhelev I'm probably missing some context around this. Is this about Kudu for Linux/Containers, or regular Kudu on Windows?

**Comment by SergeyKanzhelev** [comment]
In general. Today if you want to configure the application name, role name and version for the telemetry sent by your application you need to change config file. 

Proposal is to expose some predefined environment variables that customer (or better the platform itself) can set so SDK will pick it up and associate with the telemetry.

My worry is that platforms will not adopt those names and customers will need to configure names of environment variable to read (say `COMMIT_ID` should be used as application version) or will set those manually which is error prone.

So the question is - for Azure web apps - do you think you'd adopt names we may define or you'd prefer to not tight the platform to those names?

**Comment by davidebbo** [comment]
In App Service, anything you set as an App Setting (in Portal or API) becomes an environment variable at runtime. So if there are new env variables that App Insights responds to, I would think they those can be set as App Settings without the platform having specific knowledge of them.

But I'm probably misunderstanding things still...

**Comment by SergeyKanzhelev** [comment]
@davidebbo the question is what it will take to set those variables out of the box? Today Application Insights SDK already has Web Apps specific code that takes data from `WEBSITE_HOSTNAME` and we thinking of getting the version from `COMMIT_ID`. If we define generic name for application name and other telemetry identity properties - do you think Azure Web App can start set those out of the box?

**Comment by paulomorgado** [comment]
I would go with `APPINSIGHTS_ROLE_NAME` instead of `APPINSIGHTS_APP_NAME` because they are different concepts in application insights.

**Comment by trask** [comment]
Hi! We want to add environment variable support for cloud role name in Java also. I like `APPINSIGHTS_ROLE_NAME`.

@SergeyKanzhelev I understand your concern, but it seems useful to have an AI-specific environment variable that will always win over general platform environment variables. And this allows us to move forward with providing environment variable support for now, while still providing platform environment variable support if/when they exist (e.g. falling back to `WEBSITE_SITE_NAME`).

Let me know what you think! Thanks.

**Comment by lmolkova** [comment]
I'm ok with `APPINSIGHTS_ROLE_NAME`

**Comment by SergeyKanzhelev** [comment]
Fine by me
