### ISSUE TITLE
Debug snapshots no longer being captured after setting up deployment slots and auto swap

### ISSUE THREAD

**Issue by xt0rted** [Microsoft/ApplicationInsights-dotnet#632]
This is part of a larger group of issues I'm having, but I wanted to post this here in case there were any known issues with this setup. (ref: https://github.com/projectkudu/kudu/issues/2583)

I setup debug snapshots on my site and they were running ok. I had a number of them created and was able to browser them & download them. Then this past Monday I setup a deployment slot and auto swap. After setup I found that the app insights site extension was missing from my new slot so I installed that. At that point all of the settings between my two slots were the same.

I've had a couple exceptions thrown since then and none of them had snapshots saved. Browsing the exception on the portal gives me the link to the docs on setting them up, but nothing is captured.

My config is as follows:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
    <TelemetryProcessors>
        <Add Type="Microsoft.ApplicationInsights.SnapshotCollector.SnapshotCollectorTelemetryProcessor, Microsoft.ApplicationInsights.SnapshotCollector">
            <!-- The default is true, but you can disable Snapshot Debugging by setting it to false -->
            <IsEnabled>true</IsEnabled>
            <!-- Snapshot Debugging is usually disabled in developer mode, but you can enable it by setting this to true. -->
            <!-- DeveloperMode is a property on the active TelemetryChannel. Default: false -->
            <IsEnabledInDeveloperMode>false</IsEnabledInDeveloperMode>
            <!-- How many times we need to see an exception before we ask for snapshots. Default: 5 -->
            <ThresholdForSnapshotting>1</ThresholdForSnapshotting>
            <!-- The maximum number of snapshots we collect for a single problem. Default: 3 -->
            <MaximumSnapshotsRequired>3</MaximumSnapshotsRequired>
            <!-- The maximum number of problems that we can be tracking at any time. Default: 50 -->
            <MaximumCollectionPlanSize>50</MaximumCollectionPlanSize>
            <!-- How often to reset problem counters. Default: 06:00:00 -->
            <ProblemCounterResetInterval>06:00:00</ProblemCounterResetInterval>
            <!-- The maximum number of snapshots allowed in one minute. Default: 2 -->
            <SnapshotsPerMinuteLimit>2</SnapshotsPerMinuteLimit>
            <!-- The maximum number of snapshots allowed per day. Default: 50 -->
            <SnapshotsPerDayLimit>50</SnapshotsPerDayLimit>
        </Add>
    </TelemetryProcessors>
</ApplicationInsights>
```

**Comment by pharring** [comment]
@xt0rted Thanks for the report. However, this isn't the right place for Snapshot Debugger support. Please use snapshothelp@microsoft.com for support. Let them know your application's instrumentation key and they'll be able to check the back-end logs. There's also a troubleshooting section in the docs you mentioned.

**Comment by xt0rted** [comment]
To follow up on this, it looks like snapshots was working correctly but the threshold setting wasn't what was expected. In my case it was set to 1, which seemed to indicate it'd snapshot the first time the exception happened. What this really means is the second occurrence will have a snapshot taken. My recent exceptions only happened once each so no snapshot was taken, while my old exceptions happened multiple times.
