### ISSUE TITLE
TrackMetric's description recommends to use MetricManager

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-dotnet#635]
/// <summary>
        /// Obsolete - use <see cref="MetricManager"/> to send metrics.
        /// </summary>

        /// <summary>
        /// Send a <see cref="MetricTelemetry"/> that represents aggregated metric data.
        /// Create a separate <see cref="MetricTelemetry"/> instance for each call to <see cref="TrackMetric(MetricTelemetry)"/>.
        /// Consider using <see cref="MetricManager"/> to send metrics with reduced bandwidth.
        /// </summary>

**Comment by MS-TimothyMothra** [comment]
I had a customer also report this issue #658.
I've reached out to @macrogreg for some clarification.

**Comment by MS-TimothyMothra** [comment]
confirmed with @macrogreg we can remove this.
