### ISSUE TITLE
High memory usage on invalid instrumentationkey

### ISSUE THREAD

**Issue by nphmuller** [microsoft/ApplicationInsights-dotnet#639]
On Microsoft.ApplicationInsights.AspNetCore v2.1.1

1. `dotnet new api`
2. In Visual Studio: Right-click project -> Add -> Add Application Insights

Calling the api produces the following output:
`Application Insights Telemetry (unconfigured): { ... }`
Memory usage is fine. Doesn't grow hard when calling the api multiple times.

3. In Program.cs, change `UseApplicationInsights()` to `UseApplicationInsights("invalid_guid").

Calling the api produces the following output:
`Application Insights Telemetry: { ... }`
Memory usage grows pretty hard when calling the api multiple times. In the memory snapshot there are a lot of extra objects with references to ApplicationInsights.

Expected:
When the guid is invalid (or the appinsights endpoint cannot be reached with a valid guid), start ApplicationInsights in Unconfigured mode. Or at least don't buffer all the telemetry.

See: https://github.com/nphmuller/AppInsightsMemory for an easy repro.

**Comment by zakimaksyutov** [comment]
@nphmuller, thank you for reporting the issue and providing the full repro!
