### ISSUE TITLE
 Infinite loop if input is string.empty in SamplingScoreGenerator

### ISSUE THREAD

**Issue by juliusl** [Microsoft/ApplicationInsights-dotnet#641]
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/c06a87bfb6ac4d28129f6e3da7c6c0f7e02d623c/src/ServerTelemetryChannel/Managed/Shared/Implementation/SamplingScoreGenerator.cs#L39-L47

I propose changing the null check to `if (string.IsNullOrEmpty(input))`.

**Comment by SergeyKanzhelev** [comment]
We'd appreciate if you can send a PR. Thanks for reporting
