### ISSUE TITLE
EnableSystemDiagnosticsTracing() makes telemetry initializers behave differently, they're now on same thread as web request

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/ApplicationInsights-dotnet#653]
## Prerequisites:

1. ASP.NET Web API 2.2+
2. AI 2.0+
3. Custom `ITelemetryInitializer` added via `TelemetryConfiguration.Active.TelemetryInitializers.Add(initiazlier)`

## Scenario 1:
1. Do not have `httpConfig.EnableSystemDiagnosticsTracing()` enabled

##  Behavior:
1. Incoming web request `ValuesController.Get()` and telemetry initializer `MyTelemetryInitializer.Initialize(ITelemetry)` are on different threads, `Thread.CurrentThread.ManagedThreadId` are different, e.g. 6 and 10.
2. `AsyncLocal<HttpMessageRequest>` set earlier is `null`, `CallContext.LogicalGetData()` returns `null`

## Scenario 2:
1. Do have `httpConfig.EnableSystemDiagnosticsTracing()` enabled

##  Behavior:
1. Incoming web reques `ValuesController.Get()` and telemetry initializer `MyTelemetryInitializer.Initialize(ITelemetry)` are on same thread, `Thread.CurrentThread.ManagedThreadId` is same, e.g. 6.
2. `AsyncLocal<HttpMessageRequest>` set earlier returns `value`, `CallContext.LogicalGetData()` returns `value`

## Question:

Can you please explain the difference in behavior?

## Version Info 
SDK Version: Microsoft.ApplicationInsights version 2.1.0, Microsoft.ApplicationInsights.Web version 2.1.0
.NET Version: .NET 4.6.2
How Application was onboarded with SDK (VisualStudio/StatusMonitor/Azure Extension): VS 2017 15.4.4
OS: Windows 10 FCU
Hosting Info (IIS/Azure WebApps/etc): IIS Express

See also https://github.com/simpleinjector/SimpleInjector/issues/484

**Comment by abatishchev** [comment]
Any response, please?

**Comment by abatishchev** [comment]
Any response, please?

**Comment by SergeyKanzhelev** [comment]
@lmolkova @MS-TimothyMothra  can you please take a look?

**Comment by lmolkova** [comment]
@abatishchev, ApplicationInsights does not own `Httpconfiguration.EnableSystemDiagnosticsTracing` [API](https://msdn.microsoft.com/en-us/library/system.web.http.httpconfigurationtracingextensions.enablesystemdiagnosticstracing(v=vs.118).aspx), it's part of ASP.NET.

In general, you should not expect controller and HttpModule.End_Request (AppInsights track requests with HTTP Module) to happen on the same thread. On the small load, it could accidentally be the same thread, but under the load, CLR may assign another thread.

Behavior for scenario1 you observe typically happens when IIS switches between managed and native threads: i.e. new thread is assigned, all execution context is lost.

Please also note that AppInsights version you are using is out of date (2.5 is the latest one). If you intend to use custom telemetry initializer to correlate telemetry, AppInsights Web SDK 2.4 does it out of the box.

**Comment by abatishchev** [comment]
@lmolkova thanks for your reply!

>On the small load, it could accidentally be the same thread, but under the load, CLR may assign another thread

I was surprised that I was able consistently to reproduce the differences in the behaviors. I didn't try under heavier load though. But suspect this is intentional rather than coincidence.

>2.5 is the latest one

I'm using [the latest stable](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/) from nuget which is 2.4 as of now

> On the small load, it could accidentally be the same thread, but under the load, CLR may assign another thread

Please point out where I should start reading from?

P.S.
What I'd love to see is a repo of reference implementations (like what AAD does). Is there one already out there by chance?

**Comment by lmolkova** [comment]
@abatishchev you can refer to TPL lib docs:
- https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl
- https://msdn.microsoft.com/en-us/library/system.threading.tasks.taskscheduler(v=vs.110).aspx

you can find .NET core sources here 
- github.com/dotnet/corefx
- github.com/dotnet/coreclr

.NET Desktop framework sources here 
- http://referencesource.microsoft.com/

I'm closing this issue as it is not related to ApplicationInsights

**Comment by abatishchev** [comment]
Oh, sorry, I quoted wrong part of your response :))

>If you intend to use custom telemetry initializer to correlate telemetry, AppInsights Web SDK 2.4 does it out of the box.

Please point out where I should start reading from?

**Comment by abatishchev** [comment]
>ApplicationInsights does not own Httpconfiguration.EnableSystemDiagnosticsTracing API, it's part of ASP.NET.

Unfortunately this means a dead-end since the ASP.NET team won't help me investigating anything related to "legacy" ASP.NET Web API.

**Comment by lmolkova** [comment]
I think the best place is to read about correlation is here: https://docs.microsoft.com/en-us/azure/application-insights/application-insights-correlation

Under the hood, AppInsights use [Activity](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md) to hold trace context and different notification mechanisms (depending on platform and available library instumentation)
- [DiagnosticSource](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md)
- EventSource
- Runtime instrumentation

If you are interested in referenced implementation, please check
- ASP.NET: [module](https://github.com/aspnet/Microsoft.AspNet.TelemetryCorrelation), [AppInsights listener](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/ca3f0a6d418b056ed04e894d174516f0068ee2af/Src/Web/Web.Net45/AspNetDiagnosticTelemetryModule.cs)
- Http (.NET Core) outgoing calls tracking with DiagnosticSource: [instrumentation](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs), [listener](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/e28d4a81f39a287112a8704d486664d86dd8d7c8/Src/DependencyCollector/Shared/Implementation/HttpCoreDiagnosticSourceListener.cs)
- Runtime instumentation (.NET Framework) https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/ProfilerRuntimeInstrumentation.cs

you may find other instrumentation sites in ASP.NET Core, Azure service client libraries.
Check the https://github.com/Microsoft/ApplicationInsights-dotnet-server repo for ASP.NET
