### ISSUE TITLE
Ensure Environment read permissions 

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#657]
There are several places in SDK where Environment variables are read without wrapping in try..catch. If the access to ENV is denied, this could throw exceptions.
Opening an issue to track the work of identifying all the places where ENV is read, and ensuring its handled properly.
(or move all ENV access to common helper).

**Comment by mastorm** [comment]
I want to get my hands on the issue. Is there anything specifically that I should have in mind during implementation?

**Comment by eddynaka** [comment]
Hi all, is this issue still open?

**Comment by cijothomas** [comment]
Yes. The following PR would have fixed it, but it now has merge conflicts. If one can resurrect it, or create a new PR that'd be great!
https://github.com/microsoft/ApplicationInsights-dotnet/pull/1234/files
