### ISSUE TITLE
Obsolete warning on TelemetryClient.TrackMetric

### ISSUE THREAD

**Issue by wijays** [Microsoft/ApplicationInsights-dotnet#658]
TelemetryClient.TrackMetric has the warning "Obsolete - use Microsoft.ApplicationInsights.Extensibility.MetricManager to send metrics".

TelemetryClient has many such warnings and notes in comments however MetricManager is internal.

Thanks

**Comment by MS-TimothyMothra** [comment]
Hi @wijays,
We apologize for the confusion. 
MetricManager was a new feature that was being worked on internally, but that documentation slipped out prematurely. 

I'm tracking this at issue #635.
I'm going to close this issue for now. Please feel free to continue the conversation there.

Thank you
