### ISSUE TITLE
Metric data is being altered

### ISSUE THREAD

**Issue by a-vishar** [microsoft/ApplicationInsights-dotnet#659]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1.  Submit a metric with a metric property which is DateTime formatted like this "yyyy-MM-dd HH:mm:ss"

##  Actual Behavior
Value of metric property in AppInsights is "2017-11-24T18:35:01.0000000Z"

## Expected Behavior
Metric property should be in this format "yyyy-MM-dd HH:mm:ss"

## Version Info 
SDK Version : 2.4
.NET Version :	 4.6.2						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : VisualStudio
Hosting Info (IIS/Azure WebApps/ etc) : Azure

**Comment by MS-TimothyMothra** [comment]
Need to investigate this with a small test app.
Need to confirm that custom formatting is transmitted in telemetryitem (Fiddler).

We suspect that our backend is parsing this string and storing as a datetime. 
If confirmed, we would need to look into changing that.

Work-around is to format your datetime at query time.

**Comment by SergeyKanzhelev** [comment]
@MS-TimothyMothra were you able to repro this?
