### ISSUE TITLE
Add default SDK payload properties to the heartbeat feature

### ISSUE THREAD

**Issue by d3r3kk** [Microsoft/ApplicationInsights-dotnet#666]
As stated in the original issue (#628) we would be providing specific default fields to the heartbeat feature that customers can turn off as desired. This issue is to track the addition of these default properties and allow for discussion of specific details as necessary.

**Comment by MS-TimothyMothra** [comment]
Hi @d3r3kk,
I see that there is a related PR that's already been merged.

Is there any more work to do for this issue, or is it safe to close this? :)

**Comment by d3r3kk** [comment]
The work related to this issue is complete for this repo (work continues in -dotnet-server repo, but other issues are tracking that).
