### ISSUE TITLE
Proposal for enhanced Exception Telemetry.

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#679]
I'm sharing this proposal for the team to discuss.
I'm advocating for Option 1 below, but I've described some slight alternatives.

**Scenario**
If a customer writes custom Exception classes for their application, we do not have support for the extra details they may capture in these custom implementations. This affects every place a custom exception could be caught, as an application must know how to create telemetry.

Customers could override the ToString or Message property and include all properties, but I feel this is not a good solution. This would create Exceptions with extremely verbose messages and would be difficult to query in Analytics.

I want to propose the addition of a 1st party solution in the BaseSDK to help users with this scenario.
This would coincide with our SCANDIUM plans to introduce more auto-collection of Exceptions.

**Workaround**
A customer can implement their own Interface and TelemtryInitializer to extract properties from Exceptions.

**Option 1**
New interface: ITelemetryException
Requires one method: GetTelemetryProperties() returns Dictionary<string, string>.
```
public interface ITelemetryException
{
    Dictionary<string, string> GetTelemetryProperties();
}
```

Customers will implement this method, returning only the properties they want to be included in customProperties.
We will check for this interface implementation in [TelemetryClient.TrackException()](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/a0c340ab7c415260cd2d1961c092dafd1858909e/src/Microsoft.ApplicationInsights/TelemetryClient.cs#L258).

- Pro: One method for customers to implement per custom Exception.
- Pro: Gives customers control over how to log Exceptions.
- Pro: Works with unhandled exceptions!
- Con: Creates an extra maintenance point for customers as custom implementations evolve.
- Con: Slight perf impact as we have to check for implementation.

**Option 1-B**
We implement a TelemetryExceptionInitializer to check for implementation instead of doing the work in TelemetryClient.TrackException().
This is the option that a customer could do for themselves.

- Pro: Customers can enable/disable Initializer as needed to save performance.
- Con: Extra configuration for customers. 

**Option 2**
New attribute: TelemetryProperty
Requires one attribute which customers can add to any Property in any class.

Customers must supply a string title for the customProperty collection.
We will check any place a customer could pass in an object for this property, and call ToString() to collect the value.
Example: `TrackEvent(string message, params object[] objects)`

- Pro: Very simple for customers to implement, can offer enriched telemetry collection across an entire app.
- Con: High perf impact as we would need to perform reflection everywhere our SDK could collect an object.
- Con: Doesn't fit with current patterns in SDK today as there are limited places where a customer-defined object would get into an ITelemetry Object.

**Comment by MS-TimothyMothra** [comment]
While working on a different project, I discovered we don't have an offering for this scenario.
It's very easy to implement a workaround from a customer's perspective (described above), but it would be just as easy for us to implement and offer to all customers.

**Comment by SergeyKanzhelev** [comment]
If I understand it correctly - scenario can be achieved today. You can implement telemetry initializer that will extract additional properties from `ExceptionTelemetry.Exception` and put it into `Properties`. Am I missing something here?

Specifically for exception - there is a side issue https://github.com/Microsoft/ApplicationInsights-dotnet/issues/627. SDK doesn't allow to override any fields or stack frames of an exception telemetry. 

That's said - we have the same problem for Http calls when in order to get some additional parameters you may need access to the http request object. See discussion here https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/343 We also have a custom solution for logger: https://github.com/Microsoft/ApplicationInsights-dotnet-logging/pull/111 So more generic approach here may be helpful to the overall SDK.

**Comment by SergeyKanzhelev** [comment]
Do you agree that this is more generic issue to be addressed? Or I misunderstood the intent here?

**Comment by MS-TimothyMothra** [comment]
> If I understand it correctly - scenario can be achieved today. You can implement telemetry initializer that will extract additional properties from ExceptionTelemetry.Exception and put it into Properties. Am I missing something here?

You are correct, this is exactly the workaround that customers can do today.
I feel like it could be a service to our customers if we did this ourselves and documented the scenario.

>That's said - we have the same problem for Http calls when in order to get some additional parameters you may need access to the http request object.

I've noticed this same problem with Http calls. 
See also https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/747 and https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/587

Providing a generic solution for the full SDK would be excellent but I think this is a separate discussion.

**Comment by zakimaksyutov** [comment]
The scenario makes sense. Proposed solutions touch public API/introduce new patterns and must be implemented not only in .NET SDK but also in Java, Node.JS and other SDKs. Without it, though bringing value to .NET only customers, this might create confusion for customers with heterogeneous environments.

So, one advantage of TelemetryInitializer approach is that it is available in all AI SDKs.
