### ISSUE TITLE
StopOperation reports telemetry that is not in current scope

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet#686]
see https://github.com/Microsoft/ApplicationInsights-dotnet/issues/644#issuecomment-353765515.

```C#
var firstOperation = telemetryClient.StartOperation<DependencyTelemetry>("task 1");
var firstTask = RunMyTaskAsync();

var secondOperation = telemetryClient.StartOperation<DependencyTelemetry>("task 2");
var secondTask = RunMyTaskAsync();

await firstTask;

// Must not be tracked, but it is
telemetryClient.StopOperation(firstOperation); 

await secondTask;
```

>  tried running the above example with firstOperation and secondOperation, and for me telemetry for task1 is still logged (after logging an error "Operation to stop does not match the current operation"). Looking at the code for OperationHolder.Dispose() it seems like the return statement on line 86 only returns from ActivityExtensions.TryRun(), but not from Dispose(). isActivityAvailable is true, so the second return is never called either, and the operation gets logged successfully. 

> Even if telemetry is reported, some of its properties may be initialized from the `System.Diagnostics.Activity` (.NET tracing context that is used by AppInsights) during `Track()` by SDK or custom TelemetryIntitializer. As the `Activity.Current` is no longer correct and represents another operation, so reported telemetry under some conditions will be incorrect.

**Comment by MS-TimothyMothra** [comment]
This is affecting some customers;

> AI (Internal): Operation to stop does not match the current operation.


- #693

- [Unexpected Trace “AI (Internal): Operation to stop does not match the current operation”](https://social.msdn.microsoft.com/Forums/en-US/130c9038-8a08-4b8c-b9cf-7ab6b6caf4ea/unexpected-trace-ai-internal-operation-to-stop-does-not-match-the-current-operation?forum=ApplicationInsights)


Do we have a work around to provide customers?
@Dmitry-Matveev has suggested disabling [Diagnostics Module](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Tracing/DiagnosticsTelemetryModule.cs).

**Comment by lmolkova** [comment]
@MS-TimothyMothra 
the only known reason for it is when StartOperation/StopOperation are called incorrectly from the user code (e.g. see example in the issue description).
More on this [here](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking#parallel-operations-processing-and-tracking)

For now, the only place Start/StopOperation are called by the SDK is [.NET Core Http listener](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/e28d4a81f39a287112a8704d486664d86dd8d7c8/Src/DependencyCollector/Shared/Implementation/HttpCoreDiagnosticSourceListener.cs).  
If we would know for sure the problem is there, we can dig more into this and see if there is an issue with the listener.

The potential impact of this issue: wrong correlation that is hard to notice. The trace helps to understand that something is wrong, so I find it useful. 

I'll get in touch with the customer in #693 to help narrow the root cause.

**Comment by nerdile** [comment]
If other folks are landing here because their events are not showing up, and they are seeing the trace "Operation to stop does not match the current operation. Telemetry is not tracked." - make sure that you are not overwriting the operation.Telemetry.Id field between StartOperation and StopOperation.

And if your failure events are not showing up in AppInsights, make sure that anytime you set Success = false, you also set a ResponseCode value.  Otherwise, the service seems to silently drop these events.

In hindsight, it seems obvious, but as someone with an existing request correlation system, trying to onboard to AppInsights for the first time, it seemed natural to put my own existing Request ID into that field.
