### ISSUE TITLE
SQL commands not reported with Dapper ORM

### ISSUE THREAD

**Issue by dbruning** [Microsoft/ApplicationInsights-dotnet#687]
Hi,

I have an ASP.NET webapi project hosted in IIS. Application Insights is installed and generally working well, however it won't show me the text of the sqlquery being generated. 

I'm using the [Dapper](https://github.com/StackExchange/Dapper) micro ORM. Do I need to do anything special to make this work with Dapper, or does Application Insights hook the CLR at a lower level so it should just work?

##  Actual Behavior
"Command" of the SQL dependency entry in the AI dashboard just shows tcp:<ipaddress> | <database_name>

## Expected Behavior
"Command" of the SQL dependency entry in the AI dashboard should show the full text of the SQL query

## Version Info 
SDK Version : Microsoft.ApplicationInsights v2.4.0 (Nuget)
.NET Version :	Application targets v4.6, IIS server has v4.7 installed 						
How Application was onboarded with SDK: VisualStudio
OS : Windows Server 2012
Hosting Info: IIS

## Bonus information
I have the following stack trace from a Raygun entry for a failed SQL request:

"Error": {
          "Data": {
               "HelpLink.ProdName": "Microsoft SQL Server",
               "HelpLink.ProdVer": "13.00.1728",
               "HelpLink.EvtSrc": "MSSQLServer",
               "HelpLink.EvtID": "8115",
               "HelpLink.BaseHelpUrl": "http://go.microsoft.com/fwlink",
               "HelpLink.LinkId": "20476"
          },
          "ClassName": "System.Data.SqlClient.SqlException",
          "Message": "Arithmetic overflow error converting numeric to data type numeric.\r\nArithmetic overflow error converting numeric to data type numeric.",
          "StackTrace": [
               {
                    "LineNumber": 94,
                    "ClassName": "System.Data.SqlClient.SqlConnection",
                    "MethodName": "OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)"
               },
               {
                    "LineNumber": 380,
                    "ClassName": "System.Data.SqlClient.TdsParser",
                    "MethodName": "ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)"
               },
               {
                    "LineNumber": 2684,
                    "ClassName": "System.Data.SqlClient.TdsParser",
                    "MethodName": "TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)"
               },
               {
                    "LineNumber": 64,
                    "ClassName": "System.Data.SqlClient.SqlDataReader",
                    "MethodName": "TryConsumeMetaData()"
               },
               {
                    "LineNumber": 60,
                    "ClassName": "System.Data.SqlClient.SqlDataReader",
                    "MethodName": "get_MetaData()"
               },
               {
                    "LineNumber": 227,
                    "ClassName": "System.Data.SqlClient.SqlCommand",
                    "MethodName": "FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)"
               },
               {
                    "LineNumber": 1505,
                    "ClassName": "System.Data.SqlClient.SqlCommand",
                    "MethodName": "RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)"
               },
               {
                    "LineNumber": 383,
                    "ClassName": "System.Data.SqlClient.SqlCommand",
                    "MethodName": "RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)"
               },
               {
                    "LineNumber": 25,
                    "ClassName": "System.Data.SqlClient.SqlCommand",
                    "MethodName": "RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)"
               },
               {
                    "LineNumber": 103,
                    "ClassName": "System.Data.SqlClient.SqlCommand",
                    "MethodName": "ExecuteReader(CommandBehavior behavior, String method)"
               },
               {
                    "LineNumber": 1589,
                    "ClassName": "Dapper.SqlMapper+<QueryImpl>d__61`1",
                    "FileName": "D:\\Dev\\dapper-dot-net\\Dapper NET40\\SqlMapper.cs",
                    "MethodName": "MoveNext()"
               },
               {
                    "LineNumber": 119,
                    "ClassName": "System.Collections.Generic.List`1",
                    "MethodName": ".ctor(IEnumerable`1 collection)"
               },
               {
                    "LineNumber": 20,
                    "ClassName": "System.Linq.Enumerable",
                    "MethodName": "ToList[TSource](IEnumerable`1 source)"
               },
               {
                    "LineNumber": 1479,
                    "ClassName": "Dapper.SqlMapper",
                    "FileName": "D:\\Dev\\dapper-dot-net\\Dapper NET40\\SqlMapper.cs",
                    "MethodName": "Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)"
               },

**Comment by cijothomas** [comment]
To get the full sql query, please install Status Monitor or Azure extension if hosted on Azure Web Apps.
Link with more info:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-monitor-performance-live-website-now

**Comment by dbruning** [comment]
thanks @cijothomas . I forgot to say: I already had Status Monitor installed & had just updated it to latest version.

**Comment by cijothomas** [comment]
I see. Status Monitor works at CLR instrumentation level.
Lets  try this:
1. Can you check the sdk version from the collected sql dependency? (it should be rddp if StatusMonitor was indeed working) If this is not, rddp (it would be rddf) - please try to re-install SM/Restart IIS to make sure SM has taken effect.
2. Do you know the exact call (done by Dapper) for which you are missing full query info? 
The following shows all the methods instrumented: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/ProfilerRuntimeInstrumentation.cs

**Comment by dbruning** [comment]
The SDK version is rddf:2.4.1-1362
I re-started IIS, still that same SDK version in a SQL dependency collected after the reboot.
My app has the Application Insights nuget package installed & configuration in web.config (and ApplicationInsights.config), so perhaps I am missing some configuration there? Are there special modules that need to be loaded for SQL dependency tracking?

Regarding Dapper: the stack includes this entry:
```
"LineNumber": 103,
"ClassName": "System.Data.SqlClient.SqlCommand",
"MethodName": "ExecuteReader(CommandBehavior behavior, String method)"
```
.. which looks like it would be covered by this decoration from the link you provided:
```
            // Decorate Sql ExecuteReader(CommandBehavior), 2 params(+this)
            Functions.Decorate(
                "System.Data",
                "System.Data.dll",
                "System.Data.SqlClient.SqlCommand.ExecuteReader",
                sqlCallbacks.OnBeginForThreeParameters,
                sqlCallbacks.OnEndForThreeParameters,
                sqlCallbacks.OnExceptionForThreeParameters,
                isStatic: false);
```

**Comment by cijothomas** [comment]
Ok - since the version if 'rddf' - this indicates profiler is not installed correctly due to some reason. The link above for method decorations are applicable only if profiler got installed correctly (leading to version being 'rddp-').

We need to find out why SM installation is failing. Do you have any other profiler tools in the machine? new relic/other profiler tools?

**Comment by cijothomas** [comment]
@iusafaro Whats the easiest way to understand about status monitor installation?

**Comment by cijothomas** [comment]
Get-ItemProperty 'hklm:\\SYSTEM\\CurrentControlSet\\Services\\W3SVC'

**Comment by dbruning** [comment]
`Get-ItemProperty 'hklm:\SYSTEM\CurrentControlSet\Services\W3SVC'
`
...gives these results: 

```
Type               : 32
Start              : 2
ErrorControl       : 1
ImagePath          : C:\Windows\system32\svchost.exe -k iissvcs
DisplayName        : @%windir%\system32\inetsrv\iisres.dll,-30003
DependOnService    : {WAS, HTTP}
ObjectName         : LocalSystem
Description        : @%windir%\system32\inetsrv\iisres.dll,-30004
RequiredPrivileges : {SeAssignPrimaryTokenPrivilege, SeAuditPrivilege, SeBackupPrivilege, SeChangeNotifyPrivilege...}
Environment        : {COR_ENABLE_PROFILING=1, COR_PROFILER={324F817A-7420-4E6D-B3C1-143FBED6D855},
                     MicrosoftInstrumentationEngine_Host={CA487940-57D2-10BF-11B2-A3AD5A13CBC0}}
FailureActions     : {255, 255, 255, 255...}
PSPath             : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W3SVC
PSParentPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services
PSChildName        : W3SVC
PSDrive            : HKLM
PSProvider         : Microsoft.PowerShell.Core\Registry
```

**Comment by dbruning** [comment]
I've been working on some other unrelated Application Insights stuff (some requests weren't being skipped because I'm using an OWIN pipeline) and now I'm getting the SQL command text coming through in my dependencies. I suspect that some combination of re-releasing, recycling the site/IIS or rebooting the server fixed the issue. Thanks for your help.
