### ISSUE TITLE
Couldn't find type for class Microsoft.ApplicationInsights.TraceListener.ApplicationInsightsTraceListener

### ISSUE THREAD

**Issue by FilipCotan** [microsoft/ApplicationInsights-dotnet#688]
## Repro Steps
I have project A and project B. Project A is a SOAP service in which I import project B as a DLL reference. 
Project A has Application Insights up and running. At some point, in project A, I call a function from project B and in that function I have a line of code that looks like
`Debug.WriteLine("output message");`. 

##  Actual Behavior
An error is thrown: `"Couldn't find type for class Microsoft.ApplicationInsights.TraceListener.ApplicationInsightsTraceListener, Microsoft.ApplicationInsights.TraceListener."`

**Note:** I don't want to reference application insights in project B.

Is it possible NOT to collect data from _System.Diagnostics_ or something like this? 

**Note:** This happens even if Application Insights is disabled.

**Comment by MS-TimothyMothra** [comment]
It sounds like B is trying to use the TraceListener resource before A has initialized it.

Can you provide us a small repro app so we can investigate this further?

**Comment by Dmitry-Matveev** [comment]
@PhilipCotan , if scenario suggested by @MS-TimothyMothra above is correct, you may have a workaround - trace something from A before you invoke B, so AI is loaded into the memory beforehand.

**Comment by PhilipCotan** [comment]
@Dmitry-Matveev thanks for your suggestion. I'll try it and I'll let you know whether it works or not. 
Cheers.

**Comment by j0nimost** [comment]
Any follow up to this?
