### ISSUE TITLE
Practical difference between trace and event telemetry

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [Microsoft/ApplicationInsights-dotnet#695]
What is the practical difference between sending a log message as a trace or event telemetry?  Events can carry metric information (ISupportMetrics which isn't an interface for traces).  Otherwise, the payload sent to Insights is basically the same. The Microsoft [documentation](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics) says the traces are for diagnostic logs while events are for user/other actions.  But are there practical differences in how tooling (either in the Insights GUI or the SDK) handle traces versus events?  For example, if traces are for logs which have varying free text in the message are traces designed to handle "free text searching" better?  Do we get different aggregations with events than what could be possible for traces.  And so on....

**Comment by MS-TimothyMothra** [comment]
The documentation you referenced is a suggested best practice. 
There aren't different aggregations or searching optimizations across telemetry types.
The schema, however, is different. For example; Trace items allow for longer text than event will.

Event Name has a max length of 512 characters
https://docs.microsoft.com/en-us/azure/application-insights/application-insights-data-model-event-telemetry

Trace Message has a max length of 32768
https://docs.microsoft.com/en-us/azure/application-insights/application-insights-data-model-trace-telemetry

**Comment by SergeyKanzhelev** [comment]
Events are also pre-configured for sampling limits independently from the diagnostics telemetry by default. So requests and log messages may be sampled out, but events still being send. We also minimize scenarios when events are collected somewhat automatically. Like from logging adaptor. They are designed for manual tracking of important, often business related events.
