### ISSUE TITLE
Provide a useful mapping between .NET runtime versions and .NET versions to improve useability of the heartbeat property 'runtimeFramework'.

### ISSUE THREAD

**Issue by d3r3kk** [microsoft/ApplicationInsights-dotnet#699]
We have added the heartbeat feature to the SDK in 2.5.0. Now that we have the information we need to provide some added value to the heartbeat feature regarding the runtimeFramework field.

See a discussion of this in PR #681 

Note: We gather the currently running framework version based on the assembly containing the 'object' type.

What we need to do is map the runtime version with the current version of the .NET Framework, Standard, or Core, version. We want to provide this mapping to help discover problems with different versions of the frameworks behaving differently and causing unexpected results for our customers. This mapping could be in the documentation somewhere or we could add some code to the `BaseDefaultHeartbeatPropertyProvider` class.

SDK Version : 2.6.0-beta1
.NET Version : all

**Comment by cijothomas** [comment]
reopened as this was never fixed.

**Comment by cijothomas** [comment]
no longer needed as 3.0 onwards, .net core reports correct framework version string.
