### ISSUE TITLE
Heartbeat provider custom metric does not include the boolean health field.

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-dotnet#705]
The custom metric contains fields as key value pairs. Overall value of metric is derived from the health field of individual items. But its not possible to tell which field caused unhealthiness.

## Repro Steps
1. 
Add custom properties, some healthy, some not healthy.
                module.AddHeartbeatProperty("myProp1", "myvalue1", false);
                module.AddHeartbeatProperty("myProp2", "myvalue2", true);
                module.AddHeartbeatProperty("myProp3", "myvalue3", false);
2. Run app
##  Actual Behavior
In analytics, custom dimensions simply show "myProp3", "myvalue3". 

## Expected Behavior
Custom dimensions should indicate the value of boolean healthy flag as well 
eg:  "myProp3", "myvalue3", "healthy:false"

Without this, it maybe hard to find out what caused the custom metric value to be non-zero.

## Version Info 
SDK Version :
.NET Version :	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS :
Hosting Info (IIS/Azure WebApps/ etc) :

**Comment by d3r3kk** [comment]
This would be an enhancement to the existing design. I like it, and I would prefer this to the 'aggregated' approach I took in the original design (binary 0/1 for healthy/unhealthy, essentially). Would provide a bit more context to our users.
