### ISSUE TITLE
PerformanceCounters setup using the PerformanceCollector modules need to be deduped

### ISSUE THREAD

**Issue by garamamo** [Microsoft/ApplicationInsights-dotnet#712]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. 
Create a PerformanceCollectorModule and initialize it with TelemetryConfiguration.Active.
2. 
Add PerformanceCounters by PerformanceCollectorModule.Add(new PerformanceCounterCollectionRequest("\\Processor(_Total)\\% Processor Time", "% Total Processor Time")) //Note: You can add any counter here.
3.
Run steps 1 and 2 in a loop or add the same counter request in step 2 multiple times

##  Actual Behavior
The same performance counter is collected multiple times in a very short time (sometimes in the order of ms based on the loop).

## Expected Behavior
The counters need to be deduped across all the performance collector modules. Otherwise you may end up in a situation where logs get collected every few ms and throttles AI.

## Version Info 
SDK Version : Microsoft.ApplicationInsights.AspNetCore (2.2.0-beta3)
.NET Version : net470	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Windows Azure
Hosting Info (IIS/Azure WebApps/ etc) : Service Fabric

**Comment by cijothomas** [comment]
If multiple PerformanceCollectorModules are added, then it would all collect counters. (duplicates). Why would one want to do this i.e create multiple modules programatically?
