### ISSUE TITLE
CosmosDB calls are not logged as Dependencies

### ISSUE THREAD

**Issue by mfpgod** [Microsoft/ApplicationInsights-dotnet#729]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
Different types of DocumentDb configurations were tried:
 - ConnectionMode = ConnectionMode.Direct | ConnectionMode.Gateway
 - ConnectionProtocol = Protocol.Tcp | Protocol.Https

##  Actual Behavior
DocumentDb Dependencies are not logged

## Expected Behavior
DocumentDb Dependencies are logged

## Version Info 
SDK Version : Microsoft.ApplicationInsights 2.5.1, Microsoft.Azure.DocumentDB 1.21.0
.NET Version :	net461 						
How Application was onboarded with SDK(VisualStudio) :
OS : Windows 7
Hosting Info : Service Fabric

**Comment by MS-TimothyMothra** [comment]
Hi @mfpgod,

If your DocumentDB is configured to use Protocol.Https, we should be capturing those dependencies as an HTTP Dependency with Type = "Azure DocumentDB" (see here: [DocumentDbHttpParser](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/HttpParsers/DocumentDbHttpParser.cs#L26-L90)) 

There are some known bugs affecting HTTP Dependencies that we are still investigating. It's possible this is also affected.

**Comment by mfpgod** [comment]
Thanks! Do you have tests that I can run and check whether these issues are the reason.

**Comment by MS-TimothyMothra** [comment]
At a minimum, I think you could write a HelloWorld style app to query DocumentDB to prove/disprove that DependencyTelemetry is being sent. That's what I would have to do to test this specifically. 
If you do create a small repo app, please share. It helps us investigate issues!

@TomMilos, @Dmitry-Matveev Do either of you have anything to add?

**Comment by mfpgod** [comment]
Thanks, I found the issue - one WindowsServer telemetry library was not reference correctly. The issue could be closed.

**Comment by AlexKeySmith** [comment]
Hi @MS-TimothyMothra you mention:

"There are some known bugs affecting HTTP Dependencies that we are still investigating."

Are there some tickets for those so we can follow along?

**Comment by Dmitry-Matveev** [comment]
@AlexKeySmith, most of the issues with dependencies are logged into the ApplicationInsights-dotnet-server repo as it contains the code of dependency collection.
For instance, [here is the list of open issues](https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues?utf8=%E2%9C%93&q=is:issue+is:open+dependency) concerning "depedency topic".

**Comment by AlexKeySmith** [comment]
Ah yes thanks Dmitry, it looks like I've stumbled across them following breadcrumbs, but good to know and that they're in the server repo.
