### ISSUE TITLE
ServerTelemetryChannel documentation and examples

### ISSUE THREAD

**Issue by marpe** [Microsoft/ApplicationInsights-dotnet#733]
Is there anywhere I can find example usage of ServerTelemetryChannel?

I've seen several different ways to set it up and I am looking for best practices. What are the default settings and what are reasonable picks for them?

**Comment by MS-TimothyMothra** [comment]
Hi @marpe,
Typically you wouldn't use it directly. It should get configured by default when you install this package and if you're using the applicationinsights.config.

Is there something specific you're trying to accomplish?

**Comment by marpe** [comment]
Hi @MS-TimothyMothra 
Well I'm not using applicationinsights.config, I'm setting up the configuration in code

I tried recreating #227 in my console app with more or less the same setup:
```
var channel = new ServerTelemetryChannel
{
    StorageFolder = @"c:\Users\marpe\Documents\TestTelemetry",
    MaxTelemetryBufferCapacity = 1, // no memory
    MaxTransmissionStorageCapacity = 1000 * 1000 * 100, // 100Mb
    MaxTransmissionBufferCapacity = 1000,
};
channel.Initialize(TelemetryConfiguration.Active);

TelemetryConfiguration.Active.InstrumentationKey = AppSettings.ApplicationInstrumentationKey;
TelemetryConfiguration.Active.TelemetryChannel = channel;
TelemetryConfiguration.Active.TelemetryChannel.DeveloperMode = true;

TelemetryClient = new TelemetryClient();

TelemetryClient.Context.User.Id = customerId;
TelemetryClient.Context.Session.Id = Guid.NewGuid().ToString();
TelemetryClient.Context.Device.OperatingSystem = Environment.OSVersion.ToString();
```
But I haven't gotten it to write out any files (using the same method, running the application and disabling the network device).

And I have some other questions off the top of my head:

- What format are the files in?
- What are the files named?
- What events are logged? All or only those which didn't reach AppInsights? Would events being sent with an invalid InstrumentationKey be logged as well?
- How can I ensure that events are being flushed if the process is killed (not exiting gracefully)?
- Why do I need to call `Initialize()`?
- Are `TelemetryClient.TrackX()` and `TelemtryClient.Flush()` blocking?
- If I would be using buffering instead of setting `MaxTelemetryBufferCapacity = 1` when would be a good time to `Flush()`? Only once the app exits?

**Comment by MS-TimothyMothra** [comment]
- What format are the files in?
    - json files

- What are the files named?
    - transmission#####.trn

- What events are logged? All or only those which didn't reach AppInsights? Would events being sent with an invalid InstrumentationKey be logged as well?
    - If IKey is not guid, AppInsights does not start.
    - If IKey is incorrect, endpoint will return 404 (not-retryable) and we will not save to file.
    - All event types will be saved before sent, and removed depending on send result.

- How can I ensure that events are being flushed if the process is killed (not exiting gracefully)?
    - Can subscribe on DOTNET event handler for application domain shutdown and call Flush().

- Why do I need to call Initialize()?
    - Normally the channel wouldn't be initialized until after the config has been loaded. Since you're configured manually you'll have to call this yourself.

- Are TelemetryClient.TrackX() and TelemtryClient.Flush() blocking or can I run them in my main thread?
    - TrackX is blocking, and SHOULD run in main thread to log context.
    - Flush is not blocking. 

- If I would be using buffering instead of setting MaxTelemetryBufferCapacity = 1 when would be a good time to Flush()? Only once the app exits?
    - Not necessary to call flush manually, it will auto flush when at capacity or timer.
