### ISSUE TITLE
[New] Interface for ApplicationId Lookup (IApplicationIdProvider)

### ISSUE THREAD

**Issue by MS-TimothyMothra** [Microsoft/ApplicationInsights-dotnet#739]
Proposing a new Interface for ~Correlation~ Application ID resolution in the BaseSDK.

**Why**:
This came about while working to resolve this issue: https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/853

The current [`CorrelationIdLookupHelper`](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/Common/CorrelationIdLookupHelper.cs) was not designed with configuring the endpoint in mind.

Additionally, multiple modules have private instances of the `CorrelationIdLookupHelper` which prevents it from caching lookup results and preventing duplicate requests.

**What:**
`TelemetryConfiguration` will get a root level property:  `ApplicationIdProvider`
```
public IApplicationIdProvider ApplicationIdProvider { get; set; }
```

The new interface is proposed as such:
```
public interface IApplicationIdProvider
{
    bool TryGetApplicationId(string instrumentationKey, out string applicationId);
}
```

**Assumptions:**
- An app will only need one provider, not a collection of providers.
- an ikey(s) will be needed to lookup an app id(s)
- the provider will take an ikey and resolve an appid and may store that formatted
- Breeze applicaton id format: "cid-v1:{app id}"

**Delivering:**

- the new interface: `IApplicationIdProvider`
- new `TelemetryConfiguration` property `ApplicationIdProvider`
    - This property will be `null` by default in the BaseSDK. Users will be able to opt-in.
    - This property will be set to an ApplicationInsights specific implementation when the WebSDK is installed.
- three implementations:
    - ~StaticCorrelationIdProvider will allow users to configure a single app id.~
    - `DictionaryApplicationIdProvider` will allow users to configure a collection of ikey/appid pairs
    - `ApplicationInsightsApplicationIdPovider` is a copy of the `CorrelationIdLookupHelper` from the WebSDK. This will be our provider that supports our Breeze endpoint.

**Comment by MS-TimothyMothra** [comment]
I pushed my working branch and created a PR so you can review my changes in the context of this conversation: #740

**Comment by SergeyKanzhelev** [comment]
Do you think we will need `TryGetCorrelationIdAsync` method instead of sync version `TryGetCorrelationId`

**Comment by SergeyKanzhelev** [comment]
> If I made the Interface method TryGetCorrelationIdAsync that would make A LOT of implementation details simpler! :) I'm definitely in favor of that, but we need to review the Modules that intend to use this first. If the Modules are synchronous, all we'll accomplish is moving the sync/async boundary up one level which doesn't simplify much in my opinion.

I understand this. If there will be more consumers - they'd be able to decide for themselves whether to wait for result or not. So it may be a better API for base SDK. Alternative will be to provide both versions.

> The Dictionary provider still has to perform a lookup, and can potentially fail. I don't know how common this will be needed. The Static provider will always return a single value. I expect that would be the most common user scenario, but I will defer to your judgment. :)

I don't think the fact it may fail on dictionary lookup is a big concern for me. Dictionary one makes it clearer that there is a mapping between instrumentation key and app id. Static may hide this. I'd propose to remove Static one. 

> Chaining providers are slightly more complicated, so we should discuss if this is needed and how you would like that to work.

Chaining is easy, Just accept "next" one as a public property and constructor parameter. And delegate resolution if current once cannot find the mapping. At least for Dictionary one it might be useful

**Comment by MS-TimothyMothra** [comment]
tagging @lmolkova to join the conversation here :)

**Comment by lmolkova** [comment]
Repeating [suggestion from the PR](https://github.com/Microsoft/ApplicationInsights-dotnet/pull/740#issuecomment-377042971) here (sorry, I did not realize there is a design discussion)

> We use correlation term for two completely different things in the SDK: multi-ikey support and transaction/operation correlation.
It introduces some level of confusion (not extremely high though) for our users. I wonder, since we are already in the massive refactoring, could we avoid using 'correlation' word in the multi-ikey feature to avoid this confusion? e.g. rename it to IAppIdProvider?

**Comment by lmolkova** [comment]
@SergeyKanzhelev please chime in

**Comment by SergeyKanzhelev** [comment]
`AppIdProvider` works for me. I agree with confusion part, haven't thought of it.

**Comment by MS-TimothyMothra** [comment]
Understood. I'll make that change. :)

@SergeyKanzhelev, I reviewed the Web Modules and I don't believe that any of these would benefit from having access to an Async interface. 
I fully support going in that direction for the SDK as a whole, but I think we should hold this change until we can review the necessary changes in more depth. 

I would be curious to hear your thoughts in more detail and if you have an approach to make this work, but my gut says this is a more significant design change that would affect the SDK as a whole.

**Comment by SergeyKanzhelev** [comment]
@MS-TimothyMothra base SDK making decisions on timeout and things like this may be too much of responsibility for it. I'm not against the sync method though... So maybe just have an async alternative as well.
