### ISSUE TITLE
Disable the Style Cop rule "SA1623: Property Summary Documentation Must Match Accessors".

### ISSUE THREAD

**Issue by macrogreg** [Microsoft/ApplicationInsights-dotnet#741]
I propose that we disable the following Style Cop rule:

category:       "StyleCop.CSharp.DocumentationRules",
checkId:        "SA1623: Property Summary Documentation Must Match Accessors",

This is the rule that says that docs for properties must start with phrases like "Gets or Sets XXX" and similar, depending of various aspects of the property.

Justification:
This rules does not contribute to quality of the documentation, but it makes life more difficult for people who want to write good docs using their own words. For example, assume a class MetricConfiguration with a RW property MaxTimeSeries. The following doc is accepted by the rule:
 > "Gets or sets MaxTimeSeries".

The following is not accepted:

 > "The limit for how many series will be created for this metric based on dimension values passed to the TryTrackValue(..) method."

Developers trivially know that properties can be get or set. Whether a property is Read-Only or RW is already clear from the signature. Reiterating it in comments is redundant. Rather than forcing a specific language we should focus on encouraging quality docs.

**Comment by SergeyKanzhelev** [comment]
This sentence sounds perfectly fine: 

>Gets or sets the limit for how many series will be created for this metric based on dimension values passed to the TryTrackValue(..) method.

In fact it will be more informative. Developers typically see API thru the intellisense or in html doc. Neither gives information on whether property can be read or write to.

Another benefit I know for myself is that `Gets or sets` forces to formulate the purpose of the property in a few words. With the rest of long remarks later in the summary. Descriptions will not start with long background history of how why this property is important.

You can look up discussions on internet like [this](https://softwareengineering.stackexchange.com/questions/193244/is-the-gets-or-sets-necessary-in-xml-documentation-of-properties). I think there is general agreement that this is in-perfect. But people following it. 

I looked over few repos in `aspnet` org. You can see how people [trying](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Kestrel.Core/KestrelServerOptions.cs) to follow the rule, but have a tendency to fall back in what you suggesting. Knowing history this repo was started without stylecop for .net core support. This repo is still not cleaned up. Use of this rule is forced when repo owner cares about documenting. See [this](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs). I would appreciate if you'd point me to examples of people using stylecop to force documentation, but disabling this rule.

I like description you gave as example. It wouldn't be made worse by adding `gets or sets` as a prefix. So please, keep up with this annoyance. 

Closing issue for now. Please re-open if you think we need further discussion.

**Comment by macrogreg** [comment]
Hi Sergey,

I am re-opening merely to make sure you get a notification and get a chance to read my response. Given that this was closed twice, rather that to remain open to encourage a wider discussion, and given the previous responses I am assuming that you will close this again and the issue will remain closed afterwards. :)

> people enforcing documentation typically enforce this rule.

I have not seen any data to support or contradict this statement. But either way, this is not relevant. If this was, indeed, a correct statement - the question would be, Why? For a good reason that applies here? Because someone created a default and noone questioned it? Another reason?

>  rule has sense to indicate writeability of the property.

Agreed.

> [...] Which is basically overcomes in-perfectness of the tools by minor annoyance of enforcing certain words.

Personal opinion.

> rule enforces better descriptions, while not making good descriptions worse.

No.
I have provided several examples about how this rule does not enforce better descriptions. Both, in sources you pointed to and in other places. We have not seen any example how the rule actually enforces better descriptions. Notably, I have not suggested that we do not prefix descriptions with "Gets or Sets ...", I merely suggested that we allow not to do that.

Thanks. :)

**Comment by SergeyKanzhelev** [comment]
I have not objections re-opening issue many times for a good reason. I hold no grudge. I spent a lot of time questioning my position and investigating the question.  You can understand it by my long replies.

>> people enforcing documentation typically enforce this rule.
>I have not seen any data to support or contradict this statement. But either way, this is not relevant. If this was, indeed, a correct statement - the question would be, Why? For a good reason that applies here? Because someone created a default and noone questioned it? Another reason?

I have your opinion AND opinions of other smart people I respect. I believe they questioned this rule. So I was trying to get out my personal opinion and find examples. Also I posted a link to one forum where people quesitoning this. And that link had explanation with good reasons.

>>[...] Which is basically overcomes in-perfectness of the tools by minor annoyance of enforcing certain words.
>Personal opinion.

Everything is a personal opinion. I just pointing out that tools do not give this information today and this prefix helps. I posted this opinion from the link I gave.

>> rule enforces better descriptions, while not making good descriptions worse.
>No.
>I have provided several examples about how this rule does not enforce better descriptions. Both, in sources you pointed to and in other places. We have not seen any example how the rule actually enforces better descriptions. Notably, I have not suggested that we do not prefix descriptions with "Gets or Sets ...", I merely suggested that we allow not to do that.

This rule enforces to start description with the property semantic. It also helps beginner developer suggesting how to approach documenting of property and avoid being "too creative". Not with the general description of tool. For instance it will not allow something like `Application Insights is a monitoring tool. It uses multiple ways to do metrics aggregations. This property may be used to specify some aspects of those aggregations.`. Instead developer will be forced to start with `Gets or sets metrics aggregation type. Appliucation Insights is a monitoring tool that uses multiple....`. 

The same time it doesn't make any description you gave worse. 

All I was saying it doesn't make anything worse and enforces better descritptions in certain cases. 


# Summary

**Why to use**:
- people enforcing documentation typically enforce this rule.
- rule has sense to indicate writeability of the property. Which is basically overcomes in-perfectness of the tools by minor annoyance of enforcing certain words
- rule enforces better descriptions, while not making good descriptions worse.

**Why not to use**:
- This rules makes life more difficult for people who want to write good docs using their own words.

I'd say three (and in case of Boolean property - four) extra words in description is not very difficult. My suggestion again is to keep it. Closing, but feel free to re-open
