### ISSUE TITLE
Weird applicactionInsights.config after NuGet package update

### ISSUE THREAD

**Issue by Vlad-Stryapko** [Microsoft/ApplicationInsights-dotnet#743]
HI,

I've noticed that AI config file became pretty strange after I'd updated from 2.2.0 to 2.5.1 version. Here's the weird section:

```
		<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
			<MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
			<ExcludedTypes>Event</ExcludedTypes>
		</Add>
		<Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
			<MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
			<IncludedTypes>Event</IncludedTypes>
		</Add>
```

Steps to reproduce: 

1. Create an ASP.NET MVC project using VS 2017. 
2. Check that the version of AI package is 2.2.0 (or, probably, just lower than 2.5.1)
3. Check that ApplicationInsights.config has only one section for `Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor`. In my case it didn't contain neither Included nor Excluded types subsection. 
4. Upgrade the package to 2.5.1
5. Observe the changes in ApplicationInsights.config.

Could you please clarify the following questions: 

1. Is it an expected behaviour? 
2. If so, what would that mean? How can sampling be turned off and on at the same time?

Thanks

**Comment by zakimaksyutov** [comment]
This is expected.

The first section defines sampling for all telemetry types *except* Event.

The second section defines sampling for only Event telemetry type.

**Comment by SergeyKanzhelev** [comment]
Thanks for asking. Please re-open if you have more questions. 

It's dup of https://github.com/Microsoft/ApplicationInsights-dotnet/issues/583

Behavior was introduced in 2.4.0-beta1:

> Version 2.4.0-beta1
> Event telemetry is set to be sampled separately from all other telemetry types. It potentially can double the bill. The reason for this change is that Events are mostly used for usage analysis and should not be subject to sampling on high load of requests and dependencies. Edit ApplicationInsights.config file to revert to the previous behavior.

**Comment by joelmdev** [comment]
Blew away my previously customized sampling rules. Didn't expect this and didn't catch it initially. Not ideal.

**Comment by drauch** [comment]
@zakimaksyutov : the docs @ https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#configuring-adaptive-sampling-for-aspnet-applications do explain it differently. You should update the docs to your description to make it more clear what this does.

**Comment by cijothomas** [comment]
@drauch  Not sure what you mean by docs explain it differently? can you be specific about where the doc contradicts? 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#frequently-asked-questions

**Comment by drauch** [comment]
In https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#configuring-adaptive-sampling-for-aspnet-applications it sounds like `ExcludedTypes` means "types you don't want to be sampled" and not "all other types are being sampled".

**Comment by zakimaksyutov** [comment]
@drauch, this is a little bit more complicated =)

ExcludedTypes indeed means "types you don't want to be sampled". But this refers to individual sampling telemetry processor.

In default configuration we add two telemetry processors. One with excluded events, another one with included events. The first one doesn't touch events. But the second one touches only events.

Please let me know whether this clarifies...
