### ISSUE TITLE
Add appropriate tags to metrics test methods that need it

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-dotnet#747]
Info:

-----------

Good info, thanks. I want to minimize churn before the beta branching today, but I’ll add these tags next time I touch things.

-----------

Let’s talk about test categories in the next sprint, I’ll push an issue onto Github for this.

You can decorate test methods with:

        [Ignore]
        [Description("Ignore: test is inconclusive due to use of DateTime:Now (it runs over day barriers and can fail)")]
        [TestMethod]
        …

I suggest that you make use of Description as well, to describe why the test was set to ‘Ignore’… perhaps even assign an owner with the responsibility to update the test if you want to get real specific.
[Owner("team-or-individual")]

-----------

Ok, thanks. I wont to this right now, but I’ll do that next time I touch stuff there. 

Thanks,

-----------

All you should have to do is add the [Ignore] attribute to the test method.
Let me know if that doesn’t work.

Thanks, 
•	Could you please teach me about the proper way of temporary disabling unit tests? I had to disable three due to #746, and I just commented out [TestMethod].
However, if there was a better way that would allow them to be ignored in server builds, but still run when running all tests in VS, I would prefer using that approach.

**Comment by d3r3kk** [comment]
@macrogreg & @MS-TimothyMothra perhaps you can collaborate and set this up together?

**Comment by macrogreg** [comment]
I thought the work needed here was to add
```
[Ignore]
[Description("..")]
```
to the respective test methods. I am planning to do that, just did not yet get around to it. I am not sure about the build changes - what is this required for?

**Comment by d3r3kk** [comment]
I'm not really sure about that. [All I know is what the documentation for vstest.console.exe tells me](https://msdn.microsoft.com/en-us/library/jj155796(v=vs.150).aspx).

Perhaps there is something that can be done with a test settings file of some sort, and then passing that test settings file to vstest during the build on the build servers only?

Or, and I'm just spitballin' here, we could *fix the tests*?

**Comment by macrogreg** [comment]
> Or, and I'm just spitballin' here, we could _fix_ the tests?

Dude, take it easy here, right? Just be chill with ideas here, ok?

**Comment by macrogreg** [comment]
More on the serious side, the tests that I added and that were failing were failing because of concurrency.
We have various statics in the product, most importantly `TelemetryConfiguration.Active`. That make things very convenient most of the time, but sometimes create test difficulties when two test mess around with the settings on those statics and want to observe the corresponding effect. If I force tests to never run in parallel, I get no failures. 
Runsettings can ensure that tests run sequentially in VS, I can only assume that it is also the case on the command line. Whether or not it is ever acceptable or a good idea to force SDK tests to always run sequentially, I ll leave to the wise judgement of @MS-TimothyMothra , @Dmitry-Matveev , @SergeyKanzhelev and other smart individuals.

**Comment by cijothomas** [comment]
Closing this for now as there is no action required now. Most of the unstable tests got fixed over last few months.
