### ISSUE TITLE
(Minor Improvement) Guard TelemetryClient.Flush to not throw NullReference Exception

### ISSUE THREAD

**Issue by MichaConrad** [microsoft/ApplicationInsights-dotnet#755]
Hi,
today I ran into an odd behavior that on app shutdown of my ASP.NET Core service, one part of the application (the Serilog Sink) tries to `Flush` before it disposes.
But at that point in time, `this.configuration.TelemetryChannel` in `TelemetryClient` is already null.

And that causes `Flush` to throw a hard NullReference Exception [Code line 589](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/TelemetryClient.cs#L589)

see https://github.com/serilog/serilog-sinks-applicationinsights/issues/46

Could you just elvis the expression or at least null check it?

Thanks,
Michael

**Comment by MichaCo** [comment]
@SergeyKanzhelev sure, just added the PR
