### ISSUE TITLE
Release: Remove deadcode: SessionState

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#758]
These classes were marked Obsolete on 9/26/2016. 
Are these safe to delete now?
These were flagged by FxCop.

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/7321d2bf7b9c4733fb43b6c186e381863931eb1a/src/Microsoft.ApplicationInsights/DataContracts/SessionState.cs#L8-L9

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/7321d2bf7b9c4733fb43b6c186e381863931eb1a/src/Microsoft.ApplicationInsights/DataContracts/SessionStateTelemetry.cs#L9-L10

**Comment by SergeyKanzhelev** [comment]
what version were they marked as `Obsolete`? Semantic versioning saying we can only remove public APIs in major versions. Meaning `3.0+`. Maybe we can make an exception if we know for sure nobody uses it any longer.

**Comment by MS-TimothyMothra** [comment]
I can align with 3.0
