### ISSUE TITLE
Add isolated application support to dotNet Base

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#762]
Moved from https://github.com/Microsoft/ApplicationInsights-Home/issues/191

Originally created by @ScottColson

> I frequently create plugins as dotNet extensions to the Microsoft Dynamics
CRM platform. These plugins generally run in isolation and don't have
access to the host drive or Environment data. Therefore the plugins will
error out with a security exception when AI initializes.
> I have developed work around to this issue that allows the calling app
to inject a custom platform via TelemetryConfiguration as part of the
TelemetryClient creation.
> However, to make this work I need to make the IPlatform interface and
the IDebugOutput interface public as well as add an alternate constructor
for TelemetryConfiguration.
> Is this something that would be beneficial to a larger user base?

> The plugins that I create for CRM use NET4.5.2 and need to run within a Microsoft.crm.sandbox.workerprocess. I know how to create unit tests and PRs but I don't know how to create a unit test that simulates what this process host allows and my searches have not yielded much. Do you have some recommended resources about simulating sandboxed services during unit test?
> I have identified the following additional areas where the existing AI SDK implementation is not compatible with the sandboxed host process:
Transmission.SendAsync() implementation for NET45 fails, but if I use the implementation that was put in place for NETSTANDARD1_3 then it works as expected. I presume the same will be true for NET46.
CallContextHelpers for NET45 are based on System.Runtime.Remoting and cause security exceptions. I don't have a good alternate implementation, so for my current testing I have simply made all of the helpers inert. This will be a problem when running more threads.
> There are also issues within the Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing classes that I still need to fully explore, but when things do wrong and the DebugTelementryModule is called upon to report the issue back to AI, my plugin fails with a security exception.

**Comment by MS-TimothyMothra** [comment]
@SergeyKanzhelev what action do you expect?

**Comment by SergeyKanzhelev** [comment]
Have a unit test that will validate that SDK will not crash in partially trust domains. @ScottColson pointed one issue that needs to be addressed and we better have a test coverage for this case

**Comment by ScottColson** [comment]
It is going to be very difficult to meet this requirement. Impossible without a breaking change to the defined API. For my particular need related to Dynamics 365 I opted to create an alternate implementation  that offers a subset of the API functionality. That implementation is now part of a larger Dynamics Xrm development framework at https://github.com/ScottColson/CCLLC.Xrm.Development.

**Comment by SergeyKanzhelev** [comment]
Seems to be referred from here: https://community.dynamics.com/crm/f/117/t/258696 as well
