### ISSUE TITLE
Enable ExceptionTelemetry.SetParsedStack for .netstandard?

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/ApplicationInsights-dotnet#763]
The method [ExceptionTelemetry.SetParsedStack](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/7321d2bf7b9c4733fb43b6c186e381863931eb1a/src/Microsoft.ApplicationInsights/DataContracts/ExceptionTelemetry.cs#L216-L250) is not available for .netstandard.

Is there a reason why it is under #if? It seems to depend only on StackFrame and ExceptionConverter which are referenced anyway.

**Comment by MS-TimothyMothra** [comment]
@SergeyKanzhelev are you aware of any reason this constraint is present? It was added [here](https://github.com/Microsoft/ApplicationInsights-dotnet/pull/512).

I removed it and everything compiles and all the tests pass.

If there's no reason to keep this constraint, I propose removing it.

**Comment by SergeyKanzhelev** [comment]
no specific reasons. Feel free to remove conditional compilation
