### ISSUE TITLE
Adjust validation if Metric and MetricNamespace monikers to ingestion requirements

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-dotnet#766]
The naming restrictions for metrics are stricter at the new endpoint compared to the AppInsights unauthenticated endpoint. The existing (stable) APIs should not be changed (back-compat). However new pre-aggregation APIs should fail-fast when invalid monikers are used. We have already included some of this validation into the first Beta, but we need to re-align them with the public endpoint shipped version:

* Metric Namespace moniker may be exceed 256 characters.
* Metric Name moniker may be exceed 256 characters.
* Metric Namespace may not start with "`Microsoft.`".
* Metric Namespace may not be equal to any of the following:
-- `GenevaKustoQos`
-- `LogsToMetricsQos`
-- `MdmQos`
-- `RecoveryService/V2`
-- `MonitorSLA`
-- `WarmPathQos`

**Comment by macrogreg** [comment]
I will worn on it as a part of namespace work.

**Comment by SergeyKanzhelev** [comment]
SDK design principle is NOT to fail. Instead make the best attempt to accept data. I'll move the document with the principles to GitHub

**Comment by macrogreg** [comment]
I am not sure I follow. If a user specified a name that we know if invalid and will fail to be ingested, we should still send it? What is the desired behavior when the sending fails? At that time we are on a background thread and throwing is not longer an option. Do we juts drop data? In not, what do we do?

**Comment by SergeyKanzhelev** [comment]
This is what we do if customer failed to populate required field: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/e8f047f6e48abae0e88a9c77bf65df858c442940/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Utils.cs#L44-L56

Basically the idea is that indication of some bad configuration is best to be surfaced as a low quality telemetry event than as a crash of an application. Application Insights SDK is a telemetry library and we want to make sure customer can trust it and not forced to wrap every call in ugly `try{}catch` statement

**Comment by macrogreg** [comment]
Completely agree on this:

> Application Insights SDK is a telemetry library and we want to make sure customer can trust it and not forced to wrap every call in ugly try{}catch statement.

However, the case we need to solve _here_ is more complex: rather than missing a required field, the name for a whole metric is invalid. 

The good thing is that in the vast majority of cases, such names are fixed. So, try-catches are not necessary, because the call will:
 - either always fail or never fail (i.e. not depending on input).
 - there is no way to handle the issue programmatically. Such a failure typically indicates a coding bug and the developer needs to change the metric name in code.

That being said, there is a way: we could manually massage invalid namespace and metric names by:
 - replacing invalid chars with other chars
 - truncating long names.

Both will not be straight forward: replacement chars would probably need to follow the URL encoding convention and will thus make names longer. Either way, as soon as any kind of replacement or truncation occurs, we would need to combine the resulting string with a hash of the original to avoid that our "beautification" leads to duplicates.

We have a lot of work for metrics right now. If we want to do this kind of "beautification", it works for me. But then, I'd rather throw for now and keep a bug around to improve this in a later release.

Also, if you can suggest other options, maybe there is an easier way?

**Comment by SergeyKanzhelev** [comment]
Search something around sanitize logic. There should be

**Comment by macrogreg** [comment]
Ok. I'll take a look. If I do not find anything, I will create a generic internal utility that can be used by other places too, but I may not have capacity to go through similar usages elsewhere and rewire them to use the generic solution.

It'll be something similar to:

string EnsureValidMoniker(string moniker, int maxLen, char[] invalidChars, char asciiEscape);

Works?
