### ISSUE TITLE
Ref docs /// issue: DependencyTelemetry Constructor (Microsoft.ApplicationInsights.DataContracts) Application insights docs non-informative, contains errors.

### ISSUE THREAD

**Issue by CamSoper** [Microsoft/ApplicationInsights-dotnet#778]
_From @las3r on April 6, 2018 16:2_

The biggest constructor is mentioned with having two 'dependencyName', which isn't correct. Also it would be very helpful to know how 'data', 'target' and 'DependancyTypeName' will show up in our AI dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c2d6c30-d2f6-5b80-7820-aff2ee35aada
* Version Independent ID: 962248d9-c25b-bc7e-b9ee-55ab26af5daa
* Content: [DependencyTelemetry Constructor (Microsoft.ApplicationInsights.DataContracts)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.dependencytelemetry.-ctor?view=azure-dotnet#Microsoft_ApplicationInsights_DataContracts_DependencyTelemetry__ctor_System_String_System_String_System_String_System_String_System_DateTimeOffset_System_TimeSpan_System_String_System_Boolean_)
* Content Source: [xml/Microsoft.ApplicationInsights.DataContracts/DependencyTelemetry.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights.DataContracts/DependencyTelemetry.xml)
* Service: **application-insights**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

_Copied from original issue: Azure/azure-docs-sdk-dotnet#572_

**Comment by SergeyKanzhelev** [comment]
@mrbullwinkle do you know how to rebuild the docs from the latest version of code?

**Comment by CamSoper** [comment]
It's all automated. So long as the code has the correct /// comments in the code, we have an automated process that will grab the NuGet package and build the docs.

**Comment by SergeyKanzhelev** [comment]
So the automation is broken? 

Summary have it wrong:
<img width="660" alt="screen shot 2018-04-17 at 1 57 20 pm" src="https://user-images.githubusercontent.com/9950081/38896372-5e5aa272-4247-11e8-810b-7c64a1edf8e5.png">

When actual definition correctly have two different names:
<img width="525" alt="screen shot 2018-04-17 at 1 57 33 pm" src="https://user-images.githubusercontent.com/9950081/38896378-60d8cb0a-4247-11e8-9963-5d52643df033.png">

Is there anything we can do from our side?

**Comment by SergeyKanzhelev** [comment]
@CamSoper @mrbullwinkle   do you know where to file the bug for the broken automation?

**Comment by SergeyKanzhelev** [comment]
closing issue here. Reopened in corresponding repo. As it is clearly generator issue, not a code problem

**Comment by CamSoper** [comment]
Are you sure about that?  I'm pretty sure it's a typo in the `<summary>` element in the inline documentation in the code.

**Comment by CamSoper** [comment]
@SergeyKanzhelev Actually, I'm 100% sure it is.  [Here](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/e43361c527ebb7aafd8c1a5a4507e94d2734d54e/src/Microsoft.ApplicationInsights/DataContracts/DependencyTelemetry.cs#L54) and [here](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/e43361c527ebb7aafd8c1a5a4507e94d2734d54e/src/Microsoft.ApplicationInsights/DataContracts/DependencyTelemetry.cs#L67).

**Comment by SergeyKanzhelev** [comment]
It was my blind trust in fxcop and stylecop. Created PR to fix it. Thanks

**Comment by CamSoper** [comment]
Thank you, sir! :)
