### ISSUE TITLE
not saving temp file in offline scenario for some users

### ISSUE THREAD

**Issue by matttabor** [microsoft/ApplicationInsights-dotnet#796]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
I'm using the SDK to send some basic application tracking data for a wpf app. I'm using the server telemetry channel to handle cases where users are not connected to the interwebs. Testing the app it works for me just fine, but when users test this for me they never see the telemetry captured offline get pushed to app insights. When I run through the app when I'm offline I see a temp file get created in my storage folder as expected. When I come back online and open the app that file goes away as expected. But trying the same thing on users computer's the file isn't getting created - so data captured when user is offline is just getting lost.

From my applicationinsights.config file

    `<TelemetryChannel Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel, Microsoft.AI.ServerTelemetryChannel">
		<StorageFolder>c:\temp</StorageFolder>
	</TelemetryChannel>`

I've asked the user to make sure they've created the folder and given write access, but still doesn't seem to work.
##  Actual Behavior
No temp file is saved in offline scenarios and therefore no offline data is captured.

## Expected Behavior
temp file should get saved in the storage folder I specified and when user comes back online they should and runs the application again they should see that data pushed out to app insights

## Version Info 
SDK Version : 2.5.1
.NET Version :	 4.5					
OS : windows 10

**Comment by matttabor** [comment]
Working with my users here it looks like the call to `NetworkInterface.GetIsNetworkAvailable();` is returning incorrectly. It returns true for them even though they are not connected to a network.

**Comment by lmolkova** [comment]
We have similar (perhaps the same) issue reported via ICM ticket with some details there.
There is a virtual network adapter without internet access so `GetIsNetworkAvailable` does not correctly identify the network state.

It is likely that channel does not receive any response from the backend, as it was using a virtual network adapter to send transmission.

From the logs, I see that couple of transmissions were started but never finished (perhaps finished with timeout after trace collection was finished). 

As we've never got any response, this branch of ErrorHandlingTransmissionPolicy is executed: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/7850e43cd17972b8be7114b4adf54ba2004a6a3d/src/ServerTelemetryChannel/Implementation/ErrorHandlingTransmissionPolicy.cs#L87, so we don't send any telemetry to the backend. 

As timeouts/cancellations is a valid and transient issue, we should test this cases and find the proper retry policy.

**Comment by Hammatt** [comment]
I'm seeing this issue too when integrating application insights into our azure iot edge modules. Is there any kind of ETA for this issue being fixed?

**Comment by cijothomas** [comment]
The latest 2.10.0-beta4 should address this issue. Please try it and let us know if this still repros.

**Comment by arabelaa** [comment]
I've tried 2.10.0-beta4 and the issue is not solved. I noticed that Network.IsAvailable() uses System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable() which returns true even if I don't have internet connection. If Network.IsAvailable() returns false tmp files are generated. Used in .NET Core 2.2.

Is there a way I can inject my own Network provider somehow?
