### ISSUE TITLE
Unable to log telemetry from plugins executed inside CRM Online (Partial Trust)

### ISSUE THREAD

**Issue by shalabhgupta1985** [microsoft/ApplicationInsights-dotnet#797]
#416 
@SergeyKanzhelev

## Repro Steps
1. Created a basic sample plugin as per the following MSDN: https://msdn.microsoft.com/en-us/library/gg594416.aspx 
2. After Line "service.Create(followup);" in above code, added the following lines of code to log insights:
`TelemetryClient telemetryClient = new TelemetryClient() {InstrumentationKey= "KEY" };
                    telemetryClient.TrackTrace("Test6 - Plugin", properties: new Dictionary<string, string>() { { $"Test 6 Plugin", $"Test 6 Plugin".ToString() } });`
3. Same code works via a .Net console application.

##  Actual Behavior
No Trace gets logged in the Azure Application Insights when executed from CRM Plugin in Online environment.  

Error message: 
Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.

## Expected Behavior
The Trace should be logged into Azure Application Insights

## Version Info 
SDK Version : CRM SDK for Dynamics 365 : https://www.microsoft.com/en-us/download/details.aspx?id=50032
.NET Version :	 4.5.2						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : Visual Studio
Hosting Info (IIS/Azure WebApps/ etc) : Azure

**Comment by Mikkel-Kaas** [comment]
Yes please. This would be hugely helpful.
