### ISSUE TITLE
The netstandard1.3 'Microsoft.AI.ServerTelemetryChannel' depends on Newtonsoft.Json

### ISSUE THREAD

**Issue by clguimanMSFT** [Microsoft/ApplicationInsights-dotnet#800]
This dependency is a problem if you want to inject ApplicationInsights at runtime in an netcore 2.1 application.
The loading logic has changed there and might downgrade the application's Newtonsoft.Json version.

**Comment by SergeyKanzhelev** [comment]
Dependency on third party library like `Newtonsoft.Json` is a problem in general. It may cause all sort of version conflicts with the customer apps.
