### ISSUE TITLE
SQL queries not tracked automatically using SQLite (and Dapper)

### ISSUE THREAD

**Issue by artberri** [Microsoft/ApplicationInsights-dotnet#802]
Hi,

I have an ASP.NET webapi project hosted in Azure (App Service for Containers). Application Insights is installed and generally working well, however it won't show me the SQL dependencies.

I'm using **SQLite** and the Dapper micro ORM. I've already read the issue https://github.com/Microsoft/ApplicationInsights-dotnet/issues/687 and it seems that there is not any problem tracking queries made with Dapper, but using SQLServer.

So, is SQLite supported or automatically tracked by App Insights or do I need to track dependencies manually?

Following the previously mentioned issue I found [this file](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/ProfilerRuntimeInstrumentation.cs) where we can see the instrumented methods and I can't see anything tracking SQLite dlls.

## Repro Steps

1. Create ASP.NET webapi project
2. Install AppInsights, Dapper and Sqlite:

```xml
  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.4" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="2.1.0-rc1-final" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.3.0-beta2" />
  </ItemGroup>
```

3. Do a query from a controller

##  Actual Behavior

There is no SQL dependency tracked in App Insights.

## Expected Behavior

To track SQL queries showing them as SQL dependencies and showing the executed command.

## Version Info 

SDK Version : Microsoft.ApplicationInsights.AspNetCore v2.3.0-beta2 (Nuget)

.NET Version :	 App created with CLI and SQL added by editing csproj with vscode. 
```bash
$ dotnet --version
2.1.300-rc1-008673
```

OS : Ubuntu 18.04 and Alpine

Hosting Info (IIS/Azure WebApps/ etc) : Azure web App for containers with the `microsoft/dotnet:2.1.300-rc1-sdk-alpine3.7` docker image.

**Comment by Dmitry-Matveev** [comment]
@artberri , you are correct. SQLite calls are not auto-collected.
There are several ways AI may collect dependency calls:

- Profiling API (the code you linked in your post) instruments the certain well-known methods and can report on their performance. It is installed with Status Monitor or via Web App Extension.
- Diagnostic Source or Event Source instrumentation: Http and SQL methods emit certain events AI listens to.

Both cases do not apply to SQLite (if SQLite does not use any of .NET underlying methods to connect/execute SQL command) - SQLite calls do not emit events in the format for AI to understand and the method list in AI profiling approach does not contain SQLite methods.

You can still track those calls manually with TrackDependency().

**Comment by artberri** [comment]
> You can still track those calls manually with TrackDependency().

That's what I'm doing currently, I was asking to ensure that it is the proper way.

Thank you very much for your answer!
