### ISSUE TITLE
Move metrics extraction to the new APIs and remove MetricManager V1 & Co

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-dotnet#806]
We have recent shipped new metric aggregation APIs.
However, standard metric extraction uses old internal APIs.
We need to 
a) Change the extractor to use the new APIs
b) Remove the old APIs.

This will not affect any public APIs or any public configuration options. However, customers who used reflection to access V1 MetricManager APIs will be broken.

**Comment by MS-TimothyMothra** [comment]
Just to confirm, will V2 be public?
Do we need to publish any guidance for customers to migrate from V1 to V2?

**Comment by macrogreg** [comment]
Yes, V2 is public, V1 is internal.
There is not guidance to migrate since V1 was internal. The extractors using V1 are public but transitioning them to V2 should not have any publicly observable effect, except a small performance improvement.

**Comment by Dmitry-Matveev** [comment]
@macrogreg , I believe we can close this issue as it was successfully implemented?
