### ISSUE TITLE
Telemetry properties split - proposal

### ISSUE THREAD

**Issue by cijothomas** [Microsoft/ApplicationInsights-dotnet#816]
Currently `ITelemetry` has a `TelemetryContext` which can define the context of the `ITelemetry` item. This context holds information that are more global than the individual item properties. Apart from well known fields like Cloud ("ai.cloud.roleinstnace"), Device("ai.user.devicetype") etc., `TelemetryContext` also contains a property bag collection to store any key,value (string,string) pair of information.
Along with this `TelemetryContext`, all concrete `ITelemetry` implementations defined in the base sdk (eg: RequestTelemetry, DependencyTelemetry) also implements `ISupportProperties` interface. 
This gives them a 'Properties' bag which can store any key,value (string,string) pair of information applicable to the individual telemetry item.
On top of these two property bags, `TelemetryClient` also contains a `TelemetryContext` which is a truly global context, applied automatically to all the telemetry items tracked using that instance of `TelemetryClient`.

To summarize, there are essentially three places for a Telemetry item to hold non strongly-typed key,value information.
1. A truly global context of properties which is stored in `TelemetryClient` instance. 
2. A less global context of properties stored in the `TelemetryContext` of `ITelemetry`.
3. Properties applicable to the individual telemetry item only.

The order of priority is 3>2>1 i.e property set on individual item takes precedence over the one set in `ITelemetry.TelemetryContext`, which takes precedence over the one set in `TelemetryClient.TelemetryContext`.

For the json used in wire format however, all the above 3 property bags are serialized into a "properties" section inside the telemetry. Few well-known properties like CloudContext, DeviceContext etc are promoted to the "tags" section.
Hence AI back-end cannot distinguish whether any given property belongs to just individual item or to context or in global context.

We are trying to optimize back-end so that properties applicable to just inidivual Telemetry item, properties of TelemetryContext, and global properties from TelemetryClient, are all separately treated.
Users will be encouraged to use lowest-cardinality fields to global TelemetryClient's context, lower-cardinality fields to ITelemetry.TelemetryContext, and any fields to Properties of individual telemetry item.

```
TelemetryClient tc = new TelemetryClient();
tc.TelemetryContext.Cloud.RoleInstance = "instance1"; //This is special well-known property and has dedicated field in back-end/first class in UI for filtering.
tc.TelemetryContext.Properties.Add("LowestCardinalityField", "region1"); //This could be treated special by back-end and UI could contain fast filters based on these fields.

RequestTelemetry req = new RequestTelemetry();
req.TelemetryContext.Properties.Add("LowerCardinalityField","Category1"); // This could be treated special for UI filters.
req.Properties.Add("anykey","GuidorAnything"); // All custom properties, not specially indexed/no tailored UI experiences.
```

The present implementation internally uses same Dictionary to hold the properties of individual item, and that from `TelemetryContext.
i.e
var req = RequestTelemetry().
req.Properties and req.Context.Properties are internally the same collection, each being affected by modification to the other.

The first step in the direction of treating properties separately would be to split the properties bag on TelemetryContext from the individual item's properties bag.
In initial implementation, the serialization should remain the same. i.e properties from all levels will continue to be serialized into "properties" section. 
This is only temporary until backend systems are modified. Later, properties from TelemetryClient's properties, those from TelemetryContext's properties, and those on individual item, will be in their own section in the serialized wire-format, allowing back-end to treat them separately.

**Comment by pharring** [comment]
1 and 2 are the same today. i.e. `req.Properties` is just a short-cut for `req.TelemetryContext.Properties`?
Why not keep them that way?
In other words, what interesting scenarios would need two different property bags on a telemetry item?

**Comment by lmolkova** [comment]
@cijothomas I've seen many places where Telemetry.Properties and Telemtery.TelemteryContext.Properties usage is mixed. Our SDKs, diagnosting agents, Azure Functions SDKs. 
I cannot imagine we can make all of them move to 'the new world of different properties'. It could be hard to prevent users from updating AI SDK while some code (e.g. in AzureFunctions) would still rely on the 'old' properties.

So I'm not sure it is feasible to make this transition non-breaking.

I also do not really understand why we want to keep this name confusion. Why we cannot separate them?

1. Keep all 'Properties' behavior the same
2. Obsolete 'Properties' on TelemteryClient and anyone of ISupportProp or TeletmeryContext
3. Add a new TelemtryClient.GlobalContext 
4. Add a new TelemetryContext.LessGlobalContext

**Comment by lmolkova** [comment]
I want to emphasize how confusing it is to have items with the same name but different purpose:

E.g. [here](https://github.com/MicrosoftDocs/azure-docs/pull/4998/files#diff-3b3ae16bac83dd1033b98019a4a8031bL391) - Azure Functions gave a recommendation to update TeletmeryContext on the TelemetryClient instead of the Telemetry. As a result, Operation.Id was set in the global context.

I'm not sure how relevant it is to the current discussion, sorry if it is not, but since we are entering 1DS era and ready to do some refactoring, let's not repeat past mistakes :)

**Comment by SergeyKanzhelev** [comment]
@lmolkova I like the idea with obsolete and rename the properties collection. This will not break customers, but will give us a way forward without major version change right away.

**Comment by cijothomas** [comment]
Thanks everyone for the feedbacks.
Paul - the reasoning behind splitting the props is to (eventually) serialize them differently, and enable UI/back-end to be optimized. 

Liudmila - Yes, you are very much right about the confusion part :) Hence this was considered as part of 3.0 release and I was modifying other SDK modules to take into account this new behavior.  I realized it'd be harder to modify all documentations/code, especially those outside this/server repo.

But I like the idea of obsoleting properties everywhere, and provide more meaningful names.
I'll think about this a bit more and come back.

**Comment by cijothomas** [comment]
Closing this issue in favor of the new one (#820)
My understanding was incorrect and this caused come confusion.
