### ISSUE TITLE
Complete missing Doc Comments for metrics

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-dotnet#817]
[Tracking item]

**Comment by MS-TimothyMothra** [comment]
Several public classes and interfaces have been released without documentation:

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/7850e43cd17972b8be7114b4adf54ba2004a6a3d/src/Microsoft.ApplicationInsights/Metrics/Extensibility/IMetricSeriesAggregator.cs#L5-L13

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/7850e43cd17972b8be7114b4adf54ba2004a6a3d/src/Microsoft.ApplicationInsights/Metrics/Extensibility/IMetricValueFilter.cs#L3-L10

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/25ff4e34992b5e1c88903ea0313bc99672c764bd/src/Microsoft.ApplicationInsights/Metrics/MetricSeriesConfigurationForMeasurement.cs#L22-L25

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/3e58b2cff77a859fc2b1e3f26e9d533e567dae7e/src/Microsoft.ApplicationInsights/Metrics/MetricManager.cs#L9-L20

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/6cf1ff15774bc3a6b8062b7949114b5e8d88631f/src/Microsoft.ApplicationInsights/Metrics/MetricAggregate.cs#L8-L22

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/6cf1ff15774bc3a6b8062b7949114b5e8d88631f/src/Microsoft.ApplicationInsights/Metrics/IMetricSeriesConfiguration.cs#L6-L16

**Comment by MS-TimothyMothra** [comment]
@macrogreg any update on this?
This is being reported by customers now #925

**Comment by TimothyMothra** [comment]
#1192
