### ISSUE TITLE
Intermittent high latency in InMemoryChannel.Flush

### ISSUE THREAD

**Issue by dennis-yemelyanov** [Microsoft/ApplicationInsights-dotnet#818]
Usually flushing telemetry using InMemoryChannel takes a few hundred milliseconds, but in some cases time goes up to 1 minute or even more. The telemetry being sent is very similar in size and nature in all cases. The max latency seems to be 1 min 40 s, which is the default timeout for calling https://dc.services.visualstudio.com/v2/track. 

Is this endpoint having some issues or is it expected that it can take so long? If it's expected, what's the recommended way to avoid timeouts and make flush faster?

I have to use InMemoryChannel because the application is a short living process (in most cases less than 30 seconds), so telemetry is flushed before exit. I considered the following solutions:

1. Changing the `SendingInterval` to a lower value like 1 second. Tried this option, but it didn't seem to help, some calls still take 100 seconds.
2. Instead of sending telemetry directly from the short living process have another long living process that will do actual logging. It would probably work, but would complicate things quite significantly (need to figure out communication between those processes etc.), so I'm not sure if that's the best option.
3. Variation of the previous one, but feels a little hacky. Instead of using InMemoryChannel and flushing telemetry before exit, use the channel that writes pending telemetry to disk and then uploads it when the process is started again (Server or Persisted telemetry channel, don't remember which one does that) and start a new process that will take care of finalizing all pending telemetry. If I understand correctly, it must be the same executable as the main process, so I can probably pass a flag to indicate that this process execution is just to upload pending telemetry. But it will also need to know when all telemetry has been sent, so it can exit. Is there a way to get this information from the SDK?

Any comments or ideas would be very helpful.

SDK Version : 2.4.0
.NET Version : 4.6.2					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Windows 10
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApps, local IIS

**Comment by dennis-yemelyanov** [comment]
Can someone please take a look at this issue? Is this endpoint unstable or should we increase client timeout?

**Comment by cijothomas** [comment]
@dennis-yemelyanov There have been few network related issues in the endpoint in past few week which caused the response time to shoot up significantly. This should be fixed now, and response times should be manageable. Are you still experiencing this?

(i'll need some time to read through other questions and respond.)

**Comment by dennis-yemelyanov** [comment]
Thank you @cijothomas for confirming it was an intermittent issue. The endpoint was indeed pretty stable recently, and the last time we saw the issue was 3-4 days ago. If it was an intermittent issue and not by design, I guess having answers to other questions is not very critical (if the issue doesn't occur, we don't need to come up with workarounds to avoid timeouts).
