### ISSUE TITLE
TelemetryConfiguration.Dispose should flush the default Channel

### ISSUE THREAD

**Issue by macrogreg** [microsoft/ApplicationInsights-dotnet#823]
I think `TelemetryConfiguration.Dispose(bool disposing)` should be flushing `this.telemetrySinks.DefaultSink.TelemetryChannel` before actually disposing. Currently it does not. If this on purpose (please explain why) or an oversight?

Thanks!

P.S. !! I am adding a comment in this respect to the mentioned method. If the resolution of this issue is to leave things as they are, we should remove that coment. :)

**Comment by Dmitry-Matveev** [comment]
Thanks! There are multiple Flush() discussions going on, I think we can consolidate and address those around ~2.8.
