### ISSUE TITLE
Make Initializing TelemetryClient more intuitive

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#826]
A [customer found](https://www.reddit.com/r/Unity3D/comments/8igabt/using_microsoft_azure_app_insights_and_unity/) a combination of initializing the `TelemetryConfiguration` and `TelemetryClient` that results in no telemetry being sent to the Portal (_see code sample 1 below_). 
It's not intuitive why this doesn't work. Telemetry is visible in the Debug window and the [Visual Studio Search window](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-diagnostic-search#in-visual-studio).

This is not blocking because there are several other ways to successfully initialize the `TelemetryClient`.

1.  **This does not work:**
```
TelemetryConfiguration tcConfig = new TelemetryConfiguration();

TelemetryClient tc = new TelemetryClient(tcConfig)
{
    InstrumentationKey = ikey
};
```

2. This works:
```
TelemetryConfiguration tcConfig = new TelemetryConfiguration
{
    InstrumentationKey = ikey
};

TelemetryClient tc = new TelemetryClient(tcConfig);
```

3. This works:
```
TelemetryConfiguration tcConfig = new TelemetryConfiguration(instrumentationKey: ikey);

TelemetryClient tc = new TelemetryClient(tcConfig);
```

4. This works: [code sample from Microsoft Docs: console applications](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-console)
```
TelemetryConfiguration.Active.InstrumentationKey = ikey;

TelemetryClient tc = new TelemetryClient();
```

5. This works:
```
TelemetryConfiguration tcConfig = TelemetryConfiguration.Active;

TelemetryClient tc = new TelemetryClient(tcConfig)
{
    InstrumentationKey = ikey
};
```

In my opinion, It's confusing to have the InstrumentationKey in both places.
For 3.0, I propose that we make the `TelemetryClient.InstrumentationKey` readonly or remove it all together.
There may be a historical reason this exists, but I think we can make it better! :)

## Version Info 
Console App
SDK Version : 2.6.4
.NET Version : 4.7.1					
How Application was onboarded with SDK: VisualStudio
OS : Windows 10

**Comment by MS-TimothyMothra** [comment]
Thanks for the context discussions!

If the `TelemetryClient.InstrumentationKey` is intended to be an override of the `TelemetryConfiguration.InstrumentationKey` I think we should detail that in our summary xml. We should make every effort to steer customers to the TelemetryConfiguration property and I think we could do better! 

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/b4495b340be2dfd46ffa6137a9a4ebf2f4035452/src/Microsoft.ApplicationInsights/TelemetryClient.cs#L67-L74

**Comment by AC740** [comment]
Cool, thanks. Hope we only need to set instrumentationkey one time in future.

**Comment by MS-TimothyMothra** [comment]
Another example: https://github.com/Microsoft/ApplicationInsights-dotnet-logging/issues/240

**Comment by NeilMacMullen** [comment]
Sigh.... Just wasted a couple of hours due to this issue (in combination with the telemetry stream not automatically flushing on disposal).   The "obvious" route for anyone trying to trouble-shoot AppInsights issues is just to try to write... 

```
void Main()
{
var key = "...." ;
var client = new TelemetryClient(key)
client.GetMetric("my metric").TrackValue(1);
Console.WriteLine("sent metric - now look in the portal"); 
}
```
It would be nice if this "just worked"....

**Comment by Dmitry-Matveev** [comment]
@NeilMacMullen , the example with `GetMetric().TrackValue()` won't work even with the right Instrumentation Key setup because metrics on that API are aggregated over 1 minute and then sent. Console application will exit by then and no telemetry will be sent. `Flush()` won't help here either - there is not telemetry to `Flush()` yet - it will only appear in 1 minute. You can try Console.ReadKey() and wait for a minute (of course after you initialize Instrumentation Key in one of the working way @MS-TimothyMothra mentioned above).

**Comment by JohnTube** [comment]
Another way not mentioned in the original post can be found [here](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/LOGGING/src/Log4NetAppender/ApplicationInsightsAppender.cs#L64):

`telemetryClient.Context.InstrumentationKey = instrumentationKey;`

which is the same as

`telemetryClient.InstrumentationKey = instrumentationKey;`

but more confusing!

**Comment by CharlieDigital** [comment]
This is a really, really time wasting issue, IMO.

I have also spent several hours on this issue only resolving it after stumbling on this issue on Stack:

https://stackoverflow.com/a/52717627/116051

Very confusing.

**Comment by sonic1981** [comment]
I don't understand why someone just hasn't add an `[Obsolete()]` attribute onto this. Surely that is a 30 second job and would save a lot of confusion. I'm realising that many of the Azure classes are poorly maintained...I wonder what the AWS ones are like :no_good:

**Comment by CharlieDigital** [comment]
@sonic1981 "Grass is always greener on the other side".  I've recently been working with AWS Amplify, AppSync, and CloudFormation.

The gaps in the documentation are just as bad once you get beyond basics.

That said, CloudWatch and X-Ray are **leaps and bounds** better than AppInsights from an ease of use perspective.

**Comment by ShiningMassXAcc** [comment]
Not that I'm expecting a change of course, but just encountered this issue.
