### ISSUE TITLE
Can't see added exception details in Azure Portal 

### ISSUE THREAD

**Issue by georgiosd** [Microsoft/ApplicationInsights-dotnet#827]
Hey guys,

This is driving me nuts! I'm trying to set up a filter for an exception but because I'm not sure of the type (it's coming from linux interop assemblies and shows with a weird name), I'm trying to collect that info first.

I've added a telemetry initializer but I still see only the standard properties in the Azure portal.

My code:

```
public class MyTelemetryInitializer : ITelemetryInitializer
      {
        public void Initialize(ITelemetry telemetry)
        {
            var exceptionTelemetry = telemetry as ExceptionTelemetry;

            if(exceptionTelemetry != null)
            {
                var exception = exceptionTelemetry?.Exception;
                exceptionTelemetry.Context.Properties.Add("Message", exception.Message);
                exceptionTelemetry.Context.Properties.Add("InnerType", exception.InnerException?.GetType().Name);
                exceptionTelemetry.Context.Properties.Add("InnerMessage", exception.InnerException?.Message);
            }
        }
      }
```

At the end of my `Configure` method (ASP.NET Core 2)

```
TelemetryConfiguration.Active.TelemetryInitializers
                .Add(new MyTelemetryInitializer());
```

Any ideas???

## Version Info 
SDK Version : Microsoft.ApplicationInsights.AspNetCore 2.3.0
.NET Version : Core 2.1 rc1
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Manually
OS : Linux
Hosting Info (IIS/Azure WebApps/ etc) : Kestrel

**Comment by lmolkova** [comment]
As you are using ASP.ENT Core SDK, you should configure the TelemteryConfiguration instance created by dependency injection, rather than `TelemetryConfiguration.Active`.

Please fund more details here: https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Custom-Configuration#code-based-approach

I'm closing this for now, feel free to reopen as needed.

**Comment by georgiosd** [comment]
Thank you! How would you add a processor with DI? 

Will `RegisterSingleton<ITelemetryProcessor, MyProcessor>()` work?

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Telemetry-Processors:-Sampling-and-Metrics-Stream#adding-a-custom-telemetry-processor-to-telemetry-pipeline
