### ISSUE TITLE
Depreciate TelemetryConfiguration.Active or make it internal

### ISSUE THREAD

**Issue by zippy1981** [Microsoft/ApplicationInsights-dotnet#831]
Its quite clear the ASP.NET Team does not like TelemetryConfiguration.Active. I wasted a lot of time getting very familiar with ApplictionInnsights internals because I didn't know that. Proof

* https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/694
* https://github.com/serilog/serilog-sinks-applicationinsights/pull/60

Anyway, can you guys do the following:

* Mark it with the Obsolete attribute
* eventually make it internal

If you can't do that, will you accept a PR where at least the doc blocks explain not to use it? I really like  idea of a compiler warning occurring if you use it though, at least in ASP.NET core. Had I known from the beginning its a bad idea to use I would have gone down a different path.

**Comment by lmolkova** [comment]
@zippy1981 
Sorry to hear that.

The TelemetryConfiguration.Active is not recommended in ASP.NET **Core** only. 

We are using TeletmryConfiguration.Active in the places where dependency injection does not exist (like classic ASP.NET) and therefore have no plans to deprecate it.

We are happy to accept documentation PRs! If you have a particular article(s) you think should be modified, please submit a PR or create an issue against https://github.com/MicrosoftDocs/azure-docs (you may also label it with 'application-insights/svc') and we'll get to it.

I'm closing this for now, feel free to reopen.

**Comment by zippy1981** [comment]
Thank you @lmolkova. I'm wondering, and I'm not very familiar with how stylecop works, but is there a set of stylecop rules for Asp.NET core? If I could add a stylecop rule to have stylecop yell at you for using it in an ASP.NET package, that might warn off more developers.

I can add to the docs, and add a `<remarks/>` tag to the code itself, but I'd like an option to set off alarm bells in the IDE.
