### ISSUE TITLE
"UseSampling" is hard to discover. Consider moving it into the same namespace as TelemetryProcessorsChainBuilder

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#84]
Consider moving ```UseSampling``` into the same namespace as telemetryProcessorsChainBuilder to simplify discovery of this method

**Comment by SergeyKanzhelev** [comment]
@upendras, @vitalyf007 what do you think of moving it to the namespace ```Microsoft.ApplicationInsights.Extensibility```?

**Comment by upendras** [comment]
makes sense...right now you have to look at documentation to find it...
