### ISSUE TITLE
Reference doc spelling error in description for  OperationContext.IsPrimitive

### ISSUE THREAD

**Issue by CamSoper** [microsoft/ApplicationInsights-dotnet#843]
Hi there! I'm the docs author at the [Azure .NET SDK docs site](https://docs.microsoft.com/dotnet/azure), and a customer submitted the following issue with documentation generated from the `///` comments in your API. Please be sure to @ them in your response. Thanks! 

@dbiehle commented in https://github.com/Azure/azure-docs-sdk-dotnet/issues/646: 

at description of IsPrimitive(Object)
"Determines if a certain property is of _premitive_ JSON type."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9da3b1-4d17-5d3b-0fa3-b33e2f74f548
* Version Independent ID: 901632ad-c1b5-4a44-797e-817514621b88
* Content: [OperationContext Class (Microsoft.ApplicationInsights.Extensibility.Implementation)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.extensibility.implementation.operationcontext?view=azure-dotnet)
* Content Source: [xml/Microsoft.ApplicationInsights.Extensibility.Implementation/OperationContext.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/OperationContext.xml)
* Service: **application-insights**
* Product: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by Dmitry-Matveev** [comment]
@dbiehle, I'm addressing this with the following [PR into Azure Docs](https://github.com/Azure/azure-docs-sdk-dotnet/pull/709).

**Comment by CamSoper** [comment]
@Dmitry-Matveev @SergeyKanzhelev I'm so sorry guys, maybe I should have been clearer. I can't fix this by making a change to the XML file. Any changes I make to that XML file will be overwritten the next time the continuous integration Docs build does its thing and generates the XML files from the NuGet packages. The change has to be made in the original `///` comments in the code.

Please reopen.

**Comment by SergeyKanzhelev** [comment]
this is an extension method on `Object` defined in some external library:

See [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.systemfunctions.typecheckfunctionsextensions.isprimitive?view=azure-dotnet#Microsoft_Azure_Documents_SystemFunctions_TypeCheckFunctionsExtensions_IsPrimitive_System_Object_)
```
Definition
Namespace:
Microsoft.Azure.Documents.SystemFunctions 
Assemblies:
Microsoft.Azure.DocumentDB.Core.dll, Microsoft.Azure.Documents.Client.dll
```

@Dmitry-Matveev did the best he can

**Comment by CamSoper** [comment]
Cool, that's what I needed to know!  Thank you! :)

**Comment by SergeyKanzhelev** [comment]
BTW, when you will find their contact information - give them this reference: https://docs.microsoft.com/dotnet/standard/design-guidelines/extension-methods

Among other problems:

>X AVOID defining extension methods on System.Object. 
>VB users will not be able to call such methods on object references using the extension method syntax. VB does not support calling such methods because, in VB, declaring a reference as Object forces all method invocations on it to be late bound (actual member called is determined at runtime), while bindings to extension methods are determined at compile-time (early bound). 
>Note that the guideline applies to other languages where the same binding behavior is present, or where extension methods are not supported.

**Comment by CamSoper** [comment]
Will do! Thanks again!
