### ISSUE TITLE
TelemetryClient.Track fails for any ITelemetry with certain properties.

### ISSUE THREAD

**Issue by BrettHessman** [Microsoft/ApplicationInsights-dotnet#846]
TelemetryClient.Track(ITelemetry) will silently fail if any ITelemetry object (that also inherits from ISupportProperties) is provided with a value in its 'Properties' dictionary with a value that contains the substring "):"

## Repro Steps
1. Any setup with application insights.
2. var telemetryClient = new TelemetryClient();
3. var metricTel = new MetricTelemetry();  // any ITelemetry
4. metricTel.Properties.Add("anystring", "anystring__):__anystring");  // properties is on ISupportProperties
5. telemetryClient.Track(metricTel);
6. telemetryClient.Flush();

##  Actual Behavior
Nothing happens.

## Expected Behavior
Application Insights records ITelemetry details

## Version Info 
SDK Version : microsoft.applicationinsights\2.6.4\lib\net46\Microsoft.ApplicationInsights.dll
.NET Version : 4.6.1
How Application was onboarded with SDK(VisualStudio) :  Nuget Package + Visual Studio 2017 15.7.1
OS :  Windows 10
Hosting Info (IIS/Azure WebApps/ etc) :  Any, IIS, ConsoleApp, etc

**Comment by SergeyKanzhelev** [comment]
hm... maybe wait little longer? Still didn't show up?

![image](https://user-images.githubusercontent.com/9950081/41807146-ec0be0a2-767e-11e8-82a7-8a66c44cd737.png)

**Comment by BrettHessman** [comment]
I have tried several different ways to create a failing unit test and have had no luck so far.  I still believe there is a bug because the log4net-AI appender does not write SqlExceptions due to the reasons I explained above.  SqlExceptions, when serialized, contain a ): substring and are attached to the properties dictionary by log4net-AI causing the failure.

**Comment by BrettHessman** [comment]
I have found that this bug is with the Visual Studio debugging collector and not the core AI code.  To anyone who is worried when they don't see their application insights records when debugging SqlException and log4net AI appender, its just visual studio.  You guys can close this bug.

**Comment by gardnerjr** [comment]
what's the bug?  somehow the VS tooling can cause data to not be sent?  that doesn't make any sense to me as the VS tooling is **watching** for values to be sent, not **causing** values to be sent.

**Comment by SergeyKanzhelev** [comment]
How I read the bug is that VS fails to show event in the VS UI:

UI:
![image](https://user-images.githubusercontent.com/9950081/41929115-120b108e-792c-11e8-925a-92eb240fdccb.png)


Debug output has two items:
```
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Message","time":"2018-06-26T17:30:06.1498760Z","tags":{"ai.cloud.roleInstance":"sergkanz-dev.redmond.corp.microsoft.com","ai.operation.id":"parent","ai.operation.parentId":"|parent.3b14db15_","ai.internal.sdkVersion":"dotnet:2.7.0-6760"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"test","properties":{"key2":"value2","key1":"value1"}}}}
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Metric","time":"2018-06-26T17:30:06.2358551Z","tags":{"ai.cloud.roleInstance":"sergkanz-dev.redmond.corp.microsoft.com","ai.operation.id":"parent","ai.operation.parentId":"|parent.3b14db15_","ai.internal.sdkVersion":"dotnet:2.7.0-6760"},"data":{"baseType":"MetricData","baseData":{"ver":2,"metrics":[{"name":"n/a","kind":"Aggregation","value":0,"count":1}],"properties":{"key2":"value2","key1":"value1","anystring":"anystring__):__anystring"}}}}
```

**Comment by gardnerjr** [comment]
gotcha.  will look into it.  possibly json or regex is failing to parse that in the debug integration
