### ISSUE TITLE
server telemetry channel backlog size error message

### ISSUE THREAD

**Issue by Hammatt** [Microsoft/ApplicationInsights-dotnet#849]
Hi, I had an issue today where I was setting the backlog size to 1, which was throwing
 `ArgumentOutOfRangeException("value")`, this error message is pretty un-descriptive and I had to come and look at the source to work out what I was doing wrong!

Would be great if you could update line 102 in `ApplicationInsights-dotnet/src/ServerTelemetryChannel/Managed/Shared/Implementation/TelemetryBuffer.cs` https://github.com/Microsoft/ApplicationInsights-dotnet/blob/e544ffae4f3188bde01a367364ea3e36f2bf03a9/src/ServerTelemetryChannel/Managed/Shared/Implementation/TelemetryBuffer.cs#L102 to something a bit more descriptive! 
Thanks

**Comment by MS-TimothyMothra** [comment]
Thank you for reporting. Would you like to submit a PR for this?

**Comment by Hammatt** [comment]
I can do sometime over the next week if that's fine.

**Comment by Hammatt** [comment]
I've created a pull request for this issue. I had some issues locating the right branch until I realised I was using the dotnet standard version of the library which seems to be hosted in a different branch?  
Please let me know if I've done anything wrong. I've also not been able to run the unit tests as described as I don't have visual studio on linux.
