### ISSUE TITLE
ApplicationInsights 2.6.4: Exception: System.InvalidCastException in Azure WebApps

### ISSUE THREAD

**Issue by Leftyx** [Microsoft/ApplicationInsights-dotnet#855]
## Repro Steps
1. Add nuget package Microsoft.ApplicationInsights
2. Publish to Azure Web App

##  Actual Behavior

After an upgrade to ApplicationInsights 2.6.4 we have started to notice these random errors in Azure WebApps. I wasn't happening before, we a previous SDK.

Random trace exceptions

```
AI (Internal): Callback 'OnNext' failed for id = '0'. Exception: System.InvalidCastException: Unable to cast object of type '<>f__AnonymousType3`3[System.Net.HttpWebRequest,System.Net.HttpStatusCode,System.Net.WebHeaderCollection]' to type '<>f__AnonymousType2`2[System.Net.HttpWebRequest,System.Net.HttpWebResponse]'.
 at Microsoft.ApplicationInsights.DependencyCollector.Implementation.PropertyFetcher.PropertyFetch.TypedFetchProperty`2.Fetch(Object obj)
 at Microsoft.ApplicationInsights.DependencyCollector.Implementation.PropertyFetcher.Fetch(Object obj)
 at Microsoft.ApplicationInsights.DependencyCollector.Implementation.HttpDesktopDiagnosticSourceListener.OnNext(KeyValuePair`2 value)
```

## Expected Behavior

`No exceptions`

## Version Info 
SDK Version : 2.6.4
.NET Version : 4.6.2 + ASP.NET MVC 5.2.6 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS :
Hosting Info (IIS/Azure WebApps/ etc) : Azure WebApps

**Comment by lmolkova** [comment]
Hi, @leftyx, thank for reporting it.

I believe we have fixed it in: https://github.com/Microsoft/ApplicationInsights-dotnet-server/pull/919. Please try latest ApplicaitonInsights 2.7.0 latest best version.

I'm closing this, feel free to reopen.
