### ISSUE TITLE
Application insights working without config

### ISSUE THREAD

**Issue by jonnovaretti** [microsoft/ApplicationInsights-dotnet#862]
I'm building a small library that use Application Insights.

Is there a possibility Application Insights working without ApplicationInsights.config file?

I tried remove and add the modules manually at constructor, but it didn't work.

**Comment by MS-TimothyMothra** [comment]
Hi @jonnovaretti,
Please try these instructions and let us know if you run into any problems:
https://docs.microsoft.com/azure/application-insights/application-insights-console

**Comment by jonnovaretti** [comment]
hi @MS-TimothyMothra,

I already have tried this sample. It works when I add the ApplicationInsights.config file, but when I remove the file, it stop working.

**Comment by MS-TimothyMothra** [comment]
Can you share your code here of how you're configuring ApplicationInsights?
remove anything sensitive (ex: ikey).

**Comment by jonnovaretti** [comment]
Sure! No problem...

Just adicional information. When I exclude the config file, it doesn't work, but when I just remove the content of file, it works.

My code:

`public Telemetry(ILogger logger)
        {
            TelemetryConfiguration configuration;
            ApplicationInsightsConfig applicationInsightsConfig;

            configuration = TelemetryConfiguration.Active;
            configuration.ApplicationIdProvider = new ApplicationInsightsApplicationIdProvider();

            configuration.DisableTelemetry = false;

            applicationInsightsConfig = ReaderConfig.ReadConfig();

            if (!applicationInsightsConfig.InstrumentationKey.Equals(EMPTY_TOKE))
                configuration.InstrumentationKey = applicationInsightsConfig.InstrumentationKey;
#if DEBUG
            configuration.InstrumentationKey = string.Empty;
#endif
            configuration.TelemetryInitializers.Add(new HttpDependenciesParsingTelemetryInitializer());
            configuration.TelemetryInitializers.Add(new AzureRoleEnvironmentTelemetryInitializer());
            configuration.TelemetryInitializers.Add(new AzureWebAppRoleEnvironmentTelemetryInitializer());
            configuration.TelemetryInitializers.Add(new BuildInfoConfigComponentVersionTelemetryInitializer());

            configuration.TelemetryProcessorChainBuilder.Use((next) => { return new AutocollectedMetricsExtractor(next); })
                                                        .Use((next) => { return new QuickPulseTelemetryProcessor(next); })
                                                        .UseAdaptiveSampling()
                                                        .Build();

            configuration.TelemetryChannel = new ServerTelemetryChannel();

            var telemetryLocal = new DeveloperModeWithDebuggerAttachedTelemetryModule();
            telemetryLocal.Initialize(configuration);

            TelemetryModules.Instance.Modules.Add(telemetryLocal);

            client = new TelemetryClient(configuration);
            this.logger = logger;
        }`

**Comment by jonnovaretti** [comment]
@MS-TimothyMothra, I'm debugging Microsoft.ApplicationInsights and I've see different behavior between delete file config and remove all content from file.

In this part of code:
 ```
// Load configuration from the specified configuration
                if (!string.IsNullOrEmpty(serializedConfiguration))
                {
                    try
                    {
                        XDocument xml = XDocument.Parse(serializedConfiguration);
                        LoadFromXml(configuration, modules, xml);
                    }
                    catch (XmlException exp)
                    {
                        CoreEventSource.Log.ConfigurationFileCouldNotBeParsedError(exp.Message);
                    }
                }
```
When there is empty file,

**Comment by MS-TimothyMothra** [comment]
This line looks suspicious to me:
`applicationInsightsConfig = ReaderConfig.ReadConfig();`
and
`configuration.InstrumentationKey = applicationInsightsConfig.InstrumentationKey;`


Can you confirm for me that this is not the `applicationinsights.config` that you're removing from your project?

I would expect that you store your Ikey in the `app.config` for your project.

---

If that doesn't work, try testing with a simpler configuration and only adding extra as you need them.

I know for a fact that this works in a sample console app:

```
TelemetryConfiguration tcConfig = TelemetryConfiguration.Active;
tcConfig.InstrumentationKey = "myikey";
TelemetryClient tc = new TelemetryClient(tcConfig);
```

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
