### ISSUE TITLE
Include XML doc into the package

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#863]
Xmldoc should be included into the package for intellisense.

This was lost between `2.5.0-beta1` and `2.5.0-beta2`

![image](https://user-images.githubusercontent.com/9950081/42772717-1d3dddb0-88e0-11e8-8664-cef1dad4f7e3.png)

**Comment by Dmitry-Matveev** [comment]
We'd need to review Web SDK, Logging SDK and ASPNET Core SDK as per Sergey's comment on PR #870 .

**Comment by Dmitry-Matveev** [comment]
The following packages in 2.7 do not have XML Doc in the output:
- PerfCounter Collector package for target: 4.5
- Intercept package for targets: 4.0/4.5
- Logging package (on example of Trace Listener) for targets: 4.5/1.3

Web, Dependency and Windows Server packages seem to have XML Doc.

**Comment by Dmitry-Matveev** [comment]
All packages are addressed.
