### ISSUE TITLE
ITelemetry.DeepClone doesn't clone context properties

### ISSUE THREAD

**Issue by zakimaksyutov** [Microsoft/ApplicationInsights-dotnet#872]
ITelemetry.DeepClone doesn't clone context properties. It has a few issues:
1. Telemetry item is partly cloned => misleading
2. It's error prone to write copying all context properties
3. Code will not handle copying any further context properties

Should this function copy everything?

Workaround:

```
            var cloned = item.DeepClone();
            cloned.Context.Component.Version = item.Context.Component.Version;
            cloned.Context.Cloud.RoleInstance = item.Context.Cloud.RoleInstance;
            cloned.Context.Cloud.RoleName = item.Context.Cloud.RoleName;
            cloned.Context.Device.Id = item.Context.Device.Id;
            cloned.Context.Device.Model = item.Context.Device.Model;
            cloned.Context.Device.OemName = item.Context.Device.OemName;
            cloned.Context.Device.OperatingSystem = item.Context.Device.OperatingSystem;
            cloned.Context.Device.Type = item.Context.Device.Type;
            cloned.Context.Location.Ip = item.Context.Location.Ip;
            cloned.Context.Operation.Id = item.Context.Operation.Id;
            cloned.Context.Operation.CorrelationVector = item.Context.Operation.CorrelationVector;
            cloned.Context.Operation.Name = item.Context.Operation.Name;
            cloned.Context.Operation.ParentId = item.Context.Operation.ParentId;
            cloned.Context.Operation.SyntheticSource = item.Context.Operation.SyntheticSource;
            cloned.Context.Session.Id = item.Context.Session.Id;
            cloned.Context.Session.IsFirst = item.Context.Session.IsFirst;
            cloned.Context.User.Id = item.Context.User.Id;
            cloned.Context.User.AccountId = item.Context.User.AccountId;
            cloned.Context.User.AuthenticatedUserId = item.Context.User.AuthenticatedUserId;
            cloned.Context.User.UserAgent = item.Context.User.UserAgent;
```

**Comment by SergeyKanzhelev** [comment]
CC: @karolz-ms 

Are you sure? I see the call to it here for instance: https://github.com/Microsoft/ApplicationInsights-dotnet/blob/fa05efa428e4ed00f1a71874249d1de35b5bb691/src/Microsoft.ApplicationInsights/DataContracts/DependencyTelemetry.cs#L96

**Comment by zakimaksyutov** [comment]
Unless this was changed in recent-recent beta - yes. It looks like that DeepClone on context copies only properties (and it looks like it saves them by reference, not actually clones) and global properties. But above fields are not filled.

**Comment by lmolkova** [comment]
BTW, BeginTimeInTicks is not cloned: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/789

**Comment by karolz-ms** [comment]
If that is the case, it is a bug and should be fixed. `DeepClone` is supposed to, well, clone everything deeply

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/992 Duplicated. Its fixed.
