### ISSUE TITLE
Enhanced editing functionality for ExceptionTelemetry

### ISSUE THREAD

**Issue by tokaplan** [microsoft/ApplicationInsights-dotnet#879]
As of #865, it is now possible to modify exception data contained within an ExceptionTelemetry object. However, the list of ExceptionDetails objects is read-only, so it is not possible to remove or add elements. This might be necessary in certain scenarios (like clearing out unwanted inner exceptions).

**Comment by SergeyKanzhelev** [comment]
Also helper methods to construct the correct `id` and `outerId` indexes for exception collection may be useful
