### ISSUE TITLE
Add Session.ID into default sampling score 

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#88]
Sampling score today is calculated based on ```User ID``` followed by ```Operation ID``` if ```User ID``` is not available. See https://github.com/Microsoft/ApplicationInsights-dotnet/blob/9f4c715fa703753c2e6107afde79051447018a02/src/TelemetryChannels/ServerTelemetryChannel/Shared/Implementation/SamplingScoreGenerator.cs

The issue is that in case when the number of sessions is much bigger than number of users and moreover - set of users is never changed - statistics may be skewed as the same user will be sampled out all the time.

Thus the idea is to use ```Session ID ``` as a first ID to calculate sampling score.

**Comment by AlexBulankou** [comment]
I agree with SessionID proposal. Sampling by User ID effectively us blind to the experience of all users who are sampled out. What is worse, when stable user ID is used (that cannot be updated when  cookies are cleared) there is simply no telemetry to detect problems that are consistently affecting the same users. Session ID offers the same benefits as User ID does (except the ability to track the user across sessions, which I would argue is not typical investigation scenario), without the drawbacks of specific user blindness.

**Comment by SergeyKanzhelev** [comment]
Just had a chat with @vitalyf007 and he made a valid point that users metrics will be skewed once we will switch to ```Session ID``` - based sampling. For instance this page will not show accurate numbers:

![image](https://cloud.githubusercontent.com/assets/9950081/10737978/5064cbea-7bd2-11e5-80e3-9843a7c2526a.png)

Ideally we need to identify which metrics we are trying to make accurate and which scenarios to keep.

**Comment by AlexBulankou** [comment]
It is correct that with sampling we can preserve only one correct dimension: Unique users, unique sessions and unique page views. For the one that we keep unique metrics and impact calculation will be correct (with our gain-ups), it won't be correct for the other ones. The question - which one do we pick based on the fact that we are focusing on best diagnostics (not usage) experience.  And this is where session ID has advantage over user ID, because it doesn't persist for eternity as user ID does (when customers override default user ID assignment that is based on something like their account).

**Comment by vitalyf007** [comment]
Theoretically we could add an extensibility point where customer would be able to provide "sampling base" strategy. Essentially, a function Func<ITelemetry, string> taking telemetry item in and returning a string that would be used for sampling score computation. By default it would be user id / operation id whichevery is specified.

That said, figuring out which property would be best to serve as "sampling base" is very difficult for customer. We do reasonably good default - user id/operation id. Choosing session id would kill user-related metrics (given a page how many users from US visited it, etc). 

The trick is that even if you do make a choice somehow, how do you validate it was the right one? Based on that I'd be hesitant to introduce this extensiblity point right now.
Remember that if you want to be able to find a particular something (a given request by its id, session by id or user having a problem) you can't use sampling in AI.

**Comment by SergeyKanzhelev** [comment]
I'm closing this issue for now to get some feedback from real life applications monitoring. Will watch closely internal apps telemetry.
