### ISSUE TITLE
Number of threads increasing significantly when calling TrackEvent

### ISSUE THREAD

**Issue by chadbert** [microsoft/ApplicationInsights-dotnet#895]
If you are not able to reproduce this, I have a project that I can show you that reproduces it.

## Repro Steps
1. Switch from 2.7.0 Beta 1 to 2.7.0 Beta 2 nuget package
2. Add an API entry point that takes a dictionary of string, string and calls TelemetryClient.TrackEvent
3. Debug on local machine and monitor the Threads window in Visual Studio
4. Log several events

##  Actual Behavior
Occasionally a thread remains instead of disappearing. For every 100 log events, I am seeing about 15-30 extra threads that stay around.
Over time I see hundreds to thousands of threads located at Microsoft.ApplicationInsights.dll!Microsoft.ApplicationInsights.Metrics.DefaultAggregationPeriodCycle.Run
See the attached thread window picture where I debugged for only a few minutes and was able to get about 60 threads in this method.
![appinsightsthreads](https://user-images.githubusercontent.com/20522587/44120309-d5567798-9fd0-11e8-84b1-d24e20d776f6.png)

Also see the attached thread count of our API app over time. We updated the package from 2.6.1 to 2.7.1 right when the thread count starts climbing. The thread count peaked at 5950 before the service fell over.
![image](https://user-images.githubusercontent.com/20522587/44120498-602c9442-9fd1-11e8-984d-8c4fadf7057c.png)

## Expected Behavior
The beta 1 version and prior versions do not contain any threads that stay around in the DefaultAggregationPeriodCycle.Run method.

## Version Info 
SDK Version : Microsoft.ApplicationInsights 2.7.0 Beta 2 and newer (Beta 2 introduces the issue)
.NET Version :	4.7 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : Visual Studio via nuget
OS : Windows 10 1803 (17134.191)
Hosting Info (IIS/Azure WebApps/ etc) : Both on dev box (IIS Express) and Azure Api App

**Comment by cijothomas** [comment]
Working to get repro. @macrogreg also to help.

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/806 - Was done in 2.7.0-beta2, which could have introduced a bug. (Dont have repro yet)

**Comment by cijothomas** [comment]
This is very much like this:
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/364

A new telemetry configuration instance is created with every request, which is not GC'ed as something is holding on to it - in this case the MetricAggregator. 
As a workaround for now, please re-use TelemetryConfiguration instance, instead of creating new.
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/364#issuecomment-393543005
