### ISSUE TITLE
Re-Enable Warnings as Errors

### ISSUE THREAD

**Issue by MS-TimothyMothra** [Microsoft/ApplicationInsights-dotnet#899]
Need to re-enable Warnings as Errors when all FxCop issues have been addressed.

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/91e9c91fcea979b1eec4e31ba8e0fc683bf86802/Common.props#L32-L33

Should only enable for Release builds.

**Comment by SergeyKanzhelev** [comment]
> Should only enable for Release builds.

This wasn't working well before. Lots of complains that locally everything works and then you discover that the build is broken

**Comment by MS-TimothyMothra** [comment]
We should discuss this as a team.
We've been getting a lot of complaints that devs can't quickly test prototypes because of strict code style rules.
