### ISSUE TITLE
TelemetryClient.Flush() does not respect Telemetry Sinks and only flushes default channel

### ISSUE THREAD

**Issue by Dmitry-Matveev** [microsoft/ApplicationInsights-dotnet#904]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. Configure several Telemetry Sinks, e.g. with
```
<TelemetrySinks>
     <Add Name="Custom">
         <TelemetryChannel Type="SimpleFileChannel.FileChannel, SimpleFileChannel">
           <MyProperty>MyValue</MyProperty>
         </TelemetryChannel>
     </Add>
 </TelemetrySinks>
```

2. Call Flush() on default TelemetryClient instance created off TelemetryConfiguration.Active be default

##  Actual Behavior
Only default channel, such as ServerTelemetryChannel get Flush() request.
Custom channel, such as aforementioned FileChannel configured with Telemetry Sink concept does not get Flush() call.

## Expected Behavior
All configured channels Flush() upon such call on TelemetryClient object.

## Version Info 
SDK Version : 2.8-b1
.NET Version :	Any Supported					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VS
OS : Any
Hosting Info (IIS/Azure WebApps/ etc) : Local

**Comment by cijothomas** [comment]
Related: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/823

**Comment by Dmitry-Matveev** [comment]
Most of the 2.8 customers with many Telemetry Sinks are expected to monitor services environments where call to Flush() is less expected than in console/desktop/worker apps. We can implement this in 2.9 to address customer feedback is any.

However, considering the size of the change (iteration over TelemetrySinks and calling Flush() on every ITelemetryChannel) - we can take it for 2.8 is it's trivial.
