### ISSUE TITLE
Supply default values, required flag and string limits to the JsonSerializationWriter

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-dotnet#905]
I'd suggest to improve `JsonSerializationWriter` by having separate methods for writing optional vs. required properties as well as provide default value for fields where applicable and require to specify string limit.

This will ensure that schema for the type can be generated better and there will be no need in Sanitize method which will improve performance.

**Comment by MS-TimothyMothra** [comment]
When would we serialize an optional vs a required property?
