### ISSUE TITLE
Add Sampling, AutoCollectedMetricExtractor TelemetryProcessors to the Default sink instead of on common pipeline.

### ISSUE THREAD

**Issue by cijothomas** [Microsoft/ApplicationInsights-dotnet#907]
Similar to being done for asp.net core, https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/752, need to modify XDT transformations so that Sampling, AutoCollectedMetricExtractor are added into the default sink's TP, and not on the main telemetry processor pipeline.

**Comment by SergeyKanzhelev** [comment]
@cijothomas is it done now? Please close
