### ISSUE TITLE
Should ITelemetryProcessor filtered items show in VisualStudio/Azure

### ISSUE THREAD

**Issue by phatcher** [microsoft/ApplicationInsights-dotnet#920]
I have an ITelemetryProcessor to filter out the webjob blob/queue 404 internal errors which is configured to be the first item in process chain.

I can debug and see that it's correctly determining that these items should not be forwarded, however they are still appearing in the AI event list in Visual Studio and AI on Azure is still seeing them.

I'm initialising AI like this...
```
public static void Initialize(string name = null, string component = null)
{
	var key = ConfigurationManager.AppSettings["APPINSIGHTS_INSTRUMENTATIONKEY"];

	if (string.IsNullOrEmpty(key) && !System.Diagnostics.Debugger.IsAttached)
	{
		TelemetryConfiguration.Active.DisableTelemetry = true;
		return;
	}

	TelemetryConfiguration.Active.TelemetryInitializers.Add(new ApplicationTelemetryInitializer(name, component));
	if (!string.IsNullOrEmpty(key))
	{
		TelemetryConfiguration.Active.InstrumentationKey = key;
	}
}
```
My ApplicationInsights.config file is as per the nuget package version with the addition of my custom ITelemetryProcessor

**Comment by SergeyKanzhelev** [comment]
When you run in Visual Studio - do you see any errors in debug window starting with `AI:` or something like this stating that initialization of you telemetry processor failed? This would probably be a culprit.

Also try to set a breakpoint in your telemetry initializer to confirm it was never called.

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
