### ISSUE TITLE
Actually Complete documentation before stable release

### ISSUE THREAD

**Issue by EnCey** [Microsoft/ApplicationInsights-dotnet#925]
## Repro Steps
1. The official documentation is littered with "@ToDo: Complete documentation before stable release" remarks, actual documentation is missing

##  Actual Behavior
Incomplete documentation after stable release

## Expected Behavior
Complete documentation before stable release

## Version Info 
SDK Version : `Microsoft.ApplicationInsights 2.7.2`
.NET Version : `*`
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS : `*`
Hosting Info (IIS/Azure WebApps/ etc) : `*`

## Evidence
[Microsoft.ApplicationInsights.Metrics Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.metrics?view=azure-dotnet)
[MetricManager](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.metrics.metricmanager?view=azure-dotnet)

[`IMetricSeriesConfiguration.RequiresPersistentAggregation`](https://docs.microsoft.com/en-ie/dotnet/api/microsoft.applicationinsights.metrics.imetricseriesconfiguration.requirespersistentaggregation?view=azure-dotnet#Microsoft_ApplicationInsights_Metrics_IMetricSeriesConfiguration_RequiresPersistentAggregation) for example says: `Gets a value indicating whether @ToDo: Complete documentation before stable release. {016}`

I have no idea what this does and there is absolutely no way for me to find out other than reading the source code.

**Comment by MS-TimothyMothra** [comment]
Thank you @EnCey for reporting this.
I'm working with the developer to get this fixed. 

I'm closing this issue as a duplicate, please feel free to comment on the original issue #817

**Comment by MS-TimothyMothra** [comment]
@EnCey I know that this is not a substitute for proper documentation, but we have two feature tutorials here:

https://github.com/Microsoft/ApplicationInsights-dotnet/issues/774
https://github.com/Microsoft/ApplicationInsights-dotnet/issues/784

**Comment by EnCey** [comment]
Sorry for the duplicate, I searched for the text "Complete documentation before stable release" but #817 isn't found when doing that :/ 

Thank you for the tutorials, much obliged!
