### ISSUE TITLE
when use GetMetrics().TrackValue(), no metrics are uploaded in azure portal.

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-dotnet#936]
I have installed appInsights 2.7.2, and when I used this method 
`Telemetry_Client.GetMetric("test12").TrackValue(50);` , then I cannot find metric in the azure portal, even in the Analytics -> CustomMetrics, there is no the metric. And in the visual studio output window, I can see this line: Application Insights Telemetry (unconfigured): xxx, what's the meaning of the (unconfigured) here?

But If use TrackMetric(), the metric can be found in azure portal as well as in Analytics.

Is there something I missed for using GetMetric().TrackValue()?

**Comment by cijothomas** [comment]
How are you configuring ikey for the telemetry client? 'Unconfigured' in debug output indicates no ikey is present.

Did you use same TelemetryClient for TrackMetric() and GetMetric().TrackValue() as well ?

**Comment by cijothomas** [comment]
Also - GetMetric("test12").TrackValue(50) does not instantly send the metric to backend - it aggregates inmemory, and sends after some time. Make sure you wait enough time.. (I can look at the docs to find exact time but i think aggregation is done in 1min intervals)

**Comment by imeya** [comment]
@cijothomas , the ikey is configured, and works for TrackMetric(). I'll try to wait for a long time, and let you know the result.

**Comment by imeya** [comment]
I found that in the vs output window, there is no ikey in this line: Application Insights Telemetry (unconfigured) {no ikey here}.  But if use TrackMetric, the ikey shows there.

**Comment by imeya** [comment]
And I found the very tricky thing, if I set the ikey in this code: `TelemetryConfiguration.Active.InstrumentationKey = "my key";  ` , it works well and metric can be sent to azure portal. I cannot figure out the difference between the two ways of ikey setting.

**Comment by cijothomas** [comment]
@imeya Glad you have a workaround. We'll investigate and response if this is intended behaviour or an actual bug.

**Comment by cijothomas** [comment]
CC: @macrogreg Please comment on this when you get a chance! Thanks.

**Comment by tarikguney** [comment]
I have been seeing this behavior since yesterday. I am glad someone figured out a workaround.

**Comment by tarikguney** [comment]
> Also - GetMetric("test12").TrackValue(50) does not instantly send the metric to backend - it aggregates inmemory, and sends after some time. Make sure you wait enough time.. (I can look at the docs to find exact time but i think aggregation is done in 1min intervals)

I have been waiting for a whole day to see the collected metrics but it won't appear. I think the issue is not timing here. It does not upload anything.

**Comment by tarikguney** [comment]
> @tarikguney , just a FYI, the code `GetMetric("test12").TrackValue(50)` works well at my side. Metrics can be shown in portal.

Thanks for letting me know. Mine does not work but using `TelemetryConfiguration.Active.InstrumentationKey` made it work.

**Comment by cijothomas** [comment]
The pre-aggregating metric API, does not respect anything on telemetryclient, which is by design. I have digged into this bit more while working on a similar issue reported in another channel. This was reported by several customers now.
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1228#issuecomment-542360416

We are treating this as a documentation issue, and not product bug.  Docs issue link:
https://github.com/MicrosoftDocs/azure-docs/issues/40231

**Comment by cijothomas** [comment]
The right way to set instrumentation key is to set on TelemetryConfiguration
// The below doesn't work.
AIClient = new TelemetryClient();
AIClient.InstrumentationKey = appInsightsKey;

 // the below does work.
var config = TelemetryConfiguration.CreateDefault();
config.InstrumentationKey = appInsightsKey;
AIClient = new TelemetryClient(config);


AIClient.getmetric().Track()...
