### ISSUE TITLE
The ways to set instrumentation key behaves differently.

### ISSUE THREAD

**Issue by imeya** [microsoft/ApplicationInsights-dotnet#941]
I have an Azure function, and integrated with app insights. I found that use different way to set ikey, it behaves differently.

1. use `TelemetryClient telemetryClient = new TelemetryClient(new TelemetryConfiguration{InstrumentationKey ="your_key"});` , then no operation_id appears in app insights(no this item operation_id in app insights).

2. if use `TelemetryClient telemetryClient = new TelemetryClient() { InstrumentationKey = "your_key" };`, then the operation_id appears in app insights in azure portal.

so could somebody let me know what's the difference between them? thanks.

My sample code is as below:
 ```
public static class Function1
    {

        private static TelemetryClient telemetryClient = new TelemetryClient() { InstrumentationKey = "your_key" };  // the operation_id appears in app insight

// **the following way, no operation_id appears**
//     private static TelemetryClient telemetryClient = new TelemetryClient(
//     new Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration
//     {
//       InstrumentationKey = "your_key";
//     });
  

        [FunctionName("Function2")]
        public static HttpResponseMessage Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)]HttpRequestMessage req)
        {
            RequestTelemetry requestTelemetry = new RequestTelemetry { Name = "Function211" };
            var operation = telemetryClient.StartOperation(requestTelemetry);

            telemetryClient.TrackTrace("trace message 111", SeverityLevel.Error);
            telemetryClient.TrackException(new System.Exception("My custom exception 111"));


            operation.Telemetry.Success = true;
            telemetryClient.StopOperation(operation);

            return req.CreateResponse(HttpStatusCode.OK, "Hello ");
        }
    }

```

**Comment by imeya** [comment]
and I submitted an [issue ](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/936) before, it's also related to the ways to set ikey. I think somebody should point out the difference between them.

**Comment by MS-TimothyMothra** [comment]
This sounds related to #826

**Comment by TimothyMothra** [comment]
I'm closing this ticket as out of date.
If you're still having issues, please reopen.
