### ISSUE TITLE
Exception while initializing Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer

### ISSUE THREAD

**Issue by VeselovAndrey** [microsoft/ApplicationInsights-dotnet#948]
## Repro Steps
1. Create .NET project (in my case this is VS2017 extension)
2. Add Microsoft.ApplicationInsights NuGet package
3. Use following simple class to log exceptions:
`
internal class AppInsightLogger : ILogger
{
    private readonly TelemetryClient _telemetryClient;

    static AppInsightLogger()
    {
        TelemetryConfiguration.Active.InstrumentationKey = "HARDCODED KEY HERE";
    }

    public AppInsightLogger()
    {
        this._telemetryClient = new TelemetryClient();
        this._telemetryClient.Context.Session.Id = Guid.NewGuid().ToString();
        this._telemetryClient.Context.Device.OperatingSystem = Environment.OSVersion.ToString();
        this._telemetryClient.Context.Component.Version = Assembly.GetAssembly(typeof(AppInsightLogger)).GetName().Version.ToString();
    }

    // This method called inside "catch (Exception ex)" block.
    public void Exception(Exception ex)
    {
        this._telemetryClient.TrackException(ex);
    }
`
##  Actual Behavior
I getting following message when trying to log exception (and exception not logged)

Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.f61d879187d04c2fb005eb6fd456ac6e.Message","time":"2018-10-10T09:38:59.1069179Z","iKey":"f61d8791-87d0-4c2f-b005-eb6fd456ac6e","tags":{,"ai.operation.syntheticSource":"SDKTelemetry","ai.internal.sdkVersion":"dotnet:2.7.2-23439"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"AI (Internal): [msg=Log Error];[msg=Exception while initializing Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer, exception message - System.TypeLoadException: Could not load type 'System.Diagnostics.Activity' from assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.\r\n   at Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer.<>c__DisplayClass0_0.<Initialize>b__0()\r\n   at Microsoft.ApplicationInsights.ActivityExtensions.TryRun(Action action)\r\n   at Microsoft.ApplicationInsights.Extensibility.OperationCorrelationTelemetryInitializer.Initialize(ITelemetry telemetryItem)\r\n   at Microsoft.ApplicationInsights.TelemetryClient.Initialize(ITelemetry telemetry)]"}}}

System.Diagnostics.DiagnosticSource was not included into project before and installed with AI package as dependency. I tried to upgrade System.Diagnostics.DiagnosticSource from 4.5.0 (installed with AI) to latest but it not help.

## Expected Behavior
Exception logged, no AI internal error.

## Version Info 
SDK Version : 2.7.2
.NET Version :	4.5						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Windows 10

**Comment by VeselovAndrey** [comment]
Rollback to 2.3.0 helps (no code changes). This latest version which not depends on System.Diagnostics.DiagnosticSource.

Starting from 2.4.0 AI depends on System.Diagnostics.DiagnosticSource and I getting error above.

**Comment by lmolkova** [comment]
I've been trying to reproduce the issue without any success.

I assume you somehow have binding redirects set to 4.0.1.0 and it's not found of course, as new AI SDK brings 4.0.3.0

Would you mind providing a small repro app?

**Comment by robintschroeder** [comment]
I am also seeing this problem while building a VS 2019 extension. 
I can confirm that rolling back to 2.3.0 resolves the issue, but it isn't a long term solution!

**Comment by pharring** [comment]
Using `TelemetryConfiguration.Active` in an extension is, unfortunately, asking for trouble. You're competing with any other extension (including built-in Visual Studio components) that might also be using TelemetryConfiguration.Active -- and they may load first with a binding redirect. That's likely what's happening here.

Extension authors should new up their own TelemetryConfiguration instances.
For example, see one of my own extensions: https://github.com/pharring/EditorGuidelines/blob/master/src/ColumnGuide/Telemetry.cs#L41

Note also that I elected to go with a super-old version of App Insights (2.1.0) for maximum compatibility:
https://github.com/pharring/EditorGuidelines/blob/master/src/ColumnGuide/ColumnGuide.csproj#L20
