### ISSUE TITLE
Why TelemetryChannel depends on System.Web.Extensions?

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-dotnet#950]
I noticed a weird reference to System.Web.Extensions in the channel package.
There is no code that depends on it and no tests that fail if it's removed. 

The package contains AJAX-related methods that do not seem to be relevant to the server telemetry channel.

Can we remove it?

@SergeyKanzhelev @MS-TimothyMothra @Dmitry-Matveev ?

**Comment by Dmitry-Matveev** [comment]
Unless it's some conditional reference that adds/supports some interface method on .NET 4.5 that is added to System.Web only in .NET 4.6+, it looks like it can be safely removed.

Compilation on 4.6 will succeed in such a case, including all tests. Compilation on 4.5 may fail with "Method not Found". Should be easy to test out.
