### ISSUE TITLE
Adding TelemetrySinks does not automatically send data to them

### ISSUE THREAD

**Issue by RamjotSingh** [Microsoft/ApplicationInsights-dotnet#957]
## Repro Steps
1.  Implement new ITelemetryChannel
2. Create a new TelemetryConfiguration
3. Create new TelemetrySink with custom TelemetryChannel by doing new TelemetrySink(config, new TelemetryChannel)
4. Add the new TelemetrySink to TelemetryConfiguration.TelemetrySinks
5. Create new TelemetryClient using the configuration above
6. Send a telemetry item through TelemetryClient (type does not matter)

##  Actual Behavior
Telemetry item is only sent to default sink.

## Expected Behavior
Telemetry item should be sent to both (default AI and custom) sinks.

## Version Info 
SDK Version : 2.8.0
.NET Version :	.NetCore2.1					
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Win10
Hosting Info (IIS/Azure WebApps/ etc) : N/A

I looked a little deeper, I think the issue is in the [PassThroughProcessor](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/39a5ef23d834777eefdd72149de705a016eb06b0/src/Microsoft.ApplicationInsights/Extensibility/Implementation/PassThroughProcessor.cs). PassThroughProcess is the default and last processor. But it only send the telemetry to default sink. This means other sinks will not get telemetry item.

**Comment by SergeyKanzhelev** [comment]
@RamjotSingh can you please provide a code example? Unit tests passes. Specifically this one that doing exactly what you describe. Perhaps some issue with global config overriding local config. In any case - please provide some repro, please:

https://github.com/Microsoft/ApplicationInsights-dotnet/blob/39a5ef23d834777eefdd72149de705a016eb06b0/Test/Microsoft.ApplicationInsights.Test/Shared/Extensibility/TelemetrySinkTests.cs#L151-L183

**Comment by RamjotSingh** [comment]
[TestTelemetryChannel.zip](https://github.com/Microsoft/ApplicationInsights-dotnet/files/2496648/TestTelemetryChannel.zip)
Here is a sample project showing the issue. I have added a TelemetryChannel class to it and added the sink on top of it. Then called TrackTrace from the controller. You can put breakpoint and see that Send is never called.

**Comment by SergeyKanzhelev** [comment]
@cijothomas can you please take a look?

**Comment by cijothomas** [comment]
```
            telemetryConfiguration.TelemetrySinks.Add(new TelemetrySink(telemetryConfiguration, new TelemetryChannel()));
            telemetryConfiguration.TelemetryProcessorChainBuilder.Build();
```

Please call `Build()` after adding sinks. This is required to build the Broadcast processor (as opposed to passthrough)

**Comment by RamjotSingh** [comment]
It is not obvious that needs to happen. At the very least this should be documented. For TelemetryProcessors it is still discoverable but not in this case.

**Comment by cijothomas** [comment]
Unfortunately TelemetrySinks are not yet in official docs page :( Only doc is some Github issues.
We'll add documentation about sinks soon to official pages.
