### ISSUE TITLE
Do you support .net standard 2.0?

### ISSUE THREAD

**Issue by srini1978** [Microsoft/ApplicationInsights-dotnet#963]
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
1. 
2. 

## Version Info 
SDK Version :   2.8.1
.NET Version :	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS :
Hosting Info (IIS/Azure WebApps/ etc) :

**Comment by cijothomas** [comment]
SDK is compiled against netstandard1.3, and hence you can use it with a netstandard2.0 app.
