### ISSUE TITLE
It still take some time to see telemetry data in azure portal after enable the developer mode

### ISSUE THREAD

**Issue by imeya** [Microsoft/ApplicationInsights-dotnet#964]
When I enable the developer mode using the following code:
`TelemetryConfiguration.Active.TelemetryChannel.DeveloperMode = true;`

As per document, the telemetry should be sent asap.
But it still take some time(like 1 or 2 minutes) then I can see the logs in azure portal, why?

**Comment by cijothomas** [comment]
DeveloperMode=true means SDK does not buffer items for sending, instead it is sent immediately to Application Insights backend. Data appears in Azure Portal in few minutes  - 2-5 mins typically. 

If your requirement is to see the data instantly in the portal, then LiveStream can help you.
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-live-stream

Let us know if you need more help.

**Comment by imeya** [comment]
thank you. Why it takes 2-5 mins to show on portal? does  the portal do something else?

**Comment by cijothomas** [comment]
The time is for the backend to ingest/process/index/store the data.
