### ISSUE TITLE
FW 4.0 application cannot load System.Threading

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-dotnet#97]
***From the customer issue report:***

We are trying to onboard to Application Insights for our asp.net application(.NET 4.0) which is running on Azure Cloud Services. We are running into issues while deploying the cspkg and\or while getting application start with application insights. It is happening because of version conflicts for System.Threading.Tasks which got added in our application because of AppInsights nuget package. This reference is needed for Microsoft.Bcl.Async and Microsoft.Bcl which are in turn used by AppInsights.

**Stepwise Problem description with workflow, status, options tried and current status:**

- Azure Web Role running ASP.NET application targetted for .NET 4.0 [Environment: OSFamily 2, .Net framework 4.0 with KB2468871           ]
                |
- Added with Application Insights + Application Insights TraceListener 
                |
- Installed Nuget Package Application Insights for Web Applications (.NET 4.0) 
                |
- which has dependency on 
                |
- Microsoft.Bcl.Async.1.0.168 -> Uses  Microsoft.Threading.Tasks.dll 1.0.168.0 -> which references-> System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 
                |
- which has dependency on
                |              
- Microsoft.Bcl.1.1.8 -> Which adds -> System.Threading.Tasks.dll  -> versions available in the package2.6.8.0 & 1.6.8.0
                |
- By default, 2.6.8.0 gets added reference to the project and gets copied to bin folder 
                |
- There is assembly redirect present in web.config of web application (Web Role) for System.Threading.Tasks.dll to redirect anything from 0.0.0.0 to 2.6.8.0. But WaIISHost.exe tries to start webrole and hence it does not consider assembly redirect of web.config of our application. 
                |
-   WaIISHost.exe 
                |
- RoleEntryPoint OnStart() -> if we try to set InstrumentationKey here(i.e. TelemetryConfiguration.Active.InstrumentationKey = RoleEnvironment.GetConfigurationSettingValue("Telemetry.AI.InstrumentationKey") runs into same exception) WebRole does not start because of Type: System.IO.FileLoadException for System.Threading.Tasks, Version=1.5.11.0. Check exception 1 attached. Same fusion log as below step
                |
- Moved that instrumenation key intialization code Global.asax.cs
                |
- Application_start() ->  if we try to set here, we run into .NET runtime error for loading System.Threading.Tasks.dll 1.5.11.0 which is required by Microsoft.Threading.Tasks.dll 1.0.168.0. Check Exception 2 attached.
                |
- Whenever Microsoft.Threading.Tasks.dll is tried to load, then it tries to load System.Threading.Tasks.dll 1.5.11.0 and hence runs into System.IO.FileLoadException.
                |
- Fusion log suggests Major Version mismatch since System.Threading.Tasks.dll 2.6.8.0 is available in approot\bin but Microsoft.Threading.Tasks.dll needs -> System.Threading.Tasks.dll 1.5.11.0
                |
Removing reference to 2.6.8.0 from solution and added 1.6.8.0 which was available in Microsoft.Bcl package but that results in Minor version mismatch and hence same FileLoadException.
                |
Looked into Issue 9 of http://blogs.msdn.com/b/bclteam/p/asynctargetingpackkb.aspx which looked similar but it does not seem to help in this case(since I can't find System.Threading.Tasks.dll 1.5.11.0 anywhere in pacakges or in GAC)
                |
Tried to search for 1.5.11.0 version of System.Threading.Tasks.dll in packages, nuget gallery, on internet but I could not find one.
                |
What's the suggested approach? When Azure WebRole running WEb application targetting .NET 4.0 adds Application Insights, It looks like "Application Insights for Web Application" for .NET 4.0 together with its nuget dependencies like (Microsoft.Bcl.Async and Microsoft.Bcl) causes conflicts of versions for System.Threading.Tasks.dll 1.5.11.0
                |
An option which I can think of is to write a startup task, which will copy these two different versioned dlls and Install them in GAC. When Startup tasks run, it will install both versions to GAC and Assembly Binder should find System.Threading.Tasks.dll 1.5.11.0 in GAC when application starts.
                |
For above option, I need 1.5.11.0 version of System.Threading.Tasks.dll which can't be found.

Please suggest known solutions if there are any or suggestions to get over this issue.

![image](https://cloud.githubusercontent.com/assets/9950081/10926355/4b0a48da-824b-11e5-81de-13697f390b1e.png)

**Comment by SergeyKanzhelev** [comment]
We have the same report from people using WPF application. Microsoft.Bcl.Async binaries tries to load v2.0.5.0 of System.Net which fails as it cannot find it.

Adding of this config doesn't help either:

``` xml
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
      <assemblyIdentity name="System.Core" publicKeyToken="b77a5c561934e089" culture="neutral" />
      <bindingRedirect oldVersion="2.0.5.0" newVersion="4.0.0.0" />
    </dependentAssembly>
    <dependentAssembly>
      <assemblyIdentity name="System.Net" publicKeyToken="7cec85d7bea7798e" culture="neutral" />
      <bindingRedirect oldVersion="2.0.5.0" newVersion="4.0.0.0" />
    </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by SergeyKanzhelev** [comment]
It is a known issue that before [kb 2468871](https://support.microsoft.com/en-us/kb/2468871) update for Framework 4.0 BCL libraries didn't work properly. However it is reported that failure happens even when this KB was installed.

**Comment by SergeyKanzhelev** [comment]
@terrajobst do you have a suggestion how to further troubleshoot this issue? Are you the right person to ask?

**Comment by terrajobst** [comment]
@SergeyKanzhelev 

Thanks for the detailed write-up! The right person from our side is @ericstj.

**Comment by ShitalMehta** [comment]
Thanks Sergey and Eric for looking into this. Let us know if further information is needed from customer end

**Comment by ericstj** [comment]
Your setup will require bindingRedirects.  For simple exes these go in <app>.exe.config.  Host processes have special requirements for providing runtime config since they are the ones that initialize .net on behalf of your code.  I believe that azure hosts' convention is <name>.dll.config.  You should be able to find some examples by searching for the name of your host and dll.config.

Those redirects you listed are not for the correct assemblies.  It looks to me like those are someone trying to solve running silver light references on .net 4.0.  Binding redirects don't work for those assemblies because they had different public keys.  That specific support was added with the KB.

Once you have the KB you still need to ensure the host is setting up the CLR correctly.  You should be able to see what config the host is using in the fusion logs.  You can also enable clr load logging to help debug.

Worst case you can hook the assemblyresolve event, but that should only be the last option if you cannot get your host process to initialize the framework correctly.
