### ISSUE TITLE
upgrade via NuGet should add bindingRedirect

### ISSUE THREAD

**Issue by pbolduc** [Microsoft/ApplicationInsights-dotnet#98]
When upgrading using NuGet packages, the package should add bindingRedirect to app.config/web.config to prevent assembly load failures.

      <dependentAssembly>
        <assemblyIdentity name="Microsoft.ApplicationInsights" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.0.5639" newVersion="1.2.0.5639" />
      </dependentAssembly>

**Comment by SergeyKanzhelev** [comment]
NuGet will do it automatically when you have a reference to the other project that in turn using older version of ```Microsoft.ApplicationInsight``` assembly. Do you have specific example when it fails to do it?

**Comment by pbolduc** [comment]
I upgraded one of my web projects yesterday. When I deployed it got a could not Application.Insights assembly.  I was on version 1.x and upgraded to the latest  1.2.  The web.config file did not get updated.  Let me see if I can find the time later today to go back to the previous version and reproduce the steps.

**Comment by SergeyKanzhelev** [comment]
Make sure you don't have "hidden" references to the older version of SDK. Here is an article explaining how [bindingRedirect works\(http://blog.davidebbo.com/2011/01/nuget-versioning-part-3-unification-via.html)

**Comment by pbolduc** [comment]
I believe the original packages were added using Visual Studio "Add Application Insights" right context menu item.  However, since adding <dependentAssembly> is a function of NuGet, not the package itself, I will close this issue.

**Comment by SergeyKanzhelev** [comment]
Thanks @pbolduc. You should definitely let us know even if it is NuGet error. 

BTW, "Add Application Insights" would just invoke NuGet installation, register new component and put instrumentation key into ```ApplicationInsights.config```. So from bindingRedirect perspective it is working exactly the same way as if you just call ```Install-Package Microsoft.ApplicationInsights.Web``` from package manager console.
