### ISSUE TITLE
Telemetry contains computer name

### ISSUE THREAD

**Issue by mediawolf** [Microsoft/ApplicationInsights-dotnet#990]
## Repro Steps
With default settings, the reported telemetry contains:
"ai.cloud.roleInstance": "COMPUTER-NAME",
When TelemetryClient.Context.Cloud.RoleInstance = "."
"ai.cloud.roleInstance": "."
but
"ai.internal.nodeName": "COMPUTER-NAME"
TelemetryContext.Internal has internal access so no way to specify NodeName.
## Expected Behavior
A possibility to control what PII is sent by the library. For instance, it could be an interface which implementation provides necessary details to TelemetryClient.

## Version Info 
SDK Version : 2.8.1
.NET Version :	4.7.1 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) : VisualStudio
OS : Win10
Hosting Info (IIS/Azure WebApps/ etc) : desktop application

**Comment by SergeyKanzhelev** [comment]
@mediawolf The best place for PII stripping is Telemetry Processor. Assumption is that by the time the processor is called telemetry event is fully initialized. Register one to clean up PII from roleInstance and internal nodeName.

To access internal context - call `GetInternalContext()` extension method on `TelemetryContext` class. It is intentionally hidden to avoid confusion and misuse, but absolutely supported.

**Comment by SergeyKanzhelev** [comment]
Please re-open if this doesn't answer your question
